### ISSUE TITLE
youtube.com: "unable to download video data: HTTP Error 403: Forbidden"

### ISSUE THREAD

**Issue by scrottie** [rg3/youtube-dl#6639] opened 2015-08-22 19:38 UTC
scott@Microknoppix:/tmp/music$ sudo youtube-dl -U

youtube-dl is up-to-date (2015.08.16.1)

youtube-dl --verbose 'http://youtu.be/zYKupOsaJmk'

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://youtu.be/zYKupOsaJmk']
[debug] Encodings: locale ISO-8859-1, fs ISO-8859-1, out None, pref ISO-8859-1
[debug] youtube-dl version 2015.08.16.1
[debug] Python version 2.7.10 - Linux-3.15.0-i686-with-debian-wheezy-sid
[debug] exe versions: avconv 1.0.9, avprobe 1.0.9, ffmpeg SVN-r19631-snapshot, ffprobe 1.0.9, rtmpdump 2.3
[debug] Proxy map: {}
[youtube] zYKupOsaJmk: Downloading webpage
[youtube] zYKupOsaJmk: Downloading video info webpage
[youtube] zYKupOsaJmk: Extracting video information
[youtube] {43} signature length 40.42, html5 player new
[youtube] {18} signature length 40.42, html5 player new
[youtube] {5} signature length 40.40, html5 player new
[youtube] {36} signature length 40.42, html5 player new
[youtube] {17} signature length 40.42, html5 player new
[youtube] {13} signature length 40.42, html5 player new
[youtube] {135} signature length 40.42, html5 player new
[youtube] {244} signature length 40.42, html5 player new
[youtube] {134} signature length 40.42, html5 player new
[youtube] {243} signature length 40.42, html5 player new
[youtube] {133} signature length 40.42, html5 player new
[youtube] {242} signature length 40.42, html5 player new
[youtube] {160} signature length 40.42, html5 player new
[youtube] {140} signature length 40.42, html5 player new
[youtube] {171} signature length 40.42, html5 player new
[youtube] zYKupOsaJmk: Downloading DASH manifest
WARNING: [youtube] zYKupOsaJmk: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
WARNING: Your copy of avconv is outdated and unable to properly mux separate video and audio files, youtube-dl will download single file media. Update avconv to version 10-0 or newer to fix this.
[debug] Invoking downloader on u'https://r5---sn-nwj7knls.googlevideo.com/videoplayback?itag=18&ipbits=0&key=yt5&pl=18&dur=214.482&sver=3&expire=1440293787&ratebypass=yes&gcr=us&initcwndbps=1121250&id=o-AKRxcBGtAAoniN5OeQsmgysQYEVt8RzC36-NnBeen7-x&upn=tmYDoKTZENo&lmt=1427905994301027&ip=108.167.63.151&sparams=dur%2Cgcr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&fexp=9408208%2C9408500%2C9408710%2C9409069%2C9409208%2C9410705%2C9412927%2C9415365%2C9415485%2C9415521%2C9415530%2C9416023%2C9416126%2C9417191%2C9417707%2C9418153%2C9418215%2C9418438%2C9418449%2C9418642%2C9419342&mt=1440272043&mv=m&ms=au&source=youtube&mime=video%2Fmp4&requiressl=yes&mm=31&mn=sn-nwj7knls&signature=D4EC49A68F52753FA24D0409E936FB0E8A68575F.A218A3D5F9328EE8BA0AB464F96339866A39A12F'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1585, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1527, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 60, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1860, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden

Thanks to the devs!

**Comment by dstftw** [comment] 2015-08-22 19:39
Duplicate of #6451. Remove cache with `youtube-dl --rm-cache-dir`.

**Closed by dstftw** 2015-08-22 19:39 UTC
