### ISSUE TITLE
Bug with 8tracks

### ISSUE THREAD

**Issue by raybesiga** [rg3/youtube-dl#8470] opened 2016-02-09 01:25 UTC
Hey guys,

Great work with Youtube-DL. I updated it and run the following command with the error output at the bottom. Any clue why this is happening?

```
➜  youtube-dl --verbose http://8tracks.com/chrisholoien/you-must-be-kidding
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://8tracks.com/chrisholoien/you-must-be-kidding']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.05.1
[debug] Python version 2.7.11 - Darwin-15.2.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[8tracks] you-must-be-kidding: Downloading webpage
[8tracks] you-must-be-kidding: Downloading song information 1/20
[8tracks] you-must-be-kidding: Downloading song information 2/20
[8tracks] you-must-be-kidding: Downloading song information 3/20
[8tracks] you-must-be-kidding: Downloading song information 4/20
[8tracks] you-must-be-kidding: Downloading song information 5/20
[8tracks] you-must-be-kidding: Waiting for 300 seconds
[8tracks] you-must-be-kidding: Downloading song information 5/20
[8tracks] you-must-be-kidding: Downloading song information 6/20
[8tracks] you-must-be-kidding: Waiting for 300 seconds
[8tracks] you-must-be-kidding: Downloading song information 6/20
[8tracks] you-must-be-kidding: Downloading song information 7/20
[8tracks] you-must-be-kidding: Waiting for 300 seconds
[8tracks] you-must-be-kidding: Downloading song information 7/20
[8tracks] you-must-be-kidding: Downloading song information 8/20
[8tracks] you-must-be-kidding: Waiting for 300 seconds
[8tracks] you-must-be-kidding: Downloading song information 8/20
[8tracks] you-must-be-kidding: Downloading song information 9/20
[8tracks] you-must-be-kidding: Waiting for 300 seconds
[8tracks] you-must-be-kidding: Downloading song information 9/20
[8tracks] you-must-be-kidding: Downloading song information 10/20
[8tracks] you-must-be-kidding: Waiting for 300 seconds
[8tracks] you-must-be-kidding: Downloading song information 10/20
[8tracks] you-must-be-kidding: Downloading song information 11/20
[8tracks] you-must-be-kidding: Waiting for 300 seconds
[8tracks] you-must-be-kidding: Downloading song information 11/20
[8tracks] you-must-be-kidding: Downloading song information 12/20
[8tracks] you-must-be-kidding: Waiting for 300 seconds
[8tracks] you-must-be-kidding: Downloading song information 12/20
[8tracks] you-must-be-kidding: Downloading song information 13/20
[8tracks] you-must-be-kidding: Waiting for 300 seconds
[8tracks] you-must-be-kidding: Downloading song information 13/20
[8tracks] you-must-be-kidding: Downloading song information 14/20
[8tracks] you-must-be-kidding: Waiting for 300 seconds
[8tracks] you-must-be-kidding: Downloading song information 14/20
[8tracks] you-must-be-kidding: Waiting for 300 seconds
[8tracks] you-must-be-kidding: Downloading song information 14/20
[8tracks] you-must-be-kidding: Downloading song information 15/20
[8tracks] you-must-be-kidding: Waiting for 300 seconds
[8tracks] you-must-be-kidding: Downloading song information 15/20
[8tracks] you-must-be-kidding: Downloading song information 16/20
[8tracks] you-must-be-kidding: Downloading song information 17/20
[8tracks] you-must-be-kidding: Downloading song information 18/20
[8tracks] you-must-be-kidding: Downloading song information 19/20
[8tracks] you-must-be-kidding: Waiting for 300 seconds
[8tracks] you-must-be-kidding: Downloading song information 19/20
ERROR: An extractor error has occurred. (caused by KeyError(u'id',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/raybesiga/.virtualenvs/youtube-dl/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 313, in extract
    return self._real_extract(url)
  File "/Users/raybesiga/.virtualenvs/youtube-dl/lib/python2.7/site-packages/youtube_dl/extractor/eighttracks.py", line 146, in _real_extract
    'id': compat_str(track_data['id']),
KeyError: u'id'
Traceback (most recent call last):
  File "/Users/raybesiga/.virtualenvs/youtube-dl/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/Users/raybesiga/.virtualenvs/youtube-dl/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 319, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'id',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Any help and feedback with this issue will be greatly appreciated. Cheers.

**Comment by dstftw** [comment] 2016-02-09 02:23
Duplicate of #5029.

**Closed by dstftw** 2016-02-09 02:23 UTC
