### ISSUE TITLE
Can't download playlist from youtube

### ISSUE THREAD

**Issue by duduke** [rg3/youtube-dl#5237] opened 2015-03-19 14:32 UTC
Running:
youtube-dl "https://www.youtube.com/watch?v=rSy0JtBCZMQ&list=ELOr7Kf5pv-m8" -v
results in an error:
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=rSy0JtBCZMQ&list=ELOr7Kf5pv-m8', '-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.15
[debug] Python version 2.7.9 - Linux-3.16.0-4-686-pae-i686-with-debian-8.0
[debug] exe versions: avconv 2.6, avprobe 2.6, ffmpeg 2.6, ffprobe 2.6, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist ELOr7Kf5pv-m8 - add --no-playlist to just download video rSy0JtBCZMQ
[youtube:playlist] ELOr7Kf5pv-m8: Downloading webpage
[download] Downloading playlist: Star Blazers: Season 1
[youtube:playlist] playlist Star Blazers: Season 1: Collected 26 video ids (downloading 26 of them)
[download] Downloading video 1 of 26
[youtube] rSy0JtBCZMQ: Downloading webpage
[youtube] rSy0JtBCZMQ: Downloading embed webpage
[youtube] rSy0JtBCZMQ: Refetching age-gated info webpage
[youtube] rSy0JtBCZMQ: Extracting video information
[youtube] RTMP download detected
[debug] Invoking downloader on u'rtmpe://v1.nonxt7.c.youtube.com/videoplayback'
[download] Destination: STAR BLAZERS Ep. 1 'The Battle At Pluto'-rSy0JtBCZMQ.unknown_video
[debug] rtmpdump command line: rtmpdump --verbose -r rtmpe://v1.nonxt7.c.youtube.com/videoplayback -o 'STAR BLAZERS Ep. 1 '"'"'The Battle At Pluto'"'"'-rSy0JtBCZMQ.unknown_video.part'
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : v1.nonxt7.c.youtube.com
[rtmpdump] DEBUG: Parsed app     : videoplayback
[rtmpdump] ERROR: You must specify a playpath (--playpath) or url (-r "rtmp://host[:port]/playpath") containing a playpath
ERROR: unable to download video
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1452, in download
    res = self.extract_info(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 665, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 824, in process_ie_result
    extra_info=extra)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 718, in process_ie_result
    extra_info=extra_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 665, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 711, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1153, in process_video_result
    self.process_info(new_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1390, in process_info
    raise UnavailableVideoError(err)
UnavailableVideoError: [Errno 2] No such file or directory: "STAR BLAZERS Ep. 1 'The Battle At Pluto'-rSy0JtBCZMQ.unknown_video.part"

Although other playlists work...

**Comment by dstftw** [comment] 2015-03-19 14:42
Duplicate of #1797.

**Closed by dstftw** 2015-03-19 14:42 UTC
