### ISSUE TITLE
[youtube.com] Unable to download some videos

### ISSUE THREAD

**Issue by Goothaa4** [rg3/youtube-dl#14027] opened 2017-08-25 23:12 UTC
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.23**
user@localhost:~$ youtube-dl --version
2017.08.23

- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

There doesn't seem to be any bugs like this already listed as of 25 Aug.

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

This is a bug report.

```
USER@LOCALHOST:~$ youtube-dl -v https://www.youtube.com/watch?v=6SJNVb0GnPI
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=6SJNVb0GnPI']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.23
[debug] Python version 2.7.12 - Linux-4.4.0-92-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 6SJNVb0GnPI: Downloading webpage
[youtube] 6SJNVb0GnPI: Downloading video info webpage
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1958, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1596, in _real_extract
ValueError: invalid literal for int() with base 10: ''

```

### Description of your *issue*, suggested solution and other information

This only seems to happen on some youtube videos. It hasn't happened before. I don't quite understand the output so I don't know what else to say about it.

**Comment by ftc2** [comment] 2017-08-26 00:43
youtube says for that video: 

> The following content has been identified by the YouTube community as inappropriate or offensive to some audiences.

https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/youtube.py#L1596

it looks like 'inappropriate' videos don't display viewcount. maybe missing viewcount isn't properly handled yet, and it's trying to do `int(None)` or something like that.

**Comment by Hrxn** [comment] 2017-08-26 00:46
Duplicate of #14029

**Closed** 2017-08-26 08:17 UTC
