### ISSUE TITLE
CBSNews ERROR: rtmpdump exited with code 1

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#8270] opened 2016-01-18 19:32 UTC
If I try this enough times it will occasionally work (one out of five-ish?)
I think this might be more of RTMP issue, than a CBSNews issue...but here is an example of a failure:

URL: http://www.cbsnews.com/news/sean-penn-surprising-moments-on-60-minutes/

OUTPUT:
C:\Transmogrifier>youtube-dl.py -v "http://www.cbsnews.com/news/sean-penn-surprising-moments-on-60-minutes/"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.cbsnews.com/news/sean-penn-surprising-moments-on-60-minutes/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.01.15
[debug] Python version 2.7.5 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71727-g46778ab, rtmpdump 2.4
[debug] Proxy map: {}
[CBSNews] sean-penn-surprising-moments-on-60-minutes: Downloading webpage
[debug] Invoking downloader on u'rtmp://cp98363.edgefcs.net/ondemand/?auth=cbs&aifp=v001&slist={slistPrefix}{break}{slistFilePath}media/2016/01/18/603481155885/0117_60Min_SeanPenn2016_483916_796.mp4{s
listFilePath}{manifest:f4m}http://cbsnews-vh.akamaihd.net/z/{slist::true:false}.csmil/manifest.f4m{manifest:m3u}http://cbsnews-vh.akamaihd.net/i/{slist::true:false}.csmil/master.m3u8{manifest}'
[download] Destination: Sean Penn's surprising moments on 60 Minutes-sean-penn-surprising-moments-on-60-minutes.flv
[debug] rtmpdump command line: rtmpdump --verbose -r 'rtmp://cp98363.edgefcs.net/ondemand/?auth=cbs&aifp=v001&slist={slistPrefix}{break}{slistFilePath}media/2016/01/18/603481155885/0117_60Min_SeanPenn
2016_483916_796.mp4{slistFilePath}{manifest:f4m}http://cbsnews-vh.akamaihd.net/z/{slist::true:false}.csmil/manifest.f4m{manifest:m3u}http://cbsnews-vh.akamaihd.net/i/{slist::true:false}.csmil/master.m
3u8{manifest}' -o 'Sean Penn'"'"'s surprising moments on 60 Minutes-sean-penn-surprising-moments-on-60-minutes.flv.part' --swfVfy 'http://www.cbsnews.com/[[IMPORT]]/vidtech.cbsinteractive.com/player/3
_3_0/CBSI_PLAYER_HD.swf' --pageUrl http://www.cbsnews.com --app 'ondemand?auth=cbs' --playpath mp4:media/2016/01/18/603481155885/0117_60Min_SeanPenn2016_483916_796.mp4 --resume --skip 1
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 0
[rtmpdump] DEBUG: Parsed host    : cp98363.edgefcs.net
[rtmpdump] DEBUG: Parsed app     : ondemand/?auth=cbs&aifp=v001&slist={slistPrefix}{break}{slistFilePath}media/2016/01/18/603481155885/0117_60Min_SeanPenn2016_483916_796.mp4{slistFilePath}{manifest:f4
m}http://cbsnews-vh.akamaihd.net/z/{slist::true:false}.csmil/manifest.f4m{manifest:m3u}http://cbsnews-vh.akamaihd.net/i/{slist::true:false}.csmil/master.m3u8{manifest}
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] ERROR: RTMP_HashSWF: couldn't contact swfurl http://www.cbsnews.com/[[IMPORT]]/vidtech.cbsinteractive.com/player/3_3_0/CBSI_PLAYER_HD.swf (HTTP error 301)
[rtmpdump] DEBUG: Protocol : RTMP
[rtmpdump] DEBUG: Hostname : cp98363.edgefcs.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:media/2016/01/18/603481155885/0117_60Min_SeanPenn2016_483916_796.mp4
[rtmpdump] DEBUG: tcUrl    : rtmp://cp98363.edgefcs.net:1935/ondemand?auth=cbs
[rtmpdump] DEBUG: swfUrl   : http://www.cbsnews.com/[[IMPORT]]/vidtech.cbsinteractive.com/player/3_3_0/CBSI_PLAYER_HD.swf
[rtmpdump] DEBUG: pageUrl  : http://www.cbsnews.com
[rtmpdump] DEBUG: app      : ondemand?auth=cbs
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:           duration, NUMBER:  77.40>
[rtmpdump] DEBUG: Property: <Name:       moovPosition, NUMBER:  40.00>
[rtmpdump] DEBUG: Property: <Name:              width, NUMBER:  640.00>
[rtmpdump] DEBUG: Property: <Name:             height, NUMBER:  360.00>
[rtmpdump] DEBUG: Property: <Name:       videocodecid, STRING:  avc1>
[rtmpdump] DEBUG: Property: <Name:       audiocodecid, STRING:  mp4a>
[rtmpdump] DEBUG: Property: <Name:         avcprofile, NUMBER:  66.00>
[rtmpdump] DEBUG: Property: <Name:           avclevel, NUMBER:  30.00>
[rtmpdump] DEBUG: Property: <Name:             aacaot, NUMBER:  2.00>
[rtmpdump] DEBUG: Property: <Name:     videoframerate, NUMBER:  29.97>
[rtmpdump] DEBUG: Property: <Name:    audiosamplerate, NUMBER:  48000.00>
[rtmpdump] DEBUG: Property: <Name:      audiochannels, NUMBER:  2.00>
[rtmpdump] DEBUG: Property: <Name:               tags, ECMA_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              ??too, STRING:  Lavf56.15.102>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: Property: <Name:          trackinfo, STRICT_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:             length, NUMBER:  927600.00>
[rtmpdump] DEBUG: Property: <Name:          timescale, NUMBER:  11988.00>
[rtmpdump] DEBUG: Property: <Name:           language, STRING:  und>
[rtmpdump] DEBUG: Property: <Name:  sampledescription, STRICT_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:         sampletype, STRING:  avc1>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:             length, NUMBER:  3715134.00>
[rtmpdump] DEBUG: Property: <Name:          timescale, NUMBER:  48000.00>
[rtmpdump] DEBUG: Property: <Name:           language, STRING:  und>
[rtmpdump] DEBUG: Property: <Name:  sampledescription, STRICT_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:         sampletype, STRING:  mp4a>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:             length, NUMBER:  6963963.00>
[rtmpdump] DEBUG: Property: <Name:          timescale, NUMBER:  90000.00>
[rtmpdump] DEBUG: Property: <Name:           language, STRING:  und>
[rtmpdump] DEBUG: Property: <Name:  sampledescription, STRICT_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:             length, NUMBER:  3718144.00>
[rtmpdump] DEBUG: Property: <Name:          timescale, NUMBER:  48000.00>
[rtmpdump] DEBUG: Property: <Name:           language, STRING:  und>
[rtmpdump] DEBUG: Property: <Name:  sampledescription, STRICT_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: File has duration: 77.399000
[rtmpdump] DEBUG: bAudioOnly: 0, size: 2944905
[rtmpdump] ERROR: Last tag size must be greater/equal zero (prevTagSize=-1987019234) and smaller then filesize, corrupt file!
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 2944905 bytes
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 0
[rtmpdump] DEBUG: Parsed host    : cp98363.edgefcs.net
[rtmpdump] DEBUG: Parsed app     : ondemand/?auth=cbs&aifp=v001&slist={slistPrefix}{break}{slistFilePath}media/2016/01/18/603481155885/0117_60Min_SeanPenn2016_483916_796.mp4{slistFilePath}{manifest:f4
m}http://cbsnews-vh.akamaihd.net/z/{slist::true:false}.csmil/manifest.f4m{manifest:m3u}http://cbsnews-vh.akamaihd.net/i/{slist::true:false}.csmil/master.m3u8{manifest}
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] ERROR: RTMP_HashSWF: couldn't contact swfurl http://www.cbsnews.com/[[IMPORT]]/vidtech.cbsinteractive.com/player/3_3_0/CBSI_PLAYER_HD.swf (HTTP error 301)
[rtmpdump] DEBUG: Protocol : RTMP
[rtmpdump] DEBUG: Hostname : cp98363.edgefcs.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:media/2016/01/18/603481155885/0117_60Min_SeanPenn2016_483916_796.mp4
[rtmpdump] DEBUG: tcUrl    : rtmp://cp98363.edgefcs.net:1935/ondemand?auth=cbs
[rtmpdump] DEBUG: swfUrl   : http://www.cbsnews.com/[[IMPORT]]/vidtech.cbsinteractive.com/player/3_3_0/CBSI_PLAYER_HD.swf
[rtmpdump] DEBUG: pageUrl  : http://www.cbsnews.com
[rtmpdump] DEBUG: app      : ondemand?auth=cbs
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:           duration, NUMBER:  77.40>
[rtmpdump] DEBUG: Property: <Name:       moovPosition, NUMBER:  40.00>
[rtmpdump] DEBUG: Property: <Name:              width, NUMBER:  640.00>
[rtmpdump] DEBUG: Property: <Name:             height, NUMBER:  360.00>
[rtmpdump] DEBUG: Property: <Name:       videocodecid, STRING:  avc1>
[rtmpdump] DEBUG: Property: <Name:       audiocodecid, STRING:  mp4a>
[rtmpdump] DEBUG: Property: <Name:         avcprofile, NUMBER:  66.00>
[rtmpdump] DEBUG: Property: <Name:           avclevel, NUMBER:  30.00>
[rtmpdump] DEBUG: Property: <Name:             aacaot, NUMBER:  2.00>
[rtmpdump] DEBUG: Property: <Name:     videoframerate, NUMBER:  29.97>
[rtmpdump] DEBUG: Property: <Name:    audiosamplerate, NUMBER:  48000.00>
[rtmpdump] DEBUG: Property: <Name:      audiochannels, NUMBER:  2.00>
[rtmpdump] DEBUG: Property: <Name:               tags, ECMA_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              ??too, STRING:  Lavf56.15.102>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: Property: <Name:          trackinfo, STRICT_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:             length, NUMBER:  927600.00>
[rtmpdump] DEBUG: Property: <Name:          timescale, NUMBER:  11988.00>
[rtmpdump] DEBUG: Property: <Name:           language, STRING:  und>
[rtmpdump] DEBUG: Property: <Name:  sampledescription, STRICT_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:         sampletype, STRING:  avc1>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:             length, NUMBER:  3715134.00>
[rtmpdump] DEBUG: Property: <Name:          timescale, NUMBER:  48000.00>
[rtmpdump] DEBUG: Property: <Name:           language, STRING:  und>
[rtmpdump] DEBUG: Property: <Name:  sampledescription, STRICT_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:         sampletype, STRING:  mp4a>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:             length, NUMBER:  6963963.00>
[rtmpdump] DEBUG: Property: <Name:          timescale, NUMBER:  90000.00>
[rtmpdump] DEBUG: Property: <Name:           language, STRING:  und>
[rtmpdump] DEBUG: Property: <Name:  sampledescription, STRICT_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:             length, NUMBER:  3718144.00>
[rtmpdump] DEBUG: Property: <Name:          timescale, NUMBER:  48000.00>
[rtmpdump] DEBUG: Property: <Name:           language, STRING:  und>
[rtmpdump] DEBUG: Property: <Name:  sampledescription, STRICT_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: File has duration: 77.399000
[rtmpdump] DEBUG: bAudioOnly: 0, size: 2944905
[rtmpdump] ERROR: Last tag size must be greater/equal zero (prevTagSize=-1987019234) and smaller then filesize, corrupt file!
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.

ERROR: rtmpdump exited with code 1
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Transmogrifier\youtube-dl.py\__main__.py", line 19, in <module>
    youtube_dl.main()
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\__init__.py", line 410, in main
    _real_main(argv)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\__init__.py", line 400, in _real_main
    retcode = ydl.download(all_urls)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 1677, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 676, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 722, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 1347, in process_video_result
    self.process_info(new_info)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 1609, in process_info
    success = dl(filename, info_dict)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 1551, in dl
    return fd.download(name, info)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\downloader\common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\downloader\rtmp.py", line 202, in real_download
    self.report_error('rtmpdump exited with code %d' % retval)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\downloader\common.py", line 155, in report_error
    self.ydl.report_error(*args, **kargs)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 540, in report_error
    self.trouble(error_message, tb)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 502, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

FWIW...if I set it to -f RtmpMobileLow it will work better, but if I set to -f best seems to fail like above

Thanks
Ringo

**Comment by yan12125** [comment] 2016-01-26 07:51
I doubt it's due to out-dated rtmpdmp. Could your compile the latest rtmpdump (git commit fa8646daeb19dfd12c181f7d19de708d623704c0 on 2015/12/24) and try again?

**Comment by remitamine** [comment] 2016-01-26 09:33
i don't think the problem is in rtmp.
the link looks wrong: rtmp://cp98363.edgefcs.net/ondemand/?auth=cbs&aifp=v001&slist={slistPrefix}{break}{slistFilePath}media/2016/01/18/603481155885/0117_60Min_SeanPenn
2016_483916_796.mp4{slistFilePath}{manifest:f4m}http://cbsnews-vh.akamaihd.net/z/{slist::true:false}.csmil/manifest.f4m{manifest:m3u}http://cbsnews-vh.akamaihd.net/i/{slist::true:false}.csmil/master.m
3u8{manifest}

i think i will open a PR to fix this problem(https://github.com/rg3/youtube-dl/pull/8295#issuecomment-173830445) so i can extract better formats and metadata and fix the problem here https://github.com/rg3/youtube-dl/commit/220ee33f2b8a22d2fe992c26b32a046b77ce2a4a#commitcomment-15629846.

**Comment by remitamine** [comment] 2016-01-26 16:56
i created i PR to fix the first problem if it's accepted.
i will continue to fix the second problem.

**Comment by remitamine** [comment] 2016-01-27 18:26
this will be fixed in the next version.

**Closed** 2016-01-27 18:27 UTC

**Comment by RingoTheDog** [comment] 2016-01-27 18:49
AMAZING!
Thank you......
