### ISSUE TITLE
Execute youtube-dl with a faststart flag

### ISSUE THREAD

**Issue by alexbudin** [rg3/youtube-dl#5071] opened 2015-02-26 14:41 UTC
Where can i add the "faststart" flag in the source code or in the command line to get the moov atom at the beginning of the file?

I need this ASAP and its only for a youtube clip and only with ffmpeg.

I just need to know what file i can add that in.

Thank you.

Alex

**Comment by jaimeMF** [comment] 2015-02-26 14:49
Use the `--exec` option with this `faststart.sh` script:
```sh
#!/bin/sh

VIDEO=$1
TEMPFILE=$VIDEO.temp
mv "$VIDEO" "$TEMPFILE"

ffmpeg -i "$TEMPFILE" -c copy -movflags faststart "$VIDEO"
rm "$TEMPFILE"
```

You just need to run `youtube-dl URL --exec './faststart.sh {}'`
(Closing as a duplicate of #5071)

**Comment by phihag** [comment] 2015-02-26 14:50
If there's something wrong with the videos that youtube-dl downloads, please [say so](https://github.com/rg3/youtube-dl/blob/master/CONTRIBUTING.md#is-there-enough-context-in-your-bug-report) - I'd rather fix the problem for all users instead of one.

**Closed by jaimeMF** 2015-02-26 14:49 UTC

**Comment by alexbudin** [comment] 2015-02-26 15:05
It would be SO USEFUL to the the option of "faststart" so that the index can be at the begining of the file, making the file playable as you download it.

**Comment by alexbudin** [comment] 2015-02-26 15:09
@jaimeMF Thank you for your help. Isnt the script that you wrote executed after youtube-dl finishes? I am using youtube-dl on a livestream and it works fine, but because it creates a .part file that doesnt have the index (moov atom is missing) i cannot read that file with ffmpeg while its downloading...

I basically want to be able to grab snippets from that file (that is downloading in real time from the live stream) with ffmpeg, but because ffmpeg doesnt find a moov atom on it, it doesnt work.

**Comment by alexbudin** [comment] 2015-02-26 15:22
@jaimeMF @phihag Is what i described above doable?

Also can i download the youtube video on another format like raw h264 stream ? so i can play it even if its not completed?

Thank you.

**Comment by phihag** [comment] 2015-02-26 15:26
Next time, please be [upfront about what you want to do](https://github.com/rg3/youtube-dl/blob/master/CONTRIBUTING.md#is-there-enough-context-in-your-bug-report) - that way, we can help you better.

Judging from the updated post and [this cross-posting](http://stackoverflow.com/q/28742775/35070), it seems like you don't really care about moov in the first place, but want to extract part of a video. So feel free to [open a new issue](https://github.com/rg3/youtube-dl/issues/new) with a *detailed* explanation of your use case. At least, you should say:

* What you want to do in the greater scheme of things; this should include the error message and the name of the video player you're using.
* Which service you're interested in - our suggestions or improvements may depend on the service implementations as well as the streaming protocol.
* When do you know what part of the video you want (apparently during streaming)
* What other considerations there are (i.e. do you need the original file untouched? Do you want to stop or continue downloading?)
* How you identify the part of the video you're interested in - by absolute time, by time from now, by frame count, by byte count, or ...

**Comment by alexbudin** [comment] 2015-02-26 15:35
@phihag I am sorry for this but i thought i explained it on here very well.

http://stackoverflow.com/questions/28742775/how-to-extract-a-video-snippet-from-a-video-file-that-is-being-written-in-by-ffm

I am recording a live stream with youtube-dl and i want from time to time to get a video snippet from the created file (while the recording hasnt finished yet).

I have found out that when doing recordings with ffmpeg you can make it so the index (moov atom) is being continuously written at the beginning of the file so that at any time you can get the partial file and it will play.

Does that explain it better?

Can you help?

Thank you.

Alex
