### ISSUE TITLE
Error in downloading from youtube - RTMPe

### ISSUE THREAD

**Issue by karthik167** [rg3/youtube-dl#3480] opened 2014-08-10 08:59 UTC
Hi,
I am not able to download https://www.youtube.com/movie?v=IYZEu01yy-0

Find attached screenshot of the details. I am using WinXP 32bit, SP3

![errorscrenshot](https://cloud.githubusercontent.com/assets/8407329/3868892/94849912-206c-11e4-9228-bde8bd66ab11.PNG)

**Comment by dstftw** [comment] 2015-03-19 14:43
Duplicate of #1797.

**Closed by dstftw** 2015-03-19 14:43 UTC
