### ISSUE TITLE
Unable to extract ref_path for miomio.tv

### ISSUE THREAD

**Issue by SamuSoft** [rg3/youtube-dl#9680] opened 2016-06-03 08:46 UTC
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.06.02*. 
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Bug Report: 
```
$ youtube-dl -v http://www.miomio.tv/watch/cc273997/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.miomio.tv/watch/cc273997/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.02
[debug] Python version 2.7.11 - Darwin-15.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.0.2, ffprobe 3.0.2
[debug] Proxy map: {}
[miomio.tv] 273997: Downloading webpage
ERROR: Unable to extract ref_path; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/miomio.py", line 53, in _real_extract
    r'src="(/mioplayer/[^"]+)"', webpage, 'ref_path')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 644, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract ref_path; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

### Description:
youtube-dl throws an "Unable to extract ref_path" error when passed miomio.tv links. This problem is not present for other tested sites, such as DailyMotion

**Comment by dstftw** [comment] 2016-06-03 08:51
Duplicate of #9605.

**Closed by dstftw** 2016-06-03 08:51 UTC
