### ISSUE TITLE
Skipping DASH manifest: ExtractorError(u'Failed to download MPD manifest: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by roytam1** [rg3/youtube-dl#9211] opened 2016-04-16 13:49 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.04.13*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.13**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-f', u'best', u'-u', u'PRIVATE', u'--verbose', u'https://www.youtube.com/watch?v=XdhCFGPTZGw']
Type account password and press [Return]:
[debug] Encodings: locale cp950, fs mbcs, out cp950, pref cp950
[debug] youtube-dl version 2016.04.13
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: avconv v12_dev0-2597-g9d4d9be, ffmpeg N-79460-g21acc4d
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Logging in
[youtube] XdhCFGPTZGw: Downloading webpage
[youtube] XdhCFGPTZGw: Downloading video info webpage
[youtube] XdhCFGPTZGw: Extracting video information
[youtube] {53} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {60} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {52} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {146} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {197} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {226} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {227} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {145} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {196} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {224} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {225} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {144} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {195} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {220} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {221} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {222} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {223} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {143} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {194} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {142} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {161} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {148} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {149} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {150} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {198} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {199} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] XdhCFGPTZGw: Downloading MPD manifest
[youtube] XdhCFGPTZGw: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vflg4mKgv/base.js
[youtube] XdhCFGPTZGw: Downloading MPD manifest
WARNING: [youtube] XdhCFGPTZGw: Skipping DASH manifest: ExtractorError(u'Failed to download MPD manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[debug] Invoking downloader on u'https://r3---sn-i3b7kn7z.c.youtube.com/videoplayback?ipbits=8&ctier=A&hcs=yes&key=yt6&hightc=yes&gcr=hk&mn=sn-i3b7kn7z&mm=30&ip=<IP>&pl=18&dur=6227.777&mv=m&mt=1460813842&ms=nxu&itag=53&initcwndbps=7357500&sparams=cp%2Cctier%2Cdur%2Cgcr%2Chcs%2Chightc%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpfa%2Cpl%2Cratebypass%2Crequiressl%2Cshardbypass%2Csource%2Cupn%2Cexpire&cp=U0lVRVhOU19GSkNPNV9QSFdGOktGN3UxLXNuU0dX&id=o-APu7xt1HvoQiDdUao-wZQqP2obJZBzTUSrNjide1cn1C&requiressl=yes&mime=video%2Fmp4&pfa=5&lmt=1460690992949166&fexp=9408522%2C9416126%2C9416891%2C9420452%2C9422342%2C9422596%2C9426926%2C9428209%2C9428398%2C9429609%2C9431012%2C9431103%2C9431579%2C9432055%2C9433097%2C9433312%2C9434250&expire=1460835510&nh=IgpwcjA0LmhrZzAxKgkxMjcuMC4wLjE&ratebypass=yes&shardbypass=yes&source=youtube&upn=JbuCjmk0iRs&sver=3&signature=DF078A5672E0D7EA262F306DF7C9B9F44CC922CF.5023D72DCC82AB586723EAFE485D318BA652F440'
[download] Destination: PRIVATE-XdhCFGPTZGw.mp4
[download] 100% of 1017.57MiB in 01:32

C:\Users\Roy\Desktop>youtube-dl -U
youtube-dl is up-to-date (2016.04.13)
...
<end of log>
```

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

I bought a movie from youtube and I found that plays with black screen, seems to be encrypted.
How can I decrypt it for playing in media player?

**Comment by dstftw** [comment] 2016-09-03 21:08
Duplicate of #8944.

**Closed by dstftw** 2016-09-03 21:08 UTC
Labels: geo-restricted
