### ISSUE TITLE
can't download anymore

### ISSUE THREAD

**Issue by bslanbt** [rg3/youtube-dl#6583] opened 2015-08-16 18:54 UTC
$ ./youtube-dl --verbose https://www.youtube.com/watch?v=vjW8wmF5VWc
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=vjW8wmF5VWc']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2015.08.16
[debug] Python version 2.6.6 - Linux-2.6.32-042stab090.5-x86_64-with-debian-6.0.10
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] vjW8wmF5VWc: Downloading webpage
[youtube] vjW8wmF5VWc: Downloading video info webpage
[youtube] vjW8wmF5VWc: Extracting video information
[youtube] {22} signature length 40.42, html5 player new
[youtube] {43} signature length 40.42, html5 player new
[youtube] {18} signature length 40.42, html5 player new
[youtube] {5} signature length 40.42, html5 player new
[youtube] {36} signature length 40.42, html5 player new
[youtube] {17} signature length 40.42, html5 player new
[youtube] {137} signature length 40.42, html5 player new
[youtube] {248} signature length 40.42, html5 player new
[youtube] {136} signature length 40.42, html5 player new
[youtube] {247} signature length 40.42, html5 player new
[youtube] {135} signature length 40.42, html5 player new
[youtube] {244} signature length 40.42, html5 player new
[youtube] {134} signature length 40.42, html5 player new
[youtube] {243} signature length 40.42, html5 player new
[youtube] {133} signature length 40.42, html5 player new
[youtube] {242} signature length 40.42, html5 player new
[youtube] {160} signature length 40.42, html5 player new
[youtube] {278} signature length 40.42, html5 player new
[youtube] {140} signature length 40.42, html5 player new
[youtube] {171} signature length 40.42, html5 player new
[youtube] {249} signature length 40.42, html5 player new
[youtube] {250} signature length 40.42, html5 player new
[youtube] {251} signature length 40.42, html5 player new
[youtube] vjW8wmF5VWc: Downloading DASH manifest
WARNING: [youtube] vjW8wmF5VWc: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[debug] Invoking downloader on u'https://r19---sn-p5qlsnlk.googlevideo.com/videoplayback?initcwndbps=1147500&shardbypass=yes&id=o-AOjsjeRbofmE1K4GcpYh27_sv-LKmzw2UYn9ylpU7U4c&ipbits=0&mm=31&mn=sn-p5qlsnlk&ms=au&mt=1439750982&mv=m&dur=202.431&ip=192.249.58.110&ratebypass=yes&itag=22&sparams=dur%2Cgcr%2Chcs%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Cratebypass%2Crequiressl%2Cshardbypass%2Csource%2Cupn%2Cexpire&key=yt5&nh=IgpwcjAxLmlhZDA3KgkxMjcuMC4wLjE&source=youtube&fexp=9407060%2C9408710%2C9409069%2C9415365%2C9415485%2C9416023%2C9416126%2C9417707%2C9418153&mime=video%2Fmp4&pl=23&lmt=1438353584294033&requiressl=yes&gcr=us&sver=3&hcs=yes&upn=wBVsGvzzC2M&expire=1439772655&signature=6BE0A7F4973067A17F3C0518CAE9E430C9928DA.CF00E79C581986082C024AD31C38AF67A57A008C'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1585, in process_info
    success = dl(filename, info_dict)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1527, in dl
    return fd.download(name, info)
  File "./youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "./youtube-dl/youtube_dl/downloader/http.py", line 60, in real_download
    data = self.ydl.urlopen(request)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1860, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.6/urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden

**Comment by dstftw** [comment] 2015-08-16 18:55
Duplicate of #6451. Remove cache with `youtube-dl --rm-cache-dir`.

**Closed by dstftw** 2015-08-16 18:55 UTC
