### ISSUE TITLE
Crunchyroll Error 500

### ISSUE THREAD

**Issue by kenichi512** [rg3/youtube-dl#12204] opened 2017-02-21 04:27 UTC
Hi.

1 hour ago I was downloading videos normally, but later this appeared when I started a new download.

```
[Crunchyroll] Downloading login page
ERROR: Unable to download webpage: HTTP Error 500: Internal Server Error (caused
 by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure
you are using the latest version; type  youtube-dl -U  to update. Be sure to cal
l youtube-dl with the --verbose flag and include its complete output.
```
And also

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://www.crunchyroll.com/saint-seiya/episode-31-t
he-line-between-life-and-death-660159', '-u', 'PRIVATE', '-p', 'PRIVATE', '--use
r-agent', 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:51.0) Gecko/20100101 Firefox/5
1.0', '--cookies', 'cookies.txt', '--all-subs', '--hls-prefer-native', '--no-par
t', '--no-cache-dir', '-f', 'best[height=480]', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.01.29
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-81489-ga37e6dd, rtmpdump 2.4
[debug] Proxy map: {}
[Crunchyroll] Downloading login page
[Crunchyroll] 660159: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 500: Internal Server Error (caused
 by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure
you are using the latest version; type  youtube-dl -U  to update. Be sure to cal
l youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\bu
ild\youtube_dl\extractor\common.py", line 416, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\bu
ild\youtube_dl\YoutubeDL.py", line 2001, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_defau
lt
```

**Comment by Starsam80** [comment] 2017-02-21 04:33
This always happens sometimes, but try again in a hour or so and it will work again. It's also not youtube-dl fault either: 
![image](https://cloud.githubusercontent.com/assets/4411333/23150852/1d5e95aa-f7b4-11e6-9c6d-0b5eb5ef85dc.png)

**Comment by yan12125** [comment] 2017-02-21 05:58
Duplicate of #11572. See posts there for previous discussions.

**Closed by yan12125** 2017-02-21 05:58 UTC

**Comment by Starsam80** [comment] 2017-02-21 06:15
@yan12125 Actually, not quite. Yes, you get a error 503 when trying to access the _login_ page, but for some reason, crunchyroll also likes to throw 500 errors for _any_ page. The 500 error isn't cloudflares fault. My prediction is when crunchyroll is under load that it tends to throw 500 errors. It's _very_ random and only lasts for about an hour from what I've experienced.

**Comment by yan12125** [comment] 2017-02-21 06:20
Oops, I didn't see the second log. The first log fails at the login page, so I thought it's a duplicate.

> My prediction is when crunchyroll is under load that it tends to throw 500 errors

That's possible. Anyway that's not youtube-dl's fault.
