### ISSUE TITLE
[Vevo] HTTP Error 500: Internal Server Error (caused by HTTPError())

### ISSUE THREAD

**Issue by jsundram** [rg3/youtube-dl#8910] opened 2016-03-21 01:18 UTC
`$ youtube-dl http://www.vevo.com/watch/robert-schumann/Dichterliebe-Op-48-No-15-Aus-alten-Marchen-winkt-es/QM6MZ1432617 --verbose`
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.vevo.com/watch/robert-schumann/Dichterliebe-Op-48-No-15-Aus-alten-Marchen-winkt-es/QM6MZ1432617', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.18
[debug] Python version 2.7.11 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 2.8.1, ffprobe 2.8.1
[debug] Proxy map: {}
[Vevo] QM6MZ1432617: Downloading video info
ERROR: Unable to download info: HTTP Error 500: Internal Server Error (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 365, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1929, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Users/jsundram/anaconda/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/Users/jsundram/anaconda/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Users/jsundram/anaconda/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/Users/jsundram/anaconda/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/Users/jsundram/anaconda/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

**Comment by dstftw** [comment] 2016-03-21 03:18
Duplicate of #8900.

**Closed by dstftw** 2016-03-21 03:18 UTC
