### ISSUE TITLE
youtube-dl cannot login to lynda.com

### ISSUE THREAD

**Issue by frankkoch** [rg3/youtube-dl#7364] opened 2015-11-04 18:31 UTC
Does anybody know why I cannot log into Lynda.com?

C:\youtube-dl http://www.lynda.com/Access-tutorials/Access-2013-Essenti
al-Training/115857-2.html --username aaa@bbb.ccc --password secret --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.lynda.com/Access-tutorials/Access-2013-
Essential-Training/115857-2.html', u'--username', u'PRIVATE', u'--password', u'P
RIVATE', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.11.02
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[lynda:course] Logging in as aaa@bbb.ccc
[lynda:course] 115857: Downloading course JSON
[download] Downloading playlist: Access 2013 Essential Training
[lynda:course] playlist Access 2013 Essential Training: Collected 84 video ids (
downloading 84 of them)
[download] Downloading video 1 of 84
[lynda] Logging in as aaa@bbb.ccc
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Mak
e sure you are using the latest version; type  youtube-dl -U  to update. Be sure
 to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 661, in extract_info
  File "youtube_dl\extractor\common.pyo", line 289, in extract
  File "youtube_dl\extractor\common.pyo", line 283, in initialize
  File "youtube_dl\extractor\lynda.pyo", line 25, in _real_initialize
  File "youtube_dl\extractor\lynda.pyo", line 83, in _login
ExtractorError: Unable to log in; please report this issue on https://yt-dl.org/
bug . Make sure you are using the latest version; type  youtube-dl -U  to update
. Be sure to call youtube-dl with the --verbose flag and include its complete ou
tput.

**Comment by dstftw** [comment] 2015-11-04 19:30
Duplicate of #7361.

**Closed by dstftw** 2015-11-04 19:30 UTC
