### ISSUE TITLE
Not working on Windows.

### ISSUE THREAD

**Issue by danfiscus** [rg3/youtube-dl#9529] opened 2016-05-18 00:33 UTC
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.16**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
C:\Users\Dan Fiscus>youtube-dl -v https://www.youtube.com/watch?v=XOILpU4GXXw
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\py2exe\boot_common.py", line 92, in <module>
ImportError: No module named linecache
Traceback (most recent call last):
  File "<install zipextimporter>", line 1, in <module>
ImportError: No module named zipextimporter
Traceback (most recent call last):
  File "__main__.py", line 2, in <module>
ImportError: No module named __future__

```

---

### Description of your *issue*, suggested solution and other information
I downloaded the .exe file and put it in my path and that is what happens when I run it. I have installed Python. I tried this on two different computers and I have had the same problem with both. Both are running Windows 10.

**Comment by yan12125** [comment] 2016-05-18 01:27
Duplicate of #8397, though nobody knows the exact cause yet.

> I have installed Python.

Could you try again without an installed Python? youtube-dl.exe comes with Python and the system Python may confuse it.

**Comment by danfiscus** [comment] 2016-05-18 14:05
@yan12125 I apologize for the late response, I couldn't get my laptop working last night so I had to wait until I had access to another Windows machine. Without installing Python, I get the exact same error message.

**Comment by yan12125** [comment] 2016-05-18 16:03
If it's not related to Python maybe it's related to #2919. Do you have Cyrillic characters (or other non-ASCII characters) in the path?

**Comment by danfiscus** [comment] 2016-05-18 21:02
@yan12125 How do I find that out?

**Comment by yan12125** [comment] 2016-05-19 04:12
For example in #2919:

C:\Users\Минка\Desktop>

The username contains Cyrillic characters, which causes youtube-dl to fail.

**Comment by danfiscus** [comment] 2016-05-19 11:19
@yan12124 No, my home folder is just Dan

**Comment by yan12125** [comment] 2016-05-19 11:22
Definitely strange. I'm afraid I can't help more as I can't reproduce it.

**Comment by yan12125** [comment] 2016-05-19 11:33
Also related: #3065 - youtube-dl.exe fails to start if placed in \Windows\system32.

**Comment by danfiscus** [comment] 2016-05-19 13:02
@yan12125 I have the binary placed in that folder, since the installation guide only says to put it in the "path" and I am somewhat new to windows after spending years on mac, so I just Googled path folders and put it in that one. Where should I place it?

**Comment by yan12125** [comment] 2016-05-19 13:19
@phihag's tutorial is useful: https://github.com/rg3/youtube-dl/issues/3065#issuecomment-45716079

**Closed by yan12125** 2016-05-19 13:19 UTC
Labels: cant-reproduce
