### ISSUE TITLE
Certificate verify failed _ssl.c:590

### ISSUE THREAD

**Issue by sogen** [rg3/youtube-dl#7650] opened 2015-11-25 16:43 UTC
youtube is throwing this error.
Using latest (11.24) version

Example:
youtube-dl -v https://www.youtube.com/watch?v=tFnClnkTKro

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=tFnClnkTKro']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.11.24
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {'ftp': 'ftp://192.168.7.3:8080', 'http': 'http://192.168.7.3:8080', 'https': 'https://192.168.7.3:8080'}
[youtube] tFnClnkTKro: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)> (caused by URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))
  File "youtube_dl\extractor\common.pyo", line 329, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1878, in urlopen
  File "urllib2.pyo", line 431, in open
  File "urllib2.pyo", line 449, in _open
  File "urllib2.pyo", line 409, in _call_chain
  File "youtube_dl\utils.pyo", line 805, in https_open
  File "urllib2.pyo", line 1197, in do_open

**Comment by jaimeMF** [comment] 2015-11-25 18:56
Duplicate of #7309, the unsafe workaround is to use `--no-check-certificate`.

**Closed by jaimeMF** 2015-11-25 18:56 UTC
