### ISSUE TITLE
Unable to get Vimeo video (youtube-dl version 2015.11.10)

### ISSUE THREAD

**Issue by tammytang** [rg3/youtube-dl#7463] opened 2015-11-12 04:19 UTC
youtube-dl.exe --verbose --get-url https://vimeo.com/channels/staffpicks/145366920
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--get-url', u'https://vimeo.com/channels/staffpicks/145366920']
[debug] Encodings: locale cp950, fs mbcs, out cp950, pref cp950
[debug] youtube-dl version 2015.11.10
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\extractor\vimeo.pyo", line 378, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 584, in _search_regex
RegexNotFoundError: Unable to extract view count; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 661, in extract_info
  File "youtube_dl\extractor\common.pyo", line 290, in extract
  File "youtube_dl\extractor\vimeo.pyo", line 427, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 766, in _sort_formats
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by YuheiNakasaka** [comment] 2015-11-12 06:21
This bug is fixed if video_upload_date is None.
https://github.com/YuheiNakasaka/youtube-dl/blob/fix-vimeo/youtube_dl/extractor/vimeo.py#L378

**Comment by dstftw** [comment] 2015-11-12 06:34
@YuheiNakasaka totally unrelated.
Duplicate of #7460.

**Closed by dstftw** 2015-11-12 06:34 UTC
