### ISSUE TITLE
hotstar urls not downloading

### ISSUE THREAD

**Issue by chumma12** [rg3/youtube-dl#9223] opened 2016-04-17 06:42 UTC
I am trying to download the video from this URL
http://www.hotstar.com/tv/ilaiyaraaja-aayiram/7361/tribute-to-ilayaraja/1000084729

and it is giving me this error

pi@192.168.1.30(12:09:55) ~ $ sudo youtube-dl -U
youtube-dl is up-to-date (2016.04.13)

pi@192.168.1.30(12:10:15) ~ $ youtube-dl --verbose http://www.hotstar.com/tv/ilaiyaraaja-aayiram/7361/tribute-to-ilayaraja/1000084729
[debug] System config: []
[debug] User config: [u'-o', u'~/data/Youtube/%(title)s-{%(id)s}.%(ext)s', u'--write-srt', u'--srt-lang', u'en,en-GB', u'--sub-format', u'srt', u'--convert-subs', u'srt', u'--format', u'mp4', u'--user-agent', u'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0', u'--referer', u'https://www.youtube.com']
[debug] Command-line args: [u'--verbose', u'http://www.hotstar.com/tv/ilaiyaraaja-aayiram/7361/tribute-to-ilayaraja/1000084729']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.13
[debug] Python version 2.7.9 - Linux-4.1.18-v7+-armv7l-with-debian-8.0
[debug] exe versions: none
[debug] Proxy map: {}
[HotStar] 1000084729: Downloading JSON metadata
[HotStar] 1000084729: Downloading TABLET JSON metadata
[HotStar] 1000084729: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 671, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/hotstar.py", line 74, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 862, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by remitamine** [comment] 2016-04-22 10:39
works fine for me(i added the user agent and referrer your config):
```
youtube-dl --user-agent 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0' --referer 'https://www.youtube.com' -v --ignore-config http://www.hotstar.com/tv/ilaiyaraaja-aayiram/7361/tribute-to-ilayaraja/1000084729
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--user-agent', 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0', '--referer', 'https://www.youtube.com', '-v', '--ignore-config', 'http://www.hotstar.com/tv/ilaiyaraaja-aayiram/7361/tribute-to-ilayaraja/1000084729']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.19
[debug] Lazy loading extractors enabled
[debug] Python version 3.5.1 - Linux-4.5.0-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.0.1, ffprobe 3.0.1, rtmpdump 2.4
[debug] Proxy map: {}
[HotStar] 1000084729: Downloading JSON metadata
[HotStar] 1000084729: Downloading TABLET JSON metadata
[HotStar] 1000084729: Downloading m3u8 information
[debug] Invoking downloader on 'https://staragvod2-vh.akamaihd.net/i/videos/vijay/ilaa/1/1000084729_,16,180,400,800,1300,2000,_STAR.mp4.csmil/index_5_av.m3u8?null=0&id=AgBpbjOPWN3qBrv+GVeTaEGDotSmCbFUnekerscQiC58CMCG6fRlCraevwhmNe0GZ9gyf4z1txJP0g%3d%3d'
[download] Destination: Tribute To Ilayaraja-1000084729.mp4
[debug] ffmpeg command line: ffmpeg -y -headers 'User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Cookie: _alid_=OZt4WnbXzyoNM2KvPw0Cqw==; hdntl=exp=1461407803~acl=%2f*~data=hdntl~hmac=cbba3e484780d02b754efb11c9fc63b6d2511ae13488366f30649d0ff68ad9a8
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
Referer: https://www.youtube.com
' -i 'https://staragvod2-vh.akamaihd.net/i/videos/vijay/ilaa/1/1000084729_,16,180,400,800,1300,2000,_STAR.mp4.csmil/index_5_av.m3u8?null=0&id=AgBpbjOPWN3qBrv+GVeTaEGDotSmCbFUnekerscQiC58CMCG6fRlCraevwhmNe0GZ9gyf4z1txJP0g%3d%3d' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:Tribute To Ilayaraja-1000084729.mp4.part'
ffmpeg version 3.0.1 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.3.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-avresample --enable-fontconfig --enable-gnutls --enable-gpl --enable-ladspa --enable-libass --enable-libbluray --enable-libdcadec --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-shared --enable-version3 --enable-x11grab
  libavutil      55. 17.103 / 55. 17.103
  libavcodec     57. 24.102 / 57. 24.102
  libavformat    57. 25.100 / 57. 25.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 31.100 /  6. 31.100
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
[h264 @ 0x55e234518c80] non-existing SPS 0 referenced in buffering period
    Last message repeated 1 times
[h264 @ 0x55e23433ff20] non-existing SPS 0 referenced in buffering period
Input #0, hls,applehttp, from 'https://staragvod2-vh.akamaihd.net/i/videos/vijay/ilaa/1/1000084729_,16,180,400,800,1300,2000,_STAR.mp4.csmil/index_5_av.m3u8?null=0&id=AgBpbjOPWN3qBrv+GVeTaEGDotSmCbFUnekerscQiC58CMCG6fRlCraevwhmNe0GZ9gyf4z1txJP0g%3d%3d':
  Duration: 00:42:08.88, start: 0.100667, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 63 kb/s
Output #0, mp4, to 'file:Tribute To Ilayaraja-1000084729.mp4.part':
  Metadata:
    encoder         : Lavf57.25.100
    Stream #0:0: Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac (LC) ([64][0][0][0] / 0x0040), 48000 Hz, stereo, 63 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=   23 fps=0.0 q=-1.0 size=     172kB time=00:00:00.89 bitrate=1576.5kbits/frame=   24 fps=9.3 q=-1.0 size=     193kB time=00:00:01.02 bitrate=1540.9kbits/frame=   45 fps= 15 q=-1.0 size=     404kB time=00:00:01.81 bitrate=1823.5kbits/frame=   49 fps= 14 q=-1.0 size=     434kB time=00:00:01.94 bitrate=1832.3kbits/^Cframe=   50 fps=6.0 q=-1.0 Lsize=     457kB time=00:00:02.00 bitrate=1865.1kbits/s speed=0.24x    
video:440kB audio:14kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.552089%
Exiting normally, received signal 2.

ERROR: Interrupted by user
```

**Comment by nilmanimitra** [comment] 2017-06-08 18:43
can you help me.........this error is occurring>>>>>
![drm](https://user-images.githubusercontent.com/29285886/26945108-698f68ca-4ca8-11e7-8622-7627a3bbd70c.jpg)
link is http://www.hotstar.com/tv/ilaiyaraaja-aayiram/7361/tribute-to-ilayaraja/1000084729

**Comment by nilmanimitra** [comment] 2017-06-08 18:43
another link is >>>http://www.hotstar.com/movies/chennai-express/1660010053

**Comment by remitamine** [comment] 2017-06-08 19:58
duplicate of #2641.
@nilmanimitra DRM protected video are not supported.

**Closed by remitamine** 2017-06-08 19:58 UTC
