### ISSUE TITLE
possible bug at discovery channel

### ISSUE THREAD

**Issue by murrayf** [rg3/youtube-dl#4621] opened 2015-01-02 14:14 UTC
youtube-dl --verbose http://www.discovery.com/tv-shows/edge-of-alaska/videos/the-last-stand/
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.discovery.com/tv-shows/edge-of-alaska/videos/the-last-stand/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.01
[debug] Python version 2.7.8 - Linux-3.17.7-300.fc21.x86_64-x86_64-with-fedora-21-Twenty_One
[debug] exe versions: none
[debug] Proxy map: {}
[Discovery] the-last-stand: Downloading webpage
ERROR: Unable to extract video list; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 592, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 243, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/discovery.py", line 32, in _real_extract
    webpage, 'video list', flags=re.DOTALL)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 489, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video list;
*************************************
Thanks and congratulations for youtube-dl!

Alberto.

:)

**Comment by dstftw** [comment] 2015-01-02 14:23
Duplicate of #4535.

**Closed by dstftw** 2015-01-02 14:23 UTC
