### ISSUE TITLE
Can't download stream from twitch.tv

### ISSUE THREAD

**Issue by PhenomSX** [rg3/youtube-dl#10657] opened 2016-09-15 04:32 UTC
J:\win-youtube-dl>youtube-dl -t --verbose https://www.twitch.tv/ahage2/v/89376127
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-t', '--verbose', 'https://www.twitch.tv/ahage2/v/8
9376127']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.09.11.1
[debug] Python version 3.4.4 - Windows-7-6.1.7600-SP0
[debug] exe versions: ffmpeg N-81609-g7b3bc36, ffprobe N-81609-g7b3bc36
[debug] Proxy map: {}
[twitch:vod] 89376127: Downloading vod info JSON
ERROR: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by
HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you
are using the latest version; type  youtube-dl -U  to update. Be sure to call yo
utube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj47q005f\bu
ild\youtube_dl\extractor\common.py", line 394, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj47q005f\bu
ild\youtube_dl\YoutubeDL.py", line 1998, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

**Comment by yan12125** [comment] 2016-09-15 04:38
Duplicate of #10654 and there's a seemingly good fix.

**Closed by yan12125** 2016-09-15 04:38 UTC
