### ISSUE TITLE
Max number of videos getting in playlist is 26

### ISSUE THREAD

**Issue by akshit-sharma** [rg3/youtube-dl#5783] opened 2015-05-22 20:50 UTC
there is a playlist https://www.youtube.com/watch?v=oeNvhhjtUqo&list=RDEMImzDuEMgFSKfDeg6xsw_gw&index=27 

when i used youtube-dl "https://www.youtube.com/playlist?list=RDEMImzDuEMgFSKfDeg6xsw_gw" -J --flat-playlist | jq ".entries | length" to get the number of videos in playlist it says 26 while playlist contains 51 videos.

Is it there a max limit in youtube-dl or is it from youtube (server) side ??

Also why does typing https://www.youtube.com/playlist?list=RDEMImzDuEMgFSKfDeg6xsw_gw in browser gives unknown error while youtube-dl  can use it to fetch videos ?

**Comment by dstftw** [comment] 2015-05-22 20:52
Duplicate of #3837.

**Closed by dstftw** 2015-05-22 20:52 UTC
