### ISSUE TITLE
Bug Report - Not able to download UDEMY videos after new update

### ISSUE THREAD

**Issue by saravanashines** [rg3/youtube-dl#9044] opened 2016-04-01 03:14 UTC
Bug report
Yesterday morning, it was working but from today it was not working. Whatever URL I use im getting 
unable to download JSON metadata

C:\Users\XXX\Downloads>youtube-dl.exe -v -u XXX -p XXX https://www.udemy.com/java-tutorial/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https
://www.udemy.com/java-tutorial/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.03.27
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] Logging in as b2193454@trbvn.com
[udemy:course] java-tutorial: Downloading webpage
[udemy:course] java-tutorial: Downloading course JSON
ERROR: Unable to download JSON metadata: HTTP Error 404: NOT FOUND (caused by HT
TPError()); please report this issue on https://yt-dl.org/bug . Make sure you ar
e using the latest version; type  youtube-dl -U  to update. Be sure to call yout
ube-dl with the --verbose flag and include its complete output.
  File "youtube_dl\extractor\common.pyo", line 366, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1934, in urlopen
  File "urllib2.pyo", line 437, in open
  File "urllib2.pyo", line 550, in http_response
  File "urllib2.pyo", line 475, in error
  File "urllib2.pyo", line 409, in _call_chain
  File "urllib2.pyo", line 558, in http_error_default

**Comment by dstftw** [comment] 2016-04-01 03:15
Duplicate of #9035.

**Closed by dstftw** 2016-04-01 03:15 UTC
