### ISSUE TITLE
NBC Crashes

### ISSUE THREAD

**Issue by cyperous** [rg3/youtube-dl#13651] opened 2017-07-14 21:54 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.09*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v https://www.nbc.com/americas-got-talent/video/best-of-auditions/3546241
[debug] System config: []
[debug] User config: [u'--ap-mso', u'Comcast_SSO', u'--ap-username', u'PRIVATE', u'--ap-password', u'PRIVATE']
[debug] Custom config: []
[debug] Command-line args: [u'https://www.nbc.com/americas-got-talent/video/best-of-auditions/3546241', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.09
[debug] Python version 2.7.13 - Darwin-16.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg git-2017-04-07-0e2f0fe, ffprobe git-2017-04-07-0e2f0fe
[debug] Proxy map: {}
[NBC] 3546241: Downloading JSON metadata
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1927, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 762, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/nbc.py", line 78, in _real_extract
IndexError: list index out of range
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

NBC videos were last know to work on or before 7/12/2017 now no videos can be download without youtube-dl crashing

**Comment by remitamine** [comment] 2017-07-15 08:25
can be fixed by always passing permalinks with `http` scheme to the api.
this does work: https://api.nbc.com/v3/videos?filter[permalink]=http://www.nbc.com/americas-got-talent/video/best-of-auditions/3546241
this does not: https://api.nbc.com/v3/videos?filter[permalink]=https://www.nbc.com/americas-got-talent/video/best-of-auditions/3546241

**Comment by ddurdle** [comment] 2017-07-15 13:46
I can confirm the fix works.

**Comment by witmore1** [comment] 2017-07-19 03:05
I can confirm that both the issue still happens in the 2017.7.15 version, and taking the 's' out of the https:// link does allow the program to work again

**Comment by gkoelln** [comment] 2017-07-26 12:13
This is a free videos that requires no login and this is what I'm getting:
```
PS C:\users\user\videos> youtube-dl http://www.nbc.com/world-of-dance/video/the-cut-1/3549527 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://www.nbc.com/world-of-dance/video/the-cut-1/3549527', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.07.23
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-52233-gee94362, ffprobe N-52233-gee94362
[debug] Proxy map: {}
[NBC] 3549527: Downloading JSON metadata
[ThePlatform] 3549527: Downloading SMIL data
[ThePlatform] 3549527: Downloading m3u8 information
[ThePlatform] 3549527: Downloading JSON metadata
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://nbcmpx-vh.akamaihd.net/i/video/889/347/170711_3549527_The_Cut_1_,25,40,18,12,7,4
,2,00.mp4.csmil/index_1_av.m3u8?null=0&id=AgBsoQaQF0P8jYeGeFkPKRE2HFPAUL67J3wQ8CjvaA294rcAKw80AQwjOIFCXkXY8TMdecEvqP5L6A
%3d%3d&hdntl=exp=1501157383~acl=%2fi%2fvideo%2f889%2f347%2f170711_3549527_The_Cut_1_*~data=hdntl~hmac=2761162f5918a6f7ad
e25e9b97f8b582dfcea3ab426789543af85b3aa7d746b9'
[download] Destination: The Cut 1-3549527.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers "Accept: text/html,application/xhtml+xml,application/x
ml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate
Cookie: _alid_=3LudXL74ycajeS0TWic0zw==
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)
Accept-Language: en-us,en;q=0.5
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
" -i "https://nbcmpx-vh.akamaihd.net/i/video/889/347/170711_3549527_The_Cut_1_,25,40,18,12,7,4,2,00.mp4.csmil/index_1_av
.m3u8?null=0&id=AgBsoQaQF0P8jYeGeFkPKRE2HFPAUL67J3wQ8CjvaA294rcAKw80AQwjOIFCXkXY8TMdecEvqP5L6A%3d%3d&hdntl=exp=150115738
3~acl=%2fi%2fvideo%2f889%2f347%2f170711_3549527_The_Cut_1_*~data=hdntl~hmac=2761162f5918a6f7ade25e9b97f8b582dfcea3ab4267
89543af85b3aa7d746b9" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:The Cut 1-3549527.mp4.part"
ffmpeg version N-52233-gee94362 Copyright (c) 2000-2013 the FFmpeg developers
  built on Apr 18 2013 02:55:39 with gcc 4.8.0 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfi
g --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libcaca --enable-libfreetyp
e --enable-libgsm --enable-libilbc --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-li
bopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheo
ra --enable-libtwolame --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libx264
 --enable-libxavs --enable-libxvid --enable-zlib
  libavutil      52. 26.100 / 52. 26.100
  libavcodec     55.  2.100 / 55.  2.100
  libavformat    55.  2.100 / 55.  2.100
  libavdevice    55.  0.100 / 55.  0.100
  libavfilter     3. 56.103 /  3. 56.103
  libswscale      2.  2.100 /  2.  2.100
  libswresample   0. 17.102 /  0. 17.102
  libpostproc    52.  3.100 / 52.  3.100
[https @ 0000000002bcc4a0] HTTP error 403 Forbidden
Unable to open key file https://nbcmpx-vh.akamaihd.net/i/video/889/347/170711_3549527_The_Cut_1_,25,40,18,12,7,4,2,00.mp
4.csmil/crypt.key?null=0&id=AgBsoQaQF0P8jYeGeFkPKRE2HFPAUL67J3wQ8CjvaA294rcAKw80AQwjOIFCXkXY8TMdecEvqP5L6A%3d%3d&hdntl=e
xp=1501157383~acl=/i/video/889/347/170711_3549527_The_Cut_1_*~data=hdntl~hmac=2761162f5918a6f7ade25e9b97f8b582dfcea3ab42
6789543af85b3aa7d746b9
[https @ 0000000002be8ae0] HTTP error 403 Forbidden
[crypto @ 0000000002bcc3e0] Unable to open input
[hls,applehttp @ 0000000002cf8980] Error when loading first segment 'https://nbcmpx-vh.akamaihd.net/i/video/889/347/1707
11_3549527_The_Cut_1_,25,40,18,12,7,4,2,00.mp4.csmil/segment1_1_av.ts?null=0&id=AgBsoQaQF0P8jYeGeFkPKRE2HFPAUL67J3wQ8Cjv
aA294rcAKw80AQwjOIFCXkXY8TMdecEvqP5L6A%3d%3d&hdntl=exp=1501157383~acl=/i/video/889/347/170711_3549527_The_Cut_1_*~data=h
dntl~hmac=2761162f5918a6f7ade25e9b97f8b582dfcea3ab426789543af85b3aa7d746b9'
https://nbcmpx-vh.akamaihd.net/i/video/889/347/170711_3549527_The_Cut_1_,25,40,18,12,7,4,2,00.mp4.csmil/index_1_av.m3u8?
null=0&id=AgBsoQaQF0P8jYeGeFkPKRE2HFPAUL67J3wQ8CjvaA294rcAKw80AQwjOIFCXkXY8TMdecEvqP5L6A%3d%3d&hdntl=exp=1501157383~acl=
%2fi%2fvideo%2f889%2f347%2f170711_3549527_The_Cut_1_*~data=hdntl~hmac=2761162f5918a6f7ade25e9b97f8b582dfcea3ab426789543a
f85b3aa7d746b9: Input/output error


ERROR: ffmpeg exited with code 1
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu6zpd7mk\build\youtube_dl\__init__.py", line 465, i
n main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu6zpd7mk\build\youtube_dl\__init__.py", line 455, i
n _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu6zpd7mk\build\youtube_dl\YoutubeDL.py", line 1956,
 in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu6zpd7mk\build\youtube_dl\YoutubeDL.py", line 787,
in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu6zpd7mk\build\youtube_dl\YoutubeDL.py", line 879,
in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu6zpd7mk\build\youtube_dl\YoutubeDL.py", line 841,
in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu6zpd7mk\build\youtube_dl\YoutubeDL.py", line 1599,
 in process_video_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu6zpd7mk\build\youtube_dl\YoutubeDL.py", line 1863,
 in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu6zpd7mk\build\youtube_dl\YoutubeDL.py", line 1805,
 in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu6zpd7mk\build\youtube_dl\downloader\common.py", li
ne 361, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu6zpd7mk\build\youtube_dl\downloader\external.py",
line 57, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu6zpd7mk\build\youtube_dl\downloader\common.py", li
ne 163, in report_error
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu6zpd7mk\build\youtube_dl\YoutubeDL.py", line 604,
in report_error
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu6zpd7mk\build\youtube_dl\YoutubeDL.py", line 566,
in trouble
```

**Comment by remitamine** [comment] 2017-07-26 13:05
@gkoelln try to use `--hls-prefer-native`.

**Comment by PRMan99** [comment] 2017-08-10 03:42
Taking the 's' out of 'https' was working with --hls-prefer-native for American Ninja Warrior, but now it no longer works.

**Comment by AdmiralDal59** [comment] 2017-08-11 05:26
Like PRMan99 said, these fixes aren't working for me.

~~~
C:\apps\ydl>youtube-dl.exe
[debug] System config: []
[debug] User config: ['-v', '-o', 'K:\\videos\\%(extractor)s\\%(title)s.%(epoch)s.%(ext)s', '-a'
, 'C:\\apps\\ydl\\cfg\\list.txt', '-f', 'bestvideo[ext=mp4]+bestaudio[ext!=webm]/best', '--no-pa
rt', '--write-description', '--write-annotations', '--ap-mso', 'DTV', '--ap-username', 'PRIVATE'
, '--ap-password', 'PRIVATE', '--netrc', '--hls-prefer-native']
[debug] Custom config: []
[debug] Command-line args: []
[debug] Batch file urls: ['http://www.nbc.com/saturday-night-live/video/november-12-dave-chappel
le/3423709']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.08.09
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-86175-g64ea4d1, ffprobe N-86175-g64ea4d1, rtmpdump 2.4
[debug] Proxy map: {}
[NBC] 3423709: Downloading JSON metadata
[NBC] 3423709: Downloading Provider Redirect Page
[NBC] 3423709: Downloading Provider Login Page
[NBC] 3423709: Logging in
ERROR: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure
 you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl wi
th the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf7t6lw0k\build\youtube_dl\Y
outubeDL.py", line 776, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf7t6lw0k\build\youtube_dl\e
xtractor\common.py", line 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf7t6lw0k\build\youtube_dl\e
xtractor\nbc.py", line 90, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf7t6lw0k\build\youtube_dl\e
xtractor\adobepass.py", line 1511, in _extract_mvpd_auth
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf7t6lw0k\build\youtube_dl\e
xtractor\adobepass.py", line 1360, in post_form
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf7t6lw0k\build\youtube_dl\e
xtractor\common.py", line 791, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf7t6lw0k\build\youtube_dl\e
xtractor\common.py", line 782, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract post url; please report this issue on htt
ps://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update.
 Be sure to call youtube-dl with the --verbose flag and include its complete output.
~~~

**Comment by ddurdle** [comment] 2017-08-12 04:38
forcing http works for me including with ANW.

**Comment by johnhawkinson** [comment] 2017-08-12 12:29
I'm not sure it's clear (you can sort of tell from the title of the dupe, #13715, NBC no longer works), but this is regression. `git bisect` reports:

```
pb3:youtube-dl jhawk$ git bisect good
2eeb588efe9a7df4b2dcd90de9e461e8ff4a40fa is the first bad commit
commit 2eeb588efe9a7df4b2dcd90de9e461e8ff4a40fa
Author: Remita Amine <remitamine@gmail.com>
Date:   Sun May 7 08:58:34 2017 +0100

    [nbc] improve extraction(closes #12364)

:040000 040000 c9cbc37eb4ee9c13992383df9a442d1ea9022285 5770e58fc1f4bb3fd63b34246880ee24236e7a57 M	youtube_dl
```

So 2eeb588efe9a7df4b2dcd90de9e461e8ff4a40fa by @remitamine fixing #12364 O364.
It would be great to have a more-detailed commit message :(

Oh, hey, #12364 is my PR. Whoops…

**Comment by chancemimi** [comment] 2017-09-01 06:09
Now the youtube-dl version has come to 2017.8.27, BUT the problem of nbc still remains.
Could there be any solution?
Thanks!!

**Comment by PRMan99** [comment] 2017-09-01 10:48
American Ninja Warrior has been working except one episode (Denver first round) where there is a malformed XML error that apparently doesn't affect the player but affects YouTube-DL.  I've been able to download every episode since using a combination of http instead of https and --hls-prefer-native.

**Comment by snipem** [comment] 2017-10-01 11:04
```
$ youtube-dl -v --proxy localhost:8888 --hls-prefer-native https://www.nbc.com/saturday-night-live/video/september-30-ryan-gosling/3592851
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--proxy', 'localhost:8888', '--hls-prefer-native', 'https://www.nbc.com/saturday-night-live/video/september-30-ryan-gosling/3592851']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2017.09.24
[debug] Python version 3.6.1 - Linux-4.10.13-1-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 3.3, ffprobe 3.3, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {'http': 'localhost:8888', 'https': 'localhost:8888'}
[NBC] 3592851: Downloading JSON metadata
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 11, in <module>
    load_entry_point('youtube-dl==2017.9.24', 'console_scripts', 'youtube-dl')()
  File "/usr/lib/python3.6/site-packages/youtube_dl/__init__.py", line 465, in main
    _real_main(argv)
  File "/usr/lib/python3.6/site-packages/youtube_dl/__init__.py", line 455, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1968, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 777, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/nbc.py", line 78, in _real_extract
    })['data'][0]['attributes']
IndexError: list index out of range
```
Still not working. I'm using a local proxy.

**Comment by mekantor** [comment] 2017-10-01 14:40
This is coming back as an empty array
`self._download_json(
            'https://api.nbc.com/v3/videos', video_id, query={
                'filter[permalink]': permalink,
            })['data']`

**Comment by johnhawkinson** [comment] 2017-10-01 14:46
As I wrote in August, this was broken by #12364
> Oh, hey, #12364 is my PR. Whoops…

I haven't had a chance to look at it, but the old version works fine. Reverting #12364 in the interim is probably worth it, but of course someone should take the time to find the problem [and add a test!]

**Comment by remitamine** [comment] 2017-10-01 16:08
as i said before this can be simply fixed just by always using `http` permalink.
and i also said in other issues that i have problems in my netbook that prevent me from contributing to the project.
just change the regex from:
```python
_VALID_URL = r'(?P<permalink>https?://(?:www\.)?nbc\.com/[^/]+/video/[^/]+/(?P<id>n?\d+))'
```
to 
```python
_VALID_URL = r'https?(?P<permalink>://(?:www\.)?nbc\.com/[^/]+/video/[^/]+/(?P<id>n?\d+))'
```
and add this line:
```python
permalink = 'http' + permalink
```
after this line:
```python
permalink, video_id = re.match(self._VALID_URL, url).groups()
```

**Comment by snipem** [comment] 2017-10-01 20:35
@remitamine Why don't you create a Pull Request then?

**Comment by remitamine** [comment] 2017-10-01 21:29
@snipem
> and i also said in other issues that i have problems in my netbook that prevent me from contributing to the project.

**Comment by PRMan99** [comment] 2017-10-02 20:15
I spent 3 hours trying to get Python setup enough to actually run
youtube-dl.

Can somebody point me to a pre-made virtual machine that can compile this
with simple instructions or a list of instructions that works on a Windows
10 PC (unlike every set of instructions online, none of which work).

**Comment by snipem** [comment] 2017-10-03 12:54
Well, the only recommendation I can give you, is to use a Mac or a Linux virtual machine instead.

Setting up Scripting languages on Windows is a hassle.

I'll give @remitamine 's proposal a shot

**Comment by snipem** [comment] 2017-10-03 13:25
@remitamine Your changes seem to work and I've created a Pull Request. Can you please release your code snippets as Public Domain. A comment in the Pull Request should be enough.

**Closed** 2017-10-03 14:50 UTC
Labels: easy

**Comment by PRMan99** [comment] 2017-10-03 20:43
Thanks, guys.

If you have a VM that's set up or instructions for Linux, I can always set
up Ubuntu on Windows 10 or a VM.

**Comment by ddurdle** [comment] 2017-10-04 23:44
Updated to release 2017-10-01 and doesn't work.  My fix implemented here works still -> https://github.com/ddurdle/youtube-dl/commit/df54c57677bc9f419e9fcd74e85ea929c85673fc#comments
