### ISSUE TITLE
[cspan] download failing

### ISSUE THREAD

**Issue by rowanwernham** [rg3/youtube-dl#5433] opened 2015-04-15 18:20 UTC
Having problems downloading this video: http://www.c-span.org/video/?200413-1/new-media-technology

`````
Rowans-MacBook-Pro:~ rowan$ youtube-dl --verbose http://www.c-span.org/video/?200413-1/new-media-technology
[debug] System config: ['-o', '/Users/rowan/Downloads/%(title)s-%(id)s.%(ext)s']
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.c-span.org/video/?200413-1/new-media-technology']
WARNING: Parameter outtmpl is bytes, but should be a unicode string. Put  from __future__ import unicode_literals  at the top of your code file or consider switching to Python 3.x.
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.09
[debug] Python version 2.7.6 - Darwin-14.0.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[CSpan] 200413: Downloading webpage
[CSpan] 179812: Downloading JSON metadata
[CSpan] 179812: Downloading XML
ERROR: An extractor error has occured. (caused by KeyError(u'files',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/cspan.py", line 71, in _real_extract
    files = data['video']['files']
KeyError: u'files'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 651, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 281, in extract
    raise ExtractorError('An extractor error has occured.', cause=e)
ExtractorError: An extractor error has occured. (caused by KeyError(u'files',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Rowans-MacBook-Pro:~ rowan$ youtube-dl -U
WARNING: Parameter outtmpl is bytes, but should be a unicode string. Put  from __future__ import unicode_literals  at the top of your code file or consider switching to Python 3.x.
youtube-dl is up-to-date (2015.04.09)
````

**Comment by dstftw** [comment] 2015-04-15 18:24
Duplicate of #3734.

**Closed by dstftw** 2015-04-15 18:24 UTC
