### ISSUE TITLE
[Feature request] Support downloading a producer's entire discography on BandCamp

### ISSUE THREAD

**Issue by milesrotaru** [rg3/youtube-dl#16826] opened 2018-06-26 16:29 UTC
Downloading individual albums is already supported but I don't know of a very convenient way to fetch lists of album URL's by producer.

**Comment by parmjitv** [comment] 2018-06-26 19:56
Hi @milesrotaru,

Can you please provide an example URL that lists albums by producer?

Thanks!

Parmjit V.

**Comment by milesrotaru** [comment] 2018-06-26 21:59
Here's one, and it's an example of a BandCamp profile on a custom domain.

http://music.disasterpeace.com

Discography is listed off to the right hand side of the page and thankfully even though it's not all immediately visible, it's always in the html. In this case starting around line 3464 in the source view.

**Comment by parmjitv** [comment] 2018-06-29 20:46
@milesrotaru - thanks for the detailed response.  I am going to give this one a shot, if I understand correctly we are basically adding the ability to download playlists of albums as you describe above.

Cheers,

Parmjit V.

**Comment by lyz-code** [comment] 2018-09-12 15:45
@parmjitv @dstftw maybe this is a duplicate of https://github.com/rg3/youtube-dl/issues/6231?

**Closed** 2018-10-31 23:18 UTC
