### ISSUE TITLE
[Escapist] ERROR: Unable to extract config URL

### ISSUE THREAD

**Issue by JohnSauer** [rg3/youtube-dl#5034] opened 2015-02-23 15:26 UTC
Here is the command I'm attempting:

    youtube-dl  --verbose  --output '/Users/ghettopia/Desktop/downloaded_video.%(ext)s'  'http://www.escapistmagazine.com/videos/view/zero-punctuation/10038-Grim-Fandango-Review'

And here is the error I receive:

    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: ['--verbose', '--output', '/Users/ghettopia/Desktop/downloaded_video.%(ext)s', 'http://www.escapistmagazine.com/videos/view/zero-punctuation/10038-Grim-Fandango-Review']
    [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2015.02.21
    [debug] Python version 2.7.6 - Darwin-14.1.0-x86_64-i386-64bit
    [debug] exe versions: ffmpeg present
    [debug] Proxy map: {}
    [Escapist] 10038: Downloading webpage
    ERROR: Unable to extract config URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
    Traceback (most recent call last):
      File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 643, in extract_info
        ie_result = ie.extract(url)
      File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 269, in extract
        return self._real_extract(url)
      File "/usr/bin/youtube-dl/youtube_dl/extractor/escapist.py", line 45, in _real_extract
        r'<param name="flashvars" value="config=([^"&]+)', webpage, 'config URL'))
      File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 551, in _html_search_regex
        res = self._search_regex(pattern, string, name, default, fatal, flags, group)
      File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 541, in _search_regex
        raise RegexNotFoundError('Unable to extract %s' % _name)
    RegexNotFoundError: Unable to extract config URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment] 2015-02-23 15:36
Duplicate of #5028.
This is already fixed and will be available in the next version. Thanks for the report.

**Closed by dstftw** 2015-02-23 15:36 UTC

**Comment by phihag** [comment] 2015-02-24 10:46
I believe this issue to be fixed in youtube-dl version 2015.02.24 and newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by JohnSauer** [comment] 2015-02-24 14:55
@phihag, I just attempted the command in youtube-dl version 2015.02.24.1 and received the error below. 

    Last login: Tue Feb 24 09:53:15 on ttys001
    Macintosh:~ ghettopia$ youtube-dl  --verbose  --output '/Users/ghettopia/Desktop/downloaded_video.%(ext)s'  'http://www.escapistmagazine.com/videos/view/zero-punctuation/10038-Grim-Fandango-Review'
    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: ['--verbose', '--output', '/Users/ghettopia/Desktop/downloaded_video.%(ext)s', 'http://www.escapistmagazine.com/videos/view/zero-punctuation/10038-Grim-Fandango-Review']
    [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2015.02.24.1
    [debug] Python version 2.7.6 - Darwin-14.1.0-x86_64-i386-64bit
    [debug] exe versions: ffmpeg present
    [debug] Proxy map: {}
    [Escapist] 10038: Downloading webpage
    ERROR: Unable to extract config URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
    Traceback (most recent call last):
      File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 643, in extract_info
        ie_result = ie.extract(url)
      File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
        return self._real_extract(url)
      File "/usr/bin/youtube-dl/youtube_dl/extractor/escapist.py", line 45, in _real_extract
        r'<param\s+name="flashvars"\s+value="config=([^"&]+)', webpage, 'config URL'))
      File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 557, in _html_search_regex
        res = self._search_regex(pattern, string, name, default, fatal, flags, group)
      File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 547, in _search_regex
        raise RegexNotFoundError('Unable to extract %s' % _name)
    RegexNotFoundError: Unable to extract config URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by phihag** [comment] 2015-02-24 15:52
It seems like The Escapist has changed their player once again. Fixed in youtube-dl 2015.02.24.2.

**Comment by JohnSauer** [comment] 2015-02-24 16:01
Yup, 2015.02.24.2 fixes it.  Thanks!
