### ISSUE TITLE
Show progress for --dump-single-json

### ISSUE THREAD

**Issue by royale1223** [rg3/youtube-dl#10801] opened 2016-09-29 18:16 UTC
Is there a way to enable any sort of progress indicator for the --dump-single-json command to the error stream? Even something like the output below will do fine:

```
[youtube] E2dNAgerQHQ: Downloading webpage
[youtube] E2dNAgerQHQ: Downloading video info webpage
[youtube] E2dNAgerQHQ: Extracting video information
[youtube] E2dNAgerQHQ: Downloading MPD manifest
```

**Comment by dstftw** [comment] 2016-09-29 18:23
Duplicate of #5400.

**Closed by dstftw** 2016-09-29 18:23 UTC
