### ISSUE TITLE
unable to extract html5 player

### ISSUE THREAD

**Issue by kohankin** [rg3/youtube-dl#12899] opened 2017-04-28 10:15 UTC
Hello! Today (28.04.2017) I get error 

> unable to extract html5 player,

 tomrrow (27.04.2017) the mistake was absent. 
I use actual version of YT-dl

## **--verbose List:**

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-r', u'50K', u'https://www.youtube.com/watch?v=E-H                                                                             3Vxm7p80', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.26
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.5
[debug] exe versions: avconv 11.8-6, avprobe 11.8-6, ffmpeg 2.7.2, ffprobe 2.7.2
[debug] Proxy map: {}
[youtube] E-H3Vxm7p80: Downloading webpage
[youtube] E-H3Vxm7p80: Downloading video info webpage
[youtube] E-H3Vxm7p80: Extracting video information
WARNING: unable to extract html5 player; please report this issue on https://yt-                                                                             dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/                                                                             update  on how to update. Be sure to call youtube-dl with the --verbose flag and                                                                              include its complete output.
[youtube] {43} signature length 40.40, html5 player None
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py",                                                                              line 1081, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py",                                                                              line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://www.youtube.com/yts/jsbin/playe                                                                             r-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug .                                                                              Make sure you are using the latest version; see  https://yt-dl.org/update  on ho                                                                             w to update. Be sure to call youtube-dl with the --verbose flag and include its                                                                              complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://www.youtube.com/yt                                                                             s/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-                                                                             dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/                                                                             update  on how to update. Be sure to call youtube-dl with the --verbose flag and                                                                              include its complete output.",)); please report this issue on https://yt-dl.org                                                                             /bug . Make sure you are using the latest version; see  https://yt-dl.org/update                                                                               on how to update. Be sure to call youtube-dl with the --verbose flag and inclu                                                                             de its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py",                                                                              line 1081, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py",                                                                              line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://www.youtube.com/yts/jsbin/playe                                                                             r-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug .                                                                              Make sure you are using the latest version; see  https://yt-dl.org/update  on ho                                                                             w to update. Be sure to call youtube-dl with the --verbose flag and include its                                                                              complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 76                                                                             0, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py",                                                                              line 429, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py",                                                                              line 1642, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py",                                                                              line 1091, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py",                                                                              line 1081, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py",                                                                              line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://www.youtube.com/yts/jsbin/playe                                                                             r-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug .                                                                              Make sure you are using the latest version; see  https://yt-dl.org/update  on ho                                                                             w to update. Be sure to call youtube-dl with the --verbose flag and include its                                                                              complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://www.youtube.com/yt                                                                             s/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-                                                                             dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/                                                                             update  on how to update. Be sure to call youtube-dl with the --verbose flag and                                                                              include its complete output.",)); please report this issue on https://yt-dl.org                                                                             /bug . Make sure you are using the latest version; see  https://yt-dl.org/update                                                                               on how to update. Be sure to call youtube-dl with the --verbose flag and inclu                                                                             de its complete output.

**Comment by yan12125** [comment] 2017-04-28 10:15
Duplicate of #12885

**Closed by yan12125** 2017-04-28 10:15 UTC
