### ISSUE TITLE
vevo.com extractor error

### ISSUE THREAD

**Issue by Kirazith** [rg3/youtube-dl#12118] opened 2017-02-13 18:55 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.14*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl.exe http://www.vevo.com/watch/monrose/Shame-(Video)/DER350610087 -v

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://www.vevo.com/watch/monrose/Shame-(Video)/DER
350610087', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.02.14
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2
[debug] Proxy map: {}
[Vevo] Retrieving oauth token
[Vevo] DER350610087: Downloading api video info
[Vevo] DER350610087: Downloading video versions info
WARNING: Failed to download video versions info: HTTP Error 401: Unauthorized
[Vevo] DER350610087: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError('streams',)); please
 report this issue on https://yt-dl.org/bug . Make sure you are using the latest
 version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --
verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqajgst4a\bu
ild\youtube_dl\extractor\common.py", line 369, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqajgst4a\bu
ild\youtube_dl\extractor\vevo.py", line 196, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqajgst4a\bu
ild\youtube_dl\extractor\vevo.py", line 25, in _extract_json
KeyError: 'streams'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqajgst4a\bu
ild\youtube_dl\extractor\common.py", line 369, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqajgst4a\bu
ild\youtube_dl\extractor\vevo.py", line 196, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqajgst4a\bu
ild\youtube_dl\extractor\vevo.py", line 25, in _extract_json
KeyError: 'streams'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqajgst4a\bu
ild\youtube_dl\YoutubeDL.py", line 696, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqajgst4a\bu
ild\youtube_dl\extractor\common.py", line 375, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by Key
Error('streams',)); please report this issue on https://yt-dl.org/bug . Make sur
e you are using the latest version; type  youtube-dl -U  to update. Be sure to c
all youtube-dl with the --verbose flag and include its complete output.
```

**Comment by yan12125** [comment] 2017-02-22 16:18
Duplicate of #11719

**Closed by yan12125** 2017-02-22 16:18 UTC
