### ISSUE TITLE
certificate verify failed

### ISSUE THREAD

**Issue by victornpb** [rg3/youtube-dl#15165] opened 2018-01-04 00:29 UTC
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.31*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.31**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl -v  https://www.youtube.com/watch?v=Js3WIRF595U
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=Js3WIRF595U']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.31
[debug] Python version 2.7.13 - Darwin-16.0.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] Js3WIRF595U: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)> (caused by URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 517, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2198, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1088, in https_open
    req, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
```

---

### Description of your *issue*, suggested solution and other information

I just freshly installed homebrew by issuing

```
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```
and then installed youtube dl

```
brew install youtube-dl
```

running youtube-dl -v  https://www.youtube.com/watch?v=Js3WIRF595U

it gave me the CERTIFICATE_VERIFY_FAILED error, so I did `brew uninstall youtube-dl` an tried installing it via curl 
```
sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl
```
Same thing, I found 2 other closed issues related to reinstalling SSL, I tried that, but it still doesnt work.
```
$ openssl version
OpenSSL 1.0.2k  26 Jan 2017
```

I'm running `macOS Sierra 10.12`

**Comment by yan12125** [comment] 2018-01-04 05:21
> /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py

This is not a standard Homebrew Python path. Could you check if you have other package managers installed? (MacPorts, Fink, ...)

**Comment by MattInNC** [comment] 2018-01-04 16:56
If it helps, I'm receiving the same certificate_verify_failed error on Windows 7 x64 using the 2017.12.31 release.  I have been using the --no-check-certificate option to get around it since Jan 1.

**Comment by milleniumbug** [comment] 2018-01-06 04:17
I can reproduce the issue on Windows 10 (youtube-dl installed through Chocolatey)

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=Js3WIRF595U']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2017.12.31
[debug] Python version 3.4.4 - Windows-10-10.0.16299
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1
[debug] Proxy map: {}
[youtube] Js3WIRF595U: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpiyv5xz5s\build\youtube_dl\extractor\common.py", line 517, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpiyv5xz5s\build\youtube_dl\YoutubeDL.py", line 2198, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpiyv5xz5s\build\youtube_dl\utils.py", line 1088, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open
```

**Comment by yan12125** [comment] 2018-01-06 04:27
@milleniumbug: How SSL works on Windows is different. Check https://github.com/rg3/youtube-dl/issues/7309#issuecomment-165327967

As there are no more responses from the original poster, I'm closing this issue.

**Closed by yan12125** 2018-01-06 04:27 UTC
Labels: clarification-needed

**Comment by jschwalbe** [comment] 2018-03-13 03:28
Can I reopen it? I'm still having a similar problem (if not the same).

```
$ youtube-dl --version
2018.03.10
$ youtube-dl -v https://www.fox.com/watch/a10a2d933255f29b6928c1dd0dbe9347
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.fox.com/watch/a10a2d933255f29b6928c1dd0dbe9347']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.10
[debug] Python version 3.6.0 (CPython) - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.3, ffprobe 3.3.3, rtmpdump 2.4
[debug] Proxy map: {}
[FOX] a10a2d933255f29b6928c1dd0dbe9347: Downloading JSON metadata
ERROR: Unable to download JSON metadata: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)'),))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 519, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2199, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/utils.py", line 1101, in https_open
    req, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
```

**Comment by yan12125** [comment] 2018-03-13 08:17
@jschwalbe: Most likely you are bitten by a Mac issue. Check out https://github.com/rg3/youtube-dl/issues/11943#issuecomment-276947670

**Comment by jschwalbe** [comment] 2018-03-17 13:40
Thanks @yan12125.
Since SSL isn't important to me, I've just updated my script to use the workaround:
`    --no-check-certificate           Suppress HTTPS certificate validation`

**Comment by ezerbib** [comment] 2019-05-29 08:39
For me it was the date of the device which was set later than the certificate expiration date. So double check the date of the device you run youtube-dl

**Comment by dezza** [comment] 2020-01-18 23:30
Make sure you have
pip install certifi
Installs Mozilla CA-bundle, apparently it's not included with Python3 installations. But it fixed a similar issue for me.
