### ISSUE TITLE
Failed Youtube. ERROR: Signature extraction failed. (caused by ExtractorError(u"Cannot identify player....))

### ISSUE THREAD

**Issue by daotrunghieu** [rg3/youtube-dl#7429] opened 2015-11-10 09:12 UTC
Youtube-dl still work for almost Youtube.

#### youtube-dl failed against URL(s) below:
* youtube-dl.exe *https://www.youtube.com/watch?v=IhqqZN0H7CI* -F
* youtube-dl.exe *https://www.youtube.com/watch?v=pYt0Nwt_oNI* -F

#### output from youtube-dl --verbose may not necessary in case we could replicated issue. My youtube-dl version
> Encodings: locale cp1252, fs mbcs, out None, pref cp1252
> youtube-dl version **2015.11.02**
> Python version 2.7.10 - Windows-7-6.1.7601-SP1
> exe versions: ffmpeg N-76417-gee20354, ffprobe N-76417-gee20354

**Comment by yan12125** [comment] 2015-11-10 09:28
Duplicate of #7413. This will be fixed in the next version.

**Closed by yan12125** 2015-11-10 09:28 UTC
