### ISSUE TITLE
--get-filename returns incorrect filename if output file gets merged

### ISSUE THREAD

**Issue by nixxquality** [rg3/youtube-dl#11472] opened 2016-12-18 02:11 UTC
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.15**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
$ youtube-dl --get-filename https://www.youtube.com/watch?v=HEv_9fQBWVY
CrossFit for Chickens-HEv_9fQBWVY.mp4
$ youtube-dl https://www.youtube.com/watch?v=HEv_9fQBWVY
[youtube] HEv_9fQBWVY: Downloading webpage
[youtube] HEv_9fQBWVY: Downloading video info webpage
[youtube] HEv_9fQBWVY: Extracting video information
[youtube] HEv_9fQBWVY: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Destination: CrossFit for Chickens-HEv_9fQBWVY.f136.mp4
[download] 100% of 16.32MiB in 00:00
[download] Destination: CrossFit for Chickens-HEv_9fQBWVY.f251.webm
[download] 100% of 1.36MiB in 00:00
[ffmpeg] Merging formats into "CrossFit for Chickens-HEv_9fQBWVY.mkv"
Deleting original file CrossFit for Chickens-HEv_9fQBWVY.f136.mp4 (pass -k to keep)
Deleting original file CrossFit for Chickens-HEv_9fQBWVY.f251.webm (pass -k to keep)
```

The --get-filename function should check if mkv merge is needed, and return a proper filename.

**Comment by dstftw** [comment] 2016-12-18 02:34
Duplicate of #5710.

**Closed by dstftw** 2016-12-18 02:34 UTC
