### ISSUE TITLE
WARNING: Could not download DASH manifest: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by bealparslan** [rg3/youtube-dl#6331] opened 2015-07-22 13:06 UTC
Hello, I'm read all <b>duplicate</b> issues. But this issue very important. I'm <b>using youtube-dl 2015.07.21</b> version. Warnings / errors do not want to hide. Please correct this problem.

[root@localhost ~]# youtube-dl https://www.youtube.com/watch?v=tDq3fNew1rU --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=tDq3fNew1rU', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.21
[debug] Python version 2.6.6 - Linux-2.6.32-431.29.2.el6.x86_64-x86_64-with-centos-6.5-Final
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] tDq3fNew1rU: Downloading webpage
[youtube] tDq3fNew1rU: Downloading video info webpage
[youtube] tDq3fNew1rU: Extracting video information
[youtube] {22} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {43} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {18} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {5} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {36} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {17} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {136} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {247} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {135} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {244} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {134} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {243} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {133} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {242} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {160} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {278} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {140} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {171} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {249} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {250} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {251} signature length 40.40, html5 player en_US-vflDv401v
[youtube] tDq3fNew1rU: Downloading DASH manifest
[youtube] tDq3fNew1rU: Downloading player https://s.ytimg.com/yts/jsbin/html5player-en_US-vflDv401v/html5player.js
[youtube] tDq3fNew1rU: Downloading DASH manifest
WARNING: Could not download DASH manifest: HTTP Error 403: Forbidden
[debug] Invoking downloader on u'https://r3---sn-u2oxu-f5fs.googlevideo.com/videoplayback?fexp=901816%2C903311%2C9406194%2C9408142%2C9408710%2C9408860%2C9414856%2C9415041%2C9415397%2C9415531%2C9415540%2C9416126%2C9416215%2C9416403%2C9416650%2C9416729%2C9417689%2C9417709&pcm2cms=yes&pl=20&itag=22&mime=video%2Fmp4&upn=R701I8pxbaQ&sparams=dur%2Cid%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&ipbits=0&id=o-AOqijFrPLTHRsP6iKpcepanQ8r2gr4-4K_sRJ_tLyIIZ&source=youtube&lmt=1429771443630151&key=yt5&ip=MY_SERVER_IP&expire=1437591751&dur=213.739&sver=3&requiressl=yes&mv=u&mt=1437570052&ms=au&mn=sn-u2oxu-f5fs&mm=31&ratebypass=yes&signature=36FE793913C267CA25334DAC38142B75915F7C3E.3A9A12F983904986131972B41D6926D25840832A'
[download] Destination: Sean Paul - Got 2 Luv U Ft. Alexis Jordan [Official Music Video]-tDq3fNew1rU.mp4
[download] 100% of 65.24MiB in 00:02

**Comment by bealparslan** [comment] 2015-07-22 13:22
I receive this alert in some videos.

**Comment by dstftw** [comment] 2015-07-22 13:26
Duplicate of #5118.

**Closed by dstftw** 2015-07-22 13:26 UTC
