### ISSUE TITLE
Unable to extract DASH manifest error

### ISSUE THREAD

**Issue by CuZnDragon** [rg3/youtube-dl#4398] opened 2014-12-07 13:45 UTC
youtube-dl https://www.youtube.com/watch?v=h5c06I8rHO8
[youtube] h5c06I8rHO8: Downloading webpage
[youtube] h5c06I8rHO8: Extracting video information
WARNING: [youtube] h5c06I8rHO8: Skipping DASH manifest: ExtractorError(u'Cannot decrypt signature without player_url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[download] Destination: English Words in Japanese by 日本語 learners (Nations Of The World tune) #add1challenge 日本語学習者が歌う外来語-h5c06I8rHO8.mp4
[download] 100% of 20.79MiB in 00:11

youtube-dl -U
youtube-dl is up-to-date (2014.12.06.1)

rm -rf *-h5c06I8rHO8*

youtube-dl --verbose https://www.youtube.com/watch?v=h5c06I8rHO8
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=h5c06I8rHO8']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.12.06.1
[debug] Python version 2.7.9rc1 - Linux-3.16-3-amd64-x86_64-with-debian-8.0
[debug] exe versions: avconv 2.4.4, avprobe 2.4.4, ffmpeg 2.4.4, ffprobe 2.4.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] h5c06I8rHO8: Downloading webpage
[youtube] h5c06I8rHO8: Extracting video information
[youtube] h5c06I8rHO8: Downloading DASH manifest
[debug] Invoking downloader on u'https://r5---sn-q4f7sn7l.googlevideo.com/videoplayback?sparams=dur%2Cid%2Cip%2Cipbits%2Citag%2Cmime%2Cmm%2Cms%2Cmv%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&ratebypass=yes&sver=3&dur=115.496&signature=D10531FA78AE92309C42534799B53CE2BA8D81BA.68C58A5B3C90C943158580AEB2BFB74C2C040567&mime=video%2Fmp4&itag=22&upn=4t2EfJe8-uY&fexp=907259%2C922244%2C927622%2C932404%2C943917%2C945323%2C946008%2C947209%2C948124%2C952302%2C952605%2C952901%2C953912%2C957103%2C957106%2C957201&id=o-ACVa0oIyo5FJQjupPL0UnPrOMgfJmteItghtHOcdgZoO&source=youtube&mm=31&expire=1417981325&key=yt5&requiressl=yes&ms=au&ipbits=0&mv=u&mt=1417959346&ip=104.4.82.161'
[download] Destination: English Words in Japanese by 日本語 learners (Nations Of The World tune) #add1challenge 日本語学習者が歌う外来語-h5c06I8rHO8.mp4
[download] 100% of 20.79MiB in 00:07

**Comment by zachberger** [comment] 2015-01-16 03:37
```
➜  ~  youtube-dl --verbose https://www.youtube.com/watch\?v\=usIoVA75xsI\&hd\=1 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=usIoVA75xsI&hd=1']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.11
[debug] Python version 2.7.9 - Darwin-14.1.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.5.2, ffprobe 2.5.2
[debug] Proxy map: {}
[youtube] usIoVA75xsI: Downloading webpage
[youtube] usIoVA75xsI: Extracting video information
WARNING: [youtube] usIoVA75xsI: Skipping DASH manifest: ExtractorError(u'Cannot decrypt signature without player_url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[debug] Invoking downloader on u'https://r7---sn-jc47eu7l.googlevideo.com/videoplayback?ipbits=0&upn=aLGCD2SwdnE&gcr=us&source=youtube&signature=A9AD4A70C7E8EE9F2F8A66910E72646839BB2641.57CDE527E0F5610B5C976CFFC38A791174B804A9&expire=1421400969&ratebypass=yes&mime=video%2Fmp4&requiressl=yes&id=o-AMSVMBLmeRyF08jE_A09isSqw5fQ_PuMA_ntXQRVxTIH&fexp=900718%2C907263%2C927622%2C9405437%2C941004%2C943917%2C947209%2C947225%2C948124%2C952302%2C952605%2C952901%2C955301%2C957103%2C957105%2C957201%2C959701&sparams=dur%2Cgcr%2Cid%2Cip%2Cipbits%2Citag%2Cmime%2Cmm%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&sver=3&itag=18&ms=pm&mv=s&dur=1371.091&mt=1421377458&pl=22&ip=129.21.135.208&mm=35&key=yt5'
[download] Destination: Deadmau5 Live New York 10_30_10 'The Lost Set'-usIoVA75xsI.mp4
[download] 100% of 53.16MiB in 00:09
```

**Comment by zachberger** [comment] 2015-01-16 03:38
Looks to be dupe of: #4587 & #4638

**Closed** 2016-06-12 17:11 UTC
