### ISSUE TITLE
youtube-dl 2015.08.09: Youtube: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by himadri0327** [rg3/youtube-dl#6565] opened 2015-08-14 23:19 UTC
PS N:> youtube-dl --verbose https://www.youtube.com/watch?v=FnArBdxJ66A
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=FnArBdxJ66A']
[debug] Encodings: locale cp1252, fs mbcs, out cp1251, pref cp1252
[debug] youtube-dl version 2015.08.09
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-59433-g4aa9c91, ffprobe N-59433-g4aa9c91
[debug] Proxy map: {}
[youtube] FnArBdxJ66A: Downloading webpage
[youtube] FnArBdxJ66A: Downloading video info webpage
[youtube] FnArBdxJ66A: Extracting video information
[youtube] {43} signature length 40.42, html5 player new
[youtube] {18} signature length 40.42, html5 player new
[youtube] {5} signature length 40.42, html5 player new
[youtube] {36} signature length 40.42, html5 player new
[youtube] {17} signature length 40.42, html5 player new
[youtube] {135} signature length 40.42, html5 player new
[youtube] {244} signature length 40.42, html5 player new
[youtube] {134} signature length 40.42, html5 player new
[youtube] {243} signature length 40.42, html5 player new
[youtube] {133} signature length 40.42, html5 player new
[youtube] {242} signature length 40.42, html5 player new
[youtube] {160} signature length 40.42, html5 player new
[youtube] {140} signature length 40.42, html5 player new
[youtube] {171} signature length 40.42, html5 player new
[youtube] FnArBdxJ66A: Downloading DASH manifest
WARNING: [youtube] FnArBdxJ66A: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden
 (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  yout
ube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[debug] Invoking downloader on u'https://r18---sn-ab5l6n7l.googlevideo.com/videoplayback?sparams=clen%2Cdur%2Cgir%2Cid%2Cinitcwndbps
%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&fexp=9405989%2C9407177%
2C9408206%2C9408486%2C9408710%2C9409069%2C9410705%2C9415365%2C9415485%2C9416023%2C9416126%2C9416729%2C9417278%2C9417299%2C9417629%2C
9417707%2C9417931%2C9417950%2C9418153%2C9418232%2C9419225%2C9419444&ip=24.0.89.251&clen=10157303&id=o-APf8bOzT9w0m6YuyLSvLfqYyM2P-Oh
7FSSJzWu8v2_zD&keepalive=yes&upn=8L3YPcbTGeg&mm=31&mn=sn-ab5l6n7l&mt=1439593620&mv=m&ms=au&itag=135&ipbits=0&lmt=1389940948246349&sv
er=3&expire=1439615256&mime=video%2Fmp4&key=yt5&gir=yes&requiressl=yes&source=youtube&dur=167.134&initcwndbps=1802500&pl=17&signatur
e=D5F07F6B4916A3A2A38D67E0075572099F1A60F1.5FE4C7538C260719C8A901FF8D563E45DB6C60E4&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1579, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1527, in dl
  File "youtube_dl\downloader\common.pyo", line 342, in download
  File "youtube_dl\downloader\http.pyo", line 60, in real_download
  File "youtube_dl\YoutubeDL.pyo", line 1860, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default
HTTPError: HTTP Error 403: Forbidden

**Comment by vxbinaca** [comment] 2015-08-15 01:21
I'm getting a lot of this too, I've been on an archiving binge and I've had to halt my ripping due to this.


```
vxbinaca@workstation//media/vxbinaca/Storage/channel_rips$ youtube-dl --ignore-config --verbose https://www.youtube.com/watch?v=pD8VcixLmFc
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--ignore-config', u'--verbose', u'https://www.youtube.com/watch?v=pD8VcixLmFc']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.09
[debug] Python version 2.7.9 - Linux-3.19.0-25-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, ffmpeg 2.5.8-0ubuntu0.15.04.1, ffprobe 2.5.8-0ubuntu0.15.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] pD8VcixLmFc: Downloading webpage
[youtube] pD8VcixLmFc: Downloading video info webpage
[youtube] pD8VcixLmFc: Extracting video information
[youtube] {22} signature length 40.42, html5 player new
[youtube] {43} signature length 40.42, html5 player new
[youtube] {18} signature length 40.42, html5 player new
[youtube] {5} signature length 40.42, html5 player new
[youtube] {36} signature length 40.42, html5 player new
[youtube] {17} signature length 40.42, html5 player new
[youtube] {136} signature length 40.42, html5 player new
[youtube] {247} signature length 40.42, html5 player new
[youtube] {135} signature length 40.42, html5 player new
[youtube] {244} signature length 40.42, html5 player new
[youtube] {134} signature length 40.42, html5 player new
[youtube] {243} signature length 40.42, html5 player new
[youtube] {133} signature length 40.42, html5 player new
[youtube] {242} signature length 40.42, html5 player new
[youtube] {160} signature length 40.42, html5 player new
[youtube] {278} signature length 40.42, html5 player new
[youtube] {140} signature length 40.42, html5 player new
[youtube] {171} signature length 40.42, html5 player new
[youtube] pD8VcixLmFc: Downloading DASH manifest
WARNING: [youtube] pD8VcixLmFc: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[debug] Invoking downloader on u'https://r3---sn-585pav-ch5e.googlevideo.com/videoplayback?expire=1439623282&gir=yes&sver=3&pcm2cms=yes&requiressl=yes&keepalive=yes&pl=19&ip=46.246.63.198&initcwndbps=4773750&sparams=clen%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&id=a43f15722c4b9857&upn=yMJKowy30x4&mn=sn-585pav-ch5e&source=youtube&mm=31&fexp=9406006%2C9408512%2C9408710%2C9409069%2C9409172%2C9415365%2C9415417%2C9415426%2C9415485%2C9415992%2C9416023%2C9416103%2C9416126%2C9416729%2C9417190%2C9417703%2C9417707%2C9417942%2C9418153%2C9418809%2C9419226&ms=au&mv=m&mt=1439601651&dur=260.440&clen=29548389&ipbits=0&itag=136&key=yt5&mime=video%2Fmp4&lmt=1419351420903470&signature=0953269E5BBED7D3603C612AA6211F5EEC10FA85.C8ECC9F7E812C196A04A84A991D60D342B150FC0&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1579, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1527, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 60, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1860, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
```

**Comment by Makboro** [comment] 2015-08-15 07:24
Yes, there are problems too!!! The obtained download link does not work. Please see a comparative and tests of youtube-dl (latest version) runned in a PC with Windows of France and in other of Latinamerica with the video "Saint Asonia - Better Place" (http://www.youtube.com/watch?v=wAOfEP2OrLU). The problem of the obtained download link with youtube-dl is in france. This is the one that fails (the obtained Latinamerica download link with the same video works without problem):

France (with problems):

https://r3---sn-25ge7nl7.googlevideo.com/videoplayback?ms=au&mt=1439583966&mv=m&ip=(removed by me for security)&clen=63499271&sver=3&id=o-AG6LMXUmS8BEEkeaQ2XK4ecjqZiKxm8eB56_91ViU1CK&dur=220.261&gir=yes&mime=video%2Fmp4&mn=sn-25ge7nl7&sparams=clen%2Cdur%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&gcr=fr&upn=Bsr7c2eUgU8&mm=31&lmt=1438472659978135&expire=1439605686&ipbits=0&initcwndbps=1728750&pl=16&source=youtube&fexp=9408710%2C9409069%2C9412774%2C9415365%2C9415485%2C9416023%2C9416126%2C9416328%2C9416344%2C9416403%2C9416729%2C9416902%2C9417280%2C9417707%2C9418153%2C9418974%2C9419308&key=yt5&requiressl=yes&itag=137&keepalive=yes&signature=4CCC4E360501630AE1EA3398BD9703A8E7A43DCE.32E751034F27D4E20B1B88295AAED65C4F398545&ratebypass=yes

Latinamerica country (working without problem):

https://r3---sn-8ug-njae.googlevideo.com/videoplayback?id=c0039f10fd8eacb5&itag=134&source=youtube&requiressl=yes&ms=au&mm=31&mn=sn-8ug-njae&gcr=cl&mv=m&pcm2cms=yes&pl=24&ratebypass=yes&mime=video/mp4&gir=yes&clen=10726585&lmt=1438472657002937&dur=220.261&signature=11F6065CBF0FCB902966406CE6B0463C6C61DCBF.912C1332C8F3589208515339B02D144CD676F3DC&sver=3&key=dg_yt0&fexp=9408492,9408710,9409069,9409249,9413142,9415365,9415485,9415515,9415659,9416023,9416126,9417707,9417843,9418153,9418199,9418203,9418373,9418393,9419243&upn=nlSxeDOZTHY&mt=1439585474&ip=(removed by me for security)&ipbits=0&expire=1439607201&sparams=ip,ipbits,expire,id,itag,source,requiressl,ms,mm,mn,gcr,mv,pcm2cms,pl,ratebypass,mime,gir,clen,lmt,dur


I see a differences in the length of the value obtained between "id" parameter (please see. for france you get a value "o-AG6LMXUmS8BEEkeaQ2XK4ecjqZiKxm8eB56_91ViU1CK" and for Latinamerica you get "c0039f10fd8eacb5"). I think that is very different. Maybe its this incorrect? Well.. I hope you can help me and you can fix it. Thanks!!!!

**Comment by yan12125** [comment] 2015-08-15 07:27
A duplicate of #6451.

**Closed by yan12125** 2015-08-15 07:27 UTC
