### ISSUE TITLE
Download YouTube videos issue

### ISSUE THREAD

**Issue by sunxvogy** [rg3/youtube-dl#8160] opened 2016-01-07 08:22 UTC
C:\yd.exe --no-cache-dir --no-playlist -o c:\tmpvideo.mp4 http://www.youtube.com/watch?v=rblYSKz_VnI

[youtube] rblYSKz_VnI: Downloading webpage

ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)> (caused by URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))

**Comment by dstftw** [comment] 2016-01-07 08:23
Duplicate of #7309.

**Closed by dstftw** 2016-01-07 08:23 UTC
