### ISSUE TITLE
Trouble d/ling from YouTube.  Getting an error (I believe) related to Python.

### ISSUE THREAD

**Issue by Starfoxian** [rg3/youtube-dl#2123] opened 2014-01-09 01:09 UTC
Hi.  I've lurked on this forum since I first started with youtube-dl and I think I'm posting in the right place.  I updated my youtube-dl today and when I tried to download I get this:

youtube-dl -f 18 http://www.youtube.com/watch?v=oJnz63iJlDo
[youtube] Setting language
[youtube] oJnz63iJlDo: Downloading webpage
[youtube] oJnz63iJlDo: Downloading video info webpage
[youtube] Confirming age
[youtube] oJnz63iJlDo: Extracting video information
[youtube] RTMP download detected
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/bin/youtube-dl/__main__.py", line 18, in <module>
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 761, in main
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 751, in _real_main
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 952, in download
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 493, in extract_info
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 155, in extract
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1336, in _real_extract
KeyError: None
 
I picked a video at random to see if I could download at all and it did download but the output in terminal was odd to say the least.

youtube-dl -f 18 http://www.youtube.com/watch?v=ab9176Srb5Y
[youtube] Setting language
[youtube] ab9176Srb5Y: Downloading webpage
[youtube] ab9176Srb5Y: Downloading video info webpage
[youtube] ab9176Srb5Y: Extracting video information
[youtube] ab9176Srb5Y: Encrypted signatures detected.
[youtube] ab9176Srb5Y: Downloading js player vflwMrwdI
WARNING: Writing cache to u'/home/ysuran/.cache/youtube-dl/youtube-sigfuncs/js_vflwMrwdI_82.json' failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 345, in _extract_signature_function
    write_json_file(cache_spec, cache_fn)
  File "/usr/bin/youtube-dl/youtube_dl/utils.py", line 216, in write_json_file
    with open(fn, 'wb') as f:
IOError: [Errno 13] Permission denied: u'/home/ysuran/.cache/youtube-dl/youtube-sigfuncs/js_vflwMrwdI_82.json'

[youtube] ab9176Srb5Y: Downloading js player vflwMrwdI
WARNING: Writing cache to u'/home/ysuran/.cache/youtube-dl/youtube-sigfuncs/js_vflwMrwdI_85.json' failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 345, in _extract_signature_function
    write_json_file(cache_spec, cache_fn)
  File "/usr/bin/youtube-dl/youtube_dl/utils.py", line 216, in write_json_file
    with open(fn, 'wb') as f:
IOError: [Errno 13] Permission denied: u'/home/ysuran/.cache/youtube-dl/youtube-sigfuncs/js_vflwMrwdI_85.json'

[download] Destination: Eminem - Berzerk (Official) (Explicit)-ab9176Srb5Y.mp4
[download] 100% of 22.54MiB in 00:06

I am unsure if this is the place to ask for help or to merely report issues so they can be addressed.  If this is not the place to seek help, would it be too much to ask for a link to a forum where I could receive assistance?

**Comment by dstftw** [comment] 2016-06-13 21:35
Duplicate of #343.

**Closed by dstftw** 2016-06-13 21:35 UTC

**Comment by johnstonjay** [comment] 2020-04-01 17:30
I am having a similar issue but its only present on OS X not on the Linux Distro or windows. im on version youtube-dl 2020.03.24.

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2019, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 808, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 870, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 235, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 50, in _call_api
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 31, in _get_dailymotion_cookies
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 2831, in _get_cookies
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/Cookie.py", line 583, in __init__
    if input: self.load(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/Cookie.py", line 643, in load
    for k, v in rawdata.items():
AttributeError: 'unicode' object has no attribute 'items'
