### ISSUE TITLE
youtube-dl latest version error The connection has timed 

### ISSUE THREAD

**Issue by rdxhere** [rg3/youtube-dl#13417] opened 2017-06-18 06:44 UTC
The connection has timed out The server at r7---sn-bvvbax-nuae.googlevideo.com is taking too long to respond.

youtube stop to download extract videos on youtube-dl

The server at r7---sn-bvvbax-nuae.googlevideo.com is taking too long to respond.

The site could be temporarily unavailable or too busy. Try again in a few moments.
If you are unable to load any pages, check your computer’s network connection.
If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

**Comment by yan12125** [comment] 2017-06-18 07:50
Duplicate of #13409 and #11779. Please move on to #11779 for further discussions.

**Closed by yan12125** 2017-06-18 07:50 UTC
