### ISSUE TITLE
ExtractorError: No video formats found

### ISSUE THREAD

**Issue by k24u** [rg3/youtube-dl#11426] opened 2016-12-12 15:20 UTC
youtube-dl http://vlive.tv/video/18628 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://vlive.tv/video/18628', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.12
[debug] Python version 2.7.12+ - Linux-4.8.0-30-generic-x86_64-with-Ubuntu-16.10-yakkety
[debug] exe versions: avconv 3.0.2-1ubuntu3, avprobe 3.0.2-1ubuntu3, ffmpeg 3.0.2-1ubuntu3, ffprobe 3.0.2-1ubuntu3, rtmpdump 2.4
[debug] Proxy map: {}
[vlive] 18628: Downloading webpage
[vlive] 18628: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vlive.py", line 64, in _real_extract
    return self._replay(video_id, webpage, long_video_id, key)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vlive.py", line 126, in _replay
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 924, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug

### Description of your *issue*, suggested solution and other information

Downloading fails on vlive when it used to work

**Comment by yan12125** [comment] 2016-12-12 15:32
Could you try #11375?

**Comment by dstftw** [comment] 2016-12-12 15:35
Duplicate of #11383.

**Closed by dstftw** 2016-12-12 15:35 UTC
