### ISSUE TITLE
Bug: Skipping DASH manifest error when downloading from YouTube

### ISSUE THREAD

**Issue by peterlewis** [rg3/youtube-dl#6195] opened 2015-07-11 16:47 UTC
Getting this with somewhat regularity at the moment when downloading from YouTube:

  Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError());

**Comment by dstftw** [comment] 2015-07-11 16:48
Duplicate of #5118.
This is only a warning.

**Closed by dstftw** 2015-07-11 16:48 UTC
