### ISSUE TITLE
Error with private FB video

### ISSUE THREAD

**Issue by danieman** [rg3/youtube-dl#5751] opened 2015-05-19 16:05 UTC
youtube-dl 'https://www.facebook.com/username/videos/123456789012345' -u user@user.com -p password --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.facebook.com/username/videos/1234567890123456', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.10
[debug] Python version 2.7.2 - Darwin-12.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.5, ffprobe 2.5
[debug] Proxy map: {}
[facebook] Downloading login page
[facebook] Logging in
ERROR: Unable to extract h; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 272, in extract
    self.initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 266, in initialize
    self._real_initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 117, in _real_initialize
    self._login()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 103, in _login
    r'name="h"\s+(?:\w+="[^"]+"\s+)*?value="([^"]+)"', login_results, 'h'),
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 555, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract h; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by jaimeMF** [comment] 2015-05-19 16:07
Duplicate of #4902.

**Closed by jaimeMF** 2015-05-19 16:07 UTC

**Comment by danieman** [comment] 2015-05-19 16:10
But was it solved?

**Comment by jaimeMF** [comment] 2015-05-19 16:10
It's still open, so it isn't solved.
