### ISSUE TITLE
Site request: areena.yle.fi

### ISSUE THREAD

**Issue by cyhojoey** [rg3/youtube-dl#7664] opened 2015-11-27 02:41 UTC
Hi,
Would you like to add site support for areena.yle.fi into next new version?

```
youtube-dl.exe -v http://areena.yle.fi/1-3170374
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://areena.yle.fi/1-3170374']
[debug] Encodings: locale cp950, fs mbcs, out cp950, pref cp950
[debug] youtube-dl version 2015.11.24
[debug] Python version 2.7.10 - Windows-XP-5.1.2600-SP3
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 1-3170374: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1-3170374: Downloading webpage
[generic] 1-3170374: Extracting information
ERROR: Unsupported URL: http://areena.yle.fi/1-3170374
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1282, in _real_extract
  File "youtube_dl\compat.pyo", line 248, in compat_etree_fromstring
  File "youtube_dl\compat.pyo", line 237, in _XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: mismatched tag: line 221, column 6
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 663, in extract_info
  File "youtube_dl\extractor\common.pyo", line 290, in extract
  File "youtube_dl\extractor\generic.pyo", line 1887, in _real_extract
UnsupportedError: Unsupported URL: http://areena.yle.fi/1-3170374
```

**Comment by jaimeMF** [comment] 2015-11-27 06:57
Duplicate of #1574.

**Closed by jaimeMF** 2015-11-27 06:57 UTC
