### ISSUE TITLE
[BiliBili]An extractor error (caused by KeyError(u'durl',))

### ISSUE THREAD

**Issue by Luxios** [rg3/youtube-dl#11735] opened 2017-01-15 19:13 UTC
>youtube-dl --verbose https://www.bilibili.com/video/av600625/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.bilibili.com/video/av600625/']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2016.11.22
[debug] Python version 2.7.12 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82597-gd316b21, ffprobe N-82597-gd316b21
[debug] Proxy map: {}
[BiliBili] 600625: Downloading webpage
[BiliBili] 600625: Downloading video info page
ERROR: An extractor error has occurred. (caused by KeyError(u'durl',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "d:\study\python\anaconda2\lib\site-packages\youtube_dl\extractor\common.py", line 357, in extract
    return self._real_extract(url)
  File "d:\study\python\anaconda2\lib\site-packages\youtube_dl\extractor\bilibili.py", line 65, in _real_extract
    for idx, durl in enumerate(video_info['durl']):
KeyError: u'durl'
Traceback (most recent call last):
  File "d:\study\python\anaconda2\lib\site-packages\youtube_dl\YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "d:\study\python\anaconda2\lib\site-packages\youtube_dl\extractor\common.py", line 363, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'durl',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by tomoya92** [comment] 2017-01-16 03:02
i also met

**Comment by yan12125** [comment] 2017-01-16 10:26
Duplicate of #11077

**Closed by yan12125** 2017-01-16 10:26 UTC
