### ISSUE TITLE
Request/Claification for keep audio flag

### ISSUE THREAD

**Issue by Ryonez** [rg3/youtube-dl#8983] opened 2016-03-25 20:19 UTC
Hi,

I'd like to save the audio files of videos for some devices that can't really handle the video.
I've discovered that the --keep-video does save the unmerged audio file. However it also saves the unmerged video files that I don't need.

Is there a way to instruct youtube-dl to to save just the unmerged audio file?

**Comment by dstftw** [comment] 2016-03-25 20:23
No, Duplicate of #8687.

**Closed by dstftw** 2016-03-25 20:23 UTC
