### ISSUE TITLE
Some BBC iplayer videos not working

### ISSUE THREAD

**Issue by selvagem** [rg3/youtube-dl#5790] opened 2015-05-23 14:05 UTC
User:~ user$ youtube-dl http://www.bbc.co.uk/iplayer/episode/b008d4bt/the-nature-of-britain-7-wilderness-britain --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.bbc.co.uk/iplayer/episode/b008d4bt/the-nature-of-britain-7-wilderness-britain', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.20
[debug] Python version 2.7.3 - Darwin-14.3.0-x86_64-i386-64bit
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[bbc.co.uk] b008d4bt: Downloading video page
[bbc.co.uk] b008d3ww: Downloading media selection XML
[debug] Invoking downloader on u'rtmp://bbcfmt.fcod.llnwd.net/a8984/e3?as=adobe-hmac-sha256&av=1&te=connect&mp=iplayerstream/secure_auth/1500kbps/modav/bUnknown-5bac7cd6-62cc-44be-8de9-339680fd120d_b008d3ww_1429258225373.mp4,iplayerstream/secure_auth/480kbps/modav/bUnknown-5bac7cd6-62cc-44be-8de9-339680fd120d_b008d3ww_1429258226048.mp4,iplayerstream/secure_auth/800kbps/modav/bUnknown-5bac7cd6-62cc-44be-8de9-339680fd120d_b008d3ww_1429258222265.mp4&et=1432396967&fmta-token=4c43d98d771ea603bb44befa7a80fe1adcb64141cfacaed1b3405a9b577f7ab1'
[download] Destination: The Nature of Britain, 7. Wilderness Britain-b008d3ww.flv
[debug] rtmpdump command line: rtmpdump --verbose -r 'rtmp://bbcfmt.fcod.llnwd.net/a8984/e3?as=adobe-hmac-sha256&av=1&te=connect&mp=iplayerstream/secure_auth/1500kbps/modav/bUnknown-5bac7cd6-62cc-44be-8de9-339680fd120d_b008d3ww_1429258225373.mp4,iplayerstream/secure_auth/480kbps/modav/bUnknown-5bac7cd6-62cc-44be-8de9-339680fd120d_b008d3ww_1429258226048.mp4,iplayerstream/secure_auth/800kbps/modav/bUnknown-5bac7cd6-62cc-44be-8de9-339680fd120d_b008d3ww_1429258222265.mp4&et=1432396967&fmta-token=4c43d98d771ea603bb44befa7a80fe1adcb64141cfacaed1b3405a9b577f7ab1' -o 'The Nature of Britain, 7. Wilderness Britain-b008d3ww.flv.part' --swfVfy http://www.bbc.co.uk/emp/releases/iplayer/revisions/617463_618125_4/617463_618125_4_emp.swf --pageUrl http://www.bbc.co.uk --app 'a8984/e3?as=adobe-hmac-sha256&av=1&te=connect&mp=iplayerstream/secure_auth/1500kbps/modav/bUnknown-5bac7cd6-62cc-44be-8de9-339680fd120d_b008d3ww_1429258225373.mp4,iplayerstream/secure_auth/480kbps/modav/bUnknown-5bac7cd6-62cc-44be-8de9-339680fd120d_b008d3ww_1429258226048.mp4,iplayerstream/secure_auth/800kbps/modav/bUnknown-5bac7cd6-62cc-44be-8de9-339680fd120d_b008d3ww_1429258222265.mp4&et=1432396967&fmta-token=4c43d98d771ea603bb44befa7a80fe1adcb64141cfacaed1b3405a9b577f7ab1' --playpath mp4:iplayerstream/secure_auth/1500kbps/modav/bUnknown-5bac7cd6-62cc-44be-8de9-339680fd120d_b008d3ww_1429258225373.mp4 --resume --skip 1
[rtmpdump] RTMPDump 2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 0
[rtmpdump] DEBUG: Parsed host    : bbcfmt.fcod.llnwd.net
[rtmpdump] DEBUG: Parsed app     : a8984/e3?as=adobe-hmac-sha256&av=1&te=connect&mp=iplayerstream
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMP
[rtmpdump] DEBUG: Hostname : bbcfmt.fcod.llnwd.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:iplayerstream/secure_auth/1500kbps/modav/bUnknown-5bac7cd6-62cc-44be-8de9-339680fd120d_b008d3ww_1429258225373.mp4
[rtmpdump] DEBUG: tcUrl    : rtmp://bbcfmt.fcod.llnwd.net:1935/a8984/e3?as=adobe-hmac-sha256&av=1&te=connect&mp=iplayerstream/secure_auth/1500kbps/modav/bUnknown-5bac7cd6-62cc-44be-8de9-339680fd120d_b008d3ww_1429258225373.mp4,iplayerstream/secure_auth/480kbps/modav/bUnknown-5bac7cd6-62cc-44be-8de9-339680fd120d_b008d3ww_1429258226048.mp4,iplayerstream/secure_auth/800kbps/modav/bUnknown-5bac7cd6-62cc-44be-8de9-339680fd120d_b008d3ww_1429258222265.mp4&et=1432396967&fmta-token=4c43d98d771ea603bb44befa7a80fe1adcb64141cfacaed1b3405a9b577f7a
[rtmpdump] DEBUG: swfUrl   : http://www.bbc.co.uk/emp/releases/iplayer/revisions/617463_618125_4/617463_618125_4_emp.swf
[rtmpdump] DEBUG: pageUrl  : http://www.bbc.co.uk
[rtmpdump] DEBUG: app      : a8984/e3?as=adobe-hmac-sha256&av=1&te=connect&mp=iplayerstream/secure_auth/1500kbps/modav/bUnknown-5bac7cd6-62cc-44be-8de9-339680fd120d_b008d3ww_1429258225373.mp4,iplayerstream/secure_auth/480kbps/modav/bUnknown-5bac7cd6-62cc-44be-8de9-339680fd120d_b008d3ww_1429258226048.mp4,iplayerstream/secure_auth/800kbps/modav/bUnknown-5bac7cd6-62cc-44be-8de9-339680fd120d_b008d3ww_1429258222265.mp4&et=1432396967&fmta-token=4c43d98d771ea603bb44befa7a80fe1adcb64141cfacaed1b3405a9b577f7ab1
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: SWFSHA256:
[rtmpdump] DEBUG: b6 74 7f 89 f9 ec 6a 60 c1 a4 b5 8b b1 18 b0 fa
[rtmpdump] DEBUG: 65 18 86 24 c2 8a 1a a3 2f 72 0f 0b 80 59 dd 7f
[rtmpdump] DEBUG: SWFSize  : 595316
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 0 bytes
[rtmpdump] RTMPDump 2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 0
[rtmpdump] DEBUG: Parsed host    : bbcfmt.fcod.llnwd.net
[rtmpdump] DEBUG: Parsed app     : a8984/e3?as=adobe-hmac-sha256&av=1&te=connect&mp=iplayerstream
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMP
[rtmpdump] DEBUG: Hostname : bbcfmt.fcod.llnwd.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:iplayerstream/secure_auth/1500kbps/modav/bUnknown-5bac7cd6-62cc-44be-8de9-339680fd120d_b008d3ww_1429258225373.mp4
[rtmpdump] DEBUG: tcUrl    : rtmp://bbcfmt.fcod.llnwd.net:1935/a8984/e3?as=adobe-hmac-sha256&av=1&te=connect&mp=iplayerstream/secure_auth/1500kbps/modav/bUnknown-5bac7cd6-62cc-44be-8de9-339680fd120d_b008d3ww_1429258225373.mp4,iplayerstream/secure_auth/480kbps/modav/bUnknown-5bac7cd6-62cc-44be-8de9-339680fd120d_b008d3ww_1429258226048.mp4,iplayerstream/secure_auth/800kbps/modav/bUnknown-5bac7cd6-62cc-44be-8de9-339680fd120d_b008d3ww_1429258222265.mp4&et=1432396967&fmta-token=4c43d98d771ea603bb44befa7a80fe1adcb64141cfacaed1b3405a9b577f7a
[rtmpdump] DEBUG: swfUrl   : http://www.bbc.co.uk/emp/releases/iplayer/revisions/617463_618125_4/617463_618125_4_emp.swf
[rtmpdump] DEBUG: pageUrl  : http://www.bbc.co.uk
[rtmpdump] DEBUG: app      : a8984/e3?as=adobe-hmac-sha256&av=1&te=connect&mp=iplayerstream/secure_auth/1500kbps/modav/bUnknown-5bac7cd6-62cc-44be-8de9-339680fd120d_b008d3ww_1429258225373.mp4,iplayerstream/secure_auth/480kbps/modav/bUnknown-5bac7cd6-62cc-44be-8de9-339680fd120d_b008d3ww_1429258226048.mp4,iplayerstream/secure_auth/800kbps/modav/bUnknown-5bac7cd6-62cc-44be-8de9-339680fd120d_b008d3ww_1429258222265.mp4&et=1432396967&fmta-token=4c43d98d771ea603bb44befa7a80fe1adcb64141cfacaed1b3405a9b577f7ab1
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: SWFSHA256:
[rtmpdump] DEBUG: b6 74 7f 89 f9 ec 6a 60 c1 a4 b5 8b b1 18 b0 fa
[rtmpdump] DEBUG: 65 18 86 24 c2 8a 1a a3 2f 72 0f 0b 80 59 dd 7f
[rtmpdump] DEBUG: SWFSize  : 595316
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.

ERROR: rtmpdump exited with code 1
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 405, in main
    _real_main(argv)
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 395, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1486, in download
    res = self.extract_info(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 660, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 706, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1157, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1419, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1361, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/rtmp.py", line 202, in real_download
    self.report_error('rtmpdump exited with code %d' % retval)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 155, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 527, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 489, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

**Comment by dstftw** [comment] 2015-05-23 22:03
Duplicate of #2732.
You can try downloading from different content supplier by specifying format code to `-f`. See `-F` for the list of format codes.

**Closed by dstftw** 2015-05-23 22:03 UTC
