### ISSUE TITLE
500: Internal Server Error

### ISSUE THREAD

**Issue by videoguy-canada** [rg3/youtube-dl#8945] opened 2016-03-23 14:47 UTC
Hey guys, I posted a thread yesterday which was quickly closed as a duplicate.  Getting a HTTP Error 500: Internal Server Error

Is there any way that someone can look into it and try to create a patch?  I will donate or whatever, just would love to get it back all.  All files are blocked except for one.

http://www.vevo.com/watch/iggyazalea/Team-Dance-Video/USUV71600624

This is the only file that downloads correctly.  Not sure why, but it seems to work.  If you guys can help fix, I'd be forever grateful.

Thanks for your time

Cheers

**Comment by dstftw** [comment] 2016-03-23 14:49
Duplicate of #8900.

**Closed by dstftw** 2016-03-23 14:49 UTC
