### ISSUE TITLE
AMC Networks | HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by techworley** [rg3/youtube-dl#14850] opened 2017-11-25 19:58 UTC
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.15**
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### Unable to download from AMC Networks 
```
youtube-dl -v --ap-mso Comcast_SSO --ap-username REDACTED --ap-password REDACTED -o '~/Movies/%(series)s/%(season_number)s - %(season)s/%(episode_number)s - %(episode)s - %(title)s.%(ext)s' http://www.amc.com/shows/the-walking-dead/full-episodes/season-08/episode-05/the-big-scary-u

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--ap-mso', u'Comcast_SSO', u'--ap-username', u'PRIVATE', u'--ap-password', u'PRIVATE', u'-o', u'~/Movies/%(series)s/%(season_number)s - %(season)s/%(episode_number)s - %(episode)s - %(title)s.%(ext)s', u'http://www.amc.com/shows/the-walking-dead/full-episodes/season-08/episode-05/the-big-scary-u']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.11.15
[debug] Python version 2.7.14 - Darwin-17.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4
[debug] Proxy map: {}
[AMCNetworks] the-big-scary-u: Downloading webpage
[AMCNetworks] the-big-scary-u: Downloading JSON metadata
[AMCNetworks] V1uio7Ft7ton: Downloading Provider Redirect Page
[AMCNetworks] V1uio7Ft7ton: Logging in
[AMCNetworks] V1uio7Ft7ton: Retrieving Session
ERROR: Unable to download webpage: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 506, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2196, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

**Comment by yan12125** [comment] 2017-11-27 13:42
Most likely a duplicate of #11538. Comcast_SSO is not always working as of now.

**Closed by yan12125** 2017-11-27 13:42 UTC

**Comment by GordLacey** [comment] 2018-04-03 22:43
I'm having the same problem, but on Cartoon Network. Could it be that there's a CAPTCHA on the Comcast login page that's not being filled out?

> youtube-dl --ap-mso Comcast_SSO --ap-username PRIVATE@comcast.net --ap-password PRIVATE https://www.cartoonnetwork.com/video/nexo-knights/weekend-at-halberts-episode.html --verbose
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: [u'--ap-mso', u'Comcast_SSO', u'--ap-username', u'PRIVATE', u'--ap-password', u'PRIVATE', u'https://www.cartoonnetwork.com/video/nexo-knights/weekend-at-halberts-episode.html', u'--verbose']
> [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2018.04.03
> [debug] Python version 2.7.10 (CPython) - Darwin-16.7.0-x86_64-i386-64bit
> [debug] exe versions: avconv 12.1, avprobe 12.1, ffmpeg 3.3.3, ffprobe 3.3.3
> [debug] Proxy map: {}
> [CartoonNetwork] weekend-at-halberts: Downloading webpage
> [CartoonNetwork] 598df84d240214953c1bb13eaeef2e369a59fb46: Downloading XML
> [CartoonNetwork] 598df84d240214953c1bb13eaeef2e369a59fb46: Downloading Provider Redirect Page
> [CartoonNetwork] 598df84d240214953c1bb13eaeef2e369a59fb46: Logging in
> [CartoonNetwork] 598df84d240214953c1bb13eaeef2e369a59fb46: Retrieving Session
> ERROR: Unable to download webpage: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
>   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 519, in _request_webpage
>     return self._downloader.urlopen(url_or_request)
>   File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2199, in urlopen
>     return self._opener.open(req, timeout=self._socket_timeout)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
>     response = meth(req, response)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
>     return self._call_chain(*args)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
>     result = func(*args)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
>     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
