### ISSUE TITLE
Render Subtitle after Download stop with error [crunchyroll]

### ISSUE THREAD

**Issue by kitokirisaki** [rg3/youtube-dl#9207] opened 2016-04-15 16:43 UTC
The file was not rendered and breaks with the following error.  When I look at the command of FFMPEG, then I do not see that the caption is rendered with.

Comand: youtube-dl -uUSER http://www.crunchyroll.com/twin-star-exorcists --recode-video mp4 --sub-lang deDE --write-sub --sub-format ass --embed-subs -v

"
[ffmpeg] Converting video from flv to mp4, Destination: Twin Star Exorcists Folge 1 – Zwei füreinander Bestimmte-702557.mp4
[debug] ffmpeg command line: ffmpeg -y -i 'file:Twin Star Exorcists Folge 1 – Zwei füreinander Bestimmte-702557.flv' 'file:Twin Star Exorcists Folge 1 – Zwei füreinander Bestimmte-702557.mp4'
ERROR: [aac @ 0x1102ec0] The encoder 'aac' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.
"

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-uUSER', u'http://www.crunchyroll.com/twin-star-exorcists', u'--recode-video', u'mp4', u'--sub-lang', u'deDE', u'--write-sub', u'--sub-format', u'ass', u'--embed-subs', u'-v']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.13
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.3
[debug] exe versions: ffmpeg 2.8.6-1, ffprobe 2.8.6-1, rtmpdump 2.4
[debug] Proxy map: {}
[crunchyroll:playlist] Logging in
[crunchyroll:playlist] twin-star-exorcists: Downloading webpage
[download] Downloading playlist: Twin Star Exorcists
[crunchyroll:playlist] playlist Twin Star Exorcists: Collected 2 video ids (downloading 2 of them)
[download] Downloading video 1 of 2
[Crunchyroll] Logging in
[Crunchyroll] 702557: Downloading webpage
[Crunchyroll] 702557: Downloading media info
[Crunchyroll] 702557: Downloading media info for 360p
[Crunchyroll] 702557: Downloading media info for 480p
[Crunchyroll] 702557: Downloading media info for 720p
[Crunchyroll] 702557: Downloading media info for 1080p
[Crunchyroll] 702557: Downloading subtitles for English (US)
[Crunchyroll] 702557: Downloading subtitles for العربية
[Crunchyroll] 702557: Downloading subtitles for Italiano
[Crunchyroll] 702557: Downloading subtitles for Deutsch
[info] Writing video subtitles to: Twin Star Exorcists Folge 1 – Zwei füreinander Bestimmte-702557.deDE.ass
[debug] Invoking downloader on u'rtmpe://cp150757.edgefcs.net/ondemand/?auth=daEdbclbQa2aRajcpaHb3aKcoaec9dpbnd4-bxerwI-dHa-mCExnqLAAuD&aifp=0009&slist=c21/s/ve2191381/video.mp4'
[download] Destination: Twin Star Exorcists Folge 1 – Zwei füreinander Bestimmte-702557.flv
[debug] rtmpdump command line: rtmpdump --verbose -r 'rtmpe://cp150757.edgefcs.net/ondemand/?auth=daEdbclbQa2aRajcpaHb3aKcoaec9dpbnd4-bxerwI-dHa-mCExnqLAAuD&aifp=0009&slist=c21/s/ve2191381/video.mp4' -o 'Twin Star Exorcists Folge 1 – Zwei füreinander Bestimmte-702557.flv.part' --playpath mp4:c21/s/ve2191381/video.mp4 --resume --skip 1
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : cp150757.edgefcs.net
[rtmpdump] DEBUG: Parsed app     : ondemand/?auth=daEdbclbQa2aRajcpaHb3aKcoaec9dpbnd4-bxerwI-dHa-mCExnqLAAuD&aifp=0009&slist=c21/s/ve2191381/video.mp4
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : cp150757.edgefcs.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:c21/s/ve2191381/video.mp4
[rtmpdump] DEBUG: tcUrl    : rtmpe://cp150757.edgefcs.net:1935/ondemand/?auth=daEdbclbQa2aRajcpaHb3aKcoaec9dpbnd4-bxerwI-dHa-mCExnqLAAuD&aifp=0009&slist=c21/s/ve2191381/video.mp4
[rtmpdump] DEBUG: app      : ondemand/?auth=daEdbclbQa2aRajcpaHb3aKcoaec9dpbnd4-bxerwI-dHa-mCExnqLAAuD&aifp=0009&slist=c21/s/ve2191381/video.mp4
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Setting buffer time to: 36000000ms
[rtmpdump] Connecting ...
[rtmpdump] DEBUG: RTMP_Connect1, ... connected, handshaking
[rtmpdump] DEBUG: HandShake: Client type: 06
[rtmpdump] DEBUG: HandShake: DH pubkey position: 472
[rtmpdump] DEBUG: HandShake: Client digest offset: 1383
[rtmpdump] DEBUG: HandShake: Initial client digest: 
[rtmpdump] DEBUG: 46 db f0 9a 2b 19 fa f4 67 1a e6 14 c5 53 fb 19
[rtmpdump] DEBUG: 7b 04 cf 34 f8 e8 4b f8 19 8c b6 fc 50 85 f3 ea
[rtmpdump] DEBUG: HandShake: Type Answer   : 08
[rtmpdump] WARNING: HandShake: Type mismatch: client sent 6, server answered 8
[rtmpdump] DEBUG: HandShake: Server Uptime : 439950781
[rtmpdump] DEBUG: HandShake: FMS Version   : 5.0.7.1
[rtmpdump] DEBUG: HandShake: Server DH public key offset: 143
[rtmpdump] DEBUG: HandShake: Secret key: 
[rtmpdump] DEBUG: 8d 4b dc c8 c0 f9 c9 bb 97 6f 43 8a 72 7b ee 35
[rtmpdump] DEBUG: 95 06 dc 5a c7 f2 54 61 16 f9 6e 97 2b 1e d1 09
[rtmpdump] DEBUG: 87 d3 f9 26 97 83 f3 f9 be bf 00 b8 5b b8 53 a5
[rtmpdump] DEBUG: 51 c3 95 06 17 27 c2 7c 84 92 b1 c8 5b 58 d3 bc
[rtmpdump] DEBUG: 25 a6 39 15 0b 9a 18 58 ee 65 0d e4 b7 20 6e 82
[rtmpdump] DEBUG: c1 17 4e 70 d4 88 72 9b 51 e4 67 b4 2b 81 4d 78
[rtmpdump] DEBUG: f1 ae e3 ea 83 23 61 2e 34 66 ce be a2 fc 54 85
[rtmpdump] DEBUG: 08 2f 7f f1 23 bf fe e2 03 70 17 0d 94 53 a8 3b
[rtmpdump] DEBUG: RC4 Out Key: 
[rtmpdump] DEBUG: 56 22 40 41 25 4f fc b7 5f 9d 5a ce 79 1e d8 5b
[rtmpdump] DEBUG: RC4 In Key: 
[rtmpdump] DEBUG: e8 3c 7e b5 07 f6 73 71 86 a1 4f 79 2f fd 01 34
[rtmpdump] DEBUG: HandShake: Calculated digest key from secure key and server digest: 
[rtmpdump] DEBUG: 96 c3 dd d0 8e b1 2a 3b 90 b8 ec 5a ea e8 f8 c7
[rtmpdump] DEBUG: 4d 9b dc 4a be e9 41 34 1f b9 75 9c 72 1b 72 59
[rtmpdump] DEBUG: HandShake: Client signature calculated:
[rtmpdump] DEBUG: 74 01 6c ce 47 16 2c a0 a9 ec b6 be 1c cf cc fa
[rtmpdump] DEBUG: 35 02 53 69 05 1b 5c e2 74 42 a1 28 a0 56 62 d6
[rtmpdump] DEBUG: HandShake: Server sent signature:
[rtmpdump] DEBUG: 0b f6 07 6f 2f f7 1e e1 fd e6 28 99 b9 41 56 ae
[rtmpdump] DEBUG: c7 f2 83 c3 0e 8e cf af 25 a6 79 ce cf c3 0f 39
[rtmpdump] DEBUG: HandShake: Digest key: 
[rtmpdump] DEBUG: 32 41 4b a2 e1 10 44 01 d1 01 e9 26 7b cb 85 99
[rtmpdump] DEBUG: eb 59 a0 a0 aa 99 89 07 67 6e 59 7f 68 3b 33 76
[rtmpdump] DEBUG: HandShake: Signature calculated:
[rtmpdump] DEBUG: 0b f6 07 6f 2f f7 1e e1 fd e6 28 99 b9 41 56 ae
[rtmpdump] DEBUG: c7 f2 83 c3 0e 8e cf af 25 a6 79 ce cf c3 0f 39
[rtmpdump] DEBUG: HandShake: Genuine Adobe Flash Media Server
[rtmpdump] DEBUG: HandShake: Handshaking finished....
[rtmpdump] DEBUG: RTMP_Connect1, handshaked
[rtmpdump] DEBUG: Invoking connect
[rtmpdump] INFO: Connected...
[rtmpdump] DEBUG: HandleServerBW: server BW = 1250000
[rtmpdump] DEBUG: HandleClientBW: client BW = 1250000 2
[rtmpdump] DEBUG: HandleChangeChunkSize, received: chunk size change to 4096
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 242 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:             fmsVer, STRING:	FMS/5,0,7,7054>
[rtmpdump] DEBUG: Property: <Name:       capabilities, NUMBER:	127.00>
[rtmpdump] DEBUG: Property: <Name:               mode, NUMBER:	1.00>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetConnection.Connect.Success>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:	Connection succeeded.>
[rtmpdump] DEBUG: Property: <Name:     objectEncoding, NUMBER:	0.00>
[rtmpdump] DEBUG: Property: <Name:               data, ECMA_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:            version, STRING:	5,0,7,7054>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_result>
[rtmpdump] DEBUG: HandleInvoke, received result for method call <connect>
[rtmpdump] DEBUG: sending ctrl. type: 0x0003
[rtmpdump] DEBUG: Invoking createStream
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 21 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onBWDone>
[rtmpdump] DEBUG: Invoking _checkbw
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 29 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_result>
[rtmpdump] DEBUG: HandleInvoke, received result for method call <createStream>
[rtmpdump] DEBUG: SendPlay, seekTime=0, stopTime=0, sending play: mp4:c21/s/ve2191381/video.mp4
[rtmpdump] DEBUG: Invoking play
[rtmpdump] DEBUG: sending ctrl. type: 0x0003
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 10275 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: HandleCtrl, received ctrl. type: 4, len: 6
[rtmpdump] DEBUG: HandleCtrl, Stream IsRecorded 1
[rtmpdump] DEBUG: HandleChangeChunkSize, received: chunk size change to 4096
[rtmpdump] DEBUG: HandleCtrl, received ctrl. type: 0, len: 6
[rtmpdump] DEBUG: HandleCtrl, Stream Begin 1
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 192 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetStream.Play.Reset>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:	Playing and resetting c21/s/ve2191381/video.mp4.>
[rtmpdump] DEBUG: Property: <Name:            details, STRING:	c21/s/ve2191381/video.mp4>
[rtmpdump] DEBUG: Property: <Name:           clientid, STRING:	rAAXQLLA>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onStatus>
[rtmpdump] DEBUG: HandleInvoke, onStatus: NetStream.Play.Reset
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 186 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetStream.Play.Start>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:	Started playing c21/s/ve2191381/video.mp4.>
[rtmpdump] DEBUG: Property: <Name:            details, STRING:	c21/s/ve2191381/video.mp4>
[rtmpdump] DEBUG: Property: <Name:           clientid, STRING:	rAAXQLLA>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onStatus>
[rtmpdump] DEBUG: HandleInvoke, onStatus: NetStream.Play.Start
[rtmpdump] Starting download at: 0.000 kB
[rtmpdump] DEBUG: RTMP_ClientPacket, received: notify 24 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: ignoring too small audio packet: size: 0
[rtmpdump] DEBUG: RTMP_ClientPacket, received: notify 44 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetStream.Data.Start>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: RTMP_ClientPacket, received: notify 494 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:           duration, NUMBER:	1450.94>
[rtmpdump] DEBUG: Property: <Name:       moovPosition, NUMBER:	32.00>
[rtmpdump] DEBUG: Property: <Name:              width, NUMBER:	1920.00>
[rtmpdump] DEBUG: Property: <Name:             height, NUMBER:	1080.00>
[rtmpdump] DEBUG: Property: <Name:       videocodecid, STRING:	avc1>
[rtmpdump] DEBUG: Property: <Name:       audiocodecid, STRING:	mp4a>
[rtmpdump] DEBUG: Property: <Name:         avcprofile, NUMBER:	100.00>
[rtmpdump] DEBUG: Property: <Name:           avclevel, NUMBER:	40.00>
[rtmpdump] DEBUG: Property: <Name:             aacaot, NUMBER:	2.00>
[rtmpdump] DEBUG: Property: <Name:     videoframerate, NUMBER:	23.98>
[rtmpdump] DEBUG: Property: <Name:    audiosamplerate, NUMBER:	44100.00>
[rtmpdump] DEBUG: Property: <Name:      audiochannels, NUMBER:	2.00>
[rtmpdump] DEBUG: Property: <Name:          trackinfo, STRICT_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:             length, NUMBER:	17392500.00>
[rtmpdump] DEBUG: Property: <Name:          timescale, NUMBER:	11988.00>
[rtmpdump] DEBUG: Property: <Name:           language, STRING:	und>
[rtmpdump] DEBUG: Property: <Name:  sampledescription, STRICT_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:         sampletype, STRING:	avc1>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:             length, NUMBER:	63986688.00>
[rtmpdump] DEBUG: Property: <Name:          timescale, NUMBER:	44100.00>
[rtmpdump] DEBUG: Property: <Name:           language, STRING:	und>
[rtmpdump] DEBUG: Property: <Name:  sampledescription, STRICT_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:         sampletype, STRING:	mp4a>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] INFO: Metadata:
[rtmpdump] INFO:   duration              1450.94
[rtmpdump] INFO:   moovPosition          32.00
[rtmpdump] INFO:   width                 1920.00
[rtmpdump] INFO:   height                1080.00
[rtmpdump] INFO:   videocodecid          avc1
[rtmpdump] INFO:   audiocodecid          mp4a
[rtmpdump] INFO:   avcprofile            100.00
[rtmpdump] INFO:   avclevel              40.00
[rtmpdump] INFO:   aacaot                2.00
[rtmpdump] INFO:   videoframerate        23.98
[rtmpdump] INFO:   audiosamplerate       44100.00
[rtmpdump] INFO:   audiochannels         2.00
[rtmpdump] INFO: trackinfo:
[rtmpdump] INFO:   length                17392500.00
[rtmpdump] INFO:   timescale             11988.00
[rtmpdump] INFO:   language              und
[rtmpdump] INFO: sampledescription:
[rtmpdump] INFO:   sampletype            avc1
[rtmpdump] INFO:   length                63986688.00
[rtmpdump] INFO:   timescale             44100.00
[rtmpdump] INFO:   language              und
[rtmpdump] INFO: sampledescription:
[rtmpdump] INFO:   sampletype            mp4a
[download] 7.97KiB at Unknown speed (00:00)
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 20515 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 30755 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 40995 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 51235 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 61475 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[download] 215.89KiB at Unknown speed (00:00)
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 71717 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 81957 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 92197 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[download] 327.22KiB at Unknown speed (00:00)
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 102437 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 112677 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 122917 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 133157 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[download] 455.22KiB at Unknown speed (00:01)
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 143397 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 153637 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[download] 519.22KiB at Unknown speed (00:01)
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 163877 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 174117 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[download]   0.1% of ~632.05MiB at Unknown speed ETA Unknown ETA
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 184357 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 194597 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 40 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwdone>
[download]  48.7% of ~472.23MiB at  1.19MiB/s ETA 03:22
[rtmpdump] DEBUG: HandleCtrl, received ctrl. type: 6, len: 6
[rtmpdump] DEBUG: HandleCtrl, Ping 440100891
[rtmpdump] DEBUG: sending ctrl. type: 0x0007
[download]  99.9% of ~555.17MiB at  1.20MiB/s ETA 00:00
[rtmpdump] DEBUG: ignoring too small audio packet: size: 0
[rtmpdump] DEBUG: RTMP_ClientPacket, received: notify 102 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetStream.Play.Complete>
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	status>
[rtmpdump] DEBUG: Property: <Name:           duration, NUMBER:	460.00>
[rtmpdump] DEBUG: Property: <Name:              bytes, NUMBER:	581704357.00>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleCtrl, received ctrl. type: 1, len: 6
[rtmpdump] DEBUG: HandleCtrl, Stream EOF 1
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 196 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetStream.Play.Stop>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:	Stopped playing c21/s/ve2191381/video.mp4.>
[rtmpdump] DEBUG: Property: <Name:            details, STRING:	c21/s/ve2191381/video.mp4>
[rtmpdump] DEBUG: Property: <Name:           clientid, STRING:	rAAXQLLA>
[rtmpdump] DEBUG: Property: <Name:             reason, STRING:	>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onStatus>
[rtmpdump] DEBUG: HandleInvoke, onStatus: NetStream.Play.Stop
[rtmpdump] DEBUG: Invoking deleteStream
[rtmpdump] DEBUG: Got Play.Complete or Play.Stop from server. Assuming stream is complete
[download]  99.9% of ~555.31MiB at  1.20MiB/s ETA 00:00
[rtmpdump] DEBUG: RTMP_Read returned: 18409
[rtmpdump] Download complete
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 581704194 bytes
[download] 100% of 554.76MiB
[ffmpeg] Converting video from flv to mp4, Destination: Twin Star Exorcists Folge 1 – Zwei füreinander Bestimmte-702557.mp4
[debug] ffmpeg command line: ffmpeg -y -i 'file:Twin Star Exorcists Folge 1 – Zwei füreinander Bestimmte-702557.flv' 'file:Twin Star Exorcists Folge 1 – Zwei füreinander Bestimmte-702557.mp4'
ERROR: [aac @ 0x1102ec0] The encoder 'aac' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1776, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 325, in run
    self.run_ffmpeg(path, outpath, options)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 172, in run_ffmpeg
    self.run_ffmpeg_multiple_files([path], out_path, opts)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 168, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError

**Comment by yan12125** [comment] 2016-04-15 17:19
Duplicate of #1027.

**Closed by yan12125** 2016-04-15 17:19 UTC
