### ISSUE TITLE
iqiyi.com Can't find any video 

### ISSUE THREAD

**Issue by cha0ran** [rg3/youtube-dl#18059] opened 2018-11-03 17:35 UTC
```
$ youtube-dl http://www.iqiyi.com/w_19s3ippazd.html -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'http://www.iqiyi.com/w_19s3ippazd.html', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.11.03
[debug] Python version 2.7.10 (CPython) - Darwin-18.0.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Proxy map: {'http': 'http://127.0.0.1:6152', 'https': 'http://127.0.0.1:6152'}
[iqiyi] temp_id: download video page
ERROR: Can't find any video; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/iqiyi.py", line 352, in _real_extract
    raise ExtractorError('Can\'t find any video')
ExtractorError: Can't find any video; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

**Comment by remitamine** [comment] 2018-11-03 17:56
Duplicate of #16852

**Closed by remitamine** 2018-11-03 17:56 UTC
