### ISSUE TITLE
Vimeo format change...

### ISSUE THREAD

**Issue by artphotodude** [rg3/youtube-dl#7474] opened 2015-11-12 17:55 UTC
Here is the Verbose on it:

---
youtube-dl --verbose https://vimeo.com/144566059
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://vimeo.com/144566059']
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2015.11.10
[debug] Python version 2.7.8 - Darwin-8.11.0-Power_Macintosh-powerpc-32bit
[debug] exe versions: none
[debug] Proxy map: {}
[vimeo] 144566059: Downloading webpage
[vimeo] 144566059: Extracting information
[vimeo] 144566059: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 378, in _real_extract
    view_count = int(self._search_regex(r'UserPlays:(\d+)', webpage, 'view count'))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract view count; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 427, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 766, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
---

**Comment by dstftw** [comment] 2015-11-12 18:16
Duplicate of #7460.

**Closed by dstftw** 2015-11-12 18:16 UTC
