### ISSUE TITLE
Site request: Hulu (or am I doing this wrong?)

### ISSUE THREAD

**Issue by keybounce** [rg3/youtube-dl#6234] opened 2015-07-15 04:48 UTC
I was hoping to download some videos from Hulu. Specifically, a playlist of free episodes

http://www.hulu.com/grid/hacksign?categories=subtitled

But YouTube-dl doesn't seem to support Hulu.

**Comment by jaimeMF** [comment] 2015-07-15 09:18
Duplicate of #1629.

**Closed by jaimeMF** 2015-07-15 09:18 UTC
