### ISSUE TITLE
--output is not working properly

### ISSUE THREAD

**Issue by WeWin55** [rg3/youtube-dl#5576] opened 2015-05-02 14:49 UTC
Hey,

Im trying to download a video:
I have f bestvideo[height<=?1080]+bestaudio/best in my settings conf.
Here is my script:
youtube-dl -w --output '%(uploader)s %(title)s %(resolution)s' --write-thumbnail  "https://www.youtube.com/watch?v=mA9B3I44BHg"

I starts downloading, but after the avconv warning it says:

ERROR: Best of PietSmiet QUICKY # 99 - Rage Mode - Deactivated «» Best of PietSmiet _ HD 1920x1080.temp: Invalid argument

I dont know what to do.

**Comment by dstftw** [comment] 2015-05-02 14:54
Post the **full** output you get when running [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by dstftw** [comment] 2015-05-02 14:58
Duplicate of #5535.
For now you have to append an extension to output template: `-o %(uploader)s %(title)s %(resolution)s.%(ext)s`.

**Closed by dstftw** 2015-05-02 14:58 UTC
