### ISSUE TITLE
Batch Video Download failed

### ISSUE THREAD

**Issue by raj6996** [rg3/youtube-dl#11143] opened 2016-11-08 20:07 UTC
I am try to batch videos download from this url https://www.facebook.com/acervoarrocha.com.br/videos/
here is I got issue:

C:\Users\ur>youtube-dl https://www.facebook.com/acervoarrocha.com.br/videos/
[generic] videos: Requesting header
WARNING: Falling back on generic information extractor.
[generic] videos: Downloading webpage
[generic] videos: Extracting information
[redirect] Following redirect to https://www.facebook.com/acervoarrocha.com.br/videos/?_fb_noscript=1
[generic] ?_fb_noscript=1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?_fb_noscript=1: Downloading webpage
[generic] ?_fb_noscript=1: Extracting information
ERROR: Unsupported URL: https://www.facebook.com/acervoarrocha.com.br/videos/?_fb_noscript=1

**Comment by yan12125** [comment] 2016-11-09 04:14
Duplicate of #10563

**Closed by yan12125** 2016-11-09 04:14 UTC
