### ISSUE TITLE
YoutubeDL.exe does not work when special characters are in path

### ISSUE THREAD

**Issue by heil-stalin** [rg3/youtube-dl#6174] opened 2015-07-07 20:41 UTC
My username in Windows 7 is literally an infinite sign (∞), and YoutubeDL.exe does not work when trying to run it with a "special character" in the path. 

```
C:\Users\∞\Downloads>youtube-dl.exe https://www.youtube.com/watch?v=eQWka7VvUrw
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\py2exe\boot_common.py", line 92, in <modul
e>
ImportError: No module named linecache
Traceback (most recent call last):
  File "<install zipextimporter>", line 1, in <module>
ImportError: No module named zipextimporter
Traceback (most recent call last):
  File "__main__.py", line 2, in <module>
ImportError: No module named __future__
```

But from a "normal" path, it works perfectly fine.

**Comment by dstftw** [comment] 2015-07-09 15:27
Duplicate of #2919.

**Closed by dstftw** 2015-07-09 15:27 UTC
