### ISSUE TITLE
ThePlatform: always gives 403 errors

### ISSUE THREAD

**Issue by pabs3** [rg3/youtube-dl#5998] opened 2015-06-16 12:52 UTC
All of the watch now links on SBS movies no longer work:

http://www.sbs.com.au/movies/article/2015/06/08/tv-movie-guide-highlights-15-21-june

```
$ python -m youtube_dl --verbose --print-traffic http://www.sbs.com.au/ondemand/video/28304963895/mancora
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--print-traffic', u'http://www.sbs.com.au/ondemand/video/28304963895/mancora']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.15
[debug] Git HEAD: f3aecb2
[debug] Python version 2.7.10 - Linux-4.0.0-1-amd64-x86_64-with-debian-stretch-sid
[debug] exe versions: avconv 11.4-6, avprobe 11.4-6, rtmpdump 2.4
[debug] Proxy map: {}
[SBS] 28304963895: Downloading webpage
send: u'GET /ondemand/video/28304963895/mancora HTTP/1.1\r\nHost: www.sbs.com.au\r\nAccept-Language: en-us,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: Apache
header: X-Powered-By: PHP/5.3.3
header: X-Request-Id: d12f1b3e5eeb1eacd4cf315bc0b32eae
header: X-Cache: HIT
header: Cache-Control: public, max-age=753, must-revalidate
header: Expires: Tue, 16 Jun 2015 13:00:00 GMT
header: X-Source: C
header: Content-Type: text/html; charset=UTF-8
header: Content-Encoding: gzip
header: Content-Length: 20277
header: Accept-Ranges: bytes
header: Date: Tue, 16 Jun 2015 12:49:58 GMT
header: Connection: close
header: Via: HCDS (kp01)
header: X-HCDS-Status: HIT (C)
header: X-HCDS-Age: 151
[ThePlatform] 43ZwpnFuufzT: Downloading XML
send: u'GET /s/Bgtm9B/43ZwpnFuufzT/meta.smil?format=smil&mbr=true HTTP/1.1\r\nHost: link.theplatform.com\r\nAccept-Language: en-us,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Tue, 16 Jun 2015 12:49:59 GMT
header: Access-Control-Allow-Origin: *
header: X-Cache: HIT from link.theplatform.com:80
header: Cache-Control: no-cache, no-store
header: Content-Type: application/smil; charset=UTF-8
header: Content-Length: 5603
header: Server: Jetty(8.1.16.TP-SNAPSHOT)
header: Connection: close
[ThePlatform] 43ZwpnFuufzT: Downloading webpage
send: u'GET /s/Bgtm9B/43ZwpnFuufzT?format=preview HTTP/1.1\r\nHost: link.theplatform.com\r\nAccept-Language: en-us,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Tue, 16 Jun 2015 12:50:00 GMT
header: Access-Control-Allow-Origin: *
header: X-Cache: HIT from link.theplatform.com:80
header: Cache-Control: no-cache, no-store
header: Content-Type: text/plain;charset=UTF-8
header: Content-Length: 1615
header: Server: Jetty(8.1.16.TP-SNAPSHOT)
header: Connection: close
[debug] Invoking downloader on 'http://sbsauvod-f.akamaihd.net/SBS_Production/managed/2015/06/10/2015-06-10_278125_1500K.mp4'
send: u'GET /SBS_Production/managed/2015/06/10/2015-06-10_278125_1500K.mp4 HTTP/1.1\r\nHost: sbsauvod-f.akamaihd.net\r\nAccept-Encoding: identity\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nConnection: close\r\nAccept-Language: en-us,en;q=0.5\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)\r\n\r\n'
reply: 'HTTP/1.1 403 Forbidden\r\n'
header: Server: AkamaiGHost
header: Mime-Version: 1.0
header: Content-Type: text/html
header: Content-Length: 382
header: Expires: Tue, 16 Jun 2015 12:50:00 GMT
header: Date: Tue, 16 Jun 2015 12:50:00 GMT
header: Connection: close
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "youtube_dl/YoutubeDL.py", line 1429, in process_info
    success = dl(filename, info_dict)
  File "youtube_dl/YoutubeDL.py", line 1371, in dl
    return fd.download(name, info)
  File "youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "youtube_dl/downloader/http.py", line 59, in real_download
    data = self.ydl.urlopen(request)
  File "youtube_dl/YoutubeDL.py", line 1724, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
```

**Comment by jaimeMF** [comment] 2015-06-16 13:04
Closing as a duplicate of #3811.

**Closed by jaimeMF** 2015-06-16 13:04 UTC
