### ISSUE TITLE
Credentials error unable to extract login

### ISSUE THREAD

**Issue by Altruo** [rg3/youtube-dl#16399] opened 2018-05-07 23:31 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
C:\Users\Julien\Downloads\youtube-dl>youtube-dl.exe -v -u XXXX -p XXXX "https://ici.tou.tv/les-schtroumpfs/S03E151?lectureauto=1"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://ici.tou.tv/les-schtroumpfs/S03E151?lectureauto=1']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.05.01
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1
[debug] Proxy map: {}
[tou.tv] Downloading homepage
ERROR: Unable to extract toutvlogin; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpulhs0gaq\build\youtube_dl\YoutubeDL.py", line 789, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpulhs0gaq\build\youtube_dl\extractor\common.py", line 439, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpulhs0gaq\build\youtube_dl\extractor\common.py", line 397, in initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpulhs0gaq\build\youtube_dl\extractor\toutv.py", line 52, in _real_initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpulhs0gaq\build\youtube_dl\extractor\common.py", line 820, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract toutvlogin; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

---

### Description of your *issue*, suggested solution and other information

The site https://ici.tou.tv doesn't support anymore my credentials. But it used to work. I don't know if the command line is wrong, but I doubt it since I always use the same. However, the site has changed (updated) since my last login, that might be the problem.  Videos that doesn't need credential on the site still work, only the ones that needs premium account pose problem. Anyone has a solution for this problem ? Please help me with this, I would highly appreciate. I can provide my credentials if needed...

**Comment by Altruo** [comment] 2018-05-07 23:34
The site https://ici.tou.tv doesn't support anymore my credentials. But it used to work. I don't know if the command line is wrong, but I doubt it since I always use the same. However, the site has changed (updated) since my last login, that might be the problem.  Videos that doesn't need credential on the site still work, only the ones that needs premium account pose problem. Anyone has a solution for this problem ? Please help me with this, I would highly appreciate. I can provide my credentials if needed...

**Comment by remitamine** [comment] 2018-05-07 23:48
Duplicate of #16398.

**Closed by remitamine** 2018-05-07 23:48 UTC
