### ISSUE TITLE
Found “Could not download DASH manifest” on YouTube

### ISSUE THREAD

**Issue by starkshaw** [rg3/youtube-dl#6593] opened 2015-08-18 02:37 UTC
When I try `youtube-dl -f 22 www.youtube.com/watch\?v\=4Z9b2HiW_L8 --merge-output-format mp4 --verbose` it gives me these messages as below:
```
[debug] System config: []
[debug] User config: [u'-f', u'bestvideo+bestaudio/best']
[debug] Command-line args: [u'-f', u'22', u'www.youtube.com/watch?v=4Z9b2HiW_L8', u'--merge-output-format', u'mp4', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.16.1
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2
[debug] Proxy map: {}
WARNING: The url doesn't specify the protocol, trying with http
[youtube] 4Z9b2HiW_L8: Downloading webpage
[youtube] 4Z9b2HiW_L8: Downloading video info webpage
[youtube] 4Z9b2HiW_L8: Extracting video information
[youtube] {22} signature length 40.42, html5 player new
[youtube] {43} signature length 40.42, html5 player new
[youtube] {18} signature length 40.42, html5 player new
[youtube] {5} signature length 40.42, html5 player new
[youtube] {36} signature length 40.42, html5 player new
[youtube] {17} signature length 40.42, html5 player new
[youtube] {137} signature length 40.42, html5 player new
[youtube] {248} signature length 40.42, html5 player new
[youtube] {136} signature length 40.42, html5 player new
[youtube] {247} signature length 40.42, html5 player new
[youtube] {135} signature length 40.42, html5 player new
[youtube] {244} signature length 40.42, html5 player new
[youtube] {134} signature length 40.42, html5 player new
[youtube] {243} signature length 40.42, html5 player new
[youtube] {133} signature length 40.42, html5 player new
[youtube] {242} signature length 40.42, html5 player new
[youtube] {160} signature length 40.42, html5 player new
[youtube] {278} signature length 40.42, html5 player new
[youtube] {140} signature length 40.42, html5 player new
[youtube] {171} signature length 40.42, html5 player new
[youtube] {249} signature length 40.42, html5 player new
[youtube] {250} signature length 40.42, html5 player new
[youtube] {251} signature length 40.42, html5 player new
[youtube] 4Z9b2HiW_L8: Downloading DASH manifest
WARNING: [youtube] 4Z9b2HiW_L8: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[debug] Invoking downloader on u'https://r7---sn-3u-bh26.googlevideo.com/videoplayback?ipbits=0&itag=22&mm=31&mn=sn-3u-bh26&mime=video%2Fmp4&requiressl=yes&source=youtube&mt=1439864985&mv=m&ms=au&sparams=dur%2Cgcr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&fexp=9405987%2C9407157%2C9407169%2C9407882%2C9408144%2C9408214%2C9408710%2C9409069%2C9415365%2C9415485%2C9416023%2C9416126%2C9416522%2C9417269%2C9417707%2C9418153%2C9418199%2C9419302%2C9419444&ip=220.94.216.144&sver=3&lmt=1432244441896709&gcr=kr&initcwndbps=3172500&id=o-AH98qrEfTCKQSjpOAbTQhasTBzdPUm3vDImGj4r2bWgX&upn=6NQ6vsnr65g&pcm2cms=yes&ratebypass=yes&pl=17&dur=217.222&expire=1439886643&key=yt5&pcm2=yes&signature=C5CB6EFD2A9E0C475A34BABB0F8F454907B1FEAE.2539CA2CA6E1891AE6760D44CF923544EA8CFB64'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1585, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1527, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 60, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1860, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
```

I tried several different parameters for same URL but received same error. This URL works perfectly fine in Safari.

**Comment by dstftw** [comment] 2015-08-18 03:04
Duplicate of #6451. Remove cache with `youtube-dl --rm-cache-dir`.

**Closed by dstftw** 2015-08-18 03:04 UTC
