### ISSUE TITLE
URLError: <urlopen error [Errno 8] _ssl.c:510: EOF occurred in violation of protocol>

### ISSUE THREAD

**Issue by robbiewu008** [rg3/youtube-dl#4578] opened 2014-12-27 05:55 UTC
D:\50_Vendors\01_Google\01_Google_IO\2014\Talk Videos>youtube-dl.exe -c -f 22 --no-check-certificate
 https://www.youtube.com/watch?v=wtLJPvx7-ys -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-c', '-f', '22', '--no-check-certificate', 'https://www.youtube.com/wat
ch?v=wtLJPvx7-ys', '-v']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2014.12.17.2
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {'ftp': 'ftp://10.0.0.13:2516', 'http': 'http://10.0.0.13:2516', 'https': 'https:
//10.0.0.13:2516'}
[youtube] wtLJPvx7-ys: Downloading webpage
[youtube] wtLJPvx7-ys: Extracting video information
[youtube] wtLJPvx7-ys: Downloading DASH manifest
[debug] Invoking downloader on u'https://r5---sn-a5m7lne7.googlevideo.com/videoplayback?ratebypass=y
es&expire=1419681181&ipbits=0&mm=31&ms=au&mt=1419659558&upn=mFj-kFhUQqk&mv=m&signature=0C2E1442517D1
569BBAD039DDCEF1B7CBD2DA0E5.B28D5A2A466FB860191C1266FE6E99AB9FFA6364&requiressl=yes&mime=video%2Fmp4
&gcr=us&sver=3&dur=8889.341&itag=22&key=yt5&ip=198.71.90.52&source=youtube&initcwndbps=12513750&id=o
-AMC76ebqZMqwXocs4GY_HCKcwWnwnvGLsbH8GLkdV463&fexp=900718%2C927622%2C932404%2C939981%2C941004%2C9439
17%2C945067%2C945323%2C947209%2C947218%2C948124%2C952302%2C952605%2C952901%2C955301%2C957103%2C95710
5%2C957201&sparams=dur%2Cgcr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Cmime%2Cmm%2Cms%2Cmv%2Cratebyp
ass%2Crequiressl%2Csource%2Cupn%2Cexpire'
ERROR: unable to download video data: <urlopen error [Errno 8] _ssl.c:510: EOF occurred in violation
 of protocol>
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1136, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1112, in dl
  File "youtube_dl\downloader\common.pyo", line 297, in download
  File "youtube_dl\downloader\http.pyo", line 67, in real_download
  File "youtube_dl\YoutubeDL.pyo", line 1370, in urlopen
  File "urllib2.pyo", line 404, in open
  File "urllib2.pyo", line 422, in _open
  File "urllib2.pyo", line 382, in _call_chain
  File "youtube_dl\utils.pyo", line 421, in https_open
  File "urllib2.pyo", line 1184, in do_open
URLError: <urlopen error [Errno 8] _ssl.c:510: EOF occurred in violation of protocol>

**Comment by roosemberth** [comment] 2016-04-21 12:43
having the same issue with tsocks + youtube-dl 2016.03.26

**Comment by anirudh-ramesh** [comment] 2016-05-07 06:57
Encountered isolated incident throwing <urlopen error EOF occurred in violation of protocol (_ssl.c:590)> with v2016.04.01. Triggering an automatic retry could be helpful, perhaps.

**Comment by terefang** [comment] 2016-07-18 19:02
i edited "youtube_dl/utils.py":

> def make_HTTPS_handler(opts_no_check_certificate, **kwargs):
>     if sys.version_info < (3, 2):
>         import httplib
> 
>         class HTTPSConnectionV3(httplib.HTTPSConnection):
>             def __init__(self, *args, **kwargs):
>                 httplib.HTTPSConnection.__init__(self, *args, **kwargs)
> 
>             def connect(self):
>                 sock = socket.create_connection((self.host, self.port), self.timeout)
>                 if getattr(self, '_tunnel_host', False):
>                     self.sock = sock
>                     self._tunnel()
>                 try:
>                     self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file, ssl_version=ssl.PROTOCOL_TLSv1)
>                 except ssl.SSLError:
>                     try:
>                         self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file, ssl_version=ssl.PROTOCOL_SSLv3)
>                     except ssl.SSLError:
>                         self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file, ssl_version=ssl.PROTOCOL_SSLv23)

**Comment by Baalkikhaal** [comment] 2016-07-20 06:35
Dear terefang,
I was getting similar error while downloading a youtube video. Thank you for your workaround. It worked for me. However I did not understand the technicality of your solution. I would be grateful if you could explain in simple terms as I am not aware of networking fundamentals.

**Comment by yan12125** [comment] 2016-07-20 07:02
Seems SSLv3 ([considered insecure](https://docs.python.org/2/library/ssl.html#ssl.PROTOCOL_SSLv3)) works while SSLv23 (the highest protocol version that both the client and server support) not. I don't know why some networks require it.

**Comment by yan12125** [comment] 2016-07-20 08:08
Well, another cause may be broken SSL implementations. @terefang, @Baalkikhaal What's the version of operatin system, Python and OpenSSL of your device? Please also post the output of ```youtube-dl -v <some URL>```

**Comment by terefang** [comment] 2016-07-22 12:50
ok to explain the fix:

first try handshake TLSv1 (which currently is TLS 1.0, 1.1, 1.2)
if that fails retry with SSLv3 (lets call it TLS 0.3)
if that fails retry with SSLv23 (it is not version 23 but rather SSLv3 with SSLv2 fallback, horrible out of date, ie TLS 0.3 than TLS 0.2)

that was with youtube-dl from mint 17.3/ubuntu 14.04.x

i have since upgraded to mint 18/ubuntu 16.04 which has youtube-dl 2016.02.22 which works without the fix

**Comment by ovidiugabriel** [comment] 2016-07-28 11:13
Hello, 

I have encountered the same issue:

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', <<URL removed>>]
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-3.16.0-71-lowlatency-x86_64-with-Ubuntu-14.04-trusty
[debug] Proxy map: {}
[youtube] Setting language
WARNING: unable to set language: <urlopen error [Errno 8] _ssl.c:510: EOF occurred in violation of protocol>
[youtube] <URL removed>: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 8] _ssl.c:510: EOF occurred in violation of protocol>
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 191, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1157, in urlopen
    return self._opener.open(req)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/utils.py", line 572, in https_open
    return self.do_open(HTTPSConnectionV3, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)

**Comment by cru6raGu** [comment] 2016-08-05 17:42
Thanks to @terefang. It worked. 

just to help other users. I am on Ubuntu 14.04 and the utils.py is here:

 /usr/lib/python2.7/dist-packages/youtube_dl/utils.py

**Comment by alfonsojon** [comment] 2016-08-24 01:28
Just leaving my input, it currently affects the Windows 10 Linux Subsystem.

**Comment by acd10** [comment] 2016-10-06 14:39
Thanks a lot @terefang. It worked!

**Comment by AbrarNitk** [comment] 2017-03-25 17:31
Upgrade it using pip

Step First(if pip is not installed)
Firstly install pip if it is not install 
sudo apt-get install python-setuptools
sudo easy_install pip

Second Step(Upgrade youtube-dl)
sudo pip install --upgrade youtube-dl

**Comment by systemovich** [comment] 2017-10-05 08:05
This issue should be closed now, because it is fixed in the latest version youtube-dl-2017.10.1. It was broken for me in version youtube-dl-2014.2.17 which came packaged with Ubuntu 14.04.

**Comment by yan12125** [comment] 2017-10-05 08:52
fqrouter is dead [1], socks proxy support is now built-in, and many people confirmed that the latest youtube-dl works fine, so yes, this can be closed. Thanks for the reminder!

[1] https://twitter.com/fqrouter/status/578967338046787585

**Closed by yan12125** 2017-10-05 08:52 UTC

**Comment by mayankdiatm** [comment] 2017-10-31 03:50
http://stackoverflow.com/questions/11772847/error-urlopen-error-errno-8-ssl-c504-eof-occurred-in-violation-of-protoco

How is solution working can you give me an example.

**Comment by GrayXu** [comment] 2020-03-23 16:01
the same problem on clash for windows10 and the latest version of youtube-dl
