### ISSUE TITLE
live stream download from youtube with specified time limit

### ISSUE THREAD

**Issue by przemyslawpluta** [rg3/youtube-dl#9420] opened 2016-05-06 19:00 UTC
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.01**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Question

Is there a way to specify the duration of the record of the live stream? e.g. -t 00:00:10 record the live stream for 10 seconds?

Thank you.

**Comment by yan12125** [comment] 2016-05-11 05:50
Duplicate of #622.

**Closed by yan12125** 2016-05-11 05:50 UTC

**Comment by Kushcabbage** [comment] 2017-08-31 15:13
The solutions discussed in the #622 thread do not work for livestreams

**Comment by yan12125** [comment] 2017-08-31 15:27
FYI: For non-plain streams, #8851 provides more information. There are not concrete solutions yet.
