### ISSUE TITLE
Issue with Pluralsight

### ISSUE THREAD

**Issue by ricardolopes86** [rg3/youtube-dl#12078] opened 2017-02-10 20:28 UTC
It was working till a few minutes ago, now its throwing this error:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--no-overwrites', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'--min-sleep-interval', u'200', u'--max-sleep-interval', u'300', u'-a', u'Linkx.txt']
[debug] Batch file urls: [u'https://app.pluralsight.com/library/courses/mongoose-for-nodejs-mongodb', u'https://app.pluralsight.com/library/courses/android-xamarin-from-start-to-store', u'https://app.pluralsight.com/library/courses/cissp-security-engineering', u'https://app.pluralsight.com/library/courses/understanding-java-vm-memory-management', u'https://app.pluralsight.com/library/courses/node-intro', u'https://app.pluralsight.com/library/courses/npm-playbook', u'https://app.pluralsight.com/library/courses/nodejs-express-web-applications', u'https://app.pluralsight.com/library/courses/large-scale-javascript', u'https://app.pluralsight.com/library/courses/node-js-express-rest-web-services', u'https://app.pluralsight.com/library/courses/nodejs-testing-strategies', u'https://app.pluralsight.com/library/courses/node-application-patterns', u'https://app.pluralsight.com/library/courses/ethical-hacking-penetration-testing', u'https://app.pluralsight.com/library/courses/react-express-full-stack-app-build']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.10
[debug] Python version 2.7.12 - Linux-4.4.0-31-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] mongoose-for-nodejs-mongodb: Downloading course JSON
[pluralsight:course] mongoose-for-nodejs-mongodb: Downloading course data JSON

ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 416, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2006, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by ricardolopes86** [comment] 2017-02-10 20:46
I tried on the Browser and it works fine.

**Comment by gpborges** [comment] 2017-02-10 22:44
I'm facing the same error and I was donwloading it this whole morning... And my PluralSight account is all fine. I even sign out/sign in just to make sure the account is ok. Another friend is also facing this issue.

**Comment by evilkid** [comment] 2017-02-10 23:00
Same problem, i guess the "https://app.pluralsight.com/data/course/content/{course-id}" url is no longer valid.

**Comment by dstftw** [comment] 2017-02-11 09:08
Duplicate of #12075.

**Closed by dstftw** 2017-02-11 09:08 UTC
