### ISSUE TITLE
Discovery GO Json parse error

### ISSUE THREAD

**Issue by useless2764** [rg3/youtube-dl#11226] opened 2016-11-18 00:01 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.18*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.18**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
PS C:\Users\..\downloads> youtube-dl --cookies cookies.txt https://www.discoverygo.com/gold-rush/misery-on-the-mountain/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--cookies', 'cookies.txt', 'https://www.discoverygo.com/gold-rush/misery-on-the-mountain/',
 '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2016.11.18
[debug] Python version 3.5.2 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-81632-g09317e3, ffprobe N-81632-g09317e3
[debug] Proxy map: {}
ERROR: misery-on-the-mountain: Failed to parse JSON  (caused by JSONDecodeError("Expecting ',' delimiter: line 1 column
56555 (char 56554)",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version;
see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its comp
lete output.
Traceback (most recent call last):
  File "c:\python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 559, in _parse_json
    return json.loads(json_string)
  File "c:\python35-32\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "c:\python35-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\python35-32\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 56555 (char 56554)
Traceback (most recent call last):
  File "c:\python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 559, in _parse_json
    return json.loads(json_string)
  File "c:\python35-32\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "c:\python35-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\python35-32\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 56555 (char 56554)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python35-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "c:\python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 357, in extract
    return self._real_extract(url)
  File "c:\python35-32\lib\site-packages\youtube_dl\extractor\discoverygo.py", line 53, in _real_extract
    display_id)
  File "c:\python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 563, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
youtube_dl.utils.ExtractorError: misery-on-the-mountain: Failed to parse JSON  (caused by JSONDecodeError("Expecting ','
 delimiter: line 1 column 56555 (char 56554)",)); please report this issue on https://yt-dl.org/bug . Make sure you are
using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose
 flag and include its complete output.
                                                                                
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.discoverygo.com/gold-rush/misery-on-the-mountain/

---

### Description of your *issue*, suggested solution and other information

I'm currently getting a Failed to extract JSON error when trying to download from discoverygo.com, My guess is they made a change recently as downloading worked as expected last week.

**Comment by dstftw** [comment] 2016-11-18 02:25
Duplicate of #11219.

**Closed by dstftw** 2016-11-18 02:25 UTC
