### ISSUE TITLE
Unable to download https://www.youtube.com/watch?v=kL8ULMwc_F4 - Server Error - but video plays fine?

### ISSUE THREAD

**Issue by victorhooi** [rg3/youtube-dl#12420] opened 2017-03-10 21:44 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.10*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.10**

```
victorhooi@victorhooi-macbookpro /p/tmp> youtube-dl --version
2017.03.10
```

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
victorhooi@victorhooi-macbookpro ~/D/b/computer_science_61b> youtube-dl --verbose "http://www.youtube.com/view_play_list?p=-XXv-cvA_iDD4nnsfVIqPFORTgZi9xRp"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'http://www.youtube.com/view_play_list?p=-XXv-cvA_iDD4nnsfVIqPFORTgZi9xRp']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.10
[debug] Python version 2.7.13 - Darwin-16.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {}
[youtube:playlist] -XXv-cvA_iDD4nnsfVIqPFORTgZi9xRp: Downloading webpage
[download] Downloading playlist: Computer Science 61B, 002 - Spring 2015
[youtube:playlist] playlist Computer Science 61B, 002 - Spring 2015: Downloading 37 videos
[download] Downloading video 1 of 37
[youtube] kL8ULMwc_F4: Downloading webpage
[youtube] kL8ULMwc_F4: Downloading video info webpage
[youtube] kL8ULMwc_F4: Extracting video information
[youtube] kL8ULMwc_F4: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on u'https://r14---sn-ntqe7n7d.googlevideo.com/videoplayback?id=90bf142ccc1cfc5e&itag=136&source=youtube&requiressl=yes&mm=31&mn=sn-ntqe7n7d&ms=au&mv=m&pl=24&initcwndbps=1092500&ratebypass=yes&mime=video/mp4&gir=yes&clen=276993027&lmt=1422875739494945&dur=2993.933&upn=oe1PF38GQMU&mt=1489180350&signature=4576A81BBB5074AE1BA83E1DAF727D6DC5FD51BE.7087D4C870F44860C4C52A9BD51740A05AFD28CE&key=dg_yt0&ip=58.84.194.14&ipbits=0&expire=1489202382&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mn,ms,mv,pl,initcwndbps,ratebypass,mime,gir,clen,lmt,dur'
[download] Resuming download at byte 118671711
[download] Destination: Computer Science 61B - 2015-01-21-kL8ULMwc_F4.f136.mp4
[download] 100% of 264.16MiB in 01:18
[debug] Invoking downloader on u'https://r14---sn-ntqe7n7d.googlevideo.com/videoplayback?key=yt6&initcwndbps=1092500&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&lmt=1422022781647163&clen=65169417&expire=1489202382&ip=58.84.194.14&gir=yes&source=youtube&mm=31&mn=sn-ntqe7n7d&mt=1489180350&mv=m&pl=24&id=o-ANqoH6eBqyZGP-kjkaAkn4MFzptFjW6yUYO0OJkilRur&ei=bhjDWNesBNSs4gKX17fQAQ&ms=au&requiressl=yes&mime=audio%2Fwebm&dur=2993.981&upn=faIllDpm_BE&ipbits=0&itag=251&keepalive=yes&pcm2=yes&signature=1291FF8D65A980ABBEF6534BE95DBBA1265DB019.311BF2492C416F36573135D25BE4700814B2C22D&ratebypass=yes'
[download] Got server HTTP error. Retrying (attempt 1 of 10)...
[download] Got server HTTP error. Retrying (attempt 2 of 10)...
[download] Got server HTTP error. Retrying (attempt 3 of 10)...
[download] Got server HTTP error. Retrying (attempt 4 of 10)...
[download] Got server HTTP error. Retrying (attempt 5 of 10)...
[download] Got server HTTP error. Retrying (attempt 6 of 10)...
[download] Got server HTTP error. Retrying (attempt 7 of 10)...
[download] Got server HTTP error. Retrying (attempt 8 of 10)...
[download] Got server HTTP error. Retrying (attempt 9 of 10)...
[download] Got server HTTP error. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries
Traceback (most recent call last):
  File "/Users/victorhooi/homebrew/bin/youtube-dl/youtube_dl/downloader/http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "/Users/victorhooi/homebrew/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2093, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Users/victorhooi/homebrew/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/Users/victorhooi/homebrew/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Users/victorhooi/homebrew/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/Users/victorhooi/homebrew/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Users/victorhooi/homebrew/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: Internal Server Error
```
---

### Description of your *issue*, suggested solution and other information

I am trying to download the YouTube playlist from here:

https://www.youtube.com/view_play_list?p=-XXv-cvA_iDD4nnsfVIqPFORTgZi9xRp

There are 37 videos in total. youtube-dl appears to download the video content for the first video successfully - then fails download the audio (?):

```
victorhooi@victorhooi-macbookpro ~/D/b/c/tmp> youtube-dl --verbose "https://www.youtube.com/watch?v=kL8ULMwc_F4"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=kL8ULMwc_F4']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.10
[debug] Python version 2.7.13 - Darwin-16.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {}
[youtube] kL8ULMwc_F4: Downloading webpage
[youtube] kL8ULMwc_F4: Downloading video info webpage
[youtube] kL8ULMwc_F4: Extracting video information
[youtube] kL8ULMwc_F4: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on u'https://r14---sn-ntqe7n7d.googlevideo.com/videoplayback?id=90bf142ccc1cfc5e&itag=136&source=youtube&requiressl=yes&mm=31&initcwndbps=1072500&ms=au&pl=24&mv=m&mn=sn-ntqe7n7d&ratebypass=yes&mime=video/mp4&gir=yes&clen=276993027&lmt=1422875739494945&dur=2993.933&upn=NwNaw5aoLoI&signature=03EA23B8FDABA3BEA36D93CE6AB119F53C4BB613.20C06CB3FE91A00D77F97C08AFAFE9430B54BB2A&key=dg_yt0&mt=1489180769&ip=58.84.194.14&ipbits=0&expire=1489202664&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,initcwndbps,ms,pl,mv,mn,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Computer Science 61B - 2015-01-21-kL8ULMwc_F4.f136.mp4
[download] 100% of 264.16MiB in 02:41
[debug] Invoking downloader on u'https://r14---sn-ntqe7n7d.googlevideo.com/videoplayback?expire=1489202664&clen=65169417&pl=24&initcwndbps=1072500&mime=audio%2Fwebm&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&upn=6mB1m3bnGAk&mv=m&mt=1489180769&ms=au&itag=251&ei=iBnDWOXPEoKO4gKi-bq4Cw&mn=sn-ntqe7n7d&mm=31&keepalive=yes&id=o-AJfp7MVzYPNEasgdOmUQUErWGmAseYMVNsof6R8xKsQM&requiressl=yes&ip=58.84.194.14&signature=3B51BE02005833C45ACB0488D89C850E76E44D84.DDC79EBB6E60DA708BFF7A81E0B5E448D257EA41&gir=yes&key=yt6&dur=2993.981&source=youtube&lmt=1422022781647163&ipbits=0&ratebypass=yes'
[download] Got server HTTP error. Retrying (attempt 1 of 10)...
[download] Got server HTTP error. Retrying (attempt 2 of 10)...
[download] Got server HTTP error. Retrying (attempt 3 of 10)...
[download] Got server HTTP error. Retrying (attempt 4 of 10)...
[download] Got server HTTP error. Retrying (attempt 5 of 10)...
[download] Got server HTTP error. Retrying (attempt 6 of 10)...
[download] Got server HTTP error. Retrying (attempt 7 of 10)...
[download] Got server HTTP error. Retrying (attempt 8 of 10)...
[download] Got server HTTP error. Retrying (attempt 9 of 10)...
[download] Got server HTTP error. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries
Traceback (most recent call last):
  File "/Users/victorhooi/homebrew/bin/youtube-dl/youtube_dl/downloader/http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "/Users/victorhooi/homebrew/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2093, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Users/victorhooi/homebrew/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/Users/victorhooi/homebrew/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Users/victorhooi/homebrew/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/Users/victorhooi/homebrew/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Users/victorhooi/homebrew/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: Internal Server Error
```

I can confirm the video plays fine on YouTube though:

https://www.youtube.com/watch?v=kL8ULMwc_F4

**Comment by dstftw** [comment] 2017-03-11 10:32
Duplicate of #3721.

**Closed by dstftw** 2017-03-11 10:32 UTC
