### ISSUE TITLE
Add support for myvideos.stanford.edu

### ISSUE THREAD

**Issue by Siddhant** [rg3/youtube-dl#3084] opened 2014-06-15 09:56 UTC
$ youtube-dl.exe --verbose http://myvideos.stanford.edu/player/slplayer.aspx?coll=ea60314a-53b3-4be2-8552-dcf190ca0c0b&co=18bcd3a8-965a-4a63-a516-a1ad74af1119&o=true
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://myvideos.stanford.edu/player/sl
player.aspx?coll=ea60314a-53b3-4be2-8552-dcf190ca0c0b']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2014.06.09
[debug] Python version 2.7.5 - Windows-7-6.1.7601-SP1
[generic] slplayer: Requesting header
[redirect] Following redirect to http://myvideos.stanford.edu/errors/login.aspx?
errorMessage=Could%20not%20Authenticate%20user
[generic] login: Requesting header
WARNING: Falling back on generic information extractor.
[generic] login: Downloading webpage
[generic] login: Extracting information
ERROR: Unsupported URL: http://myvideos.stanford.edu/errors/login.aspx?errorMess
age=Could%20not%20Authenticate%20user; please report this issue on https://yt-dl
.org/bug . Be sure to call youtube-dl with the --verbose flag and include its co
mplete output. Make sure you are using the latest version; type  youtube-dl -U
to update.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 516, in extract_info
  File "youtube_dl\extractor\common.pyo", line 167, in extract
  File "youtube_dl\extractor\generic.pyo", line 722, in _real_extract
ExtractorError: Unsupported URL: http://myvideos.stanford.edu/errors/login.aspx?
errorMessage=Could%20not%20Authenticate%20user; please report this issue on http
s://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and inclu
de its complete output. Make sure you are using the latest version; type  youtub
e-dl -U  to update.

'co' is not recognized as an internal or external command,
operable program or batch file.
'o' is not recognized as an internal or external command,
operable program or batch file.

**Comment by seanjensengrey** [comment] 2015-04-10 05:10
https://mvideos.stanford.edu/graduate#/SeminarDetail/Spring/2015/EE/380/6954

**Comment by mpenkov** [comment] 2018-08-31 02:04
I think the original problem was caused by an unquoted URL with a querystring (ampersands) in it.

Anyway, myvideos.stanford.edu no longer resolves to an IP address. @seanjensengrey https://mvideos.stanford.edu/graduate#/SeminarDetail/Spring/2015/EE/380/6954 gives an error page (yeah, it's been over 3 years...)

I think we can close this.

**Closed** 2018-08-31 07:05 UTC
Labels: site-support-request
