### ISSUE TITLE
ExtractorError

### ISSUE THREAD

**Issue by Javinator9889** [rg3/youtube-dl#12891] opened 2017-04-28 07:48 UTC
_raise IOError(str(e).replace('YouTube said', 'Youtube says'))
OSError: ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/home/javialonso/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "/home/javialonso/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'_

I have tryed downgrading YouTube-dl versión but is working in none versión...

**Comment by yan12125** [comment] 2017-04-28 07:50
Duplicate of #12885. It's fixed and will be available in the upcoming version.

**Closed by yan12125** 2017-04-28 07:50 UTC
