### ISSUE TITLE
ExtractorError

### ISSUE THREAD

**Issue by fu9ar** [rg3/youtube-dl#7416] opened 2015-11-10 03:59 UTC
E:\>youtube-dl.exe --verbose https://www.youtube.com/watch?v=C6vinrXWxls&feature
=youtu.be
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=C6vi
nrXWxls']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.11.02
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] C6vinrXWxls: Downloading webpage
[youtube] C6vinrXWxls: Downloading video info webpage
[youtube] C6vinrXWxls: Extracting video information
WARNING: unable to extract html5 player; please report this issue on https://yt-
dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
 update. Be sure to call youtube-dl with the --verbose flag and include its comp
lete output.
[youtube] {22} signature length 40.44, html5 player None
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 817, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 709, in _extract_signature_funct
ion
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en
_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.org/bug . Make
 sure you are using the latest version; type  youtube-dl -U  to update. Be sure
to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/js
bin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.o
rg/bug . Make sure you are using the latest version; type  youtube-dl -U  to upd
ate. Be sure to call youtube-dl with the --verbose flag and include its complete
 output.",)); please report this issue on https://yt-dl.org/bug . Make sure you
are using the latest version; type  youtube-dl -U  to update. Be sure to call yo
utube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 817, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 709, in _extract_signature_funct
ion
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en
_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.org/bug . Make
 sure you are using the latest version; type  youtube-dl -U  to update. Be sure
to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 661, in extract_info
  File "youtube_dl\extractor\common.pyo", line 290, in extract
  File "youtube_dl\extractor\youtube.pyo", line 1345, in _real_extract
  File "youtube_dl\extractor\youtube.pyo", line 827, in _decrypt_signature
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 817, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 709, in _extract_signature_funct
ion
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en
_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.org/bug . Make
 sure you are using the latest version; type  youtube-dl -U  to update. Be sure
to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/js
bin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.o
rg/bug . Make sure you are using the latest version; type  youtube-dl -U  to upd
ate. Be sure to call youtube-dl with the --verbose flag and include its complete
 output.",)); please report this issue on https://yt-dl.org/bug . Make sure you
are using the latest version; type  youtube-dl -U  to update. Be sure to call yo
utube-dl with the --verbose flag and include its complete output.

'feature' is not recognized as an internal or external command,
operable program or batch file.

**Comment by yan12125** [comment] 2015-11-10 05:01
Duplicate of #7413. By the way, you need to enclose URLs in single or double quotes. See [this FAQ entry](https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command).

**Closed by yan12125** 2015-11-10 05:01 UTC
