### ISSUE TITLE
[iQiyi] Cannot download the correct video, downloaded Ad only

### ISSUE THREAD

**Issue by js904** [rg3/youtube-dl#9903] opened 2016-06-25 22:24 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.06.25*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.25**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.iqiyi.com/v_19rrlke8qo.html']
[debug] Encodings: locale cp950, fs mbcs, out cp950, pref cp950
[debug] youtube-dl version 2016.06.25
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[iqiyi] temp_id: download video page
[iqiyi] 4045d62575b0d4423c1cc5d88fa25611: Downloading JSON metadata
[iqiyi] 4045d62575b0d4423c1cc5d88fa25611: Download path key of segment 1 for for
mat h3
[iqiyi] 4045d62575b0d4423c1cc5d88fa25611: Download video info of segment 1 for f
ormat h3
[iqiyi] 4045d62575b0d4423c1cc5d88fa25611: Download path key of segment 1 for for
mat h6
[iqiyi] 4045d62575b0d4423c1cc5d88fa25611: Download video info of segment 1 for f
ormat h6
[iqiyi] 4045d62575b0d4423c1cc5d88fa25611: Download path key of segment 1 for for
mat h5
[iqiyi] 4045d62575b0d4423c1cc5d88fa25611: Download video info of segment 1 for f
ormat h5
[debug] Invoking downloader on 'http://netcncoversea.inter.iqiyi.com/videos/v0/2
0160614/7f/bc/463a675a7a52033ba0174a1f159adb51.f4v?key=0adb4d9e05106c6dcf0d0f665
4e01b680&src=iqiyi.com&qd_tvid=496130600&qd_vipres=0&qd_index=1&qd_aid=496130600
&qd_stert=0&qd_scc=9180d1951ed4bf6e18b30b02fedba4cc&qd_sc=4611a8a60af8c8f6de1b05
813c5c085b&qd_src=1702633101b340d8917a69cf8a4b8c7c&qd_ip=ca6c0ef0&qd_uid=2047395
208&qd_tm=1465957198790&qd_vip=1&su=bb4d10a43d584c19ac8a790db14e2ca4&bt=&z=&ct=&
client=&qyid=ea93d6d92b004fd5bd032fa6f8d178a1&tn=1466893448&uuid=74302609-576f04
88-b2'
[download] 广告宣传片-4045d62575b0d4423c1cc5d88fa25611.f4v has already been down
loaded
[download] 100% of 16.39MiB

...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.
Seems iqiyi have changed the settings and cannot download the actual video now.

**Comment by dstftw** [comment] 2016-06-25 22:28
Duplicate of #9839.

**Closed by dstftw** 2016-06-25 22:28 UTC
