### ISSUE TITLE
Infinite regression.

### ISSUE THREAD

**Issue by shrinidhi111** [rg3/youtube-dl#11853] opened 2017-01-27 16:28 UTC
I tried downloading a video from Channel9 (MS channel) and it seems the application enters an infinite loop where it keeps "trying" to get the video.

It won't give an error or anything.. It keeps shuffling between downloading the RSS and playlist but downloads neither of them.

Here's the link for the video I was trying to download : [Channel9 video](https://channel9.msdn.com/Shows/Inside-Windows-Platform/Using-Drag-and-Drop-in-your-Universal-Windows-App)

---

### Verbose log. 

I always download with verbose ON (I like it that way)

```

C:\Users\Hackathon\Music\iTunes\iTunes Media\Automatically Add to iTunes\Not Added>Waiting for file handle to be closed ...
Updated youtube-dl to version 2017.01.25.

C:\Users\Hackathon\Music\iTunes\iTunes Media\Automatically Add to iTunes\Not Added>v2i https://channel9.msdn.com/Shows/Inside-Windows-Platform/Using-Drag-and-Drop-in-your-Universal-Windows-App

C:\Users\Hackathon\Music\iTunes\iTunes Media\Automatically Add to iTunes\Not Added>echo This baby requires youtube-dl program downloadable from github.
This baby requires youtube-dl program downloadable from github.

C:\Users\Hackathon\Music\iTunes\iTunes Media\Automatically Add to iTunes\Not Added>youtube-dl -f "18/medium" --add-metadata --mark-watched --console-title --print-traffic --newline -v --write-pages --write-thumbnail --embed-thumbnail --write-sub -o "C:/Users/Hackathon/Music/iTunes/iTunes Media/Automatically Add to iTunes/%(title)s.%(ext)s" https://channel9.msdn.com/Shows/Inside-Windows-Platform/Using-Drag-and-Drop-in-your-Universal-Windows-App
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', '18/medium', '--add-metadata', '--mark-watched', '--console-title', '--print-traffic', '--newline', '-v', '--write-pages', '--write-thumbnail', '--embed-thumbnail', '--write-sub', '-o', 'C:/Users/Hackathon/Music/iTunes/iTunes Media/Automatically Add to iTunes/%(title)s.%(ext)s', 'https://channel9.msdn.com/Shows/Inside-Windows-Platform/Using-Drag-and-Drop-in-your-Universal-Windows-App']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.01.25
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-81632-g09317e3, ffprobe N-81632-g09317e3
[debug] Proxy map: {}
[channel9] Shows/Inside-Windows-Platform/Using-Drag-and-Drop-in-your-Universal-Windows-App: Downloading web page
[channel9] Saving request to Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App_https_-_channel9.msdn.com_Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App.dump
[channel9] Shows/Inside-Windows-Platform/Using-Drag-and-Drop-in-your-Universal-Windows-App: Downloading RSS
[channel9] Saving request to Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App_http_-_channel9.msdn.com_Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App_RSS.dump
[download] Downloading playlist: Comment Feed for Channel 9 - Using "Drag and Drop" in your Universal Windows App
[channel9] playlist Comment Feed for Channel 9 - Using "Drag and Drop" in your Universal Windows App: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[channel9] Shows/Inside-Windows-Platform/Using-Drag-and-Drop-in-your-Universal-Windows-App: Downloading web page
[channel9] Saving request to Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App_https_-_channel9.msdn.com_Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App.dump
[channel9] Shows/Inside-Windows-Platform/Using-Drag-and-Drop-in-your-Universal-Windows-App: Downloading RSS
[channel9] Saving request to Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App_http_-_channel9.msdn.com_Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App_RSS.dump
[download] Downloading playlist: Comment Feed for Channel 9 - Using "Drag and Drop" in your Universal Windows App
[channel9] playlist Comment Feed for Channel 9 - Using "Drag and Drop" in your Universal Windows App: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[channel9] Shows/Inside-Windows-Platform/Using-Drag-and-Drop-in-your-Universal-Windows-App: Downloading web page
[channel9] Saving request to Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App_https_-_channel9.msdn.com_Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App.dump
[channel9] Shows/Inside-Windows-Platform/Using-Drag-and-Drop-in-your-Universal-Windows-App: Downloading RSS
[channel9] Saving request to Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App_http_-_channel9.msdn.com_Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App_RSS.dump
[download] Downloading playlist: Comment Feed for Channel 9 - Using "Drag and Drop" in your Universal Windows App
[channel9] playlist Comment Feed for Channel 9 - Using "Drag and Drop" in your Universal Windows App: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[channel9] Shows/Inside-Windows-Platform/Using-Drag-and-Drop-in-your-Universal-Windows-App: Downloading web page
[channel9] Saving request to Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App_https_-_channel9.msdn.com_Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App.dump
[channel9] Shows/Inside-Windows-Platform/Using-Drag-and-Drop-in-your-Universal-Windows-App: Downloading RSS
[channel9] Saving request to Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App_http_-_channel9.msdn.com_Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App_RSS.dump
[download] Downloading playlist: Comment Feed for Channel 9 - Using "Drag and Drop" in your Universal Windows App
[channel9] playlist Comment Feed for Channel 9 - Using "Drag and Drop" in your Universal Windows App: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[channel9] Shows/Inside-Windows-Platform/Using-Drag-and-Drop-in-your-Universal-Windows-App: Downloading web page
[channel9] Saving request to Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App_https_-_channel9.msdn.com_Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App.dump
[channel9] Shows/Inside-Windows-Platform/Using-Drag-and-Drop-in-your-Universal-Windows-App: Downloading RSS
[channel9] Saving request to Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App_http_-_channel9.msdn.com_Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App_RSS.dump
[download] Downloading playlist: Comment Feed for Channel 9 - Using "Drag and Drop" in your Universal Windows App
[channel9] playlist Comment Feed for Channel 9 - Using "Drag and Drop" in your Universal Windows App: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[channel9] Shows/Inside-Windows-Platform/Using-Drag-and-Drop-in-your-Universal-Windows-App: Downloading web page
[channel9] Saving request to Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App_https_-_channel9.msdn.com_Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App.dump
[channel9] Shows/Inside-Windows-Platform/Using-Drag-and-Drop-in-your-Universal-Windows-App: Downloading RSS
[channel9] Saving request to Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App_http_-_channel9.msdn.com_Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App_RSS.dump
[download] Downloading playlist: Comment Feed for Channel 9 - Using "Drag and Drop" in your Universal Windows App
[channel9] playlist Comment Feed for Channel 9 - Using "Drag and Drop" in your Universal Windows App: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[channel9] Shows/Inside-Windows-Platform/Using-Drag-and-Drop-in-your-Universal-Windows-App: Downloading web page
[channel9] Saving request to Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App_https_-_channel9.msdn.com_Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App.dump
[channel9] Shows/Inside-Windows-Platform/Using-Drag-and-Drop-in-your-Universal-Windows-App: Downloading RSS
[channel9] Saving request to Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App_http_-_channel9.msdn.com_Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App_RSS.dump
[download] Downloading playlist: Comment Feed for Channel 9 - Using "Drag and Drop" in your Universal Windows App
[channel9] playlist Comment Feed for Channel 9 - Using "Drag and Drop" in your Universal Windows App: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[channel9] Shows/Inside-Windows-Platform/Using-Drag-and-Drop-in-your-Universal-Windows-App: Downloading web page
[channel9] Saving request to Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App_https_-_channel9.msdn.com_Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App.dump
[channel9] Shows/Inside-Windows-Platform/Using-Drag-and-Drop-in-your-Universal-Windows-App: Downloading RSS
[channel9] Saving request to Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App_http_-_channel9.msdn.com_Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App_RSS.dump
[download] Downloading playlist: Comment Feed for Channel 9 - Using "Drag and Drop" in your Universal Windows App
[channel9] playlist Comment Feed for Channel 9 - Using "Drag and Drop" in your Universal Windows App: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[channel9] Shows/Inside-Windows-Platform/Using-Drag-and-Drop-in-your-Universal-Windows-App: Downloading web page
[channel9] Saving request to Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App_https_-_channel9.msdn.com_Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App.dump
[channel9] Shows/Inside-Windows-Platform/Using-Drag-and-Drop-in-your-Universal-Windows-App: Downloading RSS
[channel9] Saving request to Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App_http_-_channel9.msdn.com_Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App_RSS.dump
[download] Downloading playlist: Comment Feed for Channel 9 - Using "Drag and Drop" in your Universal Windows App
[channel9] playlist Comment Feed for Channel 9 - Using "Drag and Drop" in your Universal Windows App: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[channel9] Shows/Inside-Windows-Platform/Using-Drag-and-Drop-in-your-Universal-Windows-App: Downloading web page
[channel9] Saving request to Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App_https_-_channel9.msdn.com_Shows_Inside-Windows-Platform_Using-Drag-and-Drop-in-your-Universal-Windows-App.dump
[channel9] Shows/Inside-Windows-Platform/Using-Drag-and-Drop-in-your-Universal-Windows-App: Downloading RSS

ERROR: Interrupted by user
Terminate batch job (Y/N)? y

C:\Users\Hackathon\Music\iTunes\iTunes Media\Automatically Add to iTunes\Not Added>...
<end of log>
```

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.25*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.25**

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [x ] Site support request (request for adding support Channel9)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

**Comment by dstftw** [comment] 2017-01-27 16:30
Duplicate of #11323.

**Closed by dstftw** 2017-01-27 16:30 UTC
