### ISSUE TITLE
ffmpeg errors

### ISSUE THREAD

**Issue by tyrone-mt** [rg3/youtube-dl#8209] opened 2016-01-12 07:04 UTC
Two days ago I started having problems when downloading clips from Dailymotion via api.  Never had such problems before.  When checking I found that I needed to install the latest verison of ffmpeg which I did.  Server: Centos 6

Still I'm encountering issues such as the following:

<
[http @ 0xa6efe0] HTTP error 404 Not Found
http://proxy-017.dc3.dailymotion.com/sec(f139fc5e2ad483b6a5a397eccb891c38)/video/001/088/217880100_mp4_h264_aac_hd_1.m3u8#cell=core: Input/output error
ERROR: ffmpeg exited with code 1
/>

<
WARNING: Failed to download m3u8 information:
/>

<
[http @ 0xdb6fe0] HTTP error 404 Not Found
http://proxy-01.nyc.dailymotion.com/sec(8b0e24ca04c5df5036361f928b8dae96)/video/567/768/217867765_mp4_h264_aac_hd.m3u8#cell=nyc: Input/output error
/>

Kindly, could someone help how to best tackle such issues.

Thanks in advance.

**Comment by tyrone-mt** [comment] 2016-01-12 07:07
Actually I just found out that this has already been reported in #8156.

**Comment by dstftw** [comment] 2016-01-12 13:42
Duplicate of #8156.

**Closed by dstftw** 2016-01-12 13:42 UTC
