### ISSUE TITLE
Site Support Request: CBC.ca Archives (and theplatform.com in general)

### ISSUE THREAD

**Issue by aaronvegh** [rg3/youtube-dl#7563] opened 2015-11-19 13:00 UTC
I've been noticing more videos lately being hosted on theplatform.com. This latest one is from CBC.ca. I can provide others if you wish.

```
$ youtube-dl --version
2015.11.15
```

```
$ youtube-dl -v -j "http://www.cbc.ca/archives/entry/1978-tv-like-machines-replace-secretaries"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-j', u'http://www.cbc.ca/archives/entry/1978-tv-like-machines-replace-secretaries']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.15
[debug] Python version 2.7.10 - Darwin-15.0.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: http://www.cbc.ca/archives/entry/1978-tv-like-machines-replace-secretaries
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1255, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 248, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=etree.TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 237, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 72, column 124
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1858, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.cbc.ca/archives/entry/1978-tv-like-machines-replace-secretaries
```

**Comment by dstftw** [comment] 2015-11-19 14:48
Duplicate of #4731.

**Closed by dstftw** 2015-11-19 14:48 UTC
