### ISSUE TITLE
[Youtube] Video downloading stops (410) even though the video exists and it downloads the data

### ISSUE THREAD

**Issue by vxbinaca** [rg3/youtube-dl#9009] opened 2016-03-27 19:07 UTC
```youtube-dl -v ts5pI0aG8-I```

```
[debug] System config: []
[debug] User config: [u'--download-archive', u'~/.ytdlarchive', u'--retries', u'100', u'--no-overwrites', u'--call-home', u'--continue', u'--write-info-json', u'--write-description', u'--write-thumbnail', u'--write-annotations', u'--all-subs', u'--write-sub', u'--add-metadata', u'-f', u'bestvideo+bestaudio/best', u'--merge-output-format', u'mkv', u'--prefer-ffmpeg', u'--embed-thumbnail']
[debug] Command-line args: [u'-v', u'ts5pI0aG8-I']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.27
[debug] Python version 2.7.10 - Linux-4.2.0-34-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: ffmpeg 2.7.6-0ubuntu0.15.10.1, ffprobe 2.7.6-0ubuntu0.15.10.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Public IP address: 76.101.221.232
[youtube] ts5pI0aG8-I: Downloading webpage
[youtube] ts5pI0aG8-I: Downloading video info webpage
[youtube] ts5pI0aG8-I: Extracting video information
WARNING: video doesn't have subtitles
[youtube] ts5pI0aG8-I: Searching for annotations.
[youtube] ts5pI0aG8-I: Downloading MPD manifest
[info] Video description is already present
[info] Video annotations are already present
[info] Video description metadata is already present
[youtube] ts5pI0aG8-I: Thumbnail is already present
[debug] Invoking downloader on u'https://r5---sn-hp57knsk.googlevideo.com/videoplayback?id=b6ce69234686f3e2&itag=137&source=youtube&requiressl=yes&mv=m&ms=au&mm=31&mn=sn-hp57knsk&pl=16&nh=IgpwcjAzLm1pYTA0KgkxMjcuMC4wLjE&ratebypass=yes&mime=video/mp4&gir=yes&clen=5946039&lmt=1412901665920351&dur=29.996&mt=1459105545&upn=b__Q67knx-M&sver=3&key=dg_yt0&fexp=9416126,9420452,9422596,9423660,9423662,9427902&signature=7B15316E9AA67A6C8E96A9F83196A3A434AF1538.443D2E4DF39DFE6CBA2EED6B81F12E84250FDD09&ip=76.101.221.232&ipbits=0&expire=1459127230&sparams=ip,ipbits,expire,id,itag,source,requiressl,mv,ms,mm,mn,pl,nh,ratebypass,mime,gir,clen,lmt,dur'
[download] Why we're endorsing Al Franken for Senate-ts5pI0aG8-I.f137.mp4 has already been downloaded
[download] 100% of 5.67MiB
[debug] Invoking downloader on u'https://r5---sn-hp57knsk.googlevideo.com/videoplayback?id=b6ce69234686f3e2&itag=141&source=youtube&requiressl=yes&mv=m&ms=au&mm=31&mn=sn-hp57knsk&pl=16&nh=IgpwcjAzLm1pYTA0KgkxMjcuMC4wLjE&ratebypass=yes&mime=audio/mp4&gir=yes&clen=960149&lmt=1412901604709109&dur=30.093&mt=1459105545&upn=b__Q67knx-M&sver=3&key=dg_yt0&fexp=9416126,9420452,9422596,9423660,9423662,9427902&signature=5843C9B6465DBB93A3AE222D2961277169C78EDE.781C566978DB6DAAF7BB348E5CFBA4D4062A7BC1&ip=76.101.221.232&ipbits=0&expire=1459127230&sparams=ip,ipbits,expire,id,itag,source,requiressl,mv,ms,mm,mn,pl,nh,ratebypass,mime,gir,clen,lmt,dur'
ERROR: unable to download video data: HTTP Error 410: Gone
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1626, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1574, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 350, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1934, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 410: Gone
```

**Comment by vxbinaca** [comment] 2016-03-27 19:09
I've removed both the video data and all associated metadata and re-ran the command and the problem persists. I even ran ```--rm-cache``` to no avail.

**Comment by dstftw** [comment] 2016-03-27 19:13
format 141 is not available on YouTube.
Duplicate of #3721.

**Closed by dstftw** 2016-03-27 19:13 UTC

**Comment by vxbinaca** [comment] 2016-03-28 03:37
You sure about that? Requesting a second look, here's ```f137```:

```youtube-dl -v --ignore-config ts5pI0aG8-I```

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--ignore-config', u'ts5pI0aG8-I']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.27
[debug] Python version 2.7.10 - Linux-4.2.0-34-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: ffmpeg 2.7.6-0ubuntu0.15.10.1, ffprobe 2.7.6-0ubuntu0.15.10.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] ts5pI0aG8-I: Downloading webpage
[youtube] ts5pI0aG8-I: Downloading video info webpage
[youtube] ts5pI0aG8-I: Extracting video information
[youtube] ts5pI0aG8-I: Downloading MPD manifest
[debug] Invoking downloader on u'https://r5---sn-hp57knsk.googlevideo.com/videoplayback?id=b6ce69234686f3e2&itag=137&source=youtube&requiressl=yes&mv=m&ms=au&mn=sn-hp57knsk&pl=16&mm=31&nh=IgpwcjAzLm1pYTA0KgkxMjcuMC4wLjE&ratebypass=yes&mime=video/mp4&gir=yes&clen=5946039&lmt=1412901665920351&dur=29.996&upn=fzw7oHqR5O8&mt=1459136008&fexp=9416126,9419670,9420452,9421906,9422596,9423661,9423662,9425363,9425416,9427902,9428421,9428626,9432195&signature=5D88F6F469E94FF2ECAE6E8651B44C3CA96650A5.7AFE7260E32151691B9C1A2F0C4DB86AA61A51CE&sver=3&key=dg_yt0&ip=76.101.221.232&ipbits=0&expire=1459157758&sparams=ip,ipbits,expire,id,itag,source,requiressl,mv,ms,mn,pl,mm,nh,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Why we're endorsing Al Franken for Senate-ts5pI0aG8-I.f137.mp4
[download] 100% of 5.67MiB in 00:02
[debug] Invoking downloader on u'https://r5---sn-hp57knsk.googlevideo.com/videoplayback?id=b6ce69234686f3e2&itag=141&source=youtube&requiressl=yes&mv=m&ms=au&mn=sn-hp57knsk&pl=16&mm=31&nh=IgpwcjAzLm1pYTA0KgkxMjcuMC4wLjE&ratebypass=yes&mime=audio/mp4&gir=yes&clen=960149&lmt=1412901604709109&dur=30.093&upn=fzw7oHqR5O8&mt=1459136008&fexp=9416126,9419670,9420452,9421906,9422596,9423661,9423662,9425363,9425416,9427902,9428421,9428626,9432195&signature=4A43D749B115376706DF8C448F7F1FD58DBB1FF9.17EBCAF49C98248C61978B1BE9EFB17B5B72C92F&sver=3&key=dg_yt0&ip=76.101.221.232&ipbits=0&expire=1459157758&sparams=ip,ipbits,expire,id,itag,source,requiressl,mv,ms,mn,pl,mm,nh,ratebypass,mime,gir,clen,lmt,dur'
ERROR: unable to download video data: HTTP Error 410: Gone
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1626, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1574, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 350, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1934, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, m
```

It's grabbing the video data, as you can see, but halts on getting the audio.
