### ISSUE TITLE
Add support v.qq.com site request

### ISSUE THREAD

**Issue by moyaying** [rg3/youtube-dl#13402] opened 2017-06-16 09:32 UTC
### What is the purpose of your *issue*?
- [x] Site support request (request for adding support for a new site)
---

```
$ youtube-dl -v -j https://v.qq.com/x/page/h0333gs1cqh.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-j', 'https://v.qq.com/x/page/h0333gs1cqh.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.06.12
[debug] Git HEAD: 729a723c4
[debug] Python version 3.5.0 - Darwin-16.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.3, ffprobe 3.2.3, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: https://v.qq.com/x/page/h0333gs1cqh.html
Traceback (most recent call last):
  File "/Users/aipai/project/god-show/crawler/youtube_dl/youtube_dl/YoutubeDL.py", line 762, in extract_info
    ie_result = ie.extract(url)
  File "/Users/aipai/project/god-show/crawler/youtube_dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/Users/aipai/project/god-show/crawler/youtube_dl/youtube_dl/extractor/generic.py", line 2796, in _real_extract
    raise UnsupportedError(url)
youtube_dl.youtube_dl.utils.UnsupportedError: Unsupported URL: https://v.qq.com/x/page/h0333gs1cqh.html
...
<end of log>
```

**Comment by yan12125** [comment] 2017-06-16 20:58
Duplicate of #6831.

**Closed by yan12125** 2017-06-16 20:58 UTC
