### ISSUE TITLE
ERROR: Signature extraction failed (AGAIN)

### ISSUE THREAD

**Issue by RazoRIX** [rg3/youtube-dl#11918] opened 2017-01-31 14:14 UTC
Recently (today) the Signature Extraction failed issue made a comeback... here's the error log when trying a Youtube video.

    **_[0] => ERROR: Signature extraction failed: Traceback (most recent call last):
    [1] =>   File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1057, in _decrypt_signature
    [2] =>     video_id, player_url, s
    [3] =>   File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 971, in _extract_signature_function
    [4] =>     errnote='Download of %s failed' % player_url)
    [5] =>   File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 529, in _download_webpage
    [6] =>     res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
    [7] =>   File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 436, in _download_webpage_handle
    [8] =>     urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
    [9] =>   File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 416, in _request_webpage
    [10] =>     return self._downloader.urlopen(url_or_request)
    [11] =>   File "/usr/local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 2000, in urlopen
    [12] =>     req = sanitized_Request(req)
    [13] =>   File "/usr/local/lib/python3.5/site-packages/youtube_dl/utils.py", line 525, in sanitized_Request
    [14] =>     return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
    [15] =>   File "/usr/local/lib/python3.5/urllib/request.py", line 268, in __init__
    [16] =>     self.full_url = url
    [17] =>   File "/usr/local/lib/python3.5/urllib/request.py", line 294, in full_url
    [18] =>     self._parse()
    [19] =>   File "/usr/local/lib/python3.5/urllib/request.py", line 323, in _parse
    [20] =>     raise ValueError("unknown url type: %r" % self.full_url)
    [21] => ValueError: unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'
    [22] =>  (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output._**

**Comment by jaydenkieran** [comment] 2017-01-31 14:16
Duplicate of #11890

**Comment by ThomasChr** [comment] 2017-01-31 14:54
Why on earth does NO ONE check the issues right before???
I'm actually counting about 15 Issues for the same problem!!!

**Comment by rofl0r** [comment] 2017-01-31 14:59
maybe you should fix it then, @ThomasChr ?

**Comment by jaydenkieran** [comment] 2017-01-31 15:01
@rofl0r It's fixed in this PR #11892

**Comment by ThomasChr** [comment] 2017-01-31 15:06
Maybe a first fix has already been provided 10 issues ago?

**Closed** 2017-01-31 15:23 UTC
