### ISSUE TITLE
youtube error on v=-xdYG188Gbw

### ISSUE THREAD

**Issue by oowi** [rg3/youtube-dl#7626] opened 2015-11-24 06:41 UTC
$ git pull origin
Already up-to-date.
$ python -m youtube_dl --verbose  -f 141 "https://www.youtube.com/watch?v=-xdYG188Gbw"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-f', u'141', u'https://www.youtube.com/watch?v=-xdYG188Gbw']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.23
[debug] Git HEAD: 032f2f2
[debug] Python version 2.7.6 - Linux-3.8.11-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] -xdYG188Gbw: Downloading webpage
[youtube] -xdYG188Gbw: Downloading video info webpage
[youtube] -xdYG188Gbw: Extracting video information
[youtube] {22} signature length 49.43, html5 player en_US-vflUpjAy9
[youtube] -xdYG188Gbw: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vflUpjAy9/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "youtube_dl/extractor/youtube.py", line 856, in _decrypt_signature
    video_id, player_url, s
  File "youtube_dl/extractor/youtube.py", line 783, in _extract_signature_function
    cache_res = res(test_string)
  File "youtube_dl/extractor/youtube.py", line 835, in <lambda>
    return lambda s: initial_function([s])
  File "youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "youtube_dl/jsinterp.py", line 135, in interpret_expression
    self._objects[variable] = self.extract_object(variable)
  File "youtube_dl/jsinterp.py", line 220, in extract_object
    fields = obj_m.group('fields')
AttributeError: 'NoneType' object has no attribute 'group'
 (caused by AttributeError("'NoneType' object has no attribute 'group'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl/extractor/youtube.py", line 856, in _decrypt_signature
    video_id, player_url, s
  File "youtube_dl/extractor/youtube.py", line 783, in _extract_signature_function
    cache_res = res(test_string)
  File "youtube_dl/extractor/youtube.py", line 835, in <lambda>
    return lambda s: initial_function([s])
  File "youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "youtube_dl/jsinterp.py", line 135, in interpret_expression
    self._objects[variable] = self.extract_object(variable)
  File "youtube_dl/jsinterp.py", line 220, in extract_object
    fields = obj_m.group('fields')
AttributeError: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "youtube_dl/YoutubeDL.py", line 663, in extract_info
    ie_result = ie.extract(url)
  File "youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "youtube_dl/extractor/youtube.py", line 1410, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "youtube_dl/extractor/youtube.py", line 866, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "youtube_dl/extractor/youtube.py", line 856, in _decrypt_signature
    video_id, player_url, s
  File "youtube_dl/extractor/youtube.py", line 783, in _extract_signature_function
    cache_res = res(test_string)
  File "youtube_dl/extractor/youtube.py", line 835, in <lambda>
    return lambda s: initial_function([s])
  File "youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "youtube_dl/jsinterp.py", line 135, in interpret_expression
    self._objects[variable] = self.extract_object(variable)
  File "youtube_dl/jsinterp.py", line 220, in extract_object
    fields = obj_m.group('fields')
AttributeError: 'NoneType' object has no attribute 'group'
 (caused by AttributeError("'NoneType' object has no attribute 'group'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment] 2015-11-24 06:42
Duplicate of #7623.

**Closed by yan12125** 2015-11-24 06:42 UTC

**Comment by phihag** [comment] 2015-11-24 06:49
Thank you for the report. I believe this issue to be fixed in youtube-dl 2015.11.24 and newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.
