### ISSUE TITLE
Feature Request: When extracting audio provide the option to trim beginning and end silence/white noise

### ISSUE THREAD

**Issue by space4science** [rg3/youtube-dl#8612] opened 2016-02-19 23:13 UTC
Sometimes YouTube videos have an image introduction and/or end credits which are useless and a bit annoying when all you are interested in is the audio. Would like to be able to provide the option to trim the audio at the beginning and end.

Starting Point?
https://ffmpeg.org/ffmpeg-filters.html#silencedetect

**Comment by dstftw** [comment] 2016-02-20 03:00
Duplicate of #3529.

**Closed by dstftw** 2016-02-20 03:00 UTC
