### ISSUE TITLE
Download part of Youtube video

### ISSUE THREAD

**Issue by alexmatveev** [rg3/youtube-dl#5547] opened 2015-04-28 20:27 UTC
Is it possible to specify a time range which will be downloaded from YouTube?

**Comment by dstftw** [comment] 2015-04-28 20:33
This is not possible at the moment, consider [this comment](https://github.com/rg3/youtube-dl/issues/4821#issuecomment-72213508) for info.
Closing as duplicate of #4821.

**Closed by dstftw** 2015-04-28 20:33 UTC
