### ISSUE TITLE
Xhamster - ERROR: Unable to extract title 

### ISSUE THREAD

**Issue by delouncle** [rg3/youtube-dl#6965] opened 2015-09-25 10:12 UTC
youtube-dl --version
2015.09.22

youtube-dl --verbose "http://xhamster.com/movies/4851516/premiere_sextape_en_camera_cachee_avec_ma_copine.html"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://xhamster.com/movies/4851516/premiere_sextape_en_camera_cachee_avec_ma_copine.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.22
[debug] Python version 2.7.3 - Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Ubuntu-12.04-precise
[debug] exe versions: avconv 0.8.16-4, avprobe 0.8.16-4, ffmpeg 2.5.git, ffprobe 0.8.16-4
[debug] Proxy map: {}
[XHamster] 4851516: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and incl
ude its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 287, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/xhamster.py", line 66, in _real_extract
    title = self._html_search_regex(r'<title>(?P<title>.+?) - xHamster\.com</title>', webpage, 'title')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 590, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 581, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose
flag and include its complete output.

Thanks

**Comment by yan12125** [comment] 2015-09-25 12:26
Duplicate of #6944. It's fixed in git but not included in the latest release yet.

**Closed by yan12125** 2015-09-25 12:26 UTC
