### ISSUE TITLE
Stopped downloading from youtube user playlists

### ISSUE THREAD

**Issue by Clementwe** [rg3/youtube-dl#7550] opened 2015-11-18 18:13 UTC
Youtube-dl stopped downloading the list of videos from user video page. If I feed it links to individual videos it downloads fine, but if given the users video page it fails.
  
 youtube-dl --verbose https://www.youtube.com/user/NerdSyncProductions/videos

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/user/NerdSyncProductions/videos']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.15
[debug] Python version 2.7.6 - Linux-3.13.0-67-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6
[debug] Proxy map: {}
[youtube:user] NerdSyncProductions: Downloading channel page
[youtube:playlist] UUURz5rKDgt7YibUSageNhEw: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1644, in _real_extract
    return self._extract_playlist(playlist_id)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1619, in _extract_playlist
    page, 'title')
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 593, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by jaimeMF** [comment] 2015-11-18 18:20
Duplicate of #7544.

**Closed by jaimeMF** 2015-11-18 18:20 UTC

**Comment by phihag** [comment] 2015-11-18 18:24
Thank you for the report. I believe this issue to be fixed in youtube-dl version 2015.11.18. See [our FAQ](https://yt-dl.org/update) if you need help updating.
