### ISSUE TITLE
http://www.rts.ch/play/tv/divertissementachats/video/daft-punk-unchained?id=7153933

### ISSUE THREAD

**Issue by Rudloff** [rg3/youtube-dl#7111] opened 2015-10-09 14:00 UTC
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.rts.ch/play/tv/divertissementachats/video/daft-punk-unchained?id=7153933', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.09
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.2
[debug] exe versions: none
[debug] Proxy map: {}
[RTS] daft-punk-unchained: Downloading JSON metadata
[RTS] 7153933: Downloading m3u8 information
ERROR: Failed to download m3u8 information: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 329, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1872, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

**Comment by remitamine** [comment] 2015-10-09 19:54
it's geo restricted.
the api request contains this:
```json
{
  "Video": {
    "id": "7153933",
...
    "block": "GEOBLOCK",
...
```
which map to this message:`For legal reasons, this video is only available in Switzerland.`

**Comment by dstftw** [comment] 2015-10-09 19:57
It does not work with Swiss IP either. f4m does not work due to unsupported akamai player verification.

**Comment by remitamine** [comment] 2015-10-09 20:05
is it the akamai playerVerificationChallenge?
if it's the case i send pull request to prevent it(#6408).

**Comment by dstftw** [comment] 2015-10-09 20:18
It's probably it but it won't anyhow help in this case. Moreover I'm not sure whether `;` in `pv-2.0` is always a sign of player verification.

**Comment by remitamine** [comment] 2015-10-09 20:30
i base the code on parts of code that deal with playerVerificationChallenge in the akamai plugin for francetv player.

**Comment by dstftw** [comment] 2015-10-10 20:48
Duplicate of #4989.

**Closed by dstftw** 2015-10-10 20:48 UTC
