### ISSUE TITLE
SoundCloud: Unable to download JSON metadata: HTTP Error 401 

### ISSUE THREAD

**Issue by vaibhav1312** [rg3/youtube-dl#6947] opened 2015-09-24 13:50 UTC
$ youtube-dl -j "https://soundcloud.com/universalrepublic/jessie-j-ariana-grande-nicki-minaj-bang-bang"

ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment] 2015-09-24 13:51
Duplicate of #6930.

**Closed by dstftw** 2015-09-24 13:51 UTC
