### ISSUE TITLE
Iqiyi don't work 

### ISSUE THREAD

**Issue by yangfan3333** [rg3/youtube-dl#10953] opened 2016-10-18 05:38 UTC
C:\yy>1016 -v   http://www.iqiyi.com/v_19rr9llt5o.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.iqiyi.com/v_19rr9llt5o.html']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2016.10.16
[debug] Python version 3.4.4 - Windows-8-6.2.9200-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[iqiyi] temp_id: download video page
WARNING: unable to extract album title; please report this issue on https://yt-d
l.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
update. Be sure to call youtube-dl with the --verbose flag and include its compl
ete output.
[iqiyi] 202134201: Download playlist page 2
[iqiyi] 202134201: Download playlist page 3
[iqiyi] 202134201: Download playlist page 4
[iqiyi] 202134201: Download playlist page 5
[iqiyi] 202134201: Download playlist page 6
[iqiyi] 202134201: Download playlist page 7
[iqiyi] 202134201: Download playlist page 8
[iqiyi] 202134201: Download playlist page 9
[iqiyi] 202134201: Download playlist page 10
[iqiyi] 202134201: Download playlist page 11
[iqiyi] 202134201: Download playlist page 12
[iqiyi] 202134201: Download playlist page 13
[iqiyi] 202134201: Download playlist page 14
[iqiyi] 202134201: Download playlist page 15
[iqiyi] 202134201: Download playlist page 16
[iqiyi] 202134201: Download playlist page 17
[iqiyi] 202134201: Download playlist page 18
[download] Downloading playlist: 202134201
[iqiyi] playlist 202134201: Collected 851 video ids (downloading 851 of them)
[download] Downloading video 1 of 851
[iqiyi] temp_id: download video page
WARNING: unable to extract album title; please report this issue on https://yt-d
l.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
update. Be sure to call youtube-dl with the --verbose flag and include its compl
ete output.
[iqiyi] 202861101: Download playlist page 2
[iqiyi] 202861101: Download playlist page 3
[iqiyi] 202861101: Download playlist page 4
[iqiyi] 202861101: Download playlist page 5
[iqiyi] 202861101: Download playlist page 6
[iqiyi] 202861101: Download playlist page 7
[iqiyi] 202861101: Download playlist page 8
[iqiyi] 202861101: Download playlist page 9
[iqiyi] 202861101: Download playlist page 10
[iqiyi] 202861101: Download playlist page 11
[iqiyi] 202861101: Download playlist page 12
[iqiyi] 202861101: Download playlist page 13
[iqiyi] 202861101: Download playlist page 14
[iqiyi] 202861101: Download playlist page 15
[iqiyi] 202861101: Download playlist page 16
[download] Downloading playlist: 202861101
[iqiyi] playlist 202861101: Collected 720 video ids (downloading 720 of them)
[download] Downloading video 1 of 720
[iqiyi] temp_id: download video page
WARNING: unable to extract album title; please report this issue on https://yt-d
l.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
update. Be sure to call youtube-dl with the --verbose flag and include its compl
ete output.
[iqiyi] 202861101: Download playlist page 2
[iqiyi] 202861101: Download playlist page 3
[iqiyi] 202861101: Download playlist page 4
[iqiyi] 202861101: Download playlist page 5
[iqiyi] 202861101: Download playlist page 6
[iqiyi] 202861101: Download playlist page 7
[iqiyi] 202861101: Download playlist page 8
[iqiyi] 202861101: Download playlist page 9
[iqiyi] 202861101: Download playlist page 10
[iqiyi] 202861101: Download playlist page 11
[iqiyi] 202861101: Download playlist page 12
[iqiyi] 202861101: Download playlist page 13
[iqiyi] 202861101: Download playlist page 14
[iqiyi] 202861101: Download playlist page 15
[iqiyi] 202861101: Download playlist page 16
[download] Downloading playlist: 202861101
[iqiyi] playlist 202861101: Collected 720 video ids (downloading 720 of them)
[download] Downloading video 1 of 720
[iqiyi] temp_id: download video page
WARNING: unable to extract album title; please report this issue on https://yt-d
l.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
update. Be sure to call youtube-dl with the --verbose flag and include its compl
ete output.
[iqiyi] 202861101: Download playlist page 2
[iqiyi] 202861101: Download playlist page 3
[iqiyi] 202861101: Download playlist page 4
[iqiyi] 202861101: Download playlist page 5
[iqiyi] 202861101: Download playlist page 6
[iqiyi] 202861101: Download playlist page 7
[iqiyi] 202861101: Download playlist page 8
[iqiyi] 202861101: Download playlist page 9
[iqiyi] 202861101: Download playlist page 10
[iqiyi] 202861101: Download playlist page 11
[iqiyi] 202861101: Download playlist page 12
[iqiyi] 202861101: Download playlist page 13
[iqiyi] 202861101: Download playlist page 14
[iqiyi] 202861101: Download playlist page 15
[iqiyi] 202861101: Download playlist page 16
[download] Downloading playlist: 202861101
[iqiyi] playlist 202861101: Collected 720 video ids (downloading 720 of them)
[download] Downloading video 1 of 720
[iqiyi] temp_id: download video page
WARNING: unable to extract album title; please report this issue on https://yt-d
l.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
update. Be sure to call youtube-dl with the --verbose flag and include its compl
ete output.
[iqiyi] 202861101: Download playlist page 2
[iqiyi] 202861101: Download playlist page 3
[iqiyi] 202861101: Download playlist page 4
[iqiyi] 202861101: Download playlist page 5

ERROR: Interrupted by user

C:\yy>

**Comment by ztytian** [comment] 2016-10-19 05:59
I'm not geo-restricted.
I'm located in China

**Comment by ztytian** [comment] 2016-10-19 07:47
You-get works very well on the same video and it seems to have no issue with those other iqiyi videos that youtube-dl have issue with. Only problem is it downloads frame-by-frame so it is shit slow

**Comment by yan12125** [comment] 2016-10-19 13:12
FYI: The label "geo-restricted" indicates that the video is geo-restricted, so a developer needs to find a proxy for that.

**Comment by yangfan3333** [comment] 2016-10-19 18:38
@ztytian  You can download Iqiyi   wiht  you-get?  What is your version ？

**Comment by ztytian** [comment] 2016-10-19 19:32
you-get --version
you-get: version 0.4.555, a tiny downloader that scrapes the web.
BTY, if a proxy is needed, you can obtain one here: https://vnet.one/?rc=2879
Use OpenVPN to connect or else Python traffic won't go through.

**Comment by yangfan3333** [comment] 2016-10-19 19:47
@ztytian   thanks

**Comment by yangfan3333** [comment] 2016-10-19 20:35
@ztytian  you-get.exe 只能下载3分钟视频  你有这个问题吗？

**Comment by yan12125** [comment] 2016-10-19 21:05
Hey, it's not a bug tracker of you-get.

**Comment by ztytian** [comment] 2016-10-19 21:37
Sorry

**Comment by yangfan3333** [comment] 2016-10-20 04:55
@ztytian   

Could  you download this video(http://www.iqiyi.com/v_19rr99ulkw.html) with you-get?

I can only download 3 minutes

**Comment by yan12125** [comment] 2016-10-20 07:15
Sorry if my previous comment seems blaming anyone. My attention was that you-get problems should be reported to [you-get](https://github.com/soimort/you-get/issues). Almost all you-get experts are there, so it's more likely to get answers there than this bug tracker.

**Comment by ztytian** [comment] 2016-10-20 07:56
I know no offend was intended (and GitHub really need a PM system). Sorry for discuss it here but no offend to youtube-dl is intended. It is a great piece of software but currently it is experiencing issue with iQiyi. Would you please fix it? If you need Proxy don't hesitate to ask me. :p

**Comment by ztytian** [comment] 2016-10-20 08:06
@yangfan3333 
私下交流，麻烦提供一下联系方式，或者到you-get那边

**Comment by yangfan3333** [comment] 2016-10-20 13:17
@ztytian   QQ 2856----271006   谢谢啦。。

**Comment by ztytian** [comment] 2016-10-21 04:44
@yan12125 
Do you have a plan for fixing it?

**Comment by ztytian** [comment] 2016-10-21 04:46
@yan12125 
Can I expect an update for fixing the issue in the near version?

**Comment by yan12125** [comment] 2016-10-21 10:01
Most likely I need to wait until Iqiyi drops the Flash version. The current player uses CrossBridge, which is much beyond my ability.

**Comment by remitamine** [comment] 2016-10-21 11:50
the html5 player uses an obfuscation similar to what bilibili use to hide their api `sign` generation(`vf` for iqiyi).

**Comment by yan12125** [comment] 2016-10-21 11:54
I guess you got html5 videos by faking User-Agent to Android or iPhone? The resolution is awful there.

**Comment by remitamine** [comment] 2016-10-21 14:13
> The resolution is awful there.

if they drop the flash play they will eventually use something similar to what they are using in the current html5 player code.
for the CrossBridge a possible solution whould be to improve `swfinterp.py`(handling multiple DoABC in a single swf file, supporting more opcodes, nested scopes...).

**Comment by ztytian** [comment] 2016-10-21 23:12
you-get used some sort of recording solution to it.
They used the feed from iqiyi directly to ffmpeg and record the video itself, which can lead to many issues when ffmpeg failed to get the correct video data from the site, resulting in a non-complete download. THIS SITE IS FREAKING HARD TO DEAL WITH AND IT HOLDS THE COPYRIGHT OF MANY SHOWS.

**Comment by ztytian** [comment] 2016-10-24 20:39
I did obtain the m3u8 for the video I intended to download, but VLC refused to load it...(and crashed).
Here is the link http://cache.m.iqiyi.com/dc/dt/2669ebdx2f740c2fx777a6171/20161023/30/e8/68c086ea67df2410d19215eb3b47ff1c.m3u8?qd_sc=ad1b56eb89e90ef08e939716a08b4318&t_sign=-0-76f90cbd92f94a2e925d83e8ccd22cb7-555965100_04022000001000000000_17 
Seems to be a temporary link

**Comment by ztytian** [comment] 2016-11-07 07:54
You-Get was able to download again, as it was only the problem of broken ffmpeg.
YT-DL and You-Get used two approaches when downloading iqiyi videos as you-get resolved the m3u8 video address and feeds it into ffmpeg. Ffmpeg then download (or record) the m3u8 feed. You can consider using a similar approach to this site if Cross Bridge json structure was too difficult to handle. If I did understand your codes correctly, yt-dl attempted to resolves smaller pieces of video that is fed into the swf player.

**Comment by denobisipsis** [comment] 2017-01-24 11:16
Hi, here the cmd5x to generate vf & ibt

https://github.com/denobisipsis/adownloader/blob/master/iqiyi_vf_ibt.php

src must be 01010031010010000000 

i think that the swf-code (for src 1702633101b340d8917a69cf8a4b8c7c) is similar, but until now haven´t been able to make it work.

**Comment by yan12125** [comment] 2017-04-25 14:36
I believe this is a duplicate of #12504 and already fixed in git master. Please move on there for further discussions.

**Closed by yan12125** 2017-04-25 14:36 UTC
Labels: geo-restricted
