### ISSUE TITLE
Unable to download https://www.youtube.com/watch?v=NjG27_zVpg4

### ISSUE THREAD

**Issue by kostaz** [rg3/youtube-dl#6690] opened 2015-08-27 07:51 UTC

**Comment by kostaz** [comment] 2015-08-27 07:53
I used the latest youtube-dl version:
```
youtube-dl --version 
2015.08.23
```

Nevertheless, the error is:
```
youtube-dl --extract-audio --audio-format mp3 https://www.youtube.com/watch?v=NjG27_zVpg4
[youtube] NjG27_zVpg4: Downloading webpage
[youtube] NjG27_zVpg4: Downloading video info webpage
[youtube] NjG27_zVpg4: Extracting video information
[youtube] NjG27_zVpg4: Downloading DASH manifest
WARNING: [youtube] NjG27_zVpg4: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
ERROR: unable to download video data: HTTP Error 403: Forbidden
```

**Comment by jaimeMF** [comment] 2015-08-27 09:16
Duplicate of #6451. Remove cache with `youtube-dl --rm-cache-dir`.

**Closed by jaimeMF** 2015-08-27 09:16 UTC

**Comment by mayurss786** [comment] 2015-08-27 17:34
i am also getting 403 forbidden 
tried

youtube-dl --rm-cache-dir
youtube-dl --version 
2015.08.23

youtube-dl https://www.youtube.com/watch?v=ZEJ3P92bKZo
[youtube] ZEJ3P92bKZo: Downloading webpage
[youtube] ZEJ3P92bKZo: Downloading video info webpage
[youtube] ZEJ3P92bKZo: Extracting video information
[youtube] ZEJ3P92bKZo: Downloading DASH manifest
WARNING: [youtube] ZEJ3P92bKZo: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
ERROR: unable to download video data: HTTP Error 403: Forbidden

**Comment by mayurss786** [comment] 2015-08-27 17:36
it was stopped working from last 3 days

**Comment by jaimeMF** [comment] 2015-08-27 19:24
If you have run `youtube-dl --rm-cache-dir` and it still fails, please open a new issue and as the error message says: post the full output with the --verbose option.

**Comment by mayurss786** [comment] 2015-08-27 19:29
Its solved, i was using via php with user account 
And checking in ssh via root

I tried to clear cache command in both root n user, now youtube-dl working fine
