### ISSUE TITLE
forbidden

### ISSUE THREAD

**Issue by hansgpe** [rg3/youtube-dl#6615] opened 2015-08-19 16:32 UTC
youtube-dl -x --audio-format mp3 tLu3SA4wxOI
[youtube] tLu3SA4wxOI: Downloading webpage
[youtube] tLu3SA4wxOI: Extracting video information
[youtube] tLu3SA4wxOI: Downloading DASH manifest
WARNING: [youtube] tLu3SA4wxOI: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
ERROR: unable to download video data: HTTP Error 403: Forbidden

**Comment by dstftw** [comment] 2015-08-19 16:33
Duplicate of #6451. Remove cache with `youtube-dl --rm-cache-dir`.

**Closed by dstftw** 2015-08-19 16:33 UTC
