### ISSUE TITLE
youtube video failing with http server error

### ISSUE THREAD

**Issue by UncleOwen** [rg3/youtube-dl#12378] opened 2017-03-06 13:38 UTC
I'm getting the following error when downloading a video from youtube. Every other video works fine.

```
$ youtube-dl -v https://www.youtube.com/watch?v=_QPJQUOifJg
[debug] System config: []
[debug] User config: ['-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=_QPJQUOifJg']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.06
[debug] Python version 3.4.3 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.6
[debug] exe versions: ffmpeg 3.2-2, ffprobe 3.2-2
[debug] Proxy map: {}
[youtube] _QPJQUOifJg: Downloading webpage
[youtube] _QPJQUOifJg: Downloading video info webpage
[youtube] _QPJQUOifJg: Extracting video information
[youtube] _QPJQUOifJg: Downloading MPD manifest
[debug] Invoking downloader on 'https://r2---sn-9nj-q0ne.googlevideo.com/videoplayback?id=fd03c94143a27c98&itag=299&source=youtube&requiressl=yes&mm=31&mn=sn-9nj-q0ne&initcwndbps=915000&mv=m&pl=16&ms=au&ratebypass=yes&mime=video/mp4&gir=yes&clen=766643298&lmt=1487110148530822&dur=1309.899&upn=wJNeDscc7Ag&key=dg_yt0&mt=1488807148&signature=788256429354D9E988C0FF360A25B884231A7FC1.958E4EBD97DD727850175FCBB09BC46F68EA78B9&ip=92.196.51.189&ipbits=0&expire=1488828869&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mn,initcwndbps,mv,pl,ms,ratebypass,mime,gir,clen,lmt,dur'
[download] Got server HTTP error. Retrying (attempt 1 of 10)...
[download] Got server HTTP error. Retrying (attempt 2 of 10)...
[download] Got server HTTP error. Retrying (attempt 3 of 10)...
[download] Got server HTTP error. Retrying (attempt 4 of 10)...
[download] Got server HTTP error. Retrying (attempt 5 of 10)...
[download] Got server HTTP error. Retrying (attempt 6 of 10)...
[download] Got server HTTP error. Retrying (attempt 7 of 10)...
[download] Got server HTTP error. Retrying (attempt 8 of 10)...
[download] Got server HTTP error. Retrying (attempt 9 of 10)...
[download] Got server HTTP error. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries
  File "/home/uo/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/home/uo/youtube-dl-venv/lib/python3.4/site-packages/youtube_dl/__init__.py", line 457, in main
    _real_main(argv)
  File "/home/uo/youtube-dl-venv/lib/python3.4/site-packages/youtube_dl/__init__.py", line 447, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/uo/youtube-dl-venv/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1883, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/home/uo/youtube-dl-venv/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 772, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/uo/youtube-dl-venv/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 826, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/home/uo/youtube-dl-venv/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1527, in process_video_result
    self.process_info(new_info)
  File "/home/uo/youtube-dl-venv/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1785, in process_info
    partial_success = dl(fname, new_info)
  File "/home/uo/youtube-dl-venv/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1733, in dl
    return fd.download(name, info)
  File "/home/uo/youtube-dl-venv/lib/python3.4/site-packages/youtube_dl/downloader/common.py", line 356, in download
    return self.real_download(filename, info_dict)
  File "/home/uo/youtube-dl-venv/lib/python3.4/site-packages/youtube_dl/downloader/http.py", line 131, in real_download
    self.report_error('giving up after %s retries' % retries)
  File "/home/uo/youtube-dl-venv/lib/python3.4/site-packages/youtube_dl/downloader/common.py", line 162, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/home/uo/youtube-dl-venv/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 589, in report_error
    self.trouble(error_message, tb)
  File "/home/uo/youtube-dl-venv/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 551, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
```

**Comment by dstftw** [comment] 2017-03-06 13:41
Duplicate of #3721.

**Closed by dstftw** 2017-03-06 13:41 UTC
