### ISSUE TITLE
VHX.tv support please

### ISSUE THREAD

**Issue by dilliboy** [rg3/youtube-dl#17441] opened 2018-09-05 09:16 UTC
https://buythecoffeeman.vhx.tv/packages/the-coffee-man-film-1/videos/tcm-online-master-web
https://embed.vhx.tv/videos/106682

---

I don't really know what other url's to supply (some may not be accessible without my account, i'm not sure?) I have paid for a rental but youtube-dl does not recognize the host.

I was surprised by this because as far as I can tell it's essentially the same site as vimeo on demand. But I could be wrong.

I've successfully retrieved rental videos from on demand before, so I just assumed it would work here too, This was my mistake.

I'd love to see support for this as I have come across VHX in the past and they host some very interesting independent documentaries. 

Thanks for any help.

**Comment by dstftw** [comment] 2018-09-05 17:03
Duplicate of #14835.

**Closed** 2018-09-05 17:03 UTC
