### ISSUE TITLE
Failure to download from zonevideo.telequebec.tv

### ISSUE THREAD

**Issue by juef17** [rg3/youtube-dl#15207] opened 2018-01-09 16:31 UTC
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.07*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.07**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
francois@SilentPC:~$ youtube-dl -v https://zonevideo.telequebec.tv/media/36260/like-moi-speciale-bloopers/like-moi
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://zonevideo.telequebec.tv/media/36260/like-moi-speciale-bloopers/like-moi']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.01.07
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-104-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.11-0ubuntu0.16.04.1, avprobe 2.8.11-0ubuntu0.16.04.1, ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[TeleQuebec] 36260: Downloading JSON metadata
[debug] Using fake IP 99.230.158.134 (CA) as X-Forwarded-For.
[limelight] d4ee0dc9fe474c8695ee9f656d338b3b: Downloading PlaylistService getPlaylistByMediaId JSON
[limelight] d4ee0dc9fe474c8695ee9f656d338b3b: Downloading API properties JSON
[limelight] d4ee0dc9fe474c8695ee9f656d338b3b: Downloading PlaylistService getMobilePlaylistByMediaId JSON
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1988, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 795, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 861, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 438, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/limelight.py", line 286, in _real_extract
IndexError: list index out of range
```
---

### Description of your *issue*, suggested solution and other information

Videos cannot be downloaded with the telequebec.py extractor, including the test in that very file. The above log includes another (more recent) URL that doesn't work. youtube-dl.exe on a Windows 7 64-bit computer also fails, and aside from version differences (e.g. python 3 instead of 2) and the file paths, the log is pretty much identical.

**Comment by dstftw** [comment] 2018-01-09 22:15
Duplicate of #15150.

**Closed by dstftw** 2018-01-09 22:15 UTC
