### ISSUE TITLE
youtube - video download problem

### ISSUE THREAD

**Issue by moonrise007** [rg3/youtube-dl#6602] opened 2015-08-18 14:37 UTC
Hello

It looks like there is something changed on youtube webpage. Download of YqeW9_5kURI is falling with:

$ ./youtube-dl -f mp4 --verbose 'https://www.youtube.com/watch?v=YqeW9_5kURI'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-f', u'mp4', u'--verbose', u'https://www.youtube.com/watch?v=YqeW9_5kURI']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.16.1
[debug] Python version 2.7.9 - Linux-3.19.0-25-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, ffmpeg 2.5.8-0ubuntu0.15.04.1, ffprobe 2.5.8-0ubuntu0.15.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] YqeW9_5kURI: Downloading webpage
[youtube] YqeW9_5kURI: Downloading video info webpage
[youtube] YqeW9_5kURI: Extracting video information
[youtube] {22} signature length 40.42, html5 player new
[youtube] {43} signature length 40.42, html5 player new
[youtube] {18} signature length 40.42, html5 player new
[youtube] {5} signature length 40.42, html5 player new
[youtube] {36} signature length 40.42, html5 player new
[youtube] {17} signature length 40.42, html5 player new
[youtube] {137} signature length 40.42, html5 player new
[youtube] {248} signature length 40.42, html5 player new
[youtube] {136} signature length 40.42, html5 player new
[youtube] {247} signature length 40.42, html5 player new
[youtube] {135} signature length 40.42, html5 player new
[youtube] {244} signature length 40.42, html5 player new
[youtube] {134} signature length 40.42, html5 player new
[youtube] {243} signature length 40.42, html5 player new
[youtube] {133} signature length 40.42, html5 player new
[youtube] {242} signature length 40.42, html5 player new
[youtube] {160} signature length 40.42, html5 player new
[youtube] {278} signature length 40.42, html5 player new
[youtube] {140} signature length 40.42, html5 player new
[youtube] {171} signature length 40.42, html5 player new
[youtube] {249} signature length 40.42, html5 player new
[youtube] {250} signature length 40.42, html5 player new
[youtube] {251} signature length 40.42, html5 player new
[youtube] YqeW9_5kURI: Downloading DASH manifest
WARNING: [youtube] YqeW9_5kURI: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[debug] Invoking downloader on u'https://r3---sn-vg5obxn3-cunl.googlevideo.com/videoplayback?upn=hQM3RIiMI78&itag=22&mime=video%2Fmp4&gcr=sk&dur=178.932&fexp=9407642%2C9407992%2C9408086%2C9408093%2C9408710%2C9409069%2C9415365%2C9415435%2C9415485%2C9415868%2C9415881%2C9416023%2C9416126%2C9416729%2C9416768%2C9417056%2C9417707%2C9418058%2C9418153%2C9418437%2C9418710%2C9418824%2C9419446&sver=3&ipbits=0&expire=1439930207&sparams=dur%2Cgcr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&requiressl=yes&lmt=1427314042758719&initcwndbps=1720000&key=yt5&ms=au&id=o-AJ5Hw3DQiaJiZedIeJPSeKOPI9taxMRvdIppcoMw61rA&pl=21&mv=m&mt=1439908560&ratebypass=yes&ip=85.237.234.244&mn=sn-vg5obxn3-cunl&mm=31&source=youtube&signature=5AFF7898F5C3ABE8BFFD115F48ACA654EA85FDA2.081D818B8E9CBC1ECBF5CA74D50D09F47AEEBFF7'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1585, in process_info
    success = dl(filename, info_dict)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1527, in dl
    return fd.download(name, info)
  File "./youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "./youtube-dl/youtube_dl/downloader/http.py", line 60, in real_download
    data = self.ydl.urlopen(request)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1860, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden

====================

$ ./youtube-dl -U
youtube-dl is up-to-date (2015.08.16.1)

====================

Thanks

Lukas

**Comment by dstftw** [comment] 2015-08-18 14:38
Duplicate of #6451. Remove cache with `youtube-dl --rm-cache-dir`.

**Closed by dstftw** 2015-08-18 14:38 UTC

**Comment by moonrise007** [comment] 2015-08-18 14:41
working well, thanks for quick response :)
