### ISSUE TITLE
Either can't download YouTube _or_ it has to be merged. Both seem wrong?

### ISSUE THREAD

**Issue by tjluoma** [rg3/youtube-dl#6668] opened 2015-08-25 18:17 UTC
On my Mac running 10.11 (beta 6, I believe) I get this:

> youtube-dl -U &&  youtube-dl 'https://www.youtube.com/watch?v=6vQpW9XRiyM'

youtube-dl is up-to-date (2015.08.23)
[youtube] 6vQpW9XRiyM: Downloading webpage
[youtube] 6vQpW9XRiyM: Downloading video info webpage
[youtube] 6vQpW9XRiyM: Extracting video information
[youtube] 6vQpW9XRiyM: Downloading DASH manifest
WARNING: [youtube] 6vQpW9XRiyM: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
ERROR: unable to download video data: HTTP Error 403: Forbidden

On my 10.10 Mac I get this:

> youtube-dl -U &&  youtube-dl 'https://www.youtube.com/watch?v=6vQpW9XRiyM'

youtube-dl is up-to-date (2015.08.23)
[youtube] 6vQpW9XRiyM: Downloading webpage
[youtube] 6vQpW9XRiyM: Downloading video info webpage
[youtube] 6vQpW9XRiyM: Extracting video information
[youtube] 6vQpW9XRiyM: Downloading js player new
[youtube] 6vQpW9XRiyM: Downloading DASH manifest
[download] Destination: Bruce Springsteen - Glory Days-6vQpW9XRiyM.f135.mp4
[download] 100% of 27.92MiB in 00:03
[download] Destination: Bruce Springsteen - Glory Days-6vQpW9XRiyM.f141.m4a
[download] 100% of 10.40MiB in 00:04
[ffmpeg] Merging formats into "Bruce Springsteen - Glory Days-6vQpW9XRiyM.mp4"
Deleting original file Bruce Springsteen - Glory Days-6vQpW9XRiyM.f135.mp4 (pass -k to keep)
Deleting original file Bruce Springsteen - Glory Days-6vQpW9XRiyM.f141.m4a (pass -k to keep)

I don't remember this happening in the past, it used to just download the video, there was no merge, AFAICT.

(It’s possible that I might have compiled one with different args?)

**Comment by dstftw** [comment] 2015-08-25 18:19
1. Duplicate of #6451. Remove cache with `youtube-dl --rm-cache-dir`.
2. Default behavior has changed. Read the last two paragraphs of [format selection section](https://github.com/rg3/youtube-dl#format-selection).

**Closed by dstftw** 2015-08-25 18:19 UTC
