### ISSUE TITLE
facebook video not working

### ISSUE THREAD

**Issue by treaki** [rg3/youtube-dl#8578] opened 2016-02-16 12:27 UTC
reports a 500 internal server error, but video is playing in browser. Maybe youll need to use another useragent to pass tests on the facebook server...

```
$ youtube-dl --verbose https://www.facebook.com/axel.klos.7/videos/1636612619944995/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.facebook.com/axel.klos.7/videos/1636612619944995/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.13
[debug] Python version 2.7.9 - Linux-4.2.0-0.bpo.1-amd64-x86_64-with-debian-8.2
[debug] exe versions: avconv 2.6.3, avprobe 2.6.3, ffmpeg 2.6.3, ffprobe 2.6.3, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] 1636612619944995: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 500: Internal Server Error (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 354, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1905, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)


```

plaese fix that

thanks in advance, regards

**Comment by yan12125** [comment] 2016-02-16 14:31
Duplicate of #8504. See my comments there.

**Closed by yan12125** 2016-02-16 14:31 UTC
