### ISSUE TITLE
[QQ]UnsupportedError: Unsupported URL: http://v.qq.com/cover/i/ipmc5u3dwb48mv2.html?vid=v0021p0s0i7

### ISSUE THREAD

**Issue by Irving23** [rg3/youtube-dl#10230] opened 2016-08-05 08:32 UTC
➜  ~ youtube-dl -vF http://v.qq.com/cover/i/ipmc5u3dwb48mv2.html\?vid\=v0021p0s0i7
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-vF', u'http://v.qq.com/cover/i/ipmc5u3dwb48mv2.html?vid=v0021p0s0i7']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.01
[debug] Python version 2.7.10 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.0.2, ffprobe 3.0.2
[debug] Proxy map: {}
[generic] ipmc5u3dwb48mv2: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ipmc5u3dwb48mv2: Downloading webpage
[generic] ipmc5u3dwb48mv2: Extracting information
ERROR: Unsupported URL: http://v.qq.com/cover/i/ipmc5u3dwb48mv2.html?vid=v0021p0s0i7
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1610, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2525, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2514, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 6, column 60
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 682, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2336, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://v.qq.com/cover/i/ipmc5u3dwb48mv2.html?vid=v0021p0s0i7

**Comment by yan12125** [comment] 2016-08-05 09:44
Duplicate of #6831.

**Closed by yan12125** 2016-08-05 09:44 UTC
