### ISSUE TITLE
YT Chanel download  DASH manifest: HTTP Error 403

### ISSUE THREAD

**Issue by Marv-X** [rg3/youtube-dl#6236] opened 2015-07-15 08:04 UTC
I'm getting this error while downloading a channel and the program recommended that I post the error output.
I downloaded some videos however then the program gets this issue and stops.
I can post the log however its a 104KB file and contains only the results of successful downloads.

F:\YTD>youtube-dl.exe -cit --verbose "https://www.youtube.com/user/TryMike4insta
nce/videos" >log
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-cit', u'--verbose', u'https://www.youtube.com/use
r/TryMike4instance/videos']
[debug] Encodings: locale cp1250, fs mbcs, out None, pref cp1250
[debug] youtube-dl version 2015.07.07
[debug] Python version 2.7.8 - Windows-XP-5.1.2600-SP3
[debug] exe versions: none
[debug] Proxy map: {}
WARNING: [youtube] AUANVrNwYyQ: Skipping DASH manifest: ExtractorError(u'Could n
ot download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); pl
ease report this issue on https://yt-dl.org/bug . Make sure you are using the la
test version; type  youtube-dl -U  to update. Be sure to call youtube-dl with th
e --verbose flag and include its complete output.',)
WARNING: [youtube] HOBWnuRPDXk: Skipping DASH manifest: ExtractorError(u'Could n
ot download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); pl
ease report this issue on https://yt-dl.org/bug . Make sure you are using the la
test version; type  youtube-dl -U  to update. Be sure to call youtube-dl with th
e --verbose flag and include its complete output.',)
WARNING: [youtube] GJM5GfXgchI: Skipping DASH manifest: ExtractorError(u'Could n
ot download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); pl
ease report this issue on https://yt-dl.org/bug . Make sure you are using the la
test version; type  youtube-dl -U  to update. Be sure to call youtube-dl with th
e --verbose flag and include its complete output.',)
WARNING: [youtube] e5sXbXwI83o: Skipping DASH manifest: ExtractorError(u'Could n
ot download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); pl
ease report this issue on https://yt-dl.org/bug . Make sure you are using the la
test version; type  youtube-dl -U  to update. Be sure to call youtube-dl with th
e --verbose flag and include its complete output.',)
WARNING: [youtube] 6JsoW6_BaYE: Skipping DASH manifest: ExtractorError(u'Could n
ot download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); pl
ease report this issue on https://yt-dl.org/bug . Make sure you are using the la
test version; type  youtube-dl -U  to update. Be sure to call youtube-dl with th
e --verbose flag and include its complete output.',)
WARNING: [youtube] zNkDrN41f2o: Skipping DASH manifest: ExtractorError(u'Could n
ot download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); pl
ease report this issue on https://yt-dl.org/bug . Make sure you are using the la
test version; type  youtube-dl -U  to update. Be sure to call youtube-dl with th
e --verbose flag and include its complete output.',)
WARNING: [youtube] 7CX4uCkzccY: Skipping DASH manifest: ExtractorError(u'Could n
ot download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); pl
ease report this issue on https://yt-dl.org/bug . Make sure you are using the la
test version; type  youtube-dl -U  to update. Be sure to call youtube-dl with th
e --verbose flag and include its complete output.',)
WARNING: [youtube] ibJyIE0dBvM: Skipping DASH manifest: ExtractorError(u'Could n
ot download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); pl
ease report this issue on https://yt-dl.org/bug . Make sure you are using the la
test version; type  youtube-dl -U  to update. Be sure to call youtube-dl with th
e --verbose flag and include its complete output.',)
WARNING: [youtube] r2bs__UCxHM: Skipping DASH manifest: ExtractorError(u'Could n
ot download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); pl
ease report this issue on https://yt-dl.org/bug . Make sure you are using the la
test version; type  youtube-dl -U  to update. Be sure to call youtube-dl with th
e --verbose flag and include its complete output.',)

**Comment by mikhaelkh** [comment] 2015-07-15 08:48
Same problem.
And another problem: Requested formats are incompatible for merge and will be merged into mkv.
```
[debug] System config: []
[debug] User config: [u'--verbose']
[debug] Command-line args: [u'https://www.youtube.com/watch?v=ij_0p_6qTss']
[debug] Encodings: locale cp1251, fs mbcs, out None, pref cp1251
[debug] youtube-dl version 2015.07.07
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 2.7, ffprobe 2.7
[debug] Proxy map: {}
[youtube] ij_0p_6qTss: Downloading webpage
[youtube] ij_0p_6qTss: Downloading video info webpage
[youtube] ij_0p_6qTss: Extracting video information
[youtube] {22} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {43} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {18} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {5} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {36} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {17} signature length 41.40, html5 player en_US-vflVsMRd_
[youtube] {137} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {248} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {136} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {247} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {135} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {244} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {134} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {243} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {133} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {242} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {160} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {278} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {140} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {171} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {249} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {250} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {251} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] ij_0p_6qTss: Downloading DASH manifest
[youtube] ij_0p_6qTss: Downloading DASH manifest
WARNING: [youtube] ij_0p_6qTss: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r3---sn-n8t51nxg8pjx-2xne.googlevideo.com/videoplayback?id=8a3ff4a7feaa4ecb&itag=248&source=youtube&requiressl=yes&pl=19&ms=au&mm=31&gcr=ru&pcm2cms=yes&mn=sn-n8t51nxg8pjx-2xne&mv=m&ratebypass=yes&mime=video/webm&gir=yes&clen=50619990&lmt=1415363354216850&dur=275.150&upn=q0yASejuIJ0&key=dg_yt0&mt=1436949681&fexp=901816,919154,936126,9408142,9408420,9408710,9414764,9416126,962727&sver=3&signature=721B7684D7BF6056835184F6B8583654645BC458.3C9A036E5813E9789C4B5FC169F656A621384C99&ip=212.109.6.214&ipbits=0&expire=1436971332&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,ms,mm,gcr,pcm2cms,mn,mv,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Selena Gomez - The Heart Wants What It Wants (Official Video)-ij_0p_6qTss.f248.webm

[download]   0.0% of 48.27MiB at Unknown speed ETA Unknown ETA
[download]   0.0% of 48.27MiB at Unknown speed ETA Unknown ETA
[download]   0.0% of 48.27MiB at Unknown speed ETA Unknown ETA
[download]   0.0% of 48.27MiB at Unknown speed ETA Unknown ETA
[download]   0.1% of 48.27MiB at Unknown speed ETA Unknown ETA
[download]   0.1% of 48.27MiB at Unknown speed ETA Unknown ETA
[download]   0.3% of 48.27MiB at  7.75MiB/s ETA 00:06         
[download]   0.5% of 48.27MiB at  7.78MiB/s ETA 00:06         
[download]   1.0% of 48.27MiB at  8.91MiB/s ETA 00:05         
[download]   2.1% of 48.27MiB at  8.84MiB/s ETA 00:05         
[download]   4.1% of 48.27MiB at  9.21MiB/s ETA 00:05         
[download]   8.3% of 48.27MiB at  9.78MiB/s ETA 00:04         
[download]  16.6% of 48.27MiB at 10.37MiB/s ETA 00:03         
[download]  24.9% of 48.27MiB at 10.53MiB/s ETA 00:03         
[download]  33.1% of 48.27MiB at 10.56MiB/s ETA 00:03         
[download]  41.4% of 48.27MiB at 10.71MiB/s ETA 00:02         
[download]  49.7% of 48.27MiB at 10.73MiB/s ETA 00:02         
[download]  58.0% of 48.27MiB at 10.82MiB/s ETA 00:01         
[download]  66.3% of 48.27MiB at 10.83MiB/s ETA 00:01         
[download]  74.6% of 48.27MiB at 10.85MiB/s ETA 00:01         
[download]  82.9% of 48.27MiB at 10.87MiB/s ETA 00:00         
[download]  91.1% of 48.27MiB at 10.88MiB/s ETA 00:00         
[download]  99.4% of 48.27MiB at 10.86MiB/s ETA 00:00         
[download] 100.0% of 48.27MiB at 10.89MiB/s ETA 00:00         
[download] 100% of 48.27MiB in 00:04                          
[debug] Invoking downloader on 'https://r3---sn-n8t51nxg8pjx-2xne.googlevideo.com/videoplayback?id=8a3ff4a7feaa4ecb&itag=141&source=youtube&requiressl=yes&pl=19&ms=au&mm=31&gcr=ru&pcm2cms=yes&mn=sn-n8t51nxg8pjx-2xne&mv=m&ratebypass=yes&mime=audio/mp4&gir=yes&clen=8776176&lmt=1415229533771983&dur=275.249&upn=q0yASejuIJ0&key=dg_yt0&mt=1436949681&fexp=901816,919154,936126,9408142,9408420,9408710,9414764,9416126,962727&sver=3&signature=3D3D463FCD73A657D5216988795D9E80ED311926.1D83718C855845ED90FD25278DBEB980E00E4848&ip=212.109.6.214&ipbits=0&expire=1436971332&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,ms,mm,gcr,pcm2cms,mn,mv,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Selena Gomez - The Heart Wants What It Wants (Official Video)-ij_0p_6qTss.f141.m4a

[download]   0.0% of 8.37MiB at 200.00KiB/s ETA 00:42
[download]   0.0% of 8.37MiB at 500.00KiB/s ETA 00:17
[download]   0.1% of 8.37MiB at  1.14MiB/s ETA 00:07 
[download]   0.2% of 8.37MiB at  2.44MiB/s ETA 00:03 
[download]   0.4% of 8.37MiB at  4.32MiB/s ETA 00:01 
[download]   0.7% of 8.37MiB at  7.69MiB/s ETA 00:01 
[download]   1.5% of 8.37MiB at  9.54MiB/s ETA 00:00 
[download]   3.0% of 8.37MiB at  8.30MiB/s ETA 00:00 
[download]   6.0% of 8.37MiB at 10.18MiB/s ETA 00:00 
[download]  11.9% of 8.37MiB at  9.70MiB/s ETA 00:00 
[download]  23.9% of 8.37MiB at  9.95MiB/s ETA 00:00 
[download]  47.8% of 8.37MiB at 10.28MiB/s ETA 00:00 
[download]  95.6% of 8.37MiB at 10.27MiB/s ETA 00:00 
[download] 100.0% of 8.37MiB at 10.38MiB/s ETA 00:00 
[download] 100% of 8.37MiB in 00:00                  
[ffmpeg] Merging formats into "Selena Gomez - The Heart Wants What It Wants (Official Video)-ij_0p_6qTss.mkv"
[debug] ffmpeg command line: ffmpeg -y -i 'Selena Gomez - The Heart Wants What It Wants (Official Video)-ij_0p_6qTss.f248.webm' -i 'Selena Gomez - The Heart Wants What It Wants (Official Video)-ij_0p_6qTss.f141.m4a' -c copy -map 0:v:0 -map 1:a:0 'Selena Gomez - The Heart Wants What It Wants (Official Video)-ij_0p_6qTss.temp.mkv'
Deleting original file Selena Gomez - The Heart Wants What It Wants (Official Video)-ij_0p_6qTss.f248.webm (pass -k to keep)
Deleting original file Selena Gomez - The Heart Wants What It Wants (Official Video)-ij_0p_6qTss.f141.m4a (pass -k to keep)
```

**Comment by jaimeMF** [comment] 2015-07-15 09:19
Duplicate of #5118.

**Closed by jaimeMF** 2015-07-15 09:19 UTC
