### ISSUE TITLE
Downloads wrong subtitles extention with "--skip-download" argument on Youtube

### ISSUE THREAD

**Issue by F5System** [rg3/youtube-dl#11658] opened 2017-01-10 00:22 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.08*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.08**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

I use the latest version **2017.01.08**
I want to download Youtube's auto generated subtitles without downloading video in .SRT format. When I download subtitles+video — everything work correct. When I add "--skip-download" to skip video download, subtitles download in .VTT format (default for Youtube).

Here is my command in .bat file which download's wrong .VTT format
"C:\Program Files\youtube-dl.exe" --skip-download --write-auto-sub --sub-lang en --convert-subs srt --output "D:\_YOUTUBE\AUTOGENERATED_%%(title)s.%%(ext)s" --download-archive "D:\_YOUTUBE\archive.txt" "https://www.youtube.com/playlist?list=PLBr3GJrGh9o08Aibs53_qPBFq3QBQf98O" 

If I remove "--skip-download" then it downloads .SRT as expected.

**Comment by F5System** [comment] 2017-01-10 00:42
Sorry, looks like this is a copy of this problem
https://github.com/rg3/youtube-dl/issues/9073

**Comment by dstftw** [comment] 2017-01-10 02:15
Duplicate of #9073.

**Closed by dstftw** 2017-01-10 02:15 UTC
