### ISSUE TITLE
Failure to get youtube video - others work

### ISSUE THREAD

**Issue by sambler** [rg3/youtube-dl#12275] opened 2017-02-26 08:26 UTC
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.24.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.24.1**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)

---

While I have downloaded other videos fine I have found one particular youtube video that presents a http error and fails to download. I have been able to download this video with other software.

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
% youtube-dl -v "https://www.youtube.com/watch?v=ytRanDEXV8Y"
[debug] System config: []
[debug] User config: ['-o', '%(autonumber)s_%(playlist_index)s_%(title)s_%(extractor)s_%(id)s.%(ext)s', '--ignore-errors', '--autonumber-size', '3', '--restrict-filenames', '--continue', '--sub-lang', 'en', '--embed-subs', '--ffmpeg-location', '/usr/local/bin/ffmpeg', '--format', '22/136+140/137+140/136+bestaudio[ext=m4a]/137+bestaudio[ext=m4a]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '--merge-output-format', 'mp4']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=ytRanDEXV8Y']
WARNING: --autonumber-size is deprecated. Use output template with %(autonumber)0Nd, where N in the number of digits instead.
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.24.1
[debug] Python version 3.5.2 - FreeBSD-11.0-STABLE-amd64-64bit-ELF
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] ytRanDEXV8Y: Downloading webpage
[youtube] ytRanDEXV8Y: Downloading video info webpage
[youtube] ytRanDEXV8Y: Extracting video information
[youtube] ytRanDEXV8Y: Downloading MPD manifest
[debug] Invoking downloader on 'https://r2---sn-ppoxu-5qaz.googlevideo.com/videoplayback?source=youtube&initcwndbps=917500&dur=361.557&lmt=1488019314561143&ratebypass=yes&mm=31&ipbits=0&beids=%5B9452307%5D&key=yt6&ip=2001%3A44b8%3A20e%3Ab200%3Ab248%3A7aff%3Afeda%3A65d&mn=sn-ppoxu-5qaz&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&mt=1488096933&mv=m&ms=au&mime=video%2Fmp4&id=o-AF8Kd-Bn4F5pRyZvJ1s-We8mwayj6nT25UFku6z8Hjvy&pl=32&ei=_o6yWOLkJYG-4gKl3J-wDw&signature=7A86412678A4B3CC48AC23F9652D3A1989BE97A5.9E9C35B7C4F4B011F5312D941B2C46199FA63AC5&requiressl=yes&pcm2cms=yes&itag=22&upn=Kab5wqU33Cw&expire=1488118622'
[download] Got server HTTP error. Retrying (attempt 1 of 10)...
[download] Got server HTTP error. Retrying (attempt 2 of 10)...
[download] Got server HTTP error. Retrying (attempt 3 of 10)...
[download] Got server HTTP error. Retrying (attempt 4 of 10)...
[download] Got server HTTP error. Retrying (attempt 5 of 10)...
[download] Got server HTTP error. Retrying (attempt 6 of 10)...
[download] Got server HTTP error. Retrying (attempt 7 of 10)...
[download] Got server HTTP error. Retrying (attempt 8 of 10)...
[download] Got server HTTP error. Retrying (attempt 9 of 10)...
[download] Got server HTTP error. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries
  File "/usr/local/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 452, in main
    _real_main(argv)
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 442, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1883, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 772, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 826, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1527, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1791, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1733, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 353, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 131, in real_download
    self.report_error('giving up after %s retries' % retries)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 162, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 589, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 551, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

```

**Comment by dstftw** [comment] 2017-02-26 08:33
Duplicate of #3721.

**Closed by dstftw** 2017-02-26 08:33 UTC
