### ISSUE TITLE
Updated youtube-dl to version ... dialog pushed to wrong cmd

### ISSUE THREAD

**Issue by mikhaelkh** [rg3/youtube-dl#7248] opened 2015-10-20 20:23 UTC
I wrote this batch file and put it and youtube-dl.exe in the same directory in PATH
```Batchfile
pushd "%~dp0"
cmd /c youtube-dl.exe -U
popd
```
It seems after update `youtube-dl` calls `ping` and terminates, which causes the message `Updated youtube-dl to version ...` to push to the derived cmd instead of which actually calls `youtube-dl`.

**Comment by dstftw** [comment] 2015-10-20 20:43
Duplicate of #5810.

**Closed by dstftw** 2015-10-20 20:43 UTC
