### ISSUE TITLE
Comment link after successful download with --batch-file

### ISSUE THREAD

**Issue by OhNiice** [rg3/youtube-dl#16837] opened 2018-06-27 21:30 UTC
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.25**

- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Feature request (request for a new functionality)

---

Hi!

I read the doc, especially the Options part, and I'd like to make a request for a new option which I think shouldn't be a default behavior.

The new option would be to automatically add a comment character `# ; ]` to a batch download link after a (un?)successful download. In the case some links can't download and you absolutely want the whole list (using `until ... do`), youtube-dl wouldn't have to iterate over the whole batch file again and again.

Some pseudocode will make it more understandable hopefully :
```
for link in batchFile
    ...
    downloadVideo(link)
    ...
    if options.comment_link_after_successful_batch_download and link.isDownloadedSuccessfully
        newLink = '#' + link
        replaceInFile(batchFile, link, newLink)
    endif
endfor
```

**Comment by dstftw** [comment] 2018-06-27 21:38
Duplicate of #557.

**Closed by dstftw** 2018-06-27 21:38 UTC

**Comment by OhNiice** [comment] 2018-06-28 16:30
Thanks!
