### ISSUE TITLE
Please add support for ITV Hub

### ISSUE THREAD

**Issue by okhs** [rg3/youtube-dl#11450] opened 2016-12-15 19:29 UTC
Please add support for ITV Hub in youtube-dl

https://en.wikipedia.org/wiki/ITV_Hub

There is already a piece of working software, but only for OSX.
http://tom-tech.com/iplayer_automator/iPlayer_Automator/Get_iPlayer_Automator.html
https://github.com/GetiPlayerAutomator/get-iplayer-automator
(based on get_iplayer)

Example video link for ITV Hub:
http://www.itv.com/hub/a-is-for-acid/Ya1370a0001

Please add support for youtube-dl, so Windows and Linux users are also able to access ITV Hub.
And I personally prefer youtube-dl.

Thanks!

**Comment by yan12125** [comment] 2016-12-20 09:44
Duplicate of #9240

**Closed by yan12125** 2016-12-20 09:44 UTC
