### ISSUE TITLE
permission denied: youtube-dl -U

### ISSUE THREAD

**Issue by rsd3k** [rg3/youtube-dl#4049] opened 2014-10-28 05:39 UTC
I have placed youtube-dl.exe in C:\scripts\ folder and set the environment variable in Windows.

When I try to perform an update from a directory other than the installed directory I get a permission error.
However it works fine as longs as cd in to the installed directory.
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-U', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2014.10.18
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] Proxy map: {}
Updating to version 2014.10.27 ...
ERROR: no write permissions on youtube-dl
```

**Comment by dstftw** [comment] 2015-12-25 13:55
Duplicate of #2718.

**Closed by dstftw** 2015-12-25 13:55 UTC
