### ISSUE TITLE
[soundcloud] Unable to download JSON metadata: HTTP Error 401

### ISSUE THREAD

**Issue by pihug12** [rg3/youtube-dl#6938] opened 2015-09-23 19:25 UTC
Youtube-DL is up-to-date (version 2015.09.22) and I can't download tracks from Soundcloud.

    λ python youtube-dl https://soundcloud.com/kove/guestmix-for-friction-on-bbc-r1-15th-sept-2015 --verbose
    [debug] System config: []
    [debug] User config: [u'--no-mtime', u'--no-cache-dir']
    [debug] Command-line args: [u'https://soundcloud.com/kove/guestmix-for-friction-on-bbc-r1-15th-sept-2015', u'--verbose']
    [debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
    [debug] youtube-dl version 2015.09.22
    [debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
    [debug] exe versions: none
    [debug] Proxy map: {}
    [soundcloud] kove/guestmix-for-friction-on-bbc-r1-15th-sept-2015: Resolving id
    [soundcloud] kove/guestmix-for-friction-on-bbc-r1-15th-sept-2015: Downloading info JSON
    ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
      File "youtube-dl\youtube_dl\extractor\common.py", line 326, in _request_webpage
        return self._downloader.urlopen(url_or_request)
      File "youtube-dl\youtube_dl\YoutubeDL.py", line 1865, in urlopen
        return self._opener.open(req, timeout=self._socket_timeout)
      File "D:\Python27\lib\urllib2.py", line 410, in open
        response = meth(req, response)
      File "D:\Python27\lib\urllib2.py", line 523, in http_response
        'http', request, response, code, msg, hdrs)
      File "D:\Python27\lib\urllib2.py", line 448, in error
        return self._call_chain(*args)
      File "D:\Python27\lib\urllib2.py", line 382, in _call_chain
        result = func(*args)
      File "D:\Python27\lib\urllib2.py", line 531, in http_error_default
        raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

---

    λ python youtube-dl https://soundcloud.com/tim-e-aka-current-value/current-value-abrasion-free-download --verbose
    [debug] System config: []
    [debug] User config: [u'--no-mtime', u'--no-cache-dir']
    [debug] Command-line args: [u'https://soundcloud.com/tim-e-aka-current-value/current-value-abrasion-free-download', u'--verbose']
    [debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
    [debug] youtube-dl version 2015.09.22
    [debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
    [debug] exe versions: none
    [debug] Proxy map: {}
    [soundcloud] tim-e-aka-current-value/current-value-abrasion-free-download: Resolving id
    [soundcloud] tim-e-aka-current-value/current-value-abrasion-free-download: Downloading info JSON
    ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
      File "youtube-dl\youtube_dl\extractor\common.py", line 326, in _request_webpage
        return self._downloader.urlopen(url_or_request)
      File "youtube-dl\youtube_dl\YoutubeDL.py", line 1865, in urlopen
        return self._opener.open(req, timeout=self._socket_timeout)
      File "D:\Python27\lib\urllib2.py", line 410, in open
        response = meth(req, response)
      File "D:\Python27\lib\urllib2.py", line 523, in http_response
        'http', request, response, code, msg, hdrs)
      File "D:\Python27\lib\urllib2.py", line 448, in error
        return self._call_chain(*args)
      File "D:\Python27\lib\urllib2.py", line 382, in _call_chain
        result = func(*args)
      File "D:\Python27\lib\urllib2.py", line 531, in http_error_default
        raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by pihug12** [comment] 2015-09-23 19:38
Oups! I didn't see https://github.com/rg3/youtube-dl/commit/eb11cbe8674705647d6bd2947a44e08543663633 and https://github.com/rg3/youtube-dl/issues/6930.
My bad!

**Comment by capsload** [comment] 2015-09-23 22:05
I did youtube-dl -U , but still that bug.

**Comment by SirCmpwn** [comment] 2015-09-24 00:12
Ditto. Fix does not work.

**Comment by pricejn2** [comment] 2015-09-24 01:20
The fix will be in the next release (ie, whatever comes after 2015.09.22). Until then `youtube-dl -U` won't help.

**Comment by SirCmpwn** [comment] 2015-09-24 01:21
I tested from git.

**Comment by pricejn2** [comment] 2015-09-24 01:22
@SirCmpwn it works for me.

**Comment by SirCmpwn** [comment] 2015-09-24 01:23
My bad. After testing again, it works. Must have done something wrong the first time around.

**Comment by dstftw** [comment] 2015-09-24 03:08
Duplicate of #6930.

**Closed by dstftw** 2015-09-24 03:08 UTC
