### ISSUE TITLE
--embed-thumbnail | AtomicParsley error

### ISSUE THREAD

**Issue by fohrums** [rg3/youtube-dl#4134] opened 2014-11-08 06:42 UTC
option --embed-thumbnail isn't working due to an 

# AtomicParsley error
## bad mpeg4 file

<code>
dragonslayer@dungeon:~/Downloads$ youtube-dl https://www.youtube.com/watch?v=Be9kCaFdujU -x --audio-format mp3 --embed-thumbnail
[youtube] Confirming age
[youtube] Be9kCaFdujU: Downloading webpage
[youtube] Be9kCaFdujU: Downloading video info webpage
[youtube] Be9kCaFdujU: Extracting video information
[youtube] Be9kCaFdujU: Downloading DASH manifest
[download] Destination: Black Hawk Down Symphony-Be9kCaFdujU.m4a
[download] 100% of 3.65MiB in 00:01
[avconv] Destination: Black Hawk Down Symphony-Be9kCaFdujU.mp3
[ffmpeg] Fixing audio file "Black Hawk Down Symphony-Be9kCaFdujU.mp3"
[atomicparsley] Adding thumbnail to "Black Hawk Down Symphony-Be9kCaFdujU.mp3"
ERROR: AtomicParsley error: bad mpeg4 file (ftyp atom missing or alignment error).
</code>

**Comment by Nothing4You** [comment] 2015-04-07 08:37
Duplicate of #2768

**Comment by pulpe** [comment] 2015-04-24 07:32
Should be fixed by ddbed36455f8b3053f38d84b2e62e2fb5cd66eac. If you encounter another problems, please open a new issue.

**Closed by pulpe** 2015-04-24 07:32 UTC
Labels: request

**Comment by sergeevabc** [comment] 2018-01-31 10:32
Still an issue.

```
$ youtube-dl -v -f "bestaudio[ext=mp3]/bestaudio" --embed-thumbnail -o "%(title)s.%(ext)s" https://www.youtube.com/watch?v=iKeu9C7OC6o
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'bestaudio[ext=mp3]/bestaudio', '--embed-thumbnail', '-o', '%(title)s.%(ext)s', 'https://www.youtube.com/watch?v=iKeu9C7OC6o']
[debug] Encodings: locale cp1251, fs mbcs, out cp65001, pref cp1251
[debug] youtube-dl version 2018.01.27
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1
[debug] Proxy map: {}
[youtube] iKeu9C7OC6o: Downloading webpage
[youtube] iKeu9C7OC6o: Downloading video info webpage
[youtube] iKeu9C7OC6o: Extracting video information
[youtube] iKeu9C7OC6o: Downloading thumbnail ...
[youtube] iKeu9C7OC6o: Writing thumbnail to: Jordan Peterson - Guidance Around Taking Notes From Books & Lectures.jpg
[debug] Invoking downloader on 'https://r5---sn-gvnuxaxjvh-c35s.googlevideo.com/videoplayback?mn=sn-gvnuxaxjvh-c35s&mm=31&pl=17&id=o-AMJ9epEPL3qb1HYTe7Ii4CvlgYVp3sA3spVo6IWGCVAY&requiressl=yes&ip=██.███.██.███&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&mv=m&mt=1517394448&ms=au&keepalive=yes&ei=eppxWvasB87M1wK-q5-wDQ&initcwndbps=1441250&source=youtube&lmt=1496619504050085&itag=140&clen=2520572&signature=8236B7F1D5CE0E8A9D54EFBF29990B896C3AA5C1.11D1F814743950D8AA12254D59C6A0A17F3B4075&key=yt6&mime=audio%2Fmp4&gir=yes&dur=158.661&ipbits=0&expire=1517416154&ratebypass=yes'
[download] Destination: Jordan Peterson - Guidance Around Taking Notes From Books & Lectures.m4a
[download] 100% of 2.40MiB in 00:35
[ffmpeg] Correcting container in "Jordan Peterson - Guidance Around Taking Notes From Books & Lectures.m4a"
[debug] ffmpeg command line: ffmpeg -y -i "file:Jordan Peterson - Guidance Around Taking Notes From Books & Lectures.m4a" -c copy -f mp4 "file:Jordan Peterson - Guidance Around Taking Notes From Books & Lectures.temp.m4a"
ERROR: AtomicParsley was not found. Please install.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn97fzem4\build\youtube_dl\YoutubeDL.py", line 2034, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn97fzem4\build\youtube_dl\postprocessor\embedthumbnail.py", line 59, in run
youtube_dl.postprocessor.embedthumbnail.EmbedThumbnailPPError: AtomicParsley was not found. Please install.                          
```

**Comment by sergeevabc** [comment] 2018-01-31 10:43
Getting [AtomicPasrsley][1] solves the issue.

[1]: https://bitbucket.org/jonhedgerows/atomicparsley/downloads/
