### ISSUE TITLE
unable to download from playwire

### ISSUE THREAD

**Issue by wwwamroth** [rg3/youtube-dl#8088] opened 2015-12-31 18:45 UTC
unable to download anything from playwire.com

here the output

```ruby
C:\Users\Administrator\Desktop>youtube-dl2.py -v config.playwire.com/12342/video
s/v2/4447676/zeus.json
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'config.playwire.com/12342/videos/v2/4447676
/zeus.json']
[debug] Encodings: locale cp1254, fs mbcs, out cp857, pref cp1254
[debug] youtube-dl version 2015.12.31
[debug] Python version 2.7.11rc1 - Windows-2008Server-6.0.6001-SP1
[debug] exe versions: none
[debug] Proxy map: {}
WARNING: The url doesn't specify the protocol, trying with http
[Playwire] 4447676: Downloading JSON metadata
[Playwire] 4447676: Downloading XML
ERROR: Unable to download XML: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] c
ertificate verify failed (_ssl.c:590)> (caused by URLError(SSLError(1, u'[SSL: C
ERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))
  File "C:\Users\Administrator\Desktop\youtube-dl2.py\youtube_dl\extractor\commo
n.py", line 330, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\Administrator\Desktop\youtube-dl2.py\youtube_dl\YoutubeDL.py",
line 1886, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Python27\lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 449, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Users\Administrator\Desktop\youtube-dl2.py\youtube_dl\utils.py", line
 815, in https_open
    req, **kwargs)
  File "C:\Python27\lib\urllib2.py", line 1197, in do_open
    raise URLError(err)
```

**Comment by dstftw** [comment] 2015-12-31 18:56
Post the output of this command plus `--dump-pages` option.

**Comment by wwwamroth** [comment] 2015-12-31 19:05
```ruby
C:\Users\Administrator\Desktop>youtube-dl2.py -v --dump-pages --print-traffic co
nfig.playwire.com/12342/videos/v2/4447676/zeus.json
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--dump-pages', u'--print-traffic', u'config
.playwire.com/12342/videos/v2/4447676/zeus.json']
[debug] Encodings: locale cp1254, fs mbcs, out cp857, pref cp1254
[debug] youtube-dl version 2015.12.31
[debug] Python version 2.7.11rc1 - Windows-2008Server-6.0.6001-SP1
[debug] exe versions: none
[debug] Proxy map: {}
WARNING: The url doesn't specify the protocol, trying with http
[Playwire] 4447676: Downloading JSON metadata
send: u'GET /12342/videos/v2/4447676/zeus.json HTTP/1.1\r\nHost: config.playwire
.com\r\nAccept-Language: en-us,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\nAcc
ept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nUser-Age
nt: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome
)\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nConnection: close\r\n\r\n
'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Thu, 31 Dec 2015 19:00:37 GMT
header: Connection: close
header: Accept-Ranges: bytes
header: ETag: "1451586679"
header: Last-Modified: Thu, 31 Dec 2015 18:31:19 GMT
header: Cache-Control: private, must-revalidate, max-age=0
header: Content-Length: 8100
header: Content-Type: application/json
header: X-HW: 1451588438.dop015.fr7.t,1451588437.cds037.fr7.c
header: Access-Control-Allow-Origin: *
header: Access-Control-Allow-Headers: DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-
Requested-With,If-Modified-Since,Cache-Control,Content-Type,Accept-Encoding
[Playwire] Dumping request to http://config.playwire.com/12342/videos/v2/4447676
/zeus.json
eyJzZXR0aW5ncyI6eyJ0aXRsZSI6IkthYWxhIFBhaXNhIFB5YXIgRXBpc29kZSAxMDggaW4gSEQiLCJh
dXRvcGxheSI6ZmFsc2UsImJyYW5kaW5nIjp0cnVlLCJza2luIjoiIiwic2hhcmUiOnRydWUsImF1dG9t
dXRlIjpmYWxzZSwibG9vcCI6ZmFsc2UsImRlZmF1bHRIRCI6ZmFsc2UsInNob3dFbWJlZCI6dHJ1ZSwi
YmlnQnV0dG9uIjpmYWxzZSwiYXBwZWFyYW5jZSI6eyJjb2xvcnMiOnsiYmFja2dyb3VuZCI6bnVsbCwi
Zm9yZWdyb3VuZCI6bnVsbCwiYWN0aXZlIjpudWxsfSwid2F0ZXJtYXJrIjp7InBvc2l0aW9uIjpudWxs
LCJvcGFjaXR5IjpudWxsfX19LCJ0eXBlIjoidmlkZW8iLCJ2ZXJzaW9uIjoyLCJkdXJhdGlvbiI6MjM1
NDc2MCwicHVibGlzaGVySWQiOjEyMzQyLCJob3N0aW5nSWQiOjEyMzQyLCJyZWxhdGVkIjoiaHR0cHM6
Ly9jb25maWcucGxheXdpcmUuY29tLzEyMzQyL3JlbGF0ZWRfdmlkZW9zL3YyLzQ0NDc2NzYvemV1cy5q
c29uIiwiY29udGVudCI6eyJ2aWRlb0lkIjo0NDQ3Njc2LCJwb3N0ZXIiOiJodHRwczovL2Nkbi52aWRl
by5wbGF5d2lyZS5jb20vMTIzNDIvdmlkZW9zLzQ0NDc2NzYvcG9zdGVyXzAwMDAucG5nIiwibWVkaWEi
OnsiZjRtIjoiaHR0cHM6Ly9jb25maWcucGxheXdpcmUuY29tLzEyMzQyL3ZpZGVvcy92Mi80NDQ3Njc2
L21hbmlmZXN0LmY0bSJ9LCJjYXB0aW9ucyI6W119LCJhZHZlcnRpc2luZyI6eyJ2aWRlb0FkUmF0aW8i
OjEsInRydWVWaWV3IjpmYWxzZSwib24iOnRydWUsInNlcnZlcnMiOlt7InR5cGUiOiJhZHRlY2gtaW50
ZXJnaSIsInRhZ3MiOnsiZGVmYXVsdCI6eyJzdGFuZGFyZCI6eyJwcmVyb2xsIjoiaHR0cDovL2Fkcy5p
bnRlcmdpLmNvbS9hZHJhd2RhdGEvMy4wLzUyMDUvMjY2NjM2NC80NDQ3Njc2LzEwMTMvQURURUNIO2Nv
cnM9eWVzO3dpZHRoPV9fV0lEVEhfXztoZWlnaHQ9X19IRUlHSFRfXztyZWZlcnJpbmdfdXJsPV9fV0VC
X1VSTF9fO2NvbnRlbnRfdXJsPV9fQ09OVEVOVF9VUkxfXzttZWRpYV9pZD1fX01FRElBX0lEX187dGl0
bGU9X19USVRMRV9fO2RldmljZT1fX0RFVklDRV9fO21vZGVsPV9fTU9ERUxfXztvcz1fX09TX187b3N2
ZXJzaW9uPV9fT1NWRVJTSU9OX187dWE9X19VQV9fO2lwPV9fSVBfXzt1bmlxdWVpZDpfX1VOSVFVRUlE
X187dGFncz1fX1RBR1NfXztudW1iZXI9X19SQU5ET01fXzt0aW1lPV9fVElNRV9fO2hlYWRlcmJpZHM9
YW1hem9uIiwibWlkcm9sbCI6Imh0dHA6Ly9hZHMuaW50ZXJnaS5jb20vYWRyYXdkYXRhLzMuMC81MjA1
LzI2NjYzNjQvNDQ0NzY3Ni8xMDEzL0FEVEVDSDtjb3JzPXllczt3aWR0aD1fX1dJRFRIX187aGVpZ2h0
PV9fSEVJR0hUX187cmVmZXJyaW5nX3VybD1fX1dFQl9VUkxfXztjb250ZW50X3VybD1fX0NPTlRFTlRf
VVJMX187bWVkaWFfaWQ9X19NRURJQV9JRF9fO3RpdGxlPV9fVElUTEVfXztkZXZpY2U9X19ERVZJQ0Vf
Xzttb2RlbD1fX01PREVMX187b3M9X19PU19fO29zdmVyc2lvbj1fX09TVkVSU0lPTl9fO3VhPV9fVUFf
XztpcD1fX0lQX187dW5pcXVlaWQ6X19VTklRVUVJRF9fO3RhZ3M9X19UQUdTX187bnVtYmVyPV9fUkFO
RE9NX187dGltZT1fX1RJTUVfXztoZWFkZXJiaWRzPWFtYXpvbiIsInZpZGVvMzAweDI1MCI6Imh0dHA6
Ly9hZHMuaW50ZXJnaS5jb20vYWRkeW4vMy4wLzUyMDUvMzY5OTQ2My80NDQ3Njc2LzE3MC9BRFRFQ0g7
bG9jPTEwMDt0YXJnZXQ9X2JsYW5rO2tleT1rZXkxK2tleTIra2V5MytrZXk0O2dycD1bZ3JvdXBdO21p
c2M9Iiwib3ZlcmxheSI6Imh0dHA6Ly9hZHMuaW50ZXJnaS5jb20vYWRyYXdkYXRhLzMuMC81MjA1LzM2
OTk1MzIvNDQ0NzY3Ni82NzQ0L0FEVEVDSDtjb3JzPXllczt3aWR0aD1fX1dJRFRIX187aGVpZ2h0PV9f
SEVJR0hUX187cmVmZXJyaW5nX3VybD1fX1dFQl9VUkxfXztjb250ZW50X3VybD1fX0NPTlRFTlRfVVJM
X187bWVkaWFfaWQ9X19NRURJQV9JRF9fO3RpdGxlPV9fVElUTEVfXztkZXZpY2U9X19ERVZJQ0VfXztt
b2RlbD1fX01PREVMX187b3M9X19PU19fO29zdmVyc2lvbj1fXyJ9LCJodG1sNSI6eyJkZXNrdG9wIjp7
InByZXJvbGwiOiJodHRwOi8vYWRzLmludGVyZ2kuY29tL2FkcmF3ZGF0YS8zLjAvNTIwNS8yNjY2MzY0
LzQ0NDc2NzYvMTAxMy9BRFRFQ0g7Y29ycz15ZXM7d2lkdGg9X19XSURUSF9fO2hlaWdodD1fX0hFSUdI
VF9fO3JlZmVycmluZ191cmw9X19XRUJfVVJMX187Y29udGVudF91cmw9X19DT05URU5UX1VSTF9fO21l
ZGlhX2lkPV9fTUVESUFfSURfXzt0aXRsZT1fX1RJVExFX187ZGV2aWNlPV9fREVWSUNFX187bW9kZWw9
X19NT0RFTF9fO29zPV9fT1NfXztvc3ZlcnNpb249X19PU1ZFUlNJT05fXzt1YT1fX1VBX187aXA9X19J
UF9fO3VuaXF1ZWlkOl9fVU5JUVVFSURfXzt0YWdzPV9fVEFHU19fO251bWJlcj1fX1JBTkRPTV9fO3Rp
bWU9X19USU1FX187aGVhZGVyYmlkcz1hbWF6b24iLCJtaWRyb2xsIjoiaHR0cDovL2Fkcy5pbnRlcmdp
LmNvbS9hZHJhd2RhdGEvMy4wLzUyMDUvMjY2NjM2NC80NDQ3Njc2LzEwMTMvQURURUNIO2NvcnM9eWVz
O3dpZHRoPV9fV0lEVEhfXztoZWlnaHQ9X19IRUlHSFRfXztyZWZlcnJpbmdfdXJsPV9fV0VCX1VSTF9f
O2NvbnRlbnRfdXJsPV9fQ09OVEVOVF9VUkxfXzttZWRpYV9pZD1fX01FRElBX0lEX187dGl0bGU9X19U
SVRMRV9fO2RldmljZT1fX0RFVklDRV9fO21vZGVsPV9fTU9ERUxfXztvcz1fX09TX187b3N2ZXJzaW9u
PV9fT1NWRVJTSU9OX187dWE9X19VQV9fO2lwPV9fSVBfXzt1bmlxdWVpZDpfX1VOSVFVRUlEX187dGFn
cz1fX1RBR1NfXztudW1iZXI9X19SQU5ET01fXzt0aW1lPV9fVElNRV9fO2hlYWRlcmJpZHM9YW1hem9u
IiwidmlkZW8zMDB4MjUwIjoiaHR0cDovL2Fkcy5pbnRlcmdpLmNvbS9hZGR5bi8zLjAvNTIwNS8zNjk5
NDYzLzQ0NDc2NzYvMTcwL0FEVEVDSDtsb2M9MTAwO3RhcmdldD1fYmxhbms7a2V5PWtleTEra2V5Mitr
ZXkzK2tleTQ7Z3JwPVtncm91cF07bWlzYz0iLCJvdmVybGF5IjoiaHR0cDovL2Fkcy5pbnRlcmdpLmNv
bS9hZHJhd2RhdGEvMy4wLzUyMDUvMzY5OTUzMi80NDQ3Njc2LzY3NDQvQURURUNIO2NvcnM9eWVzO3dp
ZHRoPV9fV0lEVEhfXztoZWlnaHQ9X19IRUlHSFRfXztyZWZlcnJpbmdfdXJsPV9fV0VCX1VSTF9fO2Nv
bnRlbnRfdXJsPV9fQ09OVEVOVF9VUkxfXzttZWRpYV9pZD1fX01FRElBX0lEX187dGl0bGU9X19USVRM
RV9fO2RldmljZT1fX0RFVklDRV9fO21vZGVsPV9fTU9ERUxfXztvcz1fX09TX187b3N2ZXJzaW9uPV9f
In0sIm1vYmlsZSI6eyJwcmVyb2xsIjoiaHR0cDovL2Fkcy5pbnRlcmdpLmNvbS9hZHJhd2RhdGEvMy4w
LzUyMDUvMzMzMTY1NS80NDQ3Njc2LzQ3OTYvQURURUNIO2NvcnM9eWVzO3dpZHRoPV9fV0lEVEhfXzto
ZWlnaHQ9X19IRUlHSFRfXztyZWZlcnJpbmdfdXJsPV9fV0VCX1VSTF9fO2NvbnRlbnRfdXJsPV9fQ09O
VEVOVF9VUkxfXzttZWRpYV9pZD1fX01FRElBX0lEX187dGl0bGU9X19USVRMRV9fO2RldmljZT1fX0RF
VklDRV9fO21vZGVsPV9fTU9ERUxfXztvcz1fX09TX187b3N2ZXJzaW9uPV9fT1NWRVJTSU9OX187dWE9
X19VQV9fO2lwPV9fSVBfXzt1bmlxdWVpZDpfX1VOSVFVRUlEX187dGFncz1fX1RBR1NfXztudW1iZXI9
X19SQU5ET01fXzt0aW1lPV9fVElNRV9fIiwibWlkcm9sbCI6Imh0dHA6Ly9hZHMuaW50ZXJnaS5jb20v
YWRyYXdkYXRhLzMuMC81MjA1LzMzMzE2NTUvNDQ0NzY3Ni80Nzk2L0FEVEVDSDtjb3JzPXllczt3aWR0
aD1fX1dJRFRIX187aGVpZ2h0PV9fSEVJR0hUX187cmVmZXJyaW5nX3VybD1fX1dFQl9VUkxfXztjb250
ZW50X3VybD1fX0NPTlRFTlRfVVJMX187bWVkaWFfaWQ9X19NRURJQV9JRF9fO3RpdGxlPV9fVElUTEVf
XztkZXZpY2U9X19ERVZJQ0VfXzttb2RlbD1fX01PREVMX187b3M9X19PU19fO29zdmVyc2lvbj1fX09T
VkVSU0lPTl9fO3VhPV9fVUFfXztpcD1fX0lQX187dW5pcXVlaWQ6X19VTklRVUVJRF9fO3RhZ3M9X19U
QUdTX187bnVtYmVyPV9fUkFORE9NX187dGltZT1fX1RJTUVfXyIsInZpZGVvMzAweDI1MCI6Imh0dHA6
Ly9hZHMuaW50ZXJnaS5jb20vYWRkeW4vMy4wLzUyMDUvMzY5OTQ2My80NDQ3Njc2LzE3MC9BRFRFQ0g7
bG9jPTEwMDt0YXJnZXQ9X2JsYW5rO2tleT1rZXkxK2tleTIra2V5MytrZXk0O2dycD1bZ3JvdXBdO21p
c2M9Iiwib3ZlcmxheSI6Imh0dHA6Ly9hZHMuaW50ZXJnaS5jb20vYWRyYXdkYXRhLzMuMC81MjA1LzM2
OTk1OTYvNDQ0NzY3Ni82NzQ0L0FEVEVDSDtjb3JzPXllczt3aWR0aD1fX1dJRFRIX187aGVpZ2h0PV9f
SEVJR0hUX187cmVmZXJyaW5nX3VybD1fX1dFQl9VUkxfXztjb250ZW50X3VybD1fX0NPTlRFTlRfVVJM
X187bWVkaWFfaWQ9X19NRURJQV9JRF9fO3RpdGxlPV9fVElUTEVfXztkZXZpY2U9X19ERVZJQ0VfXztt
b2RlbD1fX01PREVMX187b3M9X19PU19fO29zdmVyc2lvbj1fXyJ9fX0sImRyYW1hc29ubGluZS5jb20i
Onsic3RhbmRhcmQiOnsicHJlcm9sbCI6Imh0dHA6Ly9hZHMuaW50ZXJnaS5jb20vYWRyYXdkYXRhLzMu
MC81MjA1LzI2NjYzNjQvNDQ0NzY3Ni8xMDEzL0FEVEVDSDtjb3JzPXllczt3aWR0aD1fX1dJRFRIX187
aGVpZ2h0PV9fSEVJR0hUX187cmVmZXJyaW5nX3VybD1fX1dFQl9VUkxfXztjb250ZW50X3VybD1fX0NP
TlRFTlRfVVJMX187bWVkaWFfaWQ9X19NRURJQV9JRF9fO3RpdGxlPV9fVElUTEVfXztkZXZpY2U9X19E
RVZJQ0VfXzttb2RlbD1fX01PREVMX187b3M9X19PU19fO29zdmVyc2lvbj1fX09TVkVSU0lPTl9fO3Vh
PV9fVUFfXztpcD1fX0lQX187dW5pcXVlaWQ6X19VTklRVUVJRF9fO3RhZ3M9X19UQUdTX187bnVtYmVy
PV9fUkFORE9NX187dGltZT1fX1RJTUVfXztoZWFkZXJiaWRzPWFtYXpvbiIsIm1pZHJvbGwiOiJodHRw
Oi8vYWRzLmludGVyZ2kuY29tL2FkcmF3ZGF0YS8zLjAvNTIwNS8yNjY2MzY0LzQ0NDc2NzYvMTAxMy9B
RFRFQ0g7Y29ycz15ZXM7d2lkdGg9X19XSURUSF9fO2hlaWdodD1fX0hFSUdIVF9fO3JlZmVycmluZ191
cmw9X19XRUJfVVJMX187Y29udGVudF91cmw9X19DT05URU5UX1VSTF9fO21lZGlhX2lkPV9fTUVESUFf
SURfXzt0aXRsZT1fX1RJVExFX187ZGV2aWNlPV9fREVWSUNFX187bW9kZWw9X19NT0RFTF9fO29zPV9f
T1NfXztvc3ZlcnNpb249X19PU1ZFUlNJT05fXzt1YT1fX1VBX187aXA9X19JUF9fO3VuaXF1ZWlkOl9f
VU5JUVVFSURfXzt0YWdzPV9fVEFHU19fO251bWJlcj1fX1JBTkRPTV9fO3RpbWU9X19USU1FX187aGVh
ZGVyYmlkcz1hbWF6b24iLCJ2aWRlbzMwMHgyNTAiOiJodHRwOi8vYWRzLmludGVyZ2kuY29tL2FkZHlu
LzMuMC81MjA1LzM2OTk3NTUvNDQ0NzY3Ni8xNzAvQURURUNIO2xvYz0xMDA7dGFyZ2V0PV9ibGFuaztr
ZXk9a2V5MStrZXkyK2tleTMra2V5NDtncnA9W2dyb3VwXTttaXNjPSIsIm92ZXJsYXkiOiJodHRwOi8v
YWRzLmludGVyZ2kuY29tL2FkcmF3ZGF0YS8zLjAvNTIwNS8zNjk5ODY1LzQ0NDc2NzYvNjc0NC9BRFRF
Q0g7Y29ycz15ZXM7d2lkdGg9X19XSURUSF9fO2hlaWdodD1fX0hFSUdIVF9fO3JlZmVycmluZ191cmw9
X19XRUJfVVJMX187Y29udGVudF91cmw9X19DT05URU5UX1VSTF9fO21lZGlhX2lkPV9fTUVESUFfSURf
Xzt0aXRsZT1fX1RJVExFX187ZGV2aWNlPV9fREVWSUNFX187bW9kZWw9X19NT0RFTF9fO29zPV9fT1Nf
Xztvc3ZlcnNpb249X18ifSwiaHRtbDUiOnsiZGVza3RvcCI6eyJwcmVyb2xsIjoiaHR0cDovL2Fkcy5p
bnRlcmdpLmNvbS9hZHJhd2RhdGEvMy4wLzUyMDUvMjY2NjM2NC80NDQ3Njc2LzEwMTMvQURURUNIO2Nv
cnM9eWVzO3dpZHRoPV9fV0lEVEhfXztoZWlnaHQ9X19IRUlHSFRfXztyZWZlcnJpbmdfdXJsPV9fV0VC
X1VSTF9fO2NvbnRlbnRfdXJsPV9fQ09OVEVOVF9VUkxfXzttZWRpYV9pZD1fX01FRElBX0lEX187dGl0
bGU9X19USVRMRV9fO2RldmljZT1fX0RFVklDRV9fO21vZGVsPV9fTU9ERUxfXztvcz1fX09TX187b3N2
ZXJzaW9uPV9fT1NWRVJTSU9OX187dWE9X19VQV9fO2lwPV9fSVBfXzt1bmlxdWVpZDpfX1VOSVFVRUlE
X187dGFncz1fX1RBR1NfXztudW1iZXI9X19SQU5ET01fXzt0aW1lPV9fVElNRV9fO2hlYWRlcmJpZHM9
YW1hem9uIiwibWlkcm9sbCI6Imh0dHA6Ly9hZHMuaW50ZXJnaS5jb20vYWRyYXdkYXRhLzMuMC81MjA1
LzI2NjYzNjQvNDQ0NzY3Ni8xMDEzL0FEVEVDSDtjb3JzPXllczt3aWR0aD1fX1dJRFRIX187aGVpZ2h0
PV9fSEVJR0hUX187cmVmZXJyaW5nX3VybD1fX1dFQl9VUkxfXztjb250ZW50X3VybD1fX0NPTlRFTlRf
VVJMX187bWVkaWFfaWQ9X19NRURJQV9JRF9fO3RpdGxlPV9fVElUTEVfXztkZXZpY2U9X19ERVZJQ0Vf
Xzttb2RlbD1fX01PREVMX187b3M9X19PU19fO29zdmVyc2lvbj1fX09TVkVSU0lPTl9fO3VhPV9fVUFf
XztpcD1fX0lQX187dW5pcXVlaWQ6X19VTklRVUVJRF9fO3RhZ3M9X19UQUdTX187bnVtYmVyPV9fUkFO
RE9NX187dGltZT1fX1RJTUVfXztoZWFkZXJiaWRzPWFtYXpvbiIsInZpZGVvMzAweDI1MCI6Imh0dHA6
Ly9hZHMuaW50ZXJnaS5jb20vYWRkeW4vMy4wLzUyMDUvMzY5OTc1NS80NDQ3Njc2LzE3MC9BRFRFQ0g7
bG9jPTEwMDt0YXJnZXQ9X2JsYW5rO2tleT1rZXkxK2tleTIra2V5MytrZXk0O2dycD1bZ3JvdXBdO21p
c2M9Iiwib3ZlcmxheSI6Imh0dHA6Ly9hZHMuaW50ZXJnaS5jb20vYWRyYXdkYXRhLzMuMC81MjA1LzM2
OTk4NjUvNDQ0NzY3Ni82NzQ0L0FEVEVDSDtjb3JzPXllczt3aWR0aD1fX1dJRFRIX187aGVpZ2h0PV9f
SEVJR0hUX187cmVmZXJyaW5nX3VybD1fX1dFQl9VUkxfXztjb250ZW50X3VybD1fX0NPTlRFTlRfVVJM
X187bWVkaWFfaWQ9X19NRURJQV9JRF9fO3RpdGxlPV9fVElUTEVfXztkZXZpY2U9X19ERVZJQ0VfXztt
b2RlbD1fX01PREVMX187b3M9X19PU19fO29zdmVyc2lvbj1fXyJ9LCJtb2JpbGUiOnsicHJlcm9sbCI6
Imh0dHA6Ly9hZHMuaW50ZXJnaS5jb20vYWRyYXdkYXRhLzMuMC81MjA1LzMzMzE2NTUvNDQ0NzY3Ni80
Nzk2L0FEVEVDSDtjb3JzPXllczt3aWR0aD1fX1dJRFRIX187aGVpZ2h0PV9fSEVJR0hUX187cmVmZXJy
aW5nX3VybD1fX1dFQl9VUkxfXztjb250ZW50X3VybD1fX0NPTlRFTlRfVVJMX187bWVkaWFfaWQ9X19N
RURJQV9JRF9fO3RpdGxlPV9fVElUTEVfXztkZXZpY2U9X19ERVZJQ0VfXzttb2RlbD1fX01PREVMX187
b3M9X19PU19fO29zdmVyc2lvbj1fX09TVkVSU0lPTl9fO3VhPV9fVUFfXztpcD1fX0lQX187dW5pcXVl
aWQ6X19VTklRVUVJRF9fO3RhZ3M9X19UQUdTX187bnVtYmVyPV9fUkFORE9NX187dGltZT1fX1RJTUVf
XyIsIm1pZHJvbGwiOiJodHRwOi8vYWRzLmludGVyZ2kuY29tL2FkcmF3ZGF0YS8zLjAvNTIwNS8zMzMx
NjU1LzQ0NDc2NzYvNDc5Ni9BRFRFQ0g7Y29ycz15ZXM7d2lkdGg9X19XSURUSF9fO2hlaWdodD1fX0hF
SUdIVF9fO3JlZmVycmluZ191cmw9X19XRUJfVVJMX187Y29udGVudF91cmw9X19DT05URU5UX1VSTF9f
O21lZGlhX2lkPV9fTUVESUFfSURfXzt0aXRsZT1fX1RJVExFX187ZGV2aWNlPV9fREVWSUNFX187bW9k
ZWw9X19NT0RFTF9fO29zPV9fT1NfXztvc3ZlcnNpb249X19PU1ZFUlNJT05fXzt1YT1fX1VBX187aXA9
X19JUF9fO3VuaXF1ZWlkOl9fVU5JUVVFSURfXzt0YWdzPV9fVEFHU19fO251bWJlcj1fX1JBTkRPTV9f
O3RpbWU9X19USU1FX18iLCJ2aWRlbzMwMHgyNTAiOiJodHRwOi8vYWRzLmludGVyZ2kuY29tL2FkZHlu
LzMuMC81MjA1LzM2OTk3NTUvNDQ0NzY3Ni8xNzAvQURURUNIO2xvYz0xMDA7dGFyZ2V0PV9ibGFuaztr
ZXk9a2V5MStrZXkyK2tleTMra2V5NDtncnA9W2dyb3VwXTttaXNjPSIsIm92ZXJsYXkiOiJodHRwOi8v
YWRzLmludGVyZ2kuY29tL2FkcmF3ZGF0YS8zLjAvNTIwNS8zNzAwMDA0LzQ0NDc2NzYvNjc0NC9BRFRF
Q0g7Y29ycz15ZXM7d2lkdGg9X19XSURUSF9fO2hlaWdodD1fX0hFSUdIVF9fO3JlZmVycmluZ191cmw9
X19XRUJfVVJMX187Y29udGVudF91cmw9X19DT05URU5UX1VSTF9fO21lZGlhX2lkPV9fTUVESUFfSURf
Xzt0aXRsZT1fX1RJVExFX187ZGV2aWNlPV9fREVWSUNFX187bW9kZWw9X19NT0RFTF9fO29zPV9fT1Nf
Xztvc3ZlcnNpb249X18ifX19fX1dLCJjdWVwb2ludHMiOls0MjAsODQwLDEyNjAsMTY4MCwyMTAwXX19

[Playwire] 4447676: Downloading XML
ERROR: Unable to download XML: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] c
ertificate verify failed (_ssl.c:590)> (caused by URLError(SSLError(1, u'[SSL: C
ERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))
  File "C:\Users\Administrator\Desktop\youtube-dl2.py\youtube_dl\extractor\commo
n.py", line 330, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\Administrator\Desktop\youtube-dl2.py\youtube_dl\YoutubeDL.py",
line 1886, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Python27\lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 449, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Users\Administrator\Desktop\youtube-dl2.py\youtube_dl\utils.py", line
 815, in https_open
    req, **kwargs)
  File "C:\Python27\lib\urllib2.py", line 1197, in do_open
    raise URLError(err)
```

**Comment by dstftw** [comment] 2016-03-26 23:00
Duplicate of #7309.

**Closed by dstftw** 2016-03-26 23:00 UTC
