### ISSUE TITLE
Downloading videos from Lynda.com with Organization Login [SOLVED]

### ISSUE THREAD

**Issue by DevKiddo** [rg3/youtube-dl#5926] opened 2015-06-08 09:54 UTC
Hello!

I am writing to present my solution to this problem which has appeared previously in issue #4888 and issue #5636 . It is quite easy and just requires a tiny bit of manual labor. I have searched the internet for other tools that could download videos from Lynda when having an organization account and youtube-dl seems to be the only one that's able to do the job. 

A partial solution was presented in issue #4888 which talked about importing cookies in order to bypass authentication -  This works. But you must be careful with the exact format of the cookie file you are importing from your browser. I tried a few extensions in Chrome and Firefox before I was able to succeed and the only one that worked well was a Firefox add-on named "Cookie Exporter 1.5.1-signed" by fliwatüt.  Python does not only expect you to import a cookie.txt in a Netscape format but it also expects the cookie.txt to have a specific structure, so you will have to add a first line at the very top of the exported file being  "# Netscape HTTP Cookie File" (without the quotes). If you don't add this line at the very top of the cookie.txt file, Python won't read your file, even if it actually is in a Netscape format. Note that before exporting the cookie.txt file from your browser, you must log into your Lynda organization account. 

Good. Once that's done you just have to run "youtube-dl --cookies cookies.txt link-to-the-video" and it will download any video you want, but only ONE video - that is, youtube-dl won't collect all the Lynda videos in the course. Downloading say 150 videos from a course manually one by one can be a real pain, so I wrote a small script to automate this process:

*EDIT: removed in order not to confuse, youtube-dl works fine with courses.*

This script will do 3 things. First it will scrape all the links from a specific Lynda tutorial that you want to have, in this case the placeholder is "http://www.lynda.com/MySQL-tutorials/PHP-MySQL-Essential-Training/119003-2.html".  Second, it will parse out only those links which have a key URL that all the videos share in common. In this case, the placeholder is 'http://www.lynda.com/MySQL-tutorials/'. This is extremely important; you need to put the key URL that all the videos share in common because there are many more links in the page and you don't want youtube-dl returning a bunch of invalid URL errors. Finally, after it parses all the links from the actual tutorial videos, it runs "youtube-dl --cookies cookies.txt" for every link that it found. There it is! Youtube-dl will collect all the videos and download them automatically. Remember you'll need to install BeautifulSoup library before you run the script!

A final couple of tips: 

- Remember to export the cookie.txt file every time you download another tutorial because if you don't it will tell you that your Lynda session has expired.
- When downloading all the videos, everything will be disorganized and messy in your directory, but if you simply sort your files by date created, every video will be sorted in the correct order.

Thank you for this awesome library!

**Comment by dstftw** [comment] 2015-06-08 15:19
youtube-dl should download courses just fine. Could you run it with `--verbose --write-pages` on a course URL and post the output along with *.dump files?

**Comment by DevKiddo** [comment] 2015-06-08 18:10
Sure thing. I'll do it tomorrow as soon as I get back to my laptop. When you say "youtube-dl should download courses just fine" you mean that it should be collecting all the videos and not just one video when importing cookies right?

**Comment by dstftw** [comment] 2015-06-08 18:12
Yes, since it's [supported](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/lynda.py#L187-L235).

**Comment by pranavkaranjkar** [comment] 2015-06-24 12:23
@DevKiddo I am trying to use the script that you provided and I get following error. Terminal output with -v is included.

sudo python exposure.py 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--cookies', u'cookies.txt', u'http://www.lynda.com/Digital-Photography-tutorials/foundations-of-photography-exposure/71923-2.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.15
[debug] Python version 2.7.6 - Linux-3.16.0-41-generic-x86_64-with-elementary_OS-0.3-freya
[debug] exe versions: ffmpeg 2.7, ffprobe 2.7
[debug] Proxy map: {}
[lynda:course] 71923: Downloading course JSON
ERROR: Unable to download webpage: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 312, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1730, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)


Can you help figuring out whats going wrong?

Thanks

**Comment by pranavkaranjkar** [comment] 2015-06-24 22:21
@dstftw I did try youtube-dl directly with a coursepage but it only downloads a few videos (throughout all the chapters) from a course.

**Comment by AV12111994** [comment] 2015-07-11 16:47
I'm getting the following error on doing everything that you said (before your python script) (I'm trying this for an individual lynda link)

>[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-u', '<PRIVATE>', '--cookies', 'Desktop/cookies.txt', '--verbose', 'http://www.lynda.com/Ubuntu-tutorials/Introducing-Ubuntu/159637/179555-4.html']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
Type account password and press return:
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-3.13.0-57-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] Proxy map: {'ftp': 'ftp://172.16.15.32:2193', 'http': 'http://172.16.15.32:2193', 'https': 'https://172.16.15.32:2193'}
[lynda] Logging in as aver39@sapient.com
ERROR: Unable to download webpage: <urlopen error [Errno 110] Connection timed out>
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 191, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1157, in urlopen
    return self._opener.open(req)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/utils.py", line 572, in https_open
    return self.do_open(HTTPSConnectionV3, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)

**Comment by DevKiddo** [comment] 2015-07-11 17:34
Hi @pranavkaranjkar and @AV12111994,

I've been super busy lately and I'm not sure if I'll have the time to debug your error logs. If this helps, very recently I realized that the lynda iPhone app lets you download all videos of a course to your smartphone, regardless of your account type. It may be just a lot easier to do that and then jailbreak into your phone with software like PhoneBrowse in order to import the downloaded videos into your computer.

Hope this helps!

**Comment by AV12111994** [comment] 2015-07-11 17:44
@DevKiddo I had done that on android meanwhile, is solving the purpose, but I want to work it out on my computer too. I can wait.

**Comment by dstftw** [comment] 2015-07-11 17:47
@AV12111994 does your proxy alive at all? Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by AV12111994** [comment] 2015-07-11 18:41
@dstftw http, https proxies were set and I wasn't using any proxy network, so I removed them from .bashrc file. After that I updated the youtube-dl version. By doing this I was able to download the videos from youtube, but on doing 

`youtube-dl --write-pages --cookies Desktop/cookies.txt --verbose http://www.lynda.com/WordPress-tutorials/Downloading-correct-version-BitNami/114908/122081-4.html`

I'm getting this error log: 

>[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--write-pages', u'--cookies', u'Desktop/cookies.txt', u'--verbose', u'http://www.lynda.com/WordPress-tutorials/Downloading-correct-version-BitNami/114908/122081-4.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.07
[debug] Python version 2.7.6 - Linux-3.13.0-57-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, rtmpdump 2.4
[debug] Proxy map: {}
[lynda] 122081: Downloading video JSON
ERROR: Unable to download webpage: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 312, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1729, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by manrodriguezf** [comment] 2015-07-24 17:32
Actually I made an httpclient to do that automatically (in Java), just provide a valid cookie and output format. PM me for info guys.

**Comment by AV12111994** [comment] 2015-08-01 17:56
@manrodriguezf Could you tell what's wrong with my error that I put up above?

**Comment by AV12111994** [comment] 2015-08-01 19:15
@DevKiddo I've got mad trying to work it out, if you could help...

**Comment by DevKiddo** [comment] 2015-08-02 07:25
@AV12111994 what's your OS?

**Comment by AV12111994** [comment] 2015-08-02 07:44
@DevKiddo Ubuntu. I also put ` --verbose --print-traffic --dump-pages ` output and cookie structure here : 
https://github.com/rg3/youtube-dl/issues/6429#issuecomment-126948054

**Comment by IgorGee** [comment] 2015-09-16 03:56
Thank you so much for this solution. This seems to be a common problem with people who use institutional log ins.

**Comment by aureliaandrewsb** [comment] 2015-10-16 01:42
After long google search and practice and comparison, finally I find Allavsoft works well in downloading videos from Lynda.com with Organization Login.

Here is the step by step guide at http://www.allavsoft.com/how-to/lynda-video-downloader.html

**Comment by travman34** [comment] 2015-10-30 05:40
Thanks for the info, saved tons of time versus downloading 1 video at a time. On my windows machine running "youtube-dl --cookies cookies.txt link-to-the-video" would download the entire list after importing cookies from firefox, but wasn't working on my debian machine. So thanks again!

**Comment by gdad-s-river** [comment] 2015-10-30 06:20
After the help from this issue, I wrote the following tutorials for someone who'd want to work it out on linux(and hence hopefully mac) or windows.

Hope this helps to new people trying it out :
 
http://fossbytes.com/how-to-download-lynda-com-videos-using-youtube-dl/
http://fossbytes.com/how-to-download-lynda-com-courses-on-windows/

**Comment by dstftw** [comment] 2015-10-30 14:23
@gdad-s-river you don't need this wrapper, youtube-dl works fine with courses out of the box.
Closing since cookies usage is now documented [in FAQ](https://github.com/rg3/youtube-dl#how-do-i-pass-cookies-to-youtube-dl).

**Closed by dstftw** 2015-10-30 14:23 UTC

**Comment by gdad-s-river** [comment] 2015-10-30 14:30
@dstftw , I couldn't understand what wrapper is, that you are talking about... could you explain?

**Comment by dstftw** [comment] 2015-10-30 14:33
I'm about python code in your tutorial. youtube-dl works fine with course URLs directly.

**Comment by gdad-s-river** [comment] 2015-10-30 18:56
Oh, didn't know that! Good to know.

**Comment by freefulltime** [comment] 2016-01-21 09:05
You can Step by Step Guide for the best Lynda downloader at http://www.avdshare.com/lynda-downloader

**Comment by freefulltime** [comment] 2016-01-21 12:32
You may use Avdshare video downloader to download ynda and also capable of downloading videos from Udemy, VEVO, YouTube, NBC, HGTV, Crackle, VideoWeed, 9Jumpin, Facebook, CBS, etc.

**Comment by bestautumnn** [comment] 2016-01-27 08:28
Many of my friends recommend me to use Allavsoft to download videos from Lynda.com, Udemy.com

Today I just have a try, and find it really works great as soon as you have the Organization Login 

You may get it here http://www.allavsoft.com/how-to/lynda-video-downloader.html

**Comment by henryjackylucky** [comment] 2016-06-27 09:20
I just find a method to easily download lynda videos from http://www.allavsoft.com/how-to/lynda-video-downloader.html

After have a try, it does works great. and it aslo works for udemy

**Comment by yan12125** [comment] 2016-06-27 09:25
@henryjackylucky allavsoft is completely unrelated to youtube-dl. Please refrain from proposing other softwares here, unless it provides some clues to improve youtube-dl.

**Comment by dstftw** [comment] 2016-06-27 09:26
@yan12125 it's just a spammer.
