### ISSUE TITLE
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()

### ISSUE THREAD

**Issue by ggkr** [rg3/youtube-dl#18160] opened 2018-11-12 11:46 UTC
trying to download a few courses from PluralSight. everything worked fine yesterday when all of the sudden it stopped working. the issue occurs both in version 2018.10.29 and 2018.11.07.

help would be much appreciated.
```
CMD> .\youtube-dl.exe --verbose --username #### --password #### https://app.pluralsight.com/library/courses/tfs-2015/table-of-contents -o "D:\Guides And Tutorials\IT\Pluralsight\%(playlist)s/%(chapter_number)02d - %(chapter)s/
%(playlist_index)02d - %(title)s.%(ext)s" --sleep-interval 35 --max-sleep-interval 120 --sub-lang en --sub-format srt --write-sub

[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://app.pluralsight.com/libr
ary/courses/tfs-2015/table-of-contents', '-o', 'D:\\Guides And Tutorials\\IT\\Pluralsight\\%(playlist)s/%(chapter_number)02d
 - %(chapter)s/%(playlist_index)02d - %(title)s.%(ext)s', '--sleep-interval', '35', '--max-sleep-interval', '120', '--sub-la
ng', 'en', '--sub-format', 'srt', '--write-sub']
[debug] Encodings: locale cp1255, fs mbcs, out cp1255, pref cp1255
[debug] youtube-dl version 2018.11.07
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] tfs-2015: Downloading JSON metadata
[pluralsight:course] tfs-2015: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl w
ith the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj6iiia1g\build\youtube_dl\extractor\common.py", line 60
5, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj6iiia1g\build\youtube_dl\YoutubeDL.py", line 2211, in 
urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

```

**Comment by remitamine** [comment] 2018-11-12 15:08
Duplicate of #14288.

**Closed by remitamine** 2018-11-12 15:08 UTC
