### ISSUE TITLE
[Support request] https://www.zdf.de/migration/migration/das-handy-die-mobile-revolution-der-welt-102.html

### ISSUE THREAD

**Issue by Wikinaut** [rg3/youtube-dl#11318] opened 2016-11-29 14:18 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.27*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.27**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
yt -v https://www.zdf.de/migration/migration/das-handy-die-mobile-revolution-der-welt-102.html
[debug] System config: []
[debug] User config: [u'-f', u'best', u'-o', u'~/Videos/youtube-dl/%(title)s-%(id)s.%(ext)s', u'--user-agent', u'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:21.0) Gecko/20100101 Firefox/38.0']
[debug] Command-line args: [u'-v', u'https://www.zdf.de/migration/migration/das-handy-die-mobile-revolution-der-welt-102.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.27
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.6
[debug] exe versions: avconv 11.8-6, avprobe 11.8-6
[debug] Proxy map: {}
[generic] das-handy-die-mobile-revolution-der-welt-102: Requesting header
WARNING: Falling back on generic information extractor.
[generic] das-handy-die-mobile-revolution-der-welt-102: Downloading webpage
[generic] das-handy-die-mobile-revolution-der-welt-102: Extracting information
ERROR: Unsupported URL: https://www.zdf.de/migration/migration/das-handy-die-mobile-revolution-der-welt-102.html
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1637, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2526, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2515, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 146, column 162
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2449, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.zdf.de/migration/migration/das-handy-die-mobile-revolution-der-welt-102.html
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):

* https://www.zdf.de/migration/migration/das-handy-die-mobile-revolution-der-welt-102.html

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by dstftw** [comment] 2016-11-29 14:55
Duplicate of #11055.

**Closed by dstftw** 2016-11-29 14:55 UTC
