### ISSUE TITLE
ERROR: unable to extract uploader nickname

### ISSUE THREAD

**Issue by Albretch** [rg3/youtube-dl#200] opened 2011-10-22 08:11 UTC
~ 
$ ./youtube-dl -t --audio-format best "http://www.youtube.com/watch?v=jyOgZ8tXZV4"
[youtube] Setting language
[youtube] jyOgZ8tXZV4: Downloading video webpage
[youtube] jyOgZ8tXZV4: Downloading video info webpage
[youtube] jyOgZ8tXZV4: Extracting video information
ERROR: unable to extract uploader nickname

$ ./youtube-dl --version
2011.10.19

$ python --version
Python 2.5.4

$ uname -a
Linux Microknoppix 2.6.31.6 #4 SMP PREEMPT Tue Nov 10 19:11:11 CET 2009 i686 GNU/Linux

**Comment by danielpclark** [comment] 2015-07-25 20:19
I'm also getting this error for 

    youtube-dl -g UoSDLBPrx8A

**Comment by dstftw** [comment] 2015-07-25 20:25
@danielpclark rental videos are not supported.

**Comment by danielpclark** [comment] 2015-07-25 20:28
@dstftw Good.  I wasn't hoping it would be.  But the error is reproducible and should be an easy fix as a nickname is an easy thing to extract.  So this is useful for resolving the issue.

**Comment by dstftw** [comment] 2015-07-25 20:31
@danielpclark not reproducible for me. Coud you post *.dump files created when run youtube-dl with `--write-pages`?

**Comment by danielpclark** [comment] 2015-07-25 20:41
The error seems to only be produced on my Raspbian distro on my Raspberry Pi.  Both `--dump-pages` and `--write-pages` are invalid command line options for it.

    youtube-dl --version
    2012.02.27

I tried to reproduce this on my Ubuntu box but it isn't reproducible there.

    youtube-dl --version
    2014.02.17

**Comment by dstftw** [comment] 2015-07-25 20:47
Both extremely outdated, update to latest, try again and open a new issue if you can reproduce.
I'm closing this since none of mentioned videos are either available with US IP or reproduce the error.

**Closed by dstftw** 2015-07-25 20:47 UTC

**Comment by radu-marinescu** [comment] 2019-08-02 20:46
I do get the same error. In the output I do see a _gl=US, even though I added --geo-bypass-country ro. Here is the output:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--yes-playlist', '--extract-audio', '--audio-format', 'mp3', '--geo-bypass-country', 'ro', '--verbose', '--write-pages', 'https://www.youtube.com/playlist?list=PLnDI9sNsyhtqX-FkqpV1qpmzpjVLM3Uuy']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.14
[debug] Python version 3.6.8 (CPython) - Linux-4.15.0-54-generic-x86_64-with-LinuxMint-19-tara
[debug] exe versions: phantomjs 5
[debug] Proxy map: {}
[debug] Using fake IP 79.113.124.174 (RO) as X-Forwarded-For.
[youtube:playlist] PLnDI9sNsyhtqX-FkqpV1qpmzpjVLM3Uuy: Downloading webpage
[youtube:playlist] Saving request to PLnDI9sNsyhtqX-FkqpV1qpmzpjVLM3Uuy_https_-_www.youtube.com_playlistlist=PLnDI9sNsyhtqX-FkqpV1qpmzpjVLM3Uuy_disable_polymer=true.dump
[download] Downloading playlist: Muzica Populara Noua
[youtube:playlist] playlist Muzica Populara Noua: Downloading 55 videos
[download] Downloading video 1 of 55
[debug] Using fake IP 79.115.28.105 (RO) as X-Forwarded-For.
[youtube] iMwyj_Q_1xg: Downloading webpage
[youtube] Saving request to iMwyj_Q_1xg_https_-_www.youtube.com_watchv=iMwyj_Q_1xg_gl=US_hl=en_has_verified=1_bpctr=9999999999_disable_polymer=true.dump
[youtube] iMwyj_Q_1xg: Downloading video info webpage
[youtube] Saving request to iMwyj_Q_1xg_https_-_www.youtube.com_get_video_infovideo_id=iMwyj_Q_1xg_ps=default_eurl=_gl=US_hl=en_el=info_disable_polymer=true.dump
[youtube] Saving request to iMwyj_Q_1xg_https_-_www.youtube.com_get_video_infovideo_id=iMwyj_Q_1xg_ps=default_eurl=_gl=US_hl=en_el=embedded_disable_polymer=true.dump
WARNING: Unable to extract video title
[youtube] iMwyj_Q_1xg: Extracting video information
ERROR: Unable to extract uploader name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1704, in _real_extract
    raise ExtractorError('Unable to extract uploader name')
youtube_dl.utils.ExtractorError: Unable to extract uploader name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Let me know if you need the .dump files too.
