### ISSUE TITLE
Stop searching after last "--dateafter" video is found?

### ISSUE THREAD

**Issue by muhahacz** [rg3/youtube-dl#5503] opened 2015-04-22 19:30 UTC
Its possible to stop searching after last video of this criteria is found? 
For example, this playlist contains almost 1000 videos, output of this command are 3 videos for now, but after all, it keeps searching through all channel. 

youtube-dl https://www.youtube.com/playlist?list=UU5nc_ZtjKW1htCVZVRxlQAQ  -e --get-id --get-duration  --dateafter 20150419 --datebefore now 

Thanks

**Comment by jaimeMF** [comment] 2015-04-22 21:13
Duplicate of #1502.

**Closed by jaimeMF** 2015-04-22 21:13 UTC
Labels: request
