### ISSUE TITLE
Question: Skip certain minutes/seconds from the start

### ISSUE THREAD

**Issue by riinav** [rg3/youtube-dl#7708] opened 2015-11-30 21:01 UTC
Is it possible to skip few minutes from start point?
Usecase: I want to download a Keynote which is as long as 10+ hours, 
but the first chunk of 2 hours is just blank video which I want to skip, so do we have some special parameter which can do the Job?

**Comment by jaimeMF** [comment] 2015-11-30 22:35
Duplicate of #622, see https://github.com/rg3/youtube-dl/issues/4821#issuecomment-72213508 for more info.

**Closed by jaimeMF** 2015-11-30 22:35 UTC
