### ISSUE TITLE
youtube: no dash webm anymore?

### ISSUE THREAD

**Issue by Klaus1189** [rg3/youtube-dl#8512] opened 2016-02-11 09:42 UTC
I think there is no dash webm available anymore on youtube. I tried many videos, but not one has dash webm anymore. vorbis and opus are still available. 
I downloaded a video in dash webm some days ago and now there is no webm anymore on youtube. 
Seems like youtube dropped that format or there is another way to get it.

**Comment by 0xABC** [comment] 2016-02-12 19:11
@Klaus1189 Are you sure?

```
[info] Available formats for 8qrhRtjFlpo:
format code  extension  resolution note
249          webm       audio only DASH audio   58k , opus @ 50k, 33.41MiB
250          webm       audio only DASH audio   85k , opus @ 70k, 44.79MiB
140          m4a        audio only DASH audio  132k , m4a_dash container, mp4a.40.2@128k (44100Hz), 81.78MiB
171          webm       audio only DASH audio  156k , vorbis@128k (44100Hz), 77.98MiB
251          webm       audio only DASH audio  165k , opus @160k, 87.89MiB
242          webm       426x240    DASH video   90k , vp9, 30fps, video only, 37.48MiB
278          webm       256x144    DASH video   91k , webm container, vp9, 15fps, video only, 20.67MiB
160          mp4        256x144    DASH video  128k , avc1.42c00c, 15fps, video only, 59.10MiB
243          webm       640x360    DASH video  193k , vp9, 30fps, video only, 80.56MiB
134          mp4        640x360    DASH video  241k , avc1.4d401e, 30fps, video only, 87.75MiB
133          mp4        426x240    DASH video  281k , avc1.4d4015, 30fps, video only, 152.19MiB
244          webm       854x480    DASH video  341k , vp9, 30fps, video only, 143.71MiB
135          mp4        854x480    DASH video  476k , avc1.4d401f, 30fps, video only, 166.68MiB
247          webm       1280x720   DASH video  742k , vp9, 30fps, video only, 223.54MiB
136          mp4        1280x720   DASH video 1033k , avc1.4d401f, 30fps, video only, 351.47MiB
36           3gp        ?x320      small , mp4v.20.3,  mp4a.40.2
17           3gp        176x144    small , mp4v.20.3,  mp4a.40.2@ 24k
5            flv        400x240    small , h263, mp3  @ 64k
43           webm       640x360    medium , vp8.0,  vorbis@128k
18           mp4        640x360    medium , avc1.42001E,  mp4a.40.2@ 96k
22           mp4        1280x720   hd720 , avc1.64001F,  mp4a.40.2@192k (best)
```

**Comment by dstftw** [comment] 2016-02-12 19:22
Duplicate of #8511.

**Closed by dstftw** 2016-02-12 19:22 UTC

**Comment by Klaus1189** [comment] 2016-02-12 19:36
@ 0xABC: only vevo videos are affected as dstftw already mentioned in my other reported issue #8511
