### ISSUE TITLE
Permission denied Python error

### ISSUE THREAD

**Issue by styler2go** [rg3/youtube-dl#8428] opened 2016-02-04 18:06 UTC
Hello, i get the following Python error:
>[debug] System config: []
>[debug] User config: []
>[debug] Command-line args: [u'--verbose', u'--prefer-ffmpeg', u'-o', u'8dZDdW7v4Q8', >u'http://youtu.be/8dZDdW7v4Q8']
>Traceback (most recent call last):
>  File "__main__.py", line 19, in <module>
>  File "youtube_dl\__init__.pyo", line 410, in main
>  File "youtube_dl\__init__.pyo", line 377, in _real_main
>  File "youtube_dl\YoutubeDL.pyo", line 343, in __init__
>  File "youtube_dl\YoutubeDL.pyo", line 2000, in _setup_opener
>  File "youtube_dl\utils.pyo", line 518, in make_HTTPS_handler
>  File "ssl.pyo", line 440, in create_default_context
>  File "ssl.pyo", line 391, in load_default_certs
>  File "ssl.pyo", line 378, in _load_windows_store_certs
>WindowsError: [Error 5] Zugriff verweigert

I am very sure that my permissions are set correctly. It's running on windows. Any idea?

**Comment by dstftw** [comment] 2016-02-05 15:39
Provide more context. Possible duplicate of #7951.

**Comment by styler2go** [comment] 2016-02-08 12:18
I am running it from a PHP script.

PHP is running as PHP-CGI launched by IIS.

If PHP-CGI is being launched as Low Integrity by IIS this can surely be the bug. It worked before i upgraded.

How can i be sure that PHP is running as low integrity?

**Comment by dstftw** [comment] 2016-02-08 12:21
Duplicate of #7951.

**Closed by dstftw** 2016-02-08 12:21 UTC

**Comment by styler2go** [comment] 2016-02-08 12:27
Is there any workaround yet?

**Comment by dstftw** [comment] 2016-02-08 12:31
Read linked issue https://github.com/rg3/youtube-dl/issues/7951#issuecomment-168046944.

**Comment by styler2go** [comment] 2016-02-08 12:39
I've read that already. I also read the Python Bug tracker but i could not find any workaround. So i guess there doesn't exist any?

**Comment by dstftw** [comment] 2016-02-08 12:42
>For example, ```--no-check-certificate``` should work in such cases.

**Comment by styler2go** [comment] 2016-02-08 12:47
I saw that and i tried it but it didn't work. So i assumed this will be a workaround in a future youtube-dl version.

Here is my latest debug output:

> WindowsError: [Error 5] Zugriff verweigert
> [debug] System config: []
> [debug] User config: []
> [debug] Command-line args: [u'--verbose', u'--no-check-certificate', u'--prefer-ffmpeg', u'-o',  u'8dZDdW7v4Q8', u'http://youtu.be/8dZDdW7v4Q8']
> Traceback (most recent call last):
>  File "__main__.py", line 19, in <module>
>  File "youtube_dl\__init__.pyo", line 411, in main
>  File "youtube_dl\__init__.pyo", line 378, in _real_main
>  File "youtube_dl\YoutubeDL.pyo", line 343, in __init__
>  File "youtube_dl\YoutubeDL.pyo", line 1999, in _setup_opener
>  File "youtube_dl\utils.pyo", line 518, in make_HTTPS_handler
>  File "ssl.pyo", line 440, in create_default_context
>  File "ssl.pyo", line 391, in load_default_certs
>  File "ssl.pyo", line 378, in _load_windows_store_certs
> WindowsError: [Error 5] Zugriff verweigert

**Comment by dstftw** [comment] 2016-02-08 12:51
Try python <= 2.7.8.

**Comment by styler2go** [comment] 2016-02-08 12:57
The problem still exists with python 2.7.8:

C:\Users\Administrator\Downloads\PSTools>youtube-dl --verbose --no-check-certifi
cate --prefer-ffmpeg -o "8dZDdW7v4Q8"  http://youtu.be/8dZDdW7v4Q
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--no-check-certificate', u'--prefer-
ffmpeg', u'-o', u'8dZDdW7v4Q8', u'http://youtu.be/8dZDdW7v4Q']
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 411, in main
  File "youtube_dl\__init__.pyo", line 378, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 343, in __init__
  File "youtube_dl\YoutubeDL.pyo", line 1999, in _setup_opener
  File "youtube_dl\utils.pyo", line 518, in make_HTTPS_handler
  File "ssl.pyo", line 440, in create_default_context
  File "ssl.pyo", line 391, in load_default_certs
  File "ssl.pyo", line 378, in _load_windows_store_certs
WindowsError: [Error 5] Access is denied

C:\Users\Administrator\Downloads\PSTools>python --version
Python 2.7.8

C:\Users\Administrator\Downloads\PSTools>youtube-dl --version
2016.02.04

**Comment by dstftw** [comment] 2016-02-08 13:00
Have you rebuild youtube-dl.exe with python 2.7.8?

**Comment by styler2go** [comment] 2016-02-08 13:14
Sorry, my fault. I thought i just have to install python 2.7.8.
I will try rebuilding youtube-dl with python 2.7.8.

**Comment by devmes** [comment] 2016-07-14 08:18
In my case the "windows compatibility mode" solved the problem
right-click on youtube-dl.exe -> Properties -> Compatibility -> Change settings for all users -> Compatibility mode -> Windows XP SP3

**Comment by yan12125** [comment] 2016-07-14 09:12
Another solution is downloading Python 3.5 and youtube-dl via it.

**Comment by luisitsilva** [comment] 2022-12-19 17:23
Hi all,


it works by running with py. Suck as: python3 (Not .9, .10 or any other). python3 url.
