### ISSUE TITLE
Site support request - GlobalTV

### ISSUE THREAD

**Issue by ProgrammerAKL** [rg3/youtube-dl#9859] opened 2016-06-22 15:53 UTC
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.20**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included
The videos are listed at http://www.globaltv.com/video/
Examples:
- Single video: http://www.globaltv.com/thetalk/video/episode/troian-bellisario/video.html?v=710029891680
- Single video: http://www.globaltv.com/houdinianddoyle/video/episode/strigoi/video.html?v=709396547680
- Single video: http://www.globaltv.com/houdinianddoyle/video/webisode/needles/video.html?v=665883715545
(Canadian IP address probably required for all of these)

---

### Description of your *issue*, suggested solution and other information

Please add support for GlobalTV (http://www.globaltv.com/video/). I have found that the streaming involves an m3u8 file but may also require a session key (faxs://). Note that in the above example URLs, the Talk episode will expire within the coming week. The Houdini & Doyle webisode may stay on the website longer. The three example videos I have provided do not require credentials, at least for now. The website contains quite a few older episodes that can be accessed with credentials, if one subscribes to a Canadian cable company and creates a username and password using one's cable account information.

**Comment by yan12125** [comment] 2016-06-24 09:36
Duplicate of #9164.

**Closed by yan12125** 2016-06-24 09:36 UTC
