### ISSUE TITLE
Youtube-dl failing on soundcloud with HTTPError

### ISSUE THREAD

**Issue by ldooks** [rg3/youtube-dl#6950] opened 2015-09-24 17:18 UTC
```
 youtube-dl -v -x  https://soundcloud.com/feintdnb/we-wont-be-alone-feat-laura-brehm-mc-master --audio-format mp3 --embed-thumbnail
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-x', u'https://soundcloud.com/feintdnb/we-wont-be-alone-feat-laura-brehm-mc-master', u'--audio-format', u'mp3', u'--embed-thumbnail']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.22
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8, ffprobe 2.8
[debug] Proxy map: {}
[soundcloud] feintdnb/we-wont-be-alone-feat-laura-brehm-mc-master: Resolving id
[soundcloud] feintdnb/we-wont-be-alone-feat-laura-brehm-mc-master: Downloading info JSON
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 326, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1865, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

**Comment by dstftw** [comment] 2015-09-24 17:20
Duplicate of #6930.

**Closed by dstftw** 2015-09-24 17:20 UTC
