### ISSUE TITLE
BBC iPlayer "ERROR: rtmpdump exited with code 1"

### ISSUE THREAD

**Issue by tombrossman** [rg3/youtube-dl#6906] opened 2015-09-20 14:57 UTC
Downloading videos from BBC iPlayer has stopped working recently, returning the error: "ERROR: rtmpdump exited with code 1". This same error message is returned when trying multiple different videos.

I'm in an area served by the BBC so geographic restriction isn't a problem. I'm running the latest youtube-dl version 2015.09.09.

`youtube-dl -v "http://www.bbc.co.uk/iplayer/episode/b06bgnwg/"` returns this:

```
[bbc.co.uk] b06bgnwg: Downloading video page
[bbc.co.uk] b06bgn9t: Downloading media selection XML
[debug] Invoking downloader on u'rtmp://iplayertokfs.fplive.net/iplayertok?token=c3RhcnRfdGltZT0yMDE1MDkyMDEyMzQ0NyZlbmRfdGltZT0yMDE1MDkyMDE2MzQ0NyZkaWdlc3Q9Mjg2MDcxZjViZWQyMDY5OTVlYjcxNmY3ZWQxYjBkMTQ='
[download] Destination: Curry Wars, Episode 1-b06bgn9t.flv
[debug] rtmpdump command line: rtmpdump --verbose -r 'rtmp://iplayertokfs.fplive.net/iplayertok?token=c3RhcnRfdGltZT0yMDE1MDkyMDEyMzQ0NyZlbmRfdGltZT0yMDE1MDkyMDE2MzQ0NyZkaWdlc3Q9Mjg2MDcxZjViZWQyMDY5OTVlYjcxNmY3ZWQxYjBkMTQ=' -o 'Curry Wars, Episode 1-b06bgn9t.flv.part' --swfVfy http://www.bbc.co.uk/emp/releases/iplayer/revisions/617463_618125_4/617463_618125_4_emp.swf --pageUrl http://www.bbc.co.uk --app 'iplayertok?token=c3RhcnRfdGltZT0yMDE1MDkyMDEyMzQ0NyZlbmRfdGltZT0yMDE1MDkyMDE2MzQ0NyZkaWdlc3Q9Mjg2MDcxZjViZWQyMDY5OTVlYjcxNmY3ZWQxYjBkMTQ=' --playpath mp4:3200kbps/modav/p031s39b_b06bgn9t_1442530685037 --resume --skip 1
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 0
[rtmpdump] DEBUG: Parsed host    : iplayertokfs.fplive.net
[rtmpdump] DEBUG: Parsed app     : iplayertok?token=c3RhcnRfdGltZT0yMDE1MDkyMDEyMzQ0NyZlbmRfdGltZT0yMDE1MDkyMDE2MzQ0NyZkaWdlc3Q9Mjg2MDcxZjViZWQyMDY5OTVlYjcxNmY3ZWQxYjBkMTQ=
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMP
[rtmpdump] DEBUG: Hostname : iplayertokfs.fplive.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:3200kbps/modav/p031s39b_b06bgn9t_1442530685037
[rtmpdump] DEBUG: tcUrl    : rtmp://iplayertokfs.fplive.net:1935/iplayertok?token=c3RhcnRfdGltZT0yMDE1MDkyMDEyMzQ0NyZlbmRfdGltZT0yMDE1MDkyMDE2MzQ0NyZkaWdlc3Q9Mjg2MDcxZjViZWQyMDY5OTVlYjcxNmY3ZWQxYjBkMTQ=
[rtmpdump] DEBUG: swfUrl   : http://www.bbc.co.uk/emp/releases/iplayer/revisions/617463_618125_4/617463_618125_4_emp.swf
[rtmpdump] DEBUG: pageUrl  : http://www.bbc.co.uk
[rtmpdump] DEBUG: app      : iplayertok?token=c3RhcnRfdGltZT0yMDE1MDkyMDEyMzQ0NyZlbmRfdGltZT0yMDE1MDkyMDE2MzQ0NyZkaWdlc3Q9Mjg2MDcxZjViZWQyMDY5OTVlYjcxNmY3ZWQxYjBkMTQ=
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: SWFSHA256:
[rtmpdump] DEBUG: b6 74 7f 89 f9 ec 6a 60 c1 a4 b5 8b b1 18 b0 fa
[rtmpdump] DEBUG: 65 18 86 24 c2 8a 1a a3 2f 72 0f 0b 80 59 dd 7f
[rtmpdump] DEBUG: SWFSize  : 595316
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 0 bytes
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 0
[rtmpdump] DEBUG: Parsed host    : iplayertokfs.fplive.net
[rtmpdump] DEBUG: Parsed app     : iplayertok?token=c3RhcnRfdGltZT0yMDE1MDkyMDEyMzQ0NyZlbmRfdGltZT0yMDE1MDkyMDE2MzQ0NyZkaWdlc3Q9Mjg2MDcxZjViZWQyMDY5OTVlYjcxNmY3ZWQxYjBkMTQ=
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMP
[rtmpdump] DEBUG: Hostname : iplayertokfs.fplive.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:3200kbps/modav/p031s39b_b06bgn9t_1442530685037
[rtmpdump] DEBUG: tcUrl    : rtmp://iplayertokfs.fplive.net:1935/iplayertok?token=c3RhcnRfdGltZT0yMDE1MDkyMDEyMzQ0NyZlbmRfdGltZT0yMDE1MDkyMDE2MzQ0NyZkaWdlc3Q9Mjg2MDcxZjViZWQyMDY5OTVlYjcxNmY3ZWQxYjBkMTQ=
[rtmpdump] DEBUG: swfUrl   : http://www.bbc.co.uk/emp/releases/iplayer/revisions/617463_618125_4/617463_618125_4_emp.swf
[rtmpdump] DEBUG: pageUrl  : http://www.bbc.co.uk
[rtmpdump] DEBUG: app      : iplayertok?token=c3RhcnRfdGltZT0yMDE1MDkyMDEyMzQ0NyZlbmRfdGltZT0yMDE1MDkyMDE2MzQ0NyZkaWdlc3Q9Mjg2MDcxZjViZWQyMDY5OTVlYjcxNmY3ZWQxYjBkMTQ=
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: SWFSHA256:
[rtmpdump] DEBUG: b6 74 7f 89 f9 ec 6a 60 c1 a4 b5 8b b1 18 b0 fa
[rtmpdump] DEBUG: 65 18 86 24 c2 8a 1a a3 2f 72 0f 0b 80 59 dd 7f
[rtmpdump] DEBUG: SWFSize  : 595316
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.
```
`youtube-dl -v -j "http://www.bbc.co.uk/iplayer/episode/b06bgnwg/"` returns this:
```
{"display_id": "b06bgn9t", "extractor": "bbc.co.uk", "description": "Episode one of a two-part series following the hottest competition in Wales. Restaurants go head to head and only one will win the ultimate crown of Welsh Curry House of the Year.", "format": "pc_streaming_hd_level3 - 1280x720", "requested_subtitles": null, "app": "iplayertok?token=c3RhcnRfdGltZT0yMDE1MDkyMDEyNTAwMiZlbmRfdGltZT0yMDE1MDkyMDE2NTAwMiZkaWdlc3Q9OWEyZDY5YTliMzA2MjI5ZjRkYzgzZmVmZDQ5Y2U4MjQ=", "vbr": 2800, "height": 720, "_filename": "Curry Wars, Episode 1-b06bgn9t.flv", "duration": 1800, "format_id": "pc_streaming_hd_level3", "play_path": "mp4:3200kbps/modav/p031s39b_b06bgn9t_1442530685037", "id": "b06bgn9t", "subtitles": {}, "player_url": "http://www.bbc.co.uk/emp/releases/iplayer/revisions/617463_618125_4/617463_618125_4_emp.swf", "playlist": null, "rtmp_live": false, "thumbnails": [{"url": "http://ichef.bbci.co.uk/images/ic/1200x675/p031yb6f.jpg", "id": "0"}], "title": "Curry Wars, Episode 1", "url": "rtmp://iplayertokfs.fplive.net/iplayertok?token=c3RhcnRfdGltZT0yMDE1MDkyMDEyNTAwMiZlbmRfdGltZT0yMDE1MDkyMDE2NTAwMiZkaWdlc3Q9OWEyZDY5YTliMzA2MjI5ZjRkYzgzZmVmZDQ5Y2U4MjQ=", "extractor_key": "BBCCoUk", "vcodec": "h264", "http_headers": {"Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Language": "en-us,en;q=0.5", "Accept-Encoding": "gzip, deflate", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)"}, "playlist_index": null, "width": 1280, "ext": "flv", "filesize": 528198083, "webpage_url": "http://www.bbc.co.uk/iplayer/episode/b06bgnwg/", "formats": [{"http_headers": {"Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Language": "en-us,en;q=0.5", "Accept-Encoding": "gzip, deflate", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)"}, "rtmp_live": false, "width": 640, "url": "rtmp://vod-rtmp-uk-live.edgesuite.net/ondemand?auth=daEd.bLdrcabeaydqcEcYd4dUdJaacnbsaF-bv_SEA-bWG-DosGHpwoJBrHtyC&aifp=v001&slist=secure/480kbps/modav/p031s39b_b06bgn9t_1442527736875.mp4;secure/800kbps/modav/p031s39b_b06bgn9t_1442527734410.mp4;secure/3200kbps/modav/p031s39b_b06bgn9t_1442530685037.mp4;secure/1500kbps/modav/p031s39b_b06bgn9t_1442527736140.mp4", "play_path": "mp4:secure/480kbps/modav/p031s39b_b06bgn9t_1442527736875.mp4", "app": "ondemand?auth=daEd.bLdrcabeaydqcEcYd4dUdJaacnbsaF-bv_SEA-bWG-DosGHpwoJBrHtyC&aifp=v001&slist=secure/480kbps/modav/p031s39b_b06bgn9t_1442527736875.mp4;secure/800kbps/modav/p031s39b_b06bgn9t_1442527734410.mp4;secure/3200kbps/modav/p031s39b_b06bgn9t_1442530685037.mp4;secure/1500kbps/modav/p031s39b_b06bgn9t_1442527736140.mp4", "format": "iplayer_streaming_h264_flv_lo_akamai - 640x360", "player_url": "http://www.bbc.co.uk/emp/releases/iplayer/revisions/617463_618125_4/617463_618125_4_emp.swf", "vbr": 480, "ext": "flv", "filesize": 113134188, "format_id": "iplayer_streaming_h264_flv_lo_akamai", "height": 360, "vcodec": "h264", "page_url": "http://www.bbc.co.uk"}, {"http_headers": {"Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Language": "en-us,en;q=0.5", "Accept-Encoding": "gzip, deflate", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)"}, "rtmp_live": false, "width": 640, "url": "rtmp://bbcfmt.fcod.llnwd.net/a8984/e3?as=adobe-hmac-sha256&av=1&te=connect&mp=iplayerstream/secure_auth/480kbps/modav/p031s39b_b06bgn9t_1442527736875.mp4,iplayerstream/secure_auth/800kbps/modav/p031s39b_b06bgn9t_1442527734410.mp4,iplayerstream/secure_auth/1500kbps/modav/p031s39b_b06bgn9t_1442527736140.mp4&et=1442767802&fmta-token=1d4eb4fe116aaa37e6555afb3fbb4a5b9a3ef8493e91cf390a163254320b1e49", "play_path": "mp4:iplayerstream/secure_auth/480kbps/modav/p031s39b_b06bgn9t_1442527736875.mp4", "app": "a8984/e3?as=adobe-hmac-sha256&av=1&te=connect&mp=iplayerstream/secure_auth/480kbps/modav/p031s39b_b06bgn9t_1442527736875.mp4,iplayerstream/secure_auth/800kbps/modav/p031s39b_b06bgn9t_1442527734410.mp4,iplayerstream/secure_auth/1500kbps/modav/p031s39b_b06bgn9t_1442527736140.mp4&et=1442767802&fmta-token=1d4eb4fe116aaa37e6555afb3fbb4a5b9a3ef8493e91cf390a163254320b1e49", "format": "iplayer_streaming_h264_flv_lo_limelight - 640x360", "player_url": "http://www.bbc.co.uk/emp/releases/iplayer/revisions/617463_618125_4/617463_618125_4_emp.swf", "vbr": 480, "ext": "flv", "filesize": 113134188, "format_id": "iplayer_streaming_h264_flv_lo_limelight", "height": 360, "vcodec": "h264", "page_url": "http://www.bbc.co.uk"}, {"http_headers": {"Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Language": "en-us,en;q=0.5", "Accept-Encoding": "gzip, deflate", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)"}, "rtmp_live": false, "width": 640, "url": "rtmp://vod-rtmp-uk-live.edgesuite.net/ondemand?auth=daEd.bLdrcabeaydqcEcYd4dUdJaacnbsaF-bv_SEA-bWG-DosGHpwoJBrHtyC&aifp=v001&slist=secure/480kbps/modav/p031s39b_b06bgn9t_1442527736875.mp4;secure/800kbps/modav/p031s39b_b06bgn9t_1442527734410.mp4;secure/3200kbps/modav/p031s39b_b06bgn9t_1442530685037.mp4;secure/1500kbps/modav/p031s39b_b06bgn9t_1442527736140.mp4", "play_path": "mp4:secure/800kbps/modav/p031s39b_b06bgn9t_1442527734410.mp4", "app": "ondemand?auth=daEd.bLdrcabeaydqcEcYd4dUdJaacnbsaF-bv_SEA-bWG-DosGHpwoJBrHtyC&aifp=v001&slist=secure/480kbps/modav/p031s39b_b06bgn9t_1442527736875.mp4;secure/800kbps/modav/p031s39b_b06bgn9t_1442527734410.mp4;secure/3200kbps/modav/p031s39b_b06bgn9t_1442530685037.mp4;secure/1500kbps/modav/p031s39b_b06bgn9t_1442527736140.mp4", "format": "iplayer_streaming_h264_flv_akamai - 640x360", "player_url": "http://www.bbc.co.uk/emp/releases/iplayer/revisions/617463_618125_4/617463_618125_4_emp.swf", "vbr": 796, "ext": "flv", "filesize": 176787058, "format_id": "iplayer_streaming_h264_flv_akamai", "height": 360, "vcodec": "h264", "page_url": "http://www.bbc.co.uk"}, {"http_headers": {"Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Language": "en-us,en;q=0.5", "Accept-Encoding": "gzip, deflate", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)"}, "rtmp_live": false, "width": 640, "url": "rtmp://bbcfmt.fcod.llnwd.net/a8984/e3?as=adobe-hmac-sha256&av=1&te=connect&mp=iplayerstream/secure_auth/480kbps/modav/p031s39b_b06bgn9t_1442527736875.mp4,iplayerstream/secure_auth/800kbps/modav/p031s39b_b06bgn9t_1442527734410.mp4,iplayerstream/secure_auth/1500kbps/modav/p031s39b_b06bgn9t_1442527736140.mp4&et=1442767802&fmta-token=1d4eb4fe116aaa37e6555afb3fbb4a5b9a3ef8493e91cf390a163254320b1e49", "play_path": "mp4:iplayerstream/secure_auth/800kbps/modav/p031s39b_b06bgn9t_1442527734410.mp4", "app": "a8984/e3?as=adobe-hmac-sha256&av=1&te=connect&mp=iplayerstream/secure_auth/480kbps/modav/p031s39b_b06bgn9t_1442527736875.mp4,iplayerstream/secure_auth/800kbps/modav/p031s39b_b06bgn9t_1442527734410.mp4,iplayerstream/secure_auth/1500kbps/modav/p031s39b_b06bgn9t_1442527736140.mp4&et=1442767802&fmta-token=1d4eb4fe116aaa37e6555afb3fbb4a5b9a3ef8493e91cf390a163254320b1e49", "format": "iplayer_streaming_h264_flv_limelight - 640x360", "player_url": "http://www.bbc.co.uk/emp/releases/iplayer/revisions/617463_618125_4/617463_618125_4_emp.swf", "vbr": 796, "ext": "flv", "filesize": 176787058, "format_id": "iplayer_streaming_h264_flv_limelight", "height": 360, "vcodec": "h264", "page_url": "http://www.bbc.co.uk"}, {"http_headers": {"Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Language": "en-us,en;q=0.5", "Accept-Encoding": "gzip, deflate", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)"}, "rtmp_live": false, "width": 832, "url": "rtmp://vod-rtmp-uk-live.edgesuite.net/ondemand?auth=daEd.bLdrcabeaydqcEcYd4dUdJaacnbsaF-bv_SEA-bWG-DosGHpwoJBrHtyC&aifp=v001&slist=secure/480kbps/modav/p031s39b_b06bgn9t_1442527736875.mp4;secure/800kbps/modav/p031s39b_b06bgn9t_1442527734410.mp4;secure/3200kbps/modav/p031s39b_b06bgn9t_1442530685037.mp4;secure/1500kbps/modav/p031s39b_b06bgn9t_1442527736140.mp4", "play_path": "mp4:secure/1500kbps/modav/p031s39b_b06bgn9t_1442527736140.mp4", "app": "ondemand?auth=daEd.bLdrcabeaydqcEcYd4dUdJaacnbsaF-bv_SEA-bWG-DosGHpwoJBrHtyC&aifp=v001&slist=secure/480kbps/modav/p031s39b_b06bgn9t_1442527736875.mp4;secure/800kbps/modav/p031s39b_b06bgn9t_1442527734410.mp4;secure/3200kbps/modav/p031s39b_b06bgn9t_1442530685037.mp4;secure/1500kbps/modav/p031s39b_b06bgn9t_1442527736140.mp4", "format": "iplayer_streaming_h264_flv_high_akamai - 832x468", "player_url": "http://www.bbc.co.uk/emp/releases/iplayer/revisions/617463_618125_4/617463_618125_4_emp.swf", "vbr": 1500, "ext": "flv", "filesize": 330782692, "format_id": "iplayer_streaming_h264_flv_high_akamai", "height": 468, "vcodec": "h264", "page_url": "http://www.bbc.co.uk"}, {"http_headers": {"Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Language": "en-us,en;q=0.5", "Accept-Encoding": "gzip, deflate", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)"}, "rtmp_live": false, "width": 832, "url": "rtmp://bbcfmt.fcod.llnwd.net/a8984/e3?as=adobe-hmac-sha256&av=1&te=connect&mp=iplayerstream/secure_auth/480kbps/modav/p031s39b_b06bgn9t_1442527736875.mp4,iplayerstream/secure_auth/800kbps/modav/p031s39b_b06bgn9t_1442527734410.mp4,iplayerstream/secure_auth/1500kbps/modav/p031s39b_b06bgn9t_1442527736140.mp4&et=1442767802&fmta-token=1d4eb4fe116aaa37e6555afb3fbb4a5b9a3ef8493e91cf390a163254320b1e49", "play_path": "mp4:iplayerstream/secure_auth/1500kbps/modav/p031s39b_b06bgn9t_1442527736140.mp4", "app": "a8984/e3?as=adobe-hmac-sha256&av=1&te=connect&mp=iplayerstream/secure_auth/480kbps/modav/p031s39b_b06bgn9t_1442527736875.mp4,iplayerstream/secure_auth/800kbps/modav/p031s39b_b06bgn9t_1442527734410.mp4,iplayerstream/secure_auth/1500kbps/modav/p031s39b_b06bgn9t_1442527736140.mp4&et=1442767802&fmta-token=1d4eb4fe116aaa37e6555afb3fbb4a5b9a3ef8493e91cf390a163254320b1e49", "format": "iplayer_streaming_h264_flv_high_limelight - 832x468", "player_url": "http://www.bbc.co.uk/emp/releases/iplayer/revisions/617463_618125_4/617463_618125_4_emp.swf", "vbr": 1500, "ext": "flv", "filesize": 330782692, "format_id": "iplayer_streaming_h264_flv_high_limelight", "height": 468, "vcodec": "h264", "page_url": "http://www.bbc.co.uk"}, {"http_headers": {"Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Language": "en-us,en;q=0.5", "Accept-Encoding": "gzip, deflate", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)"}, "rtmp_live": false, "width": 1280, "url": "rtmp://vod-rtmp-uk-live.edgesuite.net/ondemand?auth=daEd.bLdrcabeaydqcEcYd4dUdJaacnbsaF-bv_SEA-bWG-DosGHpwoJBrHtyC&aifp=v001&slist=secure/480kbps/modav/p031s39b_b06bgn9t_1442527736875.mp4;secure/800kbps/modav/p031s39b_b06bgn9t_1442527734410.mp4;secure/3200kbps/modav/p031s39b_b06bgn9t_1442530685037.mp4;secure/1500kbps/modav/p031s39b_b06bgn9t_1442527736140.mp4", "play_path": "mp4:secure/3200kbps/modav/p031s39b_b06bgn9t_1442530685037.mp4", "app": "ondemand?auth=daEd.bLdrcabeaydqcEcYd4dUdJaacnbsaF-bv_SEA-bWG-DosGHpwoJBrHtyC&aifp=v001&slist=secure/480kbps/modav/p031s39b_b06bgn9t_1442527736875.mp4;secure/800kbps/modav/p031s39b_b06bgn9t_1442527734410.mp4;secure/3200kbps/modav/p031s39b_b06bgn9t_1442530685037.mp4;secure/1500kbps/modav/p031s39b_b06bgn9t_1442527736140.mp4", "format": "pc_streaming_hd_akamai - 1280x720", "player_url": "http://www.bbc.co.uk/emp/releases/iplayer/revisions/617463_618125_4/617463_618125_4_emp.swf", "vbr": 2800, "ext": "flv", "filesize": 528198083, "format_id": "pc_streaming_hd_akamai", "height": 720, "vcodec": "h264", "page_url": "http://www.bbc.co.uk"}, {"http_headers": {"Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Language": "en-us,en;q=0.5", "Accept-Encoding": "gzip, deflate", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)"}, "rtmp_live": false, "width": 1280, "url": "rtmp://iplayertokfs.fplive.net/iplayertok?token=c3RhcnRfdGltZT0yMDE1MDkyMDEyNTAwMiZlbmRfdGltZT0yMDE1MDkyMDE2NTAwMiZkaWdlc3Q9OWEyZDY5YTliMzA2MjI5ZjRkYzgzZmVmZDQ5Y2U4MjQ=", "play_path": "mp4:3200kbps/modav/p031s39b_b06bgn9t_1442530685037", "app": "iplayertok?token=c3RhcnRfdGltZT0yMDE1MDkyMDEyNTAwMiZlbmRfdGltZT0yMDE1MDkyMDE2NTAwMiZkaWdlc3Q9OWEyZDY5YTliMzA2MjI5ZjRkYzgzZmVmZDQ5Y2U4MjQ=", "format": "pc_streaming_hd_level3 - 1280x720", "player_url": "http://www.bbc.co.uk/emp/releases/iplayer/revisions/617463_618125_4/617463_618125_4_emp.swf", "vbr": 2800, "ext": "flv", "filesize": 528198083, "format_id": "pc_streaming_hd_level3", "height": 720, "vcodec": "h264", "page_url": "http://www.bbc.co.uk"}], "fulltitle": "Curry Wars, Episode 1", "thumbnail": "http://ichef.bbci.co.uk/images/ic/1200x675/p031yb6f.jpg", "webpage_url_basename": "b06bgnwg", "page_url": "http://www.bbc.co.uk"}
```
If there is anything else I can test or add to this report please let me know.

**Comment by dstftw** [comment] 2015-09-20 14:58
Duplicate of #6855.

**Closed by dstftw** 2015-09-20 14:58 UTC
