### ISSUE TITLE
HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by mobvd** [rg3/youtube-dl#5149] opened 2015-03-06 15:06 UTC
youtube-dl -F https://www.youtube.com/watch?v=3dr6aTDmp8A
[youtube] 3dr6aTDmp8A: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[root@ns239479 ~]#

**Comment by BlackPropeller** [comment] 2015-03-08 03:43
Same issue as #5138

**Comment by vippendu** [comment] 2015-03-08 07:59
use proxy ip --proxy 'proxy-ip'

**Comment by jaimeMF** [comment] 2015-03-08 10:45
Closing as a duplicate of #5138.
Also: **don't run youtube-dl as the root user**, you should only need it for updating.

**Closed by jaimeMF** 2015-03-08 10:45 UTC

**Comment by mobvd** [comment] 2015-03-08 13:49
i try run it with 3 different server i face smae problem. on other server i
not run this script before so its not possible over download videos.

**Comment by mobvd** [comment] 2015-03-08 13:50
also its up-to-date :(

**Comment by BlackPropeller** [comment] 2015-03-08 17:18
@mobvd your server looks to be from OVH right? I also tested this on an ovh server that's never made a request to youtube before and i'm also getting the 429 error on that machine too. I've already reported this issue to their tech support. It might be that youtube is blocking all of ovh's ip blocks. You can do what @vippendu suggested and use proxy servers as a workaround right now.

**Comment by mobvd** [comment] 2015-03-09 01:22
yes its OVH. i notice youtube-dl work on OVH network windows based server.

thanks for suggestion

**Comment by mobvd** [comment] 2015-03-09 02:12
resolve.
 --force-ipv4

thanks

**Comment by vippendu** [comment] 2015-03-13 10:21
hi,
i checked this on another server its working ..

thanks

**Comment by mobvd** [comment] 2015-03-13 14:12
thanks janab. i will try ipv4 and it working.
