### ISSUE TITLE
ERROR: unable to download video data: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by sle3pie** [rg3/youtube-dl#6610] opened 2015-08-19 06:58 UTC
Hello,

Keep getting HTTP Error 403: Forbidden, example below

youtube-dl.exe https://youtu.be/hJYGddE0vHc
[youtube] hJYGddE0vHc: Downloading webpage
[youtube] hJYGddE0vHc: Downloading video info webpage
[youtube] hJYGddE0vHc: Extracting video information
[youtube] hJYGddE0vHc: Downloading DASH manifest
WARNING: [youtube] hJYGddE0vHc: Skipping DASH manifest: ExtractorError(u'Could n
ot download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); pl
ease report this issue on https://yt-dl.org/bug . Make sure you are using the la
test version; type  youtube-dl -U  to update. Be sure to call youtube-dl with th
e --verbose flag and include its complete output.',)
ERROR: unable to download video data: HTTP Error 403: Forbidden

**Comment by yan12125** [comment] 2015-08-19 07:45
Duplicate of #6451. Try ```youtube-dl --rm-cache-dir```

**Closed** 2015-08-19 07:46 UTC
