### ISSUE TITLE
[Soundcloud]: Unable to download JSON metadata

### ISSUE THREAD

**Issue by mhlavacka** [rg3/youtube-dl#6942] opened 2015-09-24 07:43 UTC
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Velocity-** [comment] 2015-09-24 08:25
Can confirm this, here's a full verbose log output:

```
[bart@laptop ~]$ youtube-dl -x --audio-format mp3 --verbose http://www.soundcloud.com/gpmlamb/how-deep-is-your-love-calvin-harris-disciples 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-x', '--audio-format', 'mp3', '--verbose', 'http://www.soundcloud.com/gpmlamb/how-deep-is-your-love-calvin-harris-disciples']
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[debug] Encodings: locale ANSI_X3.4-1968, fs ascii, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2015.09.22
[debug] Python version 3.4.3 - Linux-4.0.6-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.8, ffprobe 2.8
[debug] Proxy map: {}
[soundcloud] gpmlamb/how-deep-is-your-love-calvin-harris-disciples: Resolving id
[soundcloud] gpmlamb/how-deep-is-your-love-calvin-harris-disciples: Downloading info JSON
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 326, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1865, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 469, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 507, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

**Comment by Velocity-** [comment] 2015-09-24 08:32
Never mind, this does work when cloning the git repo. Seems like the release contains an outdated client ID. Maybe an idea to have the option to provide the client id?

**Comment by dstftw** [comment] 2015-09-24 09:24
Duplicate of #6930.

**Closed by dstftw** 2015-09-24 09:24 UTC
