### ISSUE TITLE
HTTP Error 403: Forbidden downloading video

### ISSUE THREAD

**Issue by gradha** [rg3/youtube-dl#6456] opened 2015-08-04 15:30 UTC
```
$ youtube-dl  -U
youtube-dl is up-to-date (2015.07.28)
$ youtube-dl --verbose http://www.youtube.com/watch?v=CDhfIgS4aAo
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.youtube.com/watch?v=CDhfIgS4aAo']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.28
[debug] Python version 2.7.6 - Darwin-14.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.6.2
[debug] Proxy map: {}
[youtube] CDhfIgS4aAo: Downloading webpage
[youtube] CDhfIgS4aAo: Downloading video info webpage
[youtube] CDhfIgS4aAo: Extracting video information
[youtube] {22} signature length 40.42, html5 player new
[youtube] {43} signature length 40.42, html5 player new
[youtube] {18} signature length 40.42, html5 player new
[youtube] {5} signature length 40.42, html5 player new
[youtube] {36} signature length 40.42, html5 player new
[youtube] {17} signature length 40.42, html5 player new
[youtube] {137} signature length 40.42, html5 player new
[youtube] {248} signature length 40.42, html5 player new
[youtube] {136} signature length 40.42, html5 player new
[youtube] {247} signature length 40.42, html5 player new
[youtube] {135} signature length 40.42, html5 player new
[youtube] {244} signature length 40.42, html5 player new
[youtube] {134} signature length 40.42, html5 player new
[youtube] {243} signature length 40.42, html5 player new
[youtube] {133} signature length 40.42, html5 player new
[youtube] {242} signature length 40.42, html5 player new
[youtube] {160} signature length 40.42, html5 player new
[youtube] {140} signature length 40.42, html5 player new
[youtube] {171} signature length 40.42, html5 player new
[youtube] CDhfIgS4aAo: Downloading DASH manifest
WARNING: [youtube] CDhfIgS4aAo: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[debug] Invoking downloader on u'https://r1---sn-h5q7dnes.googlevideo.com/videoplayback?source=youtube&dur=220.011&id=o-AKx5q_yAOAeuka7N9i5g4boFp4UjJFR8Vf3jxItQAset&itag=137&lmt=1438650941893824&requiressl=yes&ip=79.153.95.84&keepalive=yes&clen=103294426&mv=m&pl=18&mt=1438701274&ms=au&mn=sn-h5q7dnes&mm=31&key=yt5&sver=3&gir=yes&gcr=es&sparams=clen%2Cdur%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&expire=1438722978&initcwndbps=1256250&ipbits=0&fexp=9405825%2C9407992%2C9408710%2C9412773%2C9415365%2C9415485%2C9415849%2C9416126%2C9416377%2C9416729%2C9416838%2C9417097%2C9417600%2C9417942%2C9418019%2C9418153&nh=IgpwcjAxLm1hZDA2KgkxMjcuMC4wLjE&mime=video%2Fmp4&upn=Zc_0wjYfaoI&signature=D220AB1FC953273546FC5F982D83453E93BFC09.330FABF58216D3930110C9B56C7BEA6C948901D3&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/Users/gradha/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1430, in process_info
    partial_success = dl(fname, new_info)
  File "/Users/gradha/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1378, in dl
    return fd.download(name, info)
  File "/Users/gradha/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/Users/gradha/bin/youtube-dl/youtube_dl/downloader/http.py", line 59, in real_download
    data = self.ydl.urlopen(request)
  File "/Users/gradha/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1732, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
```
The video plays fine in a browser.

**Comment by dstftw** [comment] 2015-08-04 15:31
Duplicate of #6451.

**Closed by dstftw** 2015-08-04 15:31 UTC
