### ISSUE TITLE
[Syfy] Unable to extract video url

### ISSUE THREAD

**Issue by gineadai** [rg3/youtube-dl#9146] opened 2016-04-10 18:12 UTC
http://www.syfy.com/videos/Robot%20Combat%20League/Behind%20the%20Scenes/vid:2631458
http://www.syfy.com/12monkeys/videos/201-year-of-the-monkey

**Comment by dstftw** [comment] 2016-04-10 18:13
Duplicate of #9087.

**Closed by dstftw** 2016-04-10 18:13 UTC
