### ISSUE TITLE
ExtractorError('Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); 

### ISSUE THREAD

**Issue by p0ngbr** [rg3/youtube-dl#6398] opened 2015-07-29 02:56 UTC
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-x', '--audio-format=mp3', 'https://www.youtube.com/watch?v=Yr8xDSPjII8', '--verbose']
[debug] Encodings: locale ISO-8859-1, fs iso8859-1, out ISO-8859-1, pref ISO-8859-1
[debug] youtube-dl version 2015.07.21
[debug] Python version 3.4.3 - Linux-4.1.2-2-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Yr8xDSPjII8: Downloading webpage
[youtube] Yr8xDSPjII8: Downloading video info webpage
[youtube] Yr8xDSPjII8: Extracting video information
[youtube] {43} signature length 40.40, html5 player en_US-vflSxbpbe
[youtube] {18} signature length 40.40, html5 player en_US-vflSxbpbe
[youtube] {5} signature length 40.40, html5 player en_US-vflSxbpbe
[youtube] {36} signature length 40.40, html5 player en_US-vflSxbpbe
[youtube] {17} signature length 40.40, html5 player en_US-vflSxbpbe
[youtube] {135} signature length 40.40, html5 player en_US-vflSxbpbe
[youtube] {244} signature length 40.40, html5 player en_US-vflSxbpbe
[youtube] {134} signature length 40.40, html5 player en_US-vflSxbpbe
[youtube] {243} signature length 40.40, html5 player en_US-vflSxbpbe
[youtube] {133} signature length 40.40, html5 player en_US-vflSxbpbe
[youtube] {242} signature length 40.40, html5 player en_US-vflSxbpbe
[youtube] {160} signature length 40.40, html5 player en_US-vflSxbpbe
[youtube] {140} signature length 40.40, html5 player en_US-vflSxbpbe
[youtube] {171} signature length 40.40, html5 player en_US-vflSxbpbe
[youtube] Yr8xDSPjII8: Downloading DASH manifest
[youtube] Yr8xDSPjII8: Downloading player https://s.ytimg.com/yts/jsbin/html5player-en_US-vflSxbpbe/html5player.js
[youtube] Yr8xDSPjII8: Downloading DASH manifest
WARNING: Could not download DASH manifest: HTTP Error 403: Forbidden
[debug] Invoking downloader on 'https://r8---sn-b8u-bpbl.googlevideo.com/videoplayback?id=62bf310d23e3208f&itag=141&source=youtube&requiressl=yes&pcm2cms=yes&pl=22&gcr=br&ms=au&mv=m&mn=sn-b8u-bpbl&mm=31&ratebypass=yes&mime=audio/mp4&gir=yes&clen=7331061&lmt=1417201816818720&dur=229.923&fexp=901802,901816,936111,9405643,9405988,9407117,9407664,9407943,9408710,9412494,9414856,9415365,9415436,9415485,9416075,9416126,9417926,9418339&upn=LjbTulEgRS8&key=dg_yt0&mt=1438137229&signature=48CDE851966CF64146B715F8C7730F38C447B67C.3E01697495FFADD4D02B3EE010F3328226A3FED8&sver=3&ip=186.212.112.121&ipbits=0&expire=1438158892&sparams=ip,ipbits,expire,id,itag,source,requiressl,pcm2cms,pl,gcr,ms,mv,mn,mm,ratebypass,mime,gir,clen,lmt,dur'
[download] Resuming download at byte 1047552
[download] Destination: Diana Krall - The Look Of Love-Yr8xDSPjII8.m4a
[download] 100% of 6.99MiB in 00:43
[ffmpeg] Correcting container in "Diana Krall - The Look Of Love-Yr8xDSPjII8.m4a"
[debug] ffmpeg command line: ffmpeg -y -i 'Diana Krall - The Look Of Love-Yr8xDSPjII8.m4a' -c copy -f mp4 'Diana Krall - The Look Of Love-Yr8xDSPjII8.temp.m4a'
[debug] ffmpeg command line: ffprobe -show_streams 'Diana Krall - The Look Of Love-Yr8xDSPjII8.m4a'
[ffmpeg] Destination: Diana Krall - The Look Of Love-Yr8xDSPjII8.mp3
[debug] ffmpeg command line: ffmpeg -y -i 'Diana Krall - The Look Of Love-Yr8xDSPjII8.m4a' -vn -acodec libmp3lame -q:a 5 'Diana Krall - The Look Of Love-Yr8xDSPjII8.mp3'
Deleting original file Diana Krall - The Look Of Love-Yr8xDSPjII8.m4a (pass -k to keep)

**Comment by dstftw** [comment] 2015-07-29 03:19
Duplicate of #5118.

**Closed by dstftw** 2015-07-29 03:19 UTC
