### ISSUE TITLE
Vevo YouTube Download Error as requested

### ISSUE THREAD

**Issue by ljfnord** [rg3/youtube-dl#6608] opened 2015-08-19 04:16 UTC
Getting the following error on trying to download a Vevo video from YouTube:
[C:\winbin]youtube-dl.exe --verbose https://youtu.be/MS91knuzoOA
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://youtu.be/MS91knuzoOA']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.08.16.1
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-73872-g6b96c70, ffprobe N-73872-g6b96c70, rtmpdum
p 2.4
[debug] Proxy map: {}
[youtube] MS91knuzoOA: Downloading webpage
[youtube] MS91knuzoOA: Downloading video info webpage
[youtube] MS91knuzoOA: Extracting video information
[youtube] {43} signature length 40.42, html5 player new
[youtube] {18} signature length 40.42, html5 player new
[youtube] {5} signature length 40.42, html5 player new
[youtube] {36} signature length 40.42, html5 player new
[youtube] {17} signature length 40.42, html5 player new
[youtube] {135} signature length 40.42, html5 player new
[youtube] {244} signature length 40.42, html5 player new
[youtube] {134} signature length 40.42, html5 player new
[youtube] {243} signature length 40.42, html5 player new
[youtube] {133} signature length 40.42, html5 player new
[youtube] {242} signature length 40.42, html5 player new
[youtube] {160} signature length 40.42, html5 player new
[youtube] {140} signature length 40.42, html5 player new
[youtube] {171} signature length 40.42, html5 player new
[youtube] MS91knuzoOA: Downloading DASH manifest
WARNING: [youtube] MS91knuzoOA: Skipping DASH manifest: ExtractorError(u'Could n
ot download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); pl
ease report this issue on https://yt-dl.org/bug . Make sure you are using the la
test version; type  youtube-dl -U  to update. Be sure to call youtube-dl with th
e --verbose flag and include its complete output.',)
[debug] Invoking downloader on u'https://r3---sn-8xgp1vo-q4fe.googlevideo.com/vi
deoplayback?sver=3&requiressl=yes&mt=1439957476&clen=28066396&cwbhb=yes&itag=135
&fexp=9405973%2C9408507%2C9408710%2C9409069%2C9414737%2C9415051%2C9415365%2C9415
436%2C9415485%2C9416023%2C9416075%2C9416126%2C9416729%2C9416837%2C9417224%2C9417
269%2C9417707%2C9418153%2C9419225%2C9419318%2C9419445&ipbits=0&mime=video%2Fmp4&
initcwndbps=1630000&key=yt5&gir=yes&expire=1439979167&sparams=clen%2Ccwbhb%2Cdur
%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2C
mm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&upn=UMbrfA
BftRw&gcr=us&pl=21&dur=332.965&lmt=1429781862166589&ip=71.96.124.208&ms=au&keepa
live=yes&pcm2cms=yes&mv=m&source=youtube&id=o-AMlBeeIG8RYtXW8pbadOEobphU7K1vTlBe
ORIL6Zpu1Z&mn=sn-8xgp1vo-q4fe&mm=31&signature=04DD1A852056596FB119BBCB9B397B5952
88FD70.08CA01B91CB283B9D9300667CAB8ED5B71272459&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1579, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1527, in dl
  File "youtube_dl\downloader\common.pyo", line 342, in download
  File "youtube_dl\downloader\http.pyo", line 60, in real_download
  File "youtube_dl\YoutubeDL.pyo", line 1860, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default
HTTPError: HTTP Error 403: Forbidden

Sorry if this is a duplicate.

**Comment by yan12125** [comment] 2015-08-19 05:49
Duplicate of #6451.

**Closed by yan12125** 2015-08-19 05:49 UTC
