### ISSUE TITLE
Site request: embed.mecloud.vn

### ISSUE THREAD

**Issue by trandinhnam** [rg3/youtube-dl#8210] opened 2016-01-12 08:07 UTC
The basic site is: http://embed.mecloud.vn.
It keep the sessionid to get the directlink:
http://video.thethao247.vn/video-bong-da/danh-thu-bong-da/video-chiem-nguong-2-ban-thang-an-tuong-cua-messi-nam-12-tuoi-dv118308.html

Anyone have idea for this site?

**Comment by remitamine** [comment] 2016-01-15 15:46
duplicate of #6836.

**Closed by remitamine** 2016-01-15 15:46 UTC
