### ISSUE TITLE
Error 429 [Can't solve it]

### ISSUE THREAD

**Issue by jura43** [rg3/youtube-dl#9023] opened 2016-03-29 09:18 UTC
I know this is old error but I still cant to solve it.
I have sinusbot and when I try to download song from youtube I get this:

` Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

When I try to download on server via CLI with command 

`youtube-dl  http://www.youtube.com/watch?v=qlPx6tmAIlM`

I get same error.

I tried

- With `--force-ipv4`
- With `--force-ipv6`
- With `--varbose`
- To update with `youtube-dl -U`
- Reinstall

I have pip version 7.1.2

**Comment by yan12125** [comment] 2016-03-29 10:04
Duplicate of #5138. See also [this FAQ entry](https://github.com/rg3/youtube-dl#http-error-429-too-many-requests-or-402-payment-required).

**Closed by yan12125** 2016-03-29 10:04 UTC
