### ISSUE TITLE
Add support for go90.com

### ISSUE THREAD

**Issue by EveryDirection** [rg3/youtube-dl#11137] opened 2016-11-07 22:25 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.04*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

**Please add support for go90.com.** Example failed output:

```
C:\>youtube-dl -v https://www.go90.com/profiles/va_645e6b8f05d64b70a7fb6b88f02dfcb7
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://www.go90.com/profiles/va_645e6b8f05d6
4b70a7fb6b88f02dfcb7']
[debug] Encodings: locale cp950, fs mbcs, out cp950, pref cp950
[debug] youtube-dl version 2016.11.04
[debug] Python version 3.4.4 - Windows-7-6.1.7600-SP0
[debug] exe versions: ffmpeg N-79460-g21acc4d, ffprobe N-79460-g21acc4d
[debug] Proxy map: {}
[generic] va_645e6b8f05d64b70a7fb6b88f02dfcb7: Requesting header
WARNING: Falling back on generic information extractor.
[generic] va_645e6b8f05d64b70a7fb6b88f02dfcb7: Downloading webpage
[generic] va_645e6b8f05d64b70a7fb6b88f02dfcb7: Extracting information
ERROR: Unsupported URL: https://www.go90.com/profiles/va_645e6b8f05d64b70a7fb6b8
8f02dfcb7
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqdvyr8vw\bu
ild\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqdvyr8vw\bu
ild\youtube_dl\extractor\common.py", line 357, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqdvyr8vw\bu
ild\youtube_dl\extractor\generic.py", line 2421, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.go90.com/profile
s/va_645e6b8f05d64b70a7fb6b88f02dfcb7
```

Example video links:

- Single video: https://www.go90.com/profiles/va_645e6b8f05d64b70a7fb6b88f02dfcb7
- Single video: https://www.go90.com/profiles/va_b24b7af9fab24a6f86486ebb8af80e29
- Single video: https://www.go90.com/profiles/va_383197d4efb445408f582c56397c379f

Thanks!

**Comment by yan12125** [comment] 2016-11-08 03:49
Duplicate of #10127. Please follow that instead.

**Closed by yan12125** 2016-11-08 03:49 UTC
