### ISSUE TITLE
iqiyi error

### ISSUE THREAD

**Issue by Irving23** [rg3/youtube-dl#10206] opened 2016-08-01 06:57 UTC
➜  ~ youtube-dl  -vF http://www.iqiyi.com/v_19rrmdszvo.html\#vfrm\=2-3-0-1
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-vF', u'http://www.iqiyi.com/v_19rrmdszvo.html#vfrm=2-3-0-1']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.30
[debug] Python version 2.7.10 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.0.2, ffprobe 3.0.2
[debug] Proxy map: {}
[iqiyi] temp_id: download video page
[iqiyi] 4d7af00026e9ecb1e90d4066a3f51cea: Downloading JSON metadata
ERROR: Unable to load data. Error code: A00110; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 682, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/iqiyi.py", line 356, in _real_extract
    raise ExtractorError('Unable to load data. Error code: ' + raw_data['code'])
ExtractorError: Unable to load data. Error code: A00110; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment] 2016-08-01 06:59
Thanks for the report. It's a duplicate of  #10088.

**Closed by yan12125** 2016-08-01 06:59 UTC
