### ISSUE TITLE
--dateafter is looping through the entire array of videos.

### ISSUE THREAD

**Issue by Mazeto** [rg3/youtube-dl#12407] opened 2017-03-09 03:15 UTC
# --dateafter bug/feature request.

Issue #12407

In this example I'm pasting the output when I've already downloaded two videos. Regardless.
The bug/feature-request is, the videos list is in chronological order, from newer to older. If the first video out of the date range is found, youtube-dl should break the loop. In this example the channel has 1206 videos. youtube-dl doesn't need to check every single one. It would take forever.

Can someone (who knows the code base better than me) find a way to break the loop when the first video out of the range is found && only break it if the video list is in chronological order? 'Cos I imagine some sources doesn't provide the videos list in chronological order, if that's the reason why youtube-dl loops through every single one.

Thanks in advance.

    > youtube-dl -f 18 --dateafter now-1day https://m.youtube.com/user/scishow
    [youtube:user] scishow: Downloading channel page
    [youtube:playlist] UUZYTClx2T1of7BRZ86-8fow: Downloading webpage
    [download] Downloading playlist: Uploads from SciShow
    [youtube:playlist] UUZYTClx2T1of7BRZ86-8fow: Downloading page #1
    [youtube:playlist] UUZYTClx2T1of7BRZ86-8fow: Downloading page #2
    [youtube:playlist] UUZYTClx2T1of7BRZ86-8fow: Downloading page #3
    [youtube:playlist] UUZYTClx2T1of7BRZ86-8fow: Downloading page #4
    [youtube:playlist] UUZYTClx2T1of7BRZ86-8fow: Downloading page #5
    [youtube:playlist] UUZYTClx2T1of7BRZ86-8fow: Downloading page #6
    [youtube:playlist] UUZYTClx2T1of7BRZ86-8fow: Downloading page #7
    [youtube:playlist] UUZYTClx2T1of7BRZ86-8fow: Downloading page #8
    [youtube:playlist] UUZYTClx2T1of7BRZ86-8fow: Downloading page #9
    [youtube:playlist] UUZYTClx2T1of7BRZ86-8fow: Downloading page #10
    [youtube:playlist] UUZYTClx2T1of7BRZ86-8fow: Downloading page #11
    [youtube:playlist] UUZYTClx2T1of7BRZ86-8fow: Downloading page #12
    [youtube:playlist] UUZYTClx2T1of7BRZ86-8fow: Downloading page #13
    [youtube:playlist] playlist Uploads from SciShow: Downloading 1206 videos
    [download] Downloading video 1 of 1206
    [youtube] 4uqTwY_CjOA: Downloading webpage
    [youtube] 4uqTwY_CjOA: Downloading video info webpage
    [youtube] 4uqTwY_CjOA: Extracting video information
    [youtube] 4uqTwY_CjOA: Downloading MPD manifest
    [download] Deep Sea Microbiome - SciShow Talk Show-4uqTwY_CjOA.mp4 has already been downloaded

    [download] 100% of 64.22MiB
    [download] Downloading video 2 of 1206
    [youtube] mQG4aJF_B3E: Downloading webpage
    [youtube] mQG4aJF_B3E: Downloading video info webpage
    [youtube] mQG4aJF_B3E: Extracting video information
    [youtube] mQG4aJF_B3E: Downloading MPD manifest
    [download] Can Hanging Upside Down Kill You-mQG4aJF_B3E.mp4 has already been downloaded

    [download] 100% of 7.05MiB
    [download] Downloading video 3 of 1206
    [youtube] Vr_jkORTbBs: Downloading webpage
    [youtube] Vr_jkORTbBs: Downloading video info webpage
    [youtube] Vr_jkORTbBs: Extracting video information
    [youtube] Vr_jkORTbBs: Downloading MPD manifest
    [download] 2017-03-06 upload date is not in range 2017-03-07 - 9999-12-31
    [download] Downloading video 4 of 1206
    [youtube] 8I_VpC6IuJs: Downloading webpage
    [youtube] 8I_VpC6IuJs: Downloading video info webpage
    [youtube] 8I_VpC6IuJs: Extracting video information
    [youtube] 8I_VpC6IuJs: Downloading MPD manifest
    [download] 2017-03-05 upload date is not in range 2017-03-07 - 9999-12-31

**Comment by dstftw** [comment] 2017-03-09 03:25
Duplicate of #1502.

**Closed by dstftw** 2017-03-09 03:25 UTC
