### ISSUE TITLE
Download mp3 with constant bitrate @ 320 Kbps

### ISSUE THREAD

**Issue by prashantkamdar** [rg3/youtube-dl#12084] opened 2017-02-11 12:54 UTC
Hello,

After going through the instructions, I found the below command best to my needs:

`youtube-dl --extract-audio --audio-format mp3 --audio-quality 0 <video URL>`

However, with the above, the bitrate mode is always Variable & bit rate is 256 Kbps,

How do I get to constant bitrate with 320 Kbps audio mp3?

**Comment by yan12125** [comment] 2017-02-11 12:56
Duplicate of #11032. It's not implemented yet

**Closed by yan12125** 2017-02-11 12:56 UTC
