### ISSUE TITLE
[youtube] Youtube-dl don't catch live streams from the specified channel

### ISSUE THREAD

**Issue by marabu88** [rg3/youtube-dl#19105] opened 2019-02-02 16:01 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.30.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.30.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---
Problem concerns live video for a particular channel. I chose a channel that broadcasts live video around the clock to make it easier to check for a problem.

If you open the URL in the browser https://www.youtube.com/channel/UCjzHeG1KWoonmf9d5KBvSiw/videos?flow=grid&view=2, then only those videos that are broadcast live will be displayed.

If you try to download these videos using the same URL, then we will get this:

```
youtube-dl https://www.youtube.com/channel/UCjzHeG1KWoonmf9d5KBvSiw/videos?flow=grid&view=2
[youtube:channel] UCjzHeG1KWoonmf9d5KBvSiw: Downloading channel page
[youtube:playlist] UUjzHeG1KWoonmf9d5KBvSiw: Downloading webpage
[download] Downloading playlist: Uploads from Soothing Relaxation
[youtube:playlist] UUjzHeG1KWoonmf9d5KBvSiw: Downloading page #1
[youtube:playlist] UUjzHeG1KWoonmf9d5KBvSiw: Downloading page #2
[youtube:playlist] UUjzHeG1KWoonmf9d5KBvSiw: Downloading page #3
[youtube:playlist] playlist Uploads from Soothing Relaxation: Downloading 331 videos
[download] Downloading video 1 of 331
[youtube] Wqx06DtYIZs: Downloading webpage...
```
Thus, the program will use some of its own method to determine which videos to download, instead of those that are displayed on a specific page. But what's worse - when using this method, the program skips the videos that are broadcast live. I do not know why, but it is.
 
I discovered this when I decided to try to download the channel where the live broadcast was. Even the number of videos found was less than what was displayed in the browser, since video with live streaming was not taken into account.

Ok. Youtube allows you to get a list of videos using RSS. I checked and there are live streams there.
Here is the link for the same channel: http://www.youtube.com/feeds/videos.xml?channel_id=UCjzHeG1KWoonmf9d5KBvSiw

Since I read that the download of RSS in youtube-dl has long been implemented, I can get live video feeds using this link. But this led to a strange error
```
youtube-dl --verbose http://www.youtube.com/feeds/videos.xml?channel_id=UCjzHeG1KWoonmf9d5KBvSiw
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'http://www.youtube.com/feeds/videos.xml?channel_id=UCjzHeG1KWoonmf9d5KBvSiw']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.01.30.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-89794-gc51301db14, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:user] feeds: Downloading channel page
WARNING: Unable to download webpage: HTTP Error 404: Not Found
[youtube:user] feeds: Downloading page #1
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp36zpl0n4\build\youtube_dl\extractor\common.py", line 605, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp36zpl0n4\build\youtube_dl\YoutubeDL.py", line 2215, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```
Why? After all, this page without any problems opens in the browser.

Perhaps there is some way to solve this problem (except using the filter search), but I did not find it. I also don’t understand why an error occurs when trying to use RSS. Among other things, I would like to use a filter to load only live streams.

**Comment by dstftw** [comment] 2019-02-02 16:11
Duplicate of #16212.

**Closed by dstftw** 2019-02-02 16:11 UTC

**Comment by dstftw** [comment] 2019-02-02 17:42
The roots of both issues are the same: the source URL is not used for extraction due to rationale explained in the issue linked.
As for RSS - open a new issue and don't mix multiple problems in single issue.
