### ISSUE TITLE
Substitution {} returns filename between single quotes in Windows instead of double quotes

### ISSUE THREAD

**Issue by marnunez** [rg3/youtube-dl#7161] opened 2015-10-13 13:40 UTC
For example, using `--exec "adb push {} /storage/sdcard1/"` executes `adb push 'filedir\filename' /storage/sdcard1/` instead of `adb push "filedir\filename" /storage/sdcard1/`. 
AFAIK, paths under Windows are resolved only with double quotes.

Using WinXP x32 and ytdl 2015.10.13

**Comment by dstftw** [comment] 2015-10-13 14:08
Duplicate of #5889.

**Closed by dstftw** 2015-10-13 14:08 UTC
