### ISSUE TITLE
dailymotion download videos error

### ISSUE THREAD

**Issue by emirbeytekin** [rg3/youtube-dl#6249] opened 2015-07-16 17:01 UTC
hello
i can't download any dailmotion videos in Turkey

error message: ERROR: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

my yotube dl is latest version

**Comment by dstftw** [comment] 2015-07-16 17:05
Duplicate of #6151.

**Closed by dstftw** 2015-07-16 17:05 UTC
