### ISSUE TITLE
Vevo Earlier Links Not Working

### ISSUE THREAD

**Issue by goldensun87** [rg3/youtube-dl#8936] opened 2016-03-22 05:38 UTC
Example url:

https://www.vevo.com/watch/carrie-underwood/Little-Toy-Guns/GBE431400013

This is what I get when I try it:

ERROR: Unable to download info: HTTP Error 500: Internal Server Error (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete o
utput.

File "youtube_dl\extractor\common.pyo", line 365, in _request_webpage
File "youtube_dl\YoutubeDL.pyo", line 1929, in urlopen
File "urllib2.pyo", line 437, in open
File "urllib2.pyo", line 550, in http_response
File "urllib2.pyo", line 475, in error
File "urllib2.pyo", line 409, in _call_chain
File "urllib2.pyo", line 558, in http_error_default

**Comment by dstftw** [comment] 2016-03-22 14:57
Duplicate of #8900.

**Closed by dstftw** 2016-03-22 14:57 UTC
