### ISSUE TITLE
prefer-free-formats does not work [Bug]

### ISSUE THREAD

**Issue by balkierode** [rg3/youtube-dl#6218] opened 2015-07-13 23:47 UTC
Even when this option is set, mp4 is preferred. When explicitly -f webm is used, webm is downloaded fine

**Comment by yan12125** [comment] 2015-07-14 06:51
Please provide verbose log [with ```-v```](https://github.com/rg3/youtube-dl#bugs). Your problem might be the same as #6018. See https://github.com/rg3/youtube-dl/issues/6018#issuecomment-113207850, which states how ```--prefer-free-formats``` works.

**Comment by balkierode** [comment] 2015-07-14 10:44
Thanks. Yes it is the same case as mentioned in other issue. I.e free formats are selected only if both nonfree and free formats have save quality.

**Comment by jaimeMF** [comment] 2015-07-14 10:52
Closing as a duplicate of that issue, thanks for the report.

**Closed by jaimeMF** 2015-07-14 10:52 UTC
