### ISSUE TITLE
extension of thumbnail embedding ?

### ISSUE THREAD

**Issue by abc123Kappa** [rg3/youtube-dl#12126] opened 2017-02-14 03:46 UTC
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.14*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.14**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

Just wondering if you guys plan on extending the thumbnail embedding to more file types like mkv/webm etc. because when using e.g. -f bestaudio+bestvideo the created container will never have a thumbnail which is really distracting in organized libraries 
It does say "for now" that's why I was wondering if it's still in the works.

"youtube_dl.postprocessor.embedthumbnail.EmbedThumbnailPPError: Only mp3 and m4a/ mp4 are supported for thumbnail embedding for now."

It does say "for now" that's why I was wondering if it's still in the works.

kind regards

**Comment by yan12125** [comment] 2017-02-22 16:32
> Just wondering if you guys plan on extending the thumbnail embedding to more file types like mkv/webm etc.

No ETA yet.

Close as that's a duplicate of #10359.

**Closed by yan12125** 2017-02-22 16:32 UTC

**Comment by svnpenn** [comment] 2018-02-18 22:56
http://github.com/rg3/youtube-dl/issues/11981

**Comment by svnpenn** [comment] 2018-02-18 22:59
http://github.com/rg3/youtube-dl/issues/12459

**Comment by svnpenn** [comment] 2018-02-18 23:01
http://github.com/rg3/youtube-dl/issues/6046

**Comment by svnpenn** [comment] 2018-02-18 23:02
http://github.com/rg3/youtube-dl/issues/8379

**Comment by svnpenn** [comment] 2018-02-18 23:04
https://github.com/rg3/youtube-dl/pull/15445
