### ISSUE TITLE
[youtube] Support for Unicode in titles? Cyrillic, Greek etc.

### ISSUE THREAD

**Issue by bryc** [rg3/youtube-dl#8641] opened 2016-02-23 02:40 UTC
There are some videos of these titles, which fail to save the name in the resultant file:

Юрий Бучма - Чернобыль, год спустя
Ηλίας Ασβεστόπουλος - Μου Μίλησαν
Виктор Вуячич - Несколько Первых Слов
Γιάννης Σπανός - Μοναξιά

Instead we get titles such as:

"   - -aiFG0KL28Fg.webm"
"  -  -cfFrSbZBtTA.m4a"
".  - -zVobKZbSSZ0.webm"

It would be nice if it does not lose the title when downloaded!

**Comment by dstftw** [comment] 2016-02-23 08:02
Duplicate of #5045.
This is intentional behavior for now. See #4787 for the rationale and #5527 for alternative solution discussions.

**Closed by dstftw** 2016-02-23 08:02 UTC
