### ISSUE TITLE
Skipping DASH manifest: (Download fails with 403 Forbidden)

### ISSUE THREAD

**Issue by streamradio** [rg3/youtube-dl#6688] opened 2015-08-26 21:25 UTC
When downloading youtube video "wkXKQmB1A60" ( and others ) I get the following Warning, and download fails with 403 Forbidden:

m@localhost:~$ wget -O /tmp/t.mp4 $(youtube-dl --verbose -g -f"best" wkXKQmB1A60)
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--prefer-insecure', u'-g', u'-fbest', u'wkXKQmB1A60']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.23
[debug] Python version 2.7.3 - Linux-3.2.0-64-virtual-x86_64-with-Ubuntu-12.04-precise
[debug] exe versions: avconv v12_dev0-355-g28396d1, avprobe v12_dev0-355-g28396d1, ffmpeg 0.8.17-4, ffprobe 0.8.17-4, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: [youtube] wkXKQmB1A60: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
https://r9---sn-5hne6nel.googlevideo.com/videoplayback?requiressl=yes&lmt=1419504323362806&dur=369.499&gcr=us&source=youtube&key=yt5&fexp=9406985%2C9408710%2C9409069%2C9415365%2C9415485%2C9416023%2C9416126%2C9417707%2C9418153%2C9418448&nh=IgpwcjA0LmFtczE1KgkxMjcuMC4wLjE&mime=video%2Fmp4&sparams=dur%2Cgcr%2Cid%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&ipbits=0&pl=46&ip=2a02%3A2770%3A5%3A0%3A21a%3A4aff%3Afe4f%3A2ec1&ms=au&mv=u&mt=1440623265&id=o-AMmlGeYQ6uMkKcw5y6e0mWBzJEjZSDslHHbTvpwcCUsu&mn=sn-5hne6nel&mm=31&sver=3&expire=1440645450&upn=pxLTW-RKnoI&itag=22&ratebypass=yes&
signature=E8FE96FFED3DF6F43E198C05228D977C9AD1AA64.C6E4DBE23A949A14A71E844497003FD1404176CD
Resolving r9---sn-5hne6nel.googlevideo.com (r9---sn-5hne6nel.googlevideo.com)... 2a00:1450:400e:2f::e, 173.194.153.174
Connecting to r9---sn-5hne6nel.googlevideo.com (r9---sn-5hne6nel.googlevideo.com)|2a00:1450:400e:2f::e|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-08-26 21:20:46 ERROR 403: Forbidden.

**Comment by dstftw** [comment] 2015-08-26 21:26
Duplicate of #6451. Remove cache with `youtube-dl --rm-cache-dir`.

**Closed by dstftw** 2015-08-26 21:26 UTC
