### ISSUE TITLE
I'm Facing this Issue: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)')

### ISSUE THREAD

**Issue by muhsayd** [rg3/youtube-dl#8697] opened 2016-02-29 11:11 UTC
youtube-dl --verbose 'https://www.youtube.com/watch?v=9SC1yabcz4k&list=PLbGagUibVvkj8HNSf1X76MJVBMJU7S5G2'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=9SC1yabcz4k&list=PLbGagUibVvkj8HNSf1X76MJVBMJU7S5G2']
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2016.02.27
[debug] Python version 2.7.9 - Darwin-15.3.0-x86_64-i386-64bit
[debug] exe versions: avconv present, avprobe present, ffmpeg 2.8.5, ffprobe 2.8.5, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist PLbGagUibVvkj8HNSf1X76MJVBMJU7S5G2 - add --no-playlist to just download video 9SC1yabcz4k
[youtube:playlist] PLbGagUibVvkj8HNSf1X76MJVBMJU7S5G2: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)> (caused by URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 355, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1905, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 831, in https_open
    req, **kwargs)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)

**Comment by yan12125** [comment] 2016-02-29 13:13
Looks like a duplicate of #5317. See https://github.com/rg3/youtube-dl/issues/5317#issuecomment-94205465 and https://github.com/rg3/youtube-dl/issues/5317#issuecomment-94214004 for workarounds. If things are still broken with these workarounds, please provide more information at #5317.

**Closed by yan12125** 2016-02-29 13:13 UTC
