### ISSUE TITLE
All Commands - Very Slow on Raspberry pi

### ISSUE THREAD

**Issue by acpadhi** [rg3/youtube-dl#6503] opened 2015-08-09 01:09 UTC
$ - time youtube-dl --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.06.1
[debug] Python version 2.7.3 - Linux-4.0.9+-armv6l-with-debian-7.8
[debug] exe versions: avconv 9.14-6, avprobe 9.14-6, ffmpeg 0.8.17-6
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

real	0m14.736s
user	0m13.200s
sys	0m0.930s

I was monitoring the top command, and while those 14 seconds elapsed, the python process shot upto 96% load for most of the time, and then finally a couple of seconds before the execution completed, youtube-dl entry in top was taking the same 96% load before the program final shows the above output.

Raspberry Pi Model B Rev 2

**Comment by acpadhi** [comment] 2015-08-09 01:13
FYI, also checked with this :

time youtube-dl --force-ipv4  --youtube-skip-dash-manifest --verbose 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--force-ipv4', u'--youtube-skip-dash-manifest', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.06.1
[debug] Python version 2.7.3 - Linux-4.0.9+-armv6l-with-debian-7.8
[debug] exe versions: avconv 9.14-6, avprobe 9.14-6, ffmpeg 0.8.17-6
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

real	0m14.818s
user	0m13.350s
sys	0m0.880s

**Comment by acpadhi** [comment] 2015-08-09 01:17
Running it on my Desktop, which is a Q6600 CPU with 8Gb ram and Ubuntu 14.04 is fast enough.

time youtube-dl --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.06.1
[debug] Python version 2.7.6 - Linux-3.13.0-61-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

real	0m0.876s
user	0m0.653s
sys	0m0.115s

**Comment by dstftw** [comment] 2015-08-09 01:23
Duplicate of #3029.

**Closed by dstftw** 2015-08-09 01:23 UTC
