### ISSUE TITLE
rtmpdump YouTube video

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#1797] opened 2013-11-19 20:03 UTC
Have not dealt this one of these rtmpdump youtube videos before...so I may be doing something wrong.

First time I got:
"ERROR: RTMP download detected but "rtmpdump" could not be run"

...so I put a copy of rtmpdump.exe in the same directory and now I get this:

C:\Transmogrifier>youtube-dl.py -v http://www.youtube.com/watch?v=Gbe0Baw1roA
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.youtube.com/watch?v=Gbe0Baw1roA']
[debug] youtube-dl version 2013.11.19
[debug] Python version 2.7.3 - Windows-7-6.1.7601-SP1
[debug] Proxy map: {}
[youtube] Setting language
[youtube] Gbe0Baw1roA: Downloading video webpage
[youtube] Gbe0Baw1roA: Downloading video info webpage
[youtube] Gbe0Baw1roA: Extracting video information
[youtube] RTMP download detected
[download] Destination: Hunger Games -  Catching Fire Movie Trailer #3 [HD]-Gbe0
Baw1roA.flv
[debug] rtmpdump command line: rtmpdump --verbose -r rtmpe://v22.nonxt2.c.youtub
e.com/videoplayback -o 'Hunger Games -  Catching Fire Movie Trailer #3 [HD]-Gbe0
Baw1roA.flv.part' --resume --skip 1
RTMPDump v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
DEBUG: Parsing...
DEBUG: Parsed protocol: 2
DEBUG: Parsed host    : v22.nonxt2.c.youtube.com
DEBUG: Parsed app     : videoplayback
DEBUG: Number of skipped key frames for resume: 1
ERROR: You must specify a playpath (--playpath) or url (-r "rtmp://host[:port]/p
laypath") containing a playpath
ERROR: unable to download video
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 773, in d
ownload
    videos = self.extract_info(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 421, in e
xtract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 502, in p
rocess_ie_result
    for r in ie_result['entries']
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 446, in p
rocess_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 535, in p
rocess_video_result
    self.process_info(info_dict)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 751, in p
rocess_info
    raise UnavailableVideoError(err)
UnavailableVideoError: [Error 2] The system cannot find the file specified: u'Hu
nger Games -  Catching Fire Movie Trailer #3 [HD]-Gbe0Baw1roA.flv.part'

Thanks as always...

**Comment by dstftw** [comment] 2016-06-12 17:06
Duplicate of #343.

**Closed by dstftw** 2016-06-12 17:06 UTC
Labels: bug
