### ISSUE TITLE
A way to pass additional arguments to rtmpdump?

### ISSUE THREAD

**Issue by zmobbie** [rg3/youtube-dl#10266] opened 2016-08-09 04:06 UTC
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.07*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

Add a way to pass additional arguments to rtmpdump.
E.g. I have a case, where i need to pass " -y mp4:k2hq/10/100/00818/0061.mp4:0_1 -R" to rtmpdump for it to be able to successfully download the media.

**Comment by yan12125** [comment] 2016-08-09 04:11
Currently it's impossible. Which video requires these options?

**Comment by zmobbie** [comment] 2016-08-09 04:14
this is the video stream where that argument will download at least a bit of video:  rtmp://kanal2-egress.cdn.mind.ee/kanal2vod/k2hq/10/100/00818/0061.mp4:0_1

**Comment by yan12125** [comment] 2016-08-09 04:26
Did you get this URL from some web page? ```-y```, which is an abbreviation of ```--playpath```, (roughly) indicates the full path to a video file. This information is usually available on the web page.

**Comment by zmobbie** [comment] 2016-08-09 04:30
i got it from a xml file([http://kanal2.postimees.ee/pluss/video/?id=20737](http://kanal2.postimees.ee/video/playerPlaylistApi?id=20737)), which i got in turn from here: [http://kanal2.postimees.ee/pluss/video/?id=20737](http://kanal2.postimees.ee/pluss/video/?id=20737)

**Comment by yan12125** [comment] 2016-08-09 04:45
Duplicate of #3651.
If you already know the playpath and the URL, you can use rtmpdump directly:
```
rtmpdump --verbose --playpath k2hq/10/100/00818/0061.mp4:0_0 -r rtmp://kanal2-egress.cdn.mind.ee:80/kanal2vod -o output.flv
```
What youtube-dl should do is parsing the XML. There's no need to provide an option to passing additional parameters in this case.

**Closed by yan12125** 2016-08-09 04:45 UTC

**Comment by zmobbie** [comment] 2016-08-09 04:57
sorry if i forgot to mention but i'm making a script, and that's where i need to pass additional arguemnts to rtmpdump

```
        video_id = self._match_id(url)
        xmlfile = self._download_xml(update_url_query('http://kanal2.postimees.ee/video/playerPlaylistApi', {'id': video_id}), video_id)
        
        title = xpath_text(xmlfile, './playlist/video/name')
        
        for stream in xmlfile.findall('./playlist/video/streamItems/streamItem'):
          url = xmlfile.find('./playlist/video/streamItems').get('host') + stream.get('streamName').replace('k2lq','k2hq')#.replace(':0_1','')
          break
        
        return {
            'id': video_id,
            'title': title,
            'url': url,
            'rtmpdumpargs': " -y mp4:k2hq/10/100/00818/0061.mp4:0_1 -R" }
```

notice the last line of code, that's the thing i don't find any way to do

**Comment by yan12125** [comment] 2016-08-09 05:00
Oh, you need:
```
'play_path': 'mp4:k2hq/10/100/00818/0061.mp4:0_1',
'rtmp_real_time': True,
```
See ```youtube_dl/downloader/rtmp.py``` for more possible parameters.

**Comment by zmobbie** [comment] 2016-08-09 05:05
Thanks, I was looking at that file before but must've looked over these
