### ISSUE TITLE
Can we get subtitles on CBS?

### ISSUE THREAD

**Issue by jimbolaya** [rg3/youtube-dl#7389] opened 2015-11-06 20:26 UTC
I am currently running youtube-dl version 2015.11.02.

After trying to download CC/Subtitles on CBS I get a "has no subtitles" message.
```
$ youtube-dl --list-subs 'http://www.cbs.com/shows/supergirl/video/92C4EB54-8372-A474-3F03-8CA1385134F3/supergirl-pilot/'
[CBS] supergirl-pilot: Downloading webpage
[ThePlatform] wj9VAZWduGZe: Downloading SMIL data
[ThePlatform] wj9VAZWduGZe: Downloading JSON metadata
wj9VAZWduGZe has no subtitles
```
After taking a look at the "Console" in Firefox, the subtitles are available in XML (TTML) as a separate file. For instance, for this show, the subtitles are availabe at 
```
wget http://www.cbsstatic.com/closedcaption/Current/Primetime/DFXP/CBS_SUPERGIRL_101_CONTENT_CIAN_caption_DFXP.xml
```
Looking at the "--verbose" output "CBS_SUPERGIRL_101_CONTENT_CIAN" shows up repeatedly. I've posted the "--verbose" output at:
https://gist.github.com/jimbolaya/c5881f856db780bc0147

**Comment by jaimeMF** [comment] 2015-11-06 21:03
Duplicate of #6321.

**Closed by jaimeMF** 2015-11-06 21:03 UTC
