### ISSUE TITLE
[YouTube] HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by ArchCarrier** [rg3/youtube-dl#6588] opened 2015-08-17 09:45 UTC
Since updating to the latest version, I get a lot of errors trying to download from Youtube:
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-x', u'https://www.youtube.com/watch?v=bxjw_8RpoNI', u'-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.08.16.1
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-70411-g7da7d26, ffprobe N-70411-g7da7d26, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] bxjw_8RpoNI: Downloading webpage
[youtube] bxjw_8RpoNI: Downloading video info webpage
[youtube] bxjw_8RpoNI: Extracting video information
[youtube] {22} signature length 40.42, html5 player new
[youtube] {43} signature length 40.42, html5 player new
[youtube] {18} signature length 40.42, html5 player new
[youtube] {5} signature length 40.42, html5 player new
[youtube] {36} signature length 40.42, html5 player new
[youtube] {17} signature length 40.42, html5 player new
[youtube] {137} signature length 40.42, html5 player new
[youtube] {248} signature length 40.42, html5 player new
[youtube] {136} signature length 40.42, html5 player new
[youtube] {247} signature length 40.42, html5 player new
[youtube] {135} signature length 40.42, html5 player new
[youtube] {244} signature length 40.42, html5 player new
[youtube] {134} signature length 40.42, html5 player new
[youtube] {243} signature length 40.42, html5 player new
[youtube] {133} signature length 40.42, html5 player new
[youtube] {242} signature length 40.42, html5 player new
[youtube] {160} signature length 40.42, html5 player new
[youtube] {278} signature length 40.42, html5 player new
[youtube] {140} signature length 40.42, html5 player new
[youtube] {171} signature length 40.42, html5 player new
[youtube] {249} signature length 40.42, html5 player new
[youtube] {250} signature length 40.42, html5 player new
[youtube] {251} signature length 40.42, html5 player new
[youtube] bxjw_8RpoNI: Downloading DASH manifest
WARNING: [youtube] bxjw_8RpoNI: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[debug] Invoking downloader on u'https://r16---sn-5hnednel.googlevideo.com/videoplayback?clen=4060730&key=yt5&sver=3&requiressl=yes&gir=yes&nh=IgpwcjAyLmFtczE2KgkxMjcuMC4wLjE&sparams=clen%2Cdur%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&mt=1439797792&expire=1439819462&lmt=1438962889419816&upn=P71lrLnNvqw&initcwndbps=2231250&id=o-ACaAxzckRGQRU8cpWArGrHuqA5qKGrUUZi-FRVPDeSWh&pl=19&dur=258.641&mime=audio%2Fwebm&ms=au&source=youtube&mv=m&mm=31&ipbits=0&mn=sn-5hnednel&itag=251&keepalive=yes&gcr=nl&fexp=9405348%2C9406004%2C9406851%2C9407155%2C9408372%2C9408486%2C9408710%2C9409069%2C9412515%2C9415365%2C9415485%2C9416023%2C9416126%2C9416338%2C9416574%2C9416729%2C9417430%2C9417707%2C9418133%2C9418153%2C9418335%2C9419301&ip=94.214.248.224&signature=2F58F49F66389A99E03FA6672FBC7FF40804136E.B740A21A3057758FA4B8F5625E521390BA0940E8&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1585, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1527, in dl
  File "youtube_dl\downloader\common.pyo", line 342, in download
  File "youtube_dl\downloader\http.pyo", line 60, in real_download
  File "youtube_dl\YoutubeDL.pyo", line 1860, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default
HTTPError: HTTP Error 403: Forbidden
```

**Comment by BruceWouaigne** [comment] 2015-08-17 09:53
I've got pretty much the same problem since a few day

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-x', u'--audio-format', u'mp3', u'--audio-quality', u'0', u'-o', u'/tmp/D8cf5F66.%(ext)s', u'https://www.youtube.com/watch?v=HNuSD49chY8']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out None, pref ANSI_X3.4-1968
[debug] youtube-dl version 2015.08.16.1
[debug] Python version 2.7.6 - Linux-3.13.0-45-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6
[debug] Proxy map: {} WARNING:
[youtube] HNuSD49chY8: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',) ERROR: unable to download video data: HTTP Error 403: Forbidden Traceback (most recent call last):   File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1585, in process_info     success = dl(filename, info_dict)   File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1527, in dl     return fd.download(name, info)   File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 342, in download     return self.real_download(filename, info_dict)   File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 60, in real_download     data = self.ydl.urlopen(request)   File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1860, in urlopen     return self._opener.open(req, timeout=self._socket_timeout)   File "/usr/lib/python2.7/urllib2.py", line 410, in open     response = meth(req, response)   File "/usr/lib/python2.7/urllib2.py", line 523, in http_response     'http', request, response, code, msg, hdrs)   File "/usr/lib/python2.7/urllib2.py", line 448, in error     return self._call_chain(*args)   File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain     result = func(*args)   File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp) HTTPError: HTTP Error 403: Forbidden
```

**Comment by yan12125** [comment] 2015-08-17 09:55
A duplicate of #6451.

**Closed by yan12125** 2015-08-17 09:55 UTC
