### ISSUE TITLE
some adultswing.com download not working

### ISSUE THREAD

**Issue by treaki** [rg3/youtube-dl#11262] opened 2016-11-22 04:20 UTC
```
youtube-dl --verbose http://www.adultswim.com/videos/rick-and-morty/season-3-exclusive-san-diego-comic-con-2016/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.adultswim.com/videos/rick-and-morty/season-3-exclusive-san-diego-comic-con-2016/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.18
[debug] Python version 2.7.9 - Linux-4.2.0-0.bpo.1-amd64-x86_64-with-debian-8.6
[debug] exe versions: ffmpeg 2.8.8, ffprobe 2.8.8, rtmpdump 2.4
[debug] Proxy map: {}
[AdultSwim] season-3-exclusive-san-diego-comic-con-2016: Downloading webpage
ERROR: Unable to extract bootstraped data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/adultswim.py", line 152, in _real_extract
    r'var bootstrappedData = ({.*});', webpage, 'bootstraped data'), episode_path)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 660, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract bootstraped data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

**Comment by yan12125** [comment] 2016-11-22 04:25
Duplicate of #11042

**Closed by yan12125** 2016-11-22 04:25 UTC
