### ISSUE TITLE
Unsupported liveleak URL embedded from youtube

### ISSUE THREAD

**Issue by dspstudio** [rg3/youtube-dl#9165] opened 2016-04-12 06:21 UTC
[root@host1 ~]$ youtube-dl -g http://www.liveleak.com/view?i=635_1460430558
ERROR: Unable to extract embed URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[root@host1 ~]$ youtube-dl -U
youtube-dl is up-to-date (2016.04.06)
[root@host1 ~]$ youtube-dl -g http://www.liveleak.com/view?i=635_1460430558 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-g', u'http://www.liveleak.com/view?i=635_1460430558', u'--verbose']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2016.04.06
[debug] Python version 2.7.5 - Linux-2.6.32-042stab104.1-x86_64-with-centos-7.2.1511-Core
[debug] exe versions: avconv 10.1, avprobe 10.1
[debug] Proxy map: {}
ERROR: Unable to extract embed URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 669, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 323, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/liveleak.py", line 79, in _real_extract
    webpage, 'embed URL')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 627, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract embed URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment] 2017-02-16 19:15
Duplicate of #7506

**Closed by yan12125** 2017-02-16 19:15 UTC
