### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by djrosu** [rg3/youtube-dl#6540] opened 2015-08-12 18:26 UTC
C:>youtube-dl --verbose -f 137+140 hT_nvWreIhg
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-f', u'137+140', u'hT_nvWreIhg']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.08.09
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-65710-g96d2178
[debug] Proxy map: {}
[youtube] hT_nvWreIhg: Downloading webpage
[youtube] hT_nvWreIhg: Downloading video info webpage
[youtube] hT_nvWreIhg: Extracting video information
[youtube] {22} signature length 40.42, html5 player new
[youtube] {43} signature length 40.42, html5 player new
[youtube] {18} signature length 40.42, html5 player new
[youtube] {5} signature length 40.42, html5 player new
[youtube] {36} signature length 40.42, html5 player new
[youtube] {17} signature length 40.42, html5 player new
[youtube] {137} signature length 40.42, html5 player new
[youtube] {248} signature length 40.42, html5 player new
[youtube] {136} signature length 40.42, html5 player new
[youtube] {247} signature length 40.42, html5 player new
[youtube] {135} signature length 40.42, html5 player new
[youtube] {244} signature length 40.42, html5 player new
[youtube] {134} signature length 40.42, html5 player new
[youtube] {243} signature length 40.42, html5 player new
[youtube] {133} signature length 40.42, html5 player new
[youtube] {242} signature length 40.40, html5 player new
[youtube] {160} signature length 40.42, html5 player new
[youtube] {278} signature length 40.42, html5 player new
[youtube] {140} signature length 40.42, html5 player new
[youtube] {171} signature length 40.42, html5 player new
[youtube] {249} signature length 40.42, html5 player new
[youtube] {250} signature length 40.42, html5 player new
[youtube] {251} signature length 40.42, html5 player new
[youtube] hT_nvWreIhg: Downloading DASH manifest
WARNING: [youtube] hT_nvWreIhg: Skipping DASH manifest: ExtractorError(u'Could n
ot download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); pl
ease report this issue on https://yt-dl.org/bug . Make sure you are using the la
test version; type  youtube-dl -U  to update. Be sure to call youtube-dl with th
e --verbose flag and include its complete output.',)
[debug] Invoking downloader on u'https://r2---sn-fvf-jhie.googlevideo.com/videop
layback?fexp=9406000%2C9408136%2C9408710%2C9415365%2C9415485%2C9416023%2C9416126
%2C9417121%2C9417600%2C9418153%2C9418494%2C9419047%2C9419238%2C9419300&sver=3&ke
epalive=yes&sparams=clen%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ck
eepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Crequiressl%2Csource%2
Cupn%2Cexpire&requiressl=yes&clen=76962583&lmt=1434107032380195&initcwndbps=3052
500&key=yt5&ms=au&id=o-ALdXhUH4Bu4O15Hcl9rLf5hoxftgT3pBEKF_2tMGJRlm&pl=22&mv=m&m
t=1439403806&gir=yes&ip=67.149.212.48&mn=sn-fvf-jhie&mm=31&source=youtube&upn=DP
FeBXmDkDo&itag=137&ipbits=0&mime=video%2Fmp4&expire=1439425505&dur=283.032&pcm2c
ms=yes&signature=15C12DDC1ADD967C1A772D236CB432BB7061C0A3.7D3FD1F657C87D0E7EF0E8
7EAE560C1E89C38315&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1579, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1527, in dl
  File "youtube_dl\downloader\common.pyo", line 342, in download
  File "youtube_dl\downloader\http.pyo", line 60, in real_download
  File "youtube_dl\YoutubeDL.pyo", line 1860, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default
HTTPError: HTTP Error 403: Forbidden

**Comment by dstftw** [comment] 2015-08-12 18:31
Run `youtube-dl --rm-cache-dir`.
Duplicate of #6451.

**Closed by dstftw** 2015-08-12 18:31 UTC
