### ISSUE TITLE
youtube-dl no longer downloads videos from NBC.com. Please help!

### ISSUE THREAD

**Issue by RogerRogerK** [rg3/youtube-dl#14198] opened 2017-09-14 04:12 UTC
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.11**

- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
command = youtube-dl -F https://www.nbc.com/chicago-pd/video/chicago-pd-season-5-preview/3582703 -v

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-F', u'https://www.nbc.com/chicago-pd/video/chicago-pd-season-5-preview/3582703', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.11
[debug] Python version 2.7.12 - Linux-4.10.0-33-generic-x86_64-with-LinuxMint-18.2-sonya
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[NBC] 3582703: Downloading JSON metadata
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1966, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/nbc.py", line 78, in _real_extract
IndexError: list index out of range

...
<end of log>
```

---

youtube-dl is currently unable to download videos from nbc.com. I know for a fact that this site used to be supported, as I have downloaded from it before, but as of September 1, 2017, I have been unable to make it work.

Please note that I have no ill intentions for downloading from this site; I merely wish to view TV episodes on my old mobile phone, which runs Symbian OS and does not support the Android NBC app.

I really appreciate this wonderful tool, youtube-dl, that you provide.

**Comment by remitamine** [comment] 2017-09-14 06:41
Duplicate of #13651.

**Closed by remitamine** 2017-09-14 06:41 UTC

**Comment by dashxdr** [comment] 2018-02-08 05:05
youtube-dl "http://www.nbc.com/saturday-night-live/video/martha-stewarts-mothers-day/2870471?snl=1"
fails on my setup with
[mp4 @ 0x108efc0] Malformed AAC bitstream detected: use the audio bitstream filter 'aac_adtstoasc' to fix it ('-bsf:a aac_adtstoasc' option with ffmpeg)
I fixed it by adding --prefer-ffmpeg to the youtube-dl command
youtube-dl --prefer-ffmpeg ...

**Comment by davidharneyhi** [comment] 2018-10-16 08:32
Now youtube-dl has update to support nbc.
Another method is to use Allavsoft with this guide https://www.allavsoft.com/how-to/download-nbc-videos.html
