### ISSUE TITLE
A way to specify format preferences on a per-site basis?

### ISSUE THREAD

**Issue by nick-s-b** [rg3/youtube-dl#7854] opened 2015-12-13 04:51 UTC
Guys,
Is there a way to record my preferences on which formats I prefer from specific sites? For example, when downloading from YT, I'd like youtube-dl to automatically download the format that I prefer. Same goes for multitude of other sites. I know that youtube-dl selects "best" by default but some videos are then huge. Is there a way to do specify in a config file which format should be downloaded from which site so I don't have to specify it on a command line every time?

Thanks!

**Comment by dstftw** [comment] 2015-12-13 04:53
No. Duplicate of #3101.

**Closed by dstftw** 2015-12-13 04:53 UTC
