### ISSUE TITLE
Youku.com : Unable to download JSON metadata

### ISSUE THREAD

**Issue by gam2046** [rg3/youtube-dl#7838] opened 2015-12-11 06:10 UTC
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-F', u'http://v.youku.com/v_show/id_XMTE0ODUxODA4.html']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2015.12.10
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-63946-g10012fa
[debug] Proxy map: {}
[youku] XMTE0ODUxODA4: Downloading JSON metadata 1
ERROR: Unable to download JSON metadata: [Errno 10054]  (caused by error(10054, '')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "youtube_dl\extractor\common.pyo", line 329, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1884, in urlopen
  File "urllib2.pyo", line 431, in open
  File "urllib2.pyo", line 449, in _open
  File "urllib2.pyo", line 409, in _call_chain
  File "youtube_dl\utils.pyo", line 701, in http_open
  File "urllib2.pyo", line 1200, in do_open
  File "httplib.pyo", line 1132, in getresponse
  File "httplib.pyo", line 453, in begin
  File "httplib.pyo", line 409, in _read_status
  File "socket.pyo", line 480, in readline
```

**Comment by yan12125** [comment] 2015-12-11 06:12
Duplicate of #7627. You may want to try my partly working version proposed at https://github.com/rg3/youtube-dl/issues/7627#issuecomment-163850594.

**Closed by yan12125** 2015-12-11 06:12 UTC
