### ISSUE TITLE
Youporn scraper broken

### ISSUE THREAD

**Issue by k0nr4d** [rg3/youtube-dl#7050] opened 2015-10-03 06:13 UTC
* [www]# youtube-dl --verbose http://www.youporn.com/watch/11823025/old-man-fuck-nice-teenage/
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.youporn.com/watch/11823025/old-man-fuck-nice-teenage/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.28
[debug] Python version 2.6.6 - Linux-2.6.32-504.16.2.el6.x86_64-x86_64-with-centos-6.7-Final
[debug] exe versions: ffmpeg 0.10.15, ffprobe 0.10.15
[debug] Proxy map: {}
[YouPorn] 11823025: Downloading webpage
ERROR: Unable to extract JSON parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 288, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youporn.py", line 52, in _real_extract
    webpage, 'JSON parameters')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 582, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract JSON parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment] 2015-10-03 17:27
Duplicate of #6888.

**Closed by dstftw** 2015-10-03 17:27 UTC
