### ISSUE TITLE
SkillsMatter Video not Downloading

### ISSUE THREAD

**Issue by psibi** [rg3/youtube-dl#6219] opened 2015-07-14 03:33 UTC
Youtube-dl version I'm using:

```
$ youtube-dl --version
2015.07.07
```

I'm trying to download a video from skillsmatter. But it's not getting downloaded. Skillsmatter internally uses Vimeo.

Video URL: https://skillsmatter.com/skillscasts/4251-lenses-compositional-data-access-and-manipulation

```
$ youtube-dl --verbose https://skillsmatter.com/skillscasts/4251-lenses-compositional-data-access-and-manipulation
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://skillsmatter.com/skillscasts/4251-lenses-compositional-data-access-and-manipulation']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.07
[debug] Python version 2.7.6 - Linux-3.16.0-30-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 11.3, avprobe 11.3, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 4251-lenses-compositional-data-access-and-manipulation: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 4251-lenses-compositional-data-access-and-manipulation: Downloading webpage
[generic] 4251-lenses-compositional-data-access-and-manipulation: Extracting information
ERROR: Unsupported URL: https://skillsmatter.com/skillscasts/4251-lenses-compositional-data-access-and-manipulation
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 1092, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/utils.py", line 1562, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 22, column 312
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 654, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 1663, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL:
https://skillsmatter.com/skillscasts/4251-lenses-compositional-data-access-and-manipulation
```

**Comment by yan12125** [comment] 2015-07-14 06:33
FYI: SkillsMatter is not supported yet.

**Comment by psibi** [comment] 2015-07-14 06:54
@yan12125 SkillsMater uses Vimeo.

**Comment by yan12125** [comment] 2015-07-14 07:41
Logging in is not implemented yet, and seems video URLs are available only if logged in.

**Comment by dstftw** [comment] 2017-01-07 17:26
Duplicate of #1883.

**Closed by dstftw** 2017-01-07 17:26 UTC
Labels: site-support-request
