### ISSUE TITLE
'urgent issue' - Playback on other websites has been disabled by the video owner

### ISSUE THREAD

**Issue by CiscoPress** [rg3/youtube-dl#4627] opened 2015-01-03 20:46 UTC
It's the first time I see such message. I searched issues and found no other.

Would be great if you fix that fast.

> youtube-dl 'https://www.youtube.com/watch?v=TfscjnE2MWM'
[youtube] TfscjnE2MWM: Downloading webpage
[youtube] TfscjnE2MWM: Downloading embed webpage
[youtube] TfscjnE2MWM: Refetching age-gated info webpage
ERROR: TfscjnE2MWM: YouTube said: <a href="http://www.youtube.com/watch?v=TfscjnE2MWM&feature=player_embedded" target="_blank">Watch this video on YouTube.</a><br/>Playback on other websites has been disabled by the video owner.

> youtube-dl -v
[debug] System config: ['-t', '--restrict-filenames']
[debug] User config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.02
[debug] Python version 2.7.6 - Darwin-14.0.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.5.2, ffprobe 2.5.2, rtmpdump 2.4
[debug] Proxy map: {'http': 'http://localhost:8118', 'https': 'http://localhost:8118'}
Usage: youtube-dl [OPTIONS] URL [URL...]
youtube-dl: error: you must provide at least one URL

do you know any workaround for download?

> youtube-dl -g 'https://www.youtube.com/watch?v=TfscjnE2MWM' --user-agent "Mozilla/5.0 (Windows NT 6.3; rv:36.0) Gecko/20100101 Firefox/36.0"
ERROR: TfscjnE2MWM: YouTube said: <a href="http://www.youtube.com/watch?v=TfscjnE2MWM&feature=player_embedded" target="_blank">Watch this video on YouTube.</a><br/>Playback on other websites has been disabled by the video owner.

**Comment by jaimeMF** [comment] 2015-01-03 21:12
Duplicate of #4162, you could try using your youtube account with the `--username` option.

**Closed by jaimeMF** 2015-01-03 21:12 UTC

**Comment by CiscoPress** [comment] 2015-01-03 21:21
thanks. Works. 

here a short howto:

> youtube-dl -n 'https://www.youtube.com/watch?v=TfscjnE2MWM'
[youtube] Downloading login page
[youtube] Logging in
[youtube] TfscjnE2MWM: Downloading webpage
[youtube] TfscjnE2MWM: Extracting video information
[youtube] TfscjnE2MWM: Downloading DASH manifest
[download] Destination: drunk_girl_pee_+18-TfscjnE2MWM.mp4
[download] 100% of 2.41MiB in 00:01

> cat .netrc 
machine youtube
	login xxx@gmail.com
	password xxx

**Comment by ToWatchList** [comment] 2015-02-11 22:12
To add to CiscoPress's howto, here's some info on the [.netrc file format](http://www.mavetju.org/unix/netrc.php) which youtube-dl will use when given the `-n` flag.  Basically it's a plaintext folder in your home directory with the username and password needed.

Make sure you set the privileges with `chmod 600 ~/.netrc`

**Comment by zenaan** [comment] 2015-04-03 04:29
Doesn't work for me (TM)(C)(R):

$ cat ~/.netrc
machine youtube
login blah@gmail.com
password blahblah

$ youtube-dl -v http://www.youtube.com/watch?v=_ujz8dY7EAE
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=_ujz8dY7EAE']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.28
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.0
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[youtube] _ujz8dY7EAE: Downloading webpage
[youtube] _ujz8dY7EAE: Downloading embed webpage
[youtube] _ujz8dY7EAE: Refetching age-gated info webpage
ERROR: _ujz8dY7EAE: YouTube said: <a href="http://www.youtube.com/watch?v=_ujz8dY7EAE&feature=player_embedded" target="_blank">Watch this video on YouTube.</a><br/>Playback on other websites has been disabled by the video owner.
Traceback (most recent call last):
  File "/home/justa/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 651, in extract_info
    ie_result = ie.extract(url)
  File "/home/justa/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/home/justa/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 878, in _real_extract
    expected=True, video_id=video_id)
ExtractorError: _ujz8dY7EAE: YouTube said: <a href="http://www.youtube.com/watch?v=_ujz8dY7EAE&feature=player_embedded" target="_blank">Watch this video on YouTube.</a><br/>Playback on other websites has been disabled by the video owner.

Happy to run any further tests required.

**Comment by CiscoPress** [comment] 2015-04-03 04:41
User "-n" argument

> youtube-dl --help | grep netrc                         
    -n, --netrc                      use .netrc authentication data

**Comment by m-porto** [comment] 2015-07-26 12:31
-n argument does not work for me

$ cat ~/.netrc
machine youtube
login xxxx@gmail.com
password xxxx


$ youtube-dl -n -c -v "https://www.youtube.com/watch?v=_ujz8dY7EAE"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-n', u'-c', u'-v', u'https://www.youtube.com/watch?v=_ujz8dY7EAE']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.21
[debug] Python version 2.7.10 - Linux-3.16.0-4-amd64-x86_64-with-debian-stretch-sid
[debug] exe versions: avconv 2.6.2, avprobe 2.6.2, ffmpeg 2.6.2, ffprobe 2.6.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Logging in
[youtube] _ujz8dY7EAE: Downloading webpage
[youtube] _ujz8dY7EAE: Downloading embed webpage
[youtube] _ujz8dY7EAE: Refetching age-gated info webpage
ERROR: _ujz8dY7EAE: YouTube said: <a href="http://www.youtube.com/watch?v=_ujz8dY7EAE&feature=player_embedded" target="_blank">Watch this video on YouTube.</a><br/>Playback on other websites has been disabled by the video owner.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 656, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 985, in _real_extract
    expected=True, video_id=video_id)
ExtractorError: _ujz8dY7EAE: YouTube said: <a href="http://www.youtube.com/watch?v=_ujz8dY7EAE&feature=player_embedded" target="_blank">Watch this video on YouTube.</a><br/>Playback on other websites has been disabled by the video owner.

**Comment by CiscoPress** [comment] 2015-07-26 15:38
are you on a *NIX system?
what are the perms of .netrc?

**Comment by m-porto** [comment] 2015-08-09 20:12
Debian testing. File permissions for .netrc: 600, running the program with the same user who is owner of the file. And using a valid login and password (I can watch the video on the browser)
I updated to last version (2015.08.09) with the same result

**Comment by gnaag** [comment] 2016-01-19 14:56
The solution no longer works for me. For video https://www.youtube.com/watch?v=UNDIrIyvQFk I have passed login through .netrc (It worked), but still it claims I cannot download the video due to owner's restrictions on embedding.
<pre>
youtube-dl -n https://www.youtube.com/watch?v=UNDIrIyvQFk
[youtube] Downloading login page
[youtube] Logging in
Type 2-step verification code and press [Return]: 
[youtube] Submitting TFA code
[youtube] UNDIrIyvQFk: Downloading webpage
[youtube] UNDIrIyvQFk: Downloading embed webpage
[youtube] UNDIrIyvQFk: Refetching age-gated info webpage
ERROR: UNDIrIyvQFk: YouTube said: <a href="http://www.youtube.com/watch?v=UNDIrIyvQFk&feature=player_embedded" target="_blank">Watch this video on YouTube.</a><br/>Playback on other websites has been disabled by the video owner.
</pre>
