### ISSUE TITLE
[req] digitaltutors.com (sister site of pluralsight.com)

### ISSUE THREAD

**Issue by chovy** [rg3/youtube-dl#6658] opened 2015-08-24 23:15 UTC
Here is an example course page:
http://www.digitaltutors.com/tutorial/528-Beginners-Guide-to-Digital-Painting-in-Photoshop

Here is an example video page:
http://www.digitaltutors.com/tutorial/528-Beginners-Guide-to-Digital-Painting-in-Photoshop#play-9891

**Comment by dstftw** [comment] 2015-08-25 14:04
Duplicate of #2795.

**Closed by dstftw** 2015-08-25 14:04 UTC
Labels: site-support-request
