### ISSUE TITLE
openload can't get link

### ISSUE THREAD

**Issue by boxstore** [rg3/youtube-dl#12349] opened 2017-03-04 07:55 UTC
youtube-dl -g https://openload.co/embed/BP14eAR-ZEs/Monster.Trucks.2016.HDCAM.UNKNOWN.mp4
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 457, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 447, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1883, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 761, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 427, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/openload.py", line 89, in _real_extract
ValueError: invalid literal for int() with base 10: 'fc9'

**Comment by yan12125** [comment] 2017-03-04 10:03
Duplicate of #10408

**Closed by yan12125** 2017-03-04 10:03 UTC
