### ISSUE TITLE
Openload.co doesn't work.

### ISSUE THREAD

**Issue by niranjanshr13** [rg3/youtube-dl#12344] opened 2017-03-03 18:58 UTC
Openload.co link doesn't work.
I am in version of 2017.03.02; which is latest. 
Example:
youtube-dl -g 'xxxxxxxxxx'   <--- xxxxxxx = any openload link
Result: 
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 457, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 447, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1883, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 761, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 427, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/openload.py", line 78, in _real_extract
ValueError: invalid literal for int() with base 10: 'd'

**Comment by yan12125** [comment] 2017-03-03 19:00
Duplicate of #10408

**Closed by yan12125** 2017-03-03 19:00 UTC
