### ISSUE TITLE
Cant' download from Soundcloud: HTTP 401 error

### ISSUE THREAD

**Issue by UltimateBrent** [rg3/youtube-dl#6967] opened 2015-09-25 14:26 UTC
I've tried this from two different computers, so it's not me being blocked or something:
```
./youtube-dl https://soundcloud.com/dopesongsoundzmusic/k-camp-comfortable --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://soundcloud.com/dopesongsoundzmusic/k-camp-comfortable', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.22
[debug] Python version 2.7.3 - Linux-3.2.0-60-virtual-x86_64-with-Ubuntu-12.04-precise
[debug] exe versions: avconv 0.8.17-4, avprobe 0.8.17-4, ffmpeg N-39499-g12292f3, ffprobe N-39499-g12292f3, rtmpdump 2.4
[debug] Proxy map: {}
[soundcloud] dopesongsoundzmusic/k-camp-comfortable: Resolving id
[soundcloud] dopesongsoundzmusic/k-camp-comfortable: Downloading info JSON
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "./youtube-dl/youtube_dl/extractor/common.py", line 326, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1865, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 444, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 527, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

**Comment by dstftw** [comment] 2015-09-25 14:27
Duplicate of #6930.

**Closed by dstftw** 2015-09-25 14:27 UTC
