### ISSUE TITLE
Cyrillic letters in youtube video names are ignored when naming downloaded files

### ISSUE THREAD

**Issue by Nick-Triller** [rg3/youtube-dl#8529] opened 2016-02-12 15:05 UTC
Command: `youtube-dl -v -x --audio-format mp3 https://www.youtube.com/watch?v=i7ZZvwkFNhM`

Expected file name: `Энди Картрайт - Приход глухого кота-i7ZZvwkFNhM.mp3`
Actual file name: ` - -i7ZZvwkFNhM.mp3`

The cyrillic letters are missing in the actual file name.

```
C:\Users\Nick\Desktop\bug>youtube-dl -v -x --audio-format mp3 https://www.youtub
e.com/watch?v=i7ZZvwkFNhM
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-x', u'--audio-format', u'mp3', u'https://w
ww.youtube.com/watch?v=i7ZZvwkFNhM']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.02.10
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-78395-g6973846, ffprobe N-78395-g6973846
[debug] Proxy map: {}
[youtube] i7ZZvwkFNhM: Downloading webpage
[youtube] i7ZZvwkFNhM: Downloading video info webpage
[youtube] i7ZZvwkFNhM: Extracting video information
[youtube] i7ZZvwkFNhM: Downloading MPD manifest
[debug] Invoking downloader on u'https://r3---sn-35cxacf-43ce.googlevideo.com/vi
deoplayback?id=8bb659bf09053613&itag=141&source=youtube&requiressl=yes&pl=32&mv=
m&ms=au&mm=31&mn=sn-35cxacf-43ce&ratebypass=yes&mime=audio/mp4&gir=yes&clen=5994
8585&lmt=1390034822558378&dur=1880.305&signature=582DFBEF158FBB47DEED4CFA4040594
9A47F34EC.10A39CDE90B824E2E921BF2F41F19560994152F2&mt=1455289109&key=dg_yt0&fexp
=9416126,9420452,9422596,9423459,9423661,9423662&sver=3&upn=rmTGRgmzpjQ&ip=2a02:
8071:2385:fd00:bdbc:e765:45e9:f2e3&ipbits=0&expire=1455310849&sparams=ip,ipbits,
expire,id,itag,source,requiressl,pl,mv,ms,mm,mn,ratebypass,mime,gir,clen,lmt,dur
'
[download] Destination:   -   -i7ZZvwkFNhM.m4a
[download] 100% of 57.17MiB in 00:22
[ffmpeg] Correcting container in "  -   -i7ZZvwkFNhM.m4a"
[debug] ffmpeg command line: ffmpeg -y -i 'file:  -   -i7ZZvwkFNhM.m4a' -c copy
-f mp4 'file:  -   -i7ZZvwkFNhM.temp.m4a'
[debug] ffmpeg command line: ffprobe -show_streams 'file:  -   -i7ZZvwkFNhM.m4a'

[ffmpeg] Destination:   -   -i7ZZvwkFNhM.mp3
[debug] ffmpeg command line: ffmpeg -y -i 'file:  -   -i7ZZvwkFNhM.m4a' -vn -aco
dec libmp3lame -q:a 5 'file:  -   -i7ZZvwkFNhM.mp3'
```

**Comment by dstftw** [comment] 2016-02-12 15:06
Duplicate of #5045.
This is intentional behavior for now. See #4787 for the rationale and #5527 for alternative solution discussions.

**Closed by dstftw** 2016-02-12 15:06 UTC
