### ISSUE TITLE
Does not find 60fps version of Youtube stream

### ISSUE THREAD

**Issue by FichteFoll** [rg3/youtube-dl#10866] opened 2016-10-07 00:09 UTC
### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
C:\Users\Fichte>ytdl https://www.youtube.com/watch?v=4s0osYvMulU -F -v
[debug] System config: []
[debug] User config: ['--ffmpeg-location=e:/Install/_Multimedia/ffmpeg-20151025-git-2ccc1b3-win64-static/bin', '--format
=bestvideo[height<=?1440]+bestaudio/best', '--output=w:\\Video\\Download\\%(title)s_%(id)s.%(ext)s', '--no-mtime']
[debug] Command-line args: ['https://www.youtube.com/watch?v=4s0osYvMulU', '-F', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.10.02
[debug] Python version 3.5.0 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-76262-g2ccc1b3, ffprobe N-76262-g2ccc1b3
[debug] Proxy map: {}
[youtube] 4s0osYvMulU: Downloading webpage
[youtube] 4s0osYvMulU: Downloading video info webpage
[youtube] 4s0osYvMulU: Extracting video information
[youtube] 4s0osYvMulU: Downloading formats manifest
[youtube] 4s0osYvMulU: Downloading MPD manifest
[info] Available formats for 4s0osYvMulU:
format code  extension  resolution note
91           mp4        144p       HLS , h264, aac  @ 48k
92           mp4        240p       HLS , h264, aac  @ 48k
93           mp4        360p       HLS , h264, aac  @128k
94           mp4        480p       HLS , h264, aac  @128k
95           mp4        720p       HLS , h264, aac  @256k
96           mp4        1080p      HLS , h264, aac  @256k (best)
```

---

### Description of your *issue*, suggested solution and other information

The following youtube live stream video provides a 60 fps version for 720p and 1080p but ytdl doesn't find either: https://www.youtube.com/watch?v=4s0osYvMulU

As you can see here, the stream clearly features a 60 fps version:

![2016-10-07_01-52-12_firefox](https://cloud.githubusercontent.com/assets/931051/19174870/50835864-8c32-11e6-95ae-6028bbdc0536.png)
![2016-10-07_01-52-27_firefox](https://cloud.githubusercontent.com/assets/931051/19174872/51ffb6c4-8c32-11e6-8f4b-e3ca1d1e562f.png)

A `-F` log is included above. Using mpv to watch the stream, the [stats.lua](https://github.com/Argon-/mpv-stats/) script also only reports 30fps:

![2016-10-07_02-09-11_mpv](https://cloud.githubusercontent.com/assets/931051/19174964/152d4558-8c33-11e6-9fbf-07edad17e95f.jpg)

**Comment by dstftw** [comment] 2016-10-07 02:29
Duplicate of #10787.

**Closed by dstftw** 2016-10-07 02:29 UTC
