### ISSUE TITLE
netease:song broken

### ISSUE THREAD

**Issue by DennisHofmann93** [rg3/youtube-dl#7329] opened 2015-10-31 05:20 UTC
youtube-dl -v 'http://music.163.com/song?id=17380614'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://music.163.com/song?id=17380614']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.24
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.2
[debug] exe versions: avconv 11.4-6, avprobe 11.4-6
[debug] Proxy map: {}
[netease:song] 17380614: Downloading song info
[netease:song] 17380614: Downloading lyrics data
[debug] Invoking downloader on u'http://m1.music.126.net/ZlF5NQczWFx38_yehBVUcQ==/1163283302197279.mp3'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1598, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1540, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 60, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1873, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

**Comment by yan12125** [comment] 2015-10-31 05:40
Duplicate of  #7301.

**Closed by yan12125** 2015-10-31 05:40 UTC
