### ISSUE TITLE
Site support request: Google drive/docs video

### ISSUE THREAD

**Issue by woodenphone** [rg3/youtube-dl#6155] opened 2015-07-04 21:30 UTC
Example URLs:
https://docs.google.com/file/d/0B65n3MgU-72lODBoT0VLRkdCUGs/preview
https://docs.google.com/file/d/0B65n3MgU-72lODBoT0VLRkdCUGs/edit

https://drive.google.com/file/d/0B91rcCCetjGpNlY4VXhUZFJEQTA/preview

**Comment by jaimeMF** [comment] 2015-07-04 21:59
Duplicate of #2231 and #1701

**Closed by jaimeMF** 2015-07-04 21:59 UTC
