### ISSUE TITLE
DiscoveryGo while using cookies

### ISSUE THREAD

**Issue by battlecattle** [rg3/youtube-dl#11219] opened 2016-11-17 19:00 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.18*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
C:\>youtube-dl.exe --restrict-filenames --continue --no-check-certificate --verbose --cookies cookies.txt https://www.discoverygo.com/gold-rush/misery-on-the-mountain/

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--restrict-filenames', '--continue', '--no-check-certificate', '--verbose', '--cookies', 'cookies.txt', 'https://www.discoverygo.com/gold-rush/misery-on-the-mountain/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.11.18
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-79209-gb3eda69, ffprobe N-79209-gb3eda69
[debug] Proxy map: {}
[DiscoveryGo] misery-on-the-mountain: Downloading webpage
ERROR: misery-on-the-mountain: Failed to parse JSON  (caused by ValueError("Expecting ',' delimiter: line 1 column 68762 (char 68761)",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptx6jnsy6\build\youtube_dl\extractor\common.py", line 559, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 359, in raw_decode
ValueError: Expecting ',' delimiter: line 1 column 68762 (char 68761)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptx6jnsy6\build\youtube_dl\extractor\common.py", line 559, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 359, in raw_decode
ValueError: Expecting ',' delimiter: line 1 column 68762 (char 68761)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptx6jnsy6\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptx6jnsy6\build\youtube_dl\extractor\common.py", line 357, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptx6jnsy6\build\youtube_dl\extractor\discoverygo.py", line 53, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptx6jnsy6\build\youtube_dl\extractor\common.py", line 563, in _parse_json
youtube_dl.utils.ExtractorError: misery-on-the-mountain: Failed to parse JSON  (caused by ValueError("Expecting ',' delimiter: line 1 column 68762 (char 68761)",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):

- Single video: https://www.discoverygo.com/gold-rush/misery-on-the-mountain/

---

### Description of your *issue*, suggested solution and other information

I have been using this method without issue and recently stopped working. I am in the US and have no issues watching the video at the link provided.

**Comment by dstftw** [comment] 2016-11-17 19:16
Re-export cookies and try again.

**Comment by battlecattle** [comment] 2016-11-17 19:21
I have re-exported multiple times, and just tried again and received the same errors.

**Comment by StevenDTX** [comment] 2016-11-20 21:07
I, too, have verified this issue. I exported my cookies twice.

**Comment by StevenDTX** [comment] 2016-12-02 19:58
Just FYI... there are some "unlocked" episodes on DiscoveryGo where the m3u8 can be extracted without a logon or cookies.

https://www.discoverygo.com/killing-fields/a-body-in-the-bayou/
https://www.discoverygo.com/gold-rush/frankenstein-machinery/


```
E:\>youtube-dl --verbose https://www.discoverygo.com/killing-fields/a-body-in-the-bayou/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.discoverygo.com/killing-fields/a-body-in-the-bayou/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.12.01
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-81721-g7447ec9, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[DiscoveryGo] a-body-in-the-bayou: Downloading webpage
ERROR: a-body-in-the-bayou: Failed to parse JSON  (caused by ValueError("Expecting ',' delimiter: line 1 column 23968 (char 23967)",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6j6yd3lp\build\youtube_dl\extractor\common.py", line 559, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 359, in raw_decode
ValueError: Expecting ',' delimiter: line 1 column 23968 (char 23967)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6j6yd3lp\build\youtube_dl\extractor\common.py", line 559, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 359, in raw_decode
ValueError: Expecting ',' delimiter: line 1 column 23968 (char 23967)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6j6yd3lp\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6j6yd3lp\build\youtube_dl\extractor\common.py", line 357, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6j6yd3lp\build\youtube_dl\extractor\discoverygo.py", line 53, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6j6yd3lp\build\youtube_dl\extractor\common.py", line 563, in _parse_json
youtube_dl.utils.ExtractorError: a-body-in-the-bayou: Failed to parse JSON  (caused by ValueError("Expecting ',' delimiter: line 1 column 23968 (char 23967)",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by KyleBS** [comment] 2016-12-16 00:54
Inside of the data-video JSON, there is unescaped XML under "adParameters" keys causing the JSON parser to barf.  The XML root appears consistent, "VAST", and if you peel it out of the JSON string, things suddenly work (for me).

The hack I have:
youtube_dl/extractor/common.py:559
```
for i in xrange(json_string.count('"&lt;?xml version="1.0" encoding="UTF-8"?> <VAST')):
        start = json_string.find('"&lt;?xml version="1.0" encoding="UTF-8"?> <VAST')
        end = json_string.find('VAST> "') + len('VAST> "')
        json_string = json_string[:start] + json_string[end:]
```

**Comment by StevenDTX** [comment] 2016-12-28 22:12
Thanks, @KyleBS.

Would you mind posting a copy of your Discoverygo.py file?  Unfortunately, I'm on Windows and fairly new to this whole "git" thing, so I haven't been able to successfully integrate your changes.

**Comment by KyleBS** [comment] 2016-12-28 22:18
Posted as .txt to appease github, be sure to change the extension back to .py!
[discoverygo.py.txt](https://github.com/rg3/youtube-dl/files/676335/discoverygo.py.txt)

**Comment by yan12125** [comment] 2016-12-29 03:28
Could anyone paste a dump of the breaking XML string?

**Comment by StevenDTX** [comment] 2016-12-29 14:55
Thanks @KyleBS.  It still isn't working for me on Windows.  Oh well, I will just wait until its fixed.  Until then, its easy enough to get the m3u8 from the page and download it.

**Comment by StevenDTX** [comment] 2016-12-30 19:31
@yan12125 

Is that something I can help you with?  Is there a command line I should run?

**Comment by yan12125** [comment] 2016-12-30 19:41
Add ```print(container.get('data-video') or container.get('data-json'))``` before ```video = self._parse_json``` and run

**Comment by StevenDTX** [comment] 2016-12-30 19:51
Hopefully this gives you what you asked for.

[discoverygo-xml.txt](https://github.com/rg3/youtube-dl/files/679146/discoverygo-xml.txt)

**Comment by yan12125** [comment] 2016-12-30 20:19
Does things work with this change?
```Diff
diff --git a/youtube_dl/extractor/discoverygo.py b/youtube_dl/extractor/discoverygo.py
index c4e83b2c3..b4d686a09 100644
--- a/youtube_dl/extractor/discoverygo.py
+++ b/youtube_dl/extractor/discoverygo.py
@@ -49,7 +49,7 @@ class DiscoveryGoIE(InfoExtractor):
                 webpage, 'video container'))
 
         video = self._parse_json(
-            unescapeHTML(container.get('data-video') or container.get('data-json')),
+            container.get('data-video') or container.get('data-json'),
             display_id)
 
         title = video['name']
```

**Comment by StevenDTX** [comment] 2016-12-31 18:34
@yan12125 

Yes...that works!!!  Thank you!

**Comment by yan12125** [comment] 2017-01-01 08:17
Thanks @StevenDTX. Which video(s) were you testing against?

Also, I'd like to hear more feedback before commiting it. @KyleBS Does that work for you?

**Comment by StevenDTX** [comment] 2017-01-01 17:32
I downloaded a couple episodes of Gold Rush and several Alaska the Last Frontier.  It also tested fine on ScienceChannelgo.com and on AnimalPlanetgo.com

**Comment by KyleBS** [comment] 2017-01-02 13:54
@yan12125 Can confirm, this solution worked for me as well, nice catch!

**Comment by yan12125** [comment] 2017-01-05 10:53
I remember there are some errors in "unlocked" videos mentioned in https://github.com/rg3/youtube-dl/issues/11219#issuecomment-264547986. However, they are now all subscribers-only, so I can't reproduce the error. Closing this first and feel free to open new issues if there's any problem.

**Closed by yan12125** 2017-01-05 10:53 UTC
Labels: tv-provider-account-needed
