### ISSUE TITLE
Can't download 360 degree YouTube videos

### ISSUE THREAD

**Issue by danfiscus** [rg3/youtube-dl#9989] opened 2016-07-03 00:50 UTC
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
Dan-Fiscus-MBP:~ lindafiscus$ youtube-dl -v -F https://www.youtube.com/watch?v=qZ0Amn8rbpY
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.youtube.com/watch?v=qZ0Amn8rbpY']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.03
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.7.1, ffprobe 2.7.1
[debug] Proxy map: {}
[youtube] qZ0Amn8rbpY: Downloading webpage
[youtube] qZ0Amn8rbpY: Downloading video info webpage
[youtube] qZ0Amn8rbpY: Extracting video information
[youtube] qZ0Amn8rbpY: Downloading MPD manifest
[info] Available formats for qZ0Amn8rbpY:
format code  extension  resolution note
249          webm       audio only DASH audio   55k , opus @ 50k (48000Hz), 2.18MiB
250          webm       audio only DASH audio   79k , opus @ 70k (48000Hz), 2.93MiB
140          m4a        audio only DASH audio  128k , m4a_dash container, mp4a.40.2@128k (44100Hz), 5.37MiB
171          webm       audio only DASH audio  147k , vorbis@128k (44100Hz), 4.94MiB
251          webm       audio only DASH audio  151k , opus @160k (48000Hz), 5.70MiB
160          mp4        256x128    DASH video  100k , avc1.4d400c, 30fps, video only, 4.15MiB
278          webm       256x128    DASH video  106k , webm container, vp9, 30fps, video only, 3.08MiB
133          mp4        426x214    DASH video  220k , avc1.4d400d, 30fps, video only, 9.24MiB
242          webm       426x214    DASH video  230k , vp9, 30fps, video only, 4.39MiB
243          webm       640x320    DASH video  415k , vp9, 30fps, video only, 8.25MiB
134          mp4        640x320    DASH video  531k , avc1.4d401e, 30fps, video only, 8.43MiB
244          webm       854x428    DASH video  808k , vp9, 30fps, video only, 15.48MiB
135          mp4        854x428    DASH video 1031k , avc1.4d401f, 30fps, video only, 18.73MiB
247          webm       1280x640   DASH video 1645k , vp9, 30fps, video only, 36.02MiB
136          mp4        1280x640   DASH video 2057k , avc1.4d401f, 30fps, video only, 38.87MiB
248          webm       1920x960   DASH video 2762k , vp9, 30fps, video only, 72.51MiB
137          mp4        1920x960   DASH video 3843k , avc1.640028, 30fps, video only, 80.47MiB
264          mp4        2560x1280  DASH video 9227k , avc1.640032, 30fps, video only, 221.65MiB
271          webm       2560x1280  DASH video 9326k , vp9, 30fps, video only, 229.87MiB
313          webm       3840x1920  DASH video 20405k , vp9, 30fps, video only, 676.74MiB
266          mp4        3840x1920  DASH video 20623k , avc1.640033, 30fps, video only, 465.85MiB
17           3gp        176x144    small , mp4v.20.3,  mp4a.40.2@ 24k
36           3gp        320x160    small , mp4v.20.3,  mp4a.40.2
18           mp4        640x320    medium , avc1.42001E,  mp4a.40.2@ 96k
43           webm       640x360    medium , vp8.0,  vorbis@128k
22           mp4        1280x640   hd720 , avc1.64001F,  mp4a.40.2@192k (best)

```
---

### Description of your *issue*, suggested solution and other information

I wanted to download a 360 degree YouTube video to watch later and I realized none of the formats listed were the 360 degree version. I don't know if this is a bug or just not a feature yet so I marked it as both. Feel free to let me know which it is and I will edit the post accordingly. I would really like to see this feature implemented if possible.

**Comment by dstftw** [comment] 2016-07-03 00:54
Duplicate of #6246.

**Closed by dstftw** 2016-07-03 00:54 UTC
