### ISSUE TITLE
fox.com error problem with version 10.29.2017 

### ISSUE THREAD

**Issue by rellik31** [rg3/youtube-dl#14620] opened 2017-10-29 10:46 UTC
can this site please be fixed?

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', 'C:\\Users\\win10\\Desktop\\vid\\%(upload_date)s.%(uploader)s.%(ext)s', '-i', '--no-playlist', '-f', '131', '-v', '-c', '-w', 'https://www.fox.com/watch/1acae96e922460a27bd53a1b76f1ce5b/']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2017.10.29
[debug] Python version 3.4.4 - Windows-10-10.0.10240
[debug] exe versions: ffmpeg N-77704-g68eb208, ffprobe 2.2.3
[debug] Proxy map: {}
[FOX] 1acae96e922460a27bd53a1b76f1ce5b: Downloading JSON metadata
[FOX] 1acae96e922460a27bd53a1b76f1ce5b: Downloading webpage
[uplynk:preplay] 1c0ec5984ef040139d53384ae409f0b6: Downloading JSON metadata
[uplynk:preplay] 1c0ec5984ef040139d53384ae409f0b6: Downloading m3u8 information
[uplynk:preplay] 1c0ec5984ef040139d53384ae409f0b6: Downloading JSON metadata
[debug] Invoking downloader on 'http://content-ause5.uplynk.com/1c0ec5984ef040139d53384ae409f0b6/b.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 327
[download] Destination: C:\Users\win10\Desktop\vid\20171003.NA.mp4
[download]   0.3% of ~21.75MiB at 189.56KiB/s ETA 03:18     ERROR: unable to download video data: <urlopen error EOF occurred in violation of protocol (_ssl.c:600)>
Traceback (most recent call last):
  File "C:\Python\Python34\lib\urllib\request.py", line 1183, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1137, in request
  File "C:\Python\Python34\lib\http\client.py", line 1182, in _send_request
  File "C:\Python\Python34\lib\http\client.py", line 1133, in endheaders
  File "C:\Python\Python34\lib\http\client.py", line 963, in _send_output
  File "C:\Python\Python34\lib\http\client.py", line 898, in send
  File "C:\Python\Python34\lib\http\client.py", line 1287, in connect
  File "C:\Python\Python34\lib\ssl.py", line 362, in wrap_socket
  File "C:\Python\Python34\lib\ssl.py", line 580, in __init__
  File "C:\Python\Python34\lib\ssl.py", line 807, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\YoutubeDL.py", line 1892, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\YoutubeDL.py", line 1831, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\downloader\common.py", line 361, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\downloader\hls.py", line 166, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\YoutubeDL.py", line 2195, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\utils.py", line 1086, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:600)>

**Comment by goggle** [comment] 2017-10-29 12:20
I cannot reproduce your error. The download of the video works fine for me.
But it seems that this problem is connected with issue #14618, the user @mrbryce gets a similar error message regarding `_ssl.c`:
```
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1748)
```

**Comment by yan12125** [comment] 2017-10-29 13:09
Duplicate of #14139. Please move on there for further discussions.

**Closed by yan12125** 2017-10-29 13:09 UTC

**Comment by yan12125** [comment] 2017-10-29 13:10
Sorry, not #14139 but #14521

**Comment by rellik31** [comment] 2017-10-29 13:17
does fox work for you every time? 
i am using a usa dns number as fox is region blocked
i just tried again and got this message

c:\Users\win10\Desktop\yt>youtube-dl.exe -f 240 https://www.fox.com/watch/1acae96e922460a27bd53a1b76f1ce5b/
[FOX] 1acae96e922460a27bd53a1b76f1ce5b: Downloading JSON metadata
[FOX] 1acae96e922460a27bd53a1b76f1ce5b: Downloading webpage
[uplynk:preplay] 1c0ec5984ef040139d53384ae409f0b6: Downloading JSON metadata
[uplynk:preplay] 1c0ec5984ef040139d53384ae409f0b6: Downloading m3u8 information
[uplynk:preplay] 1c0ec5984ef040139d53384ae409f0b6: Downloading JSON metadata
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 327
[download] Destination: The Friend-1c0ec5984ef040139d53384ae409f0b6.mp4
[download]   0.3% of ~41.45MiB at 346.28KiB/s ETA 04:43  ERROR: unable to download video data: HTTP Error 403: Forbidden

**Comment by rellik31** [comment] 2017-10-29 13:24
desktop\yt>youtube-dl.exe -f 240 https://www.fox.com/watch/1acae96e922460a27bd53a1b76f1ce5b/
[FOX] 1acae96e922460a27bd53a1b76f1ce5b: Downloading JSON metadata
[FOX] 1acae96e922460a27bd53a1b76f1ce5b: Downloading webpage
[uplynk:preplay] 1c0ec5984ef040139d53384ae409f0b6: Downloading JSON metadata
[uplynk:preplay] 1c0ec5984ef040139d53384ae409f0b6: Downloading m3u8 information
[uplynk:preplay] 1c0ec5984ef040139d53384ae409f0b6: Downloading JSON metadata
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 327
[download] Destination: The Friend-1c0ec5984ef040139d53384ae409f0b6.mp4
[download]   0.3% of ~41.45MiB at Unknown speed ETA Unknown ETAERROR: unable to download video data: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>

**Comment by yan12125** [comment] 2017-10-29 13:49
Just tested this video and I can't watch it in Firefox with US proxies, so I won't know whether fox.com works for me or not.

**Comment by goggle** [comment] 2017-10-29 14:10
@rellik31 Since this thread is closed, you could post your output of `youtube-dl.exe -v URL` to #14139. Maybe someone will be able to reproduce the error.
