### ISSUE TITLE
douyu issues

### ISSUE THREAD

**Issue by latel** [rg3/youtube-dl#15379] opened 2018-01-21 11:30 UTC
youtube-dl https://www.douyu.com/19223
[DouyuTV] 19223: Downloading room info
[DouyuTV] 19223: Downloading video URL info
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/__init__.py", line 465, in main
    _real_main(argv)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/__init__.py", line 455, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1988, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/douyutv.py", line 106, in _real_extract
    })['data']['live_url']
TypeError: list indices must be integers or slices, not str

**Comment by yan12125** [comment] 2018-01-21 13:07
Duplicate of #13419.

**Closed by yan12125** 2018-01-21 13:07 UTC
