### ISSUE TITLE
Feature request: select bestaudio format based on determined bestvideo to preserve container type

### ISSUE THREAD

**Issue by videonerd** [rg3/youtube-dl#11517] opened 2016-12-23 17:02 UTC
Previous topic was closed due to perceived availability of such a feature.

Present behaviour of bestaudio is independent of bestvideo. My feature request is for bestaudio to be dependent on the determined bestvideo format to preserve container format e.g:

if bestvideo is determined to be mp4, bestaudio will default to bestaudio[ext=m4a] to preserve the mp4 container and avoid an mkv output.

similarly, if bestvideo is determined to be vp9, bestaudio will default to bestaudio[ext=webm] to preserve the webm container and avoid an mkv output.

Thank you!

**Comment by yan12125** [comment] 2016-12-23 17:20
Duplicate of #10226. There are some interesting discussions but no actual implementations yet.

**Closed by yan12125** 2016-12-23 17:20 UTC

**Comment by endquote** [comment] 2017-02-21 04:44
I attempted an implementation in JavaScript in response to @daemonster's Python version: https://gist.github.com/Daemonster/4c94372a85cd4b5ea86df06e102a19e7#gistcomment-2006531
