### ISSUE TITLE
Special chars aren't supported ?

### ISSUE THREAD

**Issue by Kdmeizk** [rg3/youtube-dl#7939] opened 2015-12-21 21:36 UTC
For example, Japan chars aren't copied to the file : https://www.youtube.com/watch?v=J69oCCM1EcI

In title, description, ...
Version : 2015.12.21

**Comment by phihag** [comment] 2015-12-21 21:44
Please provide more information, at the very least the complete output of `youtube-dl` when called with `-v`. For what it's worth, works fine for me:
```
$ youtube-dl --get-filename J69oCCM1EcI -f best
Hello Sleepwalkers「午夜の待ち合わせ」MUSIC VIDEO-J69oCCM1EcI.mp4
```

**Comment by Kdmeizk** [comment] 2015-12-21 21:58
I've completely forgot my OS : Windows 7 64 bits. I made the same command and special chars didn't display.
Title : Hello SleepwalkersMUSIC VIDEO.mp4

Command : C:\Users\User\Downloads\youtube-dl\youtube-dl.exe --no-playlist --buffer-size 500000000 --no-cache-dir -o "C:\Users\User\Desktop\%(title)s.%(ext)s" --console-title -v --print-traffic --no-call-home --youtube-skip-dash-manifest --add-metadata 

[output.txt](https://github.com/rg3/youtube-dl/files/69032/output.txt)

**Comment by phihag** [comment] 2015-12-21 22:04
As I wrote, we need the **complete** output. That output should start with something along the lines of `[debug] System config: []`. You can use [shell redirection](https://en.wikipedia.org/wiki/Redirection_(computing)) to save the whole output if you are unable otherwise.

**Comment by Kdmeizk** [comment] 2015-12-21 22:32
I used
youtube-dl --no-playlist --buffer-size 500000000 --no-cache-dir -o "C:\Users\User\Desktop\%(title)s.%(ext)s" --console-title -v --print-traffic --no-call-home --youtube-skip-dash-manifest --add-metadata https://www.youtube.com/watch?v=J69oCCM1EcI > output.txt

I don't know why first elements aren't here.

**Comment by Kdmeizk** [comment] 2015-12-21 22:50
The only way I found at the moment is a screenshot :

![output](https://cloud.githubusercontent.com/assets/13298795/11943349/719ac8b8-a83d-11e5-93d9-f850fd1d3853.png)

**Comment by dstftw** [comment] 2015-12-22 22:01
Duplicate of #5045.
This is intentional behavior for now. See #4787 for the rationale and #5527 for alternative solution discussions.

**Closed by dstftw** 2015-12-22 22:01 UTC
