### ISSUE TITLE
Add support for espn.go.com

### ISSUE THREAD

**Issue by hub2git** [rg3/youtube-dl#5719] opened 2015-05-15 23:52 UTC
I'd like to download the video on http://espn.go.com/video/clip?id=10365079. 
But I get this:
```
$ youtube-dl "http://espn.go.com/video/clip?id=10365079"
[generic] clip?id=10365079: Requesting header
WARNING: Falling back on generic information extractor.
[generic] clip?id=10365079: Downloading webpage
[generic] clip?id=10365079: Extracting information


ERROR: Did not get any data blocks
```

**Comment by dstftw** [comment] 2015-05-16 11:50
Duplicate of #4396.

**Closed by dstftw** 2015-05-16 11:50 UTC
Labels: site-support-request
