### ISSUE TITLE
youtube-dl can't download video today

### ISSUE THREAD

**Issue by yulcheung** [rg3/youtube-dl#12898] opened 2017-04-28 10:14 UTC
it surely is up to date.
the following is the information:

 C:\Green software\youtube>youtube-dl -F https://www.youtube.com/watch?v=qA9u6N4Rp98
[youtube] qA9u6N4Rp98: Downloading webpage
[youtube] qA9u6N4Rp98: Downloading video info webpage
[youtube] qA9u6N4Rp98: Extracting video information
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\build\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\build\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment] 2017-04-28 10:15
Duplicate of #12885

**Closed by yan12125** 2017-04-28 10:15 UTC
