### ISSUE TITLE
Error for HBO Nordic

### ISSUE THREAD

**Issue by imsdal68** [rg3/youtube-dl#17230] opened 2018-08-13 08:36 UTC
What i understand HBO should be supported by youtube-dl. I tried this earlier today and come up short. 
Since i couldnt find any issues for this earlier i post the full output here.

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://se.hbonordic.com/series/the-affair/season-4/episode-9/1f10ced-00e8cc6d07a']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.08.04
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-72805-g913685f, ffprobe N-72805-g913685f
[debug] Proxy map: {}
[generic] 1f10ced-00e8cc6d07a: Requesting header
WARNING: Could not send HEAD request to https://se.hbonordic.com/series/the-affair/season-4/episode-9/1f10ced-00e8cc6d07a: HTTP Error 404: Not Found
[generic] 1f10ced-00e8cc6d07a: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\extractor\common.py", line 599, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\YoutubeDL.py", line 2211, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

**Comment by MR-2** [comment] 2018-08-20 12:25
@imsdal68 You understand wrong. HBO Nordic's content is DRM encrypted and isn't has never been supported by youtube-dl and probably never will be. This ticket/issue can be closed.

**Comment by remitamine** [comment] 2018-08-20 12:32
Duplicate of #9257.

**Closed by remitamine** 2018-08-20 12:32 UTC
Labels: geo-restricted
