### ISSUE TITLE
Can't download private video

### ISSUE THREAD

**Issue by bengan** [rg3/youtube-dl#577] opened 2012-12-05 11:09 UTC
I would like to download this http://www.youtube.com/watch?v=oUNJZ1QObZM

youtube-dl> youtube-dl -U
Updating to latest version...
youtube-dl is up-to-date (2012.11.29)

youtube-dl> youtube-dl "http://www.youtube.com/watch?v=oUNJZ1QObZM"
[youtube] Setting language
[youtube] oUNJZ1QObZM: Downloading video webpage
[youtube] oUNJZ1QObZM: Downloading video info webpage
[youtube] oUNJZ1QObZM: Extracting video information
[youtube] RTMP download detected
[download] Destination: oUNJZ1QObZM.flv

ERROR: unable to download video

**Comment by ElijahLynn** [comment] 2015-12-30 15:35
Latest error is:

> ERROR: rtmpe downloads are not supported, see https://github.com/rg3/youtube-dl/issues/343 for more information.

**Comment by dstftw** [comment] 2016-06-12 17:05
Duplicate of #343.

**Closed by dstftw** 2016-06-12 17:05 UTC
