### ISSUE TITLE
[srf.ch] Radio

### ISSUE THREAD

**Issue by irem77** [rg3/youtube-dl#7644] opened 2015-11-25 11:48 UTC
Video Download from srf.ch works great. Is it possible to add radio (audio) too ?

http://www.srf.ch/play/radio/hoerspielarchiv-srf-musikwelle/audio/saegel-ohni-wind-von-jakob-stebler?id=415bf3d3-6429-4de7-968d-95866e37cfbc

**Comment by remitamine** [comment] 2015-12-05 15:10
duplicate of #7760

**Closed by remitamine** 2015-12-05 15:10 UTC
Labels: site-support-request
