### ISSUE TITLE
Unable to download from cinemasscare.com again.

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#6397] opened 2015-07-29 02:38 UTC
Here we go again!

$ youtube-dl-07282015 -v http://cinemassacre.com/2015/07/28/avgn-seaman-for-dreamcast/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://cinemassacre.com/2015/07/28/avgn-seaman-for-dreamcast/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.28
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.8
[debug] exe versions: avconv 1.2.12, avprobe 1.2.12, ffmpeg 1.2.12, ffprobe 1.2.12, rtmpdump 2.4
[debug] Proxy map: {}
[Cinemassacre] avgn-seaman-for-dreamcast: Downloading webpage
[ScreenwaveMedia] Cinemassacre-55b29f38c3494: Downloading player webpage
ERROR: Unable to extract vidtitle; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl-07282015/youtube_dl/YoutubeDL.py", line 656, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dl-07282015/youtube_dl/extractor/common.py", line 279, in extract
    return self._real_extract(url)
  File "/home/ant/bin/youtube-dl-07282015/youtube_dl/extractor/screenwavemedia.py", line 29, in _real_extract
    r'\'vidtitle\'\s*:\s*"([^"]+)"', playerdata, 'vidtitle').replace('\\/', '/')
  File "/home/ant/bin/youtube-dl-07282015/youtube_dl/extractor/common.py", line 561, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract vidtitle; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Thank you in advance. ;)

**Comment by remitamine** [comment] 2015-07-29 10:48
i already send a pull request 7 days ago but it didn't get reviewed untill now https://github.com/rg3/youtube-dl/pull/6330.
i know it not good enough(depend on replacing) but If you have a better idea, please propose it.
i update it today because of a new change in the site.

**Comment by jaimeMF** [comment] 2015-07-29 11:43
Closing as a duplicate of #6397.

**Closed by jaimeMF** 2015-07-29 11:43 UTC
Labels: broken-IE

**Comment by remitamine** [comment] 2015-07-29 11:48
you mean duplicate of https://github.com/rg3/youtube-dl/issues/6270?

**Comment by jaimeMF** [comment] 2015-07-29 11:49
> you mean duplicate of #6270?

Yes, it's not the first time I make the same mistake :).

**Comment by remitamine** [comment] 2015-07-29 11:50
how about the pull request?

**Comment by jaimeMF** [comment] 2015-08-01 20:19
Thanks to @remitamine it will work in the next version, thanks for the report.
