### ISSUE TITLE
openload.co unable to extract video url

### ISSUE THREAD

**Issue by trname** [rg3/youtube-dl#9761] opened 2016-06-12 11:20 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.06.12*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.12**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl --verbose https://openload.co/f/msinwGPallY/Bzns.Oynlar.2016.720p.Dvdrip.DUAL.mkv.mp4
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://openload.co/f/msinwGPallY/Bzns.Oynlar.2016.720p.Dvdrip.DUAL.mkv.mp4']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.12
[debug] Python version 2.6.6 - Linux-2.6.32-573.26.1.el6.x86_64-x86_64-with-centos-6.7-Final
[debug] exe versions: ffmpeg N-78733-g0f31d40, ffprobe N-78733-g0f31d40
[debug] Proxy map: {}
[Openload] msinwGPallY: Downloading webpage
ERROR: Unable to extract video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 342, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/openload.py", line 112, in _real_extract
    r'return\s+"(https?://[^"]+)"', decoded, 'video URL')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 645, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```
---

What could be the solution to the problem?

**Comment by yan12125** [comment] 2016-06-12 11:25
Duplicate of #9706. Openload now has upgraded protection and there's no good solution yet.

**Closed by yan12125** 2016-06-12 11:25 UTC
