### ISSUE TITLE
ValueError with bandcamp.com

### ISSUE THREAD

**Issue by Earnestly** [rg3/youtube-dl#5222] opened 2015-03-16 22:23 UTC
```
teapot earnest %i master ~ youtube-dl -vg "http://selectstartrecords.bandcamp.com/track/return-to-chiba-city"
[debug] System config: []
[debug] User config: ['--no-cache-dir']
[debug] Command-line args: ['-vg', 'http://selectstartrecords.bandcamp.com/track/return-to-chiba-city']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.15
[debug] Python version 3.4.3 - Linux-3.19.1-1-zen-x86_64-with-arch
[debug] exe versions: ffmpeg 2.6, ffprobe 2.6, rtmpdump 2.4
[debug] Proxy map: {}
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 9, in <module>
    load_entry_point('youtube-dl==2015.3.15', 'console_scripts', 'youtube-dl')()
  File "/usr/lib/python3.4/site-packages/youtube_dl/__init__.py", line 408, in main
    _real_main(argv)
  File "/usr/lib/python3.4/site-packages/youtube_dl/__init__.py", line 398, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1452, in download
    res = self.extract_info(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 665, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 711, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1067, in process_video_result
    format['http_headers'] = self._calc_headers(full_format_info)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 968, in _calc_headers
    cookies = self._calc_cookies(info_dict)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 975, in _calc_cookies
    pr = compat_urllib_request.Request(info_dict['url'])
  File "/usr/lib/python3.4/urllib/request.py", line 266, in __init__
    self.full_url = url
  File "/usr/lib/python3.4/urllib/request.py", line 292, in full_url
    self._parse()
  File "/usr/lib/python3.4/urllib/request.py", line 321, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: ''
```

Hopefully all the information required is part of the output, tell me if anything else is required.

**Comment by jaimeMF** [comment] 2015-03-16 22:28
Duplicate of #4861 (not fixed yet).

**Closed by jaimeMF** 2015-03-16 22:28 UTC
