### ISSUE TITLE
Add support for Katsomo

### ISSUE THREAD

**Issue by teepean** [rg3/youtube-dl#12212] opened 2017-02-22 09:20 UTC
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.21**

- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) - [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

- [ ] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Logs:

$ youtube-dl.exe --verbose http://www.katsomo.fi/#!/jakso/33006076/suomen-surkein-kuski/718972/sarja-alkaa
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'http://www.katsomo.fi/#!/jakso/33006076/suomen-surkein-kuski/718972/sarja-alkaa']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.02.21
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-67118-g08e6832, ffprobe N-83034-gf48b6b8, rtmpdump 2.4
[debug] Proxy map: {'https': 'https://127.0.0.1:54347'}
[generic] sarja-alkaa: Requesting header
WARNING: Could not send HEAD request to http://www.katsomo.fi/#!/jakso/33006076/suomen-surkein-kuski/718972/sarja-alkaa: HTTP Error 403: Forbidden
[generic] sarja-alkaa: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] sarja-alkaa: Extracting information
ERROR: Unsupported URL: http://www.katsomo.fi/#!/jakso/33006076/suomen-surkein-kuski/718972/sarja-alkaa
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqrnhzzwk\build\youtube_dl\YoutubeDL.py", line 704, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqrnhzzwk\build\youtube_dl\extractor\common.py", line 427, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqrnhzzwk\build\youtube_dl\extractor\generic.py", line 2604, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.katsomo.fi/#!/jakso/33006076/suomen-surkein-kuski/718972/sarja-alkaa

$ youtube-dl.exe --verbose https://mtvdashvod-a.akamaihd.net/video/viihde/ismvol1/2017-01-23/Suomen_surkein_kuski(718972_ISMUSPWV).ism/Suomen_surkein_kuski(718972_ISMUSPWV).mpd
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://mtvdashvod-a.akamaihd.net/video/viihde/ismvol1/2017-01-23/Suomen_surkein_kuski(718972_ISMUSPWV).ism/Suomen_surkein_kuski(718972_ISMUSPWV).mpd']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.02.21
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-67118-g08e6832, ffprobe N-83034-gf48b6b8, rtmpdump 2.4
[debug] Proxy map: {'https': 'https://127.0.0.1:54347'}
[generic] Suomen_surkein_kuski(718972_ISMUSPWV): Requesting header
WARNING: Falling back on generic information extractor.
[generic] Suomen_surkein_kuski(718972_ISMUSPWV): Downloading webpage
[generic] Suomen_surkein_kuski(718972_ISMUSPWV): Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqrnhzzwk\build\youtube_dl\YoutubeDL.py", line 704, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqrnhzzwk\build\youtube_dl\extractor\common.py", line 427, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqrnhzzwk\build\youtube_dl\extractor\generic.py", line 1762, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqrnhzzwk\build\youtube_dl\extractor\common.py", line 1023, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

- Single video: http://www.katsomo.fi/#!/jakso/33006076/suomen-surkein-kuski/718972/sarja-alkaa
- Single video: https://mtvdashvod-a.akamaihd.net/video/viihde/ismvol1/2017-01-23/Suomen_surkein_kuski(718972_ISMUSPWV).ism/Suomen_surkein_kuski(718972_ISMUSPWV).mpd
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Finnish site Katsomo recently switched away from their Silverlight site and started using DASH based player. AFAIK the same player is used in different cmore sites.

**Comment by yan12125** [comment] 2017-02-22 09:49
Duplicate of #10543

**Closed by yan12125** 2017-02-22 09:49 UTC
