### ISSUE TITLE
error - Playback on other websites has been disabled by the video owner

### ISSUE THREAD

**Issue by aryehbeitz** [rg3/youtube-dl#5059] opened 2015-02-24 23:17 UTC
https://www.youtube.com/watch?v=ah3utUn93fw

[youtube] ah3utUn93fw: Downloading webpage
[youtube] ah3utUn93fw: Downloading embed webpage
[youtube] ah3utUn93fw: Refetching age-gated info webpage
ERROR: ah3utUn93fw: YouTube said: <a href="http://www.youtube.com/watch?v=ah3utUn93fw&feature=player_embedded" target="_blank">Watch this video on YouTube.</a><br/>Playback on other websites has been disabled by the video owner.

**Comment by barsnick** [comment] 2015-03-04 16:22
Watching this video requires a login, due to age restrictions. You will have to use YouTube credentials to download it.

**Comment by yan12125** [comment] 2015-03-29 20:23
Duplicate of #4162 and there's a solution in #4627

**Closed** 2015-03-31 10:27 UTC

**Comment by shmilon** [comment] 2020-03-27 02:31
Playback on other websites has been disabled by the video owner you could not show it.
