### ISSUE TITLE
Question about limiting the amount of video recorded

### ISSUE THREAD

**Issue by NeedToDestroy** [rg3/youtube-dl#9449] opened 2016-05-10 20:19 UTC
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.05.10*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.10**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

---
### Description of your *question*, suggested solution and other information

Is there a way to limit the amount of video downloaded? I am looking to gather 30s-1m clips of videos to use in a training data set. Ideally, I would like to launch the program and download up to a minute of video before concluding that session. 

Thanks!

**Comment by yan12125** [comment] 2016-05-11 05:16
Duplicate of #622.

**Closed by yan12125** 2016-05-11 05:16 UTC
