### ISSUE TITLE
svtplay

### ISSUE THREAD

**Issue by GaramMasala** [rg3/youtube-dl#9831] opened 2016-06-19 03:19 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.06.19.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.19.1**

youtube-dl --version 2016.06.19.1

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

uname 10.3-RELEASE-p4 FreeBSD

youtube-dl -i -k --restrict-filenames --all-subs -v http://www.svtplay.se/video/8169501/bron/bron-sasong-1-avsnitt-4
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-i', u'-k', u'--restrict-filenames', u'--all-subs', u'-v', u'http://www.svtplay.se/video/8169501/bron/bron-sasong-1-avsnitt-4']
[debug] Encodings: locale ISO8859-15, fs ISO8859-15, out ISO8859-15, pref ISO8859-15
[debug] youtube-dl version 2016.06.19.1
[debug] Python version 2.7.11 - FreeBSD-10.3-RELEASE-p4-amd64-64bit-ELF
[debug] exe versions: ffmpeg 2.8.7, ffprobe 2.8.7, rtmpdump 2.4
[debug] Proxy map: {}
[SVTPlay] 8169501: Downloading JSON metadata
ERROR: 8169501: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 544, in _parse_json
    return json.loads(json_string)
  File "/usr/local/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 342, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/svt.py", line 124, in _real_extract
    video_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/svt.py", line 14, in _extract_video
    info = self._download_json(url, video_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 538, in _download_json
    json_string, video_id, transform_source=transform_source, fatal=fatal)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 548, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
ExtractorError: 8169501: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

youtube-dl -U
youtube-dl is up-to-date (2016.06.19.1)

**Comment by dstftw** [comment] 2016-06-19 03:21
Duplicate of #9809.

**Closed by dstftw** 2016-06-19 03:21 UTC

**Comment by GaramMasala** [comment] 2016-06-19 03:25
No it's not a duplicate.
