### ISSUE TITLE
BUG: "--convert-subs" does not work.

### ISSUE THREAD

**Issue by NothingCanPlayVTT** [rg3/youtube-dl#12185] opened 2017-02-20 06:22 UTC
(Version: Latest version)

Your downloader defaults to VTT files.  Media Player Classic literally refuses to play these.  Telling it to open them and it just no error message, just nothing.

Literally NOTHING can use VTT files.

So I see you have an option "--convert-subs FORMAT            Convert the subtitles to other format (currently supported: srt|ass|vtt)"

--convert-subs does not work

youtube-dl.exe --skip-download --all-subs --convert-subs srt http://www.tg4.ie/en/player/home/?pid=5270422774001
Another VTT file!

youtube-dl.exe --convert-subs srt --skip-download --all-subs http://www.tg4.ie/en/player/home/?pid=5270422774001
Another VTT file!

Well the cryptic instructions say lowercase so I try uppercase.
youtube-dl.exe --convert-subs SRT --skip-download --all-subs http://www.tg4.ie/en/player/home/?pid=5270422774001

So it spits out "youtube-dl.exe: error: invalid subtitle format specified"
Then quits!

So it literally notices it!  It notices that I told it "srt" when I did.  And each time, it reads it and DECIDES it's just going to not do it's job!  And it filters very specifically for certain options.  Even uppercase won't work!  And then after filtering, it REFUSES OUTRIGHT TOTALLY to actually do a basic thing of actually making a srt file instead of vtt.

I try:
youtube-dl.exe --convert-subs ass --skip-download --all-subs http://www.tg4.ie/en/player/home/?pid=5270422774001
And again it ends with
"[info] Writing video subtitles to: EIPIC - 1 Sully-5270422774001.en.vtt"

The program filters for three specific subtitle format options and then in the end DECIDES to just do a VTT file each time anyway.

And it's not simply naming it "vtt" and doing the format it's actually told.  The file starts with "WEBVTT" and its in VTT format.

If you want full printouts, then here:
------------------------------------------------------------

youtube-dl.exe --skip-download --all-subs --convert-subs srt http://www.tg4.ie/en/player/home/?pid=5270422774001

[generic] ?pid=5270422774001: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?pid=5270422774001: Downloading webpage
[generic] ?pid=5270422774001: Extracting information
[download] Downloading playlist: EIPIC | Baile | Seinnteoir | TG4
[generic] playlist EIPIC | Baile | Seinnteoir | TG4: Collected 1 video ids (down
loading 1 of them)
[download] Downloading video 1 of 1
[brightcove:new] 5270422774001: Downloading webpage
[brightcove:new] 5270422774001: Downloading JSON metadata
[brightcove:new] 5270422774001: Downloading m3u8 information
[info] Writing video subtitles to: EIPIC - 1 Sully-5270422774001.en.vtt
[download] Finished downloading playlist: EIPIC | Baile | Seinnteoir | TG4

...

youtube-dl.exe --convert-subs srt --skip-download --all-subs http://www.tg4.ie/en/player/home/?pid=5270422774001

[generic] ?pid=5270422774001: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?pid=5270422774001: Downloading webpage
[generic] ?pid=5270422774001: Extracting information
[download] Downloading playlist: EIPIC | Baile | Seinnteoir | TG4
[generic] playlist EIPIC | Baile | Seinnteoir | TG4: Collected 1 video ids (down
loading 1 of them)
[download] Downloading video 1 of 1
[brightcove:new] 5270422774001: Downloading webpage
[brightcove:new] 5270422774001: Downloading JSON metadata
[brightcove:new] 5270422774001: Downloading m3u8 information
[info] Writing video subtitles to: EIPIC - 1 Sully-5270422774001.en.vtt
[download] Finished downloading playlist: EIPIC | Baile | Seinnteoir | TG4

...

Notice it is filtering the stuff very carefully looking for three values.  If I do uppercase, it refuses:

youtube-dl.exe --convert-subs SRT --skip-download --all-subs http://www.tg4.ie/en/player/home/?pid=5270422774001

Usage: youtube-dl.exe [OPTIONS] URL [URL...]

youtube-dl.exe: error: invalid subtitle format specified

Or

youtube-dl.exe --convert-subs test --skip-download --all-subs http://www.tg4.ie/en/player/home/?pid=5270422774001

Usage: youtube-dl.exe [OPTIONS] URL [URL...]

youtube-dl.exe: error: invalid subtitle format specified

...

Using the "ass" file, the program also only makes a VTT file

youtube-dl.exe --convert-subs ass --skip-download --all-subs http://www.tg4.ie/en/player/home/?pid=5270422774001

[generic] ?pid=5270422774001: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?pid=5270422774001: Downloading webpage
[generic] ?pid=5270422774001: Extracting information
[download] Downloading playlist: EIPIC | Baile | Seinnteoir | TG4
[generic] playlist EIPIC | Baile | Seinnteoir | TG4: Collected 1 video ids (down
loading 1 of them)
[download] Downloading video 1 of 1
[brightcove:new] 5270422774001: Downloading webpage
[brightcove:new] 5270422774001: Downloading JSON metadata
[brightcove:new] 5270422774001: Downloading m3u8 information
[info] Writing video subtitles to: EIPIC - 1 Sully-5270422774001.en.vtt
[download] Finished downloading playlist: EIPIC | Baile | Seinnteoir | TG4

...

If I repeatedly tell it a million times "--convert-subs srt"

youtube-dl.exe --convert-subs srt --convert-subs srt --convert-subs srt --convert-subs srt --skip-download --all-subs http://www.tg4.ie/en/player/home/?pid=5270422774001 --convert-subs srt --convert-subs srt --convert-subs srt --convert-subs srt --convert-subs srt --convert-subs srt --convert-subs srt --convert-subs srt --convert-subs srt --convert-subs srt --convert-subs srt --convert-subs srt --convert-subs srt --convert-subs srt --convert-subs srt

[generic] ?pid=5270422774001: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?pid=5270422774001: Downloading webpage
[generic] ?pid=5270422774001: Extracting information
[download] Downloading playlist: EIPIC | Baile | Seinnteoir | TG4
[generic] playlist EIPIC | Baile | Seinnteoir | TG4: Collected 1 video ids (down
loading 1 of them)
[download] Downloading video 1 of 1
[brightcove:new] 5270422774001: Downloading webpage
[brightcove:new] 5270422774001: Downloading JSON metadata
[brightcove:new] 5270422774001: Downloading m3u8 information
[info] Writing video subtitles to: EIPIC - 1 Sully-5270422774001.en.vtt
[download] Finished downloading playlist: EIPIC | Baile | Seinnteoir | TG4

**Comment by dstftw** [comment] 2017-02-20 06:26
Duplicate of #9073.

**Closed by dstftw** 2017-02-20 06:26 UTC
