### ISSUE TITLE
instagram: allow downloading images

### ISSUE THREAD

**Issue by pabs3** [rg3/youtube-dl#5741] opened 2015-05-18 09:34 UTC
It would be great if the instagram extractor supported downloading images as well as videos.

**Comment by jaimeMF** [comment] 2015-05-18 14:22
Duplicate of #3696 (see https://github.com/rg3/youtube-dl/issues/2157#issuecomment-32796488 for the reasons why won't add support for it (at least for now)).

**Closed by jaimeMF** 2015-05-18 14:22 UTC
