### ISSUE TITLE
Unable to download free Hulu videos.

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#11760] opened 2017-01-18 08:26 UTC
Example:

$  youtube-dl http://www.hulu.com/watch/455129                 [generic] 455129: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 455129: Downloading webpage
[generic] 455129: Extracting information
[generic] embed: Requesting header
WARNING: Falling back on generic information extractor.
[generic] embed: Downloading webpage
[generic] embed: Extracting information
ERROR: Unsupported URL: https://secure.hulu.com/embed.html?eid=nbO8sk3A3nRUj-upQ3pA0g
(SopelPython3)ant@ANTian:~/Downloads$ youtube-dl -v http://www.hulu.com/watch/455129               [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.hulu.com/watch/455129']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.01.16
[debug] Python version 3.4.2 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.7
[debug] exe versions: ffmpeg 3.2.2-1, ffprobe 3.2.2-1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 455129: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 455129: Downloading webpage
[generic] 455129: Extracting information
[generic] embed: Requesting header
WARNING: Falling back on generic information extractor.
[generic] embed: Downloading webpage
[generic] embed: Extracting information
ERROR: Unsupported URL: https://secure.hulu.com/embed.html?eid=nbO8sk3A3nRUj-upQ3pA0g
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 359, in extract
    return self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2534, in _real_e           xtract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://secure.hulu.com/embed.html?e           id=nbO8sk3A3nRUj-upQ3pA0g

**Comment by yan12125** [comment] 2017-01-18 10:07
Duplicate of #1629

**Closed by yan12125** 2017-01-18 10:07 UTC
