### ISSUE TITLE
Skipping DASH manifest: Cannot decrypt signature without player_url

### ISSUE THREAD

**Issue by Giorgi** [rg3/youtube-dl#13211] opened 2017-05-26 17:51 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.26*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.26**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--playlist-start', '72', '-x', '-v', '--playlist-end', '72', '--audio-format', 'mp3', '--ffmpeg-location', 'E:\\Software\\ffmpeg-20160828-a37e6dd-win64-static\\bin', '-i', 'https://www.youtube.com/playlist?list=PLEvBpmVv6nBd1QDPrIa447P1VhmndDqoX']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.05.26
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-81489-ga37e6dd, ffprobe N-81489-ga37e6dd
[debug] Proxy map: {}
[youtube:playlist] PLEvBpmVv6nBd1QDPrIa447P1VhmndDqoX: Downloading webpage
[download] Downloading playlist: gogochkuri
[youtube:playlist] playlist gogochkuri: Downloading 1 videos
[download] Downloading video 1 of 1
[youtube] lQPCWp2A_Rk: Downloading webpage
[youtube] lQPCWp2A_Rk: Downloading video info webpage
[youtube] lQPCWp2A_Rk: Extracting video information
WARNING: [youtube] lQPCWp2A_Rk: Skipping DASH manifest: ExtractorError('Cannot decrypt signature without player_url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[debug] Invoking downloader on 'https://r1---sn-h5bupjvh-ucnl.googlevideo.com/videoplayback?itag=251&clen=3424072&key=yt6&ipbits=0&initcwndbps=2136250&keepalive=yes&signature=81E00D13DF8D852FA758DF854112FD50AC5C3C06.577AF6E7D4128377D9DF68933032FEE063DE353E&dur=204.801&ei=7GYoWcPRMtXDc-_KqtgJ&gir=yes&lmt=1449600144650713&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&mv=m&mt=1495819894&ms=au&id=o-ACuIyNVTGeBoY0M458bO_385SdDU7VGRCyv87c-eVI0p&expire=1495841613&ip=46.49.96.189&mime=audio%2Fwebm&requiressl=yes&mn=sn-h5bupjvh-ucnl&pl=20&source=youtube&mm=31&ratebypass=yes'
[download] Destination: Elena feat. Danny Mazo - Senor Loco (Official Video)-lQPCWp2A_Rk.webm
[download] 100% of 3.27MiB in 00:00
[debug] ffmpeg command line: 'E:\Software\ffmpeg-20160828-a37e6dd-win64-static\bin\ffprobe' -show_streams 'file:Elena feat. Danny Mazo - Senor Loco (Official Video)-lQPCWp2A_Rk.webm'
[ffmpeg] Destination: Elena feat. Danny Mazo - Senor Loco (Official Video)-lQPCWp2A_Rk.mp3
[debug] ffmpeg command line: 'E:\Software\ffmpeg-20160828-a37e6dd-win64-static\bin\ffmpeg' -y -i 'file:Elena feat. Danny Mazo - Senor Loco (Official Video)-lQPCWp2A_Rk.webm' -vn -acodec libmp3lame -q:a 5 'file:Elena feat. Danny Mazo - Senor Loco (Official Video)-lQPCWp2A_Rk.mp3'
Deleting original file Elena feat. Danny Mazo - Senor Loco (Official Video)-lQPCWp2A_Rk.webm (pass -k to keep)
[download] Finished downloading playlist: gogochkuri
```

---

### Description of your *issue*, suggested solution and other information

When I ran the command to download some videos from the playlist the video gets downloaded but I also get a warning and the app suggests to report the issue so here it is.

**Comment by Hrxn** [comment] 2017-05-26 18:59
#13206 again?

**Comment by stefanos82** [comment] 2017-05-26 19:40
I can confirm this issue with the latest available version `2017.05.26`:

```bash
$ youtube-dl -cixw https://www.youtube.com/watch?v=DGw9kYSSTsk
[youtube] DGw9kYSSTsk: Downloading webpage
[youtube] DGw9kYSSTsk: Downloading video info webpage
[youtube] DGw9kYSSTsk: Extracting video information
WARNING: [youtube] DGw9kYSSTsk: Skipping DASH manifest: ExtractorError('Cannot decrypt signature without player_url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[download] Destination: Epic Hits _ 1-hour Best of Thomas Bergersen-DGw9kYSSTsk.webm
```

**Comment by Hrxn** [comment] 2017-05-26 19:42
Okay, from your log, the issue is with https://www.youtube.com/watch?v=lQPCWp2A_Rk ?

Cannot reproduce..

```
C:\Users\Hrxn>youtube-dl --ignore-config -v "https://www.youtube.com/watch?v=lQPCWp2A_Rk"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '-v', 'https://www.youtube.com/watch?v=lQPCWp2A_Rk']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.05.26
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-83152-gf7e9275, ffprobe N-83152-gf7e9275
[debug] Proxy map: {}
[youtube] lQPCWp2A_Rk: Downloading webpage
[youtube] lQPCWp2A_Rk: Downloading video info webpage
[youtube] lQPCWp2A_Rk: Extracting video information
[youtube] {22} signature length 43.45, html5 player vfluaMKo6
[youtube] {43} signature length 43.45, html5 player vfluaMKo6
[youtube] {18} signature length 43.45, html5 player vfluaMKo6
[youtube] {36} signature length 43.45, html5 player vfluaMKo6
[youtube] {17} signature length 43.45, html5 player vfluaMKo6
[youtube] {137} signature length 43.45, html5 player vfluaMKo6
[youtube] {248} signature length 43.45, html5 player vfluaMKo6
[youtube] {136} signature length 43.45, html5 player vfluaMKo6
[youtube] {247} signature length 43.45, html5 player vfluaMKo6
[youtube] {135} signature length 43.45, html5 player vfluaMKo6
[youtube] {244} signature length 43.45, html5 player vfluaMKo6
[youtube] {134} signature length 43.45, html5 player vfluaMKo6
[youtube] {243} signature length 43.45, html5 player vfluaMKo6
[youtube] {133} signature length 43.45, html5 player vfluaMKo6
[youtube] {242} signature length 43.45, html5 player vfluaMKo6
[youtube] {160} signature length 43.45, html5 player vfluaMKo6
[youtube] {278} signature length 43.45, html5 player vfluaMKo6
[youtube] {140} signature length 43.45, html5 player vfluaMKo6
[youtube] {171} signature length 43.45, html5 player vfluaMKo6
[youtube] {249} signature length 43.45, html5 player vfluaMKo6
[youtube] {250} signature length 43.45, html5 player vfluaMKo6
[youtube] {251} signature length 43.45, html5 player vfluaMKo6
[youtube] lQPCWp2A_Rk: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r3---sn-8vq54voxqx-4g5e.googlevideo.com/videoplayback?id=9503c25a9d80fd19&itag=137&source=youtube&requiressl=yes&pl=20&initcwndbps=825000&pcm2cms=yes&mm=31&mv=m&ei=84QoWb63LcGWWce6i-AO&ms=au&mn=sn-8vq54voxqx-4g5e&ratebypass=yes&mime=video/mp4&gir=yes&clen=76122110&lmt=1458204195291855&dur=204.800&signature=859C877C1CD5793FD43AAC95275D8C8EFE762B30.97D874637C608C1C4B009D0C2BFE855F687DF502&key=dg_yt0&mt=1495827328&ip=92.75.235.106&ipbits=0&expire=1495849299&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,initcwndbps,pcm2cms,mm,mv,ei,ms,mn,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Elena feat. Danny Mazo - Senor Loco (Official Video)-lQPCWp2A_Rk.f137.mp4
[download] 100% of 72.60MiB in 00:14
[debug] Invoking downloader on 'https://r3---sn-8vq54voxqx-4g5e.googlevideo.com/videoplayback?ipbits=0&clen=3424072&initcwndbps=825000&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Crequiressl%2Csource%2Cexpire&pcm2cms=yes&mime=audio%2Fwebm&key=yt6&gir=yes&requiressl=yes&dur=204.801&source=youtube&lmt=1449600144650713&expire=1495849298&itag=251&mn=sn-8vq54voxqx-4g5e&mm=31&id=o-AJ_m6lRoQq3alxXRtdr2qr8lPiCrzig0cPOIO3XBDQMy&keepalive=yes&ip=92.75.235.106&pl=20&mv=m&mt=1495827328&ms=au&ei=8oQoWZfQMobCWeLQqbAI&signature=95E2B1E7C2B9DC30C0E725ECC7EE8F98510B9636.9ACC44E7163AFEA9CD9B7A70E863C02874052820&ratebypass=yes'
[download] Destination: Elena feat. Danny Mazo - Senor Loco (Official Video)-lQPCWp2A_Rk.f251.webm
[download] 100% of 3.27MiB in 00:01
[ffmpeg] Merging formats into "Elena feat. Danny Mazo - Senor Loco (Official Video)-lQPCWp2A_Rk.mkv"
[debug] ffmpeg command line: ffmpeg -y -i 'file:Elena feat. Danny Mazo - Senor Loco (Official Video)-lQPCWp2A_Rk.f137.mp4' -i 'file:Elena feat. Danny Mazo - Senor Loco (Official Video)-lQPCWp2A_Rk.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:Elena feat. Danny Mazo - Senor Loco (Official Video)-lQPCWp2A_Rk.temp.mkv'
Deleting original file Elena feat. Danny Mazo - Senor Loco (Official Video)-lQPCWp2A_Rk.f137.mp4 (pass -k to keep)
Deleting original file Elena feat. Danny Mazo - Senor Loco (Official Video)-lQPCWp2A_Rk.f251.webm (pass -k to keep)

C:\Users\Hrxn>
```

**Comment by Hrxn** [comment] 2017-05-26 19:44
https://www.youtube.com/watch?v=DGw9kYSSTsk

Works as well...

```bat
C:\Users\Hrxn>youtube-dl --ignore-config -v "https://www.youtube.com/watch?v=DGw9kYSSTsk"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '-v', 'https://www.youtube.com/watch?v=DGw9kYSSTsk']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.05.26
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-83152-gf7e9275, ffprobe N-83152-gf7e9275
[debug] Proxy map: {}
[youtube] DGw9kYSSTsk: Downloading webpage
[youtube] DGw9kYSSTsk: Downloading video info webpage
[youtube] DGw9kYSSTsk: Extracting video information
WARNING: unable to extract uploader nickname
[youtube] {22} signature length 43.45, html5 player en_US-vfln4CLQY
[youtube] DGw9kYSSTsk: Downloading player https://www.youtube.com/yts/jsbin/player-en_US-vfln4CLQY/base.js
[youtube] {43} signature length 43.45, html5 player en_US-vfln4CLQY
[youtube] {18} signature length 43.45, html5 player en_US-vfln4CLQY
[youtube] {36} signature length 43.45, html5 player en_US-vfln4CLQY
[youtube] {17} signature length 43.45, html5 player en_US-vfln4CLQY
[youtube] {136} signature length 43.45, html5 player en_US-vfln4CLQY
[youtube] {247} signature length 43.45, html5 player en_US-vfln4CLQY
[youtube] {135} signature length 43.45, html5 player en_US-vfln4CLQY
[youtube] {244} signature length 43.45, html5 player en_US-vfln4CLQY
[youtube] {134} signature length 43.45, html5 player en_US-vfln4CLQY
[youtube] {243} signature length 43.45, html5 player en_US-vfln4CLQY
[youtube] {133} signature length 43.45, html5 player en_US-vfln4CLQY
[youtube] {242} signature length 43.45, html5 player en_US-vfln4CLQY
[youtube] {160} signature length 43.45, html5 player en_US-vfln4CLQY
[youtube] {278} signature length 43.45, html5 player en_US-vfln4CLQY
[youtube] {140} signature length 43.45, html5 player en_US-vfln4CLQY
[youtube] {171} signature length 43.45, html5 player en_US-vfln4CLQY
[youtube] {249} signature length 43.45, html5 player en_US-vfln4CLQY
[youtube] {250} signature length 43.45, html5 player en_US-vfln4CLQY
[youtube] {251} signature length 43.45, html5 player en_US-vfln4CLQY
[youtube] DGw9kYSSTsk: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r1---sn-8vq54voxqx-4g5e.googlevideo.com/videoplayback?id=0c6c3d9184924ec9&itag=136&source=youtube&requiressl=yes&initcwndbps=805000&mm=31&mn=sn-8vq54voxqx-4g5e&pcm2cms=yes&ms=au&mv=m&pl=20&ei=aoUoWeLDEtLRcpmjnegG&ratebypass=yes&mime=video/mp4&gir=yes&clen=225582965&lmt=1435925186308897&dur=4187.349&mt=1495827746&signature=1767579FB3E0BF2317A02C1313F4F9F47948AD0C.45F3416EBE60913AFE0FBFE6A0034349EA1BDBFC&key=dg_yt0&ip=92.75.235.106&ipbits=0&expire=1495849418&sparams=ip,ipbits,expire,id,itag,source,requiressl,initcwndbps,mm,mn,pcm2cms,ms,mv,pl,ei,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Epic Hits _ 1-hour Best of Thomas Bergersen-DGw9kYSSTsk.f136.mp4
[download]  24.1% of 215.13MiB at  4.90MiB/s ETA 00:33
ERROR: Interrupted by user

C:\Users\Hrxn>
```

**Comment by stefanos82** [comment] 2017-05-26 19:45
I have forgot to mention my specs:

```bash
GNU / Linux Debian testing, 64-bit fully updated
Python 3.6.1
```

**Comment by stefanos82** [comment] 2017-05-27 01:04
OK, by downgrading to version `2017.05.23` I don't get any problems.

Does this help a bit?

**Comment by Hrxn** [comment] 2017-05-27 01:54
Yeah, expected. Older versions skip (partially) the DASH manifest, but this was changed because some formats apparently require to use it.

Not sure what this new issue is again, probably the same as before, we need to narrow it down a bit first.

**Comment by yan12125** [comment] 2017-05-27 11:54
For those who got this warning, please run ```youtube-dl --write-pages "the video URL"``` and upload all *.dump files.

**Comment by stefanos82** [comment] 2017-05-27 13:34
@yan12125 you mean to upload their content here or to upload somewhere the .dump files and share the URL here?

**Comment by yan12125** [comment] 2017-05-27 13:56
@stefanos82: Better to upload somewhere else and paste the link. Github's file uploading is not quite stable in my experience.

**Comment by stefanos82** [comment] 2017-05-27 14:08
Here you go:

[DGw9kYSSTsk_https_-_www.youtube.com_get_video_info.dump](https://pastebin.com/ivkhpLNR)

[DGw9kYSSTsk_https_-_www.youtube.com_watchv=DGw9kYSSTsk_gl=US_hl=en_has_verified=1_bpctr=9999999999.dump](https://pastebin.com/EVcmYsVS)

**Comment by yan12125** [comment] 2017-05-28 12:21
Thanks for the report, especially @stefanos82's dump files. This issue should be fixed in the next version. If there are still problems, feel free to open a new issue.

**Closed** 2017-05-28 12:21 UTC
Labels: bug

**Comment by Hrxn** [comment] 2017-05-28 13:17
@yan12125 Any idea why I didn't get this error message on Windows?

**Comment by yan12125** [comment] 2017-05-28 14:25
@Hrxn: This only occurs if in-page format URLs do not use encrypted signatures. In most cases URLs are encrypted; only in a few cases URLs can be used directly - that's determined by YouTube servers. Actually, I've never got unencrypted URLs, either.
