### ISSUE TITLE
can't download http://www.theatlantic.com/video/index/417309/our-place-in-the-universe/

### ISSUE THREAD

**Issue by hub2git** [rg3/youtube-dl#8676] opened 2016-02-27 05:01 UTC
``` 

> $ youtube-dl -v http://www.theatlantic.com/video/iframe/417309
> [debug] System config: []
> [debug] User config: []
> [debug] Command-line args: [u'-v', u'http://www.theatlantic.com/video/iframe/417309']
> [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2016.02.22
> [debug] Python version 2.7.6 - Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.2-rafaela
> [debug] exe versions: avconv 9.18-6, avprobe 9.18-6, rtmpdump 2.4
> [debug] Proxy map: {}
> [generic] 417309: Requesting header
> [redirect] Following redirect to http://www.theatlantic.com/video/iframe/417309/
> [generic] 417309: Requesting header
> WARNING: Falling back on generic information extractor.
> [generic] 417309: Downloading webpage
> [generic] 417309: Extracting information
> ERROR: Unsupported URL: http://www.theatlantic.com/video/iframe/417309/
> Traceback (most recent call last):
>   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1308, in _real_extract
>     doc = compat_etree_fromstring(webpage.encode('utf-8'))
>   File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 248, in compat_etree_fromstring
>     doc = _XML(text, parser=etree.XMLParser(target=etree.TreeBuilder(element_factory=_element_factory)))
>   File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 237, in _XML
>     parser.feed(text)
>   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
>     self._raiseerror(v)
>   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
>     raise err
> ParseError: not well-formed (invalid token): line 4, column 452
> Traceback (most recent call last):
>   File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 666, in extract_info
>     ie_result = ie.extract(url)
>   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 316, in extract
>     return self._real_extract(url)
>   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1950, in _real_extract
>     raise UnsupportedError(url)
> UnsupportedError: Unsupported URL: http://www.theatlantic.com/video/iframe/417309/

```

**Comment by yan12125** [comment] 2016-02-27 06:16
Duplicate of #6611. Before this site is supported you can use the following command to download this video:
```
youtube-dl -v "https://players.brightcove.net/29913724001/eaa660ba-a0a1-4f20-a2cc-4dbac4df45fe_default/index.html?videoId=4631792995001"
```

**Closed by yan12125** 2016-02-27 06:16 UTC
