### ISSUE TITLE
Can i download video with range parametar and how ?

### ISSUE THREAD

**Issue by sianbg** [rg3/youtube-dl#4789] opened 2015-01-27 09:18 UTC
Hello. Can i download a video from youtube like downloading start from 500B to 2500B or from 20s to 1m2s ?

**Comment by jaimeMF** [comment] 2015-01-27 09:21
It's not supported yet. Closing as a duplicate of #622 (you can subscribe to that issue to receive notifications).

**Closed by jaimeMF** 2015-01-27 09:21 UTC
