### ISSUE TITLE
Add support for animation.filmarchives.jp/works

### ISSUE THREAD

**Issue by gurugurumaguru** [rg3/youtube-dl#12340] opened 2017-03-03 07:55 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.02*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video (it is a silent film): http://animation.filmarchives.jp/works/play/72126
- Single video (it is a silent film) with English subtitles: http://animation.filmarchives.jp/works/playen/5226
- Single video with audio and with English subtitles: http://animation.filmarchives.jp/works/playen/5141 

They are all from http://animation.filmarchives.jp/works , there are 64 videos total I am trying to download/save/archive.

---

### Description of your *issue*, suggested solution and other information

The videos seems to be .m4s segments. I heard some Vimeo videos are like that and since we support Vimeo, I think it's feasible to configure support for this site too. I tried InviDownloader and it failed with the same error as a recent youtube commentator on its creator's tutorial video.

**Comment by dstftw** [comment] 2017-03-03 15:17
Duplicate of #12237.

**Closed by dstftw** 2017-03-03 15:17 UTC
