### ISSUE TITLE
Unable to download finalbosses.com's videos.

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#7412] opened 2015-11-09 23:39 UTC
For an example: 
$ youtube-dl -v http://finalbosses.com/game-music-sack-is-some-video-game-music-plagiarized/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://finalbosses.com/game-music-sack-is-some-video-game-music-plagiarized/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.02
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.9
[debug] exe versions: avconv 1.2.12, avprobe 1.2.12, ffmpeg 1.2.12, ffprobe 1.2.12, rtmpdump 2.4
[debug] Proxy map: {}
[generic] game-music-sack-is-some-video-game-music-plagiarized: Requesting header
WARNING: Falling back on generic information extractor.
[generic] game-music-sack-is-some-video-game-music-plagiarized: Downloading webpage
[generic] game-music-sack-is-some-video-game-music-plagiarized: Extracting information
ERROR: no suitable InfoExtractor for URL //player2.screenwavemedia.com/player.php?id=gamesack-56383b394d268
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ant/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/home/ant/bin/youtube-dl/youtube_dl/__init__.py", line 410, in main
    _real_main(argv)
  File "/home/ant/bin/youtube-dl/youtube_dl/__init__.py", line 400, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1666, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 672, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 725, in process_ie_result
    extra_info=extra_info)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 687, in extract_info
    self.report_error('no suitable InfoExtractor for URL %s' % url)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 536, in report_error
    self.trouble(error_message, tb)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 498, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

Thank you in advance. :)

**Comment by jaimeMF** [comment] 2015-11-10 18:07
Duplicate of #6739.

**Closed by jaimeMF** 2015-11-10 18:07 UTC
