### ISSUE TITLE
"--autonumber-start [number]" to begin autonumbering at a non-zero number (feature request)

### ISSUE THREAD

**Issue by JewsOfHazard** [rg3/youtube-dl#10457] opened 2016-08-28 08:02 UTC
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.28*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.28**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

"--autonumber-start [number]" to begin autonumbering at a non-zero number 

For example

`youtube-dl --yes-playlist -o /Some/Volume/%(title)s_s01e%(autonumber)s.%(ext)s --autonumber-start 16 "http://yourfavoriteurl.com/id/videoid"` 

And then the first file would be:

> Foo-bar_s01e00016.mkv

**Comment by yan12125** [comment] 2016-08-28 08:16
Duplicate of #727.

**Closed by yan12125** 2016-08-28 08:16 UTC

**Comment by JewsOfHazard** [comment] 2016-08-28 08:19
@yan12125 It isn't the same because I want to download multiple playlists into one "season" so to speak. That way I can download 12 episodes from one playlist and pick up where I left off on another url. I don't think you can do that with %(playlist_index)s

**Comment by yan12125** [comment] 2016-08-28 08:24
In #727 ```%(playlist_index)s``` is mentioned as a workaround for some cases. Later it's proved to be insufficient, so #727 is left opened. You can try #9362, though it's broken in some cases.
