### ISSUE TITLE
[youtube] Cannot identify player

### ISSUE THREAD

**Issue by keevee09** [rg3/youtube-dl#6410] opened 2015-07-30 17:20 UTC
tony@Macintosh:~/Music$ youtube-dl -U
Updating to version 2015.07.28 ...
Updated youtube-dl. Restart youtube-dl to use the new version.
tony@Macintosh:~/Music$ youtube-dl HFWKJ2FUiAQ
[youtube] HFWKJ2FUiAQ: Downloading webpage
[youtube] HFWKJ2FUiAQ: Downloading video info webpage
[youtube] HFWKJ2FUiAQ: Extracting video information
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 700, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 592, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfliLjLvh/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfliLjLvh/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
tony@Macintosh:~/Music$ youtube-dl https://www.youtube.com/watch?v=HFWKJ2FUiAQ
[youtube] HFWKJ2FUiAQ: Downloading webpage
[youtube] HFWKJ2FUiAQ: Downloading video info webpage
[youtube] HFWKJ2FUiAQ: Extracting video information
[youtube] HFWKJ2FUiAQ: Downloading js player en_US-vflGx3XCd
[youtube] HFWKJ2FUiAQ: Downloading DASH manifest
[download] Destination: This Mortal Coil - Song To The Siren (Official Video)-HFWKJ2FUiAQ.f135.mp4
[download] 100% of 12.49MiB in 00:08
[download] Destination: This Mortal Coil - Song To The Siren (Official Video)-HFWKJ2FUiAQ.f141.m4a
[download] 100% of 6.35MiB in 00:04
[ffmpeg] Merging formats into "This Mortal Coil - Song To The Siren (Official Video)-HFWKJ2FUiAQ.mp4"
Deleting original file This Mortal Coil - Song To The Siren (Official Video)-HFWKJ2FUiAQ.f135.mp4 (pass -k to keep)
Deleting original file This Mortal Coil - Song To The Siren (Official Video)-HFWKJ2FUiAQ.f141.m4a (pass -k to keep)
tony@Macintosh:~/Music$

**Comment by keevee09** [comment] 2015-07-30 17:21
After this downloading the full http address for the same video worked fine.

**Comment by silver659** [comment] 2015-08-02 17:05
@keevee09 use verbose mode '-v'
it worked fine to me:
```
youtube-dl -v HFWKJ2FUiAQ
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'HFWKJ2FUiAQ']
[debug] Encodings: locale cp1252, fs mbcs, out None, pref cp1252
[debug] youtube-dl version 2015.07.28
[debug] Python version 2.7.8 - Windows-7-6.1.7600
[debug] exe versions: ffmpeg N-74199-gb27d4fd, ffprobe N-60274-gdce9321
[debug] Proxy map: {}
[youtube] HFWKJ2FUiAQ: Downloading webpage
[youtube] HFWKJ2FUiAQ: Downloading video info webpage
[youtube] HFWKJ2FUiAQ: Extracting video information
[youtube] {43} signature length 40.40, html5 player en_US-vflGx3XCd
[youtube] {18} signature length 40.40, html5 player en_US-vflGx3XCd
[youtube] {5} signature length 40.40, html5 player en_US-vflGx3XCd
[youtube] {36} signature length 40.40, html5 player en_US-vflGx3XCd
[youtube] {17} signature length 40.40, html5 player en_US-vflGx3XCd
[youtube] {135} signature length 40.40, html5 player en_US-vflGx3XCd
[youtube] {244} signature length 40.40, html5 player en_US-vflGx3XCd
[youtube] {134} signature length 40.40, html5 player en_US-vflGx3XCd
[youtube] {243} signature length 40.40, html5 player en_US-vflGx3XCd
[youtube] {133} signature length 40.40, html5 player en_US-vflGx3XCd
[youtube] {242} signature length 40.40, html5 player en_US-vflGx3XCd
[youtube] {160} signature length 40.40, html5 player en_US-vflGx3XCd
[youtube] {140} signature length 40.40, html5 player en_US-vflGx3XCd
[youtube] {171} signature length 40.40, html5 player en_US-vflGx3XCd
[youtube] HFWKJ2FUiAQ: Downloading DASH manifest
[debug] Invoking downloader on 'https://r1---sn-cg51pauxax-4aol.googlevideo.com/videoplayback?id=1c558a2761548804&itag=135&source=youtube&requiressl=yes&pl=19&ms=au&mv=m&mn=sn-cg51pauxax-4aol&mm=31&pcm2cms=yes&ratebypass=yes&mime=video/mp4&gir=yes&clen=13093473&lmt=1417229274194488&dur=208.720&sver=3&signature=6AE521E6B3F383F48589D78F3137C2E6E865C560.7D420A71BDA0F4EACF64B71CBB1203B6B5634C63&upn=gSZtApNwZ4c&key=dg_yt0&mt=1438534298&fexp=9407538,9408497,9408710,9409171,9413148,9415089,9415365,9415485,9416126,9416729,9417206,9417911,9418204,9418427&ip=177.2.49.241&ipbits=0&expire=1438556020&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,ms,mv,mn,mm,pcm2cms,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: This Mortal Coil - Song To The Siren (Official Video)-HFWKJ2FUiAQ.f135.mp4
[download] 100% of 12.49MiB in 04:29
[debug] Invoking downloader on 'https://r1---sn-cg51pauxax-4aol.googlevideo.com/videoplayback?id=1c558a2761548804&itag=141&source=youtube&requiressl=yes&pl=19&ms=au&mv=m&mn=sn-cg51pauxax-4aol&mm=31&pcm2cms=yes&ratebypass=yes&mime=audio/mp4&gir=yes&clen=6658191&lmt=1417229246853289&dur=208.817&sver=3&signature=7F6DDE0A7A240A9AA41841A06A552A0D8E50E940.752FDB54FB8330DAF19972665FB23B50BD83B212&upn=gSZtApNwZ4c&key=dg_yt0&mt=1438534298&fexp=9407538,9408497,9408710,9409171,9413148,9415089,9415365,9415485,9416126,9416729,9417206,9417911,9418204,9418427&ip=177.2.49.241&ipbits=0&expire=1438556020&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,ms,mv,mn,mm,pcm2cms,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: This Mortal Coil - Song To The Siren (Official Video)-HFWKJ2FUiAQ.f141.m4a
[download] 100% of 6.35MiB in 01:58
[ffmpeg] Merging formats into "This Mortal Coil - Song To The Siren (Official Video)-HFWKJ2FUiAQ.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'This Mortal Coil - Song To The Siren (Official Video)-HFWKJ2FUiAQ.f135.mp4' -i 'This Mortal Coil - Song To The Siren (Official Video)-HFWKJ2FUiAQ.f141.m4a' -c copy -map 0:v:0 -map 1:a:0 'This Mortal Coil - Song To The Siren (Official Video)-HFWKJ2FUiAQ.temp.mp4'
Deleting original file This Mortal Coil - Song To The Siren (Official Video)-HFWKJ2FUiAQ.f135.mp4 (pass -k to keep)
Deleting original file This Mortal Coil - Song To The Siren (Official Video)-HFWKJ2FUiAQ.f141.m4a (pass -k to keep)
```

**Comment by mariomaric** [comment] 2015-11-10 10:04
Hi to all. I believe I have the same issue, can somebody try to reproduce it, please. Thx.

```
[debug] System config: []
[debug] User config: [u'--rate-limit', u'450K', u'--download-archive', u'/home/mama/.config/youtube-dl/archive', u'--prefer-ffmpeg']
[debug] Command-line args: [u'--verbose', u'-x', u'--audio-format', u'mp3', u'https://www.youtube.com/watch?v=iij6Wr8uP-w']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2015.11.02
[debug] Python version 2.7.3 - Linux-3.13.0-67-generic-x86_64-with-Ubuntu-12.04-precise
[debug] exe versions: avconv 0.8.17-4, avprobe 0.8.17-4, ffmpeg 2.5.3-, ffprobe 2.5.3-
[debug] Proxy map: {}
[youtube] iij6Wr8uP-w: Downloading webpage
[youtube] iij6Wr8uP-w: Downloading video info webpage
[youtube] iij6Wr8uP-w: Extracting video information
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {43} signature length 40.44, html5 player None
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 709, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 709, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1345, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 827, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 709, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by riconeitzel** [comment] 2015-11-10 10:25
I do have this issue with just *a few* youtube links

```sh
youtube-dl https://www.youtube.com/watch\?v\=i0A3-wc0rpw\&list\=PLKPi39tTpkdpjBVQZo5oFLWjFjlOMkd2A -v        
[debug] System config: []
[debug] User config: [u'-f', u'138+141/138+140/138+139/266+141/266+140/266+139/264+141/264+140/264+139/137+141/137+140/137+139/136+141/136+140/136+139/22+141/22+140/22+139/135+141/135+140/135+139/134+141/134+140/134+139/133+141/133+140/133+139/best']
[debug] Command-line args: [u'https://www.youtube.com/watch?v=i0A3-wc0rpw&list=PLKPi39tTpkdpjBVQZo5oFLWjFjlOMkd2A', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.02
[debug] Python version 2.7.10 - Darwin-15.0.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8, ffprobe 2.8, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist PLKPi39tTpkdpjBVQZo5oFLWjFjlOMkd2A - add --no-playlist to just download video i0A3-wc0rpw
[youtube:playlist] PLKPi39tTpkdpjBVQZo5oFLWjFjlOMkd2A: Downloading webpage
[download] Downloading playlist: 24 Hours of Happy
[youtube:playlist] playlist 24 Hours of Happy: Downloading 24 videos
[download] Downloading video 1 of 24
[youtube] i0A3-wc0rpw: Downloading webpage
[youtube] i0A3-wc0rpw: Downloading video info webpage
[youtube] i0A3-wc0rpw: Extracting video information
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {22} signature length 40.44, html5 player None
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 709, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 709, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1345, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 827, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 709, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Here it's about the 24hrs-of-happy Playlist from Pharell Williams (can be found here https://www.youtube.com/watch?v=i0A3-wc0rpw&list=PLOOFL6Fjn-oK91hhbNXkbN186WAs-3Cjs)

I already updated to the latest version and also tried to download the video online – always the same issue. Even tried to remove the https:// from the main url, while I'm not sure if it afffects the URL within the scraped player as well.

*willing to help test*

Best,
 Rico

**Comment by mariomaric** [comment] 2015-11-10 10:29
Yes, I forgot to mention, it only happens (at least for now) for specific videos, some other URLs that don't work:

```
https://www.youtube.com/watch?v=XeckmmNPwc8
https://www.youtube.com/watch?v=H7SeOai_DOo
https://www.youtube.com/watch?v=VqOaJZdhlUM
```

Willing to help also however I can.

**Comment by yan12125** [comment] 2015-11-10 10:59
The problem is fixed in version 2015.11.10. Have a look at [update instructions](https://github.com/rg3/youtube-dl#how-do-i-update-youtube-dl) if you have any problem.

**Closed by yan12125** 2015-11-10 10:59 UTC
Labels: bug

**Comment by riconeitzel** [comment] 2015-11-10 11:02
:+1: :bow: :-)

**Comment by mariomaric** [comment] 2015-11-10 11:08
It works like a charm, thanks a lot!

**Comment by bjmrey** [comment] 2017-04-28 20:03
Hi, this issue has just reappeared for me. It worked this morning, no longer now. Any clue?

> youtube-dl -v HFWKJ2FUiAQ
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'HFWKJ2FUiAQ']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.24
[debug] Python version 2.7.10 - Darwin-16.1.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.0.2, ffprobe 3.0.2
[debug] Proxy map: {}
[youtube] HFWKJ2FUiAQ: Downloading webpage
[youtube] HFWKJ2FUiAQ: Downloading video info webpage
[youtube] HFWKJ2FUiAQ: Extracting video information
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {43} signature length 40.40, html5 player None
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/youtube_dl/extractor/youtube.py", line 1064, in _decrypt_signature
    video_id, player_url, s
  File "/Library/Python/2.7/site-packages/youtube_dl/extractor/youtube.py", line 952, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/youtube_dl/extractor/youtube.py", line 1064, in _decrypt_signature
    video_id, player_url, s
  File "/Library/Python/2.7/site-packages/youtube_dl/extractor/youtube.py", line 952, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/Library/Python/2.7/site-packages/youtube_dl/extractor/common.py", line 427, in extract
    ie_result = self._real_extract(url)
  File "/Library/Python/2.7/site-packages/youtube_dl/extractor/youtube.py", line 1653, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/Library/Python/2.7/site-packages/youtube_dl/extractor/youtube.py", line 1074, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/youtube_dl/extractor/youtube.py", line 1064, in _decrypt_signature
    video_id, player_url, s
  File "/Library/Python/2.7/site-packages/youtube_dl/extractor/youtube.py", line 952, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment] 2017-04-28 20:08
@bjmrey update.
