### ISSUE TITLE
Unable to download the full episode from cwtv.com.

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#10742] opened 2016-09-24 05:21 UTC
$ youtube-dl -v http://cwtv.com/shows/masters-of-illusion/a-loaf-of-bread-a-magic-dollhouse-and-bound-by-music/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://cwtv.com/shows/masters-of-illusion/a-loaf-of-bread-a-magic-dollhouse-and-bound-by-music/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.24
[debug] Python version 3.4.2 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.6
[debug] exe versions: ffmpeg 3.0.2-4, ffprobe 3.0.2-4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] a-loaf-of-bread-a-magic-dollhouse-and-bound-by-music: Requesting header
WARNING: Falling back on generic information extractor.
[generic] a-loaf-of-bread-a-magic-dollhouse-and-bound-by-music: Downloading webpage
[generic] a-loaf-of-bread-a-magic-dollhouse-and-bound-by-music: Extracting information
WARNING: [generic] a-loaf-of-bread-a-magic-dollhouse-and-bound-by-music: Failed to parse JSON Invalid control character at: line 17 column 586 (char 1186)
[debug] Invoking downloader on 'http://cwtv.com/shows/masters-of-illusion/a-loaf-of-bread-a-magic-dollhouse-and-bound-by-music/'
[download] Destination: Masters of Illusion Video - A Loaf of Bread, a Magic Dollhouse, and Bound by Music _ Watch Online Free-.unknown_video
[download] 100% of 257.58KiB in 00:00

**Comment by yan12125** [comment] 2016-09-24 06:08
Duplicate of #8105. Currently only single videos are supported. To download the first video on this page, use this command:
```
youtube-dl http://cwtv.com/shows/masters-of-illusion/a-loaf-of-bread-a-magic-dollhouse-and-bound-by-music/?play=816177b4-066f-4484-b9d9-fc6fd5fefa1a
```

**Closed by yan12125** 2016-09-24 06:08 UTC
