### ISSUE TITLE
Provide a once-in-a-while Changelog

### ISSUE THREAD

**Issue by prof-milki** [rg3/youtube-dl#3440] opened 2014-08-04 19:35 UTC
Hey, can I enthuse anyone for summarizing some Changelog.txt/.md for keeping youtube-dl announcements current? Specifically for:
http://freshcode.club/projects/youtube-dl
(Also adaptable, still to OpenID-claim, etc.)

I tried to use gitlogs for automatic updates there. But that turned out to be somewhat uninformative (if you're not a developer, that is). Which is why I'm asking if somebody would consider updating a plain Changelog, with new feature or bugfix summeries. But really only every other release, or just monthly-something. (The implicit github /tags.atom or /releases or /releases.atom are too frequent anyway. Because they're obviously intended for `-U` app updates rather.)

Even as a long-time y-dl user I was also grossly unaware of how broad the video portal support has become meanwhile. And I'd assume I'm not alone, despite the nice git.io homepage. Which is where some publishing without much overhead might be cool.

**Comment by dstftw** [comment] 2016-04-11 14:01
Duplicate of #1626.

**Closed by dstftw** 2016-04-11 14:01 UTC
