### ISSUE TITLE
[iprima] broken

### ISSUE THREAD

**Issue by m4xe** [rg3/youtube-dl#7876] opened 2015-12-15 18:03 UTC
I can't download anything from play.iprima.cz anymore. Please help.

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://play.iprima.cz/particka-6', u'-v']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2015.12.13
[debug] Python version 2.7.10 - Windows-2012Server-6.2.9200
[debug] exe versions: ffmpeg N-70411-g7da7d26, rtmpdump 2.3
[debug] Proxy map: {}
[IPrima] particka-6: Downloading webpage
[IPrima] particka-6: Downloading webpage
ERROR: Unable to extract zoneGEO; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 663, in extract_info
  File "youtube_dl\extractor\common.pyo", line 290, in extract
  File "youtube_dl\extractor\iprima.pyo", line 68, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 593, in _html_search_regex
  File "youtube_dl\extractor\common.pyo", line 584, in _search_regex
RegexNotFoundError: Unable to extract zoneGEO; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment] 2015-12-15 19:00
Duplicate of #7617.

**Closed by dstftw** 2015-12-15 19:00 UTC
