### ISSUE TITLE
Youtube: 403 error on MPD manifest

### ISSUE THREAD

**Issue by DoctorVanGogh** [rg3/youtube-dl#12444] opened 2017-03-13 18:35 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.10*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
Youtube-dl got a 403 error on a MPD download, and told me to submit a bug request, so this is it 😁 

```
youtube-dl.exe https://www.youtube.com/watch?v=mjAYZs4SLlw --verbose
[debug] System config: []
[debug] User config: ['--ffmpeg-location', 'c:\\ffmpeg\\bin', '--external-downloader', 'aria2c', '--external-downloader-args', '-j 8 -s 8 -x 8 -k 5M']
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=mjAYZs4SLlw', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.03.10
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-83657-g7e4f32f, ffprobe N-83657-g7e4f32f
[debug] Proxy map: {}
[youtube] mjAYZs4SLlw: Downloading webpage
[youtube] mjAYZs4SLlw: Downloading video info webpage
[youtube] mjAYZs4SLlw: Extracting video information
[youtube] {22} signature length 40.40, html5 player en_US-vflclXGin
[youtube] {43} signature length 40.40, html5 player en_US-vflclXGin
[youtube] {18} signature length 40.40, html5 player en_US-vflclXGin
[youtube] {36} signature length 40.40, html5 player en_US-vflclXGin
[youtube] {17} signature length 40.40, html5 player en_US-vflclXGin
[youtube] {137} signature length 40.40, html5 player en_US-vflclXGin
[youtube] {248} signature length 40.40, html5 player en_US-vflclXGin
[youtube] {299} signature length 40.40, html5 player en_US-vflclXGin
[youtube] {303} signature length 40.40, html5 player en_US-vflclXGin
[youtube] {136} signature length 40.40, html5 player en_US-vflclXGin
[youtube] {247} signature length 40.40, html5 player en_US-vflclXGin
[youtube] {298} signature length 40.40, html5 player en_US-vflclXGin
[youtube] {302} signature length 40.40, html5 player en_US-vflclXGin
[youtube] {135} signature length 40.40, html5 player en_US-vflclXGin
[youtube] {244} signature length 40.40, html5 player en_US-vflclXGin
[youtube] {134} signature length 40.40, html5 player en_US-vflclXGin
[youtube] {243} signature length 40.40, html5 player en_US-vflclXGin
[youtube] {133} signature length 40.40, html5 player en_US-vflclXGin
[youtube] {242} signature length 40.40, html5 player en_US-vflclXGin
[youtube] {160} signature length 40.40, html5 player en_US-vflclXGin
[youtube] {278} signature length 40.40, html5 player en_US-vflclXGin
[youtube] {140} signature length 40.40, html5 player en_US-vflclXGin
[youtube] {171} signature length 40.40, html5 player en_US-vflclXGin
[youtube] {249} signature length 40.40, html5 player en_US-vflclXGin
[youtube] {250} signature length 40.40, html5 player en_US-vflclXGin
[youtube] {251} signature length 40.40, html5 player en_US-vflclXGin
[youtube] mjAYZs4SLlw: Downloading MPD manifest
WARNING: [youtube] mjAYZs4SLlw: Skipping DASH manifest: ExtractorError('Failed to download MPD manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on '*URLREMOVED*'
[download] Destination: Horizon Zero Dawn - Ep 32 - CAULDRON CORE AND STEALTH TRIALS - Let's Play Horizon Zero Dawn-mjAYZs4SLlw.f299.mp4
[debug] aria2c command line: aria2c -c -j 8 -s 8 -x 8 -k 5M --out 'Horizon Zero Dawn - Ep 32 - CAULDRON CORE AND STEALTH TRIALS - Let'"'"'s Play Horizon Zero Dawn-mjAYZs4SLlw.f299.mp4.part' --header 'Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7' --header 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)' --header 'Accept-Language: en-us,en;q=0.5' --header 'Accept-Encoding: gzip, deflate' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --check-certificate=true -- '*URLREMOVED*'
```

**Comment by dstftw** [comment] 2017-03-13 18:39
Duplicate of #8944.

**Closed by dstftw** 2017-03-13 18:39 UTC
