### ISSUE TITLE
[AdultSwim] Unable to extract bootstraped data.

### ISSUE THREAD

**Issue by ghost** [rg3/youtube-dl#11042] opened 2016-10-26 23:07 UTC
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.26**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
[AdultSwim] the-venture-bros: Downloading webpage
ERROR: Unable to extract bootstraped data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 356, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/adultswim.py", line 152, in _real_extract
    r'var bootstrappedData = ({.*});', webpage, 'bootstraped data'), episode_path)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 659, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract bootstraped data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

 http://www.adultswim.com/videos/streams/the-venture-bros

**Comment by yan12125** [comment] 2016-10-27 06:46
Duplicate of #10950

**Comment by stepshal** [comment] 2016-10-27 06:57
@yan12125 same with: http://www.adultswim.com/videos/toonami/friday-october-14th-2016/ from https://github.com/rg3/youtube-dl/issues/10979

**Comment by stepshal** [comment] 2016-11-05 13:40
@yan12125 it's issue after latest commit with the same video, that is test url right now:
http://www.adultswim.com/videos/toonami/friday-october-14th-2016/
Or new:
http://www.adultswim.com/videos/toonami/friday-october-28th-2016/

**Comment by yan12125** [comment] 2016-11-05 14:07
Seems they have changed the whole website. However, I can't watch any video on AdultSwim now. I guess they've applied geolocation restrictions.

**Comment by useless2764** [comment] 2016-11-22 23:15
this also seems to happen with other viacom sites, eg Spike

http://pastebin.com/8QHjzsgg

**Comment by yan12125** [comment] 2016-11-23 06:21
@useless2764 That's different, see #11148

**Closed** 2017-05-08 14:08 UTC
Labels: broken-IE
