### ISSUE TITLE
[go] Unable to extract post url; / Unable to download webpage

### ISSUE THREAD

**Issue by RuneMagle** [rg3/youtube-dl#15461] opened 2018-01-31 21:35 UTC
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.27**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
Without VPN:
C:\Users\rumag\Desktop\youtube-dl>py -3 -m youtube_dl --all-subs --ap-username USERANME --ap-passwordPASSWORD --ap-mso Comcast_SSO "http://watchdisneychannel.go.com/andi-mack/video/vdka4245399/02/102-andi-mack-cast-party" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--all-subs', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--ap-mso', 'Comcast_SSO', 'http://watchdisneychannel.go.com/andi-mack/video/vdka4245399/02/102-andi-mack-cast-party', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2018.01.27
[debug] Python version 3.6.4 (CPython) - Windows-10-10.0.16299-SP0
[debug] exe versions: ffmpeg N-86911-gb664d1f, ffprobe N-86911-gb664d1f, rtmpdump 2.4
[debug] Proxy map: {}
[Go] vdka4245399: Downloading JSON metadata
[Go] VDKA4245399: Downloading Provider Redirect Page
[Go] VDKA4245399: Logging in
[Go] VDKA4245399: Retrieving Session
ERROR: Unable to download webpage: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\rumag\Desktop\youtube-dl\youtube_dl\extractor\common.py", line 517, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\rumag\Desktop\youtube-dl\youtube_dl\YoutubeDL.py", line 2198, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Users\rumag\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\Users\rumag\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\rumag\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "C:\Users\rumag\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\rumag\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
----------
With VPN:
C:\Users\rumag\Desktop\youtube-dl>py -3 -m youtube_dl --all-subs --ap-username USERNAME --ap-password PASSWORD --ap-mso Comcast_SSO "http://watchdisneychannel.go.com/andi-mack/video/vdka4245399/02/102-andi-mack-cast-party" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--all-subs', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--ap-mso', 'Comcast_SSO', 'http://watchdisneychannel.go.com/andi-mack/video/vdka4245399/02/102-andi-mack-cast-party', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2018.01.27
[debug] Python version 3.6.4 (CPython) - Windows-10-10.0.16299-SP0
[debug] exe versions: ffmpeg N-86911-gb664d1f, ffprobe N-86911-gb664d1f, rtmpdump 2.4
[debug] Proxy map: {}
[Go] vdka4245399: Downloading JSON metadata
[Go] VDKA4245399: Downloading Provider Redirect Page
ERROR: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\rumag\Desktop\youtube-dl\youtube_dl\YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "C:\Users\rumag\Desktop\youtube-dl\youtube_dl\extractor\common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\rumag\Desktop\youtube-dl\youtube_dl\extractor\go.py", line 119, in _real_extract
    url, video_id, requestor_id, resource)
  File "C:\Users\rumag\Desktop\youtube-dl\youtube_dl\extractor\adobepass.py", line 1448, in _extract_mvpd_auth
    self._DOWNLOADING_LOGIN_PAGE)
  File "C:\Users\rumag\Desktop\youtube-dl\youtube_dl\extractor\adobepass.py", line 1360, in post_form
    post_url = self._html_search_regex(r'<form[^>]+action=(["\'])(?P<url>.+?)\1', form_page, 'post url', group='url')
  File "C:\Users\rumag\Desktop\youtube-dl\youtube_dl\extractor\common.py", line 803, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "C:\Users\rumag\Desktop\youtube-dl\youtube_dl\extractor\common.py", line 794, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

---
- Single video: http://watchdisneychannel.go.com/andi-mack/video/vdka4245399/02/102-andi-mack-cast-party

---

### Description of *issue*
I am unable to download videos on Watch Disney using Comcast Xfinity. Using VPN it does not go past login, but without VPN it does further, but still gives an error. I have tested it, and I can login just fine on the website.

**Comment by remitamine** [comment] 2018-01-31 21:42
Duplicate of #11257.
Duplicate of #11538.

**Closed by remitamine** 2018-01-31 21:42 UTC

**Comment by RuneMagle** [comment] 2018-01-31 21:49
Sorry for the duplicate. I tried searching, but didn't find those...
