### ISSUE TITLE
Can't download full video from tudou and youku

### ISSUE THREAD

**Issue by Loko0415** [rg3/youtube-dl#9838] opened 2016-06-20 07:06 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.06.19.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.19.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.06.19.1
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

I can't download full video from youku and tudou.

it only detects two parts of the video but the video should contain more than two parts (about 10-14 parts.)

Here is the debug info 
===============================================================================
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.tudou.com/albumplay/yjcmOqysUEc/
U9mhduR0hkg.html']
[debug] Encodings: locale cp950, fs mbcs, out cp65001, pref cp950
[debug] youtube-dl version 2016.06.19.1
[debug] Python version 2.7.11 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[tudou] U9mhduR0hkg: Downloading JSON metadata
[youku] XMTYxMzgxODU5Ng: Downloading JSON metadata
[download] Downloading playlist: Running Man 160619
[youku] playlist Running Man 160619: Collected 2 video ids (downloading 2 of the
m)
[download] Downloading video 1 of 2
[debug] Invoking downloader on u'http://k.youku.com/player/getFlvPath/sid/946640
582747212aa8c88_00/st/flv/fileid/030001160057677612C20A132D24F5E542B859-4EA9-BFE
F-38FC-6F44BBE94CCD?ypp=0&myp=0&K=ba75aa87e9c3c031261f13c2&ctype=12&token=4114&e
v=1&ep=eyaSHE2NU8YC4ifYij8bNn3qJ38HXP4J9h%2BFgNNkALshT%2B64njjQxe6yTo5DFfttcCZwF
Z70r9KVYkUdYfQ22GEQrTjdT%2Frj9oaQ5aslwJRyFGw%2Fdr6kwFSaQjH1&hd=1&oip=27875701'
[download] Running Man 160619-XMTYxMzgxODU5Ng_part1.flv has already been downloa
ded
[download] 100% of 55.31MiB
[download] Downloading video 2 of 2
[debug] Invoking downloader on u'http://k.youku.com/player/getFlvPath/sid/946640
582747212aa8c88_00/st/flv/fileid/030001160157677612C20A132D24F5E542B859-4EA9-BFE
F-38FC-6F44BBE94CCD?ypp=0&myp=0&K=0c77fbc0a5257315282b8210&ctype=12&token=4114&e
v=1&ep=eyaSHE2NU8YC4ifYij8bNn3qJ38HXP4J9h%2BFgNNkALohT%2B64njjQxe6yTo5DFfttcCZwF
Z70r9KVYkUdYfQ22GEQrTjdT%2Frj9oaQ5aslwJRyFGw%2Fdr6kwFSaQjH1&hd=1&oip=27875701'
[download] Running Man 160619-XMTYxMzgxODU5Ng_part2.flv has already been downloa
ded
[download] 100% of 50.44MiB
[download] Finished downloading playlist: Running Man 160619
```
===============================================================================
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://v.youku.com/v_show/id_XMTYxMzgxODU5N
g==.html']
[debug] Encodings: locale cp950, fs mbcs, out cp65001, pref cp950
[debug] youtube-dl version 2016.06.19.1
[debug] Python version 2.7.11 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youku] XMTYxMzgxODU5Ng: Downloading JSON metadata
[download] Downloading playlist: Running Man 160619
[youku] playlist Running Man 160619: Collected 2 video ids (downloading 2 of the
m)
[download] Downloading video 1 of 2
[debug] Invoking downloader on u'http://k.youku.com/player/getFlvPath/sid/146640
617281412d0a4d5_00/st/flv/fileid/030001160057677612C20A132D24F5E542B859-4EA9-BFE
F-38FC-6F44BBE94CCD?ypp=0&myp=0&K=bff78d3293d2ed7b2412a575&ctype=12&token=0924&e
v=1&ep=cyaSHE2NUM8H5yvejD8bMyyzcCMKXP4J9h%2BFgNNkALshT%2B64njjQxe6yTo5DFfttcCZwF
Z70r9KVYkUdYfQ22GEQrTjdT%2Frj9oaQ5aslwJRyFGw%2Fdr6kwFSeSjL1&hd=1&oip=27875701'
[download] Running Man 160619-XMTYxMzgxODU5Ng_part1.flv has already been downloa
ded
[download] 100% of 55.31MiB
[download] Downloading video 2 of 2
[debug] Invoking downloader on u'http://k.youku.com/player/getFlvPath/sid/146640
617281412d0a4d5_00/st/flv/fileid/030001160157677612C20A132D24F5E542B859-4EA9-BFE
F-38FC-6F44BBE94CCD?ypp=0&myp=0&K=0f1fdd4938ca7d0b2412a575&ctype=12&token=0924&e
v=1&ep=cyaSHE2NUM8H5yvejD8bMyyzcCMKXP4J9h%2BFgNNkALohT%2B64njjQxe6yTo5DFfttcCZwF
Z70r9KVYkUdYfQ22GEQrTjdT%2Frj9oaQ5aslwJRyFGw%2Fdr6kwFSeSjL1&hd=1&oip=27875701'
[download] Running Man 160619-XMTYxMzgxODU5Ng_part2.flv has already been downloa
ded
[download] 100% of 50.44MiB
[download] Finished downloading playlist: Running Man 160619
```

**Comment by yan12125** [comment] 2016-06-20 07:54
Duplicate of #8324. There's no solution to it yet.

**Closed by yan12125** 2016-06-20 07:54 UTC

**Comment by ckckchen** [comment] 2016-07-03 19:29
I met same situations here. And i tried out another tool called you-get, and this tool worked fine for youku.
