### ISSUE TITLE
download iqiyi error

### ISSUE THREAD

**Issue by xtqxk** [rg3/youtube-dl#12554] opened 2017-03-25 15:12 UTC
youtube-dl -v -F http://www.iqiyi.com/a_19rrha4rcx.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'http://www.iqiyi.com/a_19rrha4rcx.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.24
[debug] Python version 2.7.10 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[iqiyi] temp_id: download video page
[iqiyi] 205285101: Download playlist page 2
[download] Downloading playlist: 小蜜蜂寻母记 第1季
[iqiyi] playlist 小蜜蜂寻母记 第1季: Collected 91 video ids (downloading 91 of them)
[download] Downloading video 1 of 91
[iqiyi] temp_id: download video page
WARNING: unable to extract album title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[iqiyi] 205285101: Download playlist page 2
[download] Downloading playlist: 205285101
[iqiyi] playlist 205285101: Collected 51 video ids (downloading 51 of them)
[download] Downloading video 1 of 51
[iqiyi] temp_id: download video page
WARNING: unable to extract album title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[iqiyi] 202861101: Download playlist page 2
[iqiyi] 202861101: Download playlist page 3
[iqiyi] 202861101: Download playlist page 4
[iqiyi] 202861101: Download playlist page 5
[iqiyi] 202861101: Download playlist page 6
[iqiyi] 202861101: Download playlist page 7
[iqiyi] 202861101: Download playlist page 8
[iqiyi] 202861101: Download playlist page 9
[iqiyi] 202861101: Download playlist page 10
[iqiyi] 202861101: Download playlist page 11
[iqiyi] 202861101: Download playlist page 12
[iqiyi] 202861101: Download playlist page 13
[iqiyi] 202861101: Download playlist page 14
[iqiyi] 202861101: Download playlist page 15
[iqiyi] 202861101: Download playlist page 16
[download] Downloading playlist: 202861101
[iqiyi] playlist 202861101: Collected 740 video ids (downloading 740 of them)
[download] Downloading video 1 of 740
[iqiyi] temp_id: download video page
WARNING: unable to extract album title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[iqiyi] 202861101: Download playlist page 2
[iqiyi] 202861101: Download playlist page 3
[iqiyi] 202861101: Download playlist page 4
[iqiyi] 202861101: Download playlist page 5
[iqiyi] 202861101: Download playlist page 6
[iqiyi] 202861101: Download playlist page 7
[iqiyi] 202861101: Download playlist page 8
[iqiyi] 202861101: Download playlist page 9
[iqiyi] 202861101: Download playlist page 10
[iqiyi] 202861101: Download playlist page 11
[iqiyi] 202861101: Download playlist page 12
[iqiyi] 202861101: Download playlist page 13
[iqiyi] 202861101: Download playlist page 14
[iqiyi] 202861101: Download playlist page 15
[iqiyi] 202861101: Download playlist page 16
[download] Downloading playlist: 202861101
[iqiyi] playlist 202861101: Collected 740 video ids (downloading 740 of them)
[download] Downloading video 1 of 740
[iqiyi] temp_id: download video page
WARNING: unable to extract album title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[iqiyi] 202861101: Download playlist page 2
[iqiyi] 202861101: Download playlist page 3
[iqiyi] 202861101: Download playlist page 4
[iqiyi] 202861101: Download playlist page 5
[iqiyi] 202861101: Download playlist page 6
[iqiyi] 202861101: Download playlist page 7
[iqiyi] 202861101: Download playlist page 8
[iqiyi] 202861101: Download playlist page 9
[iqiyi] 202861101: Download playlist page 10
[iqiyi] 202861101: Download playlist page 11
[iqiyi] 202861101: Download playlist page 12
[iqiyi] 202861101: Download playlist page 13
[iqiyi] 202861101: Download playlist page 14
[iqiyi] 202861101: Download playlist page 15
[iqiyi] 202861101: Download playlist page 16
[download] Downloading playlist: 202861101
[iqiyi] playlist 202861101: Collected 740 video ids (downloading 740 of them)
[download] Downloading video 1 of 740
[iqiyi] temp_id: download video page

**Comment by dstftw** [comment] 2017-03-25 15:17
Duplicate of #12504.

**Closed by dstftw** 2017-03-25 15:17 UTC
