### ISSUE TITLE
Youtube-dl fails to mux video with bestvideo+bestaudio format selection

### ISSUE THREAD

**Issue by mlindner** [rg3/youtube-dl#5166] opened 2015-03-09 09:37 UTC
When downloading https://www.youtube.com/watch?v=kkd8A3QGP7M with -f bestvideo+bestaudio the muxing of the formats fails. This appears to be because youtube-dl is selecting the same container format as the video portion (which is VP9 webm) and trys to mux an audio stream of aac format.

The command run was:
```youtube-dl -v -f bestvideo+bestaudio kkd8A3QGP7M```

The error created is:
```ERROR: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument```
When running again with verbosity the ffmpeg command run is shown. Running that ffmpeg command generates:
```[webm @ 0x7fe332042600] Only VP8 or VP9 video and Vorbis or Opus audio and WebVTT subtitles are supported for WebM.```

A suggested fix would be to default to either an mp4 or an mkv format if webm format is not possible because of muxing of non-webm compatible codecs.

**Comment by dstftw** [comment] 2015-03-09 10:51
Duplicate of #4906.
You can use filters as workaround, e.g. `-f bestvideo[ext=mp4]+bestaudio`.

**Closed by dstftw** 2015-03-09 10:51 UTC
