### ISSUE TITLE
ytsearch gives a 403 error, but continues anyway

### ISSUE THREAD

**Issue by breadcat** [rg3/youtube-dl#6182] opened 2015-07-09 09:50 UTC
I'm running:
```
youtube-dl -x --audio-format=mp3 ytsearch:"Gabrielle - Rise Again" --verbose
```

Which gives:
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-x', u'--audio-format=mp3', u'ytsearch:Gabrielle - Rise Again', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.07
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.1
[debug] exe versions: ffmpeg 2.6.3, ffprobe 2.6.3, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:search] query "Gabrielle - Rise Again": Downloading page 1
[download] Downloading playlist: Gabrielle - Rise Again
[youtube:search] playlist Gabrielle - Rise Again: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[youtube] na93MI5NFy0: Downloading webpage
[youtube] na93MI5NFy0: Downloading video info webpage
[youtube] na93MI5NFy0: Extracting video information
[youtube] {43} signature length 41.42, html5 player en_US-vfld2QbH7
[youtube] {18} signature length 41.42, html5 player en_US-vfld2QbH7
[youtube] {5} signature length 41.42, html5 player en_US-vfld2QbH7
[youtube] {36} signature length 41.42, html5 player en_US-vfld2QbH7
[youtube] {17} signature length 41.42, html5 player en_US-vfld2QbH7
[youtube] {135} signature length 41.42, html5 player en_US-vfld2QbH7
[youtube] {244} signature length 41.42, html5 player en_US-vfld2QbH7
[youtube] {134} signature length 41.42, html5 player en_US-vfld2QbH7
[youtube] {243} signature length 41.42, html5 player en_US-vfld2QbH7
[youtube] {133} signature length 41.42, html5 player en_US-vfld2QbH7
[youtube] {242} signature length 41.42, html5 player en_US-vfld2QbH7
[youtube] {160} signature length 41.42, html5 player en_US-vfld2QbH7
[youtube] {140} signature length 41.42, html5 player en_US-vfld2QbH7
[youtube] {171} signature length 41.42, html5 player en_US-vfld2QbH7
[youtube] na93MI5NFy0: Downloading DASH manifest
[youtube] na93MI5NFy0: Downloading player https://s.ytimg.com/yts/jsbin/html5player-en_US-vfld2QbH7/html5player.js
[youtube] na93MI5NFy0: Downloading DASH manifest
WARNING: [youtube] na93MI5NFy0: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); 
please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl wit
h the --verbose flag and include its complete output.',)
[debug] Invoking downloader on 'https://r6---sn-cu-aigr.googlevideo.com/videoplayback?id=9daf77308e4d172d&itag=141&source=youtube&requiressl=yes&pl=25&mv=m&mm
=31&mn=sn-cu-aigr&ms=au&gcr=gb&ratebypass=yes&mime=audio/mp4&gir=yes&clen=7991512&lmt=1428134154867346&dur=250.636&upn=AAoh8FG7xBY&sver=3&signature=0D8EEEA67A
B351523F3C28BD6369F8633055728D.2E1D5CE0999E270E73B7DF469D71D2B3F7B44E97&fexp=901816,9405966,9406848,9408142,9408420,9408710,9409172,9413141,9413317,9414891,94
14936,9415435,9416126,9416658,9416729,9417041&key=dg_yt0&mt=1436434646&ip=81.129.109.234&ipbits=0&expire=1436456283&sparams=ip,ipbits,expire,id,itag,source,re
quiressl,pl,mv,mm,mn,ms,gcr,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Gabrielle - Rise-na93MI5NFy0.m4a
[download]   6.3% of 7.62MiB at 237.78KiB/s ETA 00:30^C                                      
```

It still completes without issue, and will convert the file correctly. Just thought you'd like to know.
I'm running the latest youtube-dl, with all my Debian stable packages up to date.

**Comment by yan12125** [comment] 2015-07-09 10:02
A duplicate of #5118.

**Closed by yan12125** 2015-07-09 10:02 UTC
