### ISSUE TITLE
[twitch:stream] First second of stream is repeating itself.

### ISSUE THREAD

**Issue by stepshal** [rg3/youtube-dl#10523] opened 2016-09-01 14:09 UTC
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.31**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

When you open any stream, first second is repeating itself and then go on normally. it's bugging me, can you fix this?

**Comment by dstftw** [comment] 2016-09-01 14:12
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by stepshal** [comment] 2016-09-01 14:32
@dstftw any stream,  they all affected.
https://www.twitch.tv/nintendo

**Comment by dstftw** [comment] 2016-09-01 14:40
Post verbose output.

**Comment by stepshal** [comment] 2016-09-01 14:48
I checked and it work on vods too. i forgot to mention that it appear when you open stream in mpv. Verbose doens't show anything. And i can't catch it with m3u8 download.

**Comment by dstftw** [comment] 2016-09-01 14:58
Duplicate of #10421.
mpv bugs should be addressed to mpv developers.
`youtube-dl -o - URL | mpv -`. works fine

**Closed by dstftw** 2016-09-01 14:58 UTC
Labels: cant-reproduce
