### ISSUE TITLE
ERROR : Traceback (most recent call last)

### ISSUE THREAD

**Issue by nhoclove9x** [rg3/youtube-dl#9410] opened 2016-05-05 22:56 UTC
Hi

Im using Windows cmd running so good I'm using C# running cmd youtube-dl in ProcessStartInfo on localhost is normal but run on server windows get error :
`ERROR : Traceback (most recent call last): File "__main__.py", line 19, in File "youtube_dl\__init__.pyo", line 419, in main File "youtube_dl\__init__.pyo", line 386, in _real_main File "youtube_dl\YoutubeDL.pyo", line 348, in __init__ File "youtube_dl\YoutubeDL.pyo", line 2040, in _setup_opener File "youtube_dl\utils.pyo", line 552, in make_HTTPS_handler File "ssl.pyo", line 440, in create_default_context File "ssl.pyo", line 391, in load_default_certs File "ssl.pyo", line 378, in _load_windows_store_certs WindowsError: [Error 5] Access is denied`

**Comment by dstftw** [comment] 2016-05-06 03:11
Duplicate of #7951.

**Closed by dstftw** 2016-05-06 03:11 UTC
