### ISSUE TITLE
Unable to extract html5 player

### ISSUE THREAD

**Issue by MrKoronas** [rg3/youtube-dl#7433] opened 2015-11-10 10:05 UTC
$ youtube-dl https://youtu.be/zLdO72oJEuM --verbose
[debug] System config: []
[debug] User config: [u'-x', u'-i', u'--default-search', u'ytsearch', u'--yes-playlist', u'--audio-format', u'mp3', u'--audio-quality', u'320k', u
'-o', u'%(title)s.%(ext)s']
[debug] Command-line args: [u'https://youtu.be/zLdO72oJEuM', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.11.02
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-74525-gdb91e0e, ffprobe N-74525-gdb91e0e
[debug] Proxy map: {}
[youtube] zLdO72oJEuM: Downloading webpage
[youtube] zLdO72oJEuM: Downloading video info webpage
[youtube] zLdO72oJEuM: Extracting video information
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  you
tube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {22} signature length 38.44, html5 player None
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 817, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 709, in _extract_signature_function
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.
org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and inclu
de its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on h
ttps://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose f
lag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  yo
utube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 817, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 709, in _extract_signature_function
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.
org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and inclu
de its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 661, in extract_info
  File "youtube_dl\extractor\common.pyo", line 290, in extract
  File "youtube_dl\extractor\youtube.pyo", line 1345, in _real_extract
  File "youtube_dl\extractor\youtube.pyo", line 827, in _decrypt_signature
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 817, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 709, in _extract_signature_function
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.
org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and inclu
de its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on h
ttps://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose f
lag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  yo
utube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by lol768** [comment] 2015-11-10 10:15
Dupe of #7413.

**Comment by edbergavera** [comment] 2015-11-10 10:21
Same issue here today on Mac OS X El Capitan 10.11.1

youtube-dl --verbose 'https://www.youtube.com/watch?v=rpLITtLRltw'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=rpLITtLRltw']
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2015.11.02
[debug] Python version 2.7.10 - Darwin-15.0.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8.1, ffprobe 2.8.1
[debug] Proxy map: {}
[youtube] rpLITtLRltw: Downloading webpage
[youtube] rpLITtLRltw: Downloading video info webpage
[youtube] rpLITtLRltw: Extracting video information
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {22} signature length 40.44, html5 player None
ERROR: Signature extraction failed: Traceback (most recent cal.......

**Comment by lol768** [comment] 2015-11-10 10:21
@edbergavera Did you try it with 50f84a9ae171233c08ada41e03f6555c5ed95236?

**Comment by edbergavera** [comment] 2015-11-10 10:28
@lol768 I haven't but I have installed with homebrew.

**Comment by phihag** [comment] 2015-11-10 10:52
You are using an outdated version of youtube-dl. Please update to 2015.11.10 or newer. See [our FAQ](https://yt-dl.org/update) if you are having trouble updating. Thanks!

**Closed by phihag** 2015-11-10 10:52 UTC

**Comment by edbergavera** [comment] 2015-11-10 10:55
@phihag it looks like the homebrew repo hasn't been updated yet. However, youtube-dl -U does show and updated version. I'll figure this out. Thanks again guys!

**Comment by MrKoronas** [comment] 2015-11-10 10:55
Thats funny I updated it when the error occurred just before I posted this thread but now it has updated again and works.
