### ISSUE TITLE
Channel Download ERROR

### ISSUE THREAD

**Issue by bilenyok** [rg3/youtube-dl#4929] opened 2015-02-11 11:53 UTC
Today I do not download channel videos.

ERROR: Unable to download JSON metadata: HTTP Error 400: Bad Request ....

I try many channels and diffrent computers. I get same error. Why?

**Comment by phihag** [comment] 2015-02-11 12:39
Duplicate of #4927. This seems to be an error on YouTube's side.

**Closed by phihag** 2015-02-11 12:39 UTC
