### ISSUE TITLE
crunchyroll error

### ISSUE THREAD

**Issue by gavbn** [rg3/youtube-dl#11638] opened 2017-01-08 07:31 UTC
Hi, I am getting an error while downloading a subtitle from crunchyroll,I am using the latest verison of your application i.e, youtube-dl-2017.01.05 and here is error:
HTtp Error 503: webpage unavailable

**Comment by Starsam80** [comment] 2017-01-08 07:33
Duplicate of #11572

**Comment by gavbn** [comment] 2017-01-08 07:37
I am not using login credentials I just want to download subtitles for free

**Closed** 2017-01-08 10:37 UTC
