### ISSUE TITLE
--print-traffic not working in Windows binary

### ISSUE THREAD

**Issue by spookyahell** [rg3/youtube-dl#10141] opened 2016-07-22 15:20 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.07.17*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### Description of your *issue*, suggested solution and other information

print-traffic option not showing any effect in the Windows binary.

PS: Is that related to https://github.com/rg3/youtube-dl/issues/9365 ?

**Comment by dstftw** [comment] 2016-07-22 16:08
`--print-traffic` does not work prior to Python 3.5.2. Windows build is built against Python 3.4.4.

**Comment by spookyahell** [comment] 2016-07-22 22:50
Will that change?

**Comment by dstftw** [comment] 2016-07-22 22:54
What that?

**Comment by spookyahell** [comment] 2016-07-23 04:55
The version of Python that the Windows binary is based on, will it be built with 3.5.2 or higher at a later point to solve the problem?

**Comment by dstftw** [comment] 2016-07-23 05:07
Using Python 3.5.x version for Windows build means dropping support for Windows XP. Separate 3.4.x and 3.5.x builds may be provided in future however I don't see pressing need for this at the moment.

**Comment by yan12125** [comment] 2016-07-26 02:54
Duplicate of #9365. Please move to #10014 for further discussion.

**Closed by yan12125** 2016-07-26 02:54 UTC
Labels: build/update
