### ISSUE TITLE
Youporn extrcator no longer sorking

### ISSUE THREAD

**Issue by Starbuck2010** [rg3/youtube-dl#7170] opened 2015-10-14 09:44 UTC
Same for any video (not signed in):
<code>
youtube-dl.exe --verbose --no-playlist -e http://www.youporn.com/watch/11986207/busty-daughter-squirting/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--no-playlist', u'-e', u'http://www.youporn.com/watch/11986207/busty-daughter-squirting/']
[debug] Encodings: locale cp1252, fs mbcs, out None, pref cp1252
[debug] youtube-dl version 2015.10.13
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: Unable to extract JSON parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 660, in extract_info
  File "youtube_dl\extractor\common.pyo", line 290, in extract
  File "youtube_dl\extractor\youporn.pyo", line 52, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 584, in _search_regex
RegexNotFoundError: Unable to extract JSON parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
</code>

**Comment by dstftw** [comment] 2015-10-14 13:51
Duplicate of #6888.

**Closed by dstftw** 2015-10-14 13:51 UTC
