### ISSUE TITLE
Status from ffmpeg/avconv

### ISSUE THREAD

**Issue by amkrankruleuen** [rg3/youtube-dl#6103] opened 2015-06-27 02:25 UTC
Hello.

How review the ffmpeg/avconv status? 

For example:

size=    2520kB time=00:01:04.41 bitrate= 320.4kbits/s

**Comment by yan12125** [comment] 2015-06-27 03:34
Duplicate of #1304.

**Closed by yan12125** 2015-06-27 03:34 UTC
