### ISSUE TITLE
Vine download problem: No video formats found

### ISSUE THREAD

**Issue by auerswal** [rg3/youtube-dl#5429] opened 2015-04-15 08:15 UTC
I tried to download a video from vine.co, which did not work. This is the bug report requested by youtube-dl.

$ ~/Software/youtube-dl --verbose 'https://vine.co/v/euEpIVegiIx'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://vine.co/v/euEpIVegiIx']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.09
[debug] Python version 2.7.6 - Linux-3.13.0-49-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, rtmpdump 2.4
[debug] Proxy map: {}
[Vine] euEpIVegiIx: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/auerswald/Software/youtube-dl/youtube_dl/YoutubeDL.py", line 651, in extract_info
    ie_result = ie.extract(url)
  File "/home/auerswald/Software/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/home/auerswald/Software/youtube-dl/youtube_dl/extractor/vine.py", line 42, in _real_extract
    self._sort_formats(formats)
  File "/home/auerswald/Software/youtube-dl/youtube_dl/extractor/common.py", line 703, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by naglis** [comment] 2015-04-15 09:56
I believe this problem to be a duplicate of #5389, which should be fixed in the next release of youtube-dl. Nevertheless, thanks for the reporting it.

**Closed by naglis** 2015-04-15 09:56 UTC

**Comment by auerswal** [comment] 2015-04-15 11:01
Yes, this looked like one of the problems reported in #5389, but that issue pertained to an older youtube-dl version, and I interpreted the closing remark ("next version", written 6 days ago) to pertain to the now current version which does show the problem.

Anyway, I have just checked with git HEAD, this issue is fixed there. The fix went in about 22 hours after release 2015.04.09.

Thanks.
