### ISSUE TITLE
SOCKS proxy support

### ISSUE THREAD

**Issue by FiloSottile** [rg3/youtube-dl#402] opened 2012-08-19 23:10 UTC
The necessity arose in #171 and even I needed it to debug a geo-blocked video.
There was an attempt on #305 that faced license issues.

I implemented it some time ago with SocksiPy-branch but we don't like external dependencies, do we?

**Comment by hadifarnoud** [comment] 2015-05-01 13:42
+1 for this one. any updates?

**Comment by arioch** [comment] 2015-05-11 14:14
+1

**Comment by mateon1** [comment] 2015-05-27 21:23
+1

**Comment by agate** [comment] 2015-06-02 03:56
+1

**Comment by wenerme** [comment] 2015-06-24 14:06
+1

**Comment by wuhaa11** [comment] 2015-07-10 13:53
+1

**Comment by NoAnyLove** [comment] 2015-07-19 01:46
+1

**Comment by Don42** [comment] 2015-07-24 20:28
Feature is implemented in PR #6353 
Please let me know if it works for you. It allowed me to view music videos on youtube from Germany.
Without the socks proxy they were blocked.

**Comment by Don42** [comment] 2015-07-27 19:54
I could was not able to build the windows binary with py2exe, so I could not test that.

The feature will not work under windows or anywhere else without the PySocks package installed.
Normal operation of youtube-dl is not hindered, but it will print an error_message when the user tries to use a SOCKS proxy  without the package.

I first tried to use the "official" socksipy package, but that is no longer maintained and I needed a newer feature that is only in PySocks to implement a feature @yan12125 wanted.

**Comment by yan12125** [comment] 2015-07-28 15:52
@Don42 I guess technically it's possible to bundle PySocks with youtube-dl via py2exe, while there are legal concerns. youtube-dl is released under UNLICENSE, while PySocks is under [BSD like license](https://github.com/Anorov/PySocks/blob/master/LICENSE). I'm not sure whether it's OK to bundle them together.

**Comment by Don42** [comment] 2015-07-29 06:03
Since I am not a lawyer, I will give no opinion on that.
But the way I implemented the feature would allow it to be a Linux/OSX only feature where the user would have to install PySocks if and when you wants to use a SOCKS proxy.

**Comment by tulsidas** [comment] 2015-08-04 18:20
+1

**Comment by limonte** [comment] 2015-08-10 09:52
The same issue here, can't download videos using server in Germany.

**Comment by OliverUv** [comment] 2015-10-27 05:16
+1

Using proxychains doesn't work with youtube-dl for me, though it works for almost everything else. Doesn't even work when I do proxychains bash, then youtube-dl inside of that, which is a workaround that works for npm.

**Comment by EvanCarroll** [comment] 2015-10-29 16:56
:+1:

**Comment by Ianvdl** [comment] 2015-11-17 07:51
+1

Has anyone discovered a workaround for this yet?

**Comment by Don42** [comment] 2015-11-17 08:28
@Ianvdl Workaround for what exactly? I have a branch that works with SOCKS proxies. It might be a bit old, but it still works. As it probably won't be merged I am not updating it regularly.

**Comment by Ianvdl** [comment] 2015-11-17 08:35
@Don42 I'll take a look at your fork sometime to see if I can merge it with the latest version. I find myself having to update often due to youtube's constant changes, so I expect that your version (given that it is outdated) might not be sufficient.

**Comment by Don42** [comment] 2015-11-17 08:46
@Ianvdl That is possible. I tested it a few weeks back and it still worked. The changes are quite localized, so it should be easily merged. The only problem was, that it has a dependency and I couldn't add that to the windows exe builder. But it is a soft dependency, when it's not available everything except the SOCKS proxy will work as expected.

**Comment by wenerme** [comment] 2015-12-18 16:47
Suggest use [cow](https://github.com/cyfdecyf/cow) to convert you socks to http proxy. then

```
youtube-dl --proxy http://127.0.0.1:7777 -i 'https://www.youtube.com/playlist?list=PLe5-IOvkHavsbjTT1mjsV3ai1I6ZXwotA'
```

**Comment by zqwroiez** [comment] 2016-01-22 11:23
One could use [delegate](http://www.delegate.org/) as a workaround to "convert" a socks proxy into a http proxy:
```
# Start on port 8080 an http proxy connected to a socks proxy on port 9150
delegated -v -P8080 SERVER=http SOCKS=localhost:9150
# Now download via socks
youtube-dl --proxy http://localhost:8080 https://vimeo.com/44297516
```

**Comment by EvanCarroll** [comment] 2016-01-22 18:15
@zqwroiez that is so fucking cool. You++.

**Comment by jab** [comment] 2016-01-27 06:14
Looks like @zqwroiez's comment and account have both been deleted, mysterious. I'll add the comment back as it appears in the GitHub notification email I got:

On Fri, Jan 22, 2016 at 6:24 AM, zqwroiez <notifications@github.com> wrote:
> One could use [delegate](http://www.delegate.org/) as a workaround to "convert" a socks proxy into a http proxy:
> ```
> # Start on port 8080 an http proxy connected to a socks proxy on port 9150
> delegated -v -P8080 SERVER=http SOCKS=localhost:9150
> # Now download via socks
> youtube-dl --proxy http://localhost:8080 https://vimeo.com/44297516
> ```

I wanted to try this. but unfortunately there's no formula for DeleGate in homebrew, though a PR was opened in the past: Homebrew/homebrew#30807. Tried asking the author of that PR what happened but haven't heard back yet. Just thought I'd mention here in case anyone reading would be interested in picking that back up.

**Comment by zhendongguan** [comment] 2016-02-17 05:48
+1

**Comment by polyzen** [comment] 2016-02-19 22:29
Not sure how [these](http://unix.stackexchange.com/a/128393) guys got it working back then, but urllib3 1.14 with PySocks>=1.5.6,<2.0 [supports SOCKS](https://github.com/shazow/urllib3/pull/762).

I've got urllib3 1.14 with PySocks master (which is apparently at 1.5.6), but still getting `ERROR: Unable to download webpage: <urlopen error unknown url type: socks5> (caused by URLError('unknown url type: socks5',))`

**Comment by infinity0** [comment] 2016-04-16 18:52
Just noting here that, recent versions of `ffmpeg` trigger [Debian bug 805741](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=805741) which means that `torsocks youtube-dl` goes into a busy loop (that eventually ends with "out of memory") when it tries to run `ffmpeg -version`.

**Comment by yan12125** [comment] 2016-04-23 13:53
I've proposed #9287 based on @bluec0re's socks.py. With that patch commands like this should work:
```
youtube-dl -v cbjMwKLE-RE --proxy "socks5://127.0.0.1/"
```
Given your SOCKS proxy listens on 127.0.0.1:1080.

**Comment by dstftw** [comment] 2016-05-10 15:06
SOCKS proxy support has been added in youtube-dl 2016.05.10.

**Closed by dstftw** 2016-05-10 15:06 UTC
Labels: request

**Comment by jackiilong** [comment] 2017-10-12 04:17
youtube-dl --proxy "socks5://127.0.0.1/" 
 works
