### ISSUE TITLE
%(playlist_index) pads neither by playlist size nor to 5 digits

### ISSUE THREAD

**Issue by bmedicke** [rg3/youtube-dl#5748] opened 2015-05-19 07:19 UTC
The man page states that `%(playlist_index)s` should pad to 5 digits and according to an issue here it is supposed to pad to playlist size but it does neither.

`--playlist-start 1 --playlist-end 9 -o "%(playlist_index)s"`  starts with 1,
`--playlist-start 1 --playlist-end 10 -o "%(playlist_index)s"` starts with 01,
`--playlist-start 2 --playlist-end 10 -o "%(playlist_index)s"` starts with 2,
`--playlist-start 2 --playlist-end 11 -o "%(playlist_index)s"` starts with 02.

Looks like it uses the number of videos in the current job which results in duplicates when overlapping ranges.

Any of the supposed behaviours would be fine to get consistent lexical sort names when downloading parts of a playlist. Or maybe a flag to specify the size as with `$(autonumber)s`.

**Comment by dstftw** [comment] 2015-09-12 13:37
Duplicate of #5185.

**Closed by dstftw** 2015-09-12 13:37 UTC
