### ISSUE TITLE
Please support Pandora.tv

### ISSUE THREAD

**Issue by ksy5662** [rg3/youtube-dl#2025] opened 2013-12-22 06:30 UTC
Here is one example video!!

http://channel.pandora.tv/channel/video.ptv?ch_userid=sunlight38&prgid=49713893&categid=35638245&page=2&ref=ch&lot=cthum2_1_1

**Comment by bit** [comment] 2015-12-20 14:38
Duplicate of #6884

**Comment by dstftw** [comment] 2015-12-31 19:30
pandora.tv will be supported in the next version.

**Closed by dstftw** 2015-12-31 19:30 UTC
Labels: site-support-request
