### ISSUE TITLE
special zdf pages

### ISSUE THREAD

**Issue by jubalh** [rg3/youtube-dl#11477] opened 2016-12-18 11:40 UTC
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.15**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)

### Description of your *issue*, suggested solution and other information
It seems that ZDF has some special pages like https://www.zdf.de/dokumentation/terra-x/grosse-voelker-die-germanen-100.html
Which youtube-dl cannot handle yet, it seems they are different from the usual Mediathek? Not quite sure though. For this reason I am not sure if this is a new feature request or a bug report.

```
youtube-dl -v https://www.zdf.de/dokumentation/terra-x/grosse-voelker-die-germanen-100.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.zdf.de/dokumentation/terra-x/grosse-voelker-die-germanen-100.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.15
[debug] Python version 2.7.12 - Linux-4.4.36-8-default-x86_64-with-SuSE-42.2-x86_64
[debug] exe versions: ffmpeg 3.2, ffprobe 3.2
[debug] Proxy map: {}
[generic] grosse-voelker-die-germanen-100: Requesting header
WARNING: Falling back on generic information extractor.
[generic] grosse-voelker-die-germanen-100: Downloading webpage
[generic] grosse-voelker-die-germanen-100: Extracting information
ERROR: Unsupported URL: https://www.zdf.de/dokumentation/terra-x/grosse-voelker-die-germanen-100.html
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1626, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/bin/youtube-dl/youtube_dl/compat.py", line 2526, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/bin/youtube-dl/youtube_dl/compat.py", line 2515, in _XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 143, column 162
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2433, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.zdf.de/dokumentation/terra-x/grosse-voelker-die-germanen-100.html
```

**Comment by dstftw** [comment] 2016-12-18 11:43
Duplicate of #11055.

**Closed by dstftw** 2016-12-18 11:43 UTC
