### ISSUE TITLE
add auto retry on 'ERROR: content too short'

### ISSUE THREAD

**Issue by guestguestguest** [rg3/youtube-dl#5304] opened 2015-03-28 07:27 UTC
hi,

```
[generic] video01: Requesting header
WARNING: Falling back on generic information extractor.
[generic] video01: Downloading webpage
[generic] video01: Extracting information
[download] Destination: video01.mp4
[download]  82.5% of 31.56MiB at 203.07KiB/s ETA 00:27ERROR: content too short (expected 33098194 bytes and served 27296535)
user@usershost:/tmp$ torsocks youtube-dl {url to video01, url to video 02}//same command as before but this time it worked
WARNING: Falling back on generic information extractor.
[generic] video01: Downloading webpage
[generic] video01: Extracting information
[download] Resuming download at byte 27296535
[download] Destination: video01.mp4
[download] 100% of 31.56MiB in 00:20
[generic] video02: Requesting header
WARNING: Falling back on generic information extractor.
[generic] video02: Downloading webpage
[generic] video02: Extracting information
[download] Destination: video02.mp4
[download]  15.6% of 13.53MiB at 337.32KiB/s ETA 00:34

```

here the complete download queue gets aborted because one of this error, but if manually restarted it is working again and resuming the download. could you add an autoretry in this cases to avoid the extra work?

thanks a lot

**Comment by guestguestguest** [comment] 2015-06-22 05:07
whats up, has that be fixed??

**Comment by jaimeMF** [comment] 2015-06-22 06:48
Sorry for not answering, this is a duplicate of #809 and we haven't implemented it yet (patches welcomed).

**Closed by jaimeMF** 2015-06-22 06:48 UTC
