### ISSUE TITLE
SoundCloud:set 401 error

### ISSUE THREAD

**Issue by Asbra** [rg3/youtube-dl#7007] opened 2015-09-28 01:19 UTC
```
>python C:\youtube-dl.py -F https://soundcloud.com/runthetrap/sets/100k-plays-and-above --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-F', u'https://soundcloud.com/runthetrap/sets/100k
-plays-and-above', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.09.22
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[soundcloud:set] runthetrap/sets/100k-plays-and-above: Resolving id
[soundcloud:set] runthetrap/sets/100k-plays-and-above: Downloading JSON metadata

ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\youtube-dl.py\youtube_dl\extractor\common.py", line 326, in _request_
webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\youtube-dl.py\youtube_dl\YoutubeDL.py", line 1865, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Python27\lib\urllib2.py", line 437, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

**Comment by dstftw** [comment] 2015-09-28 03:21
Duplicate of #6930.
This is already fixed in master and will be incorporated in the next version of youtube-dl.

**Closed by dstftw** 2015-09-28 03:21 UTC
