### ISSUE TITLE
ERROR: Signature extraction failed: Traceback (most recent call last):

### ISSUE THREAD

**Issue by Waldoctg** [rg3/youtube-dl#7423] opened 2015-11-10 06:08 UTC
ERROR: Signature extraction failed: Traceback (most recent call last):
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
        video_id, player_url, s
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 709, in _extract_signature_function
        raise ExtractorError('Cannot identify player %r' % player_url)
    ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js';     please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type      youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete     output.
     (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-    vfljDEtYP/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest     version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its     complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest     version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its     complete output.

I get this error...I updated to the latest version and still no dice. I tried two different videos. Any advice?

**Comment by bstoked** [comment] 2015-11-10 06:41
I am having the same issue.
youtube-dl --verbose -x --audio-format wav 'https://www.youtube.com/watch?v=Dsl6fFm-0hI'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-x', u'--audio-format', u'wav', u'https://www.youtube.com/watch?v=Dsl6fFm-0hI']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.02
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.4.3, ffprobe 2.4.3
[debug] Proxy map: {}
[youtube] Dsl6fFm-0hI: Downloading webpage
[youtube] Dsl6fFm-0hI: Downloading video info webpage
[youtube] Dsl6fFm-0hI: Extracting video information
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {43} signature length 40.44, html5 player None
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
 ate. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by bstoked** [comment] 2015-11-10 06:41
NOTE: This worked fine yesterday.

**Comment by dstftw** [comment] 2015-11-10 06:47
Duplicate of #7413. This is already fixed and will be available in the next version.

**Closed by dstftw** 2015-11-10 06:47 UTC
