### ISSUE TITLE
403 (and Video Downloadhelper returns a zero-byte file)

### ISSUE THREAD

**Issue by austux** [rg3/youtube-dl#6659] opened 2015-08-24 23:37 UTC
$ youtube-dl https://www.youtube.com/watch?v=rtOvBOTyX00
[youtube] rtOvBOTyX00: Downloading webpage
[youtube] rtOvBOTyX00: Downloading video info webpage
[youtube] rtOvBOTyX00: Extracting video information
[youtube] rtOvBOTyX00: Downloading DASH manifest
WARNING: [youtube] rtOvBOTyX00: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
WARNING: Your copy of avconv is outdated and unable to properly mux separate video and audio files, youtube-dl will download single file media. Update avconv to version 10-0 or newer to fix this.
ERROR: unable to download video data: HTTP Error 403: Forbidden

**Comment by yupi2** [comment] 2015-08-24 23:41
Duplicate of #6451. Remove cache with `youtube-dl --rm-cache-dir`.

**Comment by austux** [comment] 2015-08-25 00:20
thank you.

that worked instantly. also for https://www.youtube.com/watch?v=q9ayN39xmsI which had failed earlier.

preventative maintenance: is it possible for youtube-dl to either automatically determine that this needs doing, or suggest it as part of the error message?

**Closed** 2015-08-25 03:11 UTC
