### ISSUE TITLE
[CBS] Extraction failes 

### ISSUE THREAD

**Issue by Vittelius** [rg3/youtube-dl#15737] opened 2018-03-01 21:55 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.02.26*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---
When downloading the latest episode of CBS's _Bull_ (2x15), I get the following error:
```
./Downloads/youtube-dl -v http://www.cbs.com/shows/bull/video/sb4atUdwyQ_C3TTD8YLxun21_NLlnWvr/bull-witness-for-the-prosecution/  
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.cbs.com/shows/bull/video/sb4atUdwyQ_C3TTD8YLxun21_NLlnWvr/bull-witness-for-the-prosecution/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.02.26
[debug] Python version 2.7.14 (CPython) - Linux-4.15.6-58.current-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2, rtmpdump 2.3
[debug] Proxy map: {}
[CBS] sb4atUdwyQ_C3TTD8YLxun21_NLlnWvr: Downloading XML
[CBS] sb4atUdwyQ_C3TTD8YLxun21_NLlnWvr: Downloading OnceURL SMIL data
ERROR: None of the available releases match the specified AssetType, ProtectionScheme, and/or Format preferences
Traceback (most recent call last):
  File "./Downloads/youtube-dl(5)/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "./Downloads/youtube-dl(5)/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "./Downloads/youtube-dl(5)/youtube_dl/extractor/cbs.py", line 100, in _real_extract
    return self._extract_video_info(content_id)
  File "./Downloads/youtube-dl(5)/youtube_dl/extractor/cbs.py", line 79, in _extract_video_info
    'Downloading %s SMIL data' % asset_type)
  File "./Downloads/youtube-dl(5)/youtube_dl/extractor/theplatform.py", line 42, in _extract_theplatform_smil
    raise ExtractorError(error_element.attrib['abstract'], expected=True)
ExtractorError: None of the available releases match the specified AssetType, ProtectionScheme, and/or Format preferences

```
This issue seems to be confined to this particular video as the download of other videos from cbs.com, released before and after the one in question, works perfectly fine.

**Comment by kucksdorfs** [comment] 2018-03-02 01:42
My python skills are basically non-existant (the code I wrote today is the most I have done reading/writing python), but I have made changes to a copy on my machine that seems to work. I just wrapped the code snippet below in a try-except block and it seems to be working.

`                tp_formats, tp_subtitles = self._extract_theplatform_smil(
                    update_url_query(tp_release_url, query), content_id,
                    'Downloading %s SMIL data' % asset_type)
                formats.extend(tp_formats)
                subtitles = self._merge_subtitles(subtitles, tp_subtitles)`

This also seems to be a duplicate of the issue: #13490.

**Closed** 2018-03-02 02:38 UTC

**Comment by TPIRFan** [comment] 2018-03-07 07:34
I've been having the same problem trying to download the March 5 and March 6 episodes of The Price Is Right from https://www.cbs.com/shows/the_price_is_right/video/GTpqMvkceyNvH20lm69bMQrCOj3HvtL8/the-price-is-right-3-5-2018/ and https://www.cbs.com/shows/the_price_is_right/video/2INTSJGKeWOhuYsANboSttUetNxmTvhY/the-price-is-right-3-6-2018/ .  As others have stated, it seems to be limited to these episodes of this program.

A Verbose printout of the former yields the following:

C:\Users\TPIRFan\Program Files\NewYoutube-dl3>youtube-dl -v "https://www.cbs.com/shows/the_price_is_right/video/GTpqMvkceyNvH20lm69bMQrCOj3HvtL8/the-price-is-right-3-5-2018/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.cbs.com/shows/the_price_is_right/video/GTpqMvkceyNvH20lm69bMQrCOj3HvtL8/the-price-is-right-3-5-2018/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.03.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg N-87130-g2b9fd15, rtmpdump 2.4
[debug] Proxy map: {}
[CBS] GTpqMvkceyNvH20lm69bMQrCOj3HvtL8: Downloading XML
[CBS] GTpqMvkceyNvH20lm69bMQrCOj3HvtL8: Downloading RTMP SMIL data
[CBS] GTpqMvkceyNvH20lm69bMQrCOj3HvtL8: Downloading StreamPack SMIL data
[CBS] GTpqMvkceyNvH20lm69bMQrCOj3HvtL8: Downloading m3u8 information
[CBS] GTpqMvkceyNvH20lm69bMQrCOj3HvtL8: Downloading OnceURL SMIL data
ERROR: None of the available releases match the specified AssetType, ProtectionScheme, and/or Format preferences
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\YoutubeDL.py", line 785, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\extractor\common.py", line 440, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\extractor\cbs.py", line 100, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\extractor\cbs.py", line 79, in _extract_video_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\extractor\theplatform.py", line 42, in _extract_theplatform_smil
youtube_dl.utils.ExtractorError: None of the available releases match the specified AssetType, ProtectionScheme, and/or Format preferences

I'm not well-versed in this sort of thing, so it's entirely possible that I just don't have the fix implemented correctly.  Is there a particular place on the drive where it needs to go?

**Comment by jmacpomment** [comment] 2018-03-08 00:51
Find the file extractor/cbs.py  (in my case, it was located in /usr/lib/python3.6/site-packages/youtube_dl/extractor/cbs.py)

Search for the code (as mentioned above)

    tp_formats, tp_subtitles = self._extract_theplatform_smil(
        update_url_query(tp_release_url, query), content_id,
        'Downloading %s SMIL data' % asset_type)
    formats.extend(tp_formats),
    subtitles = self._merge_subtitles(subtitles, tp_subtitles)

In my case, the tp_formats line has 12 spaces beforehand.  So, insert a line before the tp_formats line, with 12 spaces, followed by "try:" (without the quotes).

Next, indent the 5 lines above by 4 spaces.

Follow the subtitles line with a line that starts with 12 spaces, then "except:" (without the quotes)
On the line below that, put 16 spaces, followed by "print("ERROR!")" (take off the outside quotes)

It should look like this now:

    try:
        tp_formats, tp_subtitles = self._extract_theplatform_smil(
            update_url_query(tp_release_url, query), content_id,
            'Downloading %s SMIL data' % asset_type)
        formats.extend(tp_formats)
        subtitles = self._merge_subtitles(subtitles, tp_subtitles)
    except:
        print("ERROR!")`

(All lines indented to the original level that the tp_formats line was.)

Save that, and try again.  It worked perfectly for me.

**Comment by TPIRFan** [comment] 2018-03-08 04:57
I'm afraid I'm still fouling something up.  Is there an easy way to find where this file is located on my machine?  I've only been able to locate it in the same directories that YouTube-dl itself is installed in, and editing it there doesn't seem to be affecting anything.

(Incidentally, YouTube-dl is downloading today's Price Is Right without any problems, but Monday and Tuesday's shows still won't cooperate.)

**Comment by jschwalbe** [comment] 2018-03-13 02:56
I can verify that this fix worked.
