### ISSUE TITLE
Cant play crunchy roll premium content

### ISSUE THREAD

**Issue by gabrielvis** [rg3/youtube-dl#11964] opened 2017-02-04 05:42 UTC
23:37:49.632 [E]: Tube: Unable to download webpage: HTTP Error 503: Service Temporarily Unavailable (caused by <HTTPError 503: 'Service Temporarily Unavailable'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
23:37:49.640 [E]: Tube: Unable to download webpage: HTTP Error 503: Service Temporarily Unavailable (caused by <HTTPError 503: 'Service Temporarily Unavailable'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment] 2017-02-04 06:00
Duplicate of #11572. There's a possible fix at #11730.

**Closed by yan12125** 2017-02-04 06:00 UTC
