### ISSUE TITLE
PBS download fails with http error 400 and a cookies file to enable HD

### ISSUE THREAD

**Issue by crystalclaw** [rg3/youtube-dl#5020] opened 2015-02-21 01:22 UTC
I tried to include the cookies for a nova video so that HD is enabled, but it gives me an error 400. works fine without cookies, but is really low quality.
command: ```youtube-dl -F http://video.pbs.org/video/2163057527/ --cookies /Users/iandrobney/Desktop/cookies.txt```
cookies were exported from firefox with a random cookie exporting plugin.
output:
```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/iandrobney/programs/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/Users/iandrobney/programs/bin/youtube-dl/youtube_dl/__init__.py", line 390, in main
  File "/Users/iandrobney/programs/bin/youtube-dl/youtube_dl/__init__.py", line 357, in _real_main
  File "/Users/iandrobney/programs/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 323, in __init__
  File "/Users/iandrobney/programs/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1669, in _setup_opener
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cookielib.py", line 1763, in load
    self._really_load(f, filename, ignore_discard, ignore_expires)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_MozillaCookieJar.py", line 55, in _really_load
    filename)
cookielib.LoadError: '/Users/iandrobney/Desktop/cookies.txt' does not look like a Netscape format cookies file
000009:TEMPVIDS iandrobney$ youtube-dl -F http://video.pbs.org/video/2163057527/ --cookies /Users/iandrobney/Desktop/cookies.txt
[PBS] 2163057527: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by remitamine** [comment] 2015-07-31 16:39
now, it's working.
```
youtube-dl -v http://video.pbs.org/video/2163057527/
[debug] System config: []
[debug] User config: ['--external-downloader', 'aria2c', '--external-downloader-args', '-x 16 --check-certificate=false', '-f', 'best[height<=?720]', '--sub-lang', 'ar,en', '--write-sub']
[debug] Command-line args: ['-v', 'http://video.pbs.org/video/2163057527/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.21
[debug] Python version 3.4.3 - Linux-4.1.2-2-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2, rtmpdump 2.4
[debug] Proxy map: {}
[PBS] 2163057527: Downloading JSON metadata
[PBS] 2163057527: Downloading recommended_encoding video url info
[PBS] 2163057527: Downloading alternate_encoding video url info
WARNING: ar subtitles not available for 2163057527
[info] Writing video subtitles to: The Fabric of the Cosmos - What Is Space-2163057527.en.ttml
[debug] Invoking downloader on 'http://ga.video.cdn.pbs.org/videos/nova/77aacc41-923c-4262-a265-4c003b674319/69256/hd-mezzanine-16x9/NOVA3816_web16x9-web-16x9.mp4'
[download] Destination: The Fabric of the Cosmos - What Is Space-2163057527.mp4
[debug] aria2c command line: aria2c -c -x 16 --check-certificate=false --out 'The Fabric of the Cosmos - What Is Space-2163057527.mp4.part' --header 'Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7' --header 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)' --header 'Accept-Language: en-us,en;q=0.5' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Encoding: gzip, deflate' -- http://ga.video.cdn.pbs.org/videos/nova/77aacc41-923c-4262-a265-4c003b674319/69256/hd-mezzanine-16x9/NOVA3816_web16x9-web-16x9.mp4
[#e4ab5e 16KiB/339MiB(0%) CN:16 DL:3.7KiB ETA:25h25m43s]
```

**Comment by jaimeMF** [comment] 2015-07-31 16:54
I don't have access to the video, but the cookies issue is already reported in #4539. If it works now, please tell us so we can close this issue.

**Comment by crystalclaw** [comment] 2015-07-31 17:39
I no longer have access to the computer I did this on (school laptop), so I'll have to set it up again on my new home laptop. I'll test it tonight if I can, and get back to you so this issue can be closed.

**Comment by remitamine** [comment] 2015-07-31 18:00
i'm sorry i didn't notice that the problem is about the cookies.

**Comment by dstftw** [comment] 2016-01-31 17:51
Check newline format in your cookies files to [correspond your OS](https://github.com/rg3/youtube-dl#how-do-i-pass-cookies-to-youtube-dl).

**Closed by dstftw** 2016-01-31 17:51 UTC
