### ISSUE TITLE
An extractor error has occurred with the latest version of youtube-dl

### ISSUE THREAD

**Issue by skthanu** [rg3/youtube-dl#15200] opened 2018-01-09 02:25 UTC
```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\hieuht_hanu\Desktop\youtube-dl>youtube-dl.exe -v -u username -p password --all-subs --sub-format srt --write-thumbnail --add-metadata "ht
tps://vrv.co/watch/GRMG7DP2R/The-Cherry-Blossoms-Have-Fallen"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-u', 'PRIVATE', '-p', 'PRIVATE', '--all-subs'
, '--sub-format', 'srt', '--write-thumbnail', '--add-metadata', 'https://vrv.co/
watch/GRMG7DP2R/The-Cherry-Blossoms-Have-Fallen']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.01.07
[debug] Python version 3.4.4 (CPython) - Windows-2012ServerR2-6.3.9600
[debug] exe versions: ffmpeg git-2017-12-29-5297ae9, ffprobe git-2017-12-29-5297
ae9
[debug] Proxy map: {}
[vrv] GRMG7DP2R: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError('streams',)); please
 report this issue on https://yt-dl.org/bug . Make sure you are using the latest
 version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --
verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4k56gdgt\bu
ild\youtube_dl\extractor\common.py", line 438, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4k56gdgt\bu
ild\youtube_dl\extractor\vrv.py", line 110, in _real_extract
KeyError: 'streams'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4k56gdgt\bu
ild\youtube_dl\extractor\common.py", line 438, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4k56gdgt\bu
ild\youtube_dl\extractor\vrv.py", line 110, in _real_extract
KeyError: 'streams'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4k56gdgt\bu
ild\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4k56gdgt\bu
ild\youtube_dl\extractor\common.py", line 451, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by Key
Error('streams',)); please report this issue on https://yt-dl.org/bug . Make sur
e you are using the latest version; type  youtube-dl -U  to update. Be sure to c
all youtube-dl with the --verbose flag and include its complete 
```

I don't know why, but i can not download movie anymore when i update youtube-dl, can you please help?

**Comment by LightNightCode** [comment] 2018-01-09 03:25
It seems that all can not be used, including web downloads, client, I have tried.

**Comment by skthanu** [comment] 2018-01-09 03:30
@LightNightCode can you please help? It was good yesterday, however today it's not, is that only me have this problem or everybody?

**Comment by LightNightCode** [comment] 2018-01-09 05:04
I have no other way, my distant brother is not so good, I do not know what is the situation.

**Comment by LightNightCode** [comment] 2018-01-09 05:06
My brother said that this morning can not be used, and then used, and now can not be used.

**Comment by LightNightCode** [comment] 2018-01-09 06:27
http://www.clipconverter.cc/  you can try this

**Comment by skthanu** [comment] 2018-01-09 07:26
thank you so much, I don't know why but now it is working.

**Comment by yan12125** [comment] 2018-01-09 08:33
Most likely a duplicate of #14307. Please move there if it's broken again.

**Closed by yan12125** 2018-01-09 08:33 UTC
