### ISSUE TITLE
Add differing exit codes for differing end states

### ISSUE THREAD

**Issue by gaenserich** [rg3/youtube-dl#11430] opened 2016-12-12 23:34 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.12*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.12**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

When scripting, it is often useful to get different exit codes for different sorts of failures (e.g.  0 for everything went correct, 1 for unrecognized options, 2 for an authentication error, 3 for lack of pay wall credentials, etc.). Curl, for instance, provides some [extremely useful exit codes](https://curl.haxx.se/libcurl/c/libcurl-errors.html) that help scripters to provide other contingent reactions like reattempting the download, parsing the url for errors, etc. Moreover, having these error codes would be more elegant than redirecting stderr to stdout and grep'ing the resulting string for key phrases.

**Comment by dstftw** [comment] 2016-12-13 02:39
Duplicate of #882.

**Closed by dstftw** 2016-12-13 02:39 UTC
