### ISSUE TITLE
Can no longer download from Xhamster - Extractor is unable to extract title

### ISSUE THREAD

**Issue by FeinesFabi** [rg3/youtube-dl#7001] opened 2015-09-27 16:00 UTC
Can't download any video from xhamster any more. See output:

youtube-dl --verbose xhamster.com/movies/3433906/i_need_not_my_step_brothers_help.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'xhamster.com/movies/3433906/i_need_not_my_step_brothers_help.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.22
[debug] Python version 2.7.9 - Linux-3.19.0-26-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, ffmpeg information, ffprobe information
[debug] Proxy map: {}
WARNING: The url doesn't specify the protocol, trying with http
[XHamster] 3433906: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 287, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/xhamster.py", line 66, in _real_extract
    title = self._html_search_regex(r'<title>(?P<title>.+?) - xHamster\.com</title>', webpage, 'title')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 590, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 581, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment] 2015-09-27 17:43
Duplicate of #6944.
This is already fixed in master and will be incorporated in the next version of youtube-dl.

**Closed by dstftw** 2015-09-27 17:43 UTC

**Comment by bglu** [comment] 2015-09-27 18:18
Ah, sorry for the duplicate. I can confirm that issue is resolved in the master branch.

**Comment by FeinesFabi** [comment] 2015-09-27 18:19
Sorry for the duplicate. I can confirm that the issue is resolved in the master branch.
