### ISSUE TITLE
certain videos cannot be downloaded from YouTube

### ISSUE THREAD

**Issue by jelabarre59** [rg3/youtube-dl#8858] opened 2016-03-14 20:25 UTC
I have found a handful of videos on YouTube that youtube-dl (2016.03.06) is not able to download.  As an example, trying https://www.youtube.com/watch?v=rSy0JtBCZMQ will show:

=================================
$ youtube-dl --prefer-ffmpeg https://www.youtube.com/watch?v=rSy0JtBCZMQ
[youtube] rSy0JtBCZMQ: Downloading webpage
[youtube] rSy0JtBCZMQ: Downloading embed webpage
[youtube] rSy0JtBCZMQ: Refetching age-gated info webpage
[youtube] rSy0JtBCZMQ: Extracting video information
[youtube] RTMP download detected
[download] Destination: STAR BLAZERS Ep. 1 'The Battle At Pluto'-rSy0JtBCZMQ.unknown_video
ERROR: unable to download video
=================================

Other videos such as https://www.youtube.com/watch?v=Qt7EKwBPxCo (I just tested it now) works fine (it even handles the Kanji in the file name).

**Comment by dstftw** [comment] 2016-03-15 17:34
Duplicate of #343.

**Closed by dstftw** 2016-03-15 17:34 UTC
