### ISSUE TITLE
Playlist author output template variable

### ISSUE THREAD

**Issue by wlhlm** [rg3/youtube-dl#15018] opened 2017-12-17 18:23 UTC
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

I'm trying to download playlists from Youtube and want to have them organized by the account that created the playlist. AFAICT, `youtube-dl` only gives the _video_ author for output templates, which works as long as the playlist only includes videos from the same author.

Here is what I'm currently using: `"%(uploader)s/%(playlist)s/%(playlist_index)s %(title)s.%(ext)s"`

Let's say we have author1 with video1, video2, and playlist1, and author2 with video 3. playlist1 includes video1, video2, and video3. With the above template I end up with the following file structure when downloading playlist1:
```
author1/
   +- playlist1/
      +- video1
      +- video2
author2/
   +- playlist1/
      +- video3
```
What I want is:
```
author1/
   +- playlist1/
      +- video1
      +- video2
      +- video3
```
Which means I currently have to manually merge the author directories after downloading.

My request is to add an output template variable that corresponds to the author of the playlist (for example `playlist_uploader`).

**Comment by dstftw** [comment] 2017-12-17 18:35
Duplicate of #11427.

**Closed by dstftw** 2017-12-17 18:35 UTC
