### ISSUE TITLE
[DPlay] subtitles download no longer works on Dplay.no

### ISSUE THREAD

**Issue by petersellers66** [rg3/youtube-dl#15438] opened 2018-01-27 20:52 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.27*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.27**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
lay.no/videoer/forste-date/sesong-1-episode-1
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--list-subs', '-v', 'https://www.dplay.no/videoer/f
orste-date/sesong-1-episode-1']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.01.27
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-79209-gb3eda69
[debug] Proxy map: {}
[debug] Using fake IP 84.212.179.222 (NO) as X-Forwarded-For.
[DPlay] forste-date/sesong-1-episode-1: Downloading webpage
[DPlay] forste-date/sesong-1-episode-1: Downloading token
[DPlay] forste-date/sesong-1-episode-1: Downloading JSON metadata
[DPlay] forste-date/sesong-1-episode-1: Downloading JSON metadata
[DPlay] forste-date/sesong-1-episode-1: Downloading MPD manifest
[DPlay] forste-date/sesong-1-episode-1: Downloading m3u8 information
38720 has no subtitles
...
<end of log>
```
---

### Description of your *issue*, suggested solution and other information
video downloads fine
but Youtube-dl can't find any subtitles

**Comment by dstftw** [comment] 2018-01-27 22:28
Duplicate of #6106.

**Closed by dstftw** 2018-01-27 22:28 UTC
