### ISSUE TITLE
ffmpeg merged files have wrong mtime

### ISSUE THREAD

**Issue by trapexit** [rg3/youtube-dl#17156] opened 2018-08-05 00:50 UTC
Latest version

When using `-f best` and getting a single file the mtime is correct but using `bestvideo+bestaudio` and merging with ffmpeg the resulting file does not get updated with the correct mtime.

**Comment by dstftw** [comment] 2018-08-05 00:53
This is expected behavior since the resulting merged file does not exist on remote server thus mtime does not exist as well.

**Closed by dstftw** 2018-08-05 00:53 UTC

**Comment by trapexit** [comment] 2018-08-05 00:58
Why does it matter if it's on the remote server? The data is relevant and not provide in any other way. At least include it in the file naming template so the precise time is available.

**Comment by dstftw** [comment] 2018-08-05 01:02
Because mtime is set from last-modified header reported for concrete file.
