### ISSUE TITLE
HTTP Error 403 Forbidden for a Youtube video.

### ISSUE THREAD

**Issue by bayuah** [rg3/youtube-dl#6632] opened 2015-08-21 18:42 UTC
**Command**

```youtube-dl  --dump-json "Mq9R23D85_M"```

**Message**
``` WARNING: [youtube] Mq9R23D85_M: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError());```

**Version**
```bash
$ youtube-dl --version
2015.08.16.1
````
**Country**
Indonesia

**Note 1**

When I download URL which provided by the json file, it give me:
```
--2015-08-22 00:58:55--  https://[somedomain]/[very-very-long-url]
Resolving [somedomain] ([somedomain])... [someip]
Connecting [somedomain] ([somedomain])|[someip]|:[someport]... connected.
HTTP request sent, awaiting response...
  HTTP/1.1 403 Forbidden
  Last-Modified: Wed, 02 May 2007 10:26:10 GMT
  Content-Type: text/plain
  Content-Length: 0
  Connection: close
  X-Content-Type-Options: nosniff
  Date: Fri, 21 Aug 2015 17:58:55 GMT
  Server: gvs 1.0
2015-08-22 00:58:55 ERROR 403: Forbidden.
```
**Note 2**

It also happen when I issued ```youtube-dl "Mq9R23D85_M"``` command. Even it showed ```ERROR: unable to download video data: HTTP Error 403: Forbidden```.

**Note 3**

It's a 4K video.

**Comment by dstftw** [comment] 2015-08-21 18:43
Duplicate of #6451. Remove cache with `youtube-dl --rm-cache-dir`.

**Closed by dstftw** 2015-08-21 18:43 UTC

**Comment by bayuah** [comment] 2015-08-23 04:11
You're awesome!

**Comment by bayuah** [comment] 2015-08-24 05:35
**SUGGESTION**
Give `youtube-dl --rm-cache-dir` suggestion in error message. So, if anyone stuck with this error can try it before send an issue report.
