### ISSUE TITLE
trouble downloading from site

### ISSUE THREAD

**Issue by inemesitaffia** [rg3/youtube-dl#10383] opened 2016-08-19 11:38 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.19*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.19**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [x ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl -v --call-home http://money.cnn.com/video/technology/2015/06/12/apple-upper-east-side-new-store.cnnmoney/index.html?category=video&iid=EL
[debug] System config: []
[debug] User config: ['-o', '~/youtube-dlstore/%(title)s%(id)s.%(ext)s']
[debug] Command-line args: ['-v', '--call-home', 'http://money.cnn.com/video/technology/2015/06/12/apple-upper-east-side-new-store.cnnmoney/index.html?category=video']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.08.13
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: none
[debug] Proxy map: {}
[debug] Public IP address: 197.210.225.145
WARNING: You are using an outdated version (newest version: 2016.08.19)! See https://yt-dl.org/update if you need help updating.
[generic] index: Requesting header
WARNING: Falling back on generic information extractor.
[generic] index: Downloading webpage
[generic] index: Extracting information
[generic] apple-upper-east-side-new-store: Requesting header
WARNING: Falling back on generic information extractor.
[generic] apple-upper-east-side-new-store: Downloading webpage
[generic] apple-upper-east-side-new-store: Extracting information
ERROR: Unsupported URL: https://secure.money.cnn.com/.element/apps/cvp2/players/twitter/player.html?videoid=video/technology/2015/06/12/apple-upper-east-side-new-store.cnnmoney
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpz_7f3hc1\build\youtube_dl\YoutubeDL.py", line 691, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpz_7f3hc1\build\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpz_7f3hc1\build\youtube_dl\extractor\generic.py", line 2344, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://secure.money.cnn.com/.element/apps/cvp2/players/twitter/player.html?videoid=video/technology/2015/06/12/apple-upper-east-side-new-store.cnnmoney

'iid' is not recognized as an internal or external command,
operable program or batch file.
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

**Comment by yan12125** [comment] 2016-08-19 11:42
Duplicate of #2797. CNN money is not supported yet.

**Closed by yan12125** 2016-08-19 11:42 UTC
