### ISSUE TITLE
Can't download The Daily Show anymore

### ISSUE THREAD

**Issue by hstracker90** [rg3/youtube-dl#11326] opened 2016-11-30 08:56 UTC
After Nov. 18th the Comedy Central must have implemented some serious changes. Youtube-dl is unable to even find the videos anymore: "Unable to extract mgid". Please look into this. Thank you very much.

PS C:\Windows\system32> youtube-dl http://www.cc.com/full-episodes/690ag3/the-daily-show-with-trevor-noah-november-29--2016---mahershala-ali-season-22-ep-22029 --verbose
[debug] System config: []
[debug] User config: ['-o', 'C:/Users/hstracker90/Downloads/%(title)s.%(ext)s']
[debug] Command-line args: ['http://www.cc.com/full-episodes/690ag3/the-daily-show-with-trevor-noah-november-29--2016---mahershala-ali-season-22-ep-22029', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.11.27
[debug] Python version 3.4.4 - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg N-80097-g89e9393, ffprobe N-80097-g89e9393, rtmpdump 2.4
[debug] Proxy map: {}
[ComedyCentral] the-daily-show-with-trevor-noah-november-29--2016---mahershala-ali-season-22-ep-22029: Downloading webpage
ERROR: Unable to extract mgid; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi2nj3req\build\youtube_dl\YoutubeDL.py", line 694,
in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi2nj3req\build\youtube_dl\extractor\common.py", line 357, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi2nj3req\build\youtube_dl\extractor\mtv.py", line 230, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi2nj3req\build\youtube_dl\extractor\mtv.py", line 224, in _extract_mgid
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi2nj3req\build\youtube_dl\extractor\common.py", line 660, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract mgid; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag
and include its complete output.

**Comment by vitusson** [comment] 2016-11-30 10:10
I have the same problem. I think it's caused by the mtv locator, which is in parts used by the comedycentral locator https://github.com/rg3/youtube-dl/issues/11148

**Comment by dstftw** [comment] 2016-11-30 16:25
This issue is already fixed and fix will be incorporated in the next version of youtube-dl.

**Closed by dstftw** 2016-11-30 16:25 UTC
