### ISSUE TITLE
Unsupported URL

### ISSUE THREAD

**Issue by Bachsau** [rg3/youtube-dl#10516] opened 2016-08-31 23:58 UTC
Could you please find out why it fails on http://www.tvnow.de/ntv/n-tv-dokumentation/achterbahnen-der-totale-nervenkitzel/player and fix it? Thanks.

**Comment by dstftw** [comment] 2016-09-01 02:12
Duplicate of #7831.

**Closed by dstftw** 2016-09-01 02:12 UTC
