### ISSUE TITLE
Dailymotion not working

### ISSUE THREAD

**Issue by dankunwizard** [rg3/youtube-dl#6338] opened 2015-07-22 22:53 UTC
All dailymotion videos cannot be downloaded.

$ youtube-dl --verbose https://www.dailymotion.com/video/x2ywrao_red-bull-can-timelapse-drawing_creation
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.dailymotion.com/video/x2ywrao_red-bull-can-timelapse-drawing_creation']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.21
[debug] Python version 2.7.3 - Linux-3.2.0-3-amd64-x86_64-with-debian-7.8
[debug] exe versions: avconv 0.8.17-6, avprobe 0.8.17-6, ffmpeg 0.8.17-6, ffprobe 0.8.17-6, rtmpdump 2.4
[debug] Proxy map: {}
[dailymotion] x2ywrao: Downloading webpage
[dailymotion] x2ywrao: Extracting information
[dailymotion] x2ywrao: Downloading embed page
ERROR: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 656, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 120, in _real_extract
    'video info', flags=re.MULTILINE)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 557, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment] 2015-07-23 03:23
Duplicate of #6151.

**Closed by dstftw** 2015-07-23 03:23 UTC
