### ISSUE TITLE
Disney Junior - Comcast - Unable to extract post url

### ISSUE THREAD

**Issue by Barbegazi** [rg3/youtube-dl#12669] opened 2017-04-06 15:35 UTC
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.03**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Bug report (encountered problems with youtube-dl)
---
```
C:\>youtube-dl.exe --ap-mso=Comcast_SSO --ap-username=foo --ap-password=bar --verbose http://watchdisneyjunior.go.com/miles-from-tomorrowland/video/vdka3764052/02/18-who-stole-the-dinosaur-nine-minutes-til-bedtime#playlist=PL551978168
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ap-mso=Comcast_SSO', '--ap-username=PRIVATE', '--ap-password=PRIVATE', '--verbose', 'http://watchdisneyjunior.go.com/miles-from-tomorrowland/video/vdka3764052/02/18-who-stole-the-dinosaur-nine-minutes-til-bedtime#playlist=PL551978168']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.04.03
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-84348-gdb7a05d, ffprobe N-84348-gdb7a05d
[debug] Proxy map: {}
[Go] 18-who-stole-the-dinosaur-nine-minutes-til-bedtime: Downloading webpage
[Go] 3764052: Downloading JSON metadata
[Go] 3764052: Downloading Provider Redirect Page
ERROR: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpam8ojdsi\build\youtube_dl\YoutubeDL.py", line 761, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpam8ojdsi\build\youtube_dl\extractor\common.py", line 429, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpam8ojdsi\build\youtube_dl\extractor\go.py", line 98, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpam8ojdsi\build\youtube_dl\extractor\adobepass.py", line 1409, in _extract_mvpd_auth
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpam8ojdsi\build\youtube_dl\extractor\adobepass.py", line 1332, in post_form
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpam8ojdsi\build\youtube_dl\extractor\common.py", line 787, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpam8ojdsi\build\youtube_dl\extractor\common.py", line 778, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
---
When trying to download videos from http://disneyjunior.disney.com I get an error stating "unable to extract post url".  I'm able to view these videos in the browser after logging in with the same credentials provided on the command-line.

**Comment by yan12125** [comment] 2017-05-05 08:07
That's likely a duplicate of #12563, where Comcast support is broken. Please move on there for further discussions.

**Closed by yan12125** 2017-05-05 08:07 UTC
