### ISSUE TITLE
Cannot play purchased youtube video

### ISSUE THREAD

**Issue by nmrugg** [rg3/youtube-dl#5370] opened 2015-04-07 08:23 UTC
I can download the video, but it it downloads as unknown_video and it appears to be encrypted.

```
youtube-dl -u "PRIVATE" https://www.youtube.com/watch?v=rAUJN48IHXw --verbose -F
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'https://www.youtube.com/watch?v=rAUJN48IHXw', '--verbose', u'-F']
Type account password and press [Return]:
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.03
[debug] Python version 2.7.3
[debug] exe versions: ffmpeg 2.6.git, ffprobe 2.6.git
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Logging in
[youtube] rAUJN48IHXw: Downloading webpage
[youtube] rAUJN48IHXw: Extracting video information
[youtube] {60} signature length 41.40, html5 player en_US-vfl20EdcH
[youtube] rAUJN48IHXw: Downloading player https://s.ytimg.com/yts/jsbin/html5player-en_US-vfl20EdcH/html5player.js
[youtube] {52} signature length 41.40, html5 player en_US-vfl20EdcH
[youtube] {146} signature length 41.40, html5 player en_US-vfl20EdcH
[youtube] {197} signature length 41.40, html5 player en_US-vfl20EdcH
[youtube] {226} signature length 41.40, html5 player en_US-vfl20EdcH
[youtube] {227} signature length 41.40, html5 player en_US-vfl20EdcH
[youtube] {275} signature length 41.40, html5 player en_US-vfl20EdcH
[youtube] {145} signature length 41.40, html5 player en_US-vfl20EdcH
[youtube] {196} signature length 41.40, html5 player en_US-vfl20EdcH
[youtube] {224} signature length 41.40, html5 player en_US-vfl20EdcH
[youtube] {225} signature length 41.40, html5 player en_US-vfl20EdcH
[youtube] {274} signature length 41.40, html5 player en_US-vfl20EdcH
[youtube] {144} signature length 41.40, html5 player en_US-vfl20EdcH
[youtube] {195} signature length 41.40, html5 player en_US-vfl20EdcH
[youtube] {220} signature length 41.40, html5 player en_US-vfl20EdcH
[youtube] {221} signature length 41.40, html5 player en_US-vfl20EdcH
[youtube] {222} signature length 41.40, html5 player en_US-vfl20EdcH
[youtube] {223} signature length 41.40, html5 player en_US-vfl20EdcH
[youtube] {273} signature length 41.40, html5 player en_US-vfl20EdcH
[youtube] {143} signature length 41.40, html5 player en_US-vfl20EdcH
[youtube] {194} signature length 41.40, html5 player en_US-vfl20EdcH
[youtube] {280} signature length 41.40, html5 player en_US-vfl20EdcH
[youtube] {142} signature length 41.40, html5 player en_US-vfl20EdcH
[youtube] {279} signature length 41.40, html5 player en_US-vfl20EdcH
[youtube] {161} signature length 41.40, html5 player en_US-vfl20EdcH
[youtube] {148} signature length 41.40, html5 player en_US-vfl20EdcH
[youtube] {149} signature length 41.40, html5 player en_US-vfl20EdcH
[youtube] {150} signature length 41.40, html5 player en_US-vfl20EdcH
[youtube] {198} signature length 41.40, html5 player en_US-vfl20EdcH
[youtube] {199} signature length 41.40, html5 player en_US-vfl20EdcH
[youtube] rAUJN48IHXw: Downloading DASH manifest
[info] Available formats for rAUJN48IHXw:
format code  extension      resolution note
273          unknown_video  unknown
274          unknown_video  unknown
275          unknown_video  unknown
279          unknown_video  unknown
280          unknown_video  unknown
52           unknown_video  unknown
60           unknown_video  unknown
148          unknown_video  unknown      62k  (22050Hz), 66.23MiB
149          unknown_video  unknown     142k  (44100Hz), 170.25MiB
198          unknown_video  unknown     151k  (44100Hz), 142.12MiB
161          unknown_video  256x144     153k , 12fps, 140.81MiB
199          unknown_video  unknown     251k  (44100Hz), 206.09MiB
150          unknown_video  unknown     268k  (44100Hz), 331.77MiB
142          unknown_video  426x240     291k , 24fps, 315.71MiB
143          unknown_video  640x360     620k , 24fps, 472.94MiB
194          unknown_video  640x360     889k , 25fps, 657.86MiB
144          unknown_video  854x480    1132k , 24fps, 966.58MiB
195          unknown_video  854x480    1522k , 25fps, 1.08GiB
222          unknown_video  854x480    1704k , 24fps, 1.50GiB
220          unknown_video  854x480    2254k , 25fps, 1.19GiB
145          unknown_video  1280x720   2277k , 24fps, 1.85GiB
224          unknown_video  1280x720   3402k , 24fps, 2.96GiB
223          unknown_video  854x480    3404k , 24fps, 3.18GiB
196          unknown_video  1280x720   3834k , 25fps, 2.29GiB
221          unknown_video  854x480    4194k , 25fps, 1.41GiB
146          unknown_video  1920x1080  4578k , 24fps, 3.70GiB
225          unknown_video  1280x720   5657k , 24fps, 4.89GiB
226          unknown_video  1920x1080  6079k , 24fps, 5.80GiB
197          unknown_video  1920x1080  7648k , 25fps, 4.64GiB
227          unknown_video  1920x1080  8125k , 24fps, 8.08GiB (best)
```

Is it possible to play purchased youtube videos?

**Comment by jaimeMF** [comment] 2015-04-07 13:08
Duplicate of #1774, we haven't added support for them yet.

**Closed by jaimeMF** 2015-04-07 13:08 UTC
