### ISSUE TITLE
ERROR: unable to download video data: HTTP Error 403: Forbidden (for YT Video: https://www.youtube.com/watch?v=y83-vMeWc9E)

### ISSUE THREAD

**Issue by xiaose** [rg3/youtube-dl#6683] opened 2015-08-26 17:32 UTC
## This video cannot be downloaded: youtube-dl https://www.youtube.com/watch?v=y83-vMeWc9E

output:

**$** youtube-dl https://www.youtube.com/watch?v=y83-vMeWc9E -F -v
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=y83-vMeWc9E', u'-F', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.23
[debug] Python version 2.7.6 - Linux-3.13.0-61-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6
[debug] Proxy map: {}
[youtube] y83-vMeWc9E: Downloading webpage
[youtube] y83-vMeWc9E: Downloading video info webpage
[youtube] y83-vMeWc9E: Extracting video information
[youtube] {43} signature length 40.43, html5 player new
...
...
...
[youtube] {171} signature length 40.43, html5 player new
[youtube] y83-vMeWc9E: Downloading DASH manifest
WARNING: [youtube] y83-vMeWc9E: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[info] Available formats for y83-vMeWc9E:
format code  extension  resolution note
171          webm       audio only DASH audio , audio@128k
...
...
...
18           mp4        640x360    (best)
```
**$** youtube-dl https://www.youtube.com/watch?v=y83-vMeWc9E -v -f 18
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=y83-vMeWc9E', u'-v', u'-f', u'18']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.23
[debug] Python version 2.7.6 - Linux-3.13.0-61-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6
[debug] Proxy map: {}
[youtube] y83-vMeWc9E: Downloading webpage
[youtube] y83-vMeWc9E: Downloading video info webpage
[youtube] y83-vMeWc9E: Extracting video information
[youtube] {43} signature length 40.43, html5 player new
...
...
...
[youtube] {171} signature length 40.43, html5 player new
[youtube] y83-vMeWc9E: Downloading DASH manifest
WARNING: [youtube] y83-vMeWc9E: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[debug] Invoking downloader on u'https://r5---sn-3tp8nu5g-3c2l.googlevideo.com/videoplayback?requiressl=yes&source=youtube&initcwndbps=786250&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&lmt=1429685230402269&ipbits=0&fexp=9406984%2C9408710%2C9409069%2C9415365%2C9415485%2C9416023%2C9416126%2C9417707%2C9418153%2C9418449&dur=296.054&sver=3&ratebypass=yes&itag=18&key=yt5&mime=video%2Fmp4&id=o-AESK7C6LVy7Ksx-Y5KpL6se5QYVyNTlMjSHr3Rm7Zgek&mt=1440609676&mv=m&upn=52G2bTrzhLg&ms=au&ip=94.153.81.185&mm=31&mn=sn-3tp8nu5g-3c2l&expire=1440631407&pl=20&signature=60161A7A5769B43BC807A5ADEA0DD791A42D879A.53E0E01D6FA68A55511FC3EA2D1099717E54DC28'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1585, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1527, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 60, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1860, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
```

**Comment by dstftw** [comment] 2015-08-26 17:33
Duplicate of #6451. Remove cache with `youtube-dl --rm-cache-dir`.

**Closed by dstftw** 2015-08-26 17:33 UTC
