### ISSUE TITLE
infinite loop for iqiyi

### ISSUE THREAD

**Issue by xczheng** [rg3/youtube-dl#11776] opened 2017-01-19 05:24 UTC
youtube-dl http://www.iqiyi.com/v_19rr9sei90.html
[iqiyi] temp_id: download video page
WARNING: unable to extract album title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[iqiyi] 202783001: Download playlist page 2
[download] Downloading playlist: 202783001
[iqiyi] playlist 202783001: Collected 34 video ids (downloading 34 of them)
[download] Downloading video 1 of 34
[iqiyi] temp_id: download video page
WARNING: unable to extract album title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[iqiyi] 202861101: Download playlist page 2
[iqiyi] 202861101: Download playlist page 3
[iqiyi] 202861101: Download playlist page 4
[iqiyi] 202861101: Download playlist page 5
[iqiyi] 202861101: Download playlist page 6
[iqiyi] 202861101: Download playlist page 7
[iqiyi] 202861101: Download playlist page 8
[iqiyi] 202861101: Download playlist page 9
[iqiyi] 202861101: Download playlist page 10
[iqiyi] 202861101: Download playlist page 11
[iqiyi] 202861101: Download playlist page 12
[iqiyi] 202861101: Download playlist page 13
[iqiyi] 202861101: Download playlist page 14
[iqiyi] 202861101: Download playlist page 15
[iqiyi] 202861101: Download playlist page 16
[download] Downloading playlist: 202861101
[iqiyi] playlist 202861101: Collected 732 video ids (downloading 732 of them)
[download] Downloading video 1 of 732
[iqiyi] temp_id: download video page
WARNING: unable to extract album title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[iqiyi] 202861101: Download playlist page 2
[iqiyi] 202861101: Download playlist page 3
[iqiyi] 202861101: Download playlist page 4
[iqiyi] 202861101: Download playlist page 5
[iqiyi] 202861101: Download playlist page 6
[iqiyi] 202861101: Download playlist page 7
[iqiyi] 202861101: Download playlist page 8
[iqiyi] 202861101: Download playlist page 9
[iqiyi] 202861101: Download playlist page 10
[iqiyi] 202861101: Download playlist page 11
[iqiyi] 202861101: Download playlist page 12
[iqiyi] 202861101: Download playlist page 13
[iqiyi] 202861101: Download playlist page 14
[iqiyi] 202861101: Download playlist page 15
[iqiyi] 202861101: Download playlist page 16
[download] Downloading playlist: 202861101
[iqiyi] playlist 202861101: Collected 732 video ids (downloading 732 of them)
[download] Downloading video 1 of 732
[iqiyi] temp_id: download video page
WARNING: unable to extract album title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[iqiyi] 202861101: Download playlist page 2
[iqiyi] 202861101: Download playlist page 3
[iqiyi] 202861101: Download playlist page 4
[iqiyi] 202861101: Download playlist page 5
[iqiyi] 202861101: Download playlist page 6
[iqiyi] 202861101: Download playlist page 7
[iqiyi] 202861101: Download playlist page 8
[iqiyi] 202861101: Download playlist page 9
[iqiyi] 202861101: Download playlist page 10
[iqiyi] 202861101: Download playlist page 11
[iqiyi] 202861101: Download playlist page 12
[iqiyi] 202861101: Download playlist page 13
[iqiyi] 202861101: Download playlist page 14
[iqiyi] 202861101: Download playlist page 15
[iqiyi] 202861101: Download playlist page 16
[download] Downloading playlist: 202861101
[iqiyi] playlist 202861101: Collected 732 video ids (downloading 732 of them)
[download] Downloading video 1 of 732
[iqiyi] temp_id: download video page
WARNING: unable to extract album title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[iqiyi] 202861101: Download playlist page 2
[iqiyi] 202861101: Download playlist page 3
[iqiyi] 202861101: Download playlist page 4
[iqiyi] 202861101: Download playlist page 5
[iqiyi] 202861101: Download playlist page 6
[iqiyi] 202861101: Download playlist page 7
[iqiyi] 202861101: Download playlist page 8
[iqiyi] 202861101: Download playlist page 9
[iqiyi] 202861101: Download playlist page 10
[iqiyi] 202861101: Download playlist page 11
[iqiyi] 202861101: Download playlist page 12
[iqiyi] 202861101: Download playlist page 13
[iqiyi] 202861101: Download playlist page 14
[iqiyi] 202861101: Download playlist page 15
[iqiyi] 202861101: Download playlist page 16
[download] Downloading playlist: 202861101
[iqiyi] playlist 202861101: Collected 732 video ids (downloading 732 of them)
[download] Downloading video 1 of 732
...
infinite loop here.

**Comment by yan12125** [comment] 2017-02-03 10:48
Seems working now. Is it still a problem for you?
```
$ youtube-dl -v "http://www.iqiyi.com/v_19rr9sei90.html" --geo-verification-proxy http://61.53.65.54:3128/ 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.iqiyi.com/v_19rr9sei90.html', '--geo-verification-proxy', 'http://61.53.65.54:3128/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.01
[debug] Git HEAD: d7f9242e3
[debug] Python version 3.6.0 - Linux-4.9.5-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2
[debug] Proxy map: {}
[iqiyi] temp_id: download video page
[iqiyi] 70049e6d42a7e8356362782047d37f3b: Downloading JSON metadata
[debug] Invoking downloader on 'http://cache.m.iqiyi.com/dc/dt/text/fb0a7d16x2fee3eb9x777a6171/20161225/8e/6b/f4dc1eb6be1e71ddcefff5c844c61b3d.m3u8?np_tag=nginx_part_tag&qd_sc=9f021e899d5d9ee5ab8115f8915ee621&t_sign=-0-76f90cbd92f94a2e925d83e8ccd22cb7-591217800_04022000001000000000_4'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 185
[download] Destination: 龍珠超：第72集 能否發出反擊! 看不見的殺人招式!!-70049e6d42a7e8356362782047d37f3b.mp4
[download]  33.5% of ~156.59MiB at 749.70KiB/s ETA 01:59^C
ERROR: Interrupted by user
Exception ignored in: <_io.FileIO name='龍珠超：第72集 能否發出反擊! 看不見的殺人招式!!-70049e6d42a7e8356362782047d37f3b.mp4.part' mode='wb' closefd=True>
ResourceWarning: unclosed file <_io.FileIO name='龍珠超：第72集 能否發出反擊! 看不見的殺人招式!!-70049e6d42a7e8356362782047d37f3b.mp4.part' mode='wb' closefd=True>
```

**Comment by ThomasChr** [comment] 2017-02-03 11:16
Also no problem here for me!

**Comment by yan12125** [comment] 2017-04-25 14:36
I believe this is a duplicate of #12504 and already fixed in git master. Please move on there for further discussions.

**Closed by yan12125** 2017-04-25 14:36 UTC
Labels: cant-reproduce, geo-restricted
