### ISSUE TITLE
I can not getlink VEVO video on youtube.com

### ISSUE THREAD

**Issue by haibk** [rg3/youtube-dl#7431] opened 2015-11-10 09:28 UTC
https://www.youtube.com/watch?v=CevxZvSJLk8 or
https://www.youtube.com/watch?v=0KSOMA3QBU0
I run the command:
youtube-dl https://www.youtube.com/watch?v=0KSOMA3QBU0
I get the message:
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 709, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment] 2015-11-10 09:29
Duplicate of #7413. This will be fixed in the next version.

**Closed by yan12125** 2015-11-10 09:29 UTC

**Comment by haibk** [comment] 2015-11-10 09:36
Thanks you!
