### ISSUE TITLE
myvideo bug

### ISSUE THREAD

**Issue by emcu** [rg3/youtube-dl#2487] opened 2014-03-01 16:56 UTC
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.myvideo.de/TV/Weitere_Sender/misfits?videoId=8930373']
[debug] youtube-dl version 2013.12.04
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.4
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: http://www.myvideo.de/TV/Weitere_Sender/misfits?videoId=8930373; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 429, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 131, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 236, in _real_extract
    raise ExtractorError(u'Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.myvideo.de/TV/Weitere_Sender/misfits?videoId=8930373; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by muelli** [comment] 2015-11-07 12:00
same here

```
youtube-dl --verbose 'http://www.myvideo.de/TV/Weitere_Sender/misfits?videoId=8930373'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.myvideo.de/TV/Weitere_Sender/misfits?videoId=8930373']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.28
[debug] Python version 2.7.9 - Linux-3.19.0-31-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, rtmpdump 2.4
[debug] Proxy map: {}
[generic] misfits?videoId=8930373: Requesting header
[redirect] Following redirect to http://www.myvideo.de/serien/misfits?videoId=8930373
[generic] misfits?videoId=8930373: Requesting header
WARNING: Falling back on generic information extractor.
[generic] misfits?videoId=8930373: Downloading webpage
[generic] misfits?videoId=8930373: Extracting information
ERROR: Unsupported URL: http://www.myvideo.de/serien/misfits?videoId=8930373
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 751, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/utils.py", line 1522, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 38, column 448
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 643, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 1202, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.myvideo.de/serien/misfits?videoId=8930373
```

**Comment by dstftw** [comment] 2016-02-14 04:46
Duplicate of #4145.

**Closed by dstftw** 2016-02-14 04:46 UTC
