### ISSUE TITLE
Error downloads from pornhub

### ISSUE THREAD

**Issue by Denisov39** [rg3/youtube-dl#12111] opened 2017-02-13 07:38 UTC
youtube-dl -v http://www.pornhub.com/view_video.php?viewkey=596061522

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.pornhub.com/view_video.php?viewkey=596061522']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.11
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.7
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[PornHub] 596061522: Downloading webpage
[debug] Invoking downloader on u'/*ec08d6387763c880af511344*/d4eb3e392169dff7616bca7/*ec08d6387763c880af511344*/d35c099301917af7c73aed80/*e92*/f78222ac93cd64/*d4eb3e392169dff7616bca7*/a5c5f28a6316f3a1563635c/*d4529b20ee*/b0015bce1c726bcb29/*d4eb3e392169dff7616bca7*/dc261ae39f2/*f58f65*/e92/*f58f65*/d4529b20ee/*d4eb3e392169dff7616bca7*/ec08d6387763c880af511344/*bfc28665*/bfc28665/*b0015bce1c726bcb29*/f58f65/*bfc28665*/e0db3b6d406cbf15068/*acdeead0d7f0a492bcb13692b*/acdeead0d7f0a492bcb13692b'
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 452, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 442, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1796, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 707, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 753, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1440, in process_video_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1704, in process_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1646, in dl
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 353, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 61, in real_download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2006, in urlopen
  File "/usr/lib/python2.7/urllib2.py", line 423, in open
    protocol = req.get_type()
  File "/usr/lib/python2.7/urllib2.py", line 285, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: /*ec08d6387763c880af511344*/d4eb3e392169dff7616bca7/*ec08d6387763c880af511344*/d35c099301917af7c73aed80/*e92*/f78222ac93cd64/*d4eb3e392169dff7616bca7*/a5c5f28a6316f3a1563635c/*d4529b20ee*/b0015bce1c726bcb29/*d4eb3e392169dff7616bca7*/dc261ae39f2/*f58f65*/e92/*f58f65*/d4529b20ee/*d4eb3e392169dff7616bca7*/ec08d6387763c880af511344/*bfc28665*/bfc28665/*b0015bce1c726bcb29*/f58f65/*bfc28665*/e0db3b6d406cbf15068/*acdeead0d7f0a492bcb13692b*/acdeead0d7f0a492bcb13692b

**Comment by yan12125** [comment] 2017-02-13 07:50
Duplicate of #12007

**Closed by yan12125** 2017-02-13 07:50 UTC
