### ISSUE TITLE
Downloading playlists from a channel into folders

### ISSUE THREAD

**Issue by miacaba** [rg3/youtube-dl#7594] opened 2015-11-21 19:21 UTC
Hello,

I'm trying to get a channel playlist to download into folders. I tried using the following command but got this error:

youtube-dl --youtube-skip-dash-manifest -f 18 "https://www.youtube.com/user/OUlearn/playlists" --get-filename -o "/%(playlist)s/%(playlist_index)s-%(title)s.%(ext)s" --restrict-filenames

WARNING: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)> (caused by URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))

What is wrong with this? or what is the proper command? I would like to get them in 480p if possible, with each playlist in its own folder. Thank you.

**Comment by dstftw** [comment] 2015-11-21 19:22
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by miacaba** [comment] 2015-11-21 19:25
youtube-dl --youtube-skip-dash-manifest -f 18 "https:/
/www.youtube.com/user/OUlearn/playlists" --get-filename -o "/(playlist_index)s-(
ext)s" --restrict-filenames --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--youtube-skip-dash-manifest', u'-f', u'18', u'htt
ps://www.youtube.com/user/OUlearn/playlists', u'--get-filename', u'-o', u'/(play
list_index)s-(ext)s', u'--restrict-filenames', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.11.19
[debug] Python version 2.7.10 - Windows-XP-5.1.2600-SP3
[debug] exe versions: none
[debug] Proxy map: {}
WARNING: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAI
LED] certificate verify failed (_ssl.c:590)>
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILE
D] certificate verify failed (_ssl.c:590)> (caused by URLError(SSLError(1, u'[SS
L: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))
  File "youtube_dl\extractor\common.pyo", line 329, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1873, in urlopen
  File "urllib2.pyo", line 431, in open
  File "urllib2.pyo", line 449, in _open
  File "urllib2.pyo", line 409, in _call_chain
  File "youtube_dl\utils.pyo", line 798, in https_open
  File "urllib2.pyo", line 1197, in do_open

**Comment by dstftw** [comment] 2015-11-21 19:27
Duplicate of #7309. Non secure solution: https://github.com/rg3/youtube-dl/issues/7309#issuecomment-156447651.

**Closed by dstftw** 2015-11-21 19:27 UTC
