### ISSUE TITLE
403 Error downloading from youtube qrdpliMfoAM

### ISSUE THREAD

**Issue by rhnvrm** [rg3/youtube-dl#6627] opened 2015-08-20 18:19 UTC
Hi,

I was trying to download from youtube: qrdpliMfoAM but I am getting the following error. I'm on latest version (v2015.08.16.1)

	youtube-dl -f 171 https://www.youtube.com/watch?v=qrdpliMfoAM --verbose
	[debug] System config: []
	[debug] User config: []
	[debug] Command-line args: [u'-f', u'171', u'https://www.youtube.com/watch?v=qrdpliMfoAM', u'--verbose']
	[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
	[debug] youtube-dl version 2015.08.16.1
	[debug] Python version 2.7.6 - Linux-3.14.2-031402-generic-x86_64-with-Ubuntu-14.04-trusty
	[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, rtmpdump 2.4
	[debug] Proxy map: {}
	[youtube] qrdpliMfoAM: Downloading webpage
	[youtube] qrdpliMfoAM: Downloading video info webpage
	[youtube] qrdpliMfoAM: Extracting video information
	[youtube] {43} signature length 40.42, html5 player new
	[youtube] {18} signature length 40.42, html5 player new
	[youtube] {5} signature length 40.42, html5 player new
	[youtube] {36} signature length 40.42, html5 player new
	[youtube] {17} signature length 40.42, html5 player new
	[youtube] {135} signature length 40.42, html5 player new
	[youtube] {244} signature length 40.42, html5 player new
	[youtube] {134} signature length 40.42, html5 player new
	[youtube] {243} signature length 40.42, html5 player new
	[youtube] {133} signature length 40.42, html5 player new
	[youtube] {242} signature length 40.42, html5 player new
	[youtube] {160} signature length 40.42, html5 player new
	[youtube] {140} signature length 40.42, html5 player new
	[youtube] {171} signature length 40.42, html5 player new
	[youtube] qrdpliMfoAM: Downloading DASH manifest
	WARNING: [youtube] qrdpliMfoAM: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
	[debug] Invoking downloader on u'https://r3---sn-gxap5ojx-qxae.googlevideo.com/videoplayback?initcwndbps=2946250&gir=yes&source=youtube&pl=24&mt=1440094346&mv=m&clen=2723782&ms=au&sver=3&expire=1440116030&requiressl=yes&mm=31&mn=sn-gxap5ojx-qxae&ipbits=0&itag=171&id=o-ACvIPid3vdoGEekdXAaYNvy4UVHeAYG8dL5H78FQh2xI&key=yt5&ip=103.27.164.45&lmt=1392720422884786&dur=233.025&pcm2cms=yes&fexp=9408087%2C9408710%2C9409069%2C9415365%2C9415485%2C9416023%2C9416126%2C9416347%2C9417116%2C9417707%2C9418153%2C9418220%2C9418449%2C9418493%2C9419446%2C9419506&keepalive=yes&mime=audio%2Fwebm&upn=2ux_By1GSwc&sparams=clen%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&signature=5AA5245D8E6587F5EE7973A21BDE764778BCE356.618F37674A241A35556D67C7A81623CB3388A550&ratebypass=yes'
	ERROR: unable to download video data: HTTP Error 403: Forbidden
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1585, in process_info
	    success = dl(filename, info_dict)
	  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1527, in dl
	    return fd.download(name, info)
	  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 342, in download
	    return self.real_download(filename, info_dict)
	  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 60, in real_download
	    data = self.ydl.urlopen(request)
	  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1860, in urlopen
	    return self._opener.open(req, timeout=self._socket_timeout)
	  File "/usr/lib/python2.7/urllib2.py", line 410, in open
	    response = meth(req, response)
	  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
	    'http', request, response, code, msg, hdrs)
	  File "/usr/lib/python2.7/urllib2.py", line 448, in error
	    return self._call_chain(*args)
	  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
	    result = func(*args)
	  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
	    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
	HTTPError: HTTP Error 403: Forbidden

**Comment by yan12125** [comment] 2015-08-20 18:20
Duplicate of #6451. Remove the cache with ```youtube-dl --rm-cache-dir``` and try again.

**Closed by yan12125** 2015-08-20 18:20 UTC
