### ISSUE TITLE
"ERROR: unable to download latest version"

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#10411] opened 2016-08-23 01:58 UTC
I never had problems in updating youtube-dl with its -U until today:

$ youtube-dl -v -U
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-U']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.13
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.5
[debug] exe versions: ffmpeg 3.0.2-4, ffprobe 3.0.2-4, rtmpdump 2.4
[debug] Proxy map: {}
Updating to version 2016.08.22 ...
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/update.py", line 148, in update_self
    urlh = opener.open(version['bin'][0])
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/home/ant/bin/youtube-dl/youtube_dl/utils.py", line 1004, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 101] Network is unreachable>

ERROR: unable to download latest version

I am using Debian stable (Jessie). Thank you in advance. :)

**Comment by dstftw** [comment] 2016-08-23 02:02
Duplicate of #10410.

**Closed by dstftw** 2016-08-23 02:02 UTC
