### ISSUE TITLE
Windows execute after download problem

### ISSUE THREAD

**Issue by jcandresen** [rg3/youtube-dl#11315] opened 2016-11-28 19:55 UTC
Using the --exec command in Windows let me move files 

[http://imgur.com/qd09ecO](screenshot of output)

The problem is it uses single quotation which cmd apparently won't work with.

Is there any way to set it to use double quotes instead? 

Thank you.

**Comment by dstftw** [comment] 2016-11-28 20:05
Duplicate of #5889.

**Closed by dstftw** 2016-11-28 20:05 UTC
