### ISSUE TITLE
An extractor error has occurred. (caused by KeyError(u'id',))

### ISSUE THREAD

**Issue by gandaman** [rg3/youtube-dl#8536] opened 2016-02-12 22:47 UTC
```
youtube-dl --verbose https://www.youtube.com/watch?v=gVfLd0zydlo
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=gVfLd0zydlo']
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2016.02.10
[debug] Python version 2.7.2 - Darwin-12.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.6.3, ffprobe 2.6.3, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] gVfLd0zydlo: Downloading webpage
[youtube] gVfLd0zydlo: Downloading video info webpage
ERROR: An extractor error has occurred. (caused by KeyError(u'id',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 315, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1206, in _real_extract
    '%s://www.youtube.com/watch?v=%s' % (proto, feed_data['id'][0]),
KeyError: u'id'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 321, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'id',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by gandaman** [comment] 2016-02-12 22:51
By the way I noticed the other videos in the series have a very long title

**Comment by dstftw** [comment] 2016-02-12 23:00
This issue has been fixed and fix will be incorporated in the next version of youtube-dl.

**Closed** 2016-02-12 23:00 UTC

**Comment by gandaman** [comment] 2016-02-12 23:18
Whoa that was amazingly fast.  :+1:

**Comment by thescorpioracer** [comment] 2020-07-24 00:14
youtube-dl --verbose https://tv.nrk.no/serie/17/sesong/1/episode/1/avspiller 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://tv.nrk.no/serie/17/sesong/1/episode/1/avspiller']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 2.7.16 (CPython) - Darwin-19.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg N-90866-g48330500ef-tessus
[debug] Proxy map: {}
[NRKTVEpisode] 17/sesong/1/episode/1: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError(u'@id',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/nrk.py", line 430, in _real_extract
    display_id)['@id']
KeyError: u'@id'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 543, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'@id',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by thescorpioracer** [comment] 2020-07-24 00:18
I've run into the problem now, with the latest version of youtube-dl installed. I'm newer to coding/command line, but in the past I have been able to extract videos from this site with no problems. And I can't get videos off of other sites now either... 

Any help would be greatly appreciated! (I am using a Macbook pro, if that makes any difference for finding a solution)
