### ISSUE TITLE
Launching Youtube-dl as a background command

### ISSUE THREAD

**Issue by vanilla38** [rg3/youtube-dl#955] opened 2013-06-27 19:19 UTC
Hi, I just noticed when i try to launch $ youtube-dl http://www.ZZzzzZZ.com &
It fails, program cant terminate.

Any clue ? Thanks.

**Comment by ayushgoel** [comment] 2016-04-14 06:09
+1
Running `youtube-dl` in background stops the download. Bringing it back with `fg` starts the download.

**Comment by yan12125** [comment] 2016-04-14 07:03
The problematic lines lays in ffmpeg:
```C
        if (tcgetattr (0, &tty) == 0) {
            oldtty = tty;
            restore_tty = 1;

            tty.c_iflag &= ~(IGNBRK|BRKINT|PARMRK|ISTRIP
                             |INLCR|IGNCR|ICRNL|IXON);
            tty.c_oflag |= OPOST;
            tty.c_lflag &= ~(ECHO|ECHONL|ICANON|IEXTEN);
            tty.c_cflag &= ~(CSIZE|PARENB);
            tty.c_cflag |= CS8;
            tty.c_cc[VMIN] = 1;
            tty.c_cc[VTIME] = 0;

            tcsetattr (0, TCSANOW, &tty);
        }
```
(See: https://github.com/FFmpeg/FFmpeg/blob/6f69f7a8bf6a0d013985578df2ef42ee6b1c7994/ffmpeg.c#L371-L385)
The code segment above tries to ```ioctl()``` on STDOUT. Kernel then sends SIGTTOU to the calling process, youtube-dl. A workaround is avoiding ffmpeg/avconv calls by tricking youtube-dl that ffmpeg does not exist:
```
$ youtube-dl -v http://vimeo.com/79695097 --ffmpeg-location /path/not/exist &
[1] 22603

$ [debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://vimeo.com/79695097', '--ffmpeg-location', '/path/not/exist']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.13
[debug] Git HEAD: d1c4e4b
[debug] Python version 3.5.1 - Linux-4.5.0-1-ARCH-x86_64-with-arch-Arch-Linux
WARNING: ffmpeg-location /path/not/exist does not exist! Continuing without avconv/ffmpeg.
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[vimeo] 79695097: Downloading webpage
[vimeo] 79695097: Extracting information
[vimeo] 79695097: Downloading webpage
[vimeo] 79695097: Downloading JSON metadata
[vimeo] 79695097: Checking Original video URL
[vimeo] 79695097: Original video URL is invalid, skipping
[vimeo] 79695097: Downloading m3u8 information
WARNING: ffmpeg-location /path/not/exist does not exist! Continuing without avconv/ffmpeg.
[debug] Invoking downloader on 'https://10-lvl3-pdl.vimeocdn.com/01/939/3/79695097/206208039.mp4?expires=1460620853&token=06d817e44ae6452e6b2f6'
[download] Destination: IDIOTS-79695097.mp4
[download] 100% of 67.08MiB in 00:19

[1]  + 22603 done       youtube-dl -v http://vimeo.com/79695097 --ffmpeg-location /path/not/exist
```
This is the case on Linux. Don't know the case in IRIX.

I guess there's nothing youtube-dl can do unless we have a patched ffmpeg or a patched Linux kernel, so closing this ticket here. Feel free to propose your solution and I or others will reopen this ticket.

**Closed by yan12125** 2016-04-14 07:03 UTC

**Comment by canavan** [comment] 2016-04-14 18:51
I don't think ffmpeg is involved. youtube-dl stops before even trying to download the video:

    $ youtube-dl  https://youtu.be/RE9mswQbz6M &
    [1] 1864
    $ 
    
    [1]+  Stopped                 youtube-dl https://youtu.be/RE9mswQbz6M
    $ fg
    youtube-dl https://youtu.be/RE9mswQbz6M
    [youtube] RE9mswQbz6M: Downloading webpage
    [youtube] RE9mswQbz6M: Downloading video info webpage
    [youtube] RE9mswQbz6M: Extracting video information
    [youtube] RE9mswQbz6M: Downloading MPD manifest
    [...]

**Comment by yan12125** [comment] 2016-04-14 19:21
It is. Before the video starts downloading, youtube-dl checks whether ffmpeg/avconv exists or not, and prepend ```bestvideo+bestaudio``` to requested formats. (https://github.com/rg3/youtube-dl/blob/e0986e3/youtube_dl/YoutubeDL.py#L1359-L1361)

**Comment by canavan** [comment] 2016-04-14 20:02
In IRIX, the problem persists, even if ffmpeg is not in the path.

**Comment by yan12125** [comment] 2016-04-14 20:15
Could you run the command ```stty -tostop``` and try again?

**Comment by canavan** [comment] 2016-04-14 20:43
stty -tostop doesn't change the behaviour. Python version is 2.7.11. youtube-dl even stops if the video has previously been downloaded completely.

     $ stty -tostop
     $ /usr/nekoware/bin/python /usr/nekoware/bin/youtube-dl $YOUTUBEDLFLAGS  https://youtu.be/RE9mswQbz6M  &
    [1] 3183
     $

    [1]+  Stopped                 /usr/nekoware/bin/python /usr/nekoware/bin/youtube-dl $YOUTUBEDLFLAGS https://youtu.be/RE9mswQbz6M

**Comment by yan12125** [comment] 2016-04-14 21:28
Well seems the cause is quite different. From your 2013 logs youtube-dl is stopped when calling ```stty size```. This call occurs very early, even before input URL parsing. I guess when you redirect /dev/null to STDIN, ```stty size``` just fails as no terminal exists, so youtube-dl can go down the way. This approach can be considered as a workaround for IRIX.

**Comment by yan12125** [comment] 2016-10-22 05:15
Thanks to @johnhawkinson (#10996), this should be fixed in the next version. No more workarounds are necessary. Feel free to open a new issue if there's still something wrong.
