### ISSUE TITLE
HTTP Error 429

### ISSUE THREAD

**Issue by danhnguyenviet** [rg3/youtube-dl#9385] opened 2016-05-04 09:32 UTC
RROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError());

Please help me! Thanks!

**Comment by dstftw** [comment] 2016-05-04 14:10
Duplicate of #5138.

**Closed by dstftw** 2016-05-04 14:10 UTC

**Comment by 245123** [comment] 2019-11-26 11:35
Using --cookies solves the problem
