### ISSUE TITLE
BBC iPlayer subtitle format

### ISSUE THREAD

**Issue by jiangjiangflies** [rg3/youtube-dl#9084] opened 2016-04-05 02:08 UTC
How to get SRT subtitles from BBC iPlayer? 
youtube-dl --all-subs --skip-download  --convert-subs srt http://www.bbc.co.uk/iplayer/episode/p03nnns9/murdered-by-my-father
I can only get ttml format......

**Comment by dstftw** [comment] 2016-04-05 15:12
Remove `--skip-download`. Duplicate of #9073.

**Closed by dstftw** 2016-04-05 15:12 UTC

**Comment by jiangjiangflies** [comment] 2016-04-05 15:18
@dstftw  If I remove --skip-download, I will download the video，but I just want only the srt subtitle

**Comment by dstftw** [comment] 2016-04-05 15:19
It's not possible see linked issue.

**Comment by jiangjiangflies** [comment] 2016-04-05 15:25
Sorry, I don't get it. Could you give me a command to just download the SRT subtitle  of this program? Thank you very much!!! http://www.bbc.co.uk/iplayer/episode/p03nnns9/murdered-by-my-father

**Comment by dstftw** [comment] 2016-04-05 15:28
**It's not possible** to download srt because **there is no srt** provided by BBC. You can only download ttml and convert to srt but currently only with downloading the video itself.

**Comment by jiangjiangflies** [comment] 2016-04-05 15:30
Thank you very much!
