### ISSUE TITLE
progress bar using php in youtube-dl

### ISSUE THREAD

**Issue by badershs** [rg3/youtube-dl#6348] opened 2015-07-24 09:27 UTC
is there is any way to get the progress bar for my commend line to php or not ?

**Comment by yan12125** [comment] 2015-07-24 12:31
What are the expected results? [Please provide more details](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient).

**Comment by badershs** [comment] 2015-07-24 13:45
what i need is to connect my progress bar html to my youtube-dl result which comes from php 
[download]   0.4% of 231.51KiB at  6.10KiB/s ETA 00:30
[download]   1.1% of 231.51KiB at 27.07KiB/s ETA 00:10
[download]   4.0% of 231.51KiB at 19.24KiB/s ETA 00:04
[download]   6.5% of 231.51KiB at 75.06KiB/s ETA 00:03
[download]  13.4% of 231.51KiB at 98.22KiB/s ETA 00:03
[download]  28.7% of 231.51KiB at 81.40KiB/s ETA 00:02
[download]  61.7% of 231.51KiB at 91.56KiB/s ETA 00:01
[download]  86.2% of 231.51KiB at 82.96KiB/s ETA 00:00
[download] 100.0% of 231.51KiB at 73.21KiB/s ETA 00:00

to progress bar

**Comment by jaimeMF** [comment] 2015-07-24 13:47
You have to parse the output yourself, we don't offer (yet) a interface for that. Closing as a duplicate of #152.

**Closed by jaimeMF** 2015-07-24 13:47 UTC
