### ISSUE TITLE
--retries does not retry on "ERROR: content too short"

### ISSUE THREAD

**Issue by joshtriplett** [rg3/youtube-dl#6043] opened 2015-06-21 17:43 UTC
The documentation for --retries says that the default is 10.  However, I sometimes get errors of the form "ERROR: content too short", and those cause youtube-dl to stop rather than retrying.  (Tends to happen more on long videos.)  Re-running youtube-dl completes the download, or at least gets further before stopping.

Ideally, youtube-dl should retry on that error, as many times as specified by --retries, before giving up.

**Comment by jaimeMF** [comment] 2015-06-21 17:52
Duplicate of #809.

**Closed by jaimeMF** 2015-06-21 17:52 UTC

**Comment by joshtriplett** [comment] 2015-06-21 18:40
Sorry; I looked through open issues, but missed that one.  Thanks.

**Comment by jaimeMF** [comment] 2015-06-21 19:04
Note that sometimes other formats can be downloaded (use `-F` to get a list of them).

**Comment by joshtriplett** [comment] 2015-06-21 19:10
I haven't encountered any videos that permanently give that error, only videos that sometimes give that error while downloading, and then get further or finish on retry.
