### ISSUE TITLE
[ZDF] Unsupported URL

### ISSUE THREAD

**Issue by stepshal** [rg3/youtube-dl#10483] opened 2016-08-28 17:19 UTC
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.28**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other
  
  http://www.zdf.de/ZDF/zdfportal/programdata/3c6207e5-5373-4524-870d-7e7c80b6e84f/0e86a9cf-c77c-42dd-af00-78738769a737

**Comment by yan12125** [comment] 2016-09-03 09:29
In Firefox it says: ```Kein Beitrag zur ID gefunden```. Does this video work for you?

**Comment by stepshal** [comment] 2016-09-03 11:41
@yan12125 No.

**Comment by yan12125** [comment] 2016-09-03 15:41
Feel free to leave comments if you find a working video that makes youtube-dl fail. I'll reopen the issue.

**Comment by stepshal** [comment] 2016-09-07 10:41
@yan12125  Unsupported url: http://www.zdf.de/ZDF/zdfportal/programdata/3c6207e5-5373-4524-870d-7e7c80b6e84f/0e86a9cf-c77c-42dd-af00-78738769a737

**Comment by pank** [comment] 2016-11-04 13:25
Another example is https://www.zdf.de/comedy/neo-magazin-mit-jan-boehmermann/neo-magazin-royale-mit-jan-boehmermann-clip-1-100.html

**Comment by utack** [comment] 2016-11-06 02:00
Duplicate of #11055 ?

**Comment by isotopp** [comment] 2016-11-15 20:32
Duplicate of #11055 

Also, URLs at ZDF expire after 7 days. That's why people want to use youtube-dl on them in the first place.

**Comment by dstftw** [comment] 2016-11-29 14:54
Duplicate of #11055.

**Closed by dstftw** 2016-11-29 14:54 UTC
Labels: bug
