### ISSUE TITLE
[Soundcloud] extractor broken - 401 Unauthorized

### ISSUE THREAD

**Issue by steebchen** [rg3/youtube-dl#6931] opened 2015-09-23 14:05 UTC
When I run youtube-dl like that:

     youtube-dl -f best https://soundcloud.com/samblackmore/above-beyond-love-is-not --verbose
then this appears:
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-f', u'best', u'https://soundcloud.com/samblackmore/above-beyond-love-is-not', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.22
[debug] Python version 2.7.6 - Linux-3.16.0-38-generic-x86_64-with-LinuxMint-17.2-rafaela
[debug] exe versions: ffmpeg N-75403-g3a8e447, ffprobe N-75403-g3a8e447
[debug] Proxy map: {}
[soundcloud] samblackmore/above-beyond-love-is-not: Resolving id
[soundcloud] samblackmore/above-beyond-love-is-not: Downloading info JSON
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 326, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1865, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

```
This happens with all Soundcloud links I tried.
I also updated to the latest version using `youtube-dl -U`.

**Comment by dstftw** [comment] 2015-09-23 14:06
Duplicate of #6930.

**Closed by dstftw** 2015-09-23 14:06 UTC
