### ISSUE TITLE
Unable to extract video for any Dailymotion link

### ISSUE THREAD

**Issue by tammytang** [rg3/youtube-dl#6329] opened 2015-07-22 10:11 UTC
Failure begins today, I think maybe Dailymotion changed something.

youtube-dl -v http://www.dailymotion.com/video/x2yuh7d_all
-goals-and-highlights-fc-barcelona-2-1-los-angeles-galaxy-international-champion
s-cup-21-07-2015_sport
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.dailymotion.com/video/x2yuh7d_al
l-goals-and-highlights-fc-barcelona-2-1-los-angeles-galaxy-international-champio
ns-cup-21-07-2015_sport']
[debug] Encodings: locale cp950, fs mbcs, out cp950, pref cp950
[debug] youtube-dl version 2015.07.21
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[dailymotion] x2yuh7d: Downloading webpage
[dailymotion] x2yuh7d: Extracting information
[dailymotion] x2yuh7d: Downloading embed page
ERROR: Unable to extract video info; please report this issue on https://yt-dl.o
rg/bug . Make sure you are using the latest version; type  youtube-dl -U  to upd
ate. Be sure to call youtube-dl with the --verbose flag and include its complete
 output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 656, in extract_info
  File "youtube_dl\extractor\common.pyo", line 275, in extract
  File "youtube_dl\extractor\dailymotion.pyo", line 120, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 557, in _search_regex
RegexNotFoundError: Unable to extract video info; please report this issue on ht
tps://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-
dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include
 its complete output.

**Comment by dstftw** [comment] 2015-07-22 16:07
Duplicate of #6151.

**Closed by dstftw** 2015-07-22 16:07 UTC
