### ISSUE TITLE
Canal-u issue

### ISSUE THREAD

**Issue by Animis09** [rg3/youtube-dl#10271] opened 2016-08-09 12:31 UTC
youtube-dl https://www.canal-u.tv/video/mnhn/entretien_avec_yves_coppens_partie_1_4.23841 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.canal-u.tv/video/mnhn/entretien_avec_yves_coppens_partie_1_4.23841', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.07
[debug] Proxy map: {}
[generic] entretien_avec_yves_coppens_partie_1_4: Requesting header
WARNING: Falling back on generic information extractor.
[generic] entretien_avec_yves_coppens_partie_1_4: Downloading webpage
[generic] entretien_avec_yves_coppens_partie_1_4: Extracting information
WARNING: unable to extract JSON-LD; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[generic] entretien_avec_yves_coppens_partie_1_4.23841: Downloading SMIL file
[debug] Invoking downloader on u'rtmpt://fms2.cerimes.fr:80/vod/'
[download] Destination: Entretien avec Yves Coppens. Partie 1_4-entretien_avec_yves_coppens_partie_1_4.23841.flv
[debug] rtmpdump command line: rtmpdump --verbose -r rtmpt://fms2.cerimes.fr:80/vod/ -o 'Entretien avec Yves Coppens. Partie 1_4-entretien_avec_yves_coppens_partie_1_4.23841.flv.part' --playpath media/canalu/videos/mnhn/entretien.avec.yves.coppens.partie.1.4_23841/coppens_01_decouverte_vallee_omo_hd_v3.mp4 --resume --skip 1
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 1
[rtmpdump] DEBUG: Parsed host    : fms2.cerimes.fr
[rtmpdump] DEBUG: Parsed app     : vod
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPT
[rtmpdump] DEBUG: Hostname : fms2.cerimes.fr
[rtmpdump] DEBUG: Port     : 80
[rtmpdump] DEBUG: Playpath : media/canalu/videos/mnhn/entretien.avec.yves.coppens.partie.1.4_23841/coppens_01_decouverte_vallee_omo_hd_v3.mp4
[rtmpdump] DEBUG: tcUrl    : rtmpt://fms2.cerimes.fr:80/vod
[rtmpdump] DEBUG: app      : vod
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Setting buffer time to: 36000000ms
[rtmpdump] Connecting ...
[rtmpdump] DEBUG: RTMP_Connect1, ... connected, handshaking
[rtmpdump] DEBUG: HandShake: Type Answer   : 03
[rtmpdump] DEBUG: HandShake: Server Uptime : 1245336073
[rtmpdump] DEBUG: HandShake: FMS Version   : 4.5.5.1
[rtmpdump] DEBUG: HandShake: Handshaking finished....
[rtmpdump] DEBUG: RTMP_Connect1, handshaked
[rtmpdump] DEBUG: Invoking connect
[rtmpdump] INFO: Connected...
[rtmpdump] DEBUG: HandleServerBW: server BW = 2500000
[rtmpdump] DEBUG: HandleClientBW: client BW = 2500000 2
[rtmpdump] DEBUG: HandleChangeChunkSize, received: chunk size change to 4096
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 242 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:             fmsVer, STRING:  FMS/4,5,5,4013>
[rtmpdump] DEBUG: Property: <Name:       capabilities, NUMBER:  255.00>
[rtmpdump] DEBUG: Property: <Name:               mode, NUMBER:  1.00>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:  status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:  NetConnection.Connect.Success>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:  Connection succeeded.>
[rtmpdump] DEBUG: Property: <Name:     objectEncoding, NUMBER:  0.00>
[rtmpdump] DEBUG: Property: <Name:               data, OBJECT>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:            version, STRING:  4,5,5,4013>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_result>
[rtmpdump] DEBUG: HandleInvoke, received result for method call <connect>
[rtmpdump] DEBUG: sending ctrl. type: 0x0003
[rtmpdump] DEBUG: Invoking createStream
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 21 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onBWDone>
[rtmpdump] DEBUG: Invoking _checkbw
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 29 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_result>
[rtmpdump] DEBUG: HandleInvoke, received result for method call <createStream>
[rtmpdump] DEBUG: SendPlay, seekTime=0, stopTime=0, sending play: media/canalu/videos/mnhn/entretien.avec.yves.coppens.partie.1.4_23841/coppens_01_decouverte_vallee_omo_hd_v3.mp4
[rtmpdump] DEBUG: Invoking play
[rtmpdump] DEBUG: sending ctrl. type: 0x0003
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 16419 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: HandleChangeChunkSize, received: chunk size change to 4096
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 385 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:  error>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:  NetStream.Play.StreamNotFound>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:  Failed to play media/canalu/videos/mnhn/entretien.avec.yves.coppens.partie.1.4_23841/coppens_01_decouverte_vallee_omo_hd_v3.mp4; stream not found.>
[rtmpdump] DEBUG: Property: <Name:            details, STRING:  media/canalu/videos/mnhn/entretien.avec.yves.coppens.partie.1.4_23841/coppens_01_decouverte_vallee_omo_hd_v3.mp4>
[rtmpdump] DEBUG: Property: <Name:           clientid, STRING:  qAAPwwMA>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onStatus>
[rtmpdump] DEBUG: HandleInvoke, onStatus: NetStream.Play.StreamNotFound
[rtmpdump] ERROR: Closing connection: NetStream.Play.StreamNotFound
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 0 bytes
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 1
[rtmpdump] DEBUG: Parsed host    : fms2.cerimes.fr
[rtmpdump] DEBUG: Parsed app     : vod
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPT
[rtmpdump] DEBUG: Hostname : fms2.cerimes.fr
[rtmpdump] DEBUG: Port     : 80
[rtmpdump] DEBUG: Playpath : media/canalu/videos/mnhn/entretien.avec.yves.coppens.partie.1.4_23841/coppens_01_decouverte_vallee_omo_hd_v3.mp4
[rtmpdump] DEBUG: tcUrl    : rtmpt://fms2.cerimes.fr:80/vod
[rtmpdump] DEBUG: app      : vod
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.

ERROR: rtmpdump exited with code 1
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 422, in main
    _real_main(argv)
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 412, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1775, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 693, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 739, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1421, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1683, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1625, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 350, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/rtmp.py", line 202, in real_download
    self.report_error('rtmpdump exited with code %d' % retval)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 161, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 556, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 518, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

Thank you for your help

**Comment by yan12125** [comment] 2016-08-13 08:44
Duplicate of #9491. Canal-u is not supported yet.

**Closed by yan12125** 2016-08-13 08:44 UTC
