### ISSUE TITLE
creates 721 fragment files ... HTTP Error 404

### ISSUE THREAD

**Issue by scottstensland** [rg3/youtube-dl#8750] opened 2016-03-04 04:39 UTC
I have ran this same URL many time each run fails with same error
...  this is not a bad bandwidth timeout issue

offending URL    https://www.youtube.com/watch?v=RTwddp2uIu0  
which renders fine in browsers

Other URLs  download just fine ... this error is ONLY for this URL

```youtube-dl -v https://www.youtube.com/watch?v=RTwddp2uIu0  
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=RTwddp2uIu0']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.01
[debug] Python version 2.7.11+ - Linux-4.4.0-9-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg N-78848-gf114839, ffprobe N-78848-gf114839, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] RTwddp2uIu0: Downloading webpage
[youtube] RTwddp2uIu0: Downloading video info webpage
[youtube] RTwddp2uIu0: Extracting video information
[youtube] RTwddp2uIu0: Downloading MPD manifest
[youtube] RTwddp2uIu0: Downloading MPD manifest
[debug] Invoking downloader on u'https://r6---sn-8xgp1vo-xfge7.googlevideo.com/videoplayback/id/453c1d769dae22ed/itag/136/source/yt_otf/requiressl/yes/mm/31/mn/sn-8xgp1vo-xfge7/pl/25/mv/m/ms/au/ratebypass/yes/mime/video%2Fmp4/otfp/1/otf/1/lmt/1451728107988317/fexp/9405185,9413138,9416126,9416985,9420452,9422596,9423661,9423662,9424823,9424914,9425956,9426601,9426903,9427325,9427902,9428996,9429733/upn/nJyVFbRy_G4/signature/6A45063CD2CA6A70900B135EFC442B023E0F2EAC.5F719BDAD0E8E4E1D3F75E8BBD6850EB43D00632/key/dg_yt0/sver/3/mt/1457059742/ip/74.101.198.245/ipbits/0/expire/1457081442/sparams/ip,ipbits,expire,id,itag,source,requiressl,mm,mn,pl,mv,ms,ratebypass,mime,otfp,otf,lmt/'
[dashsegments] Total fragments: 721
[download] Destination: Making Robots-RTwddp2uIu0.f136.mp4
[download]  48.7% of ~339.28MiB at 444.39KiB/s ETA 08:08ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1618, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1566, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 343, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/dash.py", line 52, in real_download
    append_url_to_file(segment_url, segment_filename)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/dash.py", line 40, in append_url_to_file
    success = ctx['dl'].download(target_filename, {'url': combine_url(base_url, target_url)})
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 343, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1905, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

```

During download it creates hundreds of such fragment files : 

`Making Robots-RTwddp2uIu0.f136.mp4.part-Init
Making Robots-RTwddp2uIu0.f136.mp4.part-Seg0
Making Robots-RTwddp2uIu0.f136.mp4.part-Seg1
Making Robots-RTwddp2uIu0.f136.mp4.part-Seg2
...
Making Robots-RTwddp2uIu0.f136.mp4.part-Seg10
Making Robots-RTwddp2uIu0.f136.mp4.part-Seg11
Making Robots-RTwddp2uIu0.f136.mp4.part-Seg12
Making Robots-RTwddp2uIu0.f136.mp4.part-Seg13
Making Robots-RTwddp2uIu0.f136.mp4.part-Seg14
Making Robots-RTwddp2uIu0.f136.mp4.part-Seg15
Making Robots-RTwddp2uIu0.f136.mp4.part-Seg16
Making Robots-RTwddp2uIu0.f136.mp4.part-Seg17
Making Robots-RTwddp2uIu0.f136.mp4.part-Seg18
Making Robots-RTwddp2uIu0.f136.mp4.part-Seg19
Making Robots-RTwddp2uIu0.f136.mp4.part-Seg20
`

**Comment by dstftw** [comment] 2016-03-04 05:02
Duplicate of #8750.

**Closed by dstftw** 2016-03-04 05:02 UTC
