### ISSUE TITLE
support for YouTube 4K Live stream?

### ISSUE THREAD

**Issue by beatsmaster** [rg3/youtube-dl#11346] opened 2016-12-02 20:55 UTC
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.01**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

---

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
E:\tools\tools>youtube-dl -v -F G0rBvROOLcs
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '-F', 'G0rBvROOLcs']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.12.01
[debug] Python version 3.4.4 - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg N-78268-g0ab25da, ffprobe N-78268-g0ab25da, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] G0rBvROOLcs: Downloading webpage
[youtube] G0rBvROOLcs: Downloading video info webpage
[youtube] G0rBvROOLcs: Extracting video information
[youtube] G0rBvROOLcs: Downloading formats manifest
[youtube] G0rBvROOLcs: Downloading MPD manifest
[info] Available formats for G0rBvROOLcs:
format code  extension  resolution note
91           mp4        144p       HLS , h264, aac  @ 48k
92           mp4        240p       HLS , h264, aac  @ 48k
93           mp4        360p       HLS , h264, aac  @128k
94           mp4        480p       HLS , h264, aac  @128k
95           mp4        720p       HLS , h264, aac  @256k
96           mp4        1080p      HLS , h264, aac  @256k (best)
...
<end of log>
```

---
- Single video: https://www.youtube.com/watch?v=G0rBvROOLcs
---

### Description of your *question*, suggested solution and other information

YouTube added 4K as an option for live streaming. This DASH live stream is not recognized by youtube-dl > only the HLS live streams are displayed; Is it possible to record the 4K live stream?

The sample video is a continuous 4K live stream example.

Recording Youtube 4K videos works flawless, but live streams not yet.

un saludo, beatsmaster

**Comment by dstftw** [comment] 2016-12-02 21:11
Duplicate of #10787.

**Closed by dstftw** 2016-12-02 21:11 UTC
