### ISSUE TITLE
ExtractorError -- Could not download DASH manifest

### ISSUE THREAD

**Issue by mwmanion** [rg3/youtube-dl#6252] opened 2015-07-16 22:58 UTC
OS:

Windows 8.1

Command: 

youtube-dl.exe --batch-file videoIds-184.txt --keep-video --extract-audio --audio-format mp3 --download-archive archive.txt --xattrs --prefer-ffmpeg --ffmpeg-location "C:\Program Files\ffmpeg-20150702-git-03b2b40-win64-static\bin\ffmpeg.exe" --embed-thumbnail --add-metadata --write-thumbnail --ignore-errors

Relevant part of output:

[youtube] 1mQtTWc0KTs: Downloading webpage
[youtube] 1mQtTWc0KTs: Downloading video info webpage
[youtube] 1mQtTWc0KTs: Extracting video information
[youtube] 1mQtTWc0KTs: Downloading js player en_US-vflaxmkJQ
[youtube] 1mQtTWc0KTs: Downloading DASH manifest
[youtube] 1mQtTWc0KTs: Downloading js player en_US-vflaxmkJQ
[youtube] 1mQtTWc0KTs: Downloading DASH manifest
WARNING: [youtube] 1mQtTWc0KTs: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[youtube] 1mQtTWc0KTs: Downloading thumbnail ...
[youtube] 1mQtTWc0KTs: Writing thumbnail to: Fez catches his parents having sex, Fez talks about sex, Fez is in a deep depression-1mQtTWc0KTs.jpg
[download] Destination: Fez catches his parents having sex, Fez talks about sex, Fez is in a deep depression-1mQtTWc0KTs.f137.mp4
[download] 100% of 31.72MiB in 00:23
[download] Destination: Fez catches his parents having sex, Fez talks about sex, Fez is in a deep depression-1mQtTWc0KTs.f141.m4a
[download] 100% of 35.58MiB in 00:20
[ffmpeg] Merging formats into "Fez catches his parents having sex, Fez talks about sex, Fez is in a deep depression-1mQtTWc0KTs.mp4"
[ffmpeg] Adding metadata to 'Fez catches his parents having sex, Fez talks about sex, Fez is in a deep depression-1mQtTWc0KTs.mp4'
[ffmpeg] Destination: Fez catches his parents having sex, Fez talks about sex, Fez is in a deep depression-1mQtTWc0KTs.mp3
[metadata] Writing metadata to file's xattrs
[ffmpeg] Adding thumbnail to "Fez catches his parents having sex, Fez talks about sex, Fez is in a deep depression-1mQtTWc0KTs.mp3"

Summary:

The video plays fine in YouTube. Both the thumbnail image and the MP3 downloaded OK, as you can see above.  Not sure what happened with the DASH, but the problem is reproduceable every time.  It only had this error on this video, not on any of the other 183 videos in the batch.  I'm only reporting it as a bug because the program asked me to :)  In fact, I just created my GitHub account 5 minutes ago so I could report this. You devs can run it with --verbose if you want.  I suspect this is a dup of some other bug but I'm never coming back here so I don't care.

**Comment by dstftw** [comment] 2015-07-17 03:24
Duplicate of #5118.

**Closed by dstftw** 2015-07-17 03:24 UTC
