### ISSUE TITLE
XHamster Unable to extract title;

### ISSUE THREAD

**Issue by timxd** [rg3/youtube-dl#10458] opened 2016-08-28 09:08 UTC
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bu
g . Make sure you are using the latest version; see  https://yt-dl.org/update  o
n how to update. Be sure to call youtube-dl with the --verbose flag and include
its complete output.

Traceback (most recent call last):
  File "c:\code\down_video.py", line 45, in <module>
    info_dict = ydl.extract_info(url, download=True)
  File "C:\Python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 706, in ext
ract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 565, in rep
ort_error
    self.trouble(error_message, tb)
  File "C:\Python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 535, in tro
uble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Unable to extract title; please report th
is issue on https://yt-dl.org/bug . Make sure you are using the latest version;
see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with
 the --verbose flag and include its complete output.

**Comment by yan12125** [comment] 2016-08-28 09:19
Possibly a duplicate of #9152. Could you add ```--dump-pages``` and upload all ```*.dump``` files?

**Comment by yan12125** [comment] 2016-09-11 11:33
Closing as no response for a long time.

**Closed by yan12125** 2016-09-11 11:33 UTC
Labels: clarification-needed
