### ISSUE TITLE
Error Downloading: ExtractorError - Could not download DASH Manifest

### ISSUE THREAD

**Issue by bowser8302** [rg3/youtube-dl#6550] opened 2015-08-13 15:28 UTC
Situation: 

Attempting to download from YouTube. Playlists (public, private, and unlisted) and videos all fail. Last successful run of youtube-dl occurred at 4:00PM (CST) on 8/12/15. Install was through apt-get. After failure, youtube-dl was removed through apt-get and re-installed using manual method. Ran...

youtube-dl -U

...but call still failed.

---

Verbose Output of Command

root@linux:/scripts/tmp# youtube-dl --verbose https://www.youtube.com/watch?v=l0_LY5bOTOE&index=1&list=[my_video_or_playlist]
[1] 21372
[2] 21373
root@linux:/scripts/tmp# [debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=l0_LY5bOTOE']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.09
[debug] Python version 2.7.10 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.8
[debug] exe versions: avconv 11.4-6, avprobe 11.4-6, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] l0_LY5bOTOE: Downloading webpage
[youtube] l0_LY5bOTOE: Downloading video info webpage
[youtube] l0_LY5bOTOE: Extracting video information
[youtube] {43} signature length 40.42, html5 player new
[youtube] {18} signature length 40.42, html5 player new
[youtube] {5} signature length 40.42, html5 player new
[youtube] {36} signature length 40.42, html5 player new
[youtube] {17} signature length 40.42, html5 player new
[youtube] {133} signature length 40.42, html5 player new
[youtube] {242} signature length 40.42, html5 player new
[youtube] {160} signature length 40.42, html5 player new
[youtube] {278} signature length 40.42, html5 player new
[youtube] {140} signature length 40.42, html5 player new
[youtube] {171} signature length 40.42, html5 player new
[youtube] {249} signature length 40.42, html5 player new
[youtube] {250} signature length 40.42, html5 player new
[youtube] {251} signature length 40.42, html5 player new
[youtube] l0_LY5bOTOE: Downloading DASH manifest
WARNING: [youtube] l0_LY5bOTOE: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on u'https://r6---sn-vgqsenez.googlevideo.com/videoplayback?mv=m&mt=1439478612&ms=au&id=o-AAXYxI_YHiDelnP84o_fv69J1Sw-7g0ytCY3clt-h7-z&expire=1439500300&mime=video%2Fmp4&ip=50.129.126.17&requiressl=yes&pl=16&mn=sn-vgqsenez&mm=31&source=youtube&itag=133&clen=6384250&fexp=9408372%2C9408710%2C9409095%2C9412843%2C9415365%2C9415485%2C9416023%2C9416126%2C9416729%2C9417118%2C9417581%2C9417632%2C9417762%2C9418153%2C9418203%2C9418677&key=yt5&upn=H7VxAfnV-Xk&ipbits=0&nh=IgpwcjAzLm9yZDEyKgkxMjcuMC4wLjE&sver=3&initcwndbps=867500&dur=217.733&gir=yes&lmt=1429592654551702&sparams=clen%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&keepalive=yes&signature=80406C53050893B33FCEB95A58AFC64D832F3D85.2B27BA236FD24A209224598E49BD1CD19F95E4D9&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1579, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1527, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 60, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1860, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden

[1]-  Exit 1                  youtube-dl --verbose https://www.youtube.com/watch?v=l0_LY5bOTOE
[2]+  Done                    index=1

**Comment by dstftw** [comment] 2015-08-13 15:31
Duplicate of #6451. Remove cache: `--rm-cache-dir`.

**Closed by dstftw** 2015-08-13 15:31 UTC
