### ISSUE TITLE
signature decrypt problem with new JS files

### ISSUE THREAD

**Issue by badproject** [rg3/youtube-dl#10922] opened 2016-10-14 12:11 UTC
Cannot decrypt signature with new JS file.

JS File: https://s.ytimg.com/yts/jsbin/player-tr_TR-vflUmuZyU/base.js
Encrypted Signature: 91913929355512D9A25CA5AB9CE3D8EF1C327D3835.601474C479A9A543C6D97B055C5D96BA577B10EB0EB
Decrypted Signature: 9019F013759CB9CA9FA271928690E01392498D3C.0A7F155816EA8373CF76A16863B49A2D558D9968

_TESTS variable for /test/test_youtube_signature.py
`_TESTS = [
    (
        'https://s.ytimg.com/yts/jsbin/player-tr_TR-vflUmuZyU/base.js',
        'js',
        '91913929355512D9A25CA5AB9CE3D8EF1C327D3835.601474C479A9A543C6D97B055C5D96BA577B10EB0EB',
        '9019F013759CB9CA9FA271928690E01392498D3C.0A7F155816EA8373CF76A16863B49A2D558D9968',
    )
]`

python youtube-dl/test/test_youtube_signature.py
E
======================================================================
ERROR: test_signature_js_vflUmuZyU (__main__.TestSignature)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "youtube-dl/test/test_youtube_signature.py", line 63, in test_func
    got_sig = func(src_sig)
  File "/home/tanerk/public_html/youtube/youtube-dl/youtube_dl/extractor/youtube.py", line 984, in <lambda>
    return lambda s: initial_function([s])
  File "/home/tanerk/public_html/youtube/youtube-dl/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/home/tanerk/public_html/youtube/youtube-dl/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/home/tanerk/public_html/youtube/youtube-dl/youtube_dl/jsinterp.py", line 174, in interpret_expression
    return obj[member](argvals)
KeyError: u'Qv'

----------------------------------------------------------------------
Ran 1 test in 0.497s

FAILED (errors=1)

**Comment by yan12125** [comment] 2016-10-14 12:13
Thanks. That's a duplicate of #10921

**Closed by yan12125** 2016-10-14 12:13 UTC
