### ISSUE TITLE
Keep Retrying Connection Failures

### ISSUE THREAD

**Issue by BullyWiiPlaza** [rg3/youtube-dl#4829] opened 2015-01-31 12:53 UTC
While downloading videos from YouTube I would like the program to resume when it fails to connect to the website either due to a random error (EOF) or a network change (switching WiFi connection or proxy). Don't make the program abort then and just keep trying until it can continue to download.

This is useful to reliably download everything over the night or something instead of coming back and seeing that it stopped when it shouldn't. Note that it won't be stuck in an endless loop since it's never a deterministic error. The network change issue can be reproduced easily however the EOF one is very random.

Thank you

**Comment by dstftw** [comment] 2016-06-12 04:44
Duplicate of #4240.

**Closed by dstftw** 2016-06-12 04:44 UTC
