### ISSUE TITLE
Could not download DASH manifest: HTTP Error 403

### ISSUE THREAD

**Issue by radjah** [rg3/youtube-dl#6166] opened 2015-07-07 04:19 UTC
URL http://www.youtube.com/watch?v=uYs1pJDhB94
Log
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.youtube.com/watch?v=uYs1pJDhB94', u'--verbose', u'-u', u'PRIVATE']
Type account password and press [Return]:
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.04
[debug] Python version 2.7.3 - Linux-3.4.79-sun7i-armv7l-with-debian-7.8
[debug] exe versions: ffmpeg 1.2.12, ffprobe 1.2.12
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Logging in
[youtube] uYs1pJDhB94: Downloading webpage
[youtube] uYs1pJDhB94: Downloading video info webpage
[youtube] uYs1pJDhB94: Extracting video information
[youtube] {22} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {43} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {18} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {5} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {36} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {17} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {299} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {298} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {135} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {244} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {134} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {243} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {133} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {242} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {160} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {278} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {140} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {171} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] uYs1pJDhB94: Downloading DASH manifest
[youtube] uYs1pJDhB94: Downloading player https://s.ytimg.com/yts/jsbin/html5player-en_US-vflzomeEU/html5player.js
[youtube] uYs1pJDhB94: Downloading DASH manifest
WARNING: [youtube] uYs1pJDhB94: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://
```
Version: 2015.07.04

**Comment by yan12125** [comment] 2015-07-07 06:07
Duplicate of #5118

**Closed by yan12125** 2015-07-07 06:07 UTC
