### ISSUE TITLE
TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by ltGuillaume** [rg3/youtube-dl#4141] opened 2014-11-09 13:37 UTC
I am unable to download all videos from this playlist: https://www.youtube.com/playlist?list=ELuUde4SmIoiM

Using latest youtube-dl (2014.11.04) and downloaded rtmpdump.

Error message for single video from playlist (Windows 8.1):
>[debug] System config: []
>[debug] User config: []
>[debug] Command-line args: ['https://www.youtube.com/watch?v=UHU1yLbD6qM', '--verbose', '-F']
>[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
>[debug] youtube-dl version 2014.10.25
>[debug] Python version 2.7.8 - Windows-8-6.2.9200
>[debug] Proxy map: {}
>[youtube] Confirming age
>[youtube] UHU1yLbD6qM: Downloading webpage
>[youtube] UHU1yLbD6qM: Downloading video info webpage
>[youtube] Confirming age
>ERROR: Unable to extract sts; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
>Traceback (most recent call last):
>  File "youtube_dl\YoutubeDL.pyo", line 528, in extract_info
>  File "youtube_dl\extractor\common.pyo", line 197, in extract
>  File "youtube_dl\extractor\youtube.pyo", line 690, in _real_extract
>  File "youtube_dl\extractor\common.pyo", line 428, in _search_regex
>RegexNotFoundError: Unable to extract sts; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

Error message for single video from playlist (Windows XP):
>[youtube] Confirming age
>[youtube] UHU1yLbD6qM: Downloading webpage
>[youtube] UHU1yLbD6qM: Downloading video info webpage
>[youtube] UHU1yLbD6qM: Refetching age-gated info webpage
>[youtube] UHU1yLbD6qM: Extracting video information
>[youtube] RTMP download detected
>Traceback (most recent call last):
>  File "__main__.py", line 18, in <module>
>  File "youtube_dl\__init__.pyo", line 351, in main
>  File "youtube_dl\__init__.pyo", line 341, in _real_main
>  File "youtube_dl\YoutubeDL.pyo", line 1085, in download
>  File "youtube_dl\YoutubeDL.pyo", line 536, in extract_info
>  File "youtube_dl\extractor\common.pyo", line 199, in extract
>  File "youtube_dl\extractor\youtube.pyo", line 956, in _real_extract
>TypeError: 'NoneType' object has no attribute '__getitem__'
>'list' is not recognized as an internal or external command, operable program or batch file.
>'index' is not recognized as an internal or external command, operable program or batch file.

Error message for playlist:
>[debug] System config: []
>[debug] User config: []
>[debug] Command-line args: ['https://www.youtube.com/playlist?list=ELuUde4SmIoiM -F', '--verbose']
>[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
>[debug] youtube-dl version 2014.11.04
>[debug] Python version 2.7.8 - Windows-XP-5.1.2600-SP3
>[debug] exe versions: ffmpeg N-59852-, rtmpdump 2.3
>[debug] Proxy map: {}
>[youtube:playlist] ELuUde4SmIoiM-F: Downloading webpage
>ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
>Traceback (most recent call last):
>  File "youtube_dl\YoutubeDL.pyo", line 536, in extract_info
>  File "youtube_dl\extractor\common.pyo", line 199, in extract
>  File "youtube_dl\extractor\youtube.pyo", line 1183, in _real_extract
>  File "youtube_dl\extractor\common.pyo", line 446, in _html_search_regex
>  File "youtube_dl\extractor\common.pyo", line 436, in _search_regex
>RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug. Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by dstftw** [comment] 2016-06-12 17:01
Duplicate of #343.

**Closed by dstftw** 2016-06-12 17:01 UTC
