### ISSUE TITLE
Openload dosent work again

### ISSUE THREAD

**Issue by apolo188** [rg3/youtube-dl#11064] opened 2016-10-29 17:52 UTC
Hi ,openload shows a video with doves

**Comment by Hrxn** [comment] 2016-10-29 17:57
Duplicate of #10408

**Comment by yan12125** [comment] 2016-10-29 17:59
@Hrxn is right. It's just fixed in f02700a1fa83205840fefe9ae86ccfe13a8cf748 (thanks to @TwelveCharzz). Please wait for the next version.

**Closed by yan12125** 2016-10-29 17:59 UTC
