### ISSUE TITLE
Add parameter for SPECIFYING config 

### ISSUE THREAD

**Issue by Forket** [rg3/youtube-dl#9379] opened 2016-05-03 12:08 UTC
Current parameters set has "--ignore-config". But it would be good to have another one, something like "---config-file".
With this I can create different configs for needed cases. For example I have some config for MUSIC and some config for VIDEO.
Or have different config set for any some services I use. 
With such scenario I could put much less parameters on **youtube-dl** run

**Comment by dstftw** [comment] 2016-05-03 12:12
Duplicate of #6745 and #3101. WIP PR #8901.

**Closed by dstftw** 2016-05-03 12:12 UTC
