### ISSUE TITLE
Error in extractor/youtube.py line 1057, in _decrypt_signature

### ISSUE THREAD

**Issue by piotr-yuxuan** [rg3/youtube-dl#11913] opened 2017-01-31 13:14 UTC
This issue is likely to be a duplicate of issues https://github.com/rg3/youtube-dl/issues/11910, https://github.com/rg3/youtube-dl/issues/11909 and https://github.com/rg3/youtube-dl/issues/11906. I open this one for the sake of completeness and because the piece of software you make is great so I hope you'll have enough test case :-)

## System settings

```
$ youtube-dl --version
2017.01.29
$ uname -a
Darwin [private] 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64
$ brew info youtube-dl
youtube-dl: stable 2017.01.29 (bottled), HEAD
Download YouTube videos from the command-line
https://rg3.github.io/youtube-dl/
/usr/local/Cellar/youtube-dl/2016.09.24 (10 files, 1.6M)
  Poured from bottle on 2016-09-25 at 11:51:14
/usr/local/Cellar/youtube-dl/2016.10.02 (11 files, 1.6M)
  Poured from bottle on 2016-10-02 at 21:37:47
/usr/local/Cellar/youtube-dl/2016.10.12 (11 files, 1.6M)
  Poured from bottle on 2016-10-13 at 10:44:35
/usr/local/Cellar/youtube-dl/2016.10.19 (11 files, 1.6M)
  Poured from bottle on 2016-10-20 at 20:31:45
/usr/local/Cellar/youtube-dl/2016.11.08.1 (11 files, 1.6M)
  Poured from bottle on 2016-11-10 at 13:58:31
/usr/local/Cellar/youtube-dl/2016.11.27 (11 files, 1.6M)
  Poured from bottle on 2016-11-30 at 11:02:36
/usr/local/Cellar/youtube-dl/2016.12.01 (11 files, 1.6M)
  Poured from bottle on 2016-12-02 at 15:40:36
/usr/local/Cellar/youtube-dl/2016.12.12 (11 files, 1.6M)
  Poured from bottle on 2016-12-14 at 11:11:59
/usr/local/Cellar/youtube-dl/2016.12.22 (11 files, 1.7M)
  Poured from bottle on 2016-12-28 at 12:04:52
/usr/local/Cellar/youtube-dl/2017.01.05 (11 files, 1.7M)
  Poured from bottle on 2017-01-05 at 12:05:57
/usr/local/Cellar/youtube-dl/2017.01.10 (11 files, 1.7M)
  Poured from bottle on 2017-01-12 at 10:35:48
/usr/local/Cellar/youtube-dl/2017.01.14 (11 files, 1.7M)
  Poured from bottle on 2017-01-14 at 12:56:04
/usr/local/Cellar/youtube-dl/2017.01.16 (11 files, 1.7M)
  Poured from bottle on 2017-01-18 at 17:37:54
/usr/local/Cellar/youtube-dl/2017.01.29 (11 files, 1.7M) *
  Poured from bottle on 2017-01-31 at 14:07:28
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/youtube-dl.rb
==> Dependencies
Optional: rtmpdump ✘
==> Options
--with-rtmpdump
	Build with rtmpdump support
--HEAD
	Install HEAD version
==> Caveats
To use post-processing options, `brew install ffmpeg` or `brew install libav`.

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completion has been installed to:
  /usr/local/share/zsh/site-functions
```

## Stacktrace

```
$ youtube-dl --verbose https://www.youtube.com/watch\?v\=Dst0iYsEyKI
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=Dst0iYsEyKI']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.01.29
[debug] Python version 2.7.13 - Darwin-16.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2
[debug] Proxy map: {}
[youtube] Dst0iYsEyKI: Downloading webpage
[youtube] Dst0iYsEyKI: Downloading video info webpage
[youtube] Dst0iYsEyKI: Extracting video information
[youtube] {43} signature length 42.43, html5 player en_US-vflV3n15C
[youtube] Dst0iYsEyKI: Downloading player /yts/jsbin/player-en_US-vflV3n15C/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1057, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 971, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 436, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 416, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 421, in open
    protocol = req.get_type()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 283, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: /yts/jsbin/player-en_US-vflV3n15C/base.js
 (caused by ValueError(u'unknown url type: /yts/jsbin/player-en_US-vflV3n15C/base.js',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1057, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 971, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 436, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 416, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 421, in open
    protocol = req.get_type()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 283, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: /yts/jsbin/player-en_US-vflV3n15C/base.js
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 369, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1646, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1067, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1057, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 971, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 436, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 416, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 421, in open
    protocol = req.get_type()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 283, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: /yts/jsbin/player-en_US-vflV3n15C/base.js
 (caused by ValueError(u'unknown url type: /yts/jsbin/player-en_US-vflV3n15C/base.js',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by jaydenkieran** [comment] 2017-01-31 13:24
Duplicate of #11890. A fix is already here: #11892 but it is waiting for merge.

**Closed** 2017-01-31 15:23 UTC
