### ISSUE TITLE
 'API does not exist' ERROR

### ISSUE THREAD

**Issue by iooou** [rg3/youtube-dl#8423] opened 2016-02-04 08:37 UTC
When I try to download a video from Naver Vlive, it gives me this error:

ERROR: GPOP_globalV/vod/5420/playinfo : Api not exists (존재하지 않는 API 입니다.); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Naver Vlive uses the same player as NaverTVCast, I hope you can fix this problem. 
Thank you.

**Comment by phihag** [comment] 2016-02-04 08:48
Sorry, we cannot fix this problem, since the information is insufficient. Be sure to call youtube-dl with the `--verbose` flag and include its **complete** output.

**Comment by dstftw** [comment] 2016-02-04 19:18
Duplicate of #8429.

**Closed by dstftw** 2016-02-04 19:18 UTC
