### ISSUE TITLE
youtube-dl throwing error 403 on certain videos

### ISSUE THREAD

**Issue by kenrestivo** [rg3/youtube-dl#6633] opened 2015-08-22 02:41 UTC
youtube-dl, latest release ( 2015.08.16.1) is throwing 403 errors on certain videos, but not others. They otherwise play fine in browsers, but youtube-dl cannot handle them anymore. Problem started today.

**Comment by dylanaraps** [comment] 2015-08-22 04:55
Also getting this issue today, tried updating to the newest version and it still persists. Happened with this url for me: https://www.youtube.com/watch\?v\=QcIy9NiNbmo

**Comment by yan12125** [comment] 2015-08-22 05:19
Duplicate of #6451. Remove the cache with ```youtube-dl --rm-cache-dir``` and try again.

**Closed by yan12125** 2015-08-22 05:19 UTC
