### ISSUE TITLE
Unable downloading from francetv since this day (2016-01-15)

### ISSUE THREAD

**Issue by hekatogkheires** [rg3/youtube-dl#8242] opened 2016-01-15 14:58 UTC
Hello,
I've tried some differents URL from francetv, downgraded youtube-dl (because of an upgrade of the system this morning), tried to modified francetv.py (but i'm not a developer), but nothing changed.
I get the same message: "Invalid data found when processing input".
Trying with other sites, youtube-dl works. It seems the problem comes with francetv.
So, you are my last chance.
Here's my output

youtube-dl -v http://pluzz.francetv.fr/videos/doctor_who_saison1_ep10_,134452437.html            
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://pluzz.francetv.fr/videos/doctor_who_saison1_ep10_,134452437.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.09
[debug] Python version 3.5.1 - Linux-4.3.3-2-ARCH-i686-with-arch
[debug] exe versions: ffmpeg 2.8.4, ffprobe 2.8.4, rtmpdump 2.4
[debug] Proxy map: {}
[pluzz.francetv.fr] doctor_who_saison1_ep10_,134452437: Downloading webpage
[pluzz.francetv.fr] 134452437: Downloading video JSON
[pluzz.francetv.fr] 134452437: Downloading geo restriction info
[pluzz.francetv.fr] 134452437: Downloading m3u8 information
[pluzz.francetv.fr] 134452437: Downloading m3u8 information
[debug] Invoking downloader on 'http://replayftv-vh.akamaihd.net/i/streaming-adaptatif_france-dom-tom/2016/S02/J1/134452437-56930ac6f04e8-,standard1,standard2,standard3,standard4,standard5,.mp4.csmil/index_4_av.m3u8?null='
[download] Destination: Doctor Who - Le Docteur danse-134452437.mp4
[debug] ffmpeg command line: ffmpeg -y -headers 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)
Cookie: _alid_=AoUOjPx/cRCvOBD/E8tm2w==
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
' -i 'http://replayftv-vh.akamaihd.net/i/streaming-adaptatif_france-dom-tom/2016/S02/J1/134452437-56930ac6f04e8-,standard1,standard2,standard3,standard4,standard5,.mp4.csmil/index_4_av.m3u8?null=' -f mp4 -c copy -bsf:a aac_adtstoasc 'file:Doctor Who - Le Docteur danse-134452437.mp4.part'
ffmpeg version 2.8.4 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 5.3.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-avresample --enable-fontconfig --enable-gnutls --enable-gpl --enable-ladspa --enable-libass --enable-libbluray --enable-libdcadec --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-shared --enable-version3 --enable-x11grab --disable-demuxer=hls --disable-protocol='concat,hls'
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
http://replayftv-vh.akamaihd.net/i/streaming-adaptatif_france-dom-tom/2016/S02/J1/134452437-56930ac6f04e8-,standard1,standard2,standard3,standard4,standard5,.mp4.csmil/index_4_av.m3u8?null=: Invalid data found when processing input

ERROR: ffmpeg exited with code 1
  File "/usr/bin/youtube-dl", line 9, in <module>
    load_entry_point('youtube-dl==2016.1.9', 'console_scripts', 'youtube-dl')()
  File "/usr/lib/python3.5/site-packages/youtube_dl/__init__.py", line 410, in main
    _real_main(argv)
  File "/usr/lib/python3.5/site-packages/youtube_dl/__init__.py", line 400, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1677, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 676, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 722, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1347, in process_video_result
    self.process_info(new_info)
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1609, in process_info
    success = dl(filename, info_dict)
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1551, in dl
    return fd.download(name, info)
  File "/usr/lib/python3.5/site-packages/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python3.5/site-packages/youtube_dl/downloader/hls.py", line 63, in real_download
    self.report_error('%s exited with code %d' % (ffpp.basename, retval))
  File "/usr/lib/python3.5/site-packages/youtube_dl/downloader/common.py", line 155, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 540, in report_error
    self.trouble(error_message, tb)
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 502, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

Best regards

**Comment by yan12125** [comment] 2016-01-15 15:08
Duplicate of  #8227. In short: francetv requires ffmpeg with HLS support but it's explicitly disabled due to security reasons. (See https://bugs.archlinux.org/task/47738). As a workaround, install ffmpeg-git from AUR.

**Closed by yan12125** 2016-01-15 15:08 UTC
