### ISSUE TITLE
Site Support Request: Daisuke

### ISSUE THREAD

**Issue by antonio8909** [rg3/youtube-dl#7776] opened 2015-12-06 22:51 UTC
Hi. Youtube-DL doesn't support Daisuki so I want to ask support for it.

youtube-dl -jv http://www.daisuki.net/anime/watch/STARMYU/brd
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-jv', u'http://www.daisuki.net/anime/watch/STARMYU/brd']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.12.05
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {'ftp': 'ftp://127.0.0.1:9666', 'http': 'http://127.0.0.1:9666', 'https': 'https://127.0.0.1:9666'}
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: http://www.daisuki.net/anime/watch/STARMYU/brd
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1285, in _real_extract
  File "youtube_dl\compat.pyo", line 248, in compat_etree_fromstring
  File "youtube_dl\compat.pyo", line 237, in _XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: mismatched tag: line 43, column 2
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 663, in extract_info
  File "youtube_dl\extractor\common.pyo", line 290, in extract
  File "youtube_dl\extractor\generic.pyo", line 1890, in _real_extract
UnsupportedError: Unsupported URL: http://www.daisuki.net/anime/watch/STARMYU/brd

Thanks in advance

**Comment by jaimeMF** [comment] 2015-12-06 23:08
Duplicate of #4738.

**Closed by jaimeMF** 2015-12-06 23:08 UTC

**Comment by antonio8909** [comment] 2015-12-06 23:12
But it doesnt say in that post if is going to be added or not

**Comment by jaimeMF** [comment] 2015-12-06 23:15
It's open and with the `site-support-request`, therefore we may add it ourselves or we'll review a pull request if someone adds support for it. Since we work on youtube-dl on our free time we prioritize things that we are interested in (sites/features we use or want to use); if you want support for it, the best way is to write the extractor yourself or pay/convince someone to do it.

**Comment by antonio8909** [comment] 2015-12-06 23:17
Don't worry I found another way to do it. Thanks anyway. Bye
