### ISSUE TITLE
Get video from this page

### ISSUE THREAD

**Issue by trandinhnam** [rg3/youtube-dl#7033] opened 2015-10-01 12:36 UTC
Dear all,
I have try to get data from this page and have solution but it take so long for video? Want to have discussion about this website to update to youtubedll project.

http://video.thethao247.vn/video-bong-da/v-league/video-cong-phuong-de-dang-danh-bai-hong-quan-o-bai-tap-doi-khang-dv113229.html
Regards,
SunSeaDo

**Comment by Phaeilo** [comment] 2015-10-05 14:46
The site you mentioned includes the script http://embed.mecloud.vn/play/JmhDQLulwd which in turn loads the script http://embed.mecloud.vn/render/JmhDQLulwd?target=abc . This script contains all the needed information (video URLs & metadata).

Unfortunately, the webserver at mecloud.vn always sends gzip compressed data, even if the client does not support it. This is kind of a pain to deal with in Python.

**Comment by trandinhnam** [comment] 2015-10-14 04:11
So, still not have solution for this website?
I have test by using WebBrowser on winform, keep session. I see i can get direct link but it will change for each session.

**Comment by remitamine** [comment] 2016-01-15 15:46
duplicate of #6836.

**Closed by remitamine** 2016-01-15 15:46 UTC
Labels: site-support-request
