### ISSUE TITLE
[PornHub] Don't download webpage for videos that match in an archive file

### ISSUE THREAD

**Issue by mjolnir870** [rg3/youtube-dl#17571] opened 2018-09-14 18:15 UTC
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: ['--no-mtime', '--no-playlist', '--playlist-reverse', '-i', '-w', '--sleep-interval', '5', '--max-sleep-interval', '7']
[debug] Command-line args: ['--config-location', 'C:\\Users\\USER\\Scripts\\youtube-dl-ondemand.conf', '--ffmpeg-location', 'C:\\Users\\USER\\Apps\\ffmpeg\\bin\\ffmpeg.exe', '--download-archive', 'M:\\test\\!pro\\!ph\\~youtube-dl_history.txt', '-f', 'bestvideo+bestaudio/best', '--write-thumbnail', '--external-downloader', 'C:\\Users\\USER\\Apps\\aria2\\64bit\\aria2c.exe', '--external-downloader-args', '--file-allocation=none -x 4 -k 1M', '-o', 'M:\\test\\!pro\\!ph\\%(title)s_%(id)s.%(ext)s', '-v', 'https://www.pornhub.com/view_video.php?viewkey=ph5b3dd823b8f68']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.09.10
[debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg N-90960-gbcff983dc3, ffprobe N-90960-gbcff983dc3
[debug] Proxy map: {}
[PornHub] ph5b3dd823b8f68: Downloading pc webpage
[download] 4K Porn: Sexy MILF with Shaved Pussy and BIG ass cant's resist HIGE cock has already been recorded in archive
```

---

### Description of your *issue*, suggested solution and other information

In the above log I am trying to download a pornhub video that is already recorded in the archive. youtube-dl is still downloading the webpage, which you can tell because it displays the title of the video.

Since youtube-dl already has the unique identifier from the URL, it should immediately reject this video BEFORE any downloading begins.

Current:
1. youtube-dl has unique identifier (ph5b3dd823b8f68).
2. youtube-dl downloads webpage
3. youtube-dl checks archive for ph5b3dd823b8f68.
4. youtube-dl rejects video with "[download] 4K Porn: Sexy MILF with Shaved Pussy and BIG ass cant's resist HIGE cock has already been recorded in archive"

Proposed:
1. youtube-dl has unique identifier (ph5b3dd823b8f68).
2. youtube-dl checks archive for ph5b3dd823b8f68.
3. youtube-dl rejects video with "[download] video with identifier ph5b3dd823b8f68 has already been recorded in archive"

**Comment by dstftw** [comment] 2019-01-22 21:02
Duplicate of #8486.

**Closed** 2019-01-22 21:01 UTC
