### ISSUE TITLE
Download playlists in reverse order (Negative boundaries for --playlist-start & --playlist-end)

### ISSUE THREAD

**Issue by 5moufl** [rg3/youtube-dl#514] opened 2012-11-05 13:43 UTC
Let's say I want the n last videos from a playlist, it'd be nice to be able to use negative numbers like in python to do that.
For example if I want the last 100 videos from a playlist I could do <pre>youtube-dl playlistURL --playlist-start -100</pre> or <pre>youtube-dl playlistURL --playlist-start -200 --playlist-101</pre> if I want the previous 100 videos.

**Comment by vitorgalvao** [comment] 2017-04-15 17:01
https://github.com/rg3/youtube-dl/issues/6845 is a duplicate of this. In that issue the suggestion is that `--playlist-reverse` (maybe it did not exist when this issue was opened) should also affect `--playlist-start` and `--playlist-end`. That seems the most logical solution.

**Comment by yan12125** [comment] 2017-04-15 17:50
Thanks. I'll close this as there are more discussions in #6845

**Closed by yan12125** 2017-04-15 17:50 UTC
Labels: request
