### ISSUE TITLE
Can't download from nicovideo.jp

### ISSUE THREAD

**Issue by UserNaem** [rg3/youtube-dl#11307] opened 2016-11-27 06:48 UTC
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.22*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.22**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
C:\Users\user>youtube-dl --verbose http://www.nicovideo.jp/watch/sm17064620
[debug] System config: []
[debug] User config: ['--console-title', '--add-metadata', '-f', 'bestvideo[vcod
ec=vp9][height<=?1080]+bestaudio[acodec=opus]/bestvideo[vcodec=vp9][height<=?720
]+bestaudio[acodec=opus]/bestvideo+bestaudio/best[ext=webm]/best', '-o', 'H:/v/y
outube-dl/%(title)s-%(id)s.%(ext)s']
[debug] Command-line args: ['--verbose', 'http://www.nicovideo.jp/watch/sm170646
20']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.11.22
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-80694-g074fdf4, ffprobe N-80694-g074fdf4
[debug] Proxy map: {}
[niconico] sm17064620: Downloading webpage
[niconico] sm17064620: Downloading video info page
[niconico] sm17064620: Downloading webpage
ERROR: Unable to extract thumbPlayKey; please report this issue on https://yt-dl
.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to u
pdate. Be sure to call youtube-dl with the --verbose flag and include its comple
te output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0yt5fyka\bu
ild\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0yt5fyka\bu
ild\youtube_dl\extractor\common.py", line 357, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0yt5fyka\bu
ild\youtube_dl\extractor\niconico.py", line 141, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0yt5fyka\bu
ild\youtube_dl\extractor\common.py", line 660, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract thumbPlayKey; please repo
rt this issue on https://yt-dl.org/bug . Make sure you are using the latest vers
ion; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbo
se flag and include its complete output.

**Comment by yan12125** [comment] 2016-11-27 07:27
Duplicate of #11170

**Closed by yan12125** 2016-11-27 07:27 UTC
