### ISSUE TITLE
u'Could not download DASH manifest

### ISSUE THREAD

**Issue by sdsucks** [rg3/youtube-dl#6222] opened 2015-07-14 07:52 UTC
F:\>youtube-dl -f 266+140 --verbose https://www.youtube.com/watch?v=RtrKAmAEMkQ
[debug] System config: []
[debug] User config: [u'-f', u'bestvideo+bestaudio', u'--console-title', u'--no-mtime', u'-w', u'-c', u'-i', u'-o
', u'%(title)s by %(uploader)s.%(ext)s']
[debug] Command-line args: [u'-f', u'266+140', u'--verbose', u'https://www.youtube.com/watch?v=RtrKAmAEMkQ']
[debug] Encodings: locale cp949, fs mbcs, out cp949, pref cp949
[debug] youtube-dl version 2015.07.07
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-73541-g944a1aa
[debug] Proxy map: {}
[youtube] RtrKAmAEMkQ: Downloading webpage
[youtube] RtrKAmAEMkQ: Downloading video info webpage
[youtube] RtrKAmAEMkQ: Extracting video information
[youtube] {22} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {43} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {18} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {5} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {36} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {17} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {266} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {264} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {137} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {136} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {135} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {134} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {133} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {160} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {140} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {171} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {249} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {250} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {251} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] RtrKAmAEMkQ: Downloading DASH manifest
[youtube] RtrKAmAEMkQ: Downloading player https://s.ytimg.com/yts/jsbin/html5player-en_US-vflVsMRd_/html5player.j
s
[youtube] RtrKAmAEMkQ: Downloading DASH manifest
WARNING: [youtube] RtrKAmAEMkQ: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP E
rror 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you ar
e using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag an
d include its complete output.',)
[debug] Invoking downloader on 'https://r5---sn-3u-bh2y.googlevideo.com/videoplayback?id=46daca0260043244&itag=26
6&source=youtube&requiressl=yes&mn=sn-3u-bh2y&mm=31&ms=au&mv=m&pcm2cms=yes&pl=19&ratebypass=yes&mime=video/mp4&gi
r=yes&clen=259513942&lmt=1436277258279598&dur=204.704&fexp=901816,936118,9407536,9407662,9407942,9408093,9408142,
9408420,9408710,9412489,9412755,9414764,9415884,9416126,9416729,9416847&upn=Lr14eS-F03Y&key=dg_yt0&mt=1436859990&
signature=3EDA2BAA6DB82BAA58438D7C1EBC409E293C467B.2050FB87045C1B4298947C208BE54024EF7AD505&sver=3&ip=xxx.xxx.xxx
.xx&ipbits=0&expire=1436881698&sparams=ip,ipbits,expire,id,itag,source,requiressl,mn,mm,ms,mv,pcm2cms,pl,ratebypa
ss,mime,gir,clen,lmt,dur'
[download] Resuming download at byte 92273664
[download] Destination: [직캠_Fancam] 150707 디홀릭(D.Holic) (두리) 쫄깃쫄깃(Chewy Chewy) @ The First Mini Album
Showcase by pharkil 2015.f266.mp4
[download] 100% of 247.49MiB in 00:18
[debug] Invoking downloader on 'https://r5---sn-3u-bh2y.googlevideo.com/videoplayback?id=46daca0260043244&itag=14
0&source=youtube&requiressl=yes&mn=sn-3u-bh2y&mm=31&ms=au&mv=m&pcm2cms=yes&pl=19&ratebypass=yes&mime=audio/mp4&gi
r=yes&clen=3253009&lmt=1436276979882171&dur=204.753&fexp=901816,936118,9407536,9407662,9407942,9408093,9408142,94
08420,9408710,9412489,9412755,9414764,9415884,9416126,9416729,9416847&upn=Lr14eS-F03Y&key=dg_yt0&mt=1436859990&si
gnature=064A56D04E90FC5BDF2BF6B4B7B47172DF4D332F.556DD6E7A5EB1BDA3111E99C1754C6F9C85A1ACA&sver=3&ip=xxx.xxx.xxx.xx
4&ipbits=0&expire=1436881698&sparams=ip,ipbits,expire,id,itag,source,requiressl,mn,mm,ms,mv,pcm2cms,pl,ratebypass
,mime,gir,clen,lmt,dur'
[download] Destination: [직캠_Fancam] 150707 디홀릭(D.Holic) (두리) 쫄깃쫄깃(Chewy Chewy) @ The First Mini Album
Showcase by pharkil 2015.f140.m4a
[download] 100% of 3.10MiB in 00:00
[ffmpeg] Merging formats into "[직캠_Fancam] 150707 디홀릭(D.Holic) (두리) 쫄깃쫄깃(Chewy Chewy) @ The First Mini
 Album Showcase by pharkil 2015.mp4"
[debug] ffmpeg command line: ffmpeg -y -i '[직캠_Fancam] 150707 디홀릭(D.Holic) (두리) 쫄깃쫄깃(Chewy Chewy) @ Th
e First Mini Album Showcase by pharkil 2015.f266.mp4' -i '[직캠_Fancam] 150707 디홀릭(D.Holic) (두리) 쫄깃쫄깃(Ch
ewy Chewy) @ The First Mini Album Showcase by pharkil 2015.f140.m4a' -c copy -map 0:v:0 -map 1:a:0 '[직캠_Fancam]
 150707 디홀릭(D.Holic) (두리) 쫄깃쫄깃(Chewy Chewy) @ The First Mini Album Showcase by pharkil 2015.temp.mp4'
Deleting original file [직캠_Fancam] 150707 디홀릭(D.Holic) (두리) 쫄깃쫄깃(Chewy Chewy) @ The First Mini Album S
howcase by pharkil 2015.f266.mp4 (pass -k to keep)
Deleting original file [직캠_Fancam] 150707 디홀릭(D.Holic) (두리) 쫄깃쫄깃(Chewy Chewy) @ The First Mini Album S
howcase by pharkil 2015.f140.m4a (pass -k to keep)

F:\>

**Comment by yan12125** [comment] 2015-07-14 07:55
A duplicate of #5118. It's a known bug.

**Closed by yan12125** 2015-07-14 07:55 UTC
