### ISSUE TITLE
[Help needed] Some youtube videos giving 403 error

### ISSUE THREAD

**Issue by kumarvaradarajulu** [rg3/youtube-dl#9756] opened 2016-06-11 12:03 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.06.11.3*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.11.3**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

I am trying to build a bot to download videos from `Youtube`. My server crawls the specific Youtube account and if there are new videos the download links are added to my web site, which is used by quite a few of my friends to download the new videos.

The issue I have is, I get *403* forbidden error. If I try to use youtube-dl command line to download the vide on my server or my machine it works fine. But when I use the download url got from the server on my machine it does not work. I have tried settings cookies, updating http headers to be the same as server, Still no luck. Went through a host of Stackoverflow questions and FAQ of youtube-dl and tried every method, it still doesn't work. 

**Failing video link https://www.youtube.com/watch?v=nCD2hj6zJEc**
  * [Resolved download url on server] (https://r3---sn-ogueln7s.googlevideo.com/videoplayback?ms=au&mv=m&mt=1465644400&requiressl=yes&ip=108.61.180.112&ipbits=0&gcr=jp&pl=23&id=o-AJTuFI48SoxcDyr4-P8C2RCj2RmQbt9yfMEt0De4HVIx&mime=video%2Fmp4&mn=sn-ogueln7s&mm=31&itag=22&lmt=1458220028615968&key=yt6&ratebypass=yes&upn=iaKrMO93Yig&nh=IgpwcjAzLm5ydDE5KgkxMjcuMC4wLjE&source=youtube&sparams=dur%2Cgcr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&expire=1465666284&sver=3&fexp=9416126%2C9416313%2C9416891%2C9422596%2C9422844%2C9425362%2C9428398%2C9431012%2C9432373%2C9432565%2C9432683%2C9433096%2C9433380%2C9433672%2C9433703%2C9433946%2C9435525%2C9435527%2C9435789%2C9435876%2C9436606%2C9436802%2C9436834%2C9436923%2C9437066%2C9437282%2C9437553%2C9438245%2C9438523%2C9438804&initcwndbps=18051250&dur=304.018&signature=C30BE1EA4A0FD1877423C47C72B3D6C302C242E3.DBCB60F8D683B4F96A86D13C1FF67178F55F60AF)
  * [Resolved download url on my machine](https://r3---sn-ci5gup-qxaz.googlevideo.com/videoplayback?mn=sn-ci5gup-qxaz&mm=31&pl=22&mv=m&mt=1465645434&ms=au&upn=hhz7Fk3fYrM&source=youtube&requiressl=yes&expire=1465667507&mime=video%2Fmp4&initcwndbps=1127500&ipbits=0&gcr=in&fexp=9416126%2C9416891%2C9416903%2C9419452%2C9420112%2C9422596%2C9428398%2C9430838%2C9431012%2C9433096%2C9433223%2C9433702%2C9433946%2C9434183%2C9434440%2C9434953%2C9435025%2C9435527%2C9435876%2C9436083%2C9436212%2C9437066%2C9437178%2C9437553%2C9438565%2C9438630%2C9438661%2C9438769&key=yt6&lmt=1458220028615968&dur=304.018&itag=22&ip=223.227.108.215&sparams=dur%2Cgcr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&sver=3&ratebypass=yes&id=o-AFwDcFMd_jzbxn5afp4hjcr4Qft9qIs0_c9IqFwhqMDZ&signature=A8F24BAE364B4A6CF73E915351ADF85BD56E236D.1320546A93446370C241B1DA04D4FB3ED5701756)

**Another failing video link https://www.youtube.com/watch?v=h3FCn_QYf8g**
 * [Resolved download url on server](https://r2---sn-ogueln7z.googlevideo.com/videoplayback?lmt=1463127938796536&gcr=jp&sver=3&expire=1465667854&upn=lpi43SAUxmY&ms=au&dur=118.630&mv=m&mt=1465646055&ip=108.61.180.112&initcwndbps=19582500&id=o-APCa8c3NTm0iO82W_yo3QhO7njmhERyzdP36PcTjj1Zj&mn=sn-ogueln7z&mm=31&ipbits=0&itag=22&cnr=14&sparams=cnr%2Cdur%2Cgcr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&requiressl=yes&ratebypass=yes&source=youtube&pl=23&mime=video%2Fmp4&fexp=9405349%2C9407190%2C9416126%2C9416891%2C9417701%2C9418778%2C9422596%2C9428398%2C9431012%2C9432369%2C9432425%2C9433096%2C9433380%2C9433946%2C9435527%2C9435666%2C9435876%2C9436050%2C9437066%2C9437553%2C9437686%2C9438095%2C9438519%2C9438892&key=yt6&nh=IgpwcjAzLm5ydDE5KgkxMjcuMC4wLjE&signature=740D485BBC202CDABC9E06EFF2E84C1509064D18.3B1EF43D73F78058CC8D975D901E3B0E717C8679)
 * [Resolved download url on my machine](https://r8---sn-ci5gup-qxaz.googlevideo.com/videoplayback?gcr=in&sver=3&upn=9QjrUaunxv8&mime=video%2Fmp4&ratebypass=yes&ipbits=0&initcwndbps=1183750&expire=1465667950&fexp=9408206%2C9414702%2C9415952%2C9416126%2C9416891%2C9419452%2C9422596%2C9424416%2C9428398%2C9431012%2C9432683%2C9433096%2C9433380%2C9433802%2C9433946%2C9435396%2C9435527%2C9435876%2C9436923%2C9436982%2C9437066%2C9437259%2C9437553%2C9437616%2C9437807%2C9437919%2C9437955%2C9438336%2C9438565%2C9438766&ip=223.227.108.215&cnr=14&requiressl=yes&lmt=1463127938796536&itag=22&id=o-APmW2ZvKHugOGmz8LLFu8CrAcTqGRViIm0Xmt9zvuQdG&dur=118.630&source=youtube&sparams=cnr%2Cdur%2Cgcr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&key=yt6&mn=sn-ci5gup-qxaz&mm=31&ms=au&pl=22&mv=m&mt=1465646055&signature=9BEA335F0E6B7A4DCB30EC800859F85DB03FA73F.84CBFC4F08787A7591E6946364C3B871D1AD1ED4)

**Successful vide link  https://www.youtube.com/watch?v=6PqTnMYK4kw**
 * [Resolved download url on server](https://r5---sn-ogueln7k.googlevideo.com/videoplayback?sver=3&ratebypass=yes&nh=IgpwcjAzLm5ydDE5KgkxMjcuMC4wLjE&lmt=1460252642769630&mn=sn-ogueln7k&dur=104.164&source=youtube&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&requiressl=yes&fexp=9410705%2C9414672%2C9416126%2C9416891%2C9417828%2C9422596%2C9428398%2C9428742%2C9431012%2C9432056%2C9433096%2C9433380%2C9433946%2C9435527%2C9435580%2C9435876%2C9436017%2C9436210%2C9436921%2C9437066%2C9437415%2C9437553%2C9437780%2C9438037%2C9438361%2C9438569&mm=31&ip=108.61.180.112&itag=22&ipbits=0&pl=23&id=o-AHhC6tK-x-mDS6airRTKYbGnjBHugH2VoqaUleyLSqzJ&mt=1465646055&mv=m&ms=au&mime=video%2Fmp4&key=yt6&upn=Y0N9wCSkyuo&expire=1465668053&initcwndbps=19582500&signature=94CF49701251FFCD25A4277456D540AABC69A36F.E1C2383940D8D5860287C29E1DF5A44F127D04FD)
 * [Resolved download url on my machine] (https://r8---sn-ci5gup-qxaz.googlevideo.com/videoplayback?upn=kmdDaSFnGCQ&ratebypass=yes&source=youtube&lmt=1460252642769630&pcm2=no&fexp=9407156%2C9416126%2C9416891%2C9419451%2C9422596%2C9427768%2C9428398%2C9431012%2C9432058%2C9432368%2C9432564%2C9432683%2C9433096%2C9433380%2C9433672%2C9433706%2C9433946%2C9435527%2C9435876%2C9436224%2C9436922%2C9437066%2C9437553%2C9437949%2C9438156%2C9438245%2C9438570&ipbits=0&mime=video%2Fmp4&itag=22&cnr=14&id=o-ACS3lkmZdF0-6erd-JrB7zSTp_s5U_GzZ78UKIb55AfV&dur=104.164&mt=1465646055&pl=22&mv=m&ms=au&requiressl=yes&mm=31&ip=223.227.108.215&mn=sn-ci5gup-qxaz&sparams=cnr%2Cdur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&key=yt6&sver=3&expire=1465668132&initcwndbps=1183750&signature=61F8102D6F897DD8EA77735CCD8E7494E02501A4.33D0041506BF026B27F931FCE612891BABDBF270)

Any help or advise on this would be much appreciated. Hope I have followed the guidelines to post.

**Comment by yan12125** [comment] 2016-06-11 12:10
Have you tried https://github.com/rg3/youtube-dl/issues/9001#issuecomment-201991818?

**Comment by kumarvaradarajulu** [comment] 2016-06-11 12:14
Thank you @yan12125 I seemed to have missed that post. With quick check it works fine. Will check in detail and report back here.

**Comment by yan12125** [comment] 2016-06-11 13:26
Seems the problem is resolved. Closing.

**Closed by yan12125** 2016-06-11 13:26 UTC

**Comment by kumarvaradarajulu** [comment] 2016-06-11 13:32
Yes the issue is solved. Had to deploy the updated code to the server and run tests hence the delay. Thank you very much.
