### ISSUE TITLE
 --skip-download --get-url "http://www.youtube.com/watch?v=EkHTsc9PU2A&fmt="

### ISSUE THREAD

**Issue by hennyere** [rg3/youtube-dl#6362] opened 2015-07-25 18:37 UTC
WARNING: Could not download DASH manifest: HTTP Error 403: Forbidden
https://r5---sn-b8u-nn5l.googlevideo.com/videoplayback?id=1241d3b1cf4f5360&itag=135&source=youtube&requiressl=yes&gcr=br&ms=au&mv=m&mn=sn-b8u-nn5l&mm=31&pl=36&pcm2cms=yes&ratebypass=yes&mime=video/mp4&gir=yes&clen=18576102&lmt=1426231872186063&dur=220.987&mt=1437849349&signature=4421F2860315FD9AFE4CA81D76FB4339F40CE283.5E4F3AE9F852ED95673624C67CEAE4D3656BC5E7&fexp=901816,923618,9408710,9414764,9415365,9415485,9416126,966300&sver=3&upn=LF09scvLfGk&key=dg_yt0&ip=2804:7f7:a280:d363:5d9a:28d0:7b71:2d64&ipbits=0&expire=1437870999&sparams=ip,ipbits,expire,id,itag,source,requiressl,gcr,ms,mv,mn,mm,pl,pcm2cms,ratebypass,mime,gir,clen,lmt,dur
https://r5---sn-b8u-nn5l.googlevideo.com/videoplayback?id=1241d3b1cf4f5360&itag=141&source=youtube&requiressl=yes&gcr=br&ms=au&mv=m&mn=sn-b8u-nn5l&mm=31&pl=36&pcm2cms=yes&ratebypass=yes&mime=audio/mp4&gir=yes&clen=7048366&lmt=1426231835392530&dur=221.053&mt=1437849349&signature=1F4C7D71463FBB7CF43E72877291F0AE8C2D0C41.2CB77019FB35B1CBCAE484DF77C3CCC82C8F88F6&fexp=901816,923618,9408710,9414764,9415365,9415485,9416126,966300&sver=3&upn=LF09scvLfGk&key=dg_yt0&ip=2804:7f7:a280:d363:5d9a:28d0:7b71:2d64&ipbits=0&expire=1437870999&sparams=ip,ipbits,expire,id,itag,source,requiressl,gcr,ms,mv,mn,mm,pl,pcm2cms,ratebypass,mime,gir,clen,lmt,dur

**Comment by dstftw** [comment] 2015-07-25 18:38
Duplicate of #5118.

**Closed by dstftw** 2015-07-25 18:38 UTC
