### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc1 in position 0

### ISSUE THREAD

**Issue by Alexey-Ky** [rg3/youtube-dl#4631] opened 2015-01-04 11:52 UTC
youtube-dl http://rutube.ru/video/033d58ffe1c922ce3aa49eb247eddd06/

[rutube] 033d58ffe1c922ce3aa49eb247eddd06: Downloading video JSON
[rutube] 033d58ffe1c922ce3aa49eb247eddd06: Downloading options JSON
[rutube] 033d58ffe1c922ce3aa49eb247eddd06: Downloading m3u8 information
[download] Destination: Белякова Ольга, толчок-033d58ffe1c922ce3aa49eb247eddd06.mp4
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 361, in main
  File "youtube_dl\__init__.pyo", line 351, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1165, in download
  File "youtube_dl\YoutubeDL.pyo", line 603, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 649, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 938, in process_video_result
  File "youtube_dl\YoutubeDL.pyo", line 1136, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1112, in dl
  File "youtube_dl\downloader\common.pyo", line 297, in download
  File "youtube_dl\downloader\hls.pyo", line 41, in real_download
  File "subprocess.pyo", line 522, in call
  File "subprocess.pyo", line 710, in __init__
  File "subprocess.pyo", line 913, in _execute_child
  File "subprocess.pyo", line 644, in list2cmdline
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc1 in position 0: ordinal not in range(128)

**Comment by Alexey-Ky** [comment] 2015-01-04 11:57
if download videos from http://rutube and the title of the video in Russian language it generates an error
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc1 in position 0: ordinal not in range(128)

http://rutube.ru/video/5b404e24f90e435abd6fdef921349921/
http://rutube.ru/video/033d58ffe1c922ce3aa49eb247eddd06/
http://rutube.ru/video/becc719340e1bdd982c607754f20f0e4/

**Comment by dstftw** [comment] 2015-01-04 16:45
Duplicate of #3580.

**Closed by dstftw** 2015-01-04 16:45 UTC
