### ISSUE TITLE
Cant download from globoplay.

### ISSUE THREAD

**Issue by Vieirabrazil** [rg3/youtube-dl#15196] opened 2018-01-08 03:50 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.07*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

Hi all,

Until 2017/12/30  I was able to download "The Voice Brasil" Episodes from Globoplay site.

From now on, site is asking authentication. Well, I have a username and password for this site, but it is not working (same in Linux or Windows).

No matter I enter the correct or incorrect password, the output is the same.

I would like to know what is the format for username field, Is it possible to insert some sub-domain or it is only for username plain text???  

Just cant imagine what is wrong

See output below.

Thanks,

Vieira 

`C:\Users\Vieira\Downloads\Softs\Youtube-DL>youtube-dl.exe --version
2018.01.07

C:\Users\Vieira\Downloads\Softs\Youtube-DL>youtube-dl.exe -v --username "myemail@gmail.com" https://globoplay.globo.com/v/6405187/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--username', 'PRIVATE', 'https://globoplay.globo.com/v/6405187/']
Type account password and press [Return]:
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.01.07
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg N-52233-gee94362, ffprobe N-52233-gee94362
[debug] Proxy map: {}
[Globo] 6405187: Downloading JSON metadata
[Globo] 6405187: Downloading security hash for 6405187_90_720_l_collection
ERROR: Globo returned error: Video is for subscribers only. Authorization required.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4k56gdgt\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4k56gdgt\build\youtube_dl\extractor\common.py", line 438, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4k56gdgt\build\youtube_dl\extractor\globo.py", line 360, in _real_extract
youtube_dl.utils.ExtractorError: Globo returned error: Video is for subscribers only. Authorization required.

C:\Users\Vieira\Downloads\Softs\Youtube-DL>`

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by dstftw** [comment] 2018-01-08 14:11
Duplicate of #4189.

**Closed by dstftw** 2018-01-08 14:11 UTC

**Comment by pathamo1** [comment] 2018-04-19 00:50
TESTADO E APROVADO

c:\>youtube-dl.exe -u user@gmail.com -p password  -o "C:\Users\Adm\Videos\%(playlist_index)s - %(title)s.%(ext)s" --fixup never --all-subs --external-downloader aria2c.exe https://LINK DA globoplay

**Comment by pathamo1** [comment] 2018-04-19 00:51
TESTADO E APROVADO

youtube-dl.exe -u user@gmail.com -p password -o "C:\Users\Adm\Videos%(playlist_index)s - %(title)s.%(ext)s" --fixup never --all-subs --external-downloader aria2c.exe https://LINK DA globoplay
