### ISSUE TITLE
Offten Errors with DashSegments!

### ISSUE THREAD

**Issue by marabu88** [rg3/youtube-dl#8465] opened 2016-02-08 18:35 UTC
videos from youtube with DashSegments not download full very offten. download some part video-stream and interrupted with error 404. may automatically restart such downloads? since these videos may download, but you have to restart the download several times manually! if the video to be downloaded in automatic mode, they can already be removed from YouTube and download them again there is no way!

**Comment by dstftw** [comment] 2016-02-09 15:54
Duplicate of #8466.

**Closed by dstftw** 2016-02-09 15:54 UTC
