### ISSUE TITLE
Instagram Videos download error

### ISSUE THREAD

**Issue by someziggyman** [rg3/youtube-dl#12785] opened 2017-04-19 09:11 UTC
I'm using the latest version - youtube-dl is up-to-date (2017.04.17)

Here's the output I'm getting:

--verbose https://www.instagram.com/p/BRi4BX-AsTL/?taken-by=nba
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.instagram.com/p/BRi4BX-AsTL/?taken-by=nba']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.20
[debug] Python version 2.7.10 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[Instagram] BRi4BX-AsTL: Downloading webpage
WARNING: unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./vydl/__main__.py", line 19, in <module>
  File "./vydl/youtube_dl/__init__.py", line 464, in main
  File "./vydl/youtube_dl/__init__.py", line 454, in _real_main
  File "./vydl/youtube_dl/YoutubeDL.py", line 1884, in download
  File "./vydl/youtube_dl/YoutubeDL.py", line 761, in extract_info
  File "./vydl/youtube_dl/extractor/common.py", line 428, in extract
  File "./vydl/youtube_dl/extractor/instagram.py", line 206, in _real_extract
UnboundLocalError: local variable 'comments' referenced before assignment

**Comment by yan12125** [comment] 2017-04-19 09:12
Duplicate of #12777. This is fixed in git and the fix will be included in the next version.

**Closed by yan12125** 2017-04-19 09:12 UTC
