### ISSUE TITLE
Warning: Skipping DASH manifest

### ISSUE THREAD

**Issue by JRichardH** [rg3/youtube-dl#5918] opened 2015-06-07 13:28 UTC
received the following warning message:
"richard@mx143:/DATL/ABA
$ youtube-dl -k https://www.youtube.com/watch?v=ac75H0SvZ5M
[youtube] ac75H0SvZ5M: Downloading webpage
[youtube] ac75H0SvZ5M: Extracting video information
WARNING: [youtube] ac75H0SvZ5M: Skipping DASH manifest: ExtractorError(u'Cannot decrypt signature without player_url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[download] Destination: 24. Presentacion de reforzadores-ac75H0SvZ5M.f133.mp4
[download]  24.6% of 18.28MiB at 125.11KiB/s ETA 01:52"

Timed out after this, but restarted and continued without problem. 
Maybe I need to include the "--youtube-skip-dash-manifest" option.
Found this about DASH, 
http://lifehacker.com/preload-entire-youtube-videos-by-disabling-dash-playbac-1186454034

Thanks for a most useful app!

**Comment by TheGr33k** [comment] 2015-07-09 08:57
Duplicate of #5118

**Comment by yan12125** [comment] 2015-07-09 09:13
Thanks @TheGr33k, but the error message is different. 

> Cannot decrypt signature without player_url

**Closed** 2017-04-01 19:52 UTC
Labels: cant-reproduce, duplicate
