### ISSUE TITLE
Vkontakte specific site support request

### ISSUE THREAD

**Issue by mememasterino** [rg3/youtube-dl#9405] opened 2016-05-05 16:25 UTC
Can you please add support to vkontakte pages like this similar to how bandcamp ones work ?

```
youtube-dl -v http://vk.com/wall-84528873_287
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://vk.com/wall-84528873_287']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.01
[debug] Python version 3.5.1 - Linux-4.5.1-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.0.2, ffprobe 3.0.2
[debug] Proxy map: {}
[generic] wall-84528873_287: Requesting header
WARNING: Could not send HEAD request to http://vk.com/wall-84528873_287: HTTP Error 501: Not Implemented
[generic] wall-84528873_287: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] wall-84528873_287: Extracting information
[redirect] Following redirect to http://vk.com/badbrowser.php
[generic] badbrowser: Requesting header
WARNING: Could not send HEAD request to http://vk.com/badbrowser.php: HTTP Error 501: Not Implemented
[generic] badbrowser: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] badbrowser: Extracting information
ERROR: Unsupported URL: http://vk.com/badbrowser.php
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 673, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2063, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://vk.com/badbrowser.php
```

**Comment by Hrxn** [comment] 2016-05-05 16:37
`http://vk.com/badbrowser.php`?

Yikes, looks like they do some kind of user agent type check..

**Comment by dstftw** [comment] 2016-05-06 16:44
Duplicate of #7053.

**Closed by dstftw** 2016-05-06 16:44 UTC
