### ISSUE TITLE
Support for bravotv.com

### ISSUE THREAD

**Issue by andreikobe** [rg3/youtube-dl#6498] opened 2015-08-08 11:19 UTC
URL: http://www.bravotv.com/watch-what-happens-live/season/episode-12131/videos?clip=2889030
Error: Unsupported URL: http://www.bravotv.com/watch-what-happens-live/season/episode-12131/videos?clip=2889030
Version: 2015.08.06.1
Video player: ThePlatform 

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.bravotv.com/watch-what-happens-live/season/episode-12131/videos?clip=2889030']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.06.1
[debug] Python version 2.7.5 - Darwin-13.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.4.3, ffprobe 2.4.3, rtmpdump 2.4
[debug] Proxy map: {}
[generic] videos?clip=2889030: Requesting header
WARNING: Falling back on generic information extractor.
[generic] videos?clip=2889030: Downloading webpage
[generic] videos?clip=2889030: Extracting information
ERROR: Unsupported URL: http://www.bravotv.com/watch-what-happens-live/season/episode-12131/videos?clip=2889030
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1115, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1594, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 14, column 409
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 655, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 282, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1704, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.bravotv.com/watch-what-happens-live/season/episode-12131/videos?clip=2889030

**Comment by dstftw** [comment] 2015-08-08 11:21
Duplicate of #4657.

**Closed by dstftw** 2015-08-08 11:21 UTC
