### ISSUE TITLE
Site request : please add erovideo

### ISSUE THREAD

**Issue by uosen123** [rg3/youtube-dl#10672] opened 2016-09-16 06:11 UTC
Thank you for an excellent tool.

Please support erovideo
http://ero-video.net/movie/?mcd=tfOpqNUwpNtDTNDc

This site don't directly describe a video source.
The video source of the above URL is http://vfile26.ero-video.net/dm/bb9aa349bf4928c63653db8e5e86718a/57db88fd/20160323/1458727419_677026_289657.flv.
But, it isn't described. Apparently, a browser seems to access http://smv.to/detail/NXu5YDf384/ but doesn't.

youtube-dl log
youtube-dl http://ero-video.net/movie/?mcd=tfOpqNUwpNtDTNDc
[generic] ?mcd=tfOpqNUwpNtDTNDc: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?mcd=tfOpqNUwpNtDTNDc: Downloading webpage
[generic] ?mcd=tfOpqNUwpNtDTNDc: Extracting information
ERROR: Unsupported URL: http://ero-video.net/movie/?mcd=tfOpqNUwpNtDTNDc

Thank you for reading

**Comment by yan12125** [comment] 2016-09-16 13:13
Duplicate of #8685. By the way I got no videos in http://ero-video.net/movie/?mcd=tfOpqNUwpNtDTNDc

**Closed by yan12125** 2016-09-16 13:13 UTC

**Comment by uosen123** [comment] 2016-09-17 07:11
Does it mean  you can't playback a video?
I have gotten the video source URL with FireFox and its add-ons, or DownLoadHelper.
We may be able to get it with Wireshark. But, I don't know a general rule.

**Comment by yan12125** [comment] 2016-09-17 07:21
OK now I can watch it with Flash enabled.

Are videos uploaded by users? This website was once concerned to be copyright infringing, and I'd like to check whether those videos are legal or not. If all videos on a website are uploaded by users, they can be considered as legal.

**Comment by yan12125** [comment] 2016-09-17 07:24
According to https://www.google.com/transparencyreport/removals/copyright/searchdata/domains/?id=ero-video.net, 82.3% of videos on this websites are considered illegal. Sorry youtube-dl can't support it.
