### ISSUE TITLE
Problem with youku

### ISSUE THREAD

**Issue by treaki** [rg3/youtube-dl#4732] opened 2015-01-17 16:29 UTC
hi,

i have problem with platform youku:

```
$ youtube-dl --verbose http://v.youku.com/v_show/id_XNjI2OTc5MDQw.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://v.youku.com/v_show/id_XNjI2OTc5MDQw.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.16
[debug] Python version 2.7.8 - Linux-3.16-3-amd64-x86_64-with-debian-jessie-sid
[debug] exe versions: avconv 2.4.3, avprobe 2.4.3, ffmpeg 2.4.3, ffprobe 2.4.3, rtmpdump 2.4
[debug] Proxy map: {}
[Youku] XNjI2OTc5MDQw: Downloading JSON metadata
WARNING: Extractor Youku returned a compat_list result. It needs to be updated.
[debug] Invoking downloader on u'http://k.youku.com/player/getFlvPath/sid/142151204342217621061_00/st/flv/fileid/0300010100526CE3C5DF9B0669FC064C7055B8-7E5C-E303-3F10-FECC7FA39F27?k=c2f232d270ff999f261e2032'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1155, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1131, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 308, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 67, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1412, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found


```

please fix that, thanks in advance

**Comment by dstftw** [comment] 2015-01-17 16:30
Duplicate of #4281.

**Closed by dstftw** 2015-01-17 16:30 UTC
