### ISSUE TITLE
Audio track ripper given the tracklist

### ISSUE THREAD

**Issue by pabloab** [rg3/youtube-dl#12251] opened 2017-02-24 17:32 UTC
_This is a postprocessor feature request._
Right now we can extract audio track and rename it beautifully with `youtube-dl --output "%(title)s.%(ext)s" --extract-audio --audio-format mp3`.
It is pretty common to find Youtube videos which are full albums, not just one track. Is also very common to find on description the tracklist, in the form _hh:mm:ss author - title\n_
Wouldn't be really useful to have a `--audio-rip` or `--rip-from-descrption` option to rip those big audio tracks into their components?
Meanwhile I'm trying to do a bash script to do it manually, maybe with `abcde`.

**Comment by dstftw** [comment] 2017-02-24 17:54
Duplicate of #6480.

**Closed** 2017-02-24 17:54 UTC
