### ISSUE TITLE
Avconv : embed thumbnail, No such file or directory

### ISSUE THREAD

**Issue by flyingrub** [rg3/youtube-dl#10116] opened 2016-07-18 14:21 UTC
```
root@raspberrypi:/mnt/test # time y2mp3 https://youtu.be/JSpKPsGoyHc -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-x', '--embed-thumbnail', '--audio-format', 'mp3', '--ignore-errors', '--add-metadata', '-o', '%(title)s.%(ext)s', '--audio-quality', '0', 'https://youtu.be/JSpKPsGoyHc', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.13
[debug] Python version 3.4.2 - Linux-4.4.13+-armv6l-with-debian-8.0
[debug] exe versions: avconv 11.7-6, avprobe 11.7-6
[debug] Proxy map: {}
[youtube] JSpKPsGoyHc: Downloading webpage
[youtube] JSpKPsGoyHc: Downloading video info webpage
[youtube] JSpKPsGoyHc: Extracting video information
[youtube] {43} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {18} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {36} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {17} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {134} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {243} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {133} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {242} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {160} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {278} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {140} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {171} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] JSpKPsGoyHc: Downloading thumbnail ...
[youtube] JSpKPsGoyHc: Writing thumbnail to: Gesaffelstein - Viol (Brodinski Remix).jpg
[debug] Invoking downloader on 'https://r5---sn-hgn7zn7l.googlevideo.com/videoplayback?keepalive=yes&ei=ouOMV-b7BYrAcY_JtcgM&lmt=1398347208733746&upn=UspbwgKjEDU&source=youtube&mn=sn-hgn7zn7l&mm=31&pl=16&id=o-AIkimiwvvCF9EOUBZ6AovF70aMnfRVxBg_cnyxtxSFP0&requiressl=yes&ip=90.57.113.193&fexp=9416126%2C9416891%2C9419452%2C9422596%2C9428398%2C9431012%2C9431825%2C9432058%2C9433096%2C9433380%2C9433946%2C9435526%2C9435673%2C9435738%2C9435876%2C9436270%2C9436607%2C9437066%2C9437553%2C9438313%2C9438662%2C9439327%2C9439652%2C9439886%2C9440030%2C9440457%2C9440499&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&mv=m&initcwndbps=780000&mt=1468850879&ms=au&dur=272.293&ipbits=0&sver=3&expire=1468872706&itag=171&clen=4222627&key=yt6&mime=audio%2Fwebm&gir=yes&signature=90DBDD330C311101E22CE515043F813BA80F5915.D776B3E0672A9534D049AFF106980D865A3A799C&ratebypass=yes'
[download] Destination: Gesaffelstein - Viol (Brodinski Remix).webm
[download] 100% of 4.03MiB in 00:04
[ffmpeg] Adding metadata to 'Gesaffelstein - Viol (Brodinski Remix).webm'
[debug] ffmpeg command line: avconv -y -i 'file:Gesaffelstein - Viol (Brodinski Remix).webm' -c copy -metadata 'description=Gesaffelstein - Viol (Brodinski Remix)

http://wearepoppies.com
https://www.facebook.com/WEAREPOPPIES' -metadata 'title=Gesaffelstein - Viol (Brodinski Remix)' -metadata artist=Gesaffelstein -metadata date=20120123 -metadata 'purl=https://www.youtube.com/watch?v=JSpKPsGoyHc' -metadata 'comment=Gesaffelstein - Viol (Brodinski Remix)

http://wearepoppies.com
https://www.facebook.com/WEAREPOPPIES' 'file:Gesaffelstein - Viol (Brodinski Remix).temp.webm'
[debug] avconv command line: avprobe -show_streams 'file:Gesaffelstein - Viol (Brodinski Remix).webm'
[ffmpeg] Destination: Gesaffelstein - Viol (Brodinski Remix).mp3
[debug] ffmpeg command line: avconv -y -i 'file:Gesaffelstein - Viol (Brodinski Remix).webm' -vn -acodec libmp3lame -q:a 0 'file:Gesaffelstein - Viol (Brodinski Remix).mp3'
Deleting original file Gesaffelstein - Viol (Brodinski Remix).webm (pass -k to keep)
[ffmpeg] Adding thumbnail to "Gesaffelstein - Viol (Brodinski Remix).mp3"
[debug] ffmpeg command line: avconv -y -i 'file:Gesaffelstein - Viol (Brodinski Remix).mp3' -i 'file:Gesaffelstein - Viol (Brodinski Remix).jpg' -c copy -map 0 -map 1 -metadata:s:v 'title="Album cover"' -metadata:s:v 'comment="Cover (Front)"' 'file:Gesaffelstein - Viol (Brodinski Remix).temp.mp3'
ERROR: file:Gesaffelstein - Viol (Brodinski Remix).jpg: No such file or directory
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/YoutubeDL.py", line 1791, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/postprocessor/embedthumbnail.py", line 50, in run
    self.run_ffmpeg_multiple_files([filename, thumbnail_filename], temp_filename, options)
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 168, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: file:Gesaffelstein - Viol (Brodinski Remix).jpg: No such file or directory


real	3m9.734s
user	2m24.550s
sys	0m8.960s
```

```
root@raspberrypi:/mnt/test # avconv -y -i 'file:Gesaffelstein - Viol (Brodinski Remix).mp3' -i 'file:Gesaffelstein - Viol (Brodinski Remix).jpg' -c copy -map 0 -map 1 -metadata:s:v 'title="Album cover"' -metadata:s:v 'comment="Cover (Front)"' 'file:Gesaffelstein - Viol (Brodinski Remix).temp.mp3'
avconv version 11.7-6:11.7-1~deb8u1+rpi1, Copyright (c) 2000-2016 the Libav developers
  built on Jun 17 2016 02:13:49 with gcc 4.9.2 (Raspbian 4.9.2-10)
[mp3 @ 0x1f52ca0] max_analyze_duration 5000000 reached
Guessed Channel Layout for  Input Stream #0.0 : stereo
Input #0, mp3, from 'file:Gesaffelstein - Viol (Brodinski Remix).mp3':
  Metadata:
    title           : Gesaffelstein - Viol (Brodinski Remix)
    encoder         : Lavf56.1.0
  Duration: 00:04:32.35, start: 0.000000, bitrate: 235 kb/s
    Stream #0.0: Audio: mp3, 44100 Hz, 2 channels, s16p, 235 kb/s
file:Gesaffelstein - Viol (Brodinski Remix).jpg: No such file or directory
```

```
root@raspberrypi:/mnt/test # avconv -y -i 'file:Gesaffelstein - Viol (Brodinski Remix).mp3' -i 'Gesaffelstein - Viol (Brodinski Remix).jpg' -c copy -map 0 -map 1 -metadata:s:v 'title="Album cover"' -metadata:s:v 'comment="Cover (Front)"' 'file:Gesaffelstein - Viol (Brodinski Remix).temp.mp3'
avconv version 11.7-6:11.7-1~deb8u1+rpi1, Copyright (c) 2000-2016 the Libav developers
  built on Jun 17 2016 02:13:49 with gcc 4.9.2 (Raspbian 4.9.2-10)
[mp3 @ 0x1ff5ca0] max_analyze_duration 5000000 reached
Guessed Channel Layout for  Input Stream #0.0 : stereo
Input #0, mp3, from 'file:Gesaffelstein - Viol (Brodinski Remix).mp3':
  Metadata:
    title           : Gesaffelstein - Viol (Brodinski Remix)
    encoder         : Lavf56.1.0
  Duration: 00:04:32.35, start: 0.000000, bitrate: 235 kb/s
    Stream #0.0: Audio: mp3, 44100 Hz, 2 channels, s16p, 235 kb/s
Input #1, image2, from 'Gesaffelstein - Viol (Brodinski Remix).jpg':
  Duration: 00:00:00.04, start: 0.000000, bitrate: N/A
    Stream #1.0: Video: mjpeg, yuvj420p, 480x360 [PAR 1:1 DAR 4:3], 25 tbn
Output #0, mp3, to 'file:Gesaffelstein - Viol (Brodinski Remix).temp.mp3':
  Metadata:
    TIT2            : Gesaffelstein - Viol (Brodinski Remix)
    TSSE            : Lavf56.1.0
    Stream #0.0: Audio: libmp3lame, 44100 Hz, stereo, 235 kb/s
    Stream #0.1: Video: mjpeg, yuvj420p, 480x360 [PAR 1:1 DAR 4:3], q=2-31, 25 tbn, 25 tbc
    Metadata:
      title           : "Album cover"
      comment         : "Cover (Front)"
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Press ctrl-c to stop encoding
frame=    1 fps=  0 q=-1.0 Lsize=    7849kB time=272.33 bitrate= 236.1kbits/s    
video:13kB audio:7835kB other streams:0kB global headers:0kB muxing overhead: 0.010577%
```

As you can see above there is a `file:` in the avconv input command that shouldn't be there.

**Comment by dstftw** [comment] 2016-07-18 14:25
avconv bug.
Duplicate of #7238.

**Closed by dstftw** 2016-07-18 14:25 UTC
