### ISSUE TITLE
Please report this issue

### ISSUE THREAD

**Issue by ChrisDate** [rg3/youtube-dl#10548] opened 2016-09-03 21:02 UTC
I got a warning saying "please report this issue", so here it is:

youtube-dl -t --verbose "https://www.youtube.com/watch?feature=player_detailpage&v=4G98sGv2NSU"

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-t', u'--verbose', u'https://www.youtube.com/watch?feature=player_detailpage&v=4G98sGv2NSU']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.03
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.5
[debug] exe versions: avconv 11.7-6, avprobe 11.7-6, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 4G98sGv2NSU: Downloading webpage
[youtube] 4G98sGv2NSU: Downloading video info webpage
[youtube] 4G98sGv2NSU: Extracting video information
[youtube] {43} signature length 46.40, html5 player en_US-vflqMMQzs
[youtube] {18} signature length 46.40, html5 player en_US-vflqMMQzs
[youtube] {36} signature length 46.40, html5 player en_US-vflqMMQzs
[youtube] {17} signature length 46.40, html5 player en_US-vflqMMQzs
[youtube] {135} signature length 46.40, html5 player en_US-vflqMMQzs
[youtube] {244} signature length 46.40, html5 player en_US-vflqMMQzs
[youtube] {134} signature length 46.40, html5 player en_US-vflqMMQzs
[youtube] {243} signature length 46.40, html5 player en_US-vflqMMQzs
[youtube] {133} signature length 46.40, html5 player en_US-vflqMMQzs
[youtube] {242} signature length 46.40, html5 player en_US-vflqMMQzs
[youtube] {160} signature length 46.40, html5 player en_US-vflqMMQzs
[youtube] {278} signature length 46.40, html5 player en_US-vflqMMQzs
[youtube] {140} signature length 46.40, html5 player en_US-vflqMMQzs
[youtube] {171} signature length 46.38, html5 player en_US-vflqMMQzs
[youtube] 4G98sGv2NSU: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vflqMMQzs/base.js
[youtube] {249} signature length 46.40, html5 player en_US-vflqMMQzs
[youtube] {250} signature length 46.40, html5 player en_US-vflqMMQzs
[youtube] {251} signature length 46.40, html5 player en_US-vflqMMQzs
[youtube] 4G98sGv2NSU: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vflqMMQzs/base.js
[youtube] 4G98sGv2NSU: Downloading MPD manifest
WARNING: [youtube] 4G98sGv2NSU: Skipping DASH manifest: ExtractorError(u'Failed to download MPD manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on u'https://r8---sn-cn3tc-aige.googlevideo.com/videoplayback?ei=VjbLV5PnF4P4WMHHgnA&itag=135&sparams=clen%2Cdur%2Cei%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&ms=au&mt=1472934878&dur=1390.466&mv=m&clen=20522888&ip=2a02%3Ac7d%3A7829%3A2d00%3Af5bb%3A53be%3A4a9%3A456d&initcwndbps=692500&gir=yes&mm=31&ipbits=0&mn=sn-cn3tc-aige&lmt=1427901444116238&gcr=gb&sver=3&upn=oCskbUSttgM&requiressl=yes&keepalive=yes&id=o-AEC5XM-hwTlfg0N0tnKEtwz0nEp2JvQmRxGk0ZagdF3G&expire=1472957110&source=youtube&mime=video%2Fmp4&pl=39&key=yt6&signature=38EDA307EFC4F6C14FC6A19A515ADC46759701AF.07997850755FF64D926167E49E8F3B1518D969F3&ratebypass=yes'
[download] Destination: Dirty chess tricks 9 (Grob's Attack)-4G98sGv2NSU.f135.mp4
[download] 100% of 19.57MiB in 02:20
[debug] Invoking downloader on u'https://r8---sn-cn3tc-aige.googlevideo.com/videoplayback?ei=VjbLV5PnF4P4WMHHgnA&itag=251&sparams=clen%2Cdur%2Cei%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&ms=au&mt=1472934878&dur=1390.541&mv=m&clen=23567094&ip=2a02%3Ac7d%3A7829%3A2d00%3Af5bb%3A53be%3A4a9%3A456d&initcwndbps=692500&gir=yes&mm=31&ipbits=0&mn=sn-cn3tc-aige&lmt=1415082645485773&gcr=gb&sver=3&upn=oCskbUSttgM&requiressl=yes&keepalive=yes&id=o-AEC5XM-hwTlfg0N0tnKEtwz0nEp2JvQmRxGk0ZagdF3G&expire=1472957110&source=youtube&mime=audio%2Fwebm&pl=39&key=yt6&signature=25CACAEE2128B7CEA9871FFD831306F13B66539C.5A9C3832BAA1974FEA48E1DB90AE0FDA8B5D0A12&ratebypass=yes'
[download] Destination: Dirty chess tricks 9 (Grob's Attack)-4G98sGv2NSU.f251.webm
[download] 100% of 22.48MiB in 02:47
[ffmpeg] Merging formats into "Dirty chess tricks 9 (Grob's Attack)-4G98sGv2NSU.mkv"
[debug] ffmpeg command line: avconv -y -i 'file:Dirty chess tricks 9 (Grob'"'"'s Attack)-4G98sGv2NSU.f135.mp4' -i 'file:Dirty chess tricks 9 (Grob'"'"'s Attack)-4G98sGv2NSU.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:Dirty chess tricks 9 (Grob'"'"'s Attack)-4G98sGv2NSU.temp.mkv'
Deleting original file Dirty chess tricks 9 (Grob's Attack)-4G98sGv2NSU.f135.mp4 (pass -k to keep)
Deleting original file Dirty chess tricks 9 (Grob's Attack)-4G98sGv2NSU.f251.webm (pass -k to keep)

**Comment by dstftw** [comment] 2016-09-03 21:07
Duplicate of #8944.

**Closed by dstftw** 2016-09-03 21:07 UTC
