### ISSUE TITLE
Problem with download from cda.pl the biggest move site in Poland

### ISSUE THREAD

**Issue by knittos** [rg3/youtube-dl#17853] opened 2018-10-10 12:08 UTC
Hello, is some problem with downloading from cda.pl.
Example:
https://www.cda.pl/video/91059fb   
```
macbook-pro-marcin:prod knittos$ youtube-dl --version
2018.10.05
macbook-pro-marcin:prod knittos$ youtube-dl https://www.cda.pl/video/91059fb
[CDA] 91059fb: Downloading webpage
ERROR: unable to download video data: HTTP Error 403: Forbidden
macbook-pro-marcin:prod knittos$ youtube-dl https://www.cda.pl/video/91059fb  --force-generic-extractor
[generic] 91059fb: Requesting header
WARNING: Forcing on generic information extractor.
[generic] 91059fb: Downloading webpage
[generic] 91059fb: Extracting information
ERROR: Unsupported URL: https://www.cda.pl/video/91059fb
macbook-pro-marcin:prod knittos$ 
```   
Maybe I do something wrong?

**Comment by remitamine** [comment] 2018-10-10 15:44
Duplicate of #17803.

**Closed by remitamine** 2018-10-10 15:44 UTC
