### ISSUE TITLE
[8tracks]Error downloading the song information of a big playlist

### ISSUE THREAD

**Issue by pauloat** [rg3/youtube-dl#5278] opened 2015-03-24 20:26 UTC
$ youtube-dl --verbose http://8tracks.com/spacebunnysounds/after-hour-space-lair-groovin
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://8tracks.com/spacebunnysounds/after-hour-space-lair-groovin']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.18
[debug] Python version 2.7.6 - Linux-3.13.0-24-generic-i686-with-LinuxMint-17-qiana
[debug] exe versions: none
[debug] Proxy map: {}
[8tracks] after-hour-space-lair-groovin: Downloading webpage
[8tracks] after-hour-space-lair-groovin: Downloading song information 1/23
[8tracks] after-hour-space-lair-groovin: Downloading song information 2/23
[8tracks] after-hour-space-lair-groovin: Downloading song information 3/23
[8tracks] after-hour-space-lair-groovin: Downloading song information 4/23
[8tracks] after-hour-space-lair-groovin: Downloading song information 5/23
[8tracks] after-hour-space-lair-groovin: Waiting for 182.173913043 seconds
[8tracks] after-hour-space-lair-groovin: Downloading song information 5/23
[8tracks] after-hour-space-lair-groovin: Downloading song information 6/23
[8tracks] after-hour-space-lair-groovin: Waiting for 182.173913043 seconds
[8tracks] after-hour-space-lair-groovin: Downloading song information 6/23
[8tracks] after-hour-space-lair-groovin: Downloading song information 7/23
[8tracks] after-hour-space-lair-groovin: Waiting for 182.173913043 seconds
[8tracks] after-hour-space-lair-groovin: Downloading song information 7/23
[8tracks] after-hour-space-lair-groovin: Downloading song information 8/23
[8tracks] after-hour-space-lair-groovin: Waiting for 182.173913043 seconds
[8tracks] after-hour-space-lair-groovin: Downloading song information 8/23
[8tracks] after-hour-space-lair-groovin: Downloading song information 9/23
[8tracks] after-hour-space-lair-groovin: Waiting for 182.173913043 seconds
[8tracks] after-hour-space-lair-groovin: Downloading song information 9/23
[8tracks] after-hour-space-lair-groovin: Downloading song information 10/23
[8tracks] after-hour-space-lair-groovin: Waiting for 182.173913043 seconds
[8tracks] after-hour-space-lair-groovin: Downloading song information 10/23
[8tracks] after-hour-space-lair-groovin: Downloading song information 11/23
[8tracks] after-hour-space-lair-groovin: Waiting for 182.173913043 seconds
[8tracks] after-hour-space-lair-groovin: Downloading song information 11/23
[8tracks] after-hour-space-lair-groovin: Downloading song information 12/23
[8tracks] after-hour-space-lair-groovin: Waiting for 182.173913043 seconds
[8tracks] after-hour-space-lair-groovin: Downloading song information 12/23
[8tracks] after-hour-space-lair-groovin: Downloading song information 13/23
[8tracks] after-hour-space-lair-groovin: Waiting for 182.173913043 seconds
[8tracks] after-hour-space-lair-groovin: Downloading song information 13/23
[8tracks] after-hour-space-lair-groovin: Downloading song information 14/23
[8tracks] after-hour-space-lair-groovin: Waiting for 182.173913043 seconds
[8tracks] after-hour-space-lair-groovin: Downloading song information 14/23
[8tracks] after-hour-space-lair-groovin: Waiting for 182.173913043 seconds
[8tracks] after-hour-space-lair-groovin: Downloading song information 14/23
[8tracks] after-hour-space-lair-groovin: Downloading song information 15/23
[8tracks] after-hour-space-lair-groovin: Waiting for 182.173913043 seconds
[8tracks] after-hour-space-lair-groovin: Downloading song information 15/23
[8tracks] after-hour-space-lair-groovin: Downloading song information 16/23
[8tracks] after-hour-space-lair-groovin: Waiting for 182.173913043 seconds
[8tracks] after-hour-space-lair-groovin: Downloading song information 16/23
[8tracks] after-hour-space-lair-groovin: Downloading song information 17/23
[8tracks] after-hour-space-lair-groovin: Waiting for 182.173913043 seconds
[8tracks] after-hour-space-lair-groovin: Downloading song information 17/23
[8tracks] after-hour-space-lair-groovin: Downloading song information 18/23
[8tracks] after-hour-space-lair-groovin: Waiting for 182.173913043 seconds
[8tracks] after-hour-space-lair-groovin: Downloading song information 18/23
[8tracks] after-hour-space-lair-groovin: Downloading song information 19/23
[8tracks] after-hour-space-lair-groovin: Waiting for 182.173913043 seconds
[8tracks] after-hour-space-lair-groovin: Downloading song information 19/23
[8tracks] after-hour-space-lair-groovin: Downloading song information 20/23
[8tracks] after-hour-space-lair-groovin: Waiting for 182.173913043 seconds
[8tracks] after-hour-space-lair-groovin: Downloading song information 20/23
[8tracks] after-hour-space-lair-groovin: Waiting for 182.173913043 seconds
[8tracks] after-hour-space-lair-groovin: Downloading song information 20/23
[8tracks] after-hour-space-lair-groovin: Waiting for 182.173913043 seconds
[8tracks] after-hour-space-lair-groovin: Downloading song information 20/23
[8tracks] after-hour-space-lair-groovin: Downloading song information 21/23
[8tracks] after-hour-space-lair-groovin: Waiting for 182.173913043 seconds
[8tracks] after-hour-space-lair-groovin: Downloading song information 21/23
ERROR: An extractor error has occured. (caused by KeyError(u'id',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/eighttracks.py", line 146, in _real_extract
    'id': compat_str(track_data['id']),
KeyError: u'id'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 654, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 281, in extract
    raise ExtractorError('An extractor error has occured.', cause=e)
ExtractorError: An extractor error has occured. (caused by KeyError(u'id',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment] 2015-12-09 18:58
Duplicate of #5029.

**Closed by dstftw** 2015-12-09 18:58 UTC
