### ISSUE TITLE
Dailymotion RegexNotFoundError

### ISSUE THREAD

**Issue by Westonfrontier** [rg3/youtube-dl#6316] opened 2015-07-21 12:16 UTC
Hi All
Dailymotion downloads were working last week. Not working this week.
youtube-dl version 2015.07.18
Any advice to solve this will be appreciated.

Error follows:

youtube-dl --verbose -t http://www.dailymotion.com/video/x2wmpdn_counting-cars-season-4-episode-12-dont-tell-danny-720p-hd_shortfilms
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-t', u'http://www.dailymotion.com/video/x2wmpdn_counting-cars-season-4-episode-12-dont-tell-danny-720p-hd_shortfilms']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2015.07.18
[debug] Python version 2.7.6 - Linux-3.13.0-29-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.13-6, avprobe 9.13-6, rtmpdump 2.4
[debug] Proxy map: {}
[dailymotion] x2wmpdn: Downloading webpage
[dailymotion] x2wmpdn: Extracting information
[dailymotion] x2wmpdn: Downloading embed page
ERROR: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 656, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 120, in _real_extract
    'video info', flags=re.MULTILINE)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 557, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment] 2015-07-21 18:06
Duplicate of #6151.

**Closed by dstftw** 2015-07-21 18:06 UTC
