### ISSUE TITLE
Facebook HD unavailable

### ISSUE THREAD

**Issue by Piokaz** [rg3/youtube-dl#8222] opened 2016-01-13 15:49 UTC
I don't know when this appeared, but we can't download HD version anymore from facebook videos.

Video example : https://www.facebook.com/video.php?v=957955867617029

```
youtube-dl --list-formats "https://www.facebook.com/video.php?v=957955867617029"
[facebook] 957955867617029: Downloading webpage
[info] Available formats for 957955867617029:
format code                      extension  resolution note
progressive_sd_src               mp4        unknown    
progressive_sd_src_no_ratelimit  mp4        unknown    (best)
```

**Comment by yan12125** [comment] 2016-02-01 10:32
Thanks for the report. Facebook HD videos will be available in the next version.

**Comment by yan12125** [comment] 2016-02-01 10:43
Currently the highest quality video is not selected automatically. Please use the following command the download it before the problem is fixed:
```
youtube-dl -v -f 474346612748657v "https://www.facebook.com/video.php?v=957955867617029"
```

**Comment by elartix** [comment] 2016-02-03 19:25
I have the same issue

![image](https://cloud.githubusercontent.com/assets/1899626/12794197/92dc7d5e-cabc-11e5-8051-9a6b68d67190.png)

**Comment by yan12125** [comment] 2016-02-03 19:43
22/17/18 itag codes are applicable for YouTube only. Facebook has its own format id system. There are still some flaws in youtube-dl now. Before all problems are fixed, use the following command to download the highest quality video:
```
youtube-dl -f bestvideo+bestaudio/best https://facebook.com/1240419485987237
```
You'll need ffmpeg for merging video and audio files.

**Comment by Piokaz** [comment] 2016-02-04 12:14
Thanks for the update.
The different format ID for each video might be a problem for an automated script, but i'll stick with the _**-f bestvideo+bestaudio/best**_ until it's back to a fixed format code, thanks :)

**Comment by yan12125** [comment] 2016-03-15 18:57
Since #8513 (thanks to @remitamine) is merged, Facebook DASH formats support is completed.

**Closed by yan12125** 2016-03-15 18:57 UTC
Labels: request
