### ISSUE TITLE
mp4 recode broken

### ISSUE THREAD

**Issue by EricBelanger** [rg3/youtube-dl#1027] opened 2013-07-11 16:11 UTC
Recoding the video to mp4 using ffmpeg doesn't work:

$ youtube-dl --recode-video=mp4 http://www.youtube.com/watch?v=iiFWoXQPOJc
[youtube] Setting language
[youtube] iiFWoXQPOJc: Downloading video webpage
[youtube] iiFWoXQPOJc: Downloading video info webpage
[youtube] iiFWoXQPOJc: Extracting video information
[download] Destination: Work Done by Isothermic Process-iiFWoXQPOJc.flv
[download] 100.0% of 21.94MiB at 864.23KiB/s ETA 00:00
[ffmpeg] Converting video from flv to mp4, Destination: Work Done by Isothermic Process-iiFWoXQPOJc.mp4
ERROR: The encoder 'aac' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.

**Comment by DavidS** [comment] 2015-09-06 10:21
This is still happening:

```
david@zion:/net/Multimedia/Movies/yt$ youtube-dl --recode-video=mp4 https://www.youtube.com/watch?v=DDDD --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--recode-video=mp4', u'https://www.youtube.com/watch?v=DDDD', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 2.7.10 - Linux-4.1.0-1-amd64-x86_64-with-debian-stretch-sid
[debug] exe versions: avconv 11.4-6, avprobe 11.4-6, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] DDDD: Downloading webpage
[youtube] DDDD: Extracting video information
[youtube] DDDD: Downloading DASH manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] DDDD.mkv has already been downloaded and merged
[ffmpeg] Converting video from mkv to mp4, Destination: DDDD.mp4
[debug] ffmpeg command line: avconv -y -i 'DDDD.mkv' 'DDDD.mp4'
ERROR: Add '-strict experimental' if you want to use it.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1548, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 302, in run
    self.run_ffmpeg(path, outpath, [])
  File "/usr/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 152, in run_ffmpeg
    self.run_ffmpeg_multiple_files([path], out_path, opts)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 148, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError

david@zion:/net/Multimedia/Movies/yt$ 
```

This is a pretty current Debian testing:

```
david@zion:~$ avconv -version
avconv version 11.4-6:11.4-2, Copyright (c) 2000-2014 the Libav developers
  built on Jun  3 2015 22:51:42 with gcc 4.9.2 (Debian 4.9.2-19)
avconv 11.4-6:11.4-2
libavutil     54.  3. 0 / 54.  3. 0
libavcodec    56.  1. 0 / 56.  1. 0
libavformat   56.  1. 0 / 56.  1. 0
libavdevice   55.  0. 0 / 55.  0. 0
libavfilter    5.  0. 0 /  5.  0. 0
libavresample  2.  1. 0 /  2.  1. 0
libswscale     3.  0. 0 /  3.  0. 0
david@zion:~$ youtube-dl --version
2015.06.04.1
david@zion:~$ 
```

running the recoding step manually with `avconv -y -i 'DDDD.mkv' -strict experimental 'DDDD.mp4'` worked.

**Comment by yan12125** [comment] 2015-09-06 10:41
@DavidS I guess the following command works:
```
youtube-dl --recode-video=mp4 https://www.youtube.com/watch?v=DDDD --verbose --postprocessor-args "-strict experimental"
```

**Comment by Dashed** [comment] 2015-09-16 06:10
@yan12125 thanks. The following: `--postprocessor-args "-strict experimental"` fixed my issue:

```
ERROR: audio conversion failed: Or use the non experimental encoder 'libfaac'.
```

**Comment by yan12125** [comment] 2015-09-16 07:41
Closing as the problem is solved with the newly added flag ```--postprocessor-args```. Feel free to open a new issue if the problem is still when the flag mentioned above is used.

**Closed by yan12125** 2015-09-16 07:41 UTC
Labels: postprocessors

**Comment by Dashed** [comment] 2015-09-16 07:53
I wasn't sure how to resolve the error at first.

Perhaps, `youtube-dl` should suggest resolving using `--postprocessor-args` flagg?

**Comment by yan12125** [comment] 2016-04-15 17:23
```experimental``` indicates that the feature should not be enabled by default. By the way, in the latest ffmpeg, aac encoder is no longer marked as experimental. [1] You may want to upgrade ffmpeg.

[1] http://ffmpeg.org/index.html#aac_encoder_stable

**Comment by faxotherapy** [comment] 2016-10-17 21:18
for unknown reasons to me, I now get the following error:
```
ERROR: audio conversion failed: Or use the non experimental encoder 'libfaac'.
```
I had no problem in the past. How can I circumvent this? If I use `mp3`, it works. I would like to use either `m4a` or `aac`, but none of them work.

**Comment by yan12125** [comment] 2016-10-18 04:59
@faxotherapy Upgrade your ffmpeg or use the command in https://github.com/rg3/youtube-dl/issues/1027#issuecomment-140639755

**Comment by chibicode** [comment] 2016-12-05 19:02
I used `homebrew` to install `ffmpeg`, so this worked for me:

```
# Reinstall ffmpeg with faac support
brew reinstall ffmpeg --with-faac

# Convert using --prefer-ffmpeg
youtube-dl -x ... --audio-format m4a --prefer-ffmpeg
```
