### ISSUE TITLE
ValueError: Unknown url type

### ISSUE THREAD

**Issue by VXeonix** [rg3/youtube-dl#11916] opened 2017-01-31 14:09 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.29*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

B:\Thomas's documents\Documents\Youtube-dl>youtube-dl https://www.youtube.com/watch?v=TbsBEb1ZxWA -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=TbsBEb1ZxWA', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.01.29
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] TbsBEb1ZxWA: Downloading webpage
[youtube] TbsBEb1ZxWA: Downloading video info webpage
[youtube] TbsBEb1ZxWA: Extracting video information
WARNING: unable to extract uploader nickname
[youtube] {22} signature length 42.43, html5 player en_US-vflV3n15C
[youtube] TbsBEb1ZxWA: Downloading player /yts/jsbin/player-en_US-vflV3n15C/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 1057, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 971, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 529, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 436, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 416, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\YoutubeDL.py", line 2000, in urlopen
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\utils.py", line 525, in sanitized_Request
  File "C:\Python\Python34\lib\urllib\request.py", line 267, in __init__
  File "C:\Python\Python34\lib\urllib\request.py", line 293, in full_url
  File "C:\Python\Python34\lib\urllib\request.py", line 322, in _parse
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 1057, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 971, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 529, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 436, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 416, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\YoutubeDL.py", line 2000, in urlopen
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\utils.py", line 525, in sanitized_Request
  File "C:\Python\Python34\lib\urllib\request.py", line 267, in __init__
  File "C:\Python\Python34\lib\urllib\request.py", line 293, in full_url
  File "C:\Python\Python34\lib\urllib\request.py", line 322, in _parse
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 1057, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 971, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 529, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 436, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 416, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\YoutubeDL.py", line 2000, in urlopen
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\utils.py", line 525, in sanitized_Request
  File "C:\Python\Python34\lib\urllib\request.py", line 267, in __init__
  File "C:\Python\Python34\lib\urllib\request.py", line 293, in full_url
  File "C:\Python\Python34\lib\urllib\request.py", line 322, in _parse
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 369, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 1646, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 1067, in _decrypt_signature
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 1057, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 971, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 529, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 436, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 416, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\YoutubeDL.py", line 2000, in urlopen
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\utils.py", line 525, in sanitized_Request
  File "C:\Python\Python34\lib\urllib\request.py", line 267, in __init__
  File "C:\Python\Python34\lib\urllib\request.py", line 293, in full_url
  File "C:\Python\Python34\lib\urllib\request.py", line 322, in _parse
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

B:\Thomas's documents\Documents\Youtube-dl>

### Description of your *issue*, suggested solution and other information

When I try downloading videos sometimes I get this error that says "unknown url type"
I read the FAQ and bugs sections, I also couldn't find anything on google.

What is causing this and how can I fix it?

Please note that this is the first time I'm using youtube-dl
I could download another video just fine.

**Comment by jaydenkieran** [comment] 2017-01-31 14:16
Duplicate of #11890

**Closed** 2017-01-31 15:23 UTC
