### ISSUE TITLE
[ctv.ca] Error: Conversion failed!

### ISSUE THREAD

**Issue by jnbdz** [rg3/youtube-dl#13373] opened 2017-06-13 16:09 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.12*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.12**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v http://www.ctv.ca/The-Tonight-Show-Starring-Jimmy-Fallon/Video/S4E155-Clips-Demi-Moores-Helium-Interview-vid1145280
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.ctv.ca/The-Tonight-Show-Starring-Jimmy-Fallon/Video/S4E155-Clips-Demi-Moores-Helium-Interview-vid1145280']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.06.12
[debug] Python version 2.7.12 - Linux-4.4.0-72-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[9c9media] 1145280: Downloading JSON metadata
[9c9media] 1145280: Downloading JSON metadata
[9c9media] 1565444: Downloading JSON metadata
[download] Downloading playlist: Clips: Demi Moore's Helium Interview
[BellMedia] playlist Clips: Demi Moore's Helium Interview: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Using fake IP 99.243.149.153 (CA) as X-Forwarded-For.
[9c9media:stack] 4633919: Downloading m3u8 information
[9c9media:stack] 4633919: Downloading f4m manifest
[debug] Invoking downloader on u'http://pe-ak-vp09a-9c9media.akamaized.net/origin/ae/2017-06-13/5C6543F5AEFD467E/hls/00010201/a6453a45b87303bd/index/07683e61/ctv/stream/h264/v1/2048000/manifest.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 73
[download] Destination: Clips - Demi Moore's Helium Interview-4633919.fhls-2048.mp4
[download] 100% of 73.36MiB in 00:17
[debug] Invoking downloader on u'http://pe-ak-vp09a-9c9media.akamaized.net/origin/ae/2017-06-13/5C6543F5AEFD467E/hls/00010201/a6453a45b87303bd/index/07683e61/ctv/stream/aac/v2/96000/manifest.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 73
[download] Destination: Clips - Demi Moore's Helium Interview-4633919.faac_96000-English.mp4
[download] 100% of 3.32MiB in 00:08
[ffmpeg] Merging formats into "Clips - Demi Moore's Helium Interview-4633919.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:Clips - Demi Moore'"'"'s Helium Interview-4633919.fhls-2048.mp4' -i 'file:Clips - Demi Moore'"'"'s Helium Interview-4633919.faac_96000-English.mp4' -c copy -map 0:v:0 -map 1:a:0 'file:Clips - Demi Moore'"'"'s Helium Interview-4633919.temp.mp4'
ERROR: Conversion failed!
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1965, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 479, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 204, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError: Conversion failed!
...
<end of log>
```

---

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

I was still able to get 3 files:

* Clips - Demi Moore's Helium Interview-4633919.faac_96000-English.mp4
* Clips - Demi Moore's Helium Interview-4633919.fhls-2048.mp4
* Clips - Demi Moore's Helium Interview-4633919.temp.mp4

**Comment by dstftw** [comment] 2017-06-13 16:24
Duplicate of #9913.

**Closed by dstftw** 2017-06-13 16:24 UTC
