### ISSUE TITLE
[mixcloud] Can't download all titles of an uploader

### ISSUE THREAD

**Issue by Nothing4You** [rg3/youtube-dl#3750] opened 2014-09-14 13:41 UTC
user@sandbox:~/deejaycorehead$ youtube-dl --proxy 'user:pass@host:port' --add-metadata http://mixcloud.com/deejaycorehead/
[debug] System config: []
[debug] User config: ['-v']
[debug] Command-line args: ['--proxy', 'user:pass@host:port', '--add-metadata', 'http://mixcloud.com/deejaycorehead/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.09.12
[debug] Python version 2.7.3 - Linux-2.6.32-openvz-042stab083.2-amd64-x86_64-with-debian-7.6
[debug] Proxy map: {u'http': 'user:pass@host:port', u'https': 'user:pass@host:port'}
[generic] deejaycorehead: Requesting header
[redirect] Following redirect to http://www.mixcloud.com/deejaycorehead/
[generic] deejaycorehead: Requesting header
WARNING: Falling back on generic information extractor.
[generic] deejaycorehead: Downloading webpage
[generic] deejaycorehead: Extracting information
ERROR: Unsupported URL: http://www.mixcloud.com/deejaycorehead/; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 545, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1472, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1643, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1507, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 5, column 4555
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 523, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 178, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 890, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.mixcloud.com/deejaycorehead/; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by dstftw** [comment] 2015-10-25 13:59
Duplicate of #5272.

**Closed by dstftw** 2015-10-25 13:59 UTC
Labels: request
