### ISSUE TITLE
v live download error

### ISSUE THREAD

**Issue by girlsapink** [rg3/youtube-dl#11393] opened 2016-12-08 18:41 UTC
I downloaded and used v live video with youtube-dl, but the error did not occur from the moment and the download did not proceed
Please confirm.
When downloading, the following error is displayed.

[vlive] 18397: Downloading webpage
[vlive] 18397: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug
 . Make sure you are using the latest version; type  youtube-dl -U  to update. B
e sure to call youtube-dl with the --verbose flag and include its complete outpu
t.

Please use the youtube-dl to get v live download video.

**Comment by dstftw** [comment] 2016-12-08 18:43
Duplicate of #11383.

**Closed by dstftw** 2016-12-08 18:43 UTC

**Comment by girlsapink** [comment] 2016-12-08 18:45
Do not say duplication and ask me to find a solution.
