### ISSUE TITLE
Download fails with "HTTPError: HTTP Error 500: Internal Server Error" on valid download url

### ISSUE THREAD

**Issue by JasonGross** [rg3/youtube-dl#12012] opened 2017-02-07 22:45 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.07*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v --no-post-overwrites  -w -x --audio-format vorbis https://www.youtube.com/watch?v=rpOwTspdwkI
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--no-post-overwrites', u'-w', u'-x', u'--audio-format', u'vorbis', u'https://www.youtube.com/watch?v=rpOwTspdwkI']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.07
[debug] Python version 2.7.12 - Linux-4.4.0-38-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.10-0ubuntu0.16.04.1, ffprobe 2.8.10-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] rpOwTspdwkI: Downloading webpage
[youtube] rpOwTspdwkI: Downloading video info webpage
[youtube] rpOwTspdwkI: Extracting video information
[youtube] rpOwTspdwkI: Downloading MPD manifest
[debug] Invoking downloader on u'https://r1---sn-a8au-cvne.googlevideo.com/videoplayback?id=ae93b04eca5dc242&itag=171&source=youtube&requiressl=yes&mm=31&mn=sn-a8au-cvne&initcwndbps=9528750&ms=au&mv=m&pl=15&pcm2cms=yes&ratebypass=yes&mime=audio/webm&gir=yes&clen=8037794&lmt=1392297776770241&dur=739.081&key=dg_yt0&signature=0930920B7A080C4D8D4494CD03F53B1FFE797414.60DB7E4E00A76A0EFAFD6862AE1FA8A8D05141B6&mt=1486501344&upn=3eJx5k0nILU&ip=128.30.92.103&ipbits=0&expire=1486522987&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mn,initcwndbps,ms,mv,pl,pcm2cms,ratebypass,mime,gir,clen,lmt,dur'
[download] Resuming download at byte 6291408
[download] Got server HTTP error. Retrying (attempt 1 of 10)...
[download] Got server HTTP error. Retrying (attempt 2 of 10)...
[download] Got server HTTP error. Retrying (attempt 3 of 10)...
[download] Got server HTTP error. Retrying (attempt 4 of 10)...
[download] Got server HTTP error. Retrying (attempt 5 of 10)...
[download] Got server HTTP error. Retrying (attempt 6 of 10)...
[download] Got server HTTP error. Retrying (attempt 7 of 10)...
[download] Got server HTTP error. Retrying (attempt 8 of 10)...
[download] Got server HTTP error. Retrying (attempt 9 of 10)...
[download] Got server HTTP error. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2006, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: Internal Server Error
$
```

---

### Description of your *issue*, suggested solution and other information

I expect the dowload of [this url](https://www.youtube.com/watch?v=rpOwTspdwkI) to succeed, but it fails.

This seems similar to #3721, except that https://github.com/rg3/youtube-dl/issues/3721#issuecomment-55933487 mentions that the download url is invalid and that passing `-g` gives a `KeyError`, neither of which occurs for me (the audio plays fine from the download url, and `-g` does not give any error.)

**Comment by dstftw** [comment] 2017-02-08 02:14
Duplicate of #3721.

**Closed by dstftw** 2017-02-08 02:14 UTC
