### ISSUE TITLE
Problem downloading some videos (worked up till about a week ago - broken now)

### ISSUE THREAD

**Issue by joeschmoe40** [rg3/youtube-dl#7422] opened 2015-11-10 06:00 UTC
About half of the usual videos that I watch have stopped working - same error message.

Observe (the goal is to download the video for "We're all alone" by Boz Scaggs):
 
$ youtube-dl.py -U
youtube-dl is up-to-date (2015.11.02)
 $ youtube-dl.py --verbose -f best 'ytsearch:were all alone boz'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-f', u'best', u'ytsearch:were all alone boz']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.02
[debug] Python version 2.7.2 - Darwin-12.5.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:search] query "were all alone boz": Downloading page 1
[download] Downloading playlist: were all alone boz
[youtube:search] playlist were all alone boz: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[youtube] k-MsVZrTQEU: Downloading webpage
[youtube] k-MsVZrTQEU: Downloading video info webpage
[youtube] k-MsVZrTQEU: Extracting video information
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {22} signature length 40.44, html5 player None
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/Users/me/bin/youtube-dl.py/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/Users/me/bin/youtube-dl.py/youtube_dl/extractor/youtube.py", line 709, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/me/bin/youtube-dl.py/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/Users/me/bin/youtube-dl.py/youtube_dl/extractor/youtube.py", line 709, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/me/bin/youtube-dl.py/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/Users/me/bin/youtube-dl.py/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/Users/me/bin/youtube-dl.py/youtube_dl/extractor/youtube.py", line 1345, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/Users/me/bin/youtube-dl.py/youtube_dl/extractor/youtube.py", line 827, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/Users/me/bin/youtube-dl.py/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/Users/me/bin/youtube-dl.py/youtube_dl/extractor/youtube.py", line 709, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

 $ python --version
Python 2.7.2
 $ uname -a
Darwin macbook 12.5.0 Darwin Kernel Version 12.5.0: Sun Sep 29 13:33:47 PDT 2013; root:xnu-2050.48.12~1/RELEASE_X86_64 x86_64
$

Also note: Get same result if I omit "-f best".

**Comment by dstftw** [comment] 2015-11-10 06:47
Duplicate of #7413. This is already fixed and will be available in the next version.

**Closed by dstftw** 2015-11-10 06:47 UTC
