### ISSUE TITLE
udemy downloads are randomly saved to same folder

### ISSUE THREAD

**Issue by reallyawesomewe** [rg3/youtube-dl#10352] opened 2016-08-15 09:58 UTC
files are downloaded in same folder rather the downloading in a sub folders   2nd thing files articles are not getting downloaded in few videos 
![image](https://cloud.githubusercontent.com/assets/21035733/17661433/c390d6ce-62fc-11e6-8057-a410b61f8d76.png)
! can create a folder with that name and videos inside section can be saved there

**Comment by yan12125** [comment] 2016-08-15 10:09
Duplicate of #4793. There's an example command.

**Closed by yan12125** 2016-08-15 10:09 UTC
