### ISSUE TITLE
this app cant run on your pc

### ISSUE THREAD

**Issue by CSWood** [rg3/youtube-dl#8841] opened 2016-03-12 12:59 UTC
Using Windows 10 64 bit. 
I've just started using the windows exe version. It worked once to download one video - but the next time I tried I got the erorr message above. 
Quick bit of googling seems to suggest the user account may be corrupt and I should create another - trying to avoid the hassle of this.
Ideas anyone?

**Comment by dstftw** [comment] 2016-03-12 13:01
How did you run it? You must run it in from cmd.exe.

**Comment by CSWood** [comment] 2016-03-12 13:03
Yes I was running it in a command window. One time it worked next time I tried - doing exactly the same thing and I get the error

**Comment by dstftw** [comment] 2016-03-12 13:05
Post the full log of your command and the output.

**Comment by CSWood** [comment] 2016-03-12 13:09
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Colin>cd\Users\Colin\Google Drive\Lynda\youtubedl\

C:\Users\Colin\Google Drive\Lynda\youtubedl>"C:\Users\Colin\Google Drive\Lynda\youtubedl\youtube-dl .exe"
Access is denied.

C:\Users\Colin\Google Drive\Lynda\youtubedl>

**Comment by CSWood** [comment] 2016-03-12 13:13
I did not notice the if the Access denied warning was there when the problem first started. 
I tried creating a new user account and running it from their, which involved changing the folder ownership - which I've now swapped back to the original account. So the "Access denied" warning could possibly be something I've done after the original problem - but I don't think so.

**Comment by dstftw** [comment] 2016-03-12 13:19
Post the output of `whoami /all` from the same console.

**Comment by CSWood** [comment] 2016-03-12 15:19
C:\Users\Colin\Google Drive\Lynda\youtubedl>icacls youtube-dl.exe
youtube-dl.exe DESKTOP-19MQRNN\Colin:(I)(F)

Successfully processed 1 files; Failed processing 0 files

C:\Users\Colin\Google Drive\Lynda\youtubedl>icacls .
. DESKTOP-19MQRNN\Colin:(OI)(CI)(F)
  DESKTOP-19MQRNN\Colin2:(OI)(CI)(F)

Successfully processed 1 files; Failed processing 0 files

**Comment by dstftw** [comment] 2016-03-12 15:28
>Post the outputs of `whoami /all`

**Comment by CSWood** [comment] 2016-03-12 15:32
C:\Users\Colin\Google Drive\Lynda\youtubedl>whoami /all

USER INFORMATION
----------------

User Name             SID
===================== ==============================================
desktop-19mqrnn\colin S-1-5-21-3938280629-4170293975-3532197375-1001


GROUP INFORMATION
-----------------

Group Name                                                    Type             SID                                                                                                           Attributes
============================================================= ================ ============================================================================================================= ==================================================
Mandatory Label\Medium Mandatory Level                        Label            S-1-16-8192                              
Everyone                                                      Well-known group S-1-1-0                                                                                                       Mandatory group, Enabled by default, Enabled group
NT AUTHORITY\Local account and member of Administrators group Well-known group S-1-5-114                                                                                                     Group used for deny only
DESKTOP-19MQRNN\HomeUsers                                     Alias            S-1-5-21-3938280629-4170293975-3532197375-1003                                                                Mandatory group, Enabled by default, Enabled group
BUILTIN\Administrators                                        Alias            S-1-5-32-544                                                                                                  Group used for deny only
BUILTIN\Users                                                 Alias            S-1-5-32-545                                                                                                  Mandatory group, Enabled by default, Enabled group
NT AUTHORITY\INTERACTIVE                                      Well-known group S-1-5-4                                                                                                       Mandatory group, Enabled by default, Enabled group
CONSOLE LOGON                                                 Well-known group S-1-2-1                                                                                                       Mandatory group, Enabled by default, Enabled group
NT AUTHORITY\Authenticated Users                              Well-known group S-1-5-11                                                                                                      Mandatory group, Enabled by default, Enabled group
NT AUTHORITY\This Organization                                Well-known group S-1-5-15                                                                                                      Mandatory group, Enabled by default, Enabled group
MicrosoftAccount\c.wood@hhgsvle.org                           User             S-1-11-96-3623454863-58364-18864-2661722203-1597581903-3423480547-2442813942-1216018936-3346542984-1862901351 Mandatory group, Enabled by default, Enabled group
NT AUTHORITY\Local account                                    Well-known group S-1-5-113                                                                                                     Mandatory group, Enabled by default, Enabled group
LOCAL                                                         Well-known group S-1-2-0                                                                                                       Mandatory group, Enabled by default, Enabled group
NT AUTHORITY\Cloud Account Authentication                     Well-known group S-1-5-64-36                                                                                                   Mandatory group, Enabled by default, Enabled group


PRIVILEGES INFORMATION
----------------------

Privilege Name                Description                          State
============================= ==================================== ========
SeShutdownPrivilege           Shut down the system                 Disabled
SeChangeNotifyPrivilege       Bypass traverse checking             Enabled
SeUndockPrivilege             Remove computer from docking station Disabled
SeIncreaseWorkingSetPrivilege Increase a process working set       Disabled
SeTimeZonePrivilege           Change the time zone                 Disabled


C:\Users\Colin\Google Drive\Lynda\youtubedl>

**Comment by dstftw** [comment] 2016-03-12 16:16
Does it work if you run it as `youtube-dl.exe` without full path?

**Comment by CSWood** [comment] 2016-03-12 16:19
No, same error message as before..

**Comment by dstftw** [comment] 2016-03-12 16:28
Have you tried redownload youtube-dl/chkdsk/reboot?

**Comment by CSWood** [comment] 2016-03-12 17:00
Not yet, I'll give it a go.
Thanks

**Comment by CSWood** [comment] 2016-03-12 17:05
Brilliant - **THANKS**

Now I need to sort out how to use it properly. The command prompt window reported a successful download but no file appeared in the folder, and I can't see where it's been put.
One other thing - is there a switch that will make it download all the video files linked to on a particular page?

**Comment by dstftw** [comment] 2016-03-12 17:09
So what was the solution?
By default files appear in the current directory you are in.
There is no switch needed you just pass the URL.

**Comment by CSWood** [comment] 2016-03-12 17:22
Sorry, should have said after all your help.
I downloaded another copy of the file.
I no longer get the error message about the app not running - but there is no output. I'm also getting system messages about a faulty app causing problems and the default app for particular filetypes has been reset. Coupled with a redirect issue on my browser it all makes me think there must a virus on my system. I ran malwarebytes and ccleaner a couple of days ago to get rid of the redirect problem but it's still there somewhere. I might just format and reinstall.

I'm not using the downloader for youtube, it's another site, there are around fifty different videos on a page, I was hoping to download them all in one go rather than pasting in fifty different URL's

Thanks again for your help...

**Comment by dstftw** [comment] 2016-03-12 17:44
If these videos are embeds per se you may not be able to download them even when pasting URLs one by one since embed URLs may differ from regular ones.

**Comment by CSWood** [comment] 2016-03-12 18:02
No, they look like regular links. It's Lynda.com

**Comment by CSWood** [comment] 2016-03-12 18:05
The script now runs without error message - but there is no sign of the video is states has been downloaded?

**Comment by dstftw** [comment] 2016-03-12 22:08
**Post the full output of youtube-dl when run with `-v`**, i.e. **add** `-v` flag to **your command line**, copy the **whole** output and post it in the issue body wrapped in \`\`\` for better formatting. It should look similar to this:
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.06
[debug] Git HEAD: 135392e
[debug] Python version 2.6.6 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
```
**Do not post screenshots of verbose log only plain text is acceptable.**

The output (including the first lines) contains important debugging information. Issues without the full output are often not reproducible and therefore do not get solved in short order, if ever.

**Comment by CSWood** [comment] 2016-03-12 23:49
```Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Colin>cd\Users\Colin\Google Drive\Lynda\youtubedl\

C:\Users\Colin\Google Drive\Lynda\youtubedl>"C:\Users\Colin\Google Drive\Lynda\youtubedl\youtube-dl.exe" http://www.lynda.com/Python-tutorials/Reusing-code-function/62226/70927-4.html -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.lynda.com/Python-tutorials/Reusing-code-function/62226/70927-4.html', u'-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.03.06
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[lynda] 70927: Downloading video JSON
[lynda] 70927: Checking 1-540 video format URL
[lynda] 70927: Checking 1-360 video format URL
[lynda] 70927: Checking 0-540 video format URL
[lynda] 70927: Checking 0-360 video format URL
[lynda] 70927: Checking 2-540 video format URL
[lynda] 70927: Checking 2-360 video format URL
[debug] Invoking downloader on u'http://files2.lynda.com/secure/courses/62226/VBR_MP4h264_main_SD/62226_02_04_SC11_functions.mp4?c3.ri=5693234104547868801&hashval=1457840551_22126bd6137e079cfcbd90617a0a1c86'
[download] Destination: Reusing code with a function-70927.mp4
[download] 100% of 5.06MiB in 00:02 ```

**Comment by dstftw** [comment] 2016-03-12 23:51
>[download] 100% of 5.06MiB

**Comment by CSWood** [comment] 2016-03-12 23:56
The same message was shown earlier when nothing was downloaded - this particular download has actually worked. Not sure what is going on. Thanks for your help anyway - I don't need to know what the problem was, if it's now sorted itself out by itself then great...

**Comment by dstftw** [comment] 2016-03-12 23:58
When you get this message it's always something downloaded. Most likely you've just looked in wrong place.

**Comment by dstftw** [comment] 2016-03-12 23:59
Closing since OP issue is now resolved.

**Closed by dstftw** 2016-03-12 23:59 UTC
