### ISSUE TITLE
Bug: Can't download audio for a YouTube video: HTTP 410 Gone

### ISSUE THREAD

**Issue by starrychloe** [rg3/youtube-dl#9715] opened 2016-06-07 05:49 UTC
It plays in the browser.

```
C:\Users\Chloe\Music>youtube-dl --version
2016.06.03

C:\Users\Chloe\Music>youtube-dl -v -x https://www.youtube.com/watch?v=a-mFITcJQvo
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '-x', 'https://www.youtube.com/watch?v=a-mFITcJQvo']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.06.03
[debug] Python version 3.4.4 - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg 3.0.1, ffprobe 3.0.1
[debug] Proxy map: {}
[youtube] a-mFITcJQvo: Downloading webpage
[youtube] a-mFITcJQvo: Downloading video info webpage
[youtube] a-mFITcJQvo: Extracting video information
[youtube] {22} signature length 42.40, html5 player en_US-vflrmwhUy
[youtube] {43} signature length 42.40, html5 player en_US-vflrmwhUy
[youtube] {18} signature length 42.40, html5 player en_US-vflrmwhUy
[youtube] {5} signature length 42.40, html5 player en_US-vflrmwhUy
[youtube] {36} signature length 42.40, html5 player en_US-vflrmwhUy
[youtube] {17} signature length 42.40, html5 player en_US-vflrmwhUy
[youtube] {137} signature length 42.40, html5 player en_US-vflrmwhUy
[youtube] {248} signature length 42.40, html5 player en_US-vflrmwhUy
[youtube] {136} signature length 42.40, html5 player en_US-vflrmwhUy
[youtube] {247} signature length 42.40, html5 player en_US-vflrmwhUy
[youtube] {135} signature length 42.40, html5 player en_US-vflrmwhUy
[youtube] {244} signature length 42.40, html5 player en_US-vflrmwhUy
[youtube] {134} signature length 42.40, html5 player en_US-vflrmwhUy
[youtube] {243} signature length 42.40, html5 player en_US-vflrmwhUy
[youtube] {133} signature length 42.40, html5 player en_US-vflrmwhUy
[youtube] {242} signature length 42.40, html5 player en_US-vflrmwhUy
[youtube] {160} signature length 42.40, html5 player en_US-vflrmwhUy
[youtube] {278} signature length 42.40, html5 player en_US-vflrmwhUy
[youtube] {140} signature length 42.40, html5 player en_US-vflrmwhUy
[youtube] {171} signature length 42.40, html5 player en_US-vflrmwhUy
[youtube] {249} signature length 42.40, html5 player en_US-vflrmwhUy
[youtube] {250} signature length 42.40, html5 player en_US-vflrmwhUy
[youtube] {251} signature length 42.40, html5 player en_US-vflrmwhUy
[debug] Invoking downloader on 'https://r18---sn-ab5l6n7e.googlevideo.com/videoplayback?itag=251&sver=3&clen=15678929&expire=1465300007&gir=yes&pl=18&mt=1465278091&mime=audio%2Fwebm&upn=mfmPwmJg5y0&initcwndbps=1816250&keepalive=yes&requiressl=yes&nh=IgpwcjAxLmxnYTA3KgkxMjcuMC4wLjE&ipbits=0&sparams=clen%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&fexp=9416126%2C9416891%2C9422596%2C9428398%2C9431012%2C9433096%2C9433380%2C9433946%2C9435527%2C9435876%2C9437066%2C9437553&lmt=1413534290589385&key=yt6&ip=208.120.122.29&ms=au&mv=m&source=youtube&dur=772.541&id=o-AM80mXCret8JrjJypaS1NQdbwts-uxQd7ZfXlwqjtiw7&mn=sn-ab5l6n7e&mm=31&signature=4006D4316BB4E55D601288AA939D6280AE8DB8B5.4FC120529951C2E4BBAA6C924B7CF5DD9EF2AE26&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 410: Gone
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpjletvtok\build\youtube_dl\YoutubeDL.py", line 1644, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpjletvtok\build\youtube_dl\YoutubeDL.py", line 1586, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpjletvtok\build\youtube_dl\downloader\common.py", line 350, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpjletvtok\build\youtube_dl\downloader\http.py", line 58, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpjletvtok\build\youtube_dl\YoutubeDL.py", line 1946, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 410: Gone


C:\Users\Chloe\Music>
```

**Comment by yan12125** [comment] 2016-06-07 05:56
As you've mentioned it's a duplicate of #4532. Format 251 is reported to be existent but actually not on YouTube's server. There's currently no way to detect whether a file is really there or not without actual downloading. As a workaround, use:
```
youtube-dl -v -f 'bestvideo+171' "https://www.youtube.com/watch?v=a-mFITcJQvo" --keep-video
```

**Closed by yan12125** 2016-06-07 05:56 UTC
