### ISSUE TITLE
Download from Lynda.com with SSO login

### ISSUE THREAD

**Issue by linbynd** [rg3/youtube-dl#5636] opened 2015-05-07 01:48 UTC
If you have a corporate login where you actually autenticate to your corporate login to access your account at Lynda.com. Then how will you use it with lynda.com, The normal username:password option passed to the commandline does not log you in

**Comment by yan12125** [comment] 2015-05-07 04:41
A duplicate of #4888

**Closed by yan12125** 2015-05-07 04:41 UTC
