### ISSUE TITLE
problem downloading from vimeo

### ISSUE THREAD

**Issue by Klaus1189** [rg3/youtube-dl#9046] opened 2016-04-01 06:15 UTC
I tried to download some videos from vimeo and this is what I got:
```
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. Alle Rechte vorbehalten.

C:\...>youtube-dl -v -F https://vimeo.com/103350643
[debug] System config: []
[debug] User config: [u'-i', u'--proxy', u'']
[debug] Command-line args: [u'-v', u'-F', u'https://vimeo.com/103350643']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.03.27
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[vimeo] 103350643: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)> (caused by URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))
  File "youtube_dl\extractor\common.pyo", line 366, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1934, in urlopen
  File "urllib2.pyo", line 431, in open
  File "urllib2.pyo", line 449, in _open
  File "urllib2.pyo", line 409, in _call_chain
  File "youtube_dl\utils.pyo", line 864, in https_open
  File "urllib2.pyo", line 1197, in do_open
```

Am I doing something wrong?

**Comment by yan12125** [comment] 2016-04-01 07:36
Duplicate of #7309. A common cause is there are some expired certificates in your system. vimeo.com uses the following certificates:

- *.vimeo.com (01:C4:C3:0F:A8:7C:68:83:80:10:FB:AA:51:8E:41:18)
- DigiCert SHA2 Secure Server CA (01:FD:A3:EB:6E:CA:75:C8:88:43:8B:72:4B:CF:BC:91)
- DigiCert Global Root CA (08:3B:E0:56:90:42:46:B1:A1:75:6A:C9:59:91:C7:4A)

If any of certificates above is expired, Python fails to verify it. It's common if your system time is wrong. Another common cause reported in #7309 is that there are invalid certificates in the system store. Refer to https://github.com/rg3/youtube-dl/issues/7309#issuecomment-167414048 for detailed steps. Note the certificate to check here is "DigiCert SHA2 Secure Server CA" (make sure it's exactly the same) rather than Google ones.

**Closed by yan12125** 2016-04-01 07:36 UTC

**Comment by Klaus1189** [comment] 2016-04-01 07:49
I installed Win 10 Pro fresh four days ago.
I read the comment, but I don't know what I have to do. 
Can you please help me?

**Comment by yan12125** [comment] 2016-04-01 07:57
Sorry I have never used Win10 and I don't know where the certificate store is in Win10. [This](http://windows.microsoft.com/en-us/windows-vista/view-or-manage-your-certificates) may help.

**Comment by Klaus1189** [comment] 2016-04-01 09:24
I typed in  `certmgr.msc` and it opens, but I don't know what certificate I have to search?

**Comment by yan12125** [comment] 2016-04-01 09:33
Any of the following:

* DigiCert SHA2 Secure Server CA
* DigiCert Global Root CA

And check whether your system clock is in their valid interval.

**Comment by Klaus1189** [comment] 2016-04-01 09:37
I searched for:
```
DigiCert SHA2 Secure Server CA
DigiCert Global Root CA
```

but I didn't find anything. What am I doing wrong?

What do I have to check with the clock? I don't get it completely.

**Comment by yan12125** [comment] 2016-04-01 09:58
> I didn't find anything

There should be at least one. On Windows 7 "DigiCert Global Root CA" is in "Trusted Root Certification Authorities => Certificates" and "Third-Party Root Certification Authorities => Certificates". These certificates should come with Windows. If not, ask Microsoft guys.

As you said it's a fresh installation, this may be the answer: http://bugs.python.org/issue20916. In brief: Windows downloads necessary certificates the first time you visit the site in Internet Explorer.

**Comment by Klaus1189** [comment] 2016-04-01 10:41
That was it. I had to visit vimeo.com with Microsoft Edge.
Now it works. I'm a Firefox guy and don't use Microsoft and/or Google browsers, players, ...
Thank you for the help, even it was such a little thing.

**Comment by yan12125** [comment] 2016-04-01 11:04
Thanks for helping identifying the problem. It should help others on Windows Vista or above.
