### ISSUE TITLE
ERROR: unable to download video data: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by arielch** [rg3/youtube-dl#6483] opened 2015-08-06 19:01 UTC
I'm getting this error with several videos, for example 00F2LBh4bd8
youtube-dl --version
2015.07.28

youtube-dl --verbose https://www.youtube.com/watch?v=00F2LBh4bd8
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=00F2LBh4bd8']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.28
[debug] Python version 2.7.8 - Linux-4.0.8-200.fc21.x86_64-x86_64-with-fedora-21-Twenty_One
[debug] exe versions: ffmpeg 2.4.10, ffprobe 2.4.10
[debug] Proxy map: {}
[youtube] 00F2LBh4bd8: Downloading webpage
[youtube] 00F2LBh4bd8: Downloading video info webpage
[youtube] 00F2LBh4bd8: Extracting video information
[youtube] {22} signature length 41.43, html5 player new
[youtube] {43} signature length 41.43, html5 player new
[youtube] {18} signature length 41.43, html5 player new
[youtube] {5} signature length 41.43, html5 player new
[youtube] {36} signature length 41.43, html5 player new
[youtube] {17} signature length 41.43, html5 player new
[youtube] {136} signature length 41.43, html5 player new
[youtube] {247} signature length 41.43, html5 player new
[youtube] {135} signature length 41.43, html5 player new
[youtube] {244} signature length 41.43, html5 player new
[youtube] {134} signature length 41.43, html5 player new
[youtube] {243} signature length 41.43, html5 player new
[youtube] {133} signature length 41.43, html5 player new
[youtube] {242} signature length 41.43, html5 player new
[youtube] {160} signature length 41.43, html5 player new
[youtube] {278} signature length 41.43, html5 player new
[youtube] {140} signature length 41.43, html5 player new
[youtube] {171} signature length 41.43, html5 player new
[youtube] 00F2LBh4bd8: Downloading DASH manifest
WARNING: [youtube] 00F2LBh4bd8: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[debug] Invoking downloader on u'https://r8---sn-j5cax8pnpvo-x1xy.googlevideo.com/videoplayback?source=youtube&keepalive=yes&mime=video%2Fmp4&expire=1438909147&itag=136&sparams=clen%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&fexp=9408710%2C9415006%2C9415365%2C9415435%2C9415485%2C9416126%2C9416372%2C9416729%2C9417721%2C9418059%2C9418153&initcwndbps=1363750&sver=3&requiressl=yes&pl=21&ipbits=0&key=yt5&ip=181.166.5.160&id=o-ABKLV_DCkxb3dEYyzpT5c5plfZpkTm7v3YONnLu2ctCJ&upn=82waLTleu2c&dur=180.013&mm=31&mn=sn-j5cax8pnpvo-x1xy&gir=yes&clen=3385943&lmt=1432274291017627&ms=au&mt=1438887412&mv=m&signature=245445E9DAF1139CAA21C236CC1D4C1646440FB4310.D204ABF2250E5812E2CB7BF253ADBA76040027A57&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/ariel/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1430, in process_info
    partial_success = dl(fname, new_info)
  File "/home/ariel/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1378, in dl
    return fd.download(name, info)
  File "/home/ariel/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/home/ariel/bin/youtube-dl/youtube_dl/downloader/http.py", line 59, in real_download
    data = self.ydl.urlopen(request)
  File "/home/ariel/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1732, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden

**Comment by dstftw** [comment] 2015-08-06 19:03
Duplicate of #6451. Remove cache: `--rm-cache-dir`.

**Closed by dstftw** 2015-08-06 19:03 UTC
