### ISSUE TITLE
Download from Pluralsight is broken

### ISSUE THREAD

**Issue by lucamerolla** [rg3/youtube-dl#11230] opened 2016-11-18 06:43 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.18*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.18**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.11.18
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by lucamerolla** [comment] 2016-11-18 06:44
youtube-dl --sleep-interval 60 --max-sleep-interval 100 --verbose --username PRIVATE --password PRIVATE https://app.pluralsight.com/library/courses/spark-kafka-cassandra-applying-lambda-architecture
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--sleep-interval', u'60', u'--max-sleep-interval', u'100', u'--verbose', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'https://app.pluralsight.com/library/courses/spark-kafka-cassandra-applying-lambda-architecture']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.18
[debug] Python version 2.7.12 - Linux-4.4.0-45-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.8-0ubuntu0.16.04.1, ffprobe 2.8.8-0ubuntu0.16.04.1
[debug] Proxy map: {}
[pluralsight:course] spark-kafka-cassandra-applying-lambda-architecture: Downloading course JSON
[pluralsight:course] spark-kafka-cassandra-applying-lambda-architecture: Downloading course data JSON
[download] Downloading playlist: Applying the Lambda Architecture with Spark, Kafka, and Cassandra
[pluralsight:course] playlist Applying the Lambda Architecture with Spark, Kafka, and Cassandra: Collected 72 video ids (downloading 72 of them)
[download] Downloading video 1 of 72
[pluralsight] Downloading login page
[pluralsight] Logging in as PRIVATE
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 356, in extract
    self.initialize()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 350, in initialize
    self._real_initialize()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/pluralsight.py", line 59, in _real_initialize
    self._login()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/pluralsight.py", line 95, in _login
    raise ExtractorError('Unable to log in')
ExtractorError: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by khushil** [comment] 2016-11-18 12:17
Getting the same here.

**Comment by siddht1** [comment] 2016-11-18 12:35
it works for me, verify if you can login from web and are able to open it.  your description also says its unable to open any url so try some other site too ,run using python2 __main__.py and python3  __main__.py  also

**Comment by lucamerolla** [comment] 2016-11-18 19:00
1. I'm able to connect via browser
2. youtube-dl "http://www.youtube.com/watch?v=P9pzm5b6FFY" works
3. I have run it also with python3 and I get the same error on the pluralsight
`youtube-dl --sleep-interval 60 --max-sleep-interval 100 --verbose --username PRIVATE --password PRIVATE https://app.pluralsight.com/library/courses/spark-kafka-cassandra-applying-lambda-architecture
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--sleep-interval', '60', '--max-sleep-interval', '100', '--verbose', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://app.pluralsight.com/library/courses/spark-kafka-cassandra-applying-lambda-architecture']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.18
[debug] Python version 3.5.2 - Linux-4.4.0-47-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.8-0ubuntu0.16.04.1, ffprobe 2.8.8-0ubuntu0.16.04.1
[debug] Proxy map: {}
[pluralsight:course] spark-kafka-cassandra-applying-lambda-architecture: Downloading course JSON
[pluralsight:course] spark-kafka-cassandra-applying-lambda-architecture: Downloading course data JSON
[download] Downloading playlist: Applying the Lambda Architecture with Spark, Kafka, and Cassandra
[pluralsight:course] playlist Applying the Lambda Architecture with Spark, Kafka, and Cassandra: Collected 72 video ids (downloading 72 of them)
[download] Downloading video 1 of 72
[pluralsight] Downloading login page
[pluralsight] Logging in as PRIVATE
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 356, in extract
    self.initialize()
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 350, in initialize
    self._real_initialize()
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/pluralsight.py", line 59, in _real_initialize
    self._login()
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/pluralsight.py", line 95, in _login
    raise ExtractorError('Unable to log in')
youtube_dl.utils.ExtractorError: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`

**Comment by dstftw** [comment] 2016-11-18 19:08
For any further investigations you have to provide credentials of account capable to access the course.

**Comment by siddht1** [comment] 2016-11-19 03:48
@lucamerolla   use it as   youtube-dl  -u [username] -p [password] -v -i https://app.pluralsight.com/library/courses/spark-kafka-cassandra-applying-lambda-architecture

i understand that you cannot provide user name,passwords for misuse of your account  .   I`m sure it will work as providing with a correct username,password will work. your log shows it fails to login , so correct it and retry and also check wheter your account is active or you missed some steps while creating account .

**Comment by siddht1** [comment] 2016-11-19 03:50
@lucamerolla   if its a free account type , it will fail .  for yearly or monthly account it will work

**Comment by khushil** [comment] 2016-11-19 17:40
Interestingly I don't think this works unless you're an individual subscriber. If you're part of a corp account I don't think this works.

**Comment by lucamerolla** [comment] 2016-11-19 17:50
Indeed, that's a corp account. Probably after the login it is redirected to a different page and there is an assertion in the code that is not met. 

I checked in the code the LOGIN page is
- https://app.pluralsight.com/id
while probably it should be (at least for corp account)
- https://app.pluralsight.com/id?redirectTo=/courses/spark-kafka-cassandra-applying-lambda-architecture

**Comment by siddht1** [comment] 2016-11-20 09:41
Yes , that may be the issue . I was able to login as I had a will user account. But still the video should be able to download . It would be worth a try to uSe the same commands once again in your office premises so that it can be verified there is a blockage of usuage other than your corp domains

**Comment by maniplus24** [comment] 2016-11-24 17:18
getting the same here, but I have individual account, if I mistype the username the error is INVALID USERNAME , but I get UNABLE to login, and I can see the videos in the browser.

**Comment by metafaniel** [comment] 2017-02-22 18:30
@siddht1 Same is happening to me with latest version: 2017.02.22
I have a Pluralsight Free Trial account, so you say it will fail because of this? It's a shame! =/

**Comment by tbaragao** [comment] 2017-03-08 14:17
Until yesterday I was able to download, but today started with that mistake.

**Comment by tbaragao** [comment] 2017-03-08 14:20
I solved my problem.

I joined this link: https://app.pluralsight.com/id

After I entered the login and password it displayed an accepted canvas of the terms. I accepted the terms.

After that it worked again

**Comment by dstftw** [comment] 2017-03-08 14:22
Duplicate of #12345.
https://github.com/rg3/youtube-dl/issues/12345#issuecomment-284054428

**Closed by dstftw** 2017-03-08 14:22 UTC
Labels: account-needed
