### ISSUE TITLE
youtube-dl stopped working on youku.com

### ISSUE THREAD

**Issue by lxbgit** [rg3/youtube-dl#7793] opened 2015-12-08 07:35 UTC

**Comment by jaimeMF** [comment] 2015-12-08 10:21
Without [the required information](https://github.com/rg3/youtube-dl/blob/535d7b681b05a37a3c2549c7501eb7fe9c8a5f4e/README.md#bugs), this looks like a duplicate of #7627.

**Closed by jaimeMF** 2015-12-08 10:21 UTC
