### ISSUE TITLE
Playlist download - music.yandex.ru

### ISSUE THREAD

**Issue by Forket** [rg3/youtube-dl#9382] opened 2016-05-03 17:48 UTC
Script itself asked me to post this bug :) 

main message of error:
`ERROR: An extractor error has occurred. (caused by KeyError(u'pageData',));`

Below is info:
1. Screenshot
![snapshot n001_2016-05-03_19-44-13](https://cloud.githubusercontent.com/assets/6735288/14992679/76be0fa6-1167-11e6-91ab-05ad6326a9a7.png)

2. info from output (same as in screenshot) in text file
[script_output.txt](https://github.com/rg3/youtube-dl/files/247409/script_output.txt)

3. Same output, but with verbose:
[script_output_verbose.txt](https://github.com/rg3/youtube-dl/files/247411/script_output_verbose.txt)

**Comment by Forket** [comment] 2016-05-03 17:56
Seems like same error as #6801 . But as I can see - not resolved.

**Comment by Forket** [comment] 2016-05-03 18:02
Here is dumped pages
[tmp.zip](https://github.com/rg3/youtube-dl/files/247443/tmp.zip)

**Comment by dstftw** [comment] 2016-05-03 19:25
Same 404 for me. Duplicate of #6801.

**Closed by dstftw** 2016-05-03 19:25 UTC

**Comment by Forket** [comment] 2016-05-03 21:04
Basically it's because playlist was private. Marked it as public, so now you can see it. But issue still exists.

**Comment by Forket** [comment] 2016-05-04 05:19
@dstftw, Sergey, could you please take a look? Because seems that it's true that script can't download playlists. Or at list can you please provide link to some playlist which script can download, so that I could check myself and find difference. 
Thanks.
