### ISSUE TITLE
Add support for srf.ch

### ISSUE THREAD

**Issue by prendinger** [rg3/youtube-dl#5324] opened 2015-03-30 15:47 UTC
http://www.srf.ch/play/tv/dok-12378-km-australien/video/folge-4-von-katoomba-bis-zur-gibb-river-road?id=03e72246-a3a4-4ea1-8a11-76ec22845a50

**Comment by yan12125** [comment] 2015-04-16 10:17
A duplicate of #981

**Closed by yan12125** 2015-04-16 10:17 UTC
Labels: site-support-request
