### ISSUE TITLE
rai.tv Unsupported URL error

### ISSUE THREAD

**Issue by Danyadd** [rg3/youtube-dl#9158] opened 2016-04-11 10:29 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.04.06*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.06**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl.exe -v "http://www.rai.tv/dl/replaytv/replaytv.html?day=2016-04-10&ch=3&v=651933&vd=2016-04-10&vc=3#day=2016-04-10&ch=3&v=651933&vd=2016-04-10&vc=3"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.rai.tv/dl/replaytv/replaytv.html?day=2016-04-10&ch=3&v=651933&vd=2016-04-10&vc=3#day=2016-04-10&ch=3&v=651933&vd=2016-04-10&vc=3']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.04.06
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-79209-gb3eda69
[debug] Proxy map: {}
[generic] replaytv: Requesting header
[redirect] Following redirect to http://www.rai.tv/dl/replaytv/replaytv.html?ch=3&vc=3&vd=2016-04-10&day=2016-04-10&v=651933#day=2016-04-10&ch=3&v=651933&vd=2016-04-10&vc=3
[generic] replaytv: Requesting header
[redirect] Following redirect to http://www.rai.tv/dl/replaytv/replaytv.html?v=651933&ch=3&vd=2016-04-10&vc=3&day=2016-04-10#day=2016-04-10&ch=3&v=651933&vd=2016-04-10&vc=3
[generic] replaytv: Requesting header
WARNING: Falling back on generic information extractor.
[generic] replaytv: Downloading webpage
[generic] replaytv: Extracting information
ERROR: Unsupported URL: http://www.rai.tv/dl/replaytv/replaytv.html?v=651933&ch=3&vd=2016-04-10&vc=3&day=2016-04-10#day=2016-04-10&ch=3&v=651933&vd=2016-04-10&vc=3
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1348, in _real_extract
  File "youtube_dl\compat.pyo", line 279, in compat_etree_fromstring
  File "youtube_dl\compat.pyo", line 268, in _XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: undefined entity: line 12, column 0
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 669, in extract_info
  File "youtube_dl\extractor\common.pyo", line 323, in extract
  File "youtube_dl\extractor\generic.pyo", line 2012, in _real_extract
UnsupportedError: Unsupported URL: http://www.rai.tv/dl/replaytv/replaytv.html?v=651933&ch=3&vd=2016-04-10&vc=3&day=2016-04-10#day=2016-04-10&ch=3&v=651933&vd=2016-04-10&vc=3
```

---

---

### Description of your *issue*, suggested solution and other information

As you can see in the log, youtube-dl says unsupported URL
but RaiTV is a supported website
https://github.com/rg3/youtube-dl/blob/master/docs/supportedsites.md

The link to the video will expire in 6 days.

**Comment by dstftw** [comment] 2016-04-11 13:42
Duplicate of #2323.

**Closed by dstftw** 2016-04-11 13:42 UTC
