### ISSUE TITLE
Error descargando de mitele.es

### ISSUE THREAD

**Issue by ninosal** [rg3/youtube-dl#6477] opened 2015-08-06 09:42 UTC
Hola.

Estaba intentando descargar unos capítulos de Cuerto Milenio, pero me da error -->

C:\Archivos de programa\youtube-dl>youtube-dl -f best "http://www.mitele.es/prog
ramas-tv/cuarto-milenio/temporada-10/programa-402/"
[mitele.es] programa-402: Downloading webpage
ERROR: Unable to extract embed data; please report this issue on https://yt-dl.o
rg/bug . Make sure you are using the latest version; type  youtube-dl -U  to upd
ate. Be sure to call youtube-dl with the --verbose flag and include its complete
 output.

C:\Archivos de programa\youtube-dl>youtube-dl -f best "http://www.mitele.es/prog
ramas-tv/cuarto-milenio/temporada-10/programa-402/" --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-f', u'best', u'http://www.mitele.es/programas-tv/
cuarto-milenio/temporada-10/programa-402/', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.07.28
[debug] Python version 2.7.8 - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg N-73155-gd5a36ed
[debug] Proxy map: {}
[mitele.es] programa-402: Downloading webpage
ERROR: Unable to extract embed data; please report this issue on https://yt-dl.o
rg/bug . Make sure you are using the latest version; type  youtube-dl -U  to upd
ate. Be sure to call youtube-dl with the --verbose flag and include its complete
 output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 656, in extract_info
  File "youtube_dl\extractor\common.pyo", line 279, in extract
  File "youtube_dl\extractor\mitele.pyo", line 42, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 561, in _search_regex
RegexNotFoundError: Unable to extract embed data; please report this issue on ht
tps://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-
dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include
 its complete output.

**Comment by remitamine** [comment] 2015-08-06 13:13
this is the same problem in this issue https://github.com/rg3/youtube-dl/issues/6414.

**Comment by dstftw** [comment] 2015-08-06 14:08
Duplicate of #6414.

**Closed by dstftw** 2015-08-06 14:08 UTC

**Comment by ninosal** [comment] 2015-08-06 14:10
Yes, it's true. I'm sorry
