### ISSUE TITLE
youku.com return error

### ISSUE THREAD

**Issue by xczheng** [rg3/youtube-dl#15052] opened 2017-12-22 06:36 UTC
youtube-dl -v http://v.youku.com/v_show/id_XNDgxNzk0MTYw.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://v.youku.com/v_show/id_XNDgxNzk0MTYw.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.14
[debug] Python version 3.6.0 - Linux-3.2.61-grsec-modsign-x86_64-with-debian-jessie-sid
[debug] exe versions: avconv 9.20-6, avprobe 9.20-6, ffmpeg N-87921-gdf45ea45df-static, ffprobe N-87921-gdf45ea45df-static
[debug] Proxy map: {}
[youku] XNDgxNzk0MTYw: Retrieving cna info
[youku] XNDgxNzk0MTYw: Downloading JSON metadata
ERROR: Youku server reported error -6004: 客户端无权播放,201; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/colinz/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/home/colinz/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "/home/colinz/lib/python3.6/site-packages/youtube_dl/extractor/youku.py", line 189, in _real_extract
    raise ExtractorError(msg)
youtube_dl.utils.ExtractorError: Youku server reported error -6004: 客户端无权播放,201; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by ellicefix** [comment] 2017-12-22 08:08
Duplicate of #14932

**Closed** 2017-12-22 08:37 UTC
