### ISSUE TITLE
Periscope - ERROR: av_interleaved_write_frame(): Invalid argument -> *temp.mp4 files

### ISSUE THREAD

**Issue by CiscoPress** [rg3/youtube-dl#9631] opened 2016-05-29 09:18 UTC
thanks for Periscope support

[ffmpeg] Fixing malformated aac bitstream in "/Users/linus/Desktop/Lyssa_-_Peeing-NA.mp4"
ERROR: av_interleaved_write_frame(): Invalid argument

the download results in two files: movie and a *.temp.mp4 file with 4.0K

```
> youtube-dl https://www.periscope.tv/DisBeLyss/1mnxewEaMNWGX
[periscope] 1mnxewEaMNWGX: Downloading JSON metadata
[periscope] 1mnxewEaMNWGX: Downloading JSON metadata
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 38
[download] Destination: /Users/linus/Desktop/Lyssa_-_Peeing-NA.mp4
[download] 100% of 4.27MiB in 01:03
[ffmpeg] Fixing malformated aac bitstream in "/Users/linus/Desktop/Lyssa_-_Peeing-NA.mp4"
ERROR: av_interleaved_write_frame(): Invalid argument
> youtube-dl -v
[debug] System config: [u'--restrict-filenames', u'--ignore-errors', u'-n', u'-o', u'~/Desktop/%(title)s-%(resolution)s.%(ext)s', u'-f', u'bestvideo[ext!=webm]+bestaudio[ext!=webm]/best[ext!=webm]']
[debug] User config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.21.2
[debug] Python version 2.7.11 - Darwin-15.5.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 3.0.2, ffprobe 3.0.2, rtmpdump 2.4
[debug] Proxy map: {'http': 'http://localhost:8118', 'https': 'http://localhost:8118'}
Usage: youtube-dl [OPTIONS] URL [URL...]
> youtube-dl https://www.periscope.tv/tonys22/1djGXkLMoroKZ
[periscope] 1djGXkLMoroKZ: Downloading JSON metadata
[periscope] 1djGXkLMoroKZ: Downloading JSON metadata
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 34
[download] Destination: /Users/linus/Desktop/Tony_-_She_pissin-NA.mp4
[download] 100% of 3.52MiB in 01:19
[ffmpeg] Fixing malformated aac bitstream in "/Users/linus/Desktop/Tony_-_She_pissin-NA.mp4"
ERROR: av_interleaved_write_frame(): Invalid argument

-rw-r--r--   1 linus  staff  4480228 May 29 11:10 Lyssa_-_Peeing-NA.mp4
-rw-r--r--   1 linus  staff       48 May 29 11:10 Lyssa_-_Peeing-NA.temp.mp4
-rw-r--r--   1 linus  staff  3690440 May 29 11:09 Tony_-_She_pissin-NA.mp4
-rw-r--r--   1 linus  staff       48 May 29 11:09 Tony_-_She_pissin-NA.temp.mp4

 ffmpeg -v
ffmpeg version 3.0.2 Copyright (c) 2000-2016 the FFmpeg developers
  built with Apple LLVM version 7.3.0 (clang-703.0.29)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.0.2 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-opencl --enable-libx264 --enable-libmp3lame --enable-libxvid --enable-vda
  libavutil      55. 17.103 / 55. 17.103
  libavcodec     57. 24.102 / 57. 24.102
  libavformat    57. 25.100 / 57. 25.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 31.100 /  6. 31.100
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Missing argument for option 'v'.
Error splitting the argument list: Invalid argument

```

**Comment by yan12125** [comment] 2016-05-29 09:24
Run the following command:
```
youtube-dl -v https://www.periscope.tv/DisBeLyss/1mnxewEaMNWGX
```
The won't solve the problem but will give more information for debugging.

**Comment by CiscoPress** [comment] 2016-05-29 09:33
sure

```
> youtube-dl -v https://www.periscope.tv/DisBeLyss/1mnxewEaMNWGX
[debug] System config: [u'--restrict-filenames', u'--ignore-errors', u'-n', u'-o', u'~/Desktop/%(title)s-%(resolution)s.%(ext)s', u'-f', u'bestvideo[ext!=webm]+bestaudio[ext!=webm]/best[ext!=webm]']
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.periscope.tv/DisBeLyss/1mnxewEaMNWGX']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.21.2
[debug] Python version 2.7.11 - Darwin-15.5.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 3.0.2, ffprobe 3.0.2, rtmpdump 2.4
[debug] Proxy map: {'http': 'http://localhost:8118', 'https': 'http://localhost:8118'}
[periscope] 1mnxewEaMNWGX: Downloading JSON metadata
[periscope] 1mnxewEaMNWGX: Downloading JSON metadata
[debug] Invoking downloader on u'https://replay.periscope.tv/GU5WDwf3mvaK1iJ09pF9BBkLA2G8wVc1dILU_qW3ek31nsCTVPcmfoHNYJ07Rv6Lr2-VoyXnwG3N-KuwSqdn5g==/playlist.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 38
[download] Destination: /Users/john/Desktop/Lyssa_-_Peeing-NA.mp4
[download] 100% of 4.27MiB in 00:28
[ffmpeg] Fixing malformated aac bitstream in "/Users/john/Desktop/Lyssa_-_Peeing-NA.mp4"
[debug] ffmpeg command line: avconv -y -i file:/Users/john/Desktop/Lyssa_-_Peeing-NA.mp4 -c copy -f mp4 -bsf:a aac_adtstoasc file:/Users/john/Desktop/Lyssa_-_Peeing-NA.temp.mp4
ERROR: av_interleaved_write_frame(): Invalid argument
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1782, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 511, in run
    self.run_ffmpeg(filename, temp_filename, options)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 172, in run_ffmpeg
    self.run_ffmpeg_multiple_files([path], out_path, opts)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 168, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError
```

**Comment by CiscoPress** [comment] 2016-05-29 09:36
additional details. I can make a preview with https://github.com/PeyloW/Screen-Grabber - it seems the MP4 is not valid

https://i.imgur.com/4waFPBt.png

**Comment by yan12125** [comment] 2016-05-29 09:41
Seems a duplicate of  #2437. Could you retry with the following command:
```
youtube-dl -v https://www.periscope.tv/DisBeLyss/1mnxewEaMNWGX --prefer-ffmpeg
```

**Comment by CiscoPress** [comment] 2016-05-29 09:50
thanks. Issue solved

```
> youtube-dl -v https://www.periscope.tv/DisBeLyss/1mnxewEaMNWGX --prefer-ffmpeg
[debug] System config: [u'--restrict-filenames', u'--ignore-errors', u'-n', u'-o', u'~/Desktop/%(title)s-%(resolution)s.%(ext)s', u'-f', u'bestvideo[ext!=webm]+bestaudio[ext!=webm]/best[ext!=webm]']
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.periscope.tv/DisBeLyss/1mnxewEaMNWGX', u'--prefer-ffmpeg']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.21.2
[debug] Python version 2.7.11 - Darwin-15.5.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 3.0.2, ffprobe 3.0.2, rtmpdump 2.4
[debug] Proxy map: {'http': 'http://localhost:8118', 'https': 'http://localhost:8118'}
[periscope] 1mnxewEaMNWGX: Downloading JSON metadata
[periscope] 1mnxewEaMNWGX: Downloading JSON metadata
[debug] Invoking downloader on u'https://replay.periscope.tv/GU5WDwf3mvaK1iJ09pF9BBkLA2G8wVc1dILU_qW3ek31nsCTVPcmfoHNYJ07Rv6Lr2-VoyXnwG3N-KuwSqdn5g==/playlist.m3u8'
[download] /Users/john/Desktop/Lyssa_-_Peeing-NA.mp4 has already been downloaded
[download] 100% of 4.27MiB
[ffmpeg] Fixing malformated aac bitstream in "/Users/john/Desktop/Lyssa_-_Peeing-NA.mp4"
[debug] ffmpeg command line: ffmpeg -y -i file:/Users/john/Desktop/Lyssa_-_Peeing-NA.mp4 -c copy -f mp4 -bsf:a aac_adtstoasc file:/Users/john/Desktop/Lyssa_-_Peeing-NA.temp.mp4
> youtube-dl -v https://www.periscope.tv/tonys22/1djGXkLMoroKZ --prefer-ffmpeg
[debug] System config: [u'--restrict-filenames', u'--ignore-errors', u'-n', u'-o', u'~/Desktop/%(title)s-%(resolution)s.%(ext)s', u'-f', u'bestvideo[ext!=webm]+bestaudio[ext!=webm]/best[ext!=webm]']
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.periscope.tv/tonys22/1djGXkLMoroKZ', u'--prefer-ffmpeg']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.21.2
[debug] Python version 2.7.11 - Darwin-15.5.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 3.0.2, ffprobe 3.0.2, rtmpdump 2.4
[debug] Proxy map: {'http': 'http://localhost:8118', 'https': 'http://localhost:8118'}
[periscope] 1djGXkLMoroKZ: Downloading JSON metadata
[periscope] 1djGXkLMoroKZ: Downloading JSON metadata
[debug] Invoking downloader on u'https://replay.periscope.tv/qZLUBAzSeZTzeqKATn_SVigFkZPbHOIxd0WfIXgJAb7Urm2dVXP78Y4oAn5HMz9II8hKvhXss4SS250-7F3KkA==/playlist.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 34
[download] Destination: /Users/john/Desktop/Tony_-_She_pissin-NA.mp4
[download] 100% of 3.52MiB in 00:47
[ffmpeg] Fixing malformated aac bitstream in "/Users/john/Desktop/Tony_-_She_pissin-NA.mp4"
[debug] ffmpeg command line: ffmpeg -y -i file:/Users/john/Desktop/Tony_-_She_pissin-NA.mp4 -c copy -f mp4 -bsf:a aac_adtstoasc file:/Users/john/Desktop/Tony_-_She_pissin-NA.temp.mp4

```

**Comment by yan12125** [comment] 2016-05-29 09:53
Thanks for testing.

**Closed by yan12125** 2016-05-29 09:53 UTC
