### ISSUE TITLE
 Unable to download  youku.com

### ISSUE THREAD

**Issue by sandf** [rg3/youtube-dl#7684] opened 2015-11-28 15:35 UTC
ERROR: Unable to download JSON metadata: [Errno 54] Connection reset by peer (caused by error(54, 'Connection reset by peer')); please report this issue on https://yt-dl.org/bug

**Comment by dstftw** [comment] 2015-11-28 15:40
Duplicate of #7627.

**Closed by dstftw** 2015-11-28 15:40 UTC
