### ISSUE TITLE
[abcnews] Falls back on generic, site support needed

### ISSUE THREAD

**Issue by vxbinaca** [rg3/youtube-dl#9459] opened 2016-05-12 06:09 UTC
```youtube-dl -v  http://abcnews.go.com/2020/video/2020-husband-stands-teacher-jail-student-affairs-26119478```

```
[debug] System config: []
[debug] User config: ['-4', '--download-archive', '~/.ytdlarchive', '--retries', '100', '--no-overwrites', '--call-home', '--continue', '--write-info-json', '--write-description', '--write-thumbnail', '--write-annotations', '--all-subs', '--convert-subs', 'srt', '--write-sub', '--add-metadata', '-f', 'bestvideo+bestaudio/best', '--merge-output-format', 'mkv', '--prefer-ffmpeg', '--embed-thumbnail']
[debug] Command-line args: ['-v', 'http://abcnews.go.com/2020/video/2020-husband-stands-teacher-jail-student-affairs-26119478']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.10
[debug] Python version 3.5.1+ - Linux-4.4.0-22-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2
[debug] Proxy map: {}
[debug] Public IP address: 73.156.11.171
[generic] 2020-husband-stands-teacher-jail-student-affairs-26119478: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 2020-husband-stands-teacher-jail-student-affairs-26119478: Downloading webpage
[generic] 2020-husband-stands-teacher-jail-student-affairs-26119478: Extracting information
ERROR: Unsupported URL: http://abcnews.go.com/2020/video/2020-husband-stands-teacher-jail-student-affairs-26119478
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/generic.py", line 2063, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://abcnews.go.com/2020/video/2020-husband-stands-teacher-jail-student-affairs-26119478
```

**Comment by yan12125** [comment] 2016-05-15 09:09
Duplicate of #3992.

**Closed by yan12125** 2016-05-15 09:09 UTC

**Comment by yan12125** [comment] 2016-05-17 07:43
ABC news will be supported in the next version.

**Comment by vxbinaca** [comment] 2016-05-17 07:46
@yan12125 thanks a lot
