### ISSUE TITLE
ytsearch --flat-playlist -j doesn't show titles of tracks in Json file

### ISSUE THREAD

**Issue by Ch3shireDev** [rg3/youtube-dl#14572] opened 2017-10-24 09:46 UTC
I use youtube-dl to automatically search for tracks (with given keyword) and get a json file with id's. Problem is, I also need thumbnails and titles of tracks - thumbnails are easy to download from https://i.ytimg.com/vi/[ID].jpg page, but to download titles youtube-dl has to carefully log into EVERY SINGLE PAGE, simulate download event and get data. It takes ridiculously large amount of time. What I need (and probably more people wouldn't mind) is to include title next to url and id data. After all, when you search for tracks by keyword, you also want to get it's title, isn't it?

- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.20**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Verbose log:
```
C:\Users\cheshire\Downloads>youtube-dl.exe "ytsearch10:Dead Can Dance" --flat-playlist -j -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['ytsearch10:Dead Can Dance', '--flat-playlist', '-j', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.10.20
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
{"ie_key": "Youtube", "id": "aiDNf8trWn8", "_type": "url", "url": "aiDNf8trWn8"}
{"ie_key": "Youtube", "id": "g0L5RFspwyE", "_type": "url", "url": "g0L5RFspwyE"}
{"ie_key": "Youtube", "id": "zReWPjreJzI", "_type": "url", "url": "zReWPjreJzI"}
{"ie_key": "Youtube", "id": "2ZpXPwmbQvc", "_type": "url", "url": "2ZpXPwmbQvc"}
{"ie_key": "Youtube", "id": "wWGKwNt9NY8", "_type": "url", "url": "wWGKwNt9NY8"}
{"ie_key": "Youtube", "id": "LWuvgx7pg_k", "_type": "url", "url": "LWuvgx7pg_k"}
{"ie_key": "Youtube", "id": "9hQqndZSbdo", "_type": "url", "url": "9hQqndZSbdo"}
{"ie_key": "Youtube", "id": "TvGLi_ZosjQ", "_type": "url", "url": "TvGLi_ZosjQ"}
{"ie_key": "Youtube", "id": "mPDLJ1UU2Uk", "_type": "url", "url": "mPDLJ1UU2Uk"}
{"ie_key": "Youtube", "id": "yKgeD0C0BsI", "_type": "url", "url": "yKgeD0C0BsI"}
```

**Comment by yan12125** [comment] 2017-10-24 11:35
This is a duplicate of #11260

**Closed by yan12125** 2017-10-24 11:35 UTC
