### ISSUE TITLE
MixCloud RegexNotFoundError

### ISSUE THREAD

**Issue by npzimmermann** [rg3/youtube-dl#13508] opened 2017-06-27 21:29 UTC
---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.25*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.25**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v --ignore-config 'https://www.mixcloud.com/8ballradio/zimmer-down-5-who-is-aphex-twin-2'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--ignore-config', u'https://www.mixcloud.com/8ballradio/zimmer-down-5-who-is-aphex-twin-2']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.06.25
[debug] Python version 2.7.10 - Darwin-16.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {}
[mixcloud] 8ballradio-zimmer-down-5-who-is-aphex-twin-2: Downloading webpage
ERROR: Unable to extract play info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 762, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/mixcloud.py", line 80, in _real_extract
    r'm-play-info="([^"]+)"', webpage, 'play info')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 782, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract play info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

---

### Description of your *issue*, suggested solution and other information

I noticed a few past Regex error bug reports for Mixcloud that have been fixed, and Mixcloud seems to work fine most of the time, but this url is different in that it's geo-restricted for copyright issues. I've tried passing --geo-bypass and --geo-bypass-country etc, all return the same error response included above: RegexNotFoundError('Unable to extract %s' % _name)

**Comment by for-coursera** [comment] 2017-08-16 17:35
Confirm that.

    ~> youtube-dl --version
    2017.08.13

**Comment by Trii** [comment] 2017-08-24 11:38
@for-coursera I can confirm with 2017.8.23

```
JoshJ:~ josh$ youtube-dl -v https://www.mixcloud.com/Krafty_Kuts/krafty-kuts-golden-era-hip-hop-vol-3-podcast-mix-only
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.mixcloud.com/Krafty_Kuts/krafty-kuts-golden-era-hip-hop-vol-3-podcast-mix-only']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.23
[debug] Python version 2.7.12 - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[mixcloud] Krafty_Kuts-krafty-kuts-golden-era-hip-hop-vol-3-podcast-mix-only: Downloading webpage
ERROR: Unable to extract play info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/josh/Library/Python/2.7/lib/python/site-packages/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/Users/josh/Library/Python/2.7/lib/python/site-packages/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/Users/josh/Library/Python/2.7/lib/python/site-packages/youtube_dl/extractor/mixcloud.py", line 108, in _real_extract
    r'm-play-info="([^"]+)"', webpage, 'play info')
  File "/Users/josh/Library/Python/2.7/lib/python/site-packages/youtube_dl/extractor/common.py", line 797, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract play info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by sudovijay** [comment] 2017-08-24 14:32
fixed in #14016

**Comment by for-coursera** [comment] 2017-08-27 18:42
Can confirm, seems like working again. Thanks a lot, @sudovijay!

**Comment by kalitara** [comment] 2017-08-31 01:37
Not working again...

# youtube-dl -v https://www.mixcloud.com/Tomares/wave-in-botnang-august-2017/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.mixcloud.com/Tomares/wave-in-botnang-august-2017/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.27.1
[debug] Python version 2.7.10 - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: avconv 12.1, avprobe 12.1, ffmpeg 3.3.3, ffprobe 3.3.3
[debug] Proxy map: {}
[mixcloud] Tomares-wave-in-botnang-august-2017: Downloading webpage
ERROR: Unable to extract play info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/mixcloud.py", line 108, in _real_extract
    r'm-play-info="([^"]+)"', webpage, 'play info')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 797, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract play info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by for-coursera** [comment] 2017-08-31 06:20
BTW, further to the comment by @kalitara (which is now deleted, I presume), I can also confirm that it indeed works kinda every other time:

    ~/tmp> ./youtube-dl  -v --ignore-config 'https://www.mixcloud.com/leproradio/sputnikone-%D1%82%D0%B5%D1%85%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B5%D1%81%D1%81-7/'
    [debug] System config: []
    [debug] User config: []
    [debug] Custom config: []
    [debug] Command-line args: [u'-v', u'--ignore-config', u'https://www.mixcloud.com/leproradio/sputnikone-%D1%82%D0%B5%D1%85%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B5%D1%81%D1%81-7/']
    [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2017.08.27.1
    [debug] Python version 2.7.5 - Linux-2.6.32-042stab113.11-x86_64-with-centos-7.3.1611-Core
    [debug] exe versions: none
    [debug] Proxy map: {}
    [mixcloud] leproradio-sputnikone-технический-прогресс-7: Downloading webpage
    ERROR: Unable to extract play info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
    Traceback (most recent call last):
      File "./youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
        ie_result = ie.extract(url)
      File "./youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
        ie_result = self._real_extract(url)
      File "./youtube-dl/youtube_dl/extractor/mixcloud.py", line 108, in _real_extract
        r'm-play-info="([^"]+)"', webpage, 'play info')
      File "./youtube-dl/youtube_dl/extractor/common.py", line 797, in _search_regex
        raise RegexNotFoundError('Unable to extract %s' % _name)
    RegexNotFoundError: Unable to extract play info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
    
    ~/tmp> ./youtube-dl  -v --ignore-config 'https://www.mixcloud.com/leproradio/sputnikone-%D1%82%D0%B5%D1%85%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B5%D1%81%D1%81-7/'
    [debug] System config: []
    [debug] User config: []
    [debug] Custom config: []
    [debug] Command-line args: [u'-v', u'--ignore-config', u'https://www.mixcloud.com/leproradio/sputnikone-%D1%82%D0%B5%D1%85%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B5%D1%81%D1%81-7/']
    [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2017.08.27.1
    [debug] Python version 2.7.5 - Linux-2.6.32-042stab113.11-x86_64-with-centos-7.3.1611-Core
    [debug] exe versions: none
    [debug] Proxy map: {}
    [mixcloud] leproradio-sputnikone-технический-прогресс-7: Downloading webpage
    [mixcloud] leproradio-sputnikone-технический-прогресс-7: Downloading webpage
    [debug] Default format spec: best
    [debug] Invoking downloader on u'https://stream6.mixcloud.com/secure/c/m4a/64/d/e/d/d/102e-7523-416e-b64a-24bd3baa21f7.m4a?sig=J8rdpPLCmWvj7sWLTf5vOg'
    [download] Destination: sputnik.one - Технический прогресс #7-leproradio-sputnikone-технический-прогресс-7.m4a
    [download]  12.3% of 32.43MiB at  2.30MiB/s ETA 00:12^C
    ERROR: Interrupted by user

**Comment by Ji-eF** [comment] 2017-09-22 18:00
Issue seems to be back :
```[debug] System config: []
[debug] User config: []                                                                                                                              
[debug] Custom config: []                                                                                                                            
[debug] Command-line args: [u'--verbose', u'http://www.mixcloud.com/kushsessions/110-kushsession']                                                   
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8                                                                                     
[debug] youtube-dl version 2017.09.15                                                                                                                
[debug] Python version 2.7.13 - Linux-4.9.0-3-amd64-x86_64-with-glibc2.7                                                                             
[debug] exe versions: ffmpeg 2.5.11, ffprobe 3.2.5-1                                                                                                 
[debug] Proxy map: {}                                                                                                                                
[mixcloud] kushsessions-110-kushsession: Downloading webpage                                                                                         
ERROR: Unable to extract play info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.                                                   
Traceback (most recent call last):                                                                                                                   
  File "/home/tukuyomi/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info                                                            
    ie_result = ie.extract(url)                                                                                                                      
  File "/home/tukuyomi/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract                                                          
    ie_result = self._real_extract(url)                                                                                                              
  File "/home/tukuyomi/bin/youtube-dl/youtube_dl/extractor/mixcloud.py", line 108, in _real_extract                                                  
    r'm-play-info="([^"]+)"', webpage, 'play info')                                                                                                  
  File "/home/tukuyomi/bin/youtube-dl/youtube_dl/extractor/common.py", line 797, in _search_regex                                                    
    raise RegexNotFoundError('Unable to extract %s' % _name)                                                                                         
RegexNotFoundError: Unable to extract play info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.                                      `

**Closed** 2017-09-22 22:38 UTC
