### ISSUE TITLE
Youku download failed: Extractor Youku returned a compat_list result. It needs to be updated.

### ISSUE THREAD

**Issue by bonfy** [rg3/youtube-dl#5114] opened 2015-03-03 12:12 UTC
youtube-dl http://v.youku.com/v_show/id_XOTAzODg2MzA0.html
[Youku] XOTAzODg2MzA0: Downloading JSON metadata
WARNING: Extractor Youku returned a compat_list result. It needs to be updated.
ERROR: unable to download video data: HTTP Error 404: Not Found

**Comment by yan12125** [comment] 2015-03-04 01:59
Probably a duplicate of #3038

**Closed** 2015-03-04 10:20 UTC
