### ISSUE TITLE
youtube playlist not working

### ISSUE THREAD

**Issue by jonapom** [rg3/youtube-dl#7549] opened 2015-11-18 18:04 UTC
myuser@linux:~$ youtube-dl --format 22 --verbose https://www.youtube.com/playlist?list=PL4vbGURud_Hqg-hbOg6WdhEcB9FDPLc1i[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--format', u'22', u'--verbose', u'https://www.youtube.com/playlist?list=PL4vbGURud_Hqg-hbOg6WdhEcB9FDPLc1i']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.15
[debug] Python version 2.7.9 - Linux-3.16.0-4-686-pae-i686-with-debian-8.2
[debug] exe versions: avconv 11.4-6, avprobe 11.4-6, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] PL4vbGURud_Hqg-hbOg6WdhEcB9FDPLc1i: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1644, in _real_extract
    return self._extract_playlist(playlist_id)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1619, in _extract_playlist
    page, 'title')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 593, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by jaimeMF** [comment] 2015-11-18 18:19
Duplicate of #7544.

**Closed by jaimeMF** 2015-11-18 18:19 UTC

**Comment by phihag** [comment] 2015-11-18 18:24
Thank you for the report. I believe this issue to be fixed in youtube-dl version 2015.11.18. See [our FAQ](https://yt-dl.org/update) if you need help updating.
