### ISSUE TITLE
Error "rtmpdump exited with code 1" on video from NowTV.de

### ISSUE THREAD

**Issue by e-d-n-a** [rg3/youtube-dl#8128] opened 2016-01-03 01:44 UTC
I have no experience with downloading from NowTV.de, but guess it should be working out-of-the-box with the existing extractor!?
So I just tested it with the video in the log.

Maybe it's similar to this old problem:
https://github.com/rg3/youtube-dl/issues/2732

The Log:
youtube-dl http://www.nowtv.de/ntv/n-tv-wissen/thema-ua-der-groesste-feuerwerk-store-der-welt/player -v -o test.flv
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.nowtv.de/ntv/n-tv-wissen/thema-ua-der-groesste-feuerwerk-store-der-welt/player', u'-v', u'-o', u'test.flv']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.21
[debug] Python version 2.7.3 - Linux-3.12.24+-armv6l-with-debian-7.5
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[NowTV] n-tv-wissen/thema-ua-der-groesste-feuerwerk-store-der-welt: Downloading JSON metadata
[debug] Invoking downloader on u'rtmpe://fms.rtl.de'
[download] Destination: test.flv
[debug] rtmpdump command line: rtmpdump --verbose -r rtmpe://fms.rtl.de -o test.flv.part --swfVfy http://cdn.static-fra.de/now/vodplayer.swf --pageUrl http://rtlnow.rtl.de --app ntvnow --playpath mp4:2038/V_926748_RESU_06-706624_132513_h264-mq_38296a388c82befbccda2f74ef25ed95.f4v --resume --skip 1
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : fms.rtl.de
[rtmpdump] WARNING: No application or playpath in URL!
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : fms.rtl.de
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:2038/V_926748_RESU_06-706624_132513_h264-mq_38296a388c82befbccda2f74ef25ed95.f4v
[rtmpdump] DEBUG: tcUrl    : rtmpe://fms.rtl.de:1935/ntvnow
[rtmpdump] DEBUG: swfUrl   : http://cdn.static-fra.de/now/vodplayer.swf
[rtmpdump] DEBUG: pageUrl  : http://rtlnow.rtl.de
[rtmpdump] DEBUG: app      : ntvnow
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: SWFSHA256:
[rtmpdump] DEBUG: 6a c3 ca 36 7c 47 c2 ae df a5 e9 87 32 b5 24 ba
[rtmpdump] DEBUG: 9b 17 88 02 10 47 bd 10 72 9d 90 b7 ef cc 9e 6e
[rtmpdump] DEBUG: SWFSize  : 913750
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 0 bytes
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : fms.rtl.de
[rtmpdump] WARNING: No application or playpath in URL!
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : fms.rtl.de
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:2038/V_926748_RESU_06-706624_132513_h264-mq_38296a388c82befbccda2f74ef25ed95.f4v
[rtmpdump] DEBUG: tcUrl    : rtmpe://fms.rtl.de:1935/ntvnow
[rtmpdump] DEBUG: swfUrl   : http://cdn.static-fra.de/now/vodplayer.swf
[rtmpdump] DEBUG: pageUrl  : http://rtlnow.rtl.de
[rtmpdump] DEBUG: app      : ntvnow
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: SWFSHA256:
[rtmpdump] DEBUG: 6a c3 ca 36 7c 47 c2 ae df a5 e9 87 32 b5 24 ba
[rtmpdump] DEBUG: 9b 17 88 02 10 47 bd 10 72 9d 90 b7 ef cc 9e 6e
[rtmpdump] DEBUG: SWFSize  : 913750
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.

ERROR: rtmpdump exited with code 1
  File "/home/pi/ytdl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/home/pi/ytdl/youtube_dl/__init__.py", line 410, in main
    _real_main(argv)
  File "/home/pi/ytdl/youtube_dl/__init__.py", line 400, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/pi/ytdl/youtube_dl/YoutubeDL.py", line 1677, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/home/pi/ytdl/youtube_dl/YoutubeDL.py", line 676, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/pi/ytdl/youtube_dl/YoutubeDL.py", line 722, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/home/pi/ytdl/youtube_dl/YoutubeDL.py", line 1347, in process_video_result
    self.process_info(new_info)
  File "/home/pi/ytdl/youtube_dl/YoutubeDL.py", line 1609, in process_info
    success = dl(filename, info_dict)
  File "/home/pi/ytdl/youtube_dl/YoutubeDL.py", line 1551, in dl
    return fd.download(name, info)
  File "/home/pi/ytdl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/home/pi/ytdl/youtube_dl/downloader/rtmp.py", line 202, in real_download
    self.report_error('rtmpdump exited with code %d' % retval)
  File "/home/pi/ytdl/youtube_dl/downloader/common.py", line 155, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/home/pi/ytdl/youtube_dl/YoutubeDL.py", line 540, in report_error
    self.trouble(error_message, tb)
  File "/home/pi/ytdl/youtube_dl/YoutubeDL.py", line 502, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

**Comment by e-d-n-a** [comment] 2016-01-03 01:59
Should have updated before, but problem persists with current version 2016.01.01 anyways!

**Comment by dstftw** [comment] 2016-01-03 02:50
Duplicate of #7831.

**Closed by dstftw** 2016-01-03 02:50 UTC
