### ISSUE TITLE
[douyu.com] HTTP error 403: Forbidden

### ISSUE THREAD

**Issue by stevencsc** [rg3/youtube-dl#12301] opened 2017-02-28 12:00 UTC

**Comment by hewenping1996** [comment] 2017-02-28 12:18
The same issue with you.
end with 

- ERRO:Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()).

However,It worked pretty good last night /smugshrug

**Comment by yan12125** [comment] 2017-02-28 13:41
Thanks for the report. It will be fixed in the next version.

**Closed by yan12125** 2017-02-28 13:41 UTC
Labels: broken-IE

**Comment by yan12125** [comment] 2017-02-28 13:45
Note that ffmpeg doesn't support live streams well. livestreamer/streamlink has better support for that. For example:
```
streamlink --player=mpv hls://$(youtube-dl -g <douyu URL>) best
```

Related: #9349
