### ISSUE TITLE
CNBC falls back to generic

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#9471] opened 2016-05-12 18:22 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.05.10*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.10**

### Before submitting an *issue* make sure you have:
- [X ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

pls see: Support for CNBC.com #9011

### What is the purpose of your *issue*?
- [X ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
C:\Transmogrifier>YOUTUBE-DL.PY -v "http://www.cnbc.com/2016/05/10/soccer-star-hope-solo-decides-to-go-to-the-rio-olympics-despite-zika-concerns.html"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.cnbc.com/2016/05/10/soccer-star-hope-solo-decides-to-go-to-the-rio-olympics-despite-zika-concerns.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.05.10
[debug] Python version 3.5.1 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71727-g46778ab, rtmpdump 2.4
[debug] Proxy map: {}
[generic] soccer-star-hope-solo-decides-to-go-to-the-rio-olympics-despite-zika-concerns: Requesting header
WARNING: Falling back on generic information extractor.
[generic] soccer-star-hope-solo-decides-to-go-to-the-rio-olympics-despite-zika-concerns: Downloading webpage
[generic] soccer-star-hope-solo-decides-to-go-to-the-rio-olympics-despite-zika-concerns: Extracting information
ERROR: Unsupported URL: http://www.cnbc.com/2016/05/10/soccer-star-hope-solo-decides-to-go-to-the-rio-olympics-despite-zika-concerns.html
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 341, in extract
    return self._real_extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\generic.py", line 2063, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.cnbc.com/2016/05/10/soccer-star-hope-solo-decides-to-go-to-the-rio-olympics-despite-zika-concerns.html
...
<end of log>
```

### Description of your *issue*, suggested solution and other information

The "article" page falls back to the generic extractor and fails, however if i point to the direct video: http://video.cnbc.com/gallery/?video=3000516505  ....it correctly downloads via "ThePlatform" extractor.

As always...Thanks!
Ringo

**Comment by yan12125** [comment] 2016-05-17 07:55
As you've already said, it's a duplicate of #9011.

**Closed by yan12125** 2016-05-17 07:55 UTC
