### ISSUE TITLE
Can't download youporn video

### ISSUE THREAD

**Issue by Cupcake-iOS** [rg3/youtube-dl#7159] opened 2015-10-13 08:50 UTC
Hello,
After update to the latest version, I can't download the youporn video.
Anyone have this problem?

```
➜  youtube-dl --verbose http://www.youporn.com/watch/561726/big-tits-awesome-brunette-on-amazing-webcam-show/\?from\=related3\&al\=2\&from_id\=561726\&pos\=4
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.youporn.com/watch/561726/big-tits-awesome-brunette-on-amazing-webcam-show/?from=related3&al=2&from_id=561726&pos=4']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.12
[debug] Python version 2.7.10 - Darwin-15.0.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[YouPorn] 561726: Downloading webpage
ERROR: Unable to extract JSON parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youporn.py", line 52, in _real_extract
    webpage, 'JSON parameters')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract JSON parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment] 2015-10-13 14:09
Duplicate of #6888.

**Closed by dstftw** 2015-10-13 14:09 UTC
