### ISSUE TITLE
[Bug report] Not able to download some iqiyi video

### ISSUE THREAD

**Issue by ztytian** [rg3/youtube-dl#10899] opened 2016-10-11 07:54 UTC
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

youtube-dl -v http://www.iqiyi.com/v_19rr9nv6do.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.iqiyi.com/v_19rr9nv6do.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.07
[debug] Python version 2.7.12 - Darwin-16.0.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 3.1.4, ffprobe 3.1.4
[debug] Proxy map: {}
[iqiyi] temp_id: download video page
[iqiyi] 6491fcdf5cfbdadafc52e89903e89c57: Downloading JSON metadata
ERROR: Unable to load data. Error code: A00110; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 356, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/iqiyi.py", line 356, in _real_extract
    raise ExtractorError('Unable to load data. Error code: ' + raw_data['code'])
ExtractorError: Unable to load data. Error code: A00110; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Failed to download http://www.iqiyi.com/v_19rr9nv6do.html
Other iqiyi videos are supported but just experienced some issue on this series.
You need a Chinese proxy to view this. You can obtain one here https://vnet.one/?rc=2879

**Comment by yan12125** [comment] 2016-10-11 08:03
Duplicate of #10088.

**Closed by yan12125** 2016-10-11 08:03 UTC
