### ISSUE TITLE
unable to download webpage  (http error)

### ISSUE THREAD

**Issue by montawartek** [rg3/youtube-dl#10161] opened 2016-07-25 01:15 UTC
unable to download webpage: http error 429: too many requests (caused by httperror()); please report this issue on https://yt-dl.org/bug . make sure you are using the latest version; type youtube-dl -u to update. be sure to call youtube-dl with the --verbose flag and include its complete output.

i got this error when i try to download a music into the sinusbot please help me if you can
youtube-dl is up-to-date (2016.07.24)
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04

**Comment by dstftw** [comment] 2016-07-25 02:13
Duplicate of #5138.

**Closed by dstftw** 2016-07-25 02:13 UTC
