### ISSUE TITLE
Please add alternate URL for Naver

### ISSUE THREAD

**Issue by BlackHoleSpain** [rg3/youtube-dl#11086] opened 2016-11-01 13:50 UTC
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.31**

- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

There are several open NAVER issues months ago.

- [X] Site support request (request for adding support for a new site)

NAVER TVCAST site has been working in youtube-dl for years, but it cannot extract data from NAVER MUSIC site. This is an example of a page released a few days ago:

- Single video: http://music.naver.com/artist/videoPlayer.nhn?videoId=68845
- Public example. Not credentials needed or georestriction for that video.

>youtube-dl -v http://music.naver.com/artist/videoPlayer.nhn?videoId=68845
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://music.naver.com/artist/videoPlayer.nhn?videoId=68845']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.10.31
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[generic] videoPlayer: Requesting header
WARNING: Falling back on generic information extractor.
[generic] videoPlayer: Downloading webpage
[generic] videoPlayer: Extracting information
ERROR: Unsupported URL: http://music.naver.com/artist/videoPlayer.nhn?videoId=68845
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmponbili4i\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmponbili4i\build\youtube_dl\extractor\common.py", line 356, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmponbili4i\build\youtube_dl\extractor\generic.py", line 2417, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://music.naver.com/artist/videoPlayer.nhn?videoId=68845

**Comment by dstftw** [comment] 2016-11-01 13:55
Duplicate of #5766.

**Closed by dstftw** 2016-11-01 13:55 UTC
