### ISSUE TITLE
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug

### ISSUE THREAD

**Issue by jpa74** [rg3/youtube-dl#7483] opened 2015-11-13 06:18 UTC
john@JN-DELL-3541:~/Videos/YouTube$ youtube-dl --verbose https://vimeo.com/102254873
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://vimeo.com/102254873']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.10
[debug] Python version 2.7.10 - Linux-4.2.0-16-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: avconv 2.7.2-1build1, avprobe 2.7.2-1build1, ffmpeg 2.7.2-1build1, ffprobe 2.7.2-1build1, rtmpdump 2.4
[debug] Proxy map: {}
[vimeo] 102254873: Downloading webpage
[vimeo] 102254873: Extracting information
[vimeo] 102254873: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 378, in _real_extract
    view_count = int(self._search_regex(r'UserPlays:(\d+)', webpage, 'view count'))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract view count; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 427, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 766, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

john@JN-DELL-3541:~/Videos/YouTube$

**Comment by timrichardt** [comment] 2015-11-13 08:38
I can confirm this bug. 

```
tim@x1c:~/Day_of_Datomic_Videos> youtube-dl --verbose https://vimeo.com/116228685
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://vimeo.com/116228685']
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[debug] Encodings: locale ANSI_X3.4-1968, fs ascii, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2015.11.10
[debug] Python version 3.5.0 - Linux-4.0.4-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.6.2, ffprobe 2.6.2, rtmpdump 2.4
[debug] Proxy map: {}
[vimeo] 116228685: Downloading webpage
[vimeo] 116228685: Extracting information
[vimeo] 116228685: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/vimeo.py", line 427, in _real_extract
    self._sort_formats(formats)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 766, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment] 2015-11-13 09:44
Duplicate of #7460.

**Closed by dstftw** 2015-11-13 09:44 UTC
