### ISSUE TITLE
[ADN] Extract subtitles : UnicodeDecodeError: "utf-8"

### ISSUE THREAD

**Issue by 0mW** [rg3/youtube-dl#16169] opened 2018-04-12 21:00 UTC
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.04.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '--cookies', '/home/asus/Téléchargements/cookies_adn.json', '--list-subs', 'http://animedigitalnetwork.fr/video/naruto/4189-episode-1-et-voici-naruto-uzumaki', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.04.09
[debug] Python version 3.5.3 (CPython) - Linux-4.9.0-6-amd64-x86_64-with-debian-9.3
[debug] exe versions: avconv 3.4.2-2, avprobe 3.4.2-2, ffmpeg 3.4.2-2, ffprobe 3.4.2-2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {'no': 'localhost,127.0.0.0/8,::1'}
[ADN] 4189: Downloading webpage
[ADN] 4189: Downloading JSON metadata
[ADN] 4189: Downloading JSON metadata
[ADN] 4189: Downloading m3u8 information
[ADN] 4189: Downloading JSON metadata
[ADN] 4189: Downloading m3u8 information
[ADN] 4189: Downloading webpage
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 471, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 461, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1993, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 789, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/adn.py", line 152, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 2552, in extract_subtitles
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/adn.py", line 58, in _get_subtitles
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 0: invalid continuation byte

---

**Comment by 0mW** [comment] 2018-04-12 21:32
And with python version 2.7  :

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'--cookies', u'/home/asus/T\xe9l\xe9chargements/cookies_adn.json', u'--list-subs', u'http://animedigitalnetwork.fr/video/naruto/4189-episode-1-et-voici-naruto-uzumaki', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.04.09
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-6-amd64-x86_64-with-debian-9.3
[debug] exe versions: avconv 3.4.2-2, avprobe 3.4.2-2, ffmpeg 3.4.2-2, ffprobe 3.4.2-2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {'no': 'localhost,127.0.0.0/8,::1'}
[ADN] 4189: Downloading webpage
[ADN] 4189: Downloading JSON metadata
[ADN] 4189: Downloading JSON metadata
[ADN] 4189: Downloading m3u8 information
[ADN] 4189: Downloading JSON metadata
[ADN] 4189: Downloading m3u8 information
[ADN] 4189: Downloading webpage
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 471, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 461, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1993, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 789, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/adn.py", line 152, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 2552, in extract_subtitles
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/adn.py", line 58, in _get_subtitles
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcd in position 2: ordinal not in range(128)

**Comment by remitamine** [comment] 2018-04-14 00:17
Duplicate of #12724.

**Closed by remitamine** 2018-04-14 00:17 UTC
