### ISSUE TITLE
8tracks bug

### ISSUE THREAD

**Issue by CrazyGentleMan** [rg3/youtube-dl#7818] opened 2015-12-09 18:56 UTC
> youtube-dl http://8tracks.com/noonpacific/noon-168 --verbose

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://8tracks.com/noonpacific/noon-168', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.12.09
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg 2.7, ffprobe 2.7
[debug] Proxy map: {}
[8tracks] noon-168: Downloading webpage
[8tracks] noon-168: Downloading song information 1/10
[8tracks] noon-168: Downloading song information 2/10
[8tracks] noon-168: Downloading song information 3/10
[8tracks] noon-168: Downloading song information 4/10
[8tracks] noon-168: Downloading song information 5/10
[8tracks] noon-168: Waiting for 228.4 seconds
[8tracks] noon-168: Downloading song information 5/10
[8tracks] noon-168: Downloading song information 6/10
[8tracks] noon-168: Waiting for 228.4 seconds
[8tracks] noon-168: Downloading song information 6/10
[8tracks] noon-168: Downloading song information 7/10
[8tracks] noon-168: Waiting for 228.4 seconds
[8tracks] noon-168: Downloading song information 7/10
[8tracks] noon-168: Downloading song information 8/10
[8tracks] noon-168: Waiting for 228.4 seconds
[8tracks] noon-168: Downloading song information 8/10
[8tracks] noon-168: Downloading song information 9/10
[8tracks] noon-168: Waiting for 228.4 seconds
[8tracks] noon-168: Downloading song information 9/10
ERROR: An extractor error has occured. (caused by KeyError(u'id',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\extractor\common.pyo", line 290, in extract
  File "youtube_dl\extractor\eighttracks.pyo", line 146, in _real_extract
KeyError: u'id'
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 663, in extract_info
  File "youtube_dl\extractor\common.pyo", line 296, in extract
ExtractorError: An extractor error has occured. (caused by KeyError(u'id',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment] 2015-12-09 18:58
Duplicate of #5029.

**Closed by dstftw** 2015-12-09 18:58 UTC
