### ISSUE TITLE
add-metadata doesn't work when container is .webm

### ISSUE THREAD

**Issue by Spenhouet** [rg3/youtube-dl#11116] opened 2016-11-04 01:31 UTC
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.02*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

If i download music with the following command, no metadata is saved:
`youtube-dl -x --audio-format "mp3" --audio-quality 0 -o "/Music/%(uploader)s/%(title)s.%(ext)s" --metadata-from-title "%(artist)s - %(title)s" --add-metadata https://www.youtube.com/watch?v=0sjR0-EG3BM`

The problem is, that for `--audio-quality 0` the initial container is allways `.webm` which can't contain metadata. Therefor the converted `.mp3` also doesn't contain metadata.

A **workaround** is to add the following command: `--format "bestaudio[ext=m4a]"`

Then the metadata is saved correct in the `.m4a` file and therefor in the converted `.mp3` file.

Searching for this problem i found multiple issues with the same or a similar problem:
- https://github.com/rg3/youtube-dl/issues/11020
- https://github.com/rg3/youtube-dl/issues/11047
- https://github.com/rg3/youtube-dl/issues/9960
- https://github.com/rg3/youtube-dl/issues/11047

Therefor i want to raise awareness to this bug and the workaround.

There is a issue with the same problem: https://github.com/rg3/youtube-dl/pull/9730
There seems to be a fix but since 09.06.2016 there wasn't any activity. Was this bug forgotten?

---

**Comment by dstftw** [comment] 2016-11-04 13:13
Duplicate of #5594.

**Closed by dstftw** 2016-11-04 13:13 UTC

**Comment by Spenhouet** [comment] 2016-11-04 17:54
@dstftw You really did just link a dead issue from 03.05.2015 and closed this one? Does that help to solve the problem? I gues not.
