### ISSUE TITLE
Support for partial timeslice downloading of a video (start time, end time)

### ISSUE THREAD

**Issue by johnhawkinson** [rg3/youtube-dl#12347] opened 2017-03-04 05:40 UTC
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.02**
- [x] Feature request (request for a new functionality)

It ought to be possible to specify downloading a partial timeslice of a video, e.g. `ffmpeg`'s `-ss $seek_position` and `-t $duration` options, ideally with a better UI (e.g. start time and end time, at least as an option).

I realize we an sort of achieve this today by passing args to ffmpeg, e.g.

`youtube-dl ... --external-downloader ffmpeg --external-downloader-args '-ss 3718.538 -t 60'`

or perhaps as a postprocessor arg where appropriate.
But that's not very user-friendly, and knowing when to choose an external downloader versus a postprocessor may not be obvious.

I guess maybe this could just be a FAQ entry, but I think some options would be a better goal.

I realize it probably cannot be made to work in all cases.

**Comment by yan12125** [comment] 2017-03-04 10:05
Duplicate of #622

**Closed by yan12125** 2017-03-04 10:05 UTC

**Comment by Ectomind1990** [comment] 2018-06-07 12:15
Worth adding the "request" label to this issue?

I searched using that label an hour ago but didn't find anything so created https://github.com/rg3/youtube-dl/issues/16665 which is now rightly closed as a duplicate

I know that https://github.com/rg3/youtube-dl/issues/622 already has the "request" label but the word "range" wasn't one of the searches I tried so it didn't find it, but I would have found this
