### ISSUE TITLE
Error with Bandcamp: ValueError: unknown url type:

### ISSUE THREAD

**Issue by goundoulf** [rg3/youtube-dl#4922] opened 2015-02-10 18:07 UTC
It crashes on track number 4, although it's possible to listen to it online.

$ youtube-dl --verbose -o "%(autonumber)s - %(title)s.%(ext)s" --autonumber-size 2 http://theflamencothief.bandcamp.com/album/liberating-parts-of-the-cosmos
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-o', '%(autonumber)s - %(title)s.%(ext)s', '--autonumber-size', '2', 'http://theflamencothief.bandcamp.com/album/liberating-parts-of-the-cosmos']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.10.5
[debug] Python version 2.7.8 - Linux-3.16.0-30-generic-i686-with-Ubuntu-14.10-utopic
[debug] exe versions: avconv 1.2.6-7, avprobe 1.2.6-7, ffmpeg 1.2.6-7, ffprobe 1.2.6-7, rtmpdump 2.4
[debug] Proxy map: {}
[Bandcamp:album] liberating-parts-of-the-cosmos: Downloading webpage
[download] Downloading playlist: Liberating Parts of the Cosmos
[Bandcamp:album] playlist Liberating Parts of the Cosmos: Collected 9 video ids (downloading 9 of them)
[download] Downloading video 1 of 9
[Bandcamp] the-beckoning: Downloading webpage
[debug] Invoking downloader on u'http://popplers5.bandcamp.com/download/track?enc=mp3-128&fsig=8bd8fb4f0d051c42bf63c0ed29e99113&id=2066510788&stream=1&ts=1423590376.0'
[download] Destination: 01 - The Beckoning.mp3
[download] 100% of 2.88MiB in 00:39
[download] Downloading video 2 of 9
[Bandcamp] indiana-the-woman-of-doom: Downloading webpage
[debug] Invoking downloader on u'http://popplers5.bandcamp.com/download/track?enc=mp3-128&fsig=8370dc4d1f607927f9da2870193476c3&id=111885090&stream=1&ts=1423590418.0'
[download] Destination: 02 - Indiana & The Woman of Doom.mp3
[download] 100% of 5.49MiB in 01:33
[download] Downloading video 3 of 9
[Bandcamp] three-pound-universe: Downloading webpage
[debug] Invoking downloader on u'http://popplers5.bandcamp.com/download/track?enc=mp3-128&fsig=19cc539209f433af34ce78f7d7442192&id=3820570798&stream=1&ts=1423590513.0'
[download] Destination: 03 - Three Pound Universe.mp3
[download] 100% of 3.81MiB in 00:58
[download] Downloading video 4 of 9
[Bandcamp] coco-bolo: Downloading webpage
[Bandcamp] 2623791756: Downloading free downloads page
[Bandcamp] 2623791756: Requesting download url
[debug] Invoking downloader on u''
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 388, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 378, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1387, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 644, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 803, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 697, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 644, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 690, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1145, in process_video_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1320, in process_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1295, in dl
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 316, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 66, in real_download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1611, in urlopen
  File "/usr/lib/python2.7/urllib2.py", line 396, in open
    protocol = req.get_type()
  File "/usr/lib/python2.7/urllib2.py", line 258, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type:

**Comment by jaimeMF** [comment] 2015-02-10 20:00
Duplicate of #4861

**Closed by jaimeMF** 2015-02-10 20:00 UTC
