### ISSUE TITLE
Cant update

### ISSUE THREAD

**Issue by pfifo** [rg3/youtube-dl#11959] opened 2017-02-03 22:41 UTC
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Your update function stopped working for me.
I reinstalled manually, that fixed it.

Guess its your hyperlinks, i was getting a 404

**Comment by dstftw** [comment] 2017-02-03 22:44
Ping @phihag.
>https://yt-dl.org/downloads/2017.02.01/youtube-dl
```
Not Found

The requested URL /downloads/2017.02.01/youtube-dl was not found on this server.

Apache/2.2.15 (CentOS) Server at yt-dl.org Port 443
```
I'm also unable to access the box via SSH.

**Comment by rlerner** [comment] 2017-02-03 22:46
Same issue here pulling down either of these links:
http://yt-dl.org/ (latest links)

Or the /downloads/2017.02.01/youtube-dl mentioned above. (even if I throw the .exe extension on there).

**Comment by Starsam80** [comment] 2017-02-03 22:53
https://yt-dl.org/latest is also completely wrong, for me it goes to 2016.06.03

**Comment by julijane** [comment] 2017-02-03 23:01
Had the same problem. Version 2017.02.01 can be downloaded here:
https://github.com/rg3/youtube-dl/releases/tag/2017.02.01

HTH

**Comment by spootrick** [comment] 2017-02-03 23:04
Same here, the error log is following:

ValueError: unknown url type: /yts/jsbin/player-en_US-vflkk7pUE/base.js
 (caused by ValueError(u'unknown url type: /yts/jsbin/player-en_US-vflkk7pUE/base.js',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

$ sudo youtube-dl -U
Updating to version 2017.02.01 ...
ERROR: unable to download latest version

**Comment by dstftw** [comment] 2017-02-03 23:05
We are aware of the problem.
Until yt-dl.org is fixed, the latest version can be downloaded manually from https://github.com/rg3/youtube-dl/releases/download/2017.02.01/youtube-dl.exe.

**Comment by yan12125** [comment] 2017-02-04 04:10
As yt-dl.org is no longer used to host binaries, how about just put Github links on downloading pages and ```versions.json```?

**Comment by dstftw** [comment] 2017-02-04 10:17
It's much easier to work with direct URLs hidden via redirects rather than direct URLs. I we decide to move binaries to another place in case of yt-dl.org links we'd just update rewrite rules and everything will just work.
Assuming these URLs spread across blogs and internet, if we put GitHub links everywhere and eventually give up on GitHub as binary hoster all these URLs will become invalid. However in case of spreading yt-dl.org links they will continue to work. So, no, putting GitHub links is a bad idea.

yt-dl.org is now fixed.

**Closed by dstftw** 2017-02-04 10:17 UTC
Labels: build/update
