### ISSUE TITLE
Lynda Unable to download video

### ISSUE THREAD

**Issue by 1dinamani** [rg3/youtube-dl#9743] opened 2016-06-10 13:22 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.06.03*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.03**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

---

### Description of your *issue*, suggested solution and other information

I am unable to download the videos from lynda from today, below is the error message whhen i used the login credentials. With the same login, i am able to login in web browser. 

[lynda:course] Logging in as '''''
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Mak
e sure you are using the latest version; type  youtube-dl -U  to update. Be sure
 to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpjletvtok\bu
ild\youtube_dl\YoutubeDL.py", line 676, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpjletvtok\bu
ild\youtube_dl\extractor\common.py", line 340, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpjletvtok\bu
ild\youtube_dl\extractor\common.py", line 334, in initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpjletvtok\bu
ild\youtube_dl\extractor\lynda.py", line 23, in _real_initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpjletvtok\bu
ild\youtube_dl\extractor\lynda.py", line 81, in _login
youtube_dl.utils.ExtractorError: Unable to log in; please report this issue on h
ttps://yt-dl.org/bug . Make sure you are using the latest version; type  youtube
-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and includ
e its complete output.

Please assist.

**Comment by 1dinamani** [comment] 2016-06-10 13:22
Please assist on above. Thanks

**Comment by TRox1972** [comment] 2016-06-10 13:25
Please post full verbose output (with `-v`).

**Comment by 1dinamani** [comment] 2016-06-10 13:34
Thanks for the quick response. Please find the details below:

C:\Users\AAA\Desktop\youtube-dl>youtube-dl.exe -v "https://www.lynda.com/Py
thon-tutorials/Up-Running-Python/122467-2.html" -u AAA -p BBB
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://www.lynda.com/Python-tutorials/Up-Run
ning-Python/122467-2.html', '-u', 'PRIVATE', '-p', 'PRIVATE']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.06.03
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[lynda:course] Logging in as AAA
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Mak
e sure you are using the latest version; type  youtube-dl -U  to update. Be sure
 to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpjletvtok\bu
ild\youtube_dl\YoutubeDL.py", line 676, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpjletvtok\bu
ild\youtube_dl\extractor\common.py", line 340, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpjletvtok\bu
ild\youtube_dl\extractor\common.py", line 334, in initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpjletvtok\bu
ild\youtube_dl\extractor\lynda.py", line 23, in _real_initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpjletvtok\bu
ild\youtube_dl\extractor\lynda.py", line 81, in _login
youtube_dl.utils.ExtractorError: Unable to log in; please report this issue on h
ttps://yt-dl.org/bug . Make sure you are using the latest version; type  youtube
-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and includ
e its complete output.

If you need any further information, please let me know. Thanks

**Comment by dstftw** [comment] 2016-06-10 13:41
Duplicate of #9740.

**Closed by dstftw** 2016-06-10 13:41 UTC

**Comment by 1dinamani** [comment] 2016-06-10 13:46
Hi dstftw you have closed both the ticket. But not received any solution for it. # 9743 & #9740

Please assit.

**Comment by SumuduLansakara** [comment] 2018-11-23 20:54
Recently I started getting a similar error (all worked fine a few weeks/months before). Can anyone help me with this.

Following is the error with verbose output.
`[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username=PRIVATE', '--password=PRIVATE', '--write-sub', '--external-downloader=aria2c', '--external-downloader-args=-c -j 3 -x 3 -s 3 -k 1M', '--output=library/[%(playlist_id)s] %(playlist_title)s/%(playlist_index)s-%(chapter)s-%(title)s.%(ext)s', 'https://www.lynda.com/C-tutorials/C-Essential-Training/182674-2.html', 'https://www.lynda.com/C-tutorials/C-Essential-Training/182674-2.html', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.11.23
[debug] Python version 3.7.0 (CPython) - Linux-4.9.0-8-amd64-x86_64-with-debian-9.6
[debug] exe versions: ffmpeg 3.2.12-1, ffprobe 3.2.12-1
[debug] Proxy map: {}
[lynda:course] Downloading signin page
ERROR: Unable to extract signin form; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/sumudu/Lynda/venv/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/home/sumudu/Lynda/venv/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 507, in extract
    self.initialize()
  File "/home/sumudu/Lynda/venv/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 411, in initialize
    self._real_initialize()
  File "/home/sumudu/Lynda/venv/lib/python3.7/site-packages/youtube_dl/extractor/lynda.py", line 25, in _real_initialize
    self._login()
  File "/home/sumudu/Lynda/venv/lib/python3.7/site-packages/youtube_dl/extractor/lynda.py", line 75, in _login
    signin_page, 'signin form')
  File "/home/sumudu/Lynda/venv/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 983, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract signin form; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`

**Comment by SumuduLansakara** [comment] 2018-11-23 21:02
### Solution to above issue
I found following pending pull request solves this issue.

https://github.com/rg3/youtube-dl/pull/18217

I made the fix locally and verified the fix with my Lynda account. It would be great if someone with write privileges can verify and add this to the main code.

**Comment by mohseneslami** [comment] 2018-11-25 17:14
Hi SumuduLansakara , How solve lynda.com problem? I have account and have problem with login signin

**Comment by SumuduLansakara** [comment] 2018-11-25 17:35
Do the change in the referred pull request locally.
https://github.com/rg3/youtube-dl/pull/18217/commits/61d294b76e6ff73757e7e6a5a3fd47c0027d3b1c
