### ISSUE TITLE
Unable to download embedded videos from https://miami.cbslocal.com

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#16828] opened 2018-06-26 21:35 UTC
$ youtube-dl -v  https://miami.cbslocal.com/2018/06/25/man-seen-on-hood-of-car-on-i-95/

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://miami.cbslocal.com/2018/06/25/man-seen-on-hood-of-car-on-i-95/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.25
[debug] Python version 3.4.2 (CPython) - Linux-3.16.0-6-amd64-x86_64-with-debian-8.11
[debug] exe versions: ffmpeg 3.2.10-1, ffprobe 3.2.10-1, rtmpdump 2.4
[debug] Proxy map: {}
[CBSLocal] man-seen-on-hood-of-car-on-i-95: Downloading webpage
[CBSLocal] 3888789: Fetching server time
ERROR: An extractor error has occurred. (caused by KeyError('DVzl9QRzox3ZZsP9bNu5Li3X7obQOnqP',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 501, in extract
    ie_result = self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/cbslocal.py", line 92, in _real_extract
    info_dict = self._extract_anvato_videos(webpage, display_id)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/anvato.py", line 276, in _extract_anvato_videos
    anvplayer_data['accessKey'], anvplayer_data['video'])
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/anvato.py", line 182, in _get_anvato_videos
    video_data = self._get_video_json(access_key, video_id)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/anvato.py", line 172, in _get_video_json
    access_key, anvrid, server_time, self._ANVACK_TABLE[access_key])),
KeyError: 'DVzl9QRzox3ZZsP9bNu5Li3X7obQOnqP'
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 501, in extract
    ie_result = self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/cbslocal.py", line 92, in _real_extract
    info_dict = self._extract_anvato_videos(webpage, display_id)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/anvato.py", line 276, in _extract_anvato_videos
    anvplayer_data['accessKey'], anvplayer_data['video'])
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/anvato.py", line 182, in _get_anvato_videos
    video_data = self._get_video_json(access_key, video_id)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/anvato.py", line 172, in _get_video_json
    access_key, anvrid, server_time, self._ANVACK_TABLE[access_key])),
KeyError: 'DVzl9QRzox3ZZsP9bNu5Li3X7obQOnqP'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 514, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('DVzl9QRzox3ZZsP9bNu5Li3X7obQOnqP',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by remitamine** [comment] 2018-07-01 14:36
Duplicate of #16788.

**Closed by remitamine** 2018-07-01 14:36 UTC
