### ISSUE TITLE
youtube-dl delay

### ISSUE THREAD

**Issue by sbPark82** [rg3/youtube-dl#7899] opened 2015-12-18 11:31 UTC
I have a question. 

I want to get the URL using youtube-dl, and the "simulate" option -g that does not download the video. 

So I gave the following command:
 youtube-dl -g https://www.youtube.com/watch?v=k4JGSAmu4lg

It gave the following output after 7 to 8 seconds
https://r20---sn-cvh7zn7d.googlevideo.com/videoplayback?initcwndbps=1113000&mt=1408702970&requiressl=yes&ipbits=0&sver=3&fexp=901454%2C902408%2C919145%2C924626%2C927622%2C927904%2C931330%2C931983%2C934024%2C934030%2C934804%2C945118%2C945308%2C946023%2C951914&ratebypass=yes&signature=38F111D46D72FFC50B47D50B3C9A631099BF5F83.FA134C91F407989B95ACADC1F1F6946B8F18C158&upn=tU0u5t7A2Uw&sparams=id%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Cmm%2Cms%2Cmv%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&mm=31&expire=1408724634&id=o-AJNPuDp9TKMKiwzUwvSk76W7JdA0cx0bRSum9mPJJ7Vo&mv=u&source=youtube&ms=au&key=yt5&ip=115.113.1.50&itag=18

But the problem is it is taking around 7 to 8 seconds for querying the URL.
 Is there any way so that it can be faster?

option "--youtube-skip-dash-manifest " does not work.  

youtube-dl -g https://www.youtube.com/watch?v=k4JGSAmu4lg
youtube-dl -g --youtube-skip-dash-manifest https://www.youtube.com/watch?v=k4JGSAmu4lg

same delay

**Comment by yan12125** [comment] 2015-12-18 12:04
Duplicate of #7897. Don't post two or more issues for the same problem.

**Closed by yan12125** 2015-12-18 12:04 UTC
