### ISSUE TITLE
Passworded Vimeo download has successful login, but results in file provided if not logged in

### ISSUE THREAD

**Issue by anxst** [rg3/youtube-dl#7206] opened 2015-10-17 13:14 UTC
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'--verbose', u'https://vimeo.com/141298620']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.10.16
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[vimeo] Logging in
[vimeo] 141298620: Downloading webpage
[vimeo] 141298620: Extracting information
[vimeo] 141298620: Downloading webpage
[vimeo] 141298620: Downloading m3u8 information
[debug] Invoking downloader on u'https://skyfire.vimeocdn.com/1445090862-0x13ca87c02606fed2f69d1eabc7787ea070524f52/140658136/video/420583964/playlist.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 16
[download] Destination: Con Man-141298620.mp4
[download] 100% of 55.23MiB in 00:22

**Comment by dstftw** [comment] 2015-10-17 13:20
Duplicate of #7118.

**Closed by dstftw** 2015-10-17 13:20 UTC

**Comment by anxst** [comment] 2015-10-17 18:51
So it is, missed it out there. My bad, thanks!
