### ISSUE TITLE
myvideo.de url not working

### ISSUE THREAD

**Issue by pejobo** [rg3/youtube-dl#3925] opened 2014-10-11 19:17 UTC
verbose output

	[debug] System config: []
	[debug] User config: []
	[debug] Command-line args: ['-v', 'http://www.myvideo.de/serien/the-voice-of-germany/staffel-4/folge-2-folge-2-blind-audition-ii-teil-1-m-9827691']
	[debug] Encodings: locale ISO-8859-1, fs ISO-8859-1, out ISO-8859-1, pref ISO-8859-1
	[debug] youtube-dl version 2014.10.05.2
	[debug] Python version 2.7.3 - Linux-3.10.36-armv6l-with-debian-7.5
	[debug] Proxy map: {}
	[generic] folge-2-folge-2-blind-audition-ii-teil-1-m-9827691: Requesting header
	WARNING: Falling back on generic information extractor.
	[generic] folge-2-folge-2-blind-audition-ii-teil-1-m-9827691: Downloading webpage
	[generic] folge-2-folge-2-blind-audition-ii-teil-1-m-9827691: Extracting information
	ERROR: Unsupported URL: http://www.myvideo.de/serien/the-voice-of-germany/staffel-4/folge-2-folge-2-blind-audition-ii-teil-1-m-9827691; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
	Traceback (most recent call last):
	  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 540, in _real_extract
	    doc = parse_xml(webpage)
	  File "/usr/bin/youtube-dl/youtube_dl/utils.py", line 1550, in parse_xml
	    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
	  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
	    parser.feed(text)
	  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1643, in feed
	    self._raiseerror(v)
	  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1507, in _raiseerror
	    raise err
	ParseError: not well-formed (invalid token): line 42, column 449
	Traceback (most recent call last):
	  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 524, in extract_info
	    ie_result = ie.extract(url)
	  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 193, in extract
	    return self._real_extract(url)
	  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 907, in _real_extract
	    raise ExtractorError('Unsupported URL: %s' % url)
	ExtractorError: Unsupported URL: http://www.myvideo.de/serien/the-voice-of-germany/staffel-4/folge-2-folge-2-blind-audition-ii-teil-1-m-9827691; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by JHGitty** [comment] 2015-06-06 18:21
myvideo not working? hm.. hope for my info.

**Comment by dstftw** [comment] 2016-02-14 04:43
Duplicate of #4145.

**Closed by dstftw** 2016-02-14 04:43 UTC

**Comment by pejobo** [comment] 2016-02-14 09:48
Still broken, #4145 closed as 'no longer relevant'

**Comment by Hrxn** [comment] 2016-02-15 07:31
@pejobo 
https://github.com/rg3/youtube-dl/issues/8557

**Comment by pejobo** [comment] 2016-02-15 07:36
> #8557
@Hrxn thank you, missed this one
