### ISSUE TITLE
[Deezer] How to download Deezer playlist using deezer.py

### ISSUE THREAD

**Issue by READMEtxt-r** [rg3/youtube-dl#11833] opened 2017-01-25 13:40 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.24*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.24**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

I'm a bit noob when it comes to all this and I can't find anywhere else to post questions regarding youtube-dl, so I'm asking here. If there is somewhere else I should be asking kindly redirect me to the correct place. I want to download Deezer.com playlist using youtube-dl but I can't for the life of me figure out how to use the deezer.py script to download the playlist. If I put the Deezer playlist directly into youtube-dl all it downloads are the 30 second previews. If someone could just help me I'd highly appreciate it, I've been scouring the documentation and google for any help but found nothing. This is my last resort pretty much.

**Comment by dstftw** [comment] 2017-01-25 15:45
Currently only 30 seconds previews are supported.
Duplicate of #10049.

**Closed by dstftw** 2017-01-25 15:45 UTC
