### ISSUE TITLE
Falls back on generic extractor and fails for some pages on tv2.no

### ISSUE THREAD

**Issue by TRox1972** [rg3/youtube-dl#9291] opened 2016-04-23 22:26 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.04.19*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.19**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v http://sumo.tv2.no/programmer/serier/hotel-caesar/hoeydepunkter/jenny-blir-reddet-fra-edvin-904213.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://sumo.tv2.no/programmer/serier/hotel-caesar/hoeydepunkter/jenny-blir-reddet-fra-edvin-904213.html']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2016.04.19
[debug] Python version 2.7.10 - Linux-2.6.32-042stab112.15-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, ffmpeg 11.2-6
[debug] Proxy map: {}
[generic] jenny-blir-reddet-fra-edvin-904213: Requesting header
WARNING: Falling back on generic information extractor.
[generic] jenny-blir-reddet-fra-edvin-904213: Downloading webpage
[generic] jenny-blir-reddet-fra-edvin-904213: Extracting information
ERROR: Unsupported URL: http://sumo.tv2.no/programmer/serier/hotel-caesar/hoeydepunkter/jenny-blir-reddet-fra-edvin-904213.html
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1374, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 279, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=etree.TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 268, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 673, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2044, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://sumo.tv2.no/programmer/serier/hotel-caesar/hoeydepunkter/jenny-blir-reddet-fra-edvin-904213.html
```

### Description of your *issue*, suggested solution and other information

When trying to run the program on some sites on tv2.no, e.g. sumo.tv2.no, it falls back on the generic extractor instead of using the TV2 extractor and fails.

**Comment by dstftw** [comment] 2016-04-24 03:28
Duplicate of #9130.

**Closed by dstftw** 2016-04-24 03:28 UTC

**Comment by TRox1972** [comment] 2016-04-25 11:21
Sorry, didn't see that. I think changing the _VALID_URL so that it also covers sumo.tv2.no will solve the issue.
