### ISSUE TITLE
Getting error while trying to download certain type of videos!

### ISSUE THREAD

**Issue by Bryannn** [rg3/youtube-dl#8605] opened 2016-02-19 02:04 UTC
Hi, lately I've been not able to download & convert these kind of videos. 

https://www.youtube.com/watch?v=etT1pp39EIw

https://www.youtube.com/watch?v=-2BmIBbGZeI

when i try to download them via terminal console they are downloading in segments as you can see in the image & then an error occurs.

![error](https://cloud.githubusercontent.com/assets/13772933/13164325/5385468e-d6da-11e5-9cc3-11243a13e8cc.jpg)

If you could fix this would be highly appreciated. Thanks!

**Comment by dstftw** [comment] 2016-02-19 15:19
Duplicate of #8466.

**Closed by dstftw** 2016-02-19 15:19 UTC
