### ISSUE TITLE
site support request

### ISSUE THREAD

**Issue by rellik31** [rg3/youtube-dl#14239] opened 2017-09-17 15:16 UTC
hi, can someone please add these sites to youtube-dl

http://www.tntdrama.com/shows/animal-kingdom/clips/inside-the-episode-karma
http://www.tbs.com/shows/american-dad/clips/makeover-plans

thanks.

**Comment by rellik31** [comment] 2017-10-02 10:38
are they not possible to download with youtube-dl?

**Comment by remitamine** [comment] 2017-12-11 11:59
Duplicate of #13658.

**Closed by remitamine** 2017-12-11 11:59 UTC
