### ISSUE TITLE
can't download channels anymore

### ISSUE THREAD

**Issue by computerfreak105** [rg3/youtube-dl#14082] opened 2017-08-31 05:34 UTC
Single videos are still working, wohle channels aren't.

G:\>youtube-dl --cookies cookies.txt --username PRIVATE --pas
sword PRIVATE -f 140/m4a -i -o F:\yt/%(uploader)s/%(title)s_%(upload_date)s_%
(autonumber)s.%(ext)s -a you.txt --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'cookies.txt', '--username', 'PRIVATE',
 '--password', 'PRIVATE', '-f', '140/m4a', '-i', '-o', 'F:\\yt/%(uploader)s/%(ti
tle)s_%(upload_date)s_%(autonumber)s.%(ext)s', '-a', 'you.txt', '--verbose']
[debug] Batch file urls: ['https://www.youtube.com/channel/UCJLlzmRbgBvi7sDtv1Wk
wXg']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.08.27.1
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:channel] Downloading login page
[youtube:channel] Looking up account info
[youtube:channel] Logging in
[youtube:channel] Checking cookie
[youtube:channel] UCJLlzmRbgBvi7sDtv1WkwXg: Downloading channel page
[youtube:channel] UCJLlzmRbgBvi7sDtv1WkwXg: Downloading page #1
[download] Downloading playlist: UCJLlzmRbgBvi7sDtv1WkwXg
[youtube:channel] playlist UCJLlzmRbgBvi7sDtv1WkwXg: Downloading 0 videos
[download] Finished downloading playlist: UCJLlzmRbgBvi7sDtv1WkwXg

Hope this helps, thanks.

**Comment by limiteddi** [comment] 2017-08-31 10:06
I have the same problem

**Comment by MatrixAndrew** [comment] 2017-08-31 10:36
Bump. Actually 1 out of 100 times it may still work.

**Comment by danieltdavis** [comment] 2017-08-31 12:54
I have the same problem

**Comment by kenstuddy** [comment] 2017-09-01 05:28
I have been able to replicate this problem on Ubuntu 16.04 LTS.

**Comment by C4K3** [comment] 2017-09-01 09:41
Duplicate of #14083

**Closed** 2017-09-01 17:21 UTC
