### ISSUE TITLE
Need help with code or I have an idea for your project

### ISSUE THREAD

**Issue by aleks5323** [rg3/youtube-dl#11862] opened 2017-01-28 13:47 UTC
Hello. I downloaded source of youtube-dl and I was trying to add "custom autonumber option". When you're downloading a lot of videos with (autonumber)s option and after interruption this number starts over. I was trying to make program that use a number from file, assign this number to the video file, increase this value and writing it back in file after video has been downloaded. I want to ask you where is the code that downloads videos. OR May i ask you to make this feature by yourself? Thank you.

**Comment by dstftw** [comment] 2017-01-28 13:50
Duplicate of #2702.

**Closed by dstftw** 2017-01-28 13:50 UTC
