### ISSUE TITLE
Youtube 403 forbidden workaround

### ISSUE THREAD

**Issue by hbt** [rg3/youtube-dl#6560] opened 2015-08-14 15:20 UTC
Youtube started returning a 403 on some videos.

Example of video: http://youtu.be/gTAghAJcO1o

Downloading this locally, returns a 403 
However downloading from my server works just fine. 

Same youtube-dl versions on both servers.

The urls are different though. Servers are in different countries. 

US server returns 
https://r19---sn-ab5l6nes.googlevideo.com/videoplayback?sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&requiressl=yes&sver=3&key=yt5&upn=4ML4hTdT6-Y&lmt=1398745018776159&expire=1439586782&ip=2600%3A3c03%3A%3Af03c%3A91ff%3Afeae%3Ae3b7&itag=22&mm=31&ipbits=0&mn=sn-ab5l6nes&source=youtube&mv=m&mime=video%2Fmp4&ms=au&dur=2629.241&initcwndbps=34235000&id=o-ADoV7CbIQYcJY48BDmTb0KH6rWRX2rb1eJC2zWQN5j-K&pl=32&fexp=9405966%2C9406993%2C9407535%2C9408501%2C9408710%2C9409069%2C9415365%2C9415485%2C9415554%2C9416023%2C9416126%2C9416231%2C9416347%2C9416687%2C9417082%2C9417577%2C9417707%2C9418153%2C9418392%2C9418455%2C9419304%2C9419444&mt=1439565149&ratebypass=yes&signature=2A57A38657A1B3A93539532D02B10CA77BA3FE8D.7A798A29057F4C802EB53B0DE189174B0407937E

Canadian server returns
https://r7---sn-ux3n588t-mjhe.googlevideo.com/videoplayback?source=youtube&upn=9xuFTaxaWYk&ratebypass=yes&lmt=1398745018776159&expire=1439586715&ipbits=0&initcwndbps=1237500&pl=23&key=yt5&requiressl=yes&itag=22&dur=2629.241&ms=au&mt=1439565016&mv=m&pcm2cms=yes&ip=192.0.162.10&mm=31&fexp=9406629%2C9408504%2C9408710%2C9409069%2C9409170%2C9414703%2C9415365%2C9415485%2C9415822%2C9416023%2C9416126%2C9416331%2C9416729%2C9417707%2C9418153%2C9418204%2C9418223%2C9418643&mn=sn-ux3n588t-mjhe&sver=3&id=o-AL-u-OGM_iHfJ8djnn5lQbDvVysunOF3C7Si_1s57YoI&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&mime=video%2Fmp4&signature=0646D5A5D05DD8D6261FA654A421CB63B94036AE56.3DA2957FCF94E66CCCC6A98FFD8B6588FC8E0968

Video is visible on both sites but cannot be downloaded

I can access the first URL directly 

Let me know if you need any more information to find a workaround.

**Comment by dstftw** [comment] 2015-08-14 15:21
Duplicate of #6451. Remove cache with `youtube-dl --rm-cache-dir`.

**Closed by dstftw** 2015-08-14 15:21 UTC

**Comment by hbt** [comment] 2015-08-14 15:24
Thank you!
