### ISSUE TITLE
Crunchyroll: No video formats found

### ISSUE THREAD

**Issue by DaviSojogos** [rg3/youtube-dl#10315] opened 2016-08-12 16:58 UTC
youtube_dl -v http://www.crunchyroll.com/rezero-starting-life-in-another-world-/rezero-kara-hajimeru-isekai-seikatsu-o-fim-do-comeo-e-o-comeo-do-fim-parte-1-702401
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.crunchyroll.com/rezero-starting-life-in-another-world-/rezero-kara-hajimeru-isekai-seikatsu-o-fim-do-comeo-e-o-comeo-do-fim-parte-1-702401']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.12
[debug] Python version 2.7.12 - Linux-4.4.0-31-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[Crunchyroll] 702401: Downloading webpage
[Crunchyroll] 702401: Downloading media info for 360p
[Crunchyroll] 702401: Downloading media info for 480p
[Crunchyroll] 702401: Downloading media info for 720p
[Crunchyroll] 702401: Downloading media info for 1080p
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/davi/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "/home/davi/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/home/davi/.local/lib/python2.7/site-packages/youtube_dl/extractor/crunchyroll.py", line 370, in _real_extract
    self._sort_formats(formats)
  File "/home/davi/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 901, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment] 2016-08-12 17:04
Duplicate of #10301.

**Closed by dstftw** 2016-08-12 17:04 UTC
