### ISSUE TITLE
OpenLoad.Co issue!

### ISSUE THREAD

**Issue by hi-too** [rg3/youtube-dl#11389] opened 2016-12-08 07:22 UTC
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://openload.co/embed/oCp3d8xvr1A']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.01
[debug] Python version 2.7.6 - Linux-4.4.4-std-3-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
[Openload] oCp3d8xvr1A: Downloading webpage
ERROR: Unable to extract encrypted code; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/root/telebot/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/root/telebot/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/root/telebot/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/openload.py", line 118, in _real_extract
    webpage, 'encrypted code')
  File "/root/telebot/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/common.py", line 669, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/root/telebot/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/common.py", line 660, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract encrypted code; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment] 2016-12-08 07:29
Duplicate of #10408

**Closed by yan12125** 2016-12-08 07:29 UTC
