### ISSUE TITLE
 HTTP Error 403

### ISSUE THREAD

**Issue by hqmaker** [rg3/youtube-dl#6800] opened 2015-09-08 10:02 UTC
root:/var/www/****/data/www/*****# youtube-dl -o 'files/songs/%(i                                                                                        d)s.%(ext)s' --extract-audio --audio-format mp3 --prefer-ffmpeg http://www.youtu                                                                                        be.com/watch?v=6nG_URWEJ9Q
[youtube] 6nG_URWEJ9Q: Downloading webpage
[youtube] 6nG_URWEJ9Q: Downloading video info webpage
[youtube] 6nG_URWEJ9Q: Extracting video information
[youtube] 6nG_URWEJ9Q: Downloading DASH manifest
[youtube] 6nG_URWEJ9Q: Downloading js player new
[youtube] 6nG_URWEJ9Q: Downloading DASH manifest
WARNING: [youtube] 6nG_URWEJ9Q: Skipping DASH manifest: ExtractorError(u'Could n                                                                                        ot download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); pl                                                                                        ease report this issue on https://yt-dl.org/bug . Make sure you are using the la                                                                                        test version; type  youtube-dl -U  to update. Be sure to call youtube-dl with th                                                                                        e --verbose flag and include its complete output.',)
[download] Destination: files/songs/6nG_URWEJ9Q.m4a
[download] 100% of 7.85MiB in 00:00
[ffmpeg] Correcting container in "files/songs/6nG_URWEJ9Q.m4a"
[ffmpeg] Destination: files/songs/6nG_URWEJ9Q.mp3
Deleting original file files/songs/6nG_URWEJ9Q.m4a (pass -k to keep)

it is through the putty.
In a php script is not working team. When warning stops

**Comment by hqmaker** [comment] 2015-09-08 10:05
version 2015.07.07

**Comment by jaimeMF** [comment] 2015-09-08 10:09
Duplicate of #6451. You are using an outdated version, [you have to update youtube-dl](https://github.com/rg3/youtube-dl/blob/8f9d522f6252f874d41045b2458256ca8cf1a312/README.md#how-do-i-update-youtube-dl).

Side note: **don't run youtube-dl as the root user**, it's an unnecessary risk.

**Closed by jaimeMF** 2015-09-08 10:09 UTC
