### ISSUE TITLE
Udemy downloads failing at login popup

### ISSUE THREAD

**Issue by Kaetee** [rg3/youtube-dl#15683] opened 2018-02-22 22:58 UTC
I am using the latest version and I have verified that the username and password are correct.

The videos are accessible via the browser and even downloadable using IDM.

Everything was working perfectly today morning.

Here is the log.

```
C:\Users\User\Downloads\Programs\YouTube DL>youtube-dl --verbose -u 'email@domain.com' -p 'password' https://www.udemy.com/master-android-7-nougat-java-app-development-step-by-step/learn/v4/overview --config-location config.txt
[debug] System config: []
[debug] User config: []
[debug] Custom config: ['-o', 'C:/Users/User/Downloads/Programs/YouTube DL/Videos/%(playlist)s/%(chapter_number)s-%(chapter)s/%(autonumber)03d-%(title)s.%(ext)s', '-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[height<=1080]', '--ffmpeg-location', 'C:/ffmpeg/bin', '--prefer-ffmpeg', '--embed-subs', '--retries', '10']
[debug] Command-line args: ['--verbose', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www.udemy.com/master-android-7-nougat-java-app-development-step-by-step/learn/v4/overview', '--config-location', 'config.txt']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.02.22
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1
[debug] Proxy map: {}
[udemy:course] Downloading login popup
ERROR: Unable to download webpage: HTTP Error 403: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkxz8b_33\build\youtube_dl\extractor\common.py", line 519, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkxz8b_33\build\youtube_dl\YoutubeDL.py", line 2199, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

**Comment by yan12125** [comment] 2018-02-23 08:06
Duplicate of #15571

**Closed by yan12125** 2018-02-23 08:06 UTC
