### ISSUE TITLE
SkillsMatter not supported even cookies is specified

### ISSUE THREAD

**Issue by luochen1990** [rg3/youtube-dl#11631] opened 2017-01-07 17:17 UTC
I'm trying to use the latest version of youtube-dl to download video from skillsmatter.com, with cookies specified, but not working.

The version of youtube-dl:

```
$ youtube-dl.exe --version
2017.01.05
```

I'm using:
- Windows 10 (64bit)
- Python 2.7.10 (64bit)
- Chrome 57.0.2970.0 (64bit)

The cookies file is got via [cookies.txt](https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg)  version 1.10.0  (which is the currently latest version).

I'm trying the `with --cookies <FILE>` way mentioned in [this issue](https://github.com/rg3/youtube-dl/issues/1602) by @jaimeMF 

And the entire information I got is below: 

```
$ youtube-dl.exe -v --cookies ./cookies.txt https://skillsmatter.com/skillscasts/3241-haskell-cloud
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--cookies', u'./cookies.txt', u'https://skillsmatter.com/skillscasts/3241-haskell-cloud']
[debug] Encodings: locale cp936, fs mbcs, out None, pref cp936
[debug] youtube-dl version 2017.01.05
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-81043-ga49ed9e, ffprobe N-81043-ga49ed9e
[debug] Proxy map: {'ftp': 'ftp://127.0.0.1:1080', 'http': 'http://127.0.0.1:1080', 'https': 'https://127.0.0.1:1080'}
[generic] 3241-haskell-cloud: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 3241-haskell-cloud: Downloading webpage
[generic] 3241-haskell-cloud: Extracting information
ERROR: Unsupported URL: https://skillsmatter.com/skillscasts/3241-haskell-cloud
Traceback (most recent call last):
  File "c:\dev\python27\lib\site-packages\youtube_dl\extractor\generic.py", line 1685, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "c:\dev\python27\lib\site-packages\youtube_dl\compat.py", line 2526, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "c:\dev\python27\lib\site-packages\youtube_dl\compat.py", line 2515, in _XML
    parser.feed(text)
  File "c:\dev\python27\lib\xml\etree\ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "c:\dev\python27\lib\xml\etree\ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 27, column 311
Traceback (most recent call last):
  File "c:\dev\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "c:\dev\python27\lib\site-packages\youtube_dl\extractor\common.py", line 359, in extract
    return self._real_extract(url)
  File "c:\dev\python27\lib\site-packages\youtube_dl\extractor\generic.py", line 2507, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://skillsmatter.com/skillscasts/3241-haskell-cloud
```

Some other related issue:
- https://github.com/rg3/youtube-dl/issues/6219
- https://github.com/rg3/youtube-dl/issues/1883

**Comment by dstftw** [comment] 2017-01-07 17:25
Duplicate of #1883.

**Closed by dstftw** 2017-01-07 17:25 UTC

**Comment by luochen1990** [comment] 2017-01-07 17:31
@dstftw  So the fact that `--cookies` option is not working on skillsmatter.com is expected ?

**Comment by dstftw** [comment] 2017-01-07 17:34
Using `--cookies` does not guarantee you anything.
