### ISSUE TITLE
Error for IQIYI

### ISSUE THREAD

**Issue by Token713** [rg3/youtube-dl#9899] opened 2016-06-25 17:20 UTC
> 2016.06.25

>youtube-dl http://www.iqiyi.com/v_19rrkyywoo.html
[iqiyi] temp_id: download video page
[iqiyi] 7f13d67408c4d737588e84d3c8b0985b: Downloading JSON metadata
[iqiyi] 7f13d67408c4d737588e84d3c8b0985b: Download path key of segment 1 for for
mat h3
[iqiyi] 7f13d67408c4d737588e84d3c8b0985b: Download video info of segment 1 for f
ormat h3
[iqiyi] 7f13d67408c4d737588e84d3c8b0985b: Download path key of segment 1 for for
mat h6
[iqiyi] 7f13d67408c4d737588e84d3c8b0985b: Download video info of segment 1 for f
ormat h6
[iqiyi] 7f13d67408c4d737588e84d3c8b0985b: Download path key of segment 1 for for
mat h5
[iqiyi] 7f13d67408c4d737588e84d3c8b0985b: Download video info of segment 1 for f
ormat h5
[download] Destination: 广告宣传片-7f13d67408c4d737588e84d3c8b0985b.f4v
[download] 100% of 16.39MiB in 00:10

>

For all urls from IQIYI,it will download the video named 广告宣传片.f4v all the time.

**Comment by yan12125** [comment] 2016-06-25 17:21
Duplicate of #9839.

**Closed by yan12125** 2016-06-25 17:21 UTC
