### ISSUE TITLE
Unrecognized FLV files from nbc.com

### ISSUE THREAD

**Issue by selvagem** [rg3/youtube-dl#5912] opened 2015-06-07 00:28 UTC
This is a very strange problem. After downloading this video (I believe you need a US connection),the flv file downloaded is unrecognizable by ffmpeg, vlc, media info, or virtually any software I have been able to use.  I am curious what is going on here, any ideas? 

And although there is a list of different flv files to download, they all have the same problem. 
My guess is perhaps there is some sort of codec on the flv files that is not freely available. 

 
Computer:~ user$ youtube-dl http://www.nbc.com/saturday-night-live/video/flex/n11113 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.nbc.com/saturday-night-live/video/flex/n11113', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 2.7.3 - Darwin-14.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.6.3, ffprobe 2.6.3, rtmpdump 2.4
[debug] Proxy map: {}
[NBC] n11113: Downloading webpage
[ThePlatform] S1Ixbswf7THc: Downloading config
[ThePlatform] S1Ixbswf7THc: Downloading XML
[ThePlatform] S1Ixbswf7THc: Downloading webpage
[ThePlatform] S1Ixbswf7THc: Downloading f4m manifest
[debug] Invoking downloader on u'http://nbcdotcom-f.akamaihd.net/z/NBCdotCOM/e07050370303ada95a74943688ce6f1e_,1296,1696,0896,0696,0496,0306,0240,0150,0064,.mp4.csmil/manifest.f4m?&g=UXWGVKRWHFSP&hdcore=3.0.3'
[download] Flex-S1Ixbswf7THc.flv has already been downloaded
[download] 100% of 0.00B
Computer:~ user$ youtube-dl http://www.nbc.com/saturday-night-live/video/flex/n11113 -F
[NBC] n11113: Downloading webpage
[ThePlatform] S1Ixbswf7THc: Downloading config
[ThePlatform] S1Ixbswf7THc: Downloading XML
[ThePlatform] S1Ixbswf7THc: Downloading webpage
[ThePlatform] S1Ixbswf7THc: Downloading f4m manifest
[info] Available formats for S1Ixbswf7THc:
format code  extension  resolution note
75           flv        unknown      75k 
173          flv        unknown     173k 
257          flv        unknown     257k 
314          flv        unknown     314k 
495          flv        unknown     495k 
685          flv        unknown     685k 
886          flv        unknown     886k 
1277         flv        unknown    1277k 
1686         flv        unkn

Please excuse me, I missed the very last section when I copied the data.

**Comment by dstftw** [comment] 2015-06-07 00:46
Can you watch it in browser?

**Comment by selvagem** [comment] 2015-06-07 00:59
yes, when you go to the website the video does play

**Comment by yan12125** [comment] 2015-06-08 07:01
I can reproduce the problem with a United States proxy, however I can't find out the problem.

**Comment by fstirlitz** [comment] 2015-07-11 16:24
That stream is encrypted with Akamai DRM. You can detect that by checking for FLV packets of type 10 and 11. This is ultimately the same problem as #6175.

#5910 contains some code which partially parses FLV packets (though for a different reason); if you merged that, adding a DRM check would be very easy. It might use some reviewing first, though.

**Comment by fb39ca4** [comment] 2015-07-13 05:58
Here is some information on generating the tokens. Still need to figure out what to do with them afterwards.
http://stream-recorder.com/forum/showpost.php?p=43761&postcount=13

**Comment by remitamine** [comment] 2015-08-01 11:13
in this video the segments contain the AkamaiBox which point to the url of the key file(IV) needed to decrypt the segment.
example of a key file for this video(base64):
BfOwSB5lxXJjVngKtuWsXw==
it change every time you play the video in the browser or trying to download it.
it's not what @fb39ca4 is talking about because the pvtoken is generated using the playerVerificationChallenge which is not present in the manifest of this video(in these pull request there is an example of the playerVerificationChallenge).

**Comment by remitamine** [comment] 2016-03-17 19:16
the extractor now extract m3u8 manifest.

**Closed by remitamine** 2016-03-17 19:16 UTC
Labels: f4m
