### ISSUE TITLE
Youtube "unable to login" HTTP error 404

### ISSUE THREAD

**Issue by rpedrica** [rg3/youtube-dl#10142] opened 2016-07-22 18:57 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.07.22*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.22**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl https://www.youtube.com/watch?v=vUPxVYAnz_E
[debug] System config: []
[debug] User config: [u'--mark-watched', u'--no-playlist', u'-o', u'/home/path/Desktop/videos/youtube/%(uploader)s-%(title)s.%(ext)s', u'-v', u'-f', u'(mp4)[height<560]', u'-n']
[debug] Command-line args: [u'https://www.youtube.com/watch?v=vUPxVYAnz_E']
[debug] Encodings: locale ISO-8859-1, fs ISO-8859-1, out ISO-8859-1, pref ISO-8859-1
[debug] youtube-dl version 2016.07.22
[debug] Python version 2.7.11 - Linux-4.4.14-x86_64-AMD_FX-tm-6350_Six-Core_Processor-with-slackware-14.2
[debug] exe versions: ffmpeg 2.1, ffprobe 2.1
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Logging in
WARNING: unable to log in: HTTP Error 404: Not Found
[youtube] vUPxVYAnz_E: Downloading webpage
[youtube] vUPxVYAnz_E: Downloading video info webpage
[youtube] vUPxVYAnz_E: Extracting video information
[youtube] vUPxVYAnz_E: Downloading MPD manifest
[youtube] vUPxVYAnz_E: Marking watched
...
<end of log>
```

---

---

I've been using 2016.06.26 previously without issue. Today however, youtube-dl will not login to youtube with my details so that the videos can be marked as watched - the error is shown above in the output. The video itself still downloads correctly.

I've updated to 2016.07.22 but the issue persists. I'm using a config file:

```
--mark-watched
--no-playlist
-o '/home/path/Desktop/videos/youtube/%(uploader)s-%(title)s.%(ext)s'
-v
-f '(mp4)[height<560]'
-n
```

Neither the config file nor my .netrc has changed from when it worked previously ( as recently as 1 week ago ). I've also logged in manually into youtube through my browser with the same credentials and I've tested video in my browser without issue.

Any assistance is appreciated. Robby

**Comment by dstftw** [comment] 2016-07-22 19:00
Add `--dump-pages` and post the output.

**Comment by rpedrica** [comment] 2016-07-22 19:22
Ok so I re-ran my download script and now it's working?!?!?! I did --dump-pages but it outputs a huge amount of code - do you still want this or do you have an idea why the login was not working earlier?

**Comment by dstftw** [comment] 2016-07-22 19:27
I only need the output of non-working authentication. If you can't reproduce it then I'm closing the issue.

**Closed by dstftw** 2016-07-22 19:27 UTC
Labels: cant-reproduce
