### ISSUE TITLE
Soundcloud - Unable to download JSON metadata 401

### ISSUE THREAD

**Issue by supgilad** [rg3/youtube-dl#6979] opened 2015-09-26 11:50 UTC
@@HI
@@Calling 
  youtube-dl.exe -x -v  https://soundcloud.com/didaktiik/sets/dreamy 
@@Returns

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-x', u'-v', u'https://soundcloud.com/didaktiik/set
s/dreamy']
[debug] Encodings: locale cp1255, fs mbcs, out cp862, pref cp1255
[debug] youtube-dl version 2015.09.22
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-55702-g920046a, ffprobe N-55702-g920046a
[debug] Proxy map: {}
[soundcloud:set] didaktiik/sets/dreamy: Resolving id
[soundcloud:set] didaktiik/sets/dreamy: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by
 HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you
 are using the latest version; type  youtube-dl -U  to update. Be sure to call y
outube-dl with the --verbose flag and include its complete output.
  File "youtube_dl\extractor\common.pyo", line 326, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1865, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default

@@ALSO, youtube works fine but soundcloud does not!

**Comment by dstftw** [comment] 2015-09-26 11:51
Duplicate of #6930.

**Closed by dstftw** 2015-09-26 11:51 UTC
