### ISSUE TITLE
Facebook video not downloading for some reason

### ISSUE THREAD

**Issue by mx-bashworkzcom** [rg3/youtube-dl#8590] opened 2016-02-17 18:12 UTC
here is output with verbose set on it -

[root@vs2 logs]# youtube-dl -U
youtube-dl is up-to-date (2016.02.13)
[root@vs2 logs]# /usr/local/bin/youtube-dl https://www.facebook.com/aromeoua/videos/1161279910550337/
[facebook] 1161279910550337: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError(u'instances',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[root@vs2 logs]# /usr/local/bin/youtube-dl --verbose https://www.facebook.com/aromeoua/videos/1161279910550337/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.facebook.com/aromeoua/videos/1161279910550337/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.13
[debug] Python version 2.6.6 - Linux-2.6.32-042stab103.6-x86_64-with-centos-6.7-Final
[debug] exe versions: ffprobe N-57307-g23c0698, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] 1161279910550337: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError(u'instances',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 315, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 189, in _real_extract
    for item in server_js_data['instances']:
KeyError: u'instances'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 321, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'instances',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

If you need anything else please let me know

**Comment by dstftw** [comment] 2016-02-17 19:59
Duplicate of #8572.

**Closed by dstftw** 2016-02-17 19:59 UTC
