### ISSUE TITLE
Unable to download a Facebook's video.

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#11951] opened 2017-02-02 22:34 UTC
$ youtube-dl -v https://www.facebook.com/BlueManGroupFans/posts/1439219159445373
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.facebook.com/BlueManGroupFans/posts/1439219159445373']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.01
[debug] Python version 3.4.2 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.7
[debug] exe versions: ffmpeg 3.2.2-1, ffprobe 3.2.2-1, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] 1439219159445373: Downloading webpage
ERROR: Unable to extract video ids; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 369, in extract
    return self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 354, in _real_extract
    webpage, 'video ids', group='ids'),
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 672, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video ids; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Thank you in advance. :)

**Comment by kalemi19** [comment] 2017-02-03 01:06
I had the same issue, around the same time. It went away after I updated my youtube-dl to the latest version.

**Comment by antdude** [comment] 2017-02-03 01:41
Hmm, I already have the latest:
$ youtube-dl -U
youtube-dl is up-to-date (2017.02.01)

**Comment by yan12125** [comment] 2017-02-03 03:53
Duplicate of #11017

**Closed by yan12125** 2017-02-03 03:53 UTC
