### ISSUE TITLE
Adding Track number to metadata

### ISSUE THREAD

**Issue by AyrA** [rg3/youtube-dl#9179] opened 2016-04-13 11:04 UTC
### Version check
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.13**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [X] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

When downloading a complete playlist it would be great, if the metadata command line switch would also add the track number (position in playlist) to the file.

**Comment by dstftw** [comment] 2016-05-01 05:23
Duplicate of #7393.

**Closed by dstftw** 2016-05-01 05:23 UTC
