### ISSUE TITLE
problem with a certain youtube video

### ISSUE THREAD

**Issue by shirkdarmstadt** [rg3/youtube-dl#12068] opened 2017-02-10 15:16 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.10**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections

### What is the purpose of your *issue*?
- [X ] Bug report (encountered problems with youtube-dl)

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Cannot use best option to download 720p version of video...has always worked before.  Download starts then fails with "content too short" or "html server error".  Only is happening with this specific video.

 youtube-dl -v -f "best[height<=720]"  tdHGBzlRPK8
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-f', u'best[height<=720]', u'tdHGBzlRPK8']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.10
[debug] Python version 2.7.5 - Linux-3.10.0-229.el7.x86_64-x86_64-with-centos-7.1.1503-Core
[debug] exe versions: ffmpeg 2.3.4, ffprobe 2.3.4
[debug] Proxy map: {}
[youtube] tdHGBzlRPK8: Downloading webpage
[youtube] tdHGBzlRPK8: Downloading video info webpage
[youtube] tdHGBzlRPK8: Extracting video information
[youtube] tdHGBzlRPK8: Downloading MPD manifest
[youtube] tdHGBzlRPK8: Downloading MPD manifest
[debug] Invoking downloader on u'https://r1---sn-p5qs7n7l.googlevideo.com/videoplayback?mime=video%2Fmp4&requiressl=yes&lmt=1485313592970286&ei=3NedWI2YIcKf8gSz7rigAw&id=o-AHBXLnRjRenMOdxKNlpeJ8sQDIDOBJ8c8IilIjWjQdDB&mn=sn-p5qs7n7l&mm=31&upn=Q8piLBV8ink&ip=72.45.62.4&key=yt6&ms=au&mv=m&mt=1486739372&ipbits=0&initcwndbps=1347500&signature=48516513087F23370409B9E0E4940663738C655C.9F95FC89E911012CD98877635793C8B13CC531C7&ratebypass=yes&expire=1486761020&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&itag=22&pl=21&dur=415.474&source=youtube'
[download] Resuming download at byte 8388644
[download] Got server HTTP error. Retrying (attempt 1 of 10)...
[download] Got server HTTP error. Retrying (attempt 2 of 10)...
[download] Got server HTTP error. Retrying (attempt 3 of 10)...
[download] Got server HTTP error. Retrying (attempt 4 of 10)...
[download] Got server HTTP error. Retrying (attempt 5 of 10)...
[download] Got server HTTP error. Retrying (attempt 6 of 10)...
[download] Got server HTTP error. Retrying (attempt 7 of 10)...
[download] Got server HTTP error. Retrying (attempt 8 of 10)...
[download] Got server HTTP error. Retrying (attempt 9 of 10)...
[download] Got server HTTP error. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2006, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: Internal Server Error

**Comment by dstftw** [comment] 2017-02-10 15:18
Duplicate of #3721.

**Closed by dstftw** 2017-02-10 15:18 UTC
