### ISSUE TITLE
Google drive link not working

### ISSUE THREAD

**Issue by mitguru007** [rg3/youtube-dl#11502] opened 2016-12-21 05:26 UTC
Hello!
  When use 
 "youtube-dl -J https://drive.google.com/file/d/0B0OiLIKFGQWKNFI0aWdLbXg4aTQ/view""
command and open any download url in browser then get error 
"Access to r3---sn-ab5l6nzk.c.docs.google.com was denied"
(Error: http://imgur.com/a/sjeEr)

However, the download work fine in server side when use "youtube-dl drive_link" command.
i found some drive video link from internet that get redirect to main url and that working fine.
https://lh3.googleusercontent.com/CJcz_V67tL-MJhzkoW2Ai0KzE0CuNtvSzgV_hnAwHoEGEa35_vtfMRWKBxzYf_7hBwM=m22

when run "youtube-dl -J drive_url" command then  get thumbnail url like "https://lh6.googleusercontent.com/CEF8QKJsCKqdg0Rb4yoY_l0OyOjog6dxfoq5O0nKFvxWvz5kLaozyw=w1200-h630-p"
but not showing video url like https://lh3.googleusercontent.com/CJcz_V67t........

so, how to get https://lh3.googleusercontent.com/CJc...  working url?
Thanks in advance for help,

**Comment by yan12125** [comment] 2016-12-21 05:37
Duplicate of #11084. You need to pass cookies, too.

**Closed by yan12125** 2016-12-21 05:37 UTC

**Comment by mitguru007** [comment] 2016-12-21 05:39
okay bro, 
but how to get https://lh3.googleusercontent.com/CJcz_V67tL-MJhzkoW2Ai0KzE0CuNtvSzgV_hnAwHoEGEa35_vtfMRWKBxzYf_7hBwM=m22
type link?

**Comment by yan12125** [comment] 2016-12-21 05:47
> i found some drive video link from internet

You might want to ask how they found the links. URLs started with r3---sn-ab5l6nzk.c.docs.google.com are exactly what Google Drive provides.

**Comment by mitguru007** [comment] 2016-12-21 05:53
bro if youtube-dl get thumbnail url https://lh6.googleusercontent.com/CEF8QKJsCKqdg0Rb4yoY_l0OyOjog6dxfoq5O0nKFvxWvz5kLaozyw=w1200-h630-p

then why youtube-dl not give video url like  https://lh3.googleusercontent.com/CJcz_V...
i think url structure is same then why miss youtube-dl this kind of video url?

**Comment by yan12125** [comment] 2016-12-21 07:17
> why miss youtube-dl this kind of video url?

youtube-dl searches for video URLs in the webpage. Google Drive doesn't provide video URLs like lh3.googleusercontent/..., so youtube-dl can't find. it.

**Comment by mitguru007** [comment] 2016-12-21 07:21
"Cookie": "NID=93=LrtV0ys95KUMsy67It8vzjQV-A2fzfr3RuoVL35Y1acRfqNSpP6E4xuxyVmbCoRJCnV0RSfYvSu3d879Nzxs3SxMfeTN1F-uPEjQNenbATuOSQLRc4skYSRdsRTB5CO0; DRIVE_STREAM=RjlAlFNGMgk"}

which is name of cookie and which is value? 
sorry for  my question.  Thanks

**Comment by yan12125** [comment] 2016-12-21 11:40
Name is NID and 93=Lrt... is the value

**Comment by dungvaph03374** [comment] 2017-10-08 19:22
been a year and the link still working
