### ISSUE TITLE
Adulltswim extractor broken

### ISSUE THREAD

**Issue by Rocksteady18** [rg3/youtube-dl#14250] opened 2017-09-18 13:48 UTC
Hi,
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.15**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Trying to get new Rick and Morty and this happens:

        
    [debug] System config: []    
    [debug] User config: []    
    [debug] Custom config: []    
    [debug] Command-line args: ['--ap-mso=DTV', '--ap-username=PRIVATE', 'http://www.adultswim.com/videos/rick-and-morty/mortys-mind-blowers', '--verbose']    
    Type TV provider account password and press [Return]:    
    [debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252    
    [debug] youtube-dl version 2017.09.15    
    [debug] Python version 3.4.4 - Windows-10-10.0.14393    
    [debug] exe versions: ffmpeg 3.0.2    
    [debug] Proxy map: {}    
    [AdultSwim] mortys-mind-blowers: Downloading webpage    
    [AdultSwim] sUCOK3V2SNq46JBhJyzBcQ: Downloading XML    
    [AdultSwim] 1477814: Downloading Provider Redirect Page    
    [AdultSwim] 1477814: Downloading Provider Login Page    
    [AdultSwim] 1477814: Logging in    
    ERROR: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.    
    Traceback (most recent call last):    
      File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\build\youtube_dl\YoutubeDL.py", line 776, in extract_info    
      File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\build\youtube_dl\extractor\common.py", line 434, in extract    
      File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\build\youtube_dl\extractor\adultswim.py", line 138, in _real_extract    
      File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\build\youtube_dl\extractor\turner.py", line 79, in _extract_cvp_info    
      File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\build\youtube_dl\extractor\adobepass.py", line 1511, in _extract_mvpd_auth    
      File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\build\youtube_dl\extractor\adobepass.py", line 1360, in post_form    
      File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\build\youtube_dl\extractor\common.py", line 806, in _html_search_regex    
      File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\build\youtube_dl\extractor\common.py", line 797, in _search_regex    
    youtube_dl.utils.RegexNotFoundError: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.    
        
Ah jeez Rick, please help.

**Comment by remitamine** [comment] 2018-05-30 02:07
Duplicate of #12997.

**Closed by remitamine** 2018-05-30 02:07 UTC
