### ISSUE TITLE
[youku.com] Bug report: Videos don't merge automatically after download

### ISSUE THREAD

**Issue by ztytian** [rg3/youtube-dl#10893] opened 2016-10-10 06:16 UTC
Issues: While trying to download videos from youku.com it downloaded into separate file instead of a complete one.

The debug log is shown below:

youtube-dl -v http://v.youku.com/v_show/id_XMTc0ODYxOTE4OA==.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://v.youku.com/v_show/id_XMTc0ODYxOTE4OA==.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.07
[debug] Python version 2.7.12 - Darwin-16.0.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 3.1.4, ffprobe 3.1.4
[debug] Proxy map: {}
[youku] XMTc0ODYxOTE4OA: Downloading JSON metadata
[download] Downloading playlist: 第698话 和解之印
[youku] playlist 第698话 和解之印: Collected 11 video ids (downloading 11 of them)
[download] Downloading video 1 of 11
[debug] Invoking downloader on u'http://k.youku.com/player/getFlvPath/sid/647607962493512e13e8e_00/st/flv/fileid/0300800B0057F47652A2E51468DEFE1A6CC46D-CF24-2FDF-8726-C1A6FC2D766F?ypp=0&myp=0&K=60680a6ddc725a40282bcb8a&ctype=12&token=2929&ev=1&ep=dCaTHEmKX8gC4SrcjT8bMi3hIX9aXP4J9h%2BNgdIQALshT567njjUxeyyO%2FpDEv8RBldwZeqAraOUbkZgYYM1q2wQ3TjcT%2Fro%2BfLl5d5StZZ2FRtCdcvRwlScSjL4&hd=1&oip=1964834764'
[download] Destination: 第698话 和解之印-XMTc0ODYxOTE4OA_part1.flv
[download]   5.1% of 51.49MiB at 125.77KiB/s ETA 06:37

I interrupted using control-c as I've downloaded and merged the video manually. The issue is that when a youku video is downloaded it recognizes it as a playlist and downloaded 11 parts of the video into 11 separate files. You might need to add something to recognize the URL and merge using ffmpeg after the download automatically like it can for other sites.
You might need a proxy server to access the video. You can obtain one at https://vnet.one/?rc=2879
This service will connect you to a Chinese IP to use the service (use OpenVPN or else Python Internet Traffic won't go through).

**Comment by yan12125** [comment] 2016-10-10 06:22
Duplicate of #2844. #10054 is useful, too.

**Closed by yan12125** 2016-10-10 06:22 UTC
