### ISSUE TITLE
Cannot download

### ISSUE THREAD

**Issue by RoboTehnik** [rg3/youtube-dl#2614] opened 2014-03-24 06:30 UTC
http://www.vesti.ru/videos?vid=586242

**Comment by jaimeMF** [comment] 2015-01-26 13:44
Closing due to lack of information. If you can reproduce the problem with the last version, post the output of `youtube-dl http://www.vesti.ru/videos?vid=586242 --verbose` and we will reopen the issue.

**Closed by jaimeMF** 2015-01-26 13:44 UTC
