### ISSUE TITLE
youtube download failed even with --no-check-certificates

### ISSUE THREAD

**Issue by 0-wiz-0** [rg3/youtube-dl#13116] opened 2017-05-17 08:48 UTC
I can't download a youtube video. My report #13114 was closed with 'use search' so I searched and found one possible solution, to use `--no-check-certificates`. However, that did not resolve the issue:
````
#  youtube-dl  -v --no-check-certificate https://www.youtube.com/watch?v=DYedXMq-R6I
[debug] System config: []
[debug] User config: ['-f', 'best']
[debug] Custom config: []
[debug] Command-line args: ['-v', '--no-check-certificate', 'https://www.youtube.com/watch?v=DYedXMq-R6I']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.14
[debug] Python version 3.6.1 - NetBSD-7.99.71-amd64-x86_64-64bit-ELF
[debug] exe versions: ffmpeg 2.8.11, ffmpeg2 2.8.11, ffmpeg3 3.3.1, ffprobe 2.8.11, ffprobe2 2.8.11, ffprobe3 3.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] DYedXMq-R6I: Downloading webpage
[youtube] DYedXMq-R6I: Downloading video info webpage
[youtube] DYedXMq-R6I: Extracting video information
WARNING: unable to extract uploader nickname
[youtube] DYedXMq-R6I: Downloading MPD manifest
[youtube] DYedXMq-R6I: Downloading MPD manifest
[debug] Invoking downloader on 'https://r7---sn-4g57knz6.googlevideo.com/videoplayback?initcwndbps=1646250&requiressl=yes&key=yt6&mime=video%2Fmp4&ip=213.47.11.167&upn=dra42cdfXcA&itag=22&signature=974F063C64D27478A100D159CB7C215EBB791D01.917AD0FA3A72F1557A23929EBEBF2EE0C0F38227&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&mt=1495010667&source=youtube&pl=18&mv=m&ipbits=0&ms=au&ei=0w0cWaKgHojYW5uVgOgM&expire=1495032371&mm=31&id=o-AIMojdk6bH4bqhT3jIeF8CQylH9WL8psxfEiHlHBeWJm&mn=sn-4g57knz6&lmt=1493795764417892&dur=622.550&ratebypass=yes'
[download] Got server HTTP error. Retrying (attempt 1 of 10)...
[download] Got server HTTP error. Retrying (attempt 2 of 10)...
[download] Got server HTTP error. Retrying (attempt 3 of 10)...
[download] Got server HTTP error. Retrying (attempt 4 of 10)...
[download] Got server HTTP error. Retrying (attempt 5 of 10)...
[download] Got server HTTP error. Retrying (attempt 6 of 10)...
[download] Got server HTTP error. Retrying (attempt 7 of 10)...
[download] Got server HTTP error. Retrying (attempt 8 of 10)...
[download] Got server HTTP error. Retrying (attempt 9 of 10)...
[download] Got server HTTP error. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries
  File "/usr/pkg/bin/youtube-dl", line 11, in <module>
    load_entry_point('youtube-dl==2017.5.14', 'console_scripts', 'youtube-dl')()
  File "/usr/pkg/lib/python3.6/site-packages/youtube_dl/__init__.py", line 465, in main
    _real_main(argv)
  File "/usr/pkg/lib/python3.6/site-packages/youtube_dl/__init__.py", line 455, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/pkg/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1896, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/pkg/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 771, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/pkg/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 825, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/pkg/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1539, in process_video_result
    self.process_info(new_info)
  File "/usr/pkg/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1803, in process_info
    success = dl(filename, info_dict)
  File "/usr/pkg/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1745, in dl
    return fd.download(name, info)
  File "/usr/pkg/lib/python3.6/site-packages/youtube_dl/downloader/common.py", line 360, in download
    return self.real_download(filename, info_dict)
  File "/usr/pkg/lib/python3.6/site-packages/youtube_dl/downloader/http.py", line 131, in real_download
    self.report_error('giving up after %s retries' % retries)
  File "/usr/pkg/lib/python3.6/site-packages/youtube_dl/downloader/common.py", line 162, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/pkg/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 589, in report_error
    self.trouble(error_message, tb)
  File "/usr/pkg/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 551, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
````
Please advise in more detail what the solution could be. Thank you.

**Comment by dstftw** [comment] 2017-05-17 08:49
Stop posting duplicates. Duplicate of #3721.

**Closed by dstftw** 2017-05-17 08:49 UTC
