### ISSUE TITLE
Signature extraction failed - python runtime error

### ISSUE THREAD

**Issue by meain** [rg3/youtube-dl#7643] opened 2015-11-25 11:30 UTC
Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 744, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 796, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 135, in interpret_expression
    self._objects[variable] = self.extract_object(variable)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 220, in extract_object
    fields = obj_m.group('fields')
AttributeError: 'NoneType' object has no attribute 'group'
 (caused by AttributeError("'NoneType' object has no attribute 'group'",));

**Comment by phihag** [comment] 2015-11-25 11:43
Can you post the entire error output? The output should start with something along the lines of `[debug] System config: []`. Also make sure that you are using the latest version of youtube-dl.

**Comment by phihag** [comment] 2015-11-25 15:32
I am closing this issue for now, because I strongly suspect that your version of youtube-dl is simply out of date. If that is not the case, please post the complete output and we will reopen this issue. Thanks!

**Closed by phihag** 2015-11-25 15:32 UTC

**Comment by atropo** [comment] 2015-11-25 16:48
I can confirm that upgrading to `2015.11.24` solved the issue for me.

**Comment by meain** [comment] 2015-11-26 14:40
I had installed the latest version but still had the error, it is working after a restart. Don't know if it is the restart or not but it is working now.
