### ISSUE TITLE
iplayer - rtmpdump exited with code 1

### ISSUE THREAD

**Issue by EdgarCarpenter** [rg3/youtube-dl#6848] opened 2015-09-13 00:26 UTC
I have gotten this error intermittently for a long time, in the last week I get it for most iplayer shows. 

Thanks for your help and your excellent work!!
Just donated at http://rg3.github.io/youtube-dl/donations.html - I encourage other users to do the same.

-------------------------------------------------------------------------------
 youtube-dl -v http://www.bbc.co.uk/iplayer/episode/b06b7w43/would-i-lie-to-you-series-9-episode-7
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.bbc.co.uk/iplayer/episode/b06b7w43/would-i-lie-to-you-series-9-episode-7']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.09
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-LinuxMint-2-betsy
[debug] exe versions: avconv 2.6.4, avprobe 2.6.4, ffmpeg 2.6.4, ffprobe 2.6.4, rtmpdump 2.4
[debug] Proxy map: {}
[bbc.co.uk] b06b7w43: Downloading video page
[bbc.co.uk] b06b7w40: Downloading media selection XML
[debug] Invoking downloader on u'rtmp://iplayertokfs.fplive.net/iplayertok?token=c3RhcnRfdGltZT0yMDE1MDkxMjIyMTY0MCZlbmRfdGltZT0yMDE1MDkxMzAyMTY0MCZkaWdlc3Q9ZmU3M2NjOGY3NWU1ZTlkNDkxMGZhNTcyZjA5YjkwZmQ='
[download] Destination: Would I Lie to You, Series 9 - Episode 7-b06b7w40.flv
[debug] rtmpdump command line: rtmpdump --verbose -r 'rtmp://iplayertokfs.fplive.net/iplayertok?token=c3RhcnRfdGltZT0yMDE1MDkxMjIyMTY0MCZlbmRfdGltZT0yMDE1MDkxMzAyMTY0MCZkaWdlc3Q9ZmU3M2NjOGY3NWU1ZTlkNDkxMGZhNTcyZjA5YjkwZmQ=' -o 'Would I Lie to You, Series 9 - Episode 7-b06b7w40.flv.part' --swfVfy http://www.bbc.co.uk/emp/releases/iplayer/revisions/617463_618125_4/617463_618125_4_emp.swf --pageUrl http://www.bbc.co.uk --app 'iplayertok?token=c3RhcnRfdGltZT0yMDE1MDkxMjIyMTY0MCZlbmRfdGltZT0yMDE1MDkxMzAyMTY0MCZkaWdlc3Q9ZmU3M2NjOGY3NWU1ZTlkNDkxMGZhNTcyZjA5YjkwZmQ=' --playpath mp4:3200kbps/modav/bUnknown-7639770d-8a59-45fb-b069-fe4a1bbd2174_b06b7w40_1441027203838 --resume --skip 1
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 0
[rtmpdump] DEBUG: Parsed host    : iplayertokfs.fplive.net
[rtmpdump] DEBUG: Parsed app     : iplayertok?token=c3RhcnRfdGltZT0yMDE1MDkxMjIyMTY0MCZlbmRfdGltZT0yMDE1MDkxMzAyMTY0MCZkaWdlc3Q9ZmU3M2NjOGY3NWU1ZTlkNDkxMGZhNTcyZjA5YjkwZmQ=
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMP
[rtmpdump] DEBUG: Hostname : iplayertokfs.fplive.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:3200kbps/modav/bUnknown-7639770d-8a59-45fb-b069-fe4a1bbd2174_b06b7w40_1441027203838
[rtmpdump] DEBUG: tcUrl    : rtmp://iplayertokfs.fplive.net:1935/iplayertok?token=c3RhcnRfdGltZT0yMDE1MDkxMjIyMTY0MCZlbmRfdGltZT0yMDE1MDkxMzAyMTY0MCZkaWdlc3Q9ZmU3M2NjOGY3NWU1ZTlkNDkxMGZhNTcyZjA5YjkwZmQ=
[rtmpdump] DEBUG: swfUrl   : http://www.bbc.co.uk/emp/releases/iplayer/revisions/617463_618125_4/617463_618125_4_emp.swf
[rtmpdump] DEBUG: pageUrl  : http://www.bbc.co.uk
[rtmpdump] DEBUG: app      : iplayertok?token=c3RhcnRfdGltZT0yMDE1MDkxMjIyMTY0MCZlbmRfdGltZT0yMDE1MDkxMzAyMTY0MCZkaWdlc3Q9ZmU3M2NjOGY3NWU1ZTlkNDkxMGZhNTcyZjA5YjkwZmQ=
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: SWFSHA256:
[rtmpdump] DEBUG: b6 74 7f 89 f9 ec 6a 60 c1 a4 b5 8b b1 18 b0 fa
[rtmpdump] DEBUG: 65 18 86 24 c2 8a 1a a3 2f 72 0f 0b 80 59 dd 7f
[rtmpdump] DEBUG: SWFSize  : 595316
[rtmpdump] DEBUG: Setting buffer time to: 36000000ms
[rtmpdump] Connecting ...
[rtmpdump] DEBUG: RTMP_Connect1, ... connected, handshaking
[rtmpdump] DEBUG: HandShake: Client type: 03
[rtmpdump] DEBUG: HandShake: Client digest offset: 430
[rtmpdump] DEBUG: HandShake: Initial client digest: 
[rtmpdump] DEBUG: bd 91 33 66 4e e6 8f 28 4b 0d 8a 0a a6 65 19 69
[rtmpdump] DEBUG: 76 37 0e 84 7b 51 7f 40 44 d8 83 6d a1 67 bf 2e
[rtmpdump] DEBUG: HandShake: Type Answer   : 03
[rtmpdump] DEBUG: HandShake: Server Uptime : 1408909277
[rtmpdump] DEBUG: HandShake: FMS Version   : 4.5.3.1
[rtmpdump] DEBUG: HandShake: Calculated digest key from secure key and server digest: 
[rtmpdump] DEBUG: 09 6a 5a 67 5a 5d 6f e3 5f 31 f6 ee 0a 57 af 09
[rtmpdump] DEBUG: 42 3e 01 77 3e ef 93 bc a0 b5 c6 ab 65 db 64 f3
[rtmpdump] DEBUG: HandShake: Client signature calculated:
[rtmpdump] DEBUG: bf 97 62 64 9d 15 6b 23 2e 09 3a e7 11 bf dd 21
[rtmpdump] DEBUG: 48 8c 7e 41 5e 57 44 46 d3 9e 2a e7 5c 36 40 04
[rtmpdump] DEBUG: HandShake: Server sent signature:
[rtmpdump] DEBUG: 95 99 cd 8c e6 92 3c 4a 4f f0 9b 8a f2 a0 ce 88
[rtmpdump] DEBUG: c0 92 45 51 67 1e f8 7e 57 4c 21 77 c5 79 dd 0f
[rtmpdump] DEBUG: HandShake: Digest key: 
[rtmpdump] DEBUG: 67 5c 17 bf 62 b8 f9 6b 41 48 72 04 75 07 c2 9c
[rtmpdump] DEBUG: 15 5a aa 3f 7c 52 49 06 93 e0 dd 9e e1 7f e7 30
[rtmpdump] DEBUG: HandShake: Signature calculated:
[rtmpdump] DEBUG: 95 99 cd 8c e6 92 3c 4a 4f f0 9b 8a f2 a0 ce 88
[rtmpdump] DEBUG: c0 92 45 51 67 1e f8 7e 57 4c 21 77 c5 79 dd 0f
[rtmpdump] DEBUG: HandShake: Genuine Adobe Flash Media Server
[rtmpdump] DEBUG: HandShake: Handshaking finished....
[rtmpdump] DEBUG: RTMP_Connect1, handshaked
[rtmpdump] DEBUG: Invoking connect
[rtmpdump] INFO: Connected...
[rtmpdump] DEBUG: HandleServerBW: server BW = 2500000
[rtmpdump] DEBUG: HandleClientBW: client BW = 2500000 2
[rtmpdump] DEBUG: HandleChangeChunkSize, received: chunk size change to 16384
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 240 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:             fmsVer, STRING:	FMS/4,5,3,101>
[rtmpdump] DEBUG: Property: <Name:       capabilities, NUMBER:	255.00>
[rtmpdump] DEBUG: Property: <Name:               mode, NUMBER:	1.00>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetConnection.Connect.Success>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:	Connection succeeded.>
[rtmpdump] DEBUG: Property: <Name:     objectEncoding, NUMBER:	0.00>
[rtmpdump] DEBUG: Property: <Name:               data, ECMA_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:            version, STRING:	4,5,3,101>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_result>
[rtmpdump] DEBUG: HandleInvoke, received result for method call <connect>
[rtmpdump] DEBUG: sending ctrl. type: 0x0003
[rtmpdump] DEBUG: Invoking createStream
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 21 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onBWDone>
[rtmpdump] DEBUG: Invoking _checkbw
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 29 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_result>
[rtmpdump] DEBUG: HandleInvoke, received result for method call <createStream>
[rtmpdump] DEBUG: SendPlay, seekTime=0, stopTime=0, sending play: mp4:3200kbps/modav/bUnknown-7639770d-8a59-45fb-b069-fe4a1bbd2174_b06b7w40_1441027203838
[rtmpdump] DEBUG: Invoking play
[rtmpdump] DEBUG: sending ctrl. type: 0x0003
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 16419 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: HandleChangeChunkSize, received: chunk size change to 16384
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 115 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	error>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetStream.Failed>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:	403 Forbidden>
[rtmpdump] DEBUG: Property: <Name:           clientid, STRING:	qAABwiEA>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onStatus>
[rtmpdump] DEBUG: HandleInvoke, onStatus: NetStream.Failed
[rtmpdump] ERROR: Closing connection: NetStream.Failed
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 0 bytes
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 0
[rtmpdump] DEBUG: Parsed host    : iplayertokfs.fplive.net
[rtmpdump] DEBUG: Parsed app     : iplayertok?token=c3RhcnRfdGltZT0yMDE1MDkxMjIyMTY0MCZlbmRfdGltZT0yMDE1MDkxMzAyMTY0MCZkaWdlc3Q9ZmU3M2NjOGY3NWU1ZTlkNDkxMGZhNTcyZjA5YjkwZmQ=
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMP
[rtmpdump] DEBUG: Hostname : iplayertokfs.fplive.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:3200kbps/modav/bUnknown-7639770d-8a59-45fb-b069-fe4a1bbd2174_b06b7w40_1441027203838
[rtmpdump] DEBUG: tcUrl    : rtmp://iplayertokfs.fplive.net:1935/iplayertok?token=c3RhcnRfdGltZT0yMDE1MDkxMjIyMTY0MCZlbmRfdGltZT0yMDE1MDkxMzAyMTY0MCZkaWdlc3Q9ZmU3M2NjOGY3NWU1ZTlkNDkxMGZhNTcyZjA5YjkwZmQ=
[rtmpdump] DEBUG: swfUrl   : http://www.bbc.co.uk/emp/releases/iplayer/revisions/617463_618125_4/617463_618125_4_emp.swf
[rtmpdump] DEBUG: pageUrl  : http://www.bbc.co.uk
[rtmpdump] DEBUG: app      : iplayertok?token=c3RhcnRfdGltZT0yMDE1MDkxMjIyMTY0MCZlbmRfdGltZT0yMDE1MDkxMzAyMTY0MCZkaWdlc3Q9ZmU3M2NjOGY3NWU1ZTlkNDkxMGZhNTcyZjA5YjkwZmQ=
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: SWFSHA256:
[rtmpdump] DEBUG: b6 74 7f 89 f9 ec 6a 60 c1 a4 b5 8b b1 18 b0 fa
[rtmpdump] DEBUG: 65 18 86 24 c2 8a 1a a3 2f 72 0f 0b 80 59 dd 7f
[rtmpdump] DEBUG: SWFSize  : 595316
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.

ERROR: rtmpdump exited with code 1
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 410, in main
    _real_main(argv)
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 400, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1658, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 671, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 717, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1328, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1590, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1532, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/rtmp.py", line 202, in real_download
    self.report_error('rtmpdump exited with code %d' % retval)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 155, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 535, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 497, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

----------------------------------------

This is a similar but different request which gives a slightly different error message when -v is not turned on:

youtube-dl -v http://www.bbc.co.uk/iplayer/episode/b00ml4yv/whisky-galore
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.bbc.co.uk/iplayer/episode/b00ml4yv/whisky-galore']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.09
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-LinuxMint-2-betsy
[debug] exe versions: avconv 2.6.4, avprobe 2.6.4, ffmpeg 2.6.4, ffprobe 2.6.4, rtmpdump 2.4
[debug] Proxy map: {}
[bbc.co.uk] b00ml4yv: Downloading video page
[bbc.co.uk] b0004p5k: Downloading media selection XML
[debug] Invoking downloader on u'rtmp://bbcfmt.fcod.llnwd.net/a8984/e3?as=adobe-hmac-sha256&av=1&te=connect&mp=iplayerstream/secure_auth/480kbps/modav/p03162cl_b0004p5k_1442022848756.mp4,iplayerstream/secure_auth/800kbps/modav/p03162cl_b0004p5k_1442022849968.mp4,iplayerstream/secure_auth/1500kbps/modav/p03162cl_b0004p5k_1442022848777.mp4&et=1442113732&fmta-token=9899eda729b624782a8d7f4ffe94b37ecc13d1236061b89029071955acdaa262'
[download] Destination: Whisky Galore!-b0004p5k.flv
[debug] rtmpdump command line: rtmpdump --verbose -r 'rtmp://bbcfmt.fcod.llnwd.net/a8984/e3?as=adobe-hmac-sha256&av=1&te=connect&mp=iplayerstream/secure_auth/480kbps/modav/p03162cl_b0004p5k_1442022848756.mp4,iplayerstream/secure_auth/800kbps/modav/p03162cl_b0004p5k_1442022849968.mp4,iplayerstream/secure_auth/1500kbps/modav/p03162cl_b0004p5k_1442022848777.mp4&et=1442113732&fmta-token=9899eda729b624782a8d7f4ffe94b37ecc13d1236061b89029071955acdaa262' -o 'Whisky Galore!-b0004p5k.flv.part' --swfVfy http://www.bbc.co.uk/emp/releases/iplayer/revisions/617463_618125_4/617463_618125_4_emp.swf --pageUrl http://www.bbc.co.uk --app 'a8984/e3?as=adobe-hmac-sha256&av=1&te=connect&mp=iplayerstream/secure_auth/480kbps/modav/p03162cl_b0004p5k_1442022848756.mp4,iplayerstream/secure_auth/800kbps/modav/p03162cl_b0004p5k_1442022849968.mp4,iplayerstream/secure_auth/1500kbps/modav/p03162cl_b0004p5k_1442022848777.mp4&et=1442113732&fmta-token=9899eda729b624782a8d7f4ffe94b37ecc13d1236061b89029071955acdaa262' --playpath mp4:iplayerstream/secure_auth/1500kbps/modav/p03162cl_b0004p5k_1442022848777.mp4 --resume --skip 1
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 0
[rtmpdump] DEBUG: Parsed host    : bbcfmt.fcod.llnwd.net
[rtmpdump] DEBUG: Parsed app     : a8984/e3?as=adobe-hmac-sha256&av=1&te=connect&mp=iplayerstream/secure_auth
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMP
[rtmpdump] DEBUG: Hostname : bbcfmt.fcod.llnwd.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:iplayerstream/secure_auth/1500kbps/modav/p03162cl_b0004p5k_1442022848777.mp4
[rtmpdump] DEBUG: tcUrl    : rtmp://bbcfmt.fcod.llnwd.net:1935/a8984/e3?as=adobe-hmac-sha256&av=1&te=connect&mp=iplayerstream/secure_auth/480kbps/modav/p03162cl_b0004p5k_1442022848756.mp4,iplayerstream/secure_auth/800kbps/modav/p03162cl_b0004p5k_1442022849968.mp4,iplayerstream/secure_auth/1500kbps/modav/p03162cl_b0004p5k_1442022848777.mp4&et=1442113732&fmta-token=9899eda729b624782a8d7f4ffe94b37ecc13d1236061b89029071955acdaa262
[rtmpdump] DEBUG: swfUrl   : http://www.bbc.co.uk/emp/releases/iplayer/revisions/617463_618125_4/617463_618125_4_emp.swf
[rtmpdump] DEBUG: pageUrl  : http://www.bbc.co.uk
[rtmpdump] DEBUG: app      : a8984/e3?as=adobe-hmac-sha256&av=1&te=connect&mp=iplayerstream/secure_auth/480kbps/modav/p03162cl_b0004p5k_1442022848756.mp4,iplayerstream/secure_auth/800kbps/modav/p03162cl_b0004p5k_1442022849968.mp4,iplayerstream/secure_auth/1500kbps/modav/p03162cl_b0004p5k_1442022848777.mp4&et=1442113732&fmta-token=9899eda729b624782a8d7f4ffe94b37ecc13d1236061b89029071955acdaa262
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: SWFSHA256:
[rtmpdump] DEBUG: b6 74 7f 89 f9 ec 6a 60 c1 a4 b5 8b b1 18 b0 fa
[rtmpdump] DEBUG: 65 18 86 24 c2 8a 1a a3 2f 72 0f 0b 80 59 dd 7f
[rtmpdump] DEBUG: SWFSize  : 595316
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 0 bytes
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 0
[rtmpdump] DEBUG: Parsed host    : bbcfmt.fcod.llnwd.net
[rtmpdump] DEBUG: Parsed app     : a8984/e3?as=adobe-hmac-sha256&av=1&te=connect&mp=iplayerstream/secure_auth
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMP
[rtmpdump] DEBUG: Hostname : bbcfmt.fcod.llnwd.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:iplayerstream/secure_auth/1500kbps/modav/p03162cl_b0004p5k_1442022848777.mp4
[rtmpdump] DEBUG: tcUrl    : rtmp://bbcfmt.fcod.llnwd.net:1935/a8984/e3?as=adobe-hmac-sha256&av=1&te=connect&mp=iplayerstream/secure_auth/480kbps/modav/p03162cl_b0004p5k_1442022848756.mp4,iplayerstream/secure_auth/800kbps/modav/p03162cl_b0004p5k_1442022849968.mp4,iplayerstream/secure_auth/1500kbps/modav/p03162cl_b0004p5k_1442022848777.mp4&et=1442113732&fmta-token=9899eda729b624782a8d7f4ffe94b37ecc13d1236061b89029071955acdaa262
[rtmpdump] DEBUG: swfUrl   : http://www.bbc.co.uk/emp/releases/iplayer/revisions/617463_618125_4/617463_618125_4_emp.swf
[rtmpdump] DEBUG: pageUrl  : http://www.bbc.co.uk
[rtmpdump] DEBUG: app      : a8984/e3?as=adobe-hmac-sha256&av=1&te=connect&mp=iplayerstream/secure_auth/480kbps/modav/p03162cl_b0004p5k_1442022848756.mp4,iplayerstream/secure_auth/800kbps/modav/p03162cl_b0004p5k_1442022849968.mp4,iplayerstream/secure_auth/1500kbps/modav/p03162cl_b0004p5k_1442022848777.mp4&et=1442113732&fmta-token=9899eda729b624782a8d7f4ffe94b37ecc13d1236061b89029071955acdaa262
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: SWFSHA256:
[rtmpdump] DEBUG: b6 74 7f 89 f9 ec 6a 60 c1 a4 b5 8b b1 18 b0 fa
[rtmpdump] DEBUG: 65 18 86 24 c2 8a 1a a3 2f 72 0f 0b 80 59 dd 7f
[rtmpdump] DEBUG: SWFSize  : 595316
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.

ERROR: rtmpdump exited with code 1
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 410, in main
    _real_main(argv)
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 400, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1658, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 671, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 717, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1328, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1590, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1532, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/rtmp.py", line 202, in real_download
    self.report_error('rtmpdump exited with code %d' % retval)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 155, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 535, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 497, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

**Comment by dstftw** [comment] 2015-09-13 16:19
Duplicate of #2732.
You can try downloading from different content supplier by specifying format code to `-f`. See `-F` for the list of format codes.

**Closed by dstftw** 2015-09-13 16:19 UTC
