### ISSUE TITLE
Codepage issue?

### ISSUE THREAD

**Issue by 486DX50** [rg3/youtube-dl#6076] opened 2015-06-24 23:13 UTC
Hello,
There is a problem when I try to download videos like this:
https://www.youtube.com/watch?v=79vp65pOM58
But on the disk I get a file named "  (1 )-79vp65pOM58.mp4" instead of "Неуловимый Фунтик (1 )-79vp65pOM58.mp4".

**Comment by yan12125** [comment] 2015-06-25 04:55
How did you invoke youtube-dl? Post the full verbose log [with option ```-v```](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient).

**Comment by 486DX50** [comment] 2015-06-29 18:25
Here is a screenshot. Sorry for delay.
![ydl-01](https://cloud.githubusercontent.com/assets/13040802/8415116/7d6a0cf6-1e51-11e5-83ff-9aece2ee637f.png)

**Comment by 486DX50** [comment] 2015-06-29 18:26
The output goes in cp 437, while the source is using 1251. Maybe that's the problem?

**Comment by dstftw** [comment] 2015-06-29 18:26
Duplicate of #5045.
This is intentional behavior for now. See #4787 for the rationale and #5527 for alternative solution discussions.

**Closed by dstftw** 2015-06-29 18:26 UTC
