### ISSUE TITLE
How to get file download progress (file no., percentage, ETA and rate)

### ISSUE THREAD

**Issue by potholiday** [rg3/youtube-dl#5958] opened 2015-06-12 02:34 UTC
Is there a way to get file download progress in the terminal. The --console-title shows the progress and displays progress details in title.

`youtube-dl --extract-audio --audio-quality 0 --console-title   --audio-format mp3 <url>`

But i want those details as an output in terminal and not in the title

eg: `a="hello"; echo $a`

is this possible

**Comment by yan12125** [comment] 2015-06-12 02:38
Does ```--newline``` help?

**Comment by potholiday** [comment] 2015-06-12 05:37
@yan12125  no it doesnt help? i tried it but it is not i want

**Comment by jaimeMF** [comment] 2015-06-12 07:15
The progress is properly outputted to the terminal, could you post the output you get and the way you want to process it?

**Comment by potholiday** [comment] 2015-06-12 08:49
`youtube-dl --extract-audio --audio-quality 0 --newline --audio-format mp3 https://www.youtube.com/watch?v=BmBEwlGCwPI`

This is the out put 
```
[youtube] BmBEwlGCwPI: Downloading webpage
[youtube] BmBEwlGCwPI: Extracting video information
[youtube] BmBEwlGCwPI: Downloading DASH manifest
[download] Destination: Beautiful Aerial Wedding Photography-BmBEwlGCwPI.m4a
[download]   0.4% of 231.51KiB at  6.10KiB/s ETA 00:30
[download]   1.1% of 231.51KiB at 27.07KiB/s ETA 00:10
[download]   4.0% of 231.51KiB at 19.24KiB/s ETA 00:04
[download]   6.5% of 231.51KiB at 75.06KiB/s ETA 00:03
[download]  13.4% of 231.51KiB at 98.22KiB/s ETA 00:03
[download]  28.7% of 231.51KiB at 81.40KiB/s ETA 00:02
[download]  61.7% of 231.51KiB at 91.56KiB/s ETA 00:01
[download]  86.2% of 231.51KiB at 82.96KiB/s ETA 00:00
[download] 100.0% of 231.51KiB at 73.21KiB/s ETA 00:00
[download] 100% of 231.51KiB in 00:02
[ffmpeg] Correcting container in "Beautiful Aerial Wedding Photography-BmBEwlGCwPI.m4a"
WARNING: Your copy of avconv is outdated, update avconv to version 10-0 or newer if you encounter any errors.
[avconv] Destination: Beautiful Aerial Wedding Photography-BmBEwlGCwPI.mp3
WARNING: Your copy of avconv is outdated, update avconv to version 10-0 or newer if you encounter any errors.
Deleting original file Beautiful Aerial Wedding Photography-BmBEwlGCwPI.m4a (pass -k to keep)
```
and i wand only

```
per      time             rate
0.40%	00:30:00	6.10KiB/s
1.10%	00:10:00	27.07KiB/s
4.00%	00:04:00	19.24KiB/s
6.50%	00:03:00	75.06KiB/s
13.40%	00:03:00	98.22KiB/s
28.70%	00:02:00	81.40KiB/s
61.70%	00:01:00	91.56KiB/s
86.20%	00:00:00	82.96KiB/s
100.00%	00:00:00	231.51KiB
```
As separate variable $per, $time, $rate 
i know we can use `awk` but for this complicated output how should i do

**Comment by dstftw** [comment] 2015-06-12 09:04
Generally, you should use an [API](https://github.com/rg3/youtube-dl/blob/a55e36f48d1f0dc5454b144c7373361f284b9236/youtube_dl/YoutubeDL.py#L206-L229). I see little sense overcomplexing progress output with template similar to `-o`.

**Comment by jaimeMF** [comment] 2015-06-12 10:15
Currently you have the option to parse the youtube-dl output or use the python api as @dstftw has mentioned. I'm closing this issue as a duplicate of #152, if we implement it we would offer the download progress as a json output.

**Closed by jaimeMF** 2015-06-12 10:15 UTC

**Comment by potholiday** [comment] 2015-06-12 17:39
I am a little bit confuesed, API and PHP is used for web application right.  I have installed youtube-dl in my ubuntu system
