### ISSUE TITLE
youtube-dl does not work with some URL from http://www.rts.ch

### ISSUE THREAD

**Issue by lnef** [rg3/youtube-dl#5099] opened 2015-03-01 20:18 UTC
nef@ubuntu:~$ youtube-dl --verbose -f best http://www.rts.ch/play/tv/station-horizon/video/deuxieme-chance?id=6576588 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-f', 'best', 'http://www.rts.ch/play/tv/station-horizon/video/deuxieme-chance?id=6576588']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.28
[debug] Python version 2.7.8 - Linux-3.16.0-29-generic-x86_64-with-Ubuntu-14.10-utopic
[debug] exe versions: avconv 11-6, avprobe 11-6
[debug] Proxy map: {}
[RTS] deuxieme-chance: Downloading JSON metadata
[RTS] 6576588: Downloading hds token
[RTS] 6576588: Downloading f4m manifest
ERROR: Unable to download f4m manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 314, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1666, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

nef@ubuntu:~$

**Comment by dstftw** [comment] 2015-03-01 20:22
Can you watch it in browser?

**Comment by lnef** [comment] 2015-03-01 20:30
yes i can watch in Chrome 40 and Internet Expllorer 11 on Windows 8,1 ... but not on firefox ...

**Comment by MichelLanne** [comment] 2015-03-03 15:27
Hi,

With this URL, I also get 
$ youtube-dl --verbose -f best http://www.rts.ch/play/tv/station-horizon/video/deuxieme-chance?id=6576588
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-f', 'best', 'http://www.rts.ch/play/tv/station-horizon/video/deuxieme-chance?id=6576588']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-3.13.0-24-generic-x86_64-with-LinuxMint-17-qiana
[debug] Proxy map: {}
[generic] deuxieme-chance?id=6576588: Requesting header
WARNING: Falling back on generic information extractor.
[generic] deuxieme-chance?id=6576588: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 191, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1157, in urlopen
    return self._opener.open(req)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by MichelLanne** [comment] 2015-03-03 15:30
Hi (bis),

I also have an error with the URL : 
http://www.rts.ch/docs/histoire-vivante/6545790-une-planete-surveillee-1-5-02-03-2015.html?rts_source=rss_a

Is it good for you ?

Thanx.

**Comment by lnef** [comment] 2015-03-03 15:59
Yes, with the URL

http://www.rts.ch/docs/histoire-vivante/6545790-une-planete-surveillee-1-5-02-03-2015.html?rts_source=rss_a

youtube-dl work fine

**Comment by lnef** [comment] 2015-03-03 16:06
Currently the URL 
http://www.rts.ch/play/tv/station-horizon/video/deuxieme-chance?id=6576588
does also not work with a browser ... we need to change the URL for testing !

**Comment by lnef** [comment] 2015-03-03 16:11
Currently the URL
http://www.rts.ch/play/tv/game-of-thrones/video/premier-du-nom?id=6568958
works with a browser (Chrome)

But the URL does not work with youtube-dl:

youtube-dl --verbose -f best http://www.rts.ch/play/tv/game-of-thrones/video/premier-du-nom?id=6568958
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-f', 'best', 'http://www.rts.ch/play/tv/game-of-thrones/video/premier-du-nom?id=6568958']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.03.1
[debug] Python version 2.7.6 - Linux-3.13.0-36-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.16-6, avprobe 9.16-6, rtmpdump 2.4
[debug] Proxy map: {}
[RTS] premier-du-nom: Downloading JSON metadata
[RTS] 6568958: Downloading m3u8 information
[RTS] 6568958: Downloading hds token
[RTS] 6568958: Downloading f4m manifest
ERROR: Unable to download f4m manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 314, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1674, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by MichelLanne** [comment] 2015-03-03 17:57
For me, it doesn't run :

$ youtube-dl --verbose
"http://www.rts.ch/docs/histoire-vivante/6545790-une-planete-surveillee-1-5-02-03-2015.html?rts_source=rss_a"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose',
'http://www.rts.ch/docs/histoire-vivante/6545790-une-planete-surveillee-1-5-02-03-2015.html?rts_source=rss_a']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 -
Linux-3.13.0-24-generic-x86_64-with-LinuxMint-17-qiana
[debug] Proxy map: {}
[generic] 6545790-une-planete-surveillee-1-5-02-03-2015: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 6545790-une-planete-surveillee-1-5-02-03-2015: Downloading webpage
[generic] 6545790-une-planete-surveillee-1-5-02-03-2015: Extracting information
ERROR: Unsupported URL:
http://www.rts.ch/docs/histoire-vivante/6545790-une-planete-surveillee-1-5-02-03-2015.html?rts_source=rss_a;
please report this issue on https://yt-dl.org/bug . Be sure to call
youtube-dl with the --verbose flag and include its complete output.
Make sure you are using the latest version; type  youtube-dl -U  to
update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py",
line 493, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py",
line 158, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py",
line 380, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL:
http://www.rts.ch/docs/histoire-vivante/6545790-une-planete-surveillee-1-5-02-03-2015.html?rts_source=rss_a;
please report this issue on https://yt-dl.org/bug . Be sure to call
youtube-dl with the --verbose flag and include its complete output.
Make sure you are using the latest version; type  youtube-dl -U  to
update.

I could suspect the version update, since the youtue-dl version I have
is 2014.02.17-1.

But when I want to update, I get :
$ youtube-dl -U
It looks like you installed youtube-dl with a package manager, pip,
setup.py or a tarball. Please use that to update.

And my package manager (the one of Linux Mint) doesn't propose
anything newer ...

Then, what's the problem, and how to solve it ..?

ML

PS : Thank's for your great job supporting these kind of tools ..!  ;-)


2015-03-03 17:00 UTC+01:00, lnef <notifications@github.com>:

**Comment by jaimeMF** [comment] 2015-03-03 18:08
@MichelLanne read [our FAQ](https://yt-dl.org/update) for updating youtube-dl.

**Comment by schnapper1920** [comment] 2015-03-16 16:27
It works from this link: http://www.rts.ch/video/fiction/station-horizon/6576588-deuxieme-chance.html

Here are the list of all episodes so far: www.rts.ch/fiction/2015/station-horizon/6603394-voir-et-revoir-les-episodes-de-station-horizon.html

**Comment by lnef** [comment] 2015-03-16 19:15
@schnapper1920 Can you tell me how to set "hls" tag ?

I tried this:

youtube-dl --verbose --hls-prefer-native http://www.rts.ch/video/fiction/station-horizon/6576588-deuxieme-chance.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--hls-prefer-native', 'http://www.rts.ch/video/fiction/station-horizon/6576588-deuxieme-chance.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.15
[debug] Python version 2.7.8 - Linux-3.16.0-29-generic-x86_64-with-Ubuntu-14.10-utopic
[debug] exe versions: avconv 11-6, avprobe 11-6
[debug] Proxy map: {}
[RTS] deuxieme-chance: Downloading JSON metadata
[RTS] 6576588: Downloading hds token
[RTS] 6576588: Downloading f4m manifest
ERROR: Unable to download f4m manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 314, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1679, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by schnapper1920** [comment] 2015-03-16 19:19
"hls" is one of the formats available for this video (-F to list them all, -f to select one).
youtube-dl http://www.rts.ch/video/fiction/station-horizon/6607828-double-jeu.html -f hls

**Comment by lnef** [comment] 2015-03-16 19:58
@schnapper1920 sorry but for me the download of the available formats (-F) and the download of the video with the option (-f hls) does not work !?

I have youtube-dl version 2015.03.15, what is your version ?

youtube-dl --verbose http://www.rts.ch/video/fiction/station-horizon/6607828-double-jeu.html -F
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.rts.ch/video/fiction/station-horizon/6607828-double-jeu.html', '-F']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.15
[debug] Python version 2.7.8 - Linux-3.16.0-29-generic-x86_64-with-Ubuntu-14.10-utopic
[debug] exe versions: avconv 11-6, avprobe 11-6
[debug] Proxy map: {}
[RTS] double-jeu: Downloading JSON metadata
[RTS] 6607828: Downloading hds token
[RTS] 6607828: Downloading f4m manifest
ERROR: Unable to download f4m manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 314, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1679, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)


youtube-dl --verbose http://www.rts.ch/video/fiction/station-horizon/6607828-double-jeu.html -f hls
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.rts.ch/video/fiction/station-horizon/6607828-double-jeu.html', '-f', 'hls']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.15
[debug] Python version 2.7.8 - Linux-3.16.0-29-generic-x86_64-with-Ubuntu-14.10-utopic
[debug] exe versions: avconv 11-6, avprobe 11-6
[debug] Proxy map: {}
[RTS] double-jeu: Downloading JSON metadata
[RTS] 6607828: Downloading hds token
[RTS] 6607828: Downloading f4m manifest
ERROR: Unable to download f4m manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 314, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1679, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by schnapper1920** [comment] 2015-03-16 20:16
I'm using the 2014.04.21.6 and it works well. The latest version surprinsingly doesn't work...

However...
720p version: http://rtsch-i.akamaihd.net/i/staho/2015/staho_20150228_full_f_837717-,101,701,701,1201,k.mp4.csmil/master.m3u8
480p version: http://ioschvod.tsr.ch.edgesuite.net/staho/2015/staho_20150228_full_f_837717-1201k.mp4

**Comment by lnef** [comment] 2015-03-16 21:41
Exactly the latest version does not work but the old version 2014.04.21.6 works !

I installed the old version 2014.04.21.6 and it works better !

But I can only download hls, hls_sd and tv formats !


youtube-dl --verbose http://www.rts.ch/video/fiction/station-horizon/6607828-double-jeu.html -F
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.rts.ch/video/fiction/station-horizon/6607828-double-jeu.html', '-F']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.04.21.6
[debug] Python version 2.7.8 - Linux-3.16.0-29-generic-x86_64-with-Ubuntu-14.10-utopic
[debug] Proxy map: {}
[RTS] 6607828: Downloading JSON metadata
[info] Available formats for 6607828:
format code extension resolution  note 
hds         f4m       unknown     (unsupported)  (worst)
hds_sd      f4m       unknown     (unsupported) 
hls         m3u8      unknown     
hls_sd      m3u8      unknown     
flv-501k    flv       unknown      501k 
mp4-101k    mp4       unknown      101k 
mp4-701k    mp4       unknown      701k 
download    mp4       unknown     1201k 
mp4-1201k   mp4       unknown     1201k 
tv          mp4       unknown     1201k 
mp4-2201k   mp4       unknown     2201k  (best)

**Comment by dstftw** [comment] 2015-10-10 20:48
Duplicate of #4989.

**Closed by dstftw** 2015-10-10 20:48 UTC
