### ISSUE TITLE
Hitbox.tv VOD error

### ISSUE THREAD

**Issue by willfe** [rg3/youtube-dl#5516] opened 2015-04-24 01:11 UTC
I'm seeing some weird malformed/incomplete URLs being generated (or provided by Hitbox; I'm unsure which) with youtube-dl 2015.04.17. It's done this with every VOD I've tried (about two dozen):

```
$ youtube-dl --verbose http://www.hitbox.tv/video/464640
[debug] System config: []
[debug] User config: [u'--output', u'%(uploader)s-%(upload_date)s-%(id)s %(title)s.%(ext)s', u'--restrict-filenames']
[debug] Command-line args: [u'--verbose', u'http://www.hitbox.tv/video/464640']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.17
[debug] Python version 2.7.9 - Linux-3.19.0-14-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: ffmpeg 2.5.4-1, ffprobe 2.5.4-1, rtmpdump 2.4
[debug] Proxy map: {}
[hitbox] 464640: Downloading JSON metadata
[hitbox] 464640: Downloading JSON metadata
[debug] Invoking downloader on u'/api/player/hlsvod/464640.m3u8'
[download] Destination: NovaWar-20150325-464640 Playing_Bloodborne_1.mp4
ffmpeg version 2.5.4-1 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.9.2 (Ubuntu 4.9.2-10ubuntu7)
  configuration: --prefix=/usr --extra-version=1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --shlibdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --enable-shared --disable-stripping --enable-avresample --enable-avisynth --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libshine --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libwavpack --enable-libwebp --enable-libxvid --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzvbi --enable-libzmq --enable-frei0r --enable-libvpx --enable-libx264 --enable-libsoxr --enable-gnutls --enable-openal --enable-libopencv --enable-librtmp --enable-libx265
  libavutil      54. 15.100 / 54. 15.100
  libavcodec     56. 13.100 / 56. 13.100
  libavformat    56. 15.102 / 56. 15.102
  libavdevice    56.  3.100 / 56.  3.100
  libavfilter     5.  2.103 /  5.  2.103
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
/api/player/hlsvod/464640.m3u8: No such file or directory


ERROR: ffmpeg exited with code 1
  File "/usr/local/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 404, in main
    _real_main(argv)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 394, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1451, in download
    res = self.extract_info(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 662, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 708, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1155, in process_video_result
    self.process_info(new_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1384, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1359, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 341, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/hls.py", line 50, in real_download
    self.report_error('%s exited with code %d' % (ffpp.basename, retval))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 154, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 529, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 491, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
```

**Comment by yan12125** [comment] 2015-04-24 03:51
The problem is fixed in git but not in the latest stable release yet. Please wait patiently for the next version of youtube-dl.

**Closed by yan12125** 2015-04-24 03:51 UTC

**Comment by willfe** [comment] 2015-04-24 11:39
I just cloned the repo and tested; picture perfect now! Thanks :)
