### ISSUE TITLE
Get http url youtube 

### ISSUE THREAD

**Issue by sysmer** [rg3/youtube-dl#5927] opened 2015-06-08 11:23 UTC
HI!
'youtube-dl -g bla bla bla' return https url,  how to get http url?
If I change https to http, video can not be downloaded.

Help me!

**Comment by yan12125** [comment] 2015-06-08 11:52
Seems youtube is moving to HTTPS almost everywhere. For example, browsing http://www.youtube.com/ leads to https://www.youtube.com/. I'm not sure whether there's a method to disable such a redirection. If not, it's impossible to extract an HTTP url.

Can you describe your scenario in more details? I think in most cases HTTPS is not worse than HTTP.

**Comment by sysmer** [comment] 2015-06-08 12:25
yan12125, http url possible, for example http://ru.savefrom.net/ return http url.
I want to use youtube-dl to xupnpd media server, xupnpd not work with https.

**Comment by jaimeMF** [comment] 2015-06-08 12:46
http urls can only be obtained with the `www.youtube.com/get_video_info?...` pages, but since their webplayer doesn't use them we don't use them (except for some videos). I'm closing the issue as a duplicate of #4510.

> I want to use youtube-dl to xupnpd media server, xupnpd not work with https.

The correct solutions would be to make xupnpd work with https urls, YouTube may drop http support at any time and it's widely used nowadays.

**Closed by jaimeMF** 2015-06-08 12:46 UTC
