### ISSUE TITLE
WARNING: [youtube] qlPx6tmAIlM: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError());

### ISSUE THREAD

**Issue by mohe2015** [rg3/youtube-dl#6194] opened 2015-07-11 12:13 UTC
youtube-dl -f 140 --verbose https://www.youtube.com/watch?v=qlPx6tmAIlM
Output:
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-f', u'140', u'--verbose', u'https://www.youtube.com/watch?v=qlPx6tmAIlM']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.07
[debug] Python version 2.7.6 - Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca
[debug] exe versions: ffmpeg 2.7.1, ffprobe 2.7.1
[debug] Proxy map: {}
[youtube] qlPx6tmAIlM: Downloading webpage
[youtube] qlPx6tmAIlM: Downloading video info webpage
[youtube] qlPx6tmAIlM: Extracting video information
[youtube] {22} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {43} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {18} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {5} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {36} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {17} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {137} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {248} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {136} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {247} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {135} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {244} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {134} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {243} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {133} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {242} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {160} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {278} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {140} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {171} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {249} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {250} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] {251} signature length 41.42, html5 player en_US-vflVsMRd_
[youtube] qlPx6tmAIlM: Downloading DASH manifest
[youtube] qlPx6tmAIlM: Downloading player https://s.ytimg.com/yts/jsbin/html5player-en_US-vflVsMRd_/html5player.js
[youtube] qlPx6tmAIlM: Downloading DASH manifest
WARNING: [youtube] qlPx6tmAIlM: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[debug] Invoking downloader on 'https://r4---sn-5hnedn7s.googlevideo.com/videoplayback?id=aa53f1ead9802253&itag=140&source=youtube&requiressl=yes&mm=31&pl=18&mn=sn-5hnedn7s&mv=m&ms=au&nh=IgpwcjAyLmFtczA0KgkxMjcuMC4wLjE&ratebypass=yes&mime=audio/mp4&gir=yes&clen=3340767&lmt=1431930633820517&dur=210.303&mt=1436616180&key=dg_yt0&upn=H-RYIjfvPnQ&fexp=901453,901816,9406990,9408142,9408420,9408710,9416126&signature=97155D5B090A9E384D94F10284C51DF53C82BE11.1047172D758CB6B370B7FE701C2B63D10EF353D5&sver=3&ip=79.240.197.4&ipbits=0&expire=1436637895&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,pl,mn,mv,ms,nh,ratebypass,mime,gir,clen,lmt,dur'
[download] Madcon - Don't Worry (Official Lyric Video) ft. Ray Dalton-qlPx6tmAIlM.m4a has already been downloaded
[download] 100% of 3.18MiB
[ffmpeg] Correcting container in "Madcon - Don't Worry (Official Lyric Video) ft. Ray Dalton-qlPx6tmAIlM.m4a"
[debug] ffmpeg command line: ffmpeg -y -i 'Madcon - Don'"'"'t Worry (Official Lyric Video) ft. Ray Dalton-qlPx6tmAIlM.m4a' -c copy -f mp4 'Madcon - Don'"'"'t Worry (Official Lyric Video) ft. Ray Dalton-qlPx6tmAIlM.temp.m4a'

youtube-dl --version
Output:
2015.07.07

**Comment by dstftw** [comment] 2015-07-11 12:53
Duplicate of #5118.

**Closed by dstftw** 2015-07-11 12:53 UTC
