### ISSUE TITLE
[Feature Request] multiple connections

### ISSUE THREAD

**Issue by rsd3k** [rg3/youtube-dl#3747] opened 2014-09-14 01:30 UTC
Is there a way to enable multiple connections for download. Some download clients (eg aria2, Jdownloader) have the feature of specifying the number of connections.

**Comment by steebchen** [comment] 2015-10-12 21:35
Yeah that would be really great for sites like nowvideo.li.

**Comment by yan12125** [comment] 2015-10-13 18:24
FYI: aria2 is supported as a external downloader. For example:
```
youtube-dl --external-downloader aria2c --external-downloader-args "--options --for --aria2c"
```

**Comment by steebchen** [comment] 2015-10-13 21:42
Thank you, that's great.

**Comment by yan12125** [comment] 2016-10-27 11:39
Closed as duplicate of #350

**Closed by yan12125** 2016-10-27 11:39 UTC
Labels: request

**Comment by yan12125** [comment] 2016-10-27 11:46
Sorry, #350 is somewhat different. Follow #1498 instead.
