### ISSUE TITLE
403 in YT

### ISSUE THREAD

**Issue by pecey** [rg3/youtube-dl#6618] opened 2015-08-20 01:42 UTC
I am getting a 403 error while downloading YT videos from the last couple of hours.
![screenshot_2015-08-20_07-10-53](https://cloud.githubusercontent.com/assets/11463842/9373683/b9e682c2-470a-11e5-984b-7f788e291821.png)

**Comment by yan12125** [comment] 2015-08-20 03:06
Duplicate of #6451. Use ```youtube-dl --rm-cache-dir``` to clear caches. Please paste texts instead of images the next time. Also, don't forget to [include the ```-v``` flag](https://github.com/rg3/youtube-dl#bugs).

**Closed by yan12125** 2015-08-20 03:06 UTC
