### ISSUE TITLE
ERROR: Signature extraction failed: Traceback (most recent call last): 

### ISSUE THREAD

**Issue by mitguru007** [rg3/youtube-dl#11676] opened 2017-01-11 09:44 UTC
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    if player_url.startswith('//'):
  File "/usr/lib/python2.6/site-packages/youtube_dl/extractor/youtube.py", line 932, in _extract_signature_function

----
* youtube-dl-2017.1.10

url = 'https://www.youtube.com/watch?v=1n-g0IhmNuQ'
ydl = YoutubeDL()
info  = ydl.extract_info(url, download=False)

not get error with "1n-g0IhmNuQ" in last 10 month but suddenly start error (Signature extraction failed: Traceback) so, i update youtube-dl version to 2017.1.10. but, get same error after update to latest version.

Please fix this error.
Thanks,

**Comment by knightmar3z** [comment] 2017-01-11 16:17
How was this issue solved?

**Comment by yan12125** [comment] 2017-01-11 16:34
@knightmar3z It's already fixed in version 2017.01.10

**Comment by mitguru007** [comment] 2017-01-13 06:16
some time error got automatically.
after update to version 2017.01.10 then one day work fine but after one day error start again.

**Comment by yan12125** [comment] 2017-01-13 09:21
Please paste the log it things are broken.
```
$ youtube-dl -vF 1n-g0IhmNuQ 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vF', '1n-g0IhmNuQ']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.01.10
[debug] Git HEAD: 365d136b7
[debug] Python version 3.6.0 - Linux-4.9.0-1-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 1n-g0IhmNuQ: Downloading webpage
[youtube] 1n-g0IhmNuQ: Downloading video info webpage
[youtube] 1n-g0IhmNuQ: Extracting video information
[youtube] {22} signature length 44.40, html5 player en_US-vflC029_L
[youtube] 1n-g0IhmNuQ: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vflC029_L/base.js
[youtube] {43} signature length 44.40, html5 player en_US-vflC029_L
[youtube] {18} signature length 44.40, html5 player en_US-vflC029_L
[youtube] {36} signature length 44.40, html5 player en_US-vflC029_L
[youtube] {17} signature length 44.40, html5 player en_US-vflC029_L
[youtube] {137} signature length 44.40, html5 player en_US-vflC029_L
[youtube] {248} signature length 44.40, html5 player en_US-vflC029_L
[youtube] {136} signature length 44.40, html5 player en_US-vflC029_L
[youtube] {247} signature length 44.40, html5 player en_US-vflC029_L
[youtube] {135} signature length 44.40, html5 player en_US-vflC029_L
[youtube] {244} signature length 44.40, html5 player en_US-vflC029_L
[youtube] {134} signature length 44.40, html5 player en_US-vflC029_L
[youtube] {243} signature length 44.40, html5 player en_US-vflC029_L
[youtube] {133} signature length 44.38, html5 player en_US-vflC029_L
[youtube] 1n-g0IhmNuQ: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vflC029_L/base.js
[youtube] {242} signature length 44.40, html5 player en_US-vflC029_L
[youtube] {160} signature length 44.40, html5 player en_US-vflC029_L
[youtube] {278} signature length 44.40, html5 player en_US-vflC029_L
[youtube] {140} signature length 44.40, html5 player en_US-vflC029_L
[youtube] {171} signature length 44.40, html5 player en_US-vflC029_L
[youtube] {249} signature length 44.40, html5 player en_US-vflC029_L
[youtube] {250} signature length 44.40, html5 player en_US-vflC029_L
[youtube] {251} signature length 44.40, html5 player en_US-vflC029_L
[info] Available formats for 1n-g0IhmNuQ:
format code  extension  resolution note
249          webm       audio only DASH audio   59k , opus @ 50k, 1008.10KiB
250          webm       audio only DASH audio   88k , opus @ 70k, 1.38MiB
140          m4a        audio only DASH audio  128k , m4a_dash container, mp4a.40.2@128k, 2.30MiB
171          webm       audio only DASH audio  142k , vorbis@128k, 2.29MiB
251          webm       audio only DASH audio  167k , opus @160k, 2.65MiB
160          mp4        256x144    144p  111k , avc1.4d400c, 25fps, video only, 1.99MiB
278          webm       256x144    144p  124k , webm container, vp9, 13fps, video only, 1.91MiB
133          mp4        426x240    240p  255k , avc1.4d4015, 25fps, video only, 4.47MiB
242          webm       426x240    240p  261k , vp9, 25fps, video only, 4.07MiB
243          webm       640x360    360p  479k , vp9, 25fps, video only, 7.48MiB
134          mp4        640x360    360p  636k , avc1.4d401e, 25fps, video only, 7.78MiB
244          webm       854x480    480p  888k , vp9, 25fps, video only, 13.43MiB
135          mp4        854x480    480p 1168k , avc1.4d401e, 25fps, video only, 15.53MiB
247          webm       1280x720   720p 1721k , vp9, 25fps, video only, 26.31MiB
136          mp4        1280x720   720p 2322k , avc1.4d401f, 25fps, video only, 28.59MiB
248          webm       1920x1080  1080p 2984k , vp9, 25fps, video only, 47.30MiB
137          mp4        1920x1080  1080p 4220k , avc1.640028, 25fps, video only, 50.95MiB
17           3gp        176x144    small , mp4v.20.3,  mp4a.40.2@ 24k
36           3gp        320x180    small , mp4v.20.3,  mp4a.40.2
43           webm       640x360    medium , vp8.0,  vorbis@128k
18           mp4        640x360    medium , avc1.42001E,  mp4a.40.2@ 96k
22           mp4        1280x720   hd720 , avc1.64001F,  mp4a.40.2@192k (best)
```

**Comment by mitguru007** [comment] 2017-01-13 10:35
No problem using command line. Working fine via ssh comand line.
But, get error with django. With bellow code. Suddenly start the error.

ydl = YoutubeDL()
info = ydl.extract_info(url, download=False)

**Comment by yan12125** [comment] 2017-01-13 12:46
```ydl = YoutubeDL({'verbose': True})``` to print verbose logs

**Comment by TopazHarley** [comment] 2017-01-16 15:35
I'm receiving a similar extraction error on Linux Mint 18.1 serena/cinnamon using youtube-dl (2017.01.14)

Adding my output, hope it helps 


`toppy@serena ~ $ youtube-dl --verbose -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' https://youtu.be/mSgnC5eQ5u0
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-f', u'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', u'https://youtu.be/mSgnC5eQ5u0']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.22
[debug] Python version 2.7.12 - Linux-4.4.0-59-generic-x86_64-with-LinuxMint-18.1-serena
[debug] exe versions: avconv 2.8.10-0ubuntu0.16.04.1, avprobe 2.8.10-0ubuntu0.16.04.1, ffmpeg 2.8.10-0ubuntu0.16.04.1, ffprobe 2.8.10-0ubuntu0.16.04.1, rtmpdump 2.4-n111-gitfa8646d-ppa9p2
[debug] Proxy map: {}
[youtube] mSgnC5eQ5u0: Downloading webpage
[youtube] mSgnC5eQ5u0: Downloading video info webpage
[youtube] mSgnC5eQ5u0: Extracting video information
[youtube] {22} signature length 41.42, html5 player en_US-vflR62D9G
[youtube] mSgnC5eQ5u0: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vflR62D9G/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 905, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 820, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 883, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'Gi'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'Gi'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 905, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 820, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 883, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'Gi'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 316, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1407, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 915, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 905, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 820, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 883, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'Gi'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'Gi'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`

**Comment by dstftw** [comment] 2017-01-16 15:37
@TopazHarley from your log
>[debug] youtube-dl version 2016.02.22

**Closed by dstftw** 2017-01-16 15:37 UTC
Labels: cant-reproduce, clarification-needed

**Comment by TopazHarley** [comment] 2017-01-16 15:40
@dstftw 
toppy@serena ~ $ sudo youtube-dl -U
youtube-dl is up-to-date (2017.01.14)

I originally installed from Mint/Ubuntu repos, then used manual install from GitHub ... let me remove all and start over :-)

**Comment by TopazHarley** [comment] 2017-01-16 15:56
@dstftw 
thanks Sergey, that fixed it .... repo istalled to /usr/bin ... manual install installed to usr/local/bin so it did not update to latest version
thanks for the help
