### ISSUE TITLE
caused by HTTPError()

### ISSUE THREAD

**Issue by amkrankruleuen** [rg3/youtube-dl#4517] opened 2014-12-19 13:36 UTC
youtube-dl -e --verbose "https://www.youtube.com/watch?v=bH4YSVZOq-U"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-e', '--verbose', 'https://www.youtube.com/watch?v=bH4YSVZOq-U']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.12.17.2
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.7
[debug] exe versions: avconv 0.8.16-6, avprobe 0.8.16-6, ffmpeg 2.3.git, ffprobe 2.3.git
[debug] Proxy map: {}
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 276, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1370, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 407, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 520, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 445, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 528, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by jaimeMF** [comment] 2015-06-06 09:37
Closing as duplicate of #154.

**Closed by jaimeMF** 2015-06-06 09:37 UTC
