### ISSUE TITLE
Unable to download videos from udemy

### ISSUE THREAD

**Issue by mkranthikmr** [rg3/youtube-dl#8787] opened 2016-03-07 17:50 UTC
E:\Course\BDD> youtube-dl -u username@gmail.com -p password***** -v https://www.udemy.com/rubyonrails-bdd-rspec-capybara/learn/v4/content
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-v', u'https://www.udemy.com/rubyonrails-bdd-rspec-c
apybara/learn/v4/content']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.03.01
[debug] Python version 2.7.11 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] Logging in as username@gmail.com
[udemy:course] rubyonrails-bdd-rspec-capybara: Downloading webpage
[udemy:course] rubyonrails-bdd-rspec-capybara: Downloading course JSON
[udemy:course] 531360: Downloading course curriculum
[download] Downloading playlist: BDD with Ruby on Rails using RSpec 3 and Capybara
[udemy:course] playlist BDD with Ruby on Rails using RSpec 3 and Capybara: Collected 83 video ids (downloading 83 of the
m)
[download] Downloading video 1 of 83
[udemy] Downloading login popup
[udemy] 3431226: Downloading webpage
ERROR: Unable to extract course id; please report this issue on https://yt-dl.org/bug . Make sure you are using the late
st version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and incl
ude its complete output.
Traceback (most recent call last):
File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 666, in extract_info
ie_result = ie.extract(url)
File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 316, in extract
return self._real_extract(url)
File "c:\python27\lib\site-packages\youtube_dl\extractor\udemy.py", line 147, in _real_extract
r'data-course-id="\'', webpage, 'course id')
File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 611, in _search_regex
raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract course id; please report this issue on https://yt-dl.org/bug . Make sure you are u
sing the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose
flag and include its complete output.

this is the output I get when I try download

**Comment by dstftw** [comment] 2016-03-07 19:27
**Post the full output of youtube-dl when run with `-v`**, i.e. **add** `-v` flag to **your command line**, copy the **whole** output and post it in the issue body wrapped in \`\`\` for better formatting. It should look similar to this:
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.06
[debug] Git HEAD: 135392e
[debug] Python version 2.6.6 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
```
**Do not post screenshots of verbose log only plain text is acceptable.**

The output (including the first lines) contains important debugging information. Issues without the full output are often not reproducible and therefore do not get solved in short order, if ever.

**Comment by dstftw** [comment] 2016-03-07 19:27
Duplicate of #8753.

**Closed by dstftw** 2016-03-07 19:27 UTC
