### ISSUE TITLE
Skipping DASH manifest: ExtractorError

### ISSUE THREAD

**Issue by amkrankruleuen** [rg3/youtube-dl#6468] opened 2015-08-05 14:29 UTC
youtube-dl --user-agent "Mozilla" --cache-dir "/tmp" --default-search "ytsearch" https://www.youtube.com/watch?v=4R1vIkL3rog -f mp4 --add-metadata --audio-format mp3 -x --prefer-ffmpeg --audio-quality 320K
[youtube] 4R1vIkL3rog: Downloading webpage
[youtube] 4R1vIkL3rog: Downloading video info webpage
[youtube] 4R1vIkL3rog: Extracting video information
[youtube] 4R1vIkL3rog: Downloading DASH manifest
WARNING: [youtube] 4R1vIkL3rog: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
ERROR: unable to download video data: HTTP Error 403: Forbidden

**Comment by dstftw** [comment] 2015-08-05 14:39
Duplicate of #6451.

**Closed by dstftw** 2015-08-05 14:39 UTC
