### ISSUE TITLE
Count --max-downloads only if the file actually is downloaded

### ISSUE THREAD

**Issue by davidhedlund** [rg3/youtube-dl#2349] opened 2014-02-08 17:01 UTC
youtube-dl --version
2014.02.08

Etnica - Floating Universe
[youtube:search] query "Etnica - Floating Universe": Downloading page 1
[download] Downloading playlist: Etnica - Floating Universe
[youtube:search] playlist Etnica - Floating Universe: Collected 10 video ids (downloading 10 of them)
[download] Downloading video #1 of 10
[youtube] Setting language
[youtube] m34r0BLy5YU: Downloading webpage
[youtube] m34r0BLy5YU: Downloading video info webpage
[youtube] m34r0BLy5YU: Extracting video information
ERROR: unable to download video data: HTTP Error 410: Gone
[download] Downloading video #2 of 10
[youtube] V0mRSz6hXAA: Downloading webpage
[youtube] V0mRSz6hXAA: Downloading video info webpage
[youtube] V0mRSz6hXAA: Extracting video information
[info] Maximum number of downloaded files reached.
--max-download limit reached, aborting.

**Comment by arrabal** [comment] 2015-12-17 17:48
I can confirm this is happening. For instance, if I try to download formats until I find a video smaller than 50Mb, I will use -f X,Y,Z,... --max-filesize 50MB --max-dowloads 1 
If X is not downloaded because it is >50MB, it ends with:
[info] Maximum number of downloaded files reached.
--max-download limit reached, aborting.

**Comment by dstftw** [comment] 2017-05-08 17:54
Duplicate of #1686.

**Closed by dstftw** 2017-05-08 17:54 UTC
Labels: request
