### ISSUE TITLE
No longer working with Dailymotion

### ISSUE THREAD

**Issue by metalx1000** [rg3/youtube-dl#10904] opened 2016-10-12 00:31 UTC
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.dailymotion.com/video/x41larr']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.07
[debug] Python version 2.7.12+ - Linux-4.7.0-1-amd64-x86_64-with-debian-stretch-sid
[debug] exe versions: ffmpeg 3.1.3-2, ffprobe 3.1.3-2, rtmpdump 2.4
[debug] Proxy map: {}
[dailymotion] x41larr: Downloading webpage
[dailymotion] x41larr: Downloading embed page
ERROR: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 356, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/dailymotion.py", line 237, in _real_extract
    'video info', flags=re.MULTILINE),
  File "./youtube-dl/youtube_dl/extractor/common.py", line 659, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### Description of your *issue*, suggested solution and other information
Dailymotion must have changed something on their site.  Youtube-dl was working a few days ago and today it does not, even with videos links I've downloaded a few days ago.  I made sure my Youtube-dl was up to date:
./youtube-dl --version                                                                                                 :(
2016.10.07

**Comment by thorsummoner** [comment] 2016-10-12 01:39
I have this issue too, same version. I suspect it might have to do with daily motion's advertisement injection.

**Comment by dstftw** [comment] 2016-10-12 02:28
Duplicate of #10901.

**Closed by dstftw** 2016-10-12 02:28 UTC
