### ISSUE TITLE
vh1 No Longer Supported?

### ISSUE THREAD

**Issue by joetex72** [rg3/youtube-dl#11662] opened 2017-01-10 11:26 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.08*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.08**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Full episodes:
```
C:\>youtube-dl --update
youtube-dl is up-to-date (2017.01.08)

C:\>youtube-dl http://www.vh1.com/full-episodes/mxl6hg/kmichelle-my-life-between-a-tour-and-a-hard-place-season-3-ep-301 --verbose
[debug] System config: []
[debug] User config: ['-o', 'G:\\Video\\Audials Imported Movies\\%(upload_date)s %(title)s %(timestamp)s.%(ext)s', '--add-metadata', '--write-sub']
[debug] Custom config: []
[debug] Command-line args: ['http://www.vh1.com/full-episodes/mxl6hg/kmichelle-my-life-between-a-tour-and-a-hard-place-season-3-ep-301', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.01.08
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: avconv v12_dev0-3162-gf01f7a7, avprobe v12_dev0-3162-gf01f7a7, ffmpeg N-82995-g4221c68, ffprobe N-82995-g4221c68, rtmpdump 2.4-20151223-gfa8646d-LibreSSL_2.5.0-x86_64-static
[debug] Proxy map: {}
[generic] kmichelle-my-life-between-a-tour-and-a-hard-place-season-3-ep-301: Requesting header
WARNING: Falling back on generic information extractor.
[generic] kmichelle-my-life-between-a-tour-and-a-hard-place-season-3-ep-301: Downloading webpage
[generic] kmichelle-my-life-between-a-tour-and-a-hard-place-season-3-ep-301: Extracting information
ERROR: Unsupported URL: http://www.vh1.com/full-episodes/mxl6hg/kmichelle-my-life-between-a-tour-and-a-hard-place-season-3-ep-301
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9qq9vblw\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9qq9vblw\build\youtube_dl\extractor\common.py", line 359, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9qq9vblw\build\youtube_dl\extractor\generic.py", line 2507, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.vh1.com/full-episodes/mxl6hg/kmichelle-my-life-between-a-tour-and-a-hard-place-season-3-ep-301

C:\>youtube-dl http://www.vh1.com/full-episodes/ogfp18/leave-it-to-stevie-stevie-is-back-season-1-ep-101 --verbose
[debug] System config: []
[debug] User config: ['-o', 'G:\\Video\\Audials Imported Movies\\%(upload_date)s %(title)s %(timestamp)s.%(ext)s', '--add-metadata', '--write-sub']
[debug] Custom config: []
[debug] Command-line args: ['http://www.vh1.com/full-episodes/ogfp18/leave-it-to-stevie-stevie-is-back-season-1-ep-101', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.01.08
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: avconv v12_dev0-3162-gf01f7a7, avprobe v12_dev0-3162-gf01f7a7, ffmpeg N-82995-g4221c68, ffprobe N-82995-g4221c68, rtmpdump 2.4-20151223-gfa8646d-LibreSSL_2.5.0-x86_64-static
[debug] Proxy map: {}
[generic] leave-it-to-stevie-stevie-is-back-season-1-ep-101: Requesting header
WARNING: Falling back on generic information extractor.
[generic] leave-it-to-stevie-stevie-is-back-season-1-ep-101: Downloading webpage
[generic] leave-it-to-stevie-stevie-is-back-season-1-ep-101: Extracting information
ERROR: Unsupported URL: http://www.vh1.com/full-episodes/ogfp18/leave-it-to-stevie-stevie-is-back-season-1-ep-101
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9qq9vblw\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9qq9vblw\build\youtube_dl\extractor\common.py", line 359, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9qq9vblw\build\youtube_dl\extractor\generic.py", line 2507, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.vh1.com/full-episodes/ogfp18/leave-it-to-stevie-stevie-is-back-season-1-ep-101

C:\>youtube-dl http://www.vh1.com/full-episodes/24huqc/americas-next-top-model-lights-camera-catwalk-season-23-ep-2302
[generic] americas-next-top-model-lights-camera-catwalk-season-23-ep-2302: Requesting header
WARNING: Falling back on generic information extractor.
[generic] americas-next-top-model-lights-camera-catwalk-season-23-ep-2302: Downloading webpage
[generic] americas-next-top-model-lights-camera-catwalk-season-23-ep-2302: Extracting information
ERROR: Unsupported URL: http://www.vh1.com/full-episodes/24huqc/americas-next-top-model-lights-camera-catwalk-season-23-ep-2302

C:\>youtube-dl http://www.vh1.com/full-episodes/u1xjnn/love-and-hip-hop-all-the-way-up-season-7-ep-701
[generic] love-and-hip-hop-all-the-way-up-season-7-ep-701: Requesting header
WARNING: Falling back on generic information extractor.
[generic] love-and-hip-hop-all-the-way-up-season-7-ep-701: Downloading webpage
[generic] love-and-hip-hop-all-the-way-up-season-7-ep-701: Extracting information
ERROR: Unsupported URL: http://www.vh1.com/full-episodes/u1xjnn/love-and-hip-hop-all-the-way-up-season-7-ep-701

C:\>youtube-dl http://www.vh1.com/full-episodes/3tqzwf/martha-snoops-potluck-dinner-party-keep-your-claws-off-me-season-1-ep-102
[generic] martha-snoops-potluck-dinner-party-keep-your-claws-off-me-season-1-ep-102: Requesting header
WARNING: Falling back on generic information extractor.
[generic] martha-snoops-potluck-dinner-party-keep-your-claws-off-me-season-1-ep-102: Downloading webpage
[generic] martha-snoops-potluck-dinner-party-keep-your-claws-off-me-season-1-ep-102: Extracting information
ERROR: Unsupported URL: http://www.vh1.com/full-episodes/3tqzwf/martha-snoops-potluck-dinner-party-keep-your-claws-off-me-season-1-ep-102

C:\>youtube-dl http://www.vh1.com/full-episodes/4y3z40/martha-snoops-potluck-dinner-party-putting-the-pot-in-potluck-season-1-ep-101
[generic] martha-snoops-potluck-dinner-party-putting-the-pot-in-potluck-season-1-ep-101: Requesting header
WARNING: Falling back on generic information extractor.
[generic] martha-snoops-potluck-dinner-party-putting-the-pot-in-potluck-season-1-ep-101: Downloading webpage
[generic] martha-snoops-potluck-dinner-party-putting-the-pot-in-potluck-season-1-ep-101: Extracting information
ERROR: Unsupported URL: http://www.vh1.com/full-episodes/4y3z40/martha-snoops-potluck-dinner-party-putting-the-pot-in-potluck-season-1-ep-101

C:\>youtube-dl http://www.vh1.com/full-episodes/3mvd1t/basketball-wives-la-episode-1-season-5-ep-501
[generic] basketball-wives-la-episode-1-season-5-ep-501: Requesting header
WARNING: Falling back on generic information extractor.
[generic] basketball-wives-la-episode-1-season-5-ep-501: Downloading webpage
[generic] basketball-wives-la-episode-1-season-5-ep-501: Extracting information
ERROR: Unsupported URL: http://www.vh1.com/full-episodes/3mvd1t/basketball-wives-la-episode-1-season-5-ep-501

C:\>youtube-dl http://www.vh1.com/full-episodes/zvdjt8/black-ink-crew-chicago-the-nicki-minaj-of-9mag-season-2-ep-201
[generic] black-ink-crew-chicago-the-nicki-minaj-of-9mag-season-2-ep-201: Requesting header
WARNING: Falling back on generic information extractor.
[generic] black-ink-crew-chicago-the-nicki-minaj-of-9mag-season-2-ep-201: Downloading webpage
[generic] black-ink-crew-chicago-the-nicki-minaj-of-9mag-season-2-ep-201: Extracting information
ERROR: Unsupported URL: http://www.vh1.com/full-episodes/zvdjt8/black-ink-crew-chicago-the-nicki-minaj-of-9mag-season-2-ep-201

C:\>youtube-dl http://www.vh1.com/full-episodes/cqxu0a/americas-next-top-model-business-brand-boss-season-23-ep-2301
[generic] americas-next-top-model-business-brand-boss-season-23-ep-2301: Requesting header
WARNING: Falling back on generic information extractor.
[generic] americas-next-top-model-business-brand-boss-season-23-ep-2301: Downloading webpage
[generic] americas-next-top-model-business-brand-boss-season-23-ep-2301: Extracting information
ERROR: Unsupported URL: http://www.vh1.com/full-episodes/cqxu0a/americas-next-top-model-business-brand-boss-season-23-ep-2301

C:\>youtube-dl http://www.vh1.com/full-episodes/ns2gw0/love-and-hip-hop-hollywood-california-dreaming-season-3-ep-301
[generic] love-and-hip-hop-hollywood-california-dreaming-season-3-ep-301: Requesting header
WARNING: Falling back on generic information extractor.
[generic] love-and-hip-hop-hollywood-california-dreaming-season-3-ep-301: Downloading webpage
[generic] love-and-hip-hop-hollywood-california-dreaming-season-3-ep-301: Extracting information
ERROR: Unsupported URL: http://www.vh1.com/full-episodes/ns2gw0/love-and-hip-hop-hollywood-california-dreaming-season-3-ep-301
```
Video clips:
```
C:\>youtube-dl --update
youtube-dl is up-to-date (2017.01.08)

C:\>youtube-dl http://www.vh1.com/video-clips/7krgcd/leave-it-to-stevie-stevie-j-and-sade-go-shopping --verbose
[debug] System config: []
[debug] User config: ['-o', 'G:\\Video\\Audials Imported Movies\\%(upload_date)s %(title)s %(timestamp)s.%(ext)s', '--add-metadata', '--write-sub']
[debug] Custom config: []
[debug] Command-line args: ['http://www.vh1.com/video-clips/7krgcd/leave-it-to-stevie-stevie-j-and-sade-go-shopping', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.01.08
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: avconv v12_dev0-3162-gf01f7a7, avprobe v12_dev0-3162-gf01f7a7, ffmpeg N-82995-g4221c68, ffprobe N-82995-g4221c68, rtmpdump 2.4-20151223-gfa8646d-LibreSSL_2.5.0-x86_64-static
[debug] Proxy map: {}
[generic] leave-it-to-stevie-stevie-j-and-sade-go-shopping: Requesting header
WARNING: Falling back on generic information extractor.
[generic] leave-it-to-stevie-stevie-j-and-sade-go-shopping: Downloading webpage
[generic] leave-it-to-stevie-stevie-j-and-sade-go-shopping: Extracting information
WARNING: [generic] leave-it-to-stevie-stevie-j-and-sade-go-shopping: Failed to parse JSON Invalid control character at: line 9 column 27 (char 461)
ERROR: Unsupported URL: http://www.vh1.com/video-clips/7krgcd/leave-it-to-stevie-stevie-j-and-sade-go-shopping
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9qq9vblw\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9qq9vblw\build\youtube_dl\extractor\common.py", line 359, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9qq9vblw\build\youtube_dl\extractor\generic.py", line 2507, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.vh1.com/video-clips/7krgcd/leave-it-to-stevie-stevie-j-and-sade-go-shopping

C:\>youtube-dl http://www.vh1.com/video-clips/0ohb4t/the-breaks-the-cast-of-the-breaks-reveal-their-favorite-music-of-2016 --verbose
[debug] System config: []
[debug] User config: ['-o', 'G:\\Video\\Audials Imported Movies\\%(upload_date)s %(title)s %(timestamp)s.%(ext)s', '--add-metadata', '--write-sub']
[debug] Custom config: []
[debug] Command-line args: ['http://www.vh1.com/video-clips/0ohb4t/the-breaks-the-cast-of-the-breaks-reveal-their-favorite-music-of-2016', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.01.08
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: avconv v12_dev0-3162-gf01f7a7, avprobe v12_dev0-3162-gf01f7a7, ffmpeg N-82995-g4221c68, ffprobe N-82995-g4221c68, rtmpdump 2.4-20151223-gfa8646d-LibreSSL_2.5.0-x86_64-static
[debug] Proxy map: {}
[generic] the-breaks-the-cast-of-the-breaks-reveal-their-favorite-music-of-2016: Requesting header
WARNING: Falling back on generic information extractor.
[generic] the-breaks-the-cast-of-the-breaks-reveal-their-favorite-music-of-2016: Downloading webpage
[generic] the-breaks-the-cast-of-the-breaks-reveal-their-favorite-music-of-2016: Extracting information
ERROR: Unsupported URL: http://www.vh1.com/video-clips/0ohb4t/the-breaks-the-cast-of-the-breaks-reveal-their-favorite-music-of-2016
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9qq9vblw\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9qq9vblw\build\youtube_dl\extractor\common.py", line 359, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9qq9vblw\build\youtube_dl\extractor\generic.py", line 2507, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.vh1.com/video-clips/0ohb4t/the-breaks-the-cast-of-the-breaks-reveal-their-favorite-music-of-2016

C:\>youtube-dl http://www.vh1.com/video-clips/zmzqc9/barely-famous-erin-s-boring-stories
[generic] barely-famous-erin-s-boring-stories: Requesting header
WARNING: Falling back on generic information extractor.
[generic] barely-famous-erin-s-boring-stories: Downloading webpage
[generic] barely-famous-erin-s-boring-stories: Extracting information
WARNING: [generic] barely-famous-erin-s-boring-stories: Failed to parse JSON Invalid control character at: line 9 column 27 (char 452)
ERROR: Unsupported URL: http://www.vh1.com/video-clips/zmzqc9/barely-famous-erin-s-boring-stories

C:\>youtube-dl http://www.vh1.com/video-clips/rnyx8p/americas-next-top-model-zendaya-helps-out-at-the-first-runway-event
[generic] americas-next-top-model-zendaya-helps-out-at-the-first-runway-event: Requesting header
WARNING: Falling back on generic information extractor.
[generic] americas-next-top-model-zendaya-helps-out-at-the-first-runway-event: Downloading webpage
[generic] americas-next-top-model-zendaya-helps-out-at-the-first-runway-event: Extracting information
WARNING: [generic] americas-next-top-model-zendaya-helps-out-at-the-first-runway-event: Failed to parse JSON Invalid control character at: line 9 column 51 (char 618)
ERROR: Unsupported URL: http://www.vh1.com/video-clips/rnyx8p/americas-next-top-model-zendaya-helps-out-at-the-first-runway-event

C:\>youtube-dl http://www.vh1.com/video-clips/i2hley/dating-naked-vanessa-and-natalie-become-wisconsin-bffs
[generic] dating-naked-vanessa-and-natalie-become-wisconsin-bffs: Requesting header
WARNING: Falling back on generic information extractor.
[generic] dating-naked-vanessa-and-natalie-become-wisconsin-bffs: Downloading webpage
[generic] dating-naked-vanessa-and-natalie-become-wisconsin-bffs: Extracting information
WARNING: [generic] dating-naked-vanessa-and-natalie-become-wisconsin-bffs: Failed to parse JSON Invalid control character at: line 9 column 43 (char 515)
ERROR: Unsupported URL: http://www.vh1.com/video-clips/i2hley/dating-naked-vanessa-and-natalie-become-wisconsin-bffs

C:\>youtube-dl http://www.vh1.com/video-clips/jilm3a/love-and-hip-hop-yandy-gets-the-inside-scoop
[generic] love-and-hip-hop-yandy-gets-the-inside-scoop: Requesting header
WARNING: Falling back on generic information extractor.
[generic] love-and-hip-hop-yandy-gets-the-inside-scoop: Downloading webpage
[generic] love-and-hip-hop-yandy-gets-the-inside-scoop: Extracting information
WARNING: [generic] love-and-hip-hop-yandy-gets-the-inside-scoop: Failed to parse JSON Invalid control character at: line 9 column 61 (char 554)
ERROR: Unsupported URL: http://www.vh1.com/video-clips/jilm3a/love-and-hip-hop-yandy-gets-the-inside-scoop

C:\>youtube-dl http://www.vh1.com/video-clips/zeuhs7/basketball-wives-la-jackie-doug-have-the-key
[generic] basketball-wives-la-jackie-doug-have-the-key: Requesting header
WARNING: Falling back on generic information extractor.
[generic] basketball-wives-la-jackie-doug-have-the-key: Downloading webpage
[generic] basketball-wives-la-jackie-doug-have-the-key: Extracting information
WARNING: [generic] basketball-wives-la-jackie-doug-have-the-key: Failed to parse JSON Invalid control character at: line 9 column 40 (char 572)
ERROR: Unsupported URL: http://www.vh1.com/video-clips/zeuhs7/basketball-wives-la-jackie-doug-have-the-key

C:\>youtube-dl http://www.vh1.com/video-clips/9bf3qw/kmichelle-my-life-k-has-a-message-for-kids-in-school
[generic] kmichelle-my-life-k-has-a-message-for-kids-in-school: Requesting header
WARNING: Falling back on generic information extractor.
[generic] kmichelle-my-life-k-has-a-message-for-kids-in-school: Downloading webpage
[generic] kmichelle-my-life-k-has-a-message-for-kids-in-school: Extracting information
WARNING: [generic] kmichelle-my-life-k-has-a-message-for-kids-in-school: Failed to parse JSON Invalid control character at: line 9 column 27 (char 483)
ERROR: Unsupported URL: http://www.vh1.com/video-clips/9bf3qw/kmichelle-my-life-k-has-a-message-for-kids-in-school

C:\>youtube-dl http://www.vh1.com/video-clips/v72itv/black-ink-crew-chicago-ryan-loses-his-luggage
[generic] black-ink-crew-chicago-ryan-loses-his-luggage: Requesting header
WARNING: Falling back on generic information extractor.
[generic] black-ink-crew-chicago-ryan-loses-his-luggage: Downloading webpage
[generic] black-ink-crew-chicago-ryan-loses-his-luggage: Extracting information
WARNING: [generic] black-ink-crew-chicago-ryan-loses-his-luggage: Failed to parse JSON Invalid control character at: line 9 column 43 (char 518)
ERROR: Unsupported URL: http://www.vh1.com/video-clips/v72itv/black-ink-crew-chicago-ryan-loses-his-luggage

C:\>youtube-dl http://www.vh1.com/video-clips/oqre7e/americas-next-top-model-india-is-nervous-about-the-first-nude-photoshoot
[generic] americas-next-top-model-india-is-nervous-about-the-first-nude-photoshoot: Requesting header
WARNING: Falling back on generic information extractor.
[generic] americas-next-top-model-india-is-nervous-about-the-first-nude-photoshoot: Downloading webpage
[generic] americas-next-top-model-india-is-nervous-about-the-first-nude-photoshoot: Extracting information
WARNING: [generic] americas-next-top-model-india-is-nervous-about-the-first-nude-photoshoot: Failed to parse JSON Invalid control character at: line 9 column 35 (char 561)
ERROR: Unsupported URL: http://www.vh1.com/video-clips/oqre7e/americas-next-top-model-india-is-nervous-about-the-first-nude-photoshoot
```
Full episode links:
http://www.vh1.com/full-episodes/mxl6hg/kmichelle-my-life-between-a-tour-and-a-hard-place-season-3-ep-301
http://www.vh1.com/full-episodes/ogfp18/leave-it-to-stevie-stevie-is-back-season-1-ep-101
http://www.vh1.com/full-episodes/24huqc/americas-next-top-model-lights-camera-catwalk-season-23-ep-2302
http://www.vh1.com/full-episodes/u1xjnn/love-and-hip-hop-all-the-way-up-season-7-ep-701
http://www.vh1.com/full-episodes/3tqzwf/martha-snoops-potluck-dinner-party-keep-your-claws-off-me-season-1-ep-102
http://www.vh1.com/full-episodes/4y3z40/martha-snoops-potluck-dinner-party-putting-the-pot-in-potluck-season-1-ep-101
http://www.vh1.com/full-episodes/3mvd1t/basketball-wives-la-episode-1-season-5-ep-501
http://www.vh1.com/full-episodes/zvdjt8/black-ink-crew-chicago-the-nicki-minaj-of-9mag-season-2-ep-201
http://www.vh1.com/full-episodes/cqxu0a/americas-next-top-model-business-brand-boss-season-23-ep-2301
http://www.vh1.com/full-episodes/ns2gw0/love-and-hip-hop-hollywood-california-dreaming-season-3-ep-301

Video clips links:
http://www.vh1.com/video-clips/7krgcd/leave-it-to-stevie-stevie-j-and-sade-go-shopping
http://www.vh1.com/video-clips/0ohb4t/the-breaks-the-cast-of-the-breaks-reveal-their-favorite-music-of-2016
http://www.vh1.com/video-clips/zmzqc9/barely-famous-erin-s-boring-stories
http://www.vh1.com/video-clips/rnyx8p/americas-next-top-model-zendaya-helps-out-at-the-first-runway-event
http://www.vh1.com/video-clips/i2hley/dating-naked-vanessa-and-natalie-become-wisconsin-bffs
http://www.vh1.com/video-clips/jilm3a/love-and-hip-hop-yandy-gets-the-inside-scoop
http://www.vh1.com/video-clips/zeuhs7/basketball-wives-la-jackie-doug-have-the-key
http://www.vh1.com/video-clips/9bf3qw/kmichelle-my-life-k-has-a-message-for-kids-in-school
http://www.vh1.com/video-clips/v72itv/black-ink-crew-chicago-ryan-loses-his-luggage
http://www.vh1.com/video-clips/oqre7e/americas-next-top-model-india-is-nervous-about-the-first-nude-photoshoot

I tried the 10 FREE full episode links first, then I tried the 10 FREE short clips. They all say "Unsupported URL". I see that a similar issue has been posted but that topic has the account-needed label and has been ignored. The 20 links I provided are 100% completely FREE and played without errors in Chrome, Firefox and IE five minutes ago, and require no account.

Will vh1 be supported at some point in the future? I suppose if the problem with one of these free links can be fixed, then the other issue that was posted months ago will be resolved.

**Comment by dstftw** [comment] 2017-01-10 14:55
Duplicate of #9613.

**Closed by dstftw** 2017-01-10 14:55 UTC
