### ISSUE TITLE
Download part of the youtube video 

### ISSUE THREAD

**Issue by mannemvamsi** [rg3/youtube-dl#4904] opened 2015-02-08 17:51 UTC
Hi, Is it possible to download part of the youtube video. 

For example: Video length is 60 min. I want to download only(5 min file) i.e:  30th min - 35min.

**Comment by robin007bond** [comment] 2015-02-08 17:58
I don't think so. 

But you can crop the downloaded video afterwards with ffmpeg.

**Comment by dstftw** [comment] 2015-02-08 18:01
Duplicate of #4821.
This is not possible at the moment, consider [this comment](https://github.com/rg3/youtube-dl/issues/4821#issuecomment-72213508) for info.

**Closed by dstftw** 2015-02-08 18:01 UTC
