### ISSUE TITLE
why not using python builtin html unescape

### ISSUE THREAD

**Issue by remitamine** [rg3/youtube-dl#9270] opened 2016-04-21 16:11 UTC
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.19**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar - [ ] Bug report (encountered problems with youtube-dl)
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---
moved from https://github.com/rg3/youtube-dl/commit/9e6dd238761e6628d7bd0b6bdb7a997604de3757#commitcomment-17012611.
why the html unescape that came with python http://stackoverflow.com/a/2360639 is not used it can handle two cases that the unescapeHTML can't(`&apos;` and the ones that start with `&#X`) and it was improved in the last version(handle HTML5 named character references).

**Comment by yan12125** [comment] 2016-04-21 16:21
I guess a reason is mentioned in #329:

>  _unescapeHTML did the same thing as htmlentity_transform but using the undocumented HTMLParser.unescape

**Comment by remitamine** [comment] 2016-04-21 16:35
> it can handle two cases that the unescapeHTML can't(&apos; and the ones that start with &#X)

if the code is the same thing. it whould give the same result.

**Comment by yan12125** [comment] 2016-04-21 16:41
The problem is **undocumented**. I guess it's OK as CPython is the _de facto_ standard. Other Python implementations, such as PyPy and Jython, are moving towards using the same set of standard libraries. Ideas from other developers needed, though.

**Comment by phihag** [comment] 2016-04-21 21:05
This function is really old. As long as the tests pass (we may need to add some to cover calling it with `None` and `b'123'`), feel free to replace its implementation. Note as @yan12125 , we should only use public python interfaces.

**Comment by yan12125** [comment] 2016-05-19 04:04
If one day youtube-dl supports Python 3.4+ only, we can use it: https://docs.python.org/3/library/html.html#html.unescape. Closing now.

Something not directly related to this topic but also interesting: http://bugs.python.org/issue27032

**Closed by yan12125** 2016-05-19 04:04 UTC

**Comment by yan12125** [comment] 2016-06-10 07:18
Since 55b2f099c0c820d6c4b46609b175a44a6d7f97bf and 9631a94fb5e5ee9b92135f938df00866535fc6c6 HTML5 entities are recognized. It works fine for Vporn. Are there other websites using HTML5 entites?
