### ISSUE TITLE
RegexNotFoundError: Unable to extract title

### ISSUE THREAD

**Issue by Wastrel** [rg3/youtube-dl#7548] opened 2015-11-18 18:02 UTC
I looked for workarounds and it seems this is an old issue, solved in 2014. I'm getting it with the latest version: 2015.11.15.

youtube-dl -wti --flat-playlist--verbose https://www.youtube.com/playlist?list=PLmN6dKnsGvNywL-1TV3hqLTW_YFgWlUjL > error
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-wti', u'--flat-playlist', u'--verbose', u'https://www.youtube.com/playlist?list=PLmN6dKnsGvNywL-1TV3hqLTW_YFgWlUjL']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2015.11.15
[debug] Python version 2.7.3 - Linux-3.5.0-54-generic-i686-athlon-with-Ubuntu-12.04-precise
[debug] exe versions: avconv 0.8.17-4, avprobe 0.8.17-4, ffmpeg 0.8.17-4, ffprobe 0.8.17-4, rtmpdump 2.4
[debug] Proxy map: {'http': 'http://10.10.10.1:3128/', 'https': 'https://10.10.10.1:3128/', 'no': 'localhost,127.0.0.0/8'}
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1644, in _real_extract
    return self._extract_playlist(playlist_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1619, in _extract_playlist
    page, 'title')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 593, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by jaimeMF** [comment] 2015-11-18 18:21
Duplicate of #7544.

**Closed by jaimeMF** 2015-11-18 18:21 UTC

**Comment by phihag** [comment] 2015-11-18 18:24
Thank you for the report. I believe this issue to be fixed in youtube-dl version 2015.11.18. See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by Wastrel** [comment] 2015-11-18 18:36
Thanks. I searched for other open issues with "title" but I didn't find anything. Please do what you need to do.


Eric


________________________________

**Comment by Wastrel** [comment] 2015-11-18 18:39
Thanks! Sometime since the time I had the problem an hour and a half ago, 2015.11.18 was available.


Eric

________________________________

**Comment by Wastrel** [comment] 2015-11-18 22:58
I'd like to mention that the message


"WARNING: Your copy of avconv is outdated and unable to properly mux separate video and audio files, youtube-dl will download single file media. Update avconv to version 10-0 or newer to fix this."


that I get every time I run youtube-dl is simply a waste of terminal space. There is no avconv 10-0 or 10.0 or anything like it for linux. I am somewhat aware of the developer war between ffmpeg and avconv but I see no reason for youtube-dl to be involved.


Eric


________________________________

**Comment by jaimeMF** [comment] 2015-11-18 23:04
Open a new issue. Keep in mind that it's reported because you have installed an old version of avconv (see the `[debug] exe versions` line).

**Comment by Wastrel** [comment] 2015-11-18 23:10
I have the latest version of avconv for my OS. What does this "exe" mean....


I'm not opening an issue. It's just an annoyance. Not a bug.


Eric


________________________________
