### ISSUE TITLE
Support for yle.fi

### ISSUE THREAD

**Issue by buchno** [rg3/youtube-dl#8896] opened 2016-03-19 04:43 UTC
Support request for yle.fi
Example video: http://arenan.yle.fi/1-3094091

They use [Adobe HTTP Dynamic Streaming](https://github.com/rg3/youtube-dl/issues/1393).

**Comment by yan12125** [comment] 2016-03-19 05:24
Duplicate of #1574.

**Closed by yan12125** 2016-03-19 05:24 UTC
