### ISSUE TITLE
[myvideo] ERROR: Unsupported URL

### ISSUE THREAD

**Issue by Hrxn** [rg3/youtube-dl#8556] opened 2016-02-14 04:39 UTC
Site: Myvideo.de
URL: http://www.myvideo.de/serien/in-the-box/staffel-1/folge-1-smudo-box-m-12153161

```
D:\>youtube-dl.exe --ignore-config -v "http://www.myvideo.de/serien/in-the-box/staffel-1/folge-1-smudo-box-m-12153161"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--ignore-config', u'-v', u'http://www.myvideo.de/serien/in-the-box/staffel-1/folge-1-smudo-box-m-12153161']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.02.10
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-77953-gcc83177
[debug] Proxy map: {}
[generic] folge-1-smudo-box-m-12153161: Requesting header
WARNING: Falling back on generic information extractor.
[generic] folge-1-smudo-box-m-12153161: Downloading webpage
[generic] folge-1-smudo-box-m-12153161: Extracting information
ERROR: Unsupported URL: http://www.myvideo.de/serien/in-the-box/staffel-1/folge-1-smudo-box-m-12153161
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1294, in _real_extract
  File "youtube_dl\compat.pyo", line 248, in compat_etree_fromstring
  File "youtube_dl\compat.pyo", line 237, in _XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: not well-formed (invalid token): line 38, column 448
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 666, in extract_info
  File "youtube_dl\extractor\common.pyo", line 315, in extract
  File "youtube_dl\extractor\generic.pyo", line 1930, in _real_extract
UnsupportedError: Unsupported URL: http://www.myvideo.de/serien/in-the-box/staffel-1/folge-1-smudo-box-m-12153161


D:\>
```

myvideo is still listed as [supported](https://github.com/rg3/youtube-dl/blob/master/docs/supportedsites.md)

**Comment by dstftw** [comment] 2016-02-14 04:43
Duplicate of #4145.

**Closed by dstftw** 2016-02-14 04:43 UTC

**Comment by Hrxn** [comment] 2016-02-14 08:26
I did search for 'myvideo' in issues, that one is about "Serien" (Series) on myvideo.de, so I assumed it would be different.

But the URL schema is the same, true.

That being said, I tried other videos on myvideo.de, and *none* of them worked. Always the same error, as mentioned earlier.


Maybe the `supportedsites.md` needs a little clean-up..

**Comment by Hrxn** [comment] 2016-02-14 08:29
Okay, just saw #8557

Done here.
