### ISSUE TITLE
Support for Mitele.es

### ISSUE THREAD

**Issue by edumj** [rg3/youtube-dl#6821] opened 2015-09-10 15:08 UTC
Hi,

I think Mitele.es has stop working. When I try to download some videos like this:

http://www.mitele.es/series-online/la-que-se-avecina/temporada-8/capitulo-109/

Throws this error:

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.mitele.es/series-online/la-que-se-avecina/temporada-8/capitulo-109/', u'--verbose', u'-f', u'best', u'-o', u'T:\\DESCAR~1\\SABERY~1\\9-9-15~1\\\\Avecina.mp4']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.09.09
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: Unable to extract embed data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 660, in extract_info
  File "youtube_dl\extractor\common.pyo", line 287, in extract
  File "youtube_dl\extractor\mitele.pyo", line 42, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 575, in _search_regex
RegexNotFoundError: Unable to extract embed data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment] 2015-09-10 15:09
Duplicate of #6414.

**Closed by dstftw** 2015-09-10 15:09 UTC
