### ISSUE TITLE
Request QQ Music  support

### ISSUE THREAD

**Issue by gam2046** [rg3/youtube-dl#13800] opened 2017-08-01 12:41 UTC
```
# youtube-dl -v https://y.qq.com/n/yqq/album/002KOCYh0x26Ae.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://y.qq.com/n/yqq/album/002KOCYh0x26Ae.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.30.1
[debug] Python version 3.6.2 - Linux-4.9.36-moby-x86_64-with
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 002KOCYh0x26Ae: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 002KOCYh0x26Ae: Downloading webpage
[generic] 002KOCYh0x26Ae: Extracting information
ERROR: Unsupported URL: https://y.qq.com/n/yqq/album/002KOCYh0x26Ae.html
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/generic.py", line 2944, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://y.qq.com/n/yqq/album/002KOCYh0x26Ae.html
```
The url of `QQ Music` has been changed.

https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/qqmusic.py

Line 21, 175, 220, 263, 317 should be update.

**Comment by yan12125** [comment] 2017-08-01 13:07
Duplicate of #13363. That's a working yet incomplete fix. You may want to take over it.

**Closed by yan12125** 2017-08-01 13:07 UTC

**Comment by gam2046** [comment] 2017-08-03 07:13
it works now maybe.  #13805
