### ISSUE TITLE
Facebook Live Video Download not possible

### ISSUE THREAD

**Issue by felixdreinulldrei** [rg3/youtube-dl#11387] opened 2016-12-07 21:35 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl   -v "https://www.facebook.com/NBCNews/videos/1603390213014336/"  
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.facebook.com/NBCNews/videos/1603390213014336/', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.01
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.0-tessus, ffprobe 3.0-tessus, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] 1603390213014336: Downloading webpage
[facebook] 1603390213014336: Downloading webpage
[debug] Invoking downloader on u'https://video-fra3-1.xx.fbcdn.net/hvideo-prn1/v/dash-md/1603390216347669.mpd?_nc_rl=AfC-JcMttEY5gCFO&oh=eb923e934df2ce88022a291c022b15e2&oe=5849FF3D'
[download] Destination: Joe Biden Honored on Senate Floor-1603390213014336.mpd
[download] 100% of 2.87KiB in 00:00
...
<end of log>
```

---

---

### Description of your *issue*, suggested solution and other information

It is not possible to download live videos. It just downloads the mpd file which is not working with ffmpeg or vlc. I also have tried it this way
$ youtube-dl -g "https://www.facebook.com/NBCNews/videos/1603390213014336/"  
I get the stream url "https://video-fra3-1.xx.fbcdn.net/hvideo-prn1/v/dash-abr/1603390216347669.mpd?_nc_rl=AfAC1NE-mOyaDki-&oh=48157680dc0dbb6e0a27c769788abd97&oe=584AFED9"
Which is still not playing with common players.
If I place this streamurl string into youtube-dl than I get this debug log:
---log begin---------------------------------------------------------------------
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://video-fra3-1.xx.fbcdn.net/hvideo-prn1/v/dash-abr/1603390216347669.mpd?_nc_rl=AfAC1NE-mOyaDki-&oh=48157680dc0dbb6e0a27c769788abd97&oe=584AFED9', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.01
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.0-tessus, ffprobe 3.0-tessus, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 1603390216347669: Requesting header
WARNING: Could not send HEAD request to https://video-fra3-1.xx.fbcdn.net/hvideo-prn1/v/dash-abr/1603390216347669.mpd?_nc_rl=AfAC1NE-mOyaDki-&oh=48157680dc0dbb6e0a27c769788abd97&oe=584AFED9: HTTP Error 502: Bad Gateway
[generic] 1603390216347669: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] 1603390216347669: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1644, in _real_extract
    self._sort_formats(info_dict['formats'])
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 924, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
---log-end----------------------------------------------------------------------------------------------------

Am I doing something wrong or is it just not supported?!
Meanwhile if you try this urls, maybe they are not active anymore because they were live.
Just try any live video from http://facebook.com/livemap

**Comment by dstftw** [comment] 2016-12-10 17:57
Works fine for me. Post the output of:
```youtube-dl -v --dump-pages https://www.facebook.com/NBCNews/videos/1603390213014336/```

**Comment by felixdreinulldrei** [comment] 2016-12-11 17:31
@dstftw  Your example is downloading a recorded video (vod) in mp4 format. This not a "Live Video".
My point was that it is not processing live videos on facebook.
Pick some Live Video i.e. from www.facebook.com/livemaps and try to download that video. Or try to play the downloaded mpd file with vlc or ffplay. Some weeks ago this was possible as facebook has delivered hls and rtmp videos. But since a while it is delivering live videos in mpeg dash format which somehow can not be handled with the latest youtube-dl versions?!

**Comment by dstftw** [comment] 2016-12-11 18:09
Duplicate of #10787.

**Closed by dstftw** 2016-12-11 18:09 UTC
Labels: cant-reproduce, clarification-needed

**Comment by orsonteodoro** [comment] 2016-12-24 20:36
youtube-dl does download the file with the MPEG DASH url but the script is not able to recognize it yet.  I have to manually extract it.  The mpd file is using relative urls and needs to be converted to absolute url which should be taken in consideration when playing them.  You can see them with --write-pages.

**Comment by orsonteodoro** [comment] 2016-12-24 20:46
orson@(none) ~/fbl $ youtube-dl -u "xxxx@xxx.xxx" -p "xxx" -v "https://www.facebook.com/cnn/videos/10155806047981509/"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-v', u'https://www.facebook.com/cnn/videos/10155806047981509/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.19-gentoo_no_offensive_sites
[debug] Python version 2.7.12 - Linux-4.4.26-gentoo-x86_64-AMD_Phenom-tm-_9850_Quad-Core_Processor-with-gentoo-2.3
[debug] exe versions: ffmpeg 2.8.6, ffprobe 2.8.6, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] Downloading login page
[facebook] Logging in
[facebook] 10155806047981509: Downloading webpage
[facebook] 10155806047981509: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/common.py", line 355, in extract
    return self._real_extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/facebook.py", line 352, in _real_extract
    video_id, fatal_if_no_video=True)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/facebook.py", line 276, in _extract_from_url
    raise ExtractorError('Cannot parse data')
ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by orsonteodoro** [comment] 2016-12-24 21:31
</MPD>orson@(none) ~/fbl $ youtube-dl -v -o - -u "xxxx@xxx.xxx" -p "xxxx" "https://www.facebook.com/cnn/videos/10155806047981509/"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-o', u'-', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://www.facebook.com/cnn/videos/10155806047981509/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.15-gentoo_no_offensive_sites
[debug] Python version 2.7.12 - Linux-4.4.26-gentoo-x86_64-AMD_Phenom-tm-_9850_Quad-Core_Processor-with-gentoo-2.3
[debug] exe versions: ffmpeg 2.8.6, ffprobe 2.8.6, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] Downloading login page
[facebook] Logging in
[facebook] 10155806047981509: Downloading webpage
[facebook] 10155806047981509: Downloading webpage
[debug] Invoking downloader on u'https://video.xx.fbcdn.net/hvideo-lla2/s3/v/dash-abr4/10155806047986509.mpd?_nc_rl=AfAz9UGEiWaXqqCZ&oh=951634ea097bd445039bd73508ec9665&oe=5861AE57'
[download] Destination: -
<?xml version="1.0"?>
<MPD
    type="dynamic"
    xmlns="urn:mpeg:dash:schema:mpd:2011"
    availabilityStartTime="2016-12-24T12:26:30-08:00"
    availabilityEndTime="2016-12-24T13:24:30-08:00"
    publishFrameTime="1"
    minimumUpdatePeriod="PT1S"
    minBufferTime="PT1S"
    timeShiftBufferDepth="P00Y00M00DT00H00M10.00S"
    suggestedPresentationDelay="PT2S"
    profiles="urn:hbbtv:dash:profile:isoff-live:2012,urn:mpeg:dash:profile:isoff-live:2011"
    xmlns:xsi="http://www.w3.org/2011/XMLSchema-instance"
    xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 DASH-MPD.xsd">
  <Period start="PT0S" id="dash">
    <AdaptationSet
        id="1"
        segmentAlignment="true">
      <Representation
          id="live-md_H264"
          mimeType="video/mp4"
          codecs="avc1.4d401e"
          width="640"
          height="360"
          FBQualityClass="sd"
          FBQualityLabel="360p"
          frameRate="30"
          sar="1:1"
          startWithSAP="1"
          bandwidth="500000">
[download]  17.0% of 5.89KiB at Unknown speed ETA Unknown ETAplate
            presentationTimeOffset="0"
            timescale="1000"
            media="../dash-md/10155806047986509-$Time$.m4v"
            initialization="../dash-md/10155806047986509-init.m4v">
          <SegmentTimeline>
             <S t="3468000" d="1000"/>
             <S t="3469000" d="1000"/>
             <S t="3470000" d="1000"/>
             <S t="3471000" d="1000"/>
             <S t="3472000" d="1000"/>
             <S t="3473000" d="1000"/>
             <S t="3474000" d="1000"/>
             <S t="3475000" d="1000"/>
             <S t="3476000" d="1000"/>
             <S t="3477000" d="1000"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
      <Representation
          id="live-ld_H264"
          mimeType="video/mp4"
          codecs="avc1.4d401e"
          width="426"
          height="240"
          FBQualityClass="sd"
          FBQualityLabel="240p"
          frameRate="30"
          sar="1:1"
          startWithSAP="1"
          bandwidth="250000">
        <SegmentTemplate
            presentationTimeOffset="0"
            timescale="1000"
            media="../dash-ld/10155806047986509-$Time$.m4v"
            initialization="../dash-ld/10155806047986509-init.m4v">
          <SegmentTimeline>
             <S t="3468000" d="1000"/>
             <S t="3469000" d="1000"/>
             <S t="3470000" d="1000"/>
             <S t="3471000" d="1000"/>
             <S t="3472000" d="1000"/>
             <S t="3473000" d="1000"/>
             <S t="3474000" d="1000"/>
             <S t="3475000" d="1000"/>
             <S t="3476000" d="1000"/>
             <S t="3477000" d="1000"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
      <Representation
          id="live-hd_H264"
          mimeType="video/mp4"
          codecs="avc1.4d401e"
          width="854"
          height="480"
          FBQualityClass="sd"
          FBQualityLabel="480p"
          frameRate="30"
          sar="1:1"
          startWithSAP="1"
[download]  50.9% of 5.89KiB at  1.29MiB/s ETA 00:00th="1000000">
        <SegmentTemplate
            presentationTimeOffset="0"
            timescale="1000"
            media="../dash-hd/10155806047986509-$Time$.m4v"
            initialization="../dash-hd/10155806047986509-init.m4v">
          <SegmentTimeline>
             <S t="3468000" d="1000"/>
             <S t="3469000" d="1000"/>
             <S t="3470000" d="1000"/>
             <S t="3471000" d="1000"/>
             <S t="3472000" d="1000"/>
             <S t="3473000" d="1000"/>
             <S t="3474000" d="1000"/>
             <S t="3475000" d="1000"/>
             <S t="3476000" d="1000"/>
             <S t="3477000" d="1000"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
      <Representation
          id="live-hd1_H264"
          mimeType="video/mp4"
          codecs="avc1.4d401e"
          width="1280"
          height="720"
          FBQualityClass="hd"
          FBQualityLabel="720p"
          frameRate="30"
          sar="1:1"
          startWithSAP="1"
          bandwidth="2000000">
        <SegmentTemplate
            presentationTimeOffset="0"
            timescale="1000"
            media="../dash-hd1/10155806047986509-$Time$.m4v"
            initialization="../dash-hd1/10155806047986509-init.m4v">
          <SegmentTimeline>
             <S t="3468000" d="1000"/>
             <S t="3469000" d="1000"/>
             <S t="3470000" d="1000"/>
             <S t="3471000" d="1000"/>
             <S t="3472000" d="1000"/>
             <S t="3473000" d="1000"/>
             <S t="3474000" d="1000"/>
             <S t="3475000" d="1000"/>
             <S t="3476000" d="1000"/>
             <S t="3477000" d="1000"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
    <AdaptationSet
        id="2"
        segmentAlignment="true">
      <AudioChannelConfiguration
          schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011"
          value="1"/>
      <Representation
          id="live-md_AAC"
          mimeType="audio/mp4"
          codecs="mp4a.40.2"
          audioSamplingRate="48000"
          startWithSAP="1"
          bandwidth="62000">
        <SegmentTemplate
            presentationTimeOffset="0"
            timescale="1000"
            media="../dash-md/10155806047986509-$Time$.m4a"
            initialization="../dash-md/10155806047986509-init.m4a">
          <SegmentTimeline>
             <S t="3468000" d="1000"/>
             <S t="3469000" d="1000"/>
             <S t="3470000" d="1000"/>
             <S t="3471000" d="1000"/>
             <S t="3472000" d="1000"/>
             <S t="3473000" d="1000"/>
             <S t="3474000" d="1000"/>
             <S t="3475000" d="1000"/>
             <S t="3476000" d="1000"/>
             <S t="3477000" d="1000"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
  </Period>
[download] 100% of 5.89KiB in 00:00
</MPD>orson@(none) ~/fbl $ 

The mpd file should be using absolute urls to feed to vlc.  vlc or mplayer doesn't know anything about the server or path if piped to it.  So it should look like:
cat t.mpd | sed -r -e "s|\.\./|https://video.xx.fbcdn.net/hvideo-lla2/s3/v/|g"
<?xml version="1.0"?>
<MPD
    type="dynamic"
    xmlns="urn:mpeg:dash:schema:mpd:2011"
    availabilityStartTime="2016-12-24T12:26:30-08:00"
    availabilityEndTime="2016-12-24T13:26:46-08:00"
    publishFrameTime="1"
    minimumUpdatePeriod="PT1S"
    minBufferTime="PT1S"
    timeShiftBufferDepth="P00Y00M00DT00H00M10.00S"
    suggestedPresentationDelay="PT2S"
    profiles="urn:hbbtv:dash:profile:isoff-live:2012,urn:mpeg:dash:profile:isoff-live:2011"
    xmlns:xsi="http://www.w3.org/2011/XMLSchema-instance"
    xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 DASH-MPD.xsd">
  <Period start="PT0S" id="dash">
    <AdaptationSet
        id="1"
        segmentAlignment="true">
      <Representation
          id="live-md_H264"
          mimeType="video/mp4"
          codecs="avc1.4d401e"
          width="640"
          height="360"
          FBQualityClass="sd"
          FBQualityLabel="360p"
          frameRate="30"
          sar="1:1"
          startWithSAP="1"
          bandwidth="500000">
        <SegmentTemplate
            presentationTimeOffset="0"
            timescale="1000"
            media="https://video.xx.fbcdn.net/hvideo-lla2/s3/v/dash-md/10155806047986509-$Time$.m4v"
            initialization="https://video.xx.fbcdn.net/hvideo-lla2/s3/v/dash-md/10155806047986509-init.m4v">
          <SegmentTimeline>
             <S t="3604000" d="1000"/>
             <S t="3605000" d="1000"/>
             <S t="3606000" d="1000"/>
             <S t="3607000" d="1000"/>
             <S t="3608000" d="1000"/>
             <S t="3609000" d="1000"/>
             <S t="3610000" d="1000"/>
             <S t="3611000" d="1000"/>
             <S t="3612000" d="1000"/>
             <S t="3613000" d="1000"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
      <Representation
          id="live-ld_H264"
          mimeType="video/mp4"
          codecs="avc1.4d401e"
          width="426"
          height="240"
          FBQualityClass="sd"
          FBQualityLabel="240p"
          frameRate="30"
          sar="1:1"
          startWithSAP="1"
          bandwidth="250000">
        <SegmentTemplate
            presentationTimeOffset="0"
            timescale="1000"
            media="https://video.xx.fbcdn.net/hvideo-lla2/s3/v/dash-ld/10155806047986509-$Time$.m4v"
            initialization="https://video.xx.fbcdn.net/hvideo-lla2/s3/v/dash-ld/10155806047986509-init.m4v">
          <SegmentTimeline>
             <S t="3604000" d="1000"/>
             <S t="3605000" d="1000"/>
             <S t="3606000" d="1000"/>
             <S t="3607000" d="1000"/>
             <S t="3608000" d="1000"/>
             <S t="3609000" d="1000"/>
             <S t="3610000" d="1000"/>
             <S t="3611000" d="1000"/>
             <S t="3612000" d="1000"/>
             <S t="3613000" d="1000"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
      <Representation
          id="live-hd_H264"
          mimeType="video/mp4"
          codecs="avc1.4d401e"
          width="854"
          height="480"
          FBQualityClass="sd"
          FBQualityLabel="480p"
          frameRate="30"
          sar="1:1"
          startWithSAP="1"
          bandwidth="1000000">
        <SegmentTemplate
            presentationTimeOffset="0"
            timescale="1000"
            media="https://video.xx.fbcdn.net/hvideo-lla2/s3/v/dash-hd/10155806047986509-$Time$.m4v"
            initialization="https://video.xx.fbcdn.net/hvideo-lla2/s3/v/dash-hd/10155806047986509-init.m4v">
          <SegmentTimeline>
             <S t="3604000" d="1000"/>
             <S t="3605000" d="1000"/>
             <S t="3606000" d="1000"/>
             <S t="3607000" d="1000"/>
             <S t="3608000" d="1000"/>
             <S t="3609000" d="1000"/>
             <S t="3610000" d="1000"/>
             <S t="3611000" d="1000"/>
             <S t="3612000" d="1000"/>
             <S t="3613000" d="1000"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
      <Representation
          id="live-hd1_H264"
          mimeType="video/mp4"
          codecs="avc1.4d401e"
          width="1280"
          height="720"
          FBQualityClass="hd"
          FBQualityLabel="720p"
          frameRate="30"
          sar="1:1"
          startWithSAP="1"
          bandwidth="2000000">
        <SegmentTemplate
            presentationTimeOffset="0"
            timescale="1000"
            media="https://video.xx.fbcdn.net/hvideo-lla2/s3/v/dash-hd1/10155806047986509-$Time$.m4v"
            initialization="https://video.xx.fbcdn.net/hvideo-lla2/s3/v/dash-hd1/10155806047986509-init.m4v">
          <SegmentTimeline>
             <S t="3604000" d="1000"/>
             <S t="3605000" d="1000"/>
             <S t="3606000" d="1000"/>
             <S t="3607000" d="1000"/>
             <S t="3608000" d="1000"/>
             <S t="3609000" d="1000"/>
             <S t="3610000" d="1000"/>
             <S t="3611000" d="1000"/>
             <S t="3612000" d="1000"/>
             <S t="3613000" d="1000"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
    <AdaptationSet
        id="2"
        segmentAlignment="true">
      <AudioChannelConfiguration
          schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011"
          value="1"/>
      <Representation
          id="live-md_AAC"
          mimeType="audio/mp4"
          codecs="mp4a.40.2"
          audioSamplingRate="48000"
          startWithSAP="1"
          bandwidth="62000">
        <SegmentTemplate
            presentationTimeOffset="0"
            timescale="1000"
            media="https://video.xx.fbcdn.net/hvideo-lla2/s3/v/dash-md/10155806047986509-$Time$.m4a"
            initialization="https://video.xx.fbcdn.net/hvideo-lla2/s3/v/dash-md/10155806047986509-init.m4a">
          <SegmentTimeline>
             <S t="3604000" d="1000"/>
             <S t="3605000" d="1000"/>
             <S t="3606000" d="1000"/>
             <S t="3607000" d="1000"/>
             <S t="3608000" d="1000"/>
             <S t="3609000" d="1000"/>
             <S t="3610000" d="1000"/>
             <S t="3611000" d="1000"/>
             <S t="3612000" d="1000"/>
             <S t="3613000" d="1000"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>
