### ISSUE TITLE
site support request: tvnow.de

### ISSUE THREAD

**Issue by hstracker90** [rg3/youtube-dl#8823] opened 2016-03-11 11:52 UTC
German TV stations changed their website for viewing shows again, now it is http://www.tvnow.de .
Please have a look if youtube-dl could support this site, too. It will be appreciated very much!

Example:
C:\WINDOWS> youtube-dl http://www.tvnow.de/rtl/rtl-nachtjournal/rtl-nachtjournal-2016-folge-049/player
[generic] player: Requesting header
WARNING: Falling back on generic information extractor.
[generic] player: Downloading webpage
[generic] player: Extracting information
ERROR: Unsupported URL: http://www.tvnow.de/rtl/rtl-nachtjournal/rtl-nachtjournal-2016-folge-049/player

**Comment by dstftw** [comment] 2016-03-11 13:52
Duplicate of #7831.

**Closed by dstftw** 2016-03-11 13:52 UTC
