### ISSUE TITLE
Facebook Download Is No More Working

### ISSUE THREAD

**Issue by mtalhaakram** [rg3/youtube-dl#5476] opened 2015-04-20 11:38 UTC
Hello,
      Facebook download is no more working, seems like they have updated mechanism at their end. Please advise if there is any fix available for it so far or not.

Thanks & Regards,
Talha

**Comment by yan12125** [comment] 2015-04-20 11:52
It still works, at least for https://www.facebook.com/video.php?v=637842556329505&fref=nf. Please post the full verbose [output with ```-v``` option](https://github.com/rg3/youtube-dl#bugs)

**Comment by warnecke** [comment] 2015-04-20 15:06
It looks like Facebook is publishing video content using a new URL format...instead of linking to the https://www.facebook.com/video.php?v=[VIDEO-ID] videos are now linked as https://www.facebook.com/[USERNAME]/videos/[VIDEO-ID].

Here's the verbose as requested:

09:59:30 user@system:~/tmp$ youtube-dl -v http://www.facebook.com/gary/videos/10153163439258350/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.facebook.com/gary/videos/10153163439258350/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.17
[debug] Python version 2.7.8 - Linux-3.16.0-34-generic-x86_64-with-Ubuntu-14.10-utopic
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[generic] 10153163439258350: Requesting header
[redirect] Following redirect to https://www.facebook.com/gary/videos/10153163439258350/
[generic] 10153163439258350: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 10153163439258350: Downloading webpage
[generic] 10153163439258350: Extracting information
[redirect] Following redirect to /gary/videos/10153163439258350/?_fb_noscript=1
WARNING: The url doesn't specify the protocol, trying with http
[generic] ?_fb_noscript=1: Requesting header
WARNING: Could not send HEAD request to http:///gary/videos/10153163439258350/?_fb_noscript=1: <urlopen error no host given>
[generic] ?_fb_noscript=1: Downloading webpage
ERROR: Unable to download webpage: <urlopen error no host given> (caused by URLError('no host given',))
  File "/home/user/bin/youtube-dl/youtube_dl/extractor/common.py", line 314, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/user/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1678, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/home/user/bin/youtube-dl/youtube_dl/utils.py", line 613, in http_open
    req)
  File "/usr/lib/python2.7/urllib2.py", line 1136, in do_open
    raise URLError('no host given')

Cheers, /b

**Comment by yan12125** [comment] 2015-04-20 15:36
Yes, and I've fixed it in c62566971fb8877d5ac52bc613d3bd53fe87a8d8 and 53faa3ca5f62c46bb56c0a85d1ed87b911b7ffa4. Such urls can be downloaded in the next version of youtube-dl. If you need the feature now, you can try the lastest git commit or use the old URL format ```https://www.facebook.com/video.php?v=10153163439258350```

@mtalhaakram, did you encounter the same problem?

**Comment by mtalhaakram** [comment] 2015-04-20 17:54
Yes as the new URL format I can see is:

https://www.facebook.com/Zubi.FunZone/videos/vb.207462935964291/917594151617829/?type=2&theater

but when I am trying manually to change the URL from :

https://www.facebook.com/Zubi.FunZone/videos/vb.207462935964291/917594151617829/?type=2&theater

to 

https://www.facebook.com/video.php?v=917594151617829

it worked fine but not with the new URL format.

**Comment by warnecke** [comment] 2015-04-20 17:59
Thanks for the quick fix, @yan12125!

Cheers, /b

**Comment by yan12125** [comment] 2015-04-20 18:03
@mtalhaakram, all of the three above URL formats are supported since 53faa3ca5f62c46bb56c0a85d1ed87b911b7ffa4. Please wait patiently for the new version or try the latest git commit. If you have ```pip``` or ```pip.exe```, you can try the following command to install the latest git version: (**Warning**: the following step may cause conflicts between the stable version and the git version)
```
pip install --user git+https://github.com/rg3/youtube-dl/
```

Now I'm closing this issue because it's already solved.

**Closed by yan12125** 2015-04-20 18:03 UTC

**Comment by mtalhaakram** [comment] 2015-04-20 19:03
Thanks @yan12125
