### ISSUE TITLE
-o - (stdout) not working for twitch.tv

### ISSUE THREAD

**Issue by Cryspart** [rg3/youtube-dl#9183] opened 2016-04-13 17:08 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.04.13*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.13**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl https://www.twitch.tv/imaqtpie -o - --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.twitch.tv/imaqtpie', u'-o', u'-', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.13
[debug] Python version 2.7.6 - Linux-3.19.0-58-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, ffmpeg N-79139-gde1a0d4, ffprobe N-79139-gde1a0d4, rtmpdump 2.4
[debug] Proxy map: {}
[twitch:stream] imaqtpie: Downloading stream JSON
[twitch:stream] imaqtpie: Downloading channel access token
[twitch:stream] imaqtpie: Downloading m3u8 information
[debug] Invoking downloader on u'http://video-edge-49a880.cdg01.hls.ttvnw.net/hls78/imaqtpie_20785763696_435471509/chunked/index-live.m3u8?token=id=4915723868490542757,bid=20785763696,exp=1460653074,node=video-edge-49a880-1.cdg01.hls.justin.tv,nname=video-edge-49a880.cdg01,fmt=chunked&sig=b77671011d0254e25d18b3c1d991060f6b9d8bbb'
[download] Destination: -
WARNING: Your copy of avconv is outdated, update avconv to version 10-0 or newer if you encounter any errors.
[debug] avconv command line: avconv -y -headers 'Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/44.0 (Chrome)
' -i 'http://video-edge-49a880.cdg01.hls.ttvnw.net/hls78/imaqtpie_20785763696_435471509/chunked/index-live.m3u8?token=id=4915723868490542757,bid=20785763696,exp=1460653074,node=video-edge-49a880-1.cdg01.hls.justin.tv,nname=video-edge-49a880.cdg01,fmt=chunked&sig=b77671011d0254e25d18b3c1d991060f6b9d8bbb' -c copy -f mp4 -bsf:a aac_adtstoasc file:-
avconv version 9.18-6:9.18-0ubuntu0.14.04.1+fdkaac, Copyright (c) 2000-2014 the Libav developers
  built on Apr 10 2015 23:18:58 with gcc 4.8 (Ubuntu 4.8.2-19ubuntu1)
[hls,applehttp @ 0x1804280] max_analyze_duration reached
[hls,applehttp @ 0x1804280] Estimating duration from bitrate, this may be inaccurate
Input #0, hls,applehttp, from 'http://video-edge-49a880.cdg01.hls.ttvnw.net/hls78/imaqtpie_20785763696_435471509/chunked/index-live.m3u8?token=id=4915723868490542757,bid=20785763696,exp=1460653074,node=video-edge-49a880-1.cdg01.hls.justin.tv,nname=video-edge-49a880.cdg01,fmt=chunked&sig=b77671011d0254e25d18b3c1d991060f6b9d8bbb':
  Duration: N/A, start: 21205.685000, bitrate: N/A
    Stream #0.0: Audio: aac, 48000 Hz, stereo, fltp
    Stream #0.1: Video: h264 (Main), yuv420p, 1280x720, 59.94 fps, 1k tbr, 90k tbn, 120 tbc
    Stream #0.2: Data: [21][0][0][0] / 0x0015
Output #0, mp4, to 'file:-':
  Metadata:
    encoder         : Lavf54.20.4
    Stream #0.0: Video: libx264, yuv420p, 1280x720, q=2-31, 90k tbn, 90k tbc
    Stream #0.1: Audio: aac, 48000 Hz, stereo
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
  Stream #0:0 -> #0:1 (copy)
Press ctrl-c to stop encoding
Non-monotonous DTS in output stream 0:1; previous: 0, current: 0; changing to 1. This may result in incorrect timestamps in the output file.
frame=  484 fps= 82 q=-1.0 Lsize=    3204kB time=8.00 bitrate=3281.0kbits/s     
video:3033kB audio:159kB global headers:0kB muxing overhead 0.382408%
Received signal 2: terminating.

ERROR: Interrupted by user

```

---
---

### Description of your *issue*, suggested solution and other information

The stdout option (-o -) doesn't print the video data in the stdout for live streams in twitch.tv (but it works for live streams in hitbox.com) but instead creates a file called "-" where the video data is written. 

EDIT: i've also tested with --prefer-ffmpeg but it also creates a file.

**Comment by yan12125** [comment] 2016-04-14 18:50
Duplicate of #2124. A solution is proposed in #9195.

**Closed by yan12125** 2016-04-14 18:50 UTC
