### ISSUE TITLE
iprima - Unable to extract zoneGEO

### ISSUE THREAD

**Issue by cz-michi** [rg3/youtube-dl#7874] opened 2015-12-15 08:04 UTC
hello, after site style change, the iprima extractor stopped working, reporting "Unable to extract zoneGEO"

youtube-dl --verbose http://play.iprima.cz/vinari/vinari-ii-16

**Comment by dstftw** [comment] 2015-12-15 14:14
Duplicate of #7617.

**Closed by dstftw** 2015-12-15 14:14 UTC
