### ISSUE TITLE
No video formats found when using youtube-dl. Working till yesterday.

### ISSUE THREAD

**Issue by nionebirk** [rg3/youtube-dl#7469] opened 2015-11-12 13:01 UTC
youtube-dl --verbose https://vimeo.com/95653848
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://vimeo.com/95653848&apos;]
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.10
[debug] Python version 2.7.3 - Linux-4.1.5-x86_64-linode61-x86_64-with-Ubuntu-12.04-precise
[debug] exe versions: avconv 0.8.17-4, avprobe 0.8.17-4, ffmpeg 0.8.17-4, ffprobe 0.8.17-4, rtmpdump 2.4
[debug] Proxy map: {}
[vimeo] 95653848: Downloading webpage
[vimeo] 95653848: Extracting information
[vimeo] 95653848: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update ; on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/vimeo.py", line 378, in _real_extract
    view_count = int(self._search_regex(r'UserPlays:(\d+)', webpage, 'view count'))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 584, in _search_regex    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract view count; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update ; on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/vimeo.py", line 427, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 766, in _sort_formats    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update ; on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output

**Comment by skyghis** [comment] 2015-11-12 13:28
I confirm vimeo videos broken on youtube-dl version 2015.11.10

```
youtube-dl --verbose https://vimeo.com/145108228
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://vimeo.com/145108228']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.10
[debug] Python version 2.7.9 - Linux-3.19.0-32-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, rtmpdump 2.4
[debug] Proxy map: {}
[vimeo] 145108228: Downloading webpage
[vimeo] 145108228: Extracting information
[vimeo] 145108228: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/ghislain/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 378, in _real_extract
    view_count = int(self._search_regex(r'UserPlays:(\d+)', webpage, 'view count'))
  File "/home/ghislain/bin/youtube-dl/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract view count; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/ghislain/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/home/ghislain/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/home/ghislain/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 427, in _real_extract
    self._sort_formats(formats)
  File "/home/ghislain/bin/youtube-dl/youtube_dl/extractor/common.py", line 766, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment] 2015-11-12 13:39
Duplicate of #7460.
It's already fixed and will be included in the next version.

**Closed by dstftw** 2015-11-12 13:39 UTC

**Comment by nionebirk** [comment] 2015-11-12 14:41
Thank you for your quick response
