### ISSUE TITLE
HTTP Error 500: Internal Server Error 

### ISSUE THREAD

**Issue by videoguy-canada** [rg3/youtube-dl#8942] opened 2016-03-22 21:05 UTC
Hey guys, getting this error:

HTTP Error 500: Internal Server Error (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output

It happens with every Vevo file I try.  Usually you guys are pretty quick to post a fix.  Been happening since Friday.  Any word on this?

Thanks

**Comment by dstftw** [comment] 2016-03-22 21:06
Duplicate of #8900.

**Closed by dstftw** 2016-03-22 21:06 UTC
