### ISSUE TITLE
Liveleak download doesn't work anymore. 

### ISSUE THREAD

**Issue by koreus** [rg3/youtube-dl#11806] opened 2017-01-22 14:04 UTC
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.22**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
$ youtube-dl --verbose http://www.liveleak.com/view?i=fb3_1485068072
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'http://www.liveleak.com/view?i=fb3_1485068072']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.01.22
[debug] Python version 2.7.10 - Darwin-16.3.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4
[debug] Proxy map: {}
[LiveLeak] fb3_1485068072: Downloading webpage
ERROR: Unable to extract embed URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 359, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/liveleak.py", line 107, in _real_extract
    webpage, 'embed URL')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 662, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract embed URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

Liveleak download doesn't work anymore.

**Comment by xzoLx** [comment] 2017-01-28 20:27
I think they have a new video player.  It doesn't look like the old one.  But yes, LiveLeak isn't working for me either.

**Comment by yan12125** [comment] 2017-02-01 08:22
Duplicate of #7506. #6869 may help

**Closed by yan12125** 2017-02-01 08:22 UTC
