### ISSUE TITLE
[naver] Add support for multi track videos

### ISSUE THREAD

**Issue by taeyeon-ss** [rg3/youtube-dl#7025] opened 2015-09-30 19:12 UTC
youtube-dl.exe "http://tvcast.naver.com/v/434716"

[Naver] 434716: Downloading webpage

ERROR: couldn't extract vid and key; please report this issue on https://yt-dl.org/bug . 
Make sure you are using the latest version; type  youtube-dl -U  to update. 
Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment] 2015-09-30 20:20
Duplicate of #5857.

**Comment by dstftw** [comment] 2015-09-30 20:44
Duplicate of #3711.

**Closed by dstftw** 2015-09-30 20:44 UTC
