### ISSUE TITLE
Can't download song

### ISSUE THREAD

**Issue by Maktos** [rg3/youtube-dl#6582] opened 2015-08-16 18:22 UTC
youtube-dl https://www.youtube.com/watch?v=PkSp8wc8lKw --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=PkSp8wc8lKw', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.16
[debug] Python version 2.7.6 - Linux-3.16.0-38-generic-x86_64-with-LinuxMint-17.2-rafaela
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] PkSp8wc8lKw: Downloading webpage
[youtube] PkSp8wc8lKw: Downloading video info webpage
[youtube] PkSp8wc8lKw: Extracting video information
[youtube] {43} signature length 40.42, html5 player new
[youtube] {18} signature length 40.42, html5 player new
[youtube] {5} signature length 40.42, html5 player new
[youtube] {36} signature length 40.42, html5 player new
[youtube] {17} signature length 40.42, html5 player new
[youtube] {135} signature length 40.42, html5 player new
[youtube] {244} signature length 40.42, html5 player new
[youtube] {134} signature length 40.42, html5 player new
[youtube] {243} signature length 40.42, html5 player new
[youtube] {133} signature length 40.42, html5 player new
[youtube] {242} signature length 40.42, html5 player new
[youtube] {160} signature length 40.42, html5 player new
[youtube] {140} signature length 40.42, html5 player new
[youtube] {171} signature length 40.42, html5 player new
[youtube] PkSp8wc8lKw: Downloading DASH manifest
WARNING: [youtube] PkSp8wc8lKw: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[debug] Invoking downloader on u'https://r5---sn-q4f7sn7r.googlevideo.com/videoplayback?mt=1439749104&mv=m&ms=au&requiressl=yes&ratebypass=yes&mm=31&mn=sn-q4f7sn7r&source=youtube&initcwndbps=372500&id=o-AN6mAd6BOF98YykUDZKRT6E5Ov8Fu69Bc6gKRG9FD_uN&sver=3&key=yt5&ip=216.45.65.54&lmt=1429601091800253&dur=301.441&expire=1439770765&upn=t9T6wV6lYnk&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&ipbits=0&fexp=9406821%2C9408710%2C9408891%2C9409069%2C9415365%2C9415436%2C9415485%2C9416023%2C9416126%2C9416729%2C9416768%2C9416984%2C9417193%2C9417707%2C9418018%2C9418144%2C9418153%2C9418617%2C9419294%2C9419329%2C9419403%2C9419444%2C9419504&mime=video%2Fmp4&pl=19&itag=18&signature=223BE1A65F27D1EFFAE1B6EB0B594CB8CFC43E28.7E81E1110448487090A3D4679C67C690C241D4FE'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1585, in process_info
    success = dl(filename, info_dict)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1527, in dl
    return fd.download(name, info)
  File "./youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "./youtube-dl/youtube_dl/downloader/http.py", line 60, in real_download
    data = self.ydl.urlopen(request)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1860, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden

**Comment by dstftw** [comment] 2015-08-16 18:23
Duplicate of #6451. Remove cache with `youtube-dl --rm-cache-dir`.

**Closed by dstftw** 2015-08-16 18:23 UTC
