### ISSUE TITLE
[Mixcloud] Add support for channels/playlists

### ISSUE THREAD

**Issue by GijsTimmers** [rg3/youtube-dl#5272] opened 2015-03-24 10:09 UTC
```
[me@pc /tmp]$ youtube-dl --version
2015.03.18
[me@pc /tmp]$ youtube-dl -x --audio-format "mp3" --restrict-filenames -o "%(title)s.%(ext)s" --verbose https://www.mixcloud.com/LeFtOoO/uploads/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-x', '--audio-format', 'mp3', '--restrict-filenames', '-o', '%(title)s.%(ext)s', '--verbose', 'https://www.mixcloud.com/LeFtOoO/uploads/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.18
[debug] Python version 2.7.6 - Linux-3.16.0-33-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 1.2.6-7, avprobe 1.2.6-7, ffmpeg 1.2.6-7, ffprobe 1.2.6-7
[debug] Proxy map: {}
[mixcloud] LeFtOoO-uploads: Downloading webpage
[mixcloud] LeFtOoO-uploads: Checking URL 21/30 ...
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 654, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/mixcloud.py", line 89, in _real_extract
    PREFIX + r'm-title="([^"]+)"', webpage, 'title')
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 557, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 547, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

[me@pc /tmp]$ 
```

**Comment by rbu** [comment] 2015-05-04 07:50
duplicate of #5272 ?

**Comment by bellwood** [comment] 2015-11-24 21:28
Is there any update for this? The 11.24.2015 build does not work for mixcloud... 

All attempts through "Unable to extract title" errors

Thank you =)

**Comment by yan12125** [comment] 2016-04-15 07:51
Thanks to @Phaeilo Mixcloud playlists and user pages will be supported in the next version.

**Closed by yan12125** 2016-04-15 07:51 UTC
Labels: site-support-request
