### ISSUE TITLE
Soundcloud fails: ERROR: Unable to download JSON metadata

### ISSUE THREAD

**Issue by L337hium** [rg3/youtube-dl#6982] opened 2015-09-26 12:55 UTC
```
$ youtube-dl --version
2015.09.22

$ youtube-dl --verbose --list-formats http://soundcloud.com/...
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--list-formats', u'http://soundcloud.com/...']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.22
[debug] Python version 2.7.10 - Linux-4.1.0-1-amd64-x86_64-with-debian-stretch-sid
[debug] exe versions: avconv 2.7.2, avprobe 2.7.2, ffmpeg 2.7.2, ffprobe 2.7.2, rtmpdump 2.4
[debug] Proxy map: {}
[soundcloud] ...: Resolving id
[soundcloud] ...: Downloading info JSON
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 326, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1865, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

**Comment by dstftw** [comment] 2015-09-26 12:55
Duplicate of #6930.
This is already fixed in master and will be incorporated in the next version of youtube-dl.

**Closed by dstftw** 2015-09-26 12:55 UTC

**Comment by L337hium** [comment] 2015-09-26 16:17
Ups, searched only in open issues :/
