### ISSUE TITLE
VRV.co 

### ISSUE THREAD

**Issue by tetra-archos** [rg3/youtube-dl#15937] opened 2018-03-21 02:32 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.20*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.20**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2018.03.20
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Unable to use youtube-dl on VRV.co for shows requiring an account even when passing login through cookies.

In this test I am not able to download Black Clover as a Series or on a per episode basis.

Series:

```
[03/20/18 22:08:39] 
[03/20/18 22:23:28] [debug] System config: []
[03/20/18 22:23:28] [debug] User config: []
[03/20/18 22:23:28] [debug] Custom config: []
[03/20/18 22:23:28] [debug] Command-line args: ['--newline', '-i', '-o', 'C:\\Users\\tetra\\%(title)s.%(ext)s', '-f', 'mp4', '-v', '--ignore-config', '--hls-prefer-native', '--cookies', 'C:\\Users\\tetra\\Downloads\\Youtube-DL\\cookies.txt', 'https://vrv.co/series/GR2PQVD7R/Black-Clover']
[03/20/18 22:23:28] [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[03/20/18 22:23:28] [debug] youtube-dl version 2018.03.20
[03/20/18 22:23:28] [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[03/20/18 22:23:28] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[03/20/18 22:23:28] [debug] Proxy map: {}
[03/20/18 22:23:28] ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[03/20/18 22:23:28]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbt_jbnlh\build\youtube_dl\extractor\common.py", line 519, in _request_webpage
[03/20/18 22:23:28]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbt_jbnlh\build\youtube_dl\YoutubeDL.py", line 2199, in urlopen
[03/20/18 22:23:28]   File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
[03/20/18 22:23:28]   File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
[03/20/18 22:23:28]   File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
[03/20/18 22:23:28]   File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
[03/20/18 22:23:28]   File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
[03/20/18 22:23:28] 
```

Episode: 

```
[03/20/18 22:23:28] 
[03/20/18 22:27:48] [debug] System config: []
[03/20/18 22:27:48] [debug] User config: []
[03/20/18 22:27:48] [debug] Custom config: []
[03/20/18 22:27:48] [debug] Command-line args: ['--newline', '-i', '-o', 'C:\\Users\\tetra\\%(title)s.%(ext)s', '-f', 'mp4', '-v', '--ignore-config', '--hls-prefer-native', '--cookies', 'C:\\Users\\tetra\\Downloads\\Youtube-DL\\cookies.txt', 'https://vrv.co/watch/GR2PQJ32R/Black-Clover:A-Young-Mans-Vow']
[03/20/18 22:27:48] [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[03/20/18 22:27:48] [debug] youtube-dl version 2018.03.20
[03/20/18 22:27:48] [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[03/20/18 22:27:48] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[03/20/18 22:27:48] [debug] Proxy map: {}
[03/20/18 22:27:48] ERROR: An extractor error has occurred. (caused by KeyError('streams',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[03/20/18 22:27:48] Traceback (most recent call last):
[03/20/18 22:27:48]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbt_jbnlh\build\youtube_dl\extractor\common.py", line 440, in extract
[03/20/18 22:27:48]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbt_jbnlh\build\youtube_dl\extractor\vrv.py", line 110, in _real_extract
[03/20/18 22:27:48] KeyError: 'streams'
[03/20/18 22:27:48] Traceback (most recent call last):
[03/20/18 22:27:48]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbt_jbnlh\build\youtube_dl\extractor\common.py", line 440, in extract
[03/20/18 22:27:48]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbt_jbnlh\build\youtube_dl\extractor\vrv.py", line 110, in _real_extract
[03/20/18 22:27:48] KeyError: 'streams'
[03/20/18 22:27:48] 
[03/20/18 22:27:48] During handling of the above exception, another exception occurred:
[03/20/18 22:27:48] 
[03/20/18 22:27:48] Traceback (most recent call last):
[03/20/18 22:27:48]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbt_jbnlh\build\youtube_dl\YoutubeDL.py", line 785, in extract_info
[03/20/18 22:27:48]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbt_jbnlh\build\youtube_dl\extractor\common.py", line 453, in extract
[03/20/18 22:27:48] youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('streams',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[03/20/18 22:27:48] 
```

**Comment by shinji257** [comment] 2018-05-03 09:10
This is related to https://github.com/rg3/youtube-dl/issues/14307.

**Comment by remitamine** [comment] 2018-05-03 09:13
Duplicate of #14307.

**Closed by remitamine** 2018-05-03 09:13 UTC
