### ISSUE TITLE
Embed subtitles at the same time when merging video and audio

### ISSUE THREAD

**Issue by nyuszika7h** [rg3/youtube-dl#13713] opened 2017-07-23 12:42 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.23*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.23**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

When video and audio has to be merged and `--embed-subs` is used, the subtitles should be also muxed at the same time as the video and audio, that would be much faster.

**Comment by nyuszika7h** [comment] 2017-07-23 12:51
Sorry, I just noticed this is a duplicate of #6996.

**Comment by yan12125** [comment] 2017-07-23 13:19
Partial duplicate of #8476. The major difficulty is how to create a command that does multiple jobs at a time and compatible with recent avconv/ffmpeg versions. If you have a good idea, feel free to post there.

**Closed by yan12125** 2017-07-23 13:19 UTC
