### ISSUE TITLE
[Twitch] Premium VOD Failed to Download m3u8 Information

### ISSUE THREAD

**Issue by Synesthesia93** [rg3/youtube-dl#6939] opened 2015-09-23 19:42 UTC
I am attempting to download a Premium Twitch VOD using the following command. The username and password options have been omitted, but you can see authentication appears to be successful in the logging. Note that I have renamed the executable to "youtube-dl-o".

youtube-dl-o -f Source http://www.twitch.tv/mingthemerciless93/v/8538217 --verbose

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-f', u'Sourc
e', u'http://www.twitch.tv/mingthemerciless93/v/8538217', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.09.22
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[twitch:vod] Downloading login page
[twitch:vod] Logging in as Synesthesia93
[twitch:vod] 8538217: Downloading vod info JSON
[twitch:vod] 8538217: Downloading vod access token
[twitch:vod] 8538217: Downloading m3u8 information
ERROR: Failed to download m3u8 information: HTTP Error 403: ERROR (caused by HTT
PError()); please report this issue on https://yt-dl.org/bug . Make sure you are
 using the latest version; type  youtube-dl -U  to update. Be sure to call youtu
be-dl with the --verbose flag and include its complete output.
  File "youtube_dl\extractor\common.pyo", line 326, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1865, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default

**Comment by dstftw** [comment] 2015-09-24 17:28
Duplicate of #6628.

**Closed by dstftw** 2015-09-24 17:28 UTC
