### ISSUE TITLE
It can not get srt fomat cpation by --convert-subs srt when using --skip-download 

### ISSUE THREAD

**Issue by CloudedDragon** [rg3/youtube-dl#9186] opened 2016-04-13 20:02 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.13**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely 
```
 $ youtube-dl -v https://www.youtube.com/watch\?v\=Y6e_m9iq-4Q --skip-download --write-sub --all-subs --convert-subs srt
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=Y6e_m9iq-4Q', u'--skip-download', u'--write-sub', u'--all-subs', u'--convert-subs', u'srt']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.13
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2
[debug] Proxy map: {}
[youtube] Y6e_m9iq-4Q: Downloading webpage
[youtube] Y6e_m9iq-4Q: Downloading video info webpage
[youtube] Y6e_m9iq-4Q: Extracting video information
[youtube] Y6e_m9iq-4Q: Downloading MPD manifest
[info] Writing video subtitles to: What are those floaty things in your eye - Michael Mauser-Y6e_m9iq-4Q.my.vtt
[info] Writing video subtitles to: What are those floaty things in your eye - Michael Mauser-Y6e_m9iq-4Q.ru.vtt
[info] Writing video subtitles to: What are those floaty things in your eye - Michael Mauser-Y6e_m9iq-4Q.fr.vtt
[info] Writing video subtitles to: What are those floaty things in your eye - Michael Mauser-Y6e_m9iq-4Q.en.vtt
[info] Writing video subtitles to: What are those floaty things in your eye - Michael Mauser-Y6e_m9iq-4Q.nl.vtt
[info] Writing video subtitles to: What are those floaty things in your eye - Michael Mauser-Y6e_m9iq-4Q.th.vtt
[info] Writing video subtitles to: What are those floaty things in your eye - Michael Mauser-Y6e_m9iq-4Q.zh-Hans.vtt
[info] Writing video subtitles to: What are those floaty things in your eye - Michael Mauser-Y6e_m9iq-4Q.zh-TW.vtt
[info] Writing video subtitles to: What are those floaty things in your eye - Michael Mauser-Y6e_m9iq-4Q.tr.vtt
[info] Writing video subtitles to: What are those floaty things in your eye - Michael Mauser-Y6e_m9iq-4Q.it.vtt
[info] Writing video subtitles to: What are those floaty things in your eye - Michael Mauser-Y6e_m9iq-4Q.iw.vtt
[info] Writing video subtitles to: What are those floaty things in your eye - Michael Mauser-Y6e_m9iq-4Q.sk.vtt
[info] Writing video subtitles to: What are those floaty things in your eye - Michael Mauser-Y6e_m9iq-4Q.hr.vtt
[info] Writing video subtitles to: What are those floaty things in your eye - Michael Mauser-Y6e_m9iq-4Q.ar.vtt
[info] Writing video subtitles to: What are those floaty things in your eye - Michael Mauser-Y6e_m9iq-4Q.pt-BR.vtt
[info] Writing video subtitles to: What are those floaty things in your eye - Michael Mauser-Y6e_m9iq-4Q.ko.vtt
[info] Writing video subtitles to: What are those floaty things in your eye - Michael Mauser-Y6e_m9iq-4Q.sr.vtt
[info] Writing video subtitles to: What are those floaty things in your eye - Michael Mauser-Y6e_m9iq-4Q.fa-AF.vtt
[info] Writing video subtitles to: What are those floaty things in your eye - Michael Mauser-Y6e_m9iq-4Q.es-ES.vtt
[info] Writing video subtitles to: What are those floaty things in your eye - Michael Mauser-Y6e_m9iq-4Q.ja.vtt
[info] Writing video subtitles to: What are those floaty things in your eye - Michael Mauser-Y6e_m9iq-4Q.pl.vtt
```
---
It can not get SRT format caption by --convert-subs srt when using --skip-download
It just provide the caption in VTT format. 
But if I remove "--skip-download" parameter, and then I can get caption by format SRT

I just want to get caption in format SRT without video and audio files, please help to fix me 
thank you :)

**Comment by dstftw** [comment] 2016-04-13 23:20
Duplicate of #9073.

**Closed by dstftw** 2016-04-13 23:20 UTC
