### ISSUE TITLE
Youtube playlist download error

### ISSUE THREAD

**Issue by SomeBody16** [rg3/youtube-dl#14095] opened 2017-09-01 14:28 UTC
I don't know why error, a few weeks ago everything working but now...

```
$ youtube-dl --verbose -i --download-archive SomeMusic.data https://www.youtube.com/playlist?list=PLo7WlwXTh7_Emg4gJLvKXYlUv2O7fQEKE
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-i', '--download-archive', 'SomeMusic.data', 'https://www.youtube.com/playlist?list=PLo7WlwXTh7_Emg4gJLvKXYlUv2O7fQEKE']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2014.08.05
[debug] Python version 2.7.9 - Linux-2.6.32-042stab123.9-x86_64-with-debian-8.5
[debug] Proxy map: {}
[youtube:playlist] PLo7WlwXTh7_Emg4gJLvKXYlUv2O7fQEKE: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 170, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1050, in _real_extract
    page, u'title')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 401, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 391, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

$ 
```

Please help me :<

**Comment by C4K3** [comment] 2017-09-01 14:35
Likely duplicate of #14083

**Closed** 2017-09-01 17:19 UTC
