### ISSUE TITLE
[Toggle does not work]

### ISSUE THREAD

**Issue by maidenform** [rg3/youtube-dl#12800] opened 2017-04-20 13:00 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.17*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.17**

### Before submitting an *issue* make sure you have:
- [ X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

# youtube-dl -v http://video.toggle.sg/en/series/faculty/ep10/482062
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://video.toggle.sg/en/series/faculty/ep10/482062']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.17
[debug] Python version 2.7.12 - Linux-4.4.0-57-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.11-0ubuntu0.16.04.1, avprobe 2.8.11-0ubuntu0.16.04.1, ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[toggle] 482062: Downloading video page
[toggle] 482062: Downloading video info json
[toggle] 482062: Downloading STBMain m3u8 information
[toggle] 482062: Downloading iPhoneMain m3u8 information
[toggle] 482062: Downloading iPadMain m3u8 information
[toggle] 482062: Downloading Android m3u8 information
[toggle] 482062: Downloading HLS_Mobile m3u8 information
ERROR: An extractor error has occurred. (caused by KeyError(u'vcodec',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/toggle.py", line 139, in _real_extract
    fatal=False))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 1427, in _extract_m3u8_formats
    if audio_in_video_stream.get(last_info.get('AUDIO')) is False and f['vcodec'] != 'none':
KeyError: u'vcodec'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 442, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'vcodec',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### Description of your *issue*, suggested solution and other information

Youtube_dl used to work without problem on this site. Recently, it does not work anymore.

**Comment by dstftw** [comment] 2017-04-20 14:34
Duplicate of #12211.

**Closed by dstftw** 2017-04-20 14:34 UTC
