### ISSUE TITLE
Nowvideo problem with some streams

### ISSUE THREAD

**Issue by apolo188** [rg3/youtube-dl#11214] opened 2016-11-16 23:04 UTC
Some streams works fine like this:http://www.nowvideo.sx/video/c0fdbd803f1fe but others like this :http://www.nowvideo.sx/video/36b65b8c28de1 [ytdl_hook] ERROR: Unable to extract filekey; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update,Idont know why

**Comment by yan12125** [comment] 2016-11-17 03:00
Duplicate of #10414

**Closed by yan12125** 2016-11-17 03:00 UTC
