### ISSUE TITLE
Sprout - Comcast - Unable to extract post url

### ISSUE THREAD

**Issue by Barbegazi** [rg3/youtube-dl#12563] opened 2017-03-26 14:02 UTC
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.24**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Bug report (encountered problems with youtube-dl)
```
C:\>youtube-dl.exe --ap-mso=Comcast_SSO --ap-username=foo --ap-password=bar --verbose http://www.sproutonline.com/watch/sahara-sled
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ap-mso=Comcast_SSO', '--ap-username=PRIVATE', '--ap-password=PRIVATE', '--verbose', 'http://www.sproutonline.com/watch/sahara-sled']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.03.24
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-84348-gdb7a05d, ffprobe N-84348-gdb7a05d
[debug] Proxy map: {}
[Sprout] sahara-sled: Downloading webpage
[Sprout] VobWK3VzW4oI: Downloading Provider Redirect Page
ERROR: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\build\youtube_dl\YoutubeDL.py", line 761, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\build\youtube_dl\extractor\common.py", line 428, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\build\youtube_dl\extractor\sprout.py", line 43, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\build\youtube_dl\extractor\adobepass.py", line 1409, in _extract_mvpd_auth
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\build\youtube_dl\extractor\adobepass.py", line 1332, in post_form
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\build\youtube_dl\extractor\common.py", line 776, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\build\youtube_dl\extractor\common.py", line 767, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

C:\>youtube-dl.exe --restrict-filenames --continue --no-check-certificate --verbose --ap-mso=Comcast_SSO --ap-username=foo --ap-password=bar "http://www.sproutonline.com/watch/sahara-sled"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--restrict-filenames', '--continue', '--no-check-certificate', '--verbose', '--ap-mso=Comcast_SSO', '--ap-username=PRIVATE', '--ap-password=PRIVATE', 'http://www.sproutonline.com/watch/sahara-sled']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.03.24
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-84348-gdb7a05d, ffprobe N-84348-gdb7a05d
[debug] Proxy map: {}
[Sprout] sahara-sled: Downloading webpage
[Sprout] VobWK3VzW4oI: Downloading Provider Redirect Page
ERROR: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\build\youtube_dl\YoutubeDL.py", line 761, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\build\youtube_dl\extractor\common.py", line 428, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\build\youtube_dl\extractor\sprout.py", line 43, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\build\youtube_dl\extractor\adobepass.py", line 1409, in _extract_mvpd_auth
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\build\youtube_dl\extractor\adobepass.py", line 1332, in post_form
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\build\youtube_dl\extractor\common.py", line 776, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\build\youtube_dl\extractor\common.py", line 767, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
---
I'm getting this "ERROR:  Unable to extract post url" message any time I try to download a video from http://www.sproutonline.com. 

I'm able to view the videos in my web-browser, after I authenticate that Comcast Xfinity is my service provide.  Interestingly, I don't have to provide my username or password in the browser when doing this authentication - it just automatically recognizes my provider and authenticates me.

**Comment by yan12125** [comment] 2017-05-05 08:08
Most likely a duplicate of #11257.

**Closed by yan12125** 2017-05-05 08:08 UTC
Labels: tv-provider-account-needed
