### ISSUE TITLE
[Feature Request - twitch.tv] Can we have an option to download the specific part of VOD?

### ISSUE THREAD

**Issue by themegabyte** [rg3/youtube-dl#8699] opened 2016-02-29 12:09 UTC
For example:
 start: 08:34:00 end 08:40:00

this will download the video file starting from 08:34:00 to 08:40:00 (i:e 7 mins long)

**Comment by dstftw** [comment] 2016-02-29 14:11
Duplicate of #622.
That is not possible at the moment. You may try using [ffmpeg](https://github.com/rg3/youtube-dl/issues/4821#issuecomment-97564929).

**Closed by dstftw** 2016-02-29 14:11 UTC

**Comment by i-cant-git** [comment] 2016-08-18 20:05
You can start a video from a specific part with `?t=1000s` (start at 1000 seconds)
I think one should be able to do the same in youtube-dl.
