### ISSUE TITLE
Downloading from YT doesn't work anymore!

### ISSUE THREAD

**Issue by sinilill** [rg3/youtube-dl#6693] opened 2015-08-27 13:45 UTC
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=i3I_WI-ce3k']
[debug] Encodings: locale cp1257, fs mbcs, out cp775, pref cp1257
[debug] youtube-dl version 2015.08.23
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-69258-gf994000, ffprobe N-69258-gf994000
[debug] Proxy map: {}
[youtube] i3I_WI-ce3k: Downloading webpage
[youtube] i3I_WI-ce3k: Downloading video info webpage
[youtube] i3I_WI-ce3k: Extracting video information
[youtube] {22} signature length 40.43, html5 player new
[youtube] {43} signature length 40.43, html5 player new
[youtube] {18} signature length 40.43, html5 player new
[youtube] {5} signature length 40.43, html5 player new
[youtube] {36} signature length 40.43, html5 player new
[youtube] {17} signature length 40.43, html5 player new
[youtube] {13} signature length 40.43, html5 player new
[youtube] {137} signature length 40.43, html5 player new
[youtube] {136} signature length 40.43, html5 player new
[youtube] {135} signature length 40.43, html5 player new
[youtube] {134} signature length 40.43, html5 player new
[youtube] {133} signature length 40.43, html5 player new
[youtube] {160} signature length 40.43, html5 player new
[youtube] {140} signature length 40.43, html5 player new
[youtube] i3I_WI-ce3k: Downloading DASH manifest
WARNING: [youtube] i3I_WI-ce3k: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[debug] Invoking downloader on u'https://r2---sn-nu5gh5o-uaae.googlevideo.com/videoplayback?id=o-AChfCU2-uhIqrZT5nPYDZ69y5aN2a7DFVmdJpUiakJ_C&keepalive=yes&expire=1440704451&mm=31&ms=au&pl=17&mv=m&ipbits=0&ip=85.253.50.82&sver=3&sparams=clen%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&itag=137&source=youtube&upn=o_ZcSdMFoBA&key=yt5&mime=video%2Fmp4&mn=sn-nu5gh5o-uaae&requiressl=yes&initcwndbps=3078750&gir=yes&fexp=9406013%2C9408513%2C9408710%2C9409069%2C9412773%2C9413313%2C9415365%2C9415485%2C9416023%2C9416126%2C9416312%2C9416334%2C9416729%2C9417097%2C9417269%2C9417707%2C9417786%2C9418153%2C9418448%2C9419216%2C9419444%2C9419487%2C9420022&dur=265.232&lmt=1378652691697649&mt=1440682727&clen=124489362&signature=88084E1DFCD612464046B539EC8F9810C1AE1D3D.BF2EA49E988748A2EBC4F861D9113ED2DB65E62A&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1579, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1527, in dl
  File "youtube_dl\downloader\common.pyo", line 342, in download
  File "youtube_dl\downloader\http.pyo", line 60, in real_download
  File "youtube_dl\YoutubeDL.pyo", line 1860, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default
HTTPError: HTTP Error 403: Forbidden

**Comment by jaimeMF** [comment] 2015-08-27 14:01
Duplicate of #6451. Remove cache with `youtube-dl --rm-cache-dir`.

**Closed by jaimeMF** 2015-08-27 14:01 UTC

**Comment by sinilill** [comment] 2015-08-27 14:07
Thanks
