### ISSUE TITLE
Type error: LoardLibrary() argument 1 must be strign not unicode

### ISSUE THREAD

**Issue by milo123milo** [rg3/youtube-dl#11593] opened 2017-01-03 16:14 UTC
Every time i run any command or just type youtube-dl i get this error: 

`Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_m
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\youtube-dl.exe\__main__.py", line 9,
  File "c:\python27\lib\site-packages\youtube_dl\__init__.py", l
    _real_main(argv)
  File "c:\python27\lib\site-packages\youtube_dl\__init__.py", l
    setproctitle('youtube-dl')
  File "c:\python27\lib\site-packages\youtube_dl\utils.py", line
    libc = ctypes.cdll.LoadLibrary('libc.so.6')
  File "c:\python27\lib\ctypes\__init__.py", line 440, in LoadLi
    return self._dlltype(name)
  File "c:\python27\lib\ctypes\__init__.py", line 362, in __init
    self._handle = _dlopen(self._name, mode)
TypeError: LoadLibrary() argument 1 must be string, not unicode`

did i make mistake? Or is your?

**Comment by yan12125** [comment] 2017-01-03 16:22
Duplicate of #11540

> did i make mistake? Or is your?

Neither you nor we (youtube-dl maintainers) made the mistake. Instead, Python should be blamed: http://bugs.python.org/issue29082.

Conclusion: Python 2.7.13 is broken. Downgrade to 2.7.12 or use 3.x

**Closed by yan12125** 2017-01-03 16:22 UTC

**Comment by milo123milo** [comment] 2017-01-03 16:50
How can i install youtube-dl on python 3  i have both on pc? @yan12125

**Comment by yan12125** [comment] 2017-01-03 16:53
Python 2 and Python 3 can co-exists. Just install it like how you've installed Python 2.
