### ISSUE TITLE
Some youtube videos won't download.

### ISSUE THREAD

**Issue by onodera-punpun** [rg3/youtube-dl#6665] opened 2015-08-25 16:47 UTC
```
~ youtube-dl "https://www.youtube.com/watch?v=BVwAVbKYYeM" --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=BVwAVbKYYeM', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.23
[debug] Python version 2.7.10 - Linux-4.1.5-ck2-punpun-x86_64-AMD_Phenom-tm-_II_X4_955_Processor-with-glibc2.2.5
[debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] BVwAVbKYYeM: Downloading webpage
[youtube] BVwAVbKYYeM: Downloading video info webpage
[youtube] BVwAVbKYYeM: Extracting video information
[youtube] {22} signature length 40.43, html5 player new
[youtube] {43} signature length 40.43, html5 player new
[youtube] {18} signature length 40.43, html5 player new
[youtube] {5} signature length 40.43, html5 player new
[youtube] {36} signature length 40.43, html5 player new
[youtube] {17} signature length 40.43, html5 player new
[youtube] {13} signature length 40.43, html5 player new
[youtube] {137} signature length 40.43, html5 player new
[youtube] {248} signature length 40.43, html5 player new
[youtube] {136} signature length 40.43, html5 player new
[youtube] {247} signature length 40.43, html5 player new
[youtube] {135} signature length 40.43, html5 player new
[youtube] {244} signature length 40.43, html5 player new
[youtube] {134} signature length 40.43, html5 player new
[youtube] {243} signature length 40.43, html5 player new
[youtube] {133} signature length 40.43, html5 player new
[youtube] {242} signature length 40.43, html5 player new
[youtube] {160} signature length 40.43, html5 player new
[youtube] {140} signature length 40.43, html5 player new
[youtube] {171} signature length 40.43, html5 player new
[youtube] BVwAVbKYYeM: Downloading DASH manifest
WARNING: [youtube] BVwAVbKYYeM: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[debug] Invoking downloader on u'https://r1---sn-mn4vg5aa-5hns.googlevideo.com/videoplayback?source=youtube&mv=m&mt=1440521106&gcr=nl&ip=2001%3A980%3Ae682%3A1%3Ae074%3A32fa%3A5052%3Ad92a&mn=sn-mn4vg5aa-5hns&gir=yes&mm=31&id=o-AFyrVgvrN8ZIuQjDgtFCGFwI4n7sL5HIGN0ZqloAvd5j&initcwndbps=1916250&key=yt5&mime=video%2Fmp4&sparams=clen%2Cdur%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&expire=1440542797&fexp=9408240%2C9408710%2C9409069%2C9415365%2C9415485%2C9416023%2C9416126%2C9417707%2C9418153%2C9418449&keepalive=yes&lmt=1438077524764784&dur=256.673&itag=137&ms=au&sver=3&requiressl=yes&ipbits=0&upn=6rLt9VCtFXs&pl=35&clen=111184680&signature=A9AA30823A4F83A6B6B4329C76915597F7411009.5DFAA6F252F57BAD6FE8AAAAAD2D93E223A88CC4&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1579, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1527, in dl
    return fd.download(name, info)
  File "/usr/lib/python2.7/site-packages/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python2.7/site-packages/youtube_dl/downloader/http.py", line 60, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1860, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
```

**Comment by dstftw** [comment] 2015-08-25 16:48
Duplicate of #6451. Remove cache with `youtube-dl --rm-cache-dir`.

**Closed by dstftw** 2015-08-25 16:48 UTC

**Comment by onodera-punpun** [comment] 2015-08-25 16:49
@dstftw That did the trick, thanks for the fast response!
