### ISSUE TITLE
While updating to new version..File handle close hang

### ISSUE THREAD

**Issue by pargitejas** [rg3/youtube-dl#5994] opened 2015-06-16 06:03 UTC
![youtube-dl](https://cloud.githubusercontent.com/assets/9839912/8176732/144b7b8c-141b-11e5-88ff-f187ef74f9c7.PNG)

While updating..Youtube-dl..After downloading latest youtube-dl latest version
Message is displayed "Waiting for File handle to be closed" for the long period.
Closing the CMD and opening again works.

**Comment by yan12125** [comment] 2015-06-16 06:06
Does pressing ENTER again brings back the prompt?

**Comment by pargitejas** [comment] 2015-06-16 16:17
I don't know. I mean;I didn't try that. I hope you get "what I am saying." from the previous description. This does not compromise the functionality or anything by the way. Just a minor issue!

My English is exactly not the best.

**Comment by yan12125** [comment] 2015-06-17 11:59
I know the situation, and I guess it's the same problem as #5810. That means all the work is done while ```C:\Users\Tejas>``` does not appear again. If you will, try it on the next update.

**Comment by dstftw** [comment] 2015-06-17 13:43
Duplicate of #5810.

**Closed by dstftw** 2015-06-17 13:43 UTC
Labels: build/update
