### ISSUE TITLE
Another sound cloud issue unsolved?

### ISSUE THREAD

**Issue by NickWinston123** [rg3/youtube-dl#5277] opened 2015-03-24 19:43 UTC
Tried to download all of the song on someones sound cloud page but got this error again

ERROR: Unable to download webpage: <urlopen error [Errno 60] Operation timed out> (caused by URLError(error(60, 'Operation timed out'),))
nickmac$ cd /Users/Nick/Dropbox/LorDFuBu 
nickmac$ LorDFuBu noahstarr$ youtube-dl https://soundcloud.com/lordfubu
[soundcloud:user] lordfubu: Downloading user info
[soundcloud:user] lordfubu: Downloading track page 1
ERROR: Unable to download JSON metadata: HTTP Error 500: Internal Server Error (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

last time i did it with the  --verbose flag  no on responded.

**Comment by dstftw** [comment] 2015-03-25 14:18
Duplicate of #5248.

**Closed by dstftw** 2015-03-25 14:18 UTC
