### ISSUE TITLE
Cannot download Youku VIP videos with valid account

### ISSUE THREAD

**Issue by ztytian** [rg3/youtube-dl#12694] opened 2017-04-09 11:20 UTC
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

youtube-dl -u 18918154528 -v http://v.youku.com/v_show/id_XMjY4MDE4NjM5Mg==.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-v', u'http://v.youku.com/v_show/id_XMjY4MDE4NjM5Mg==.html']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.09
[debug] Python version 2.7.12 - Darwin-16.5.0-x86_64-i386-64bit
[debug] exe versions: avconv 12, avprobe 12, ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {}
[youku] XMjY4MDE4NjM5Mg: Downloading JSON metadata
[download] Downloading playlist: 第12话 胜利的使用方式
[youku] playlist 第12话 胜利的使用方式: Collected 11 video ids (downloading 11 of them)
[download] Downloading video 1 of 11
[debug] Invoking downloader on u'http://k.youku.com/player/getFlvPath/sid/049173559224012a1631d_00/st/flv/fileid/0300800B0058DE7432F92F011BA6A92F66A944-7F69-A68A-003A-B44B9BD0B719?ypp=0&myp=0&K=61f9c323f3c61671261f9d2e%26sign%3Dcf3c28d6abaa3915d3e8ee33c9249927&ctype=12&token=0504&ev=1&ep=ciadG06OU8sJ5yHbiD8bNi3kd3ZbXP4J9h%2BNgdIQALshQJzKnjrSxeu5TIlCF%2FhrAyR3GemHrdaWY0QQYfc1r2EQrkigSPrg%2FvOS5d9XwOIJFG02AMrWvVSeRjD1&hd=1&oip=3727199824'
[download] 第12话 胜利的使用方式-XMjY4MDE4NjM5Mg_part1.flv has already been downloaded
[download] 100% of 45.93MiB
[download] Downloading video 2 of 11
[debug] Invoking downloader on u'http://k.youku.com/player/getFlvPath/sid/049173559224012a1631d_00/st/flv/fileid/0300800B0158DE7432F92F011BA6A92F66A944-7F69-A68A-003A-B44B9BD0B719?ypp=0&myp=0&K=50480be2d405b5ff282c4274%26sign%3Dea722eb54ff65e1464fe300522dfa8cb&ctype=12&token=0504&ev=1&ep=ciadG06OU8sJ5yHbiD8bNi3kd3ZbXP4J9h%2BNgdIQALohQJzKnjrSxeu5TIlCF%2FhrAyR3GemHrdaWY0QQYfc1r2EQrkigSPrg%2FvOS5d9XwOIJFG02AMrWvVSeRjD1&hd=1&oip=3727199824'
[download] 第12话 胜利的使用方式-XMjY4MDE4NjM5Mg_part2.flv has already been downloaded
[download] 100% of 54.15MiB
[download] Downloading video 3 of 11
[debug] Invoking downloader on u'http://k.youku.com/player/getFlvPath/sid/049173559224012a1631d_00/st/flv/fileid/0300800B0258DE7432F92F011BA6A92F66A944-7F69-A68A-003A-B44B9BD0B719?ypp=0&myp=0&K=aedf3eb9afda058d261f9d2e%26sign%3D89251957ab679a5c5c3938ab492f5c54&ctype=12&token=0504&ev=1&ep=ciadG06OU8sJ5yHbiD8bNi3kd3ZbXP4J9h%2BNgdIQALkhQJzKnjrSxeu5TIlCF%2FhrAyR3GemHrdaWY0QQYfc1r2EQrkigSPrg%2FvOS5d9XwOIJFG02AMrWvVSeRjD1&hd=1&oip=3727199824'
[download] 第12话 胜利的使用方式-XMjY4MDE4NjM5Mg_part3.flv has already been downloaded
[download] 100% of 46.38MiB
[download] Downloading video 4 of 11
[debug] Invoking downloader on u'http://k.youku.com/player/getFlvPath/sid/049173559224012a1631d_00/st/flv/fileid/0300800B0358DE7432F92F011BA6A92F66A944-7F69-A68A-003A-B44B9BD0B719?ypp=0&myp=0&K=-1&ctype=12&token=0504&ev=1&ep=ciadG06OU8sJ5yHbiD8bNi3kd3ZbXP4J9h%2BNgdIQALghQJzKnjrSxeu5TIlCF%2FhrAyR3GemHrdaWY0QQYfc1r2EQrkigSPrg%2FvOS5d9XwOIJFG02AMrWvVSeRjD1&hd=1&oip=3727199824'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1797, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1739, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 356, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2100, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

### Description of your *issue*, suggested solution and other information
It appears that I cannot download part 4 of the video due to some 404 error. I have used the correct user credentials. You-get also fails so I suspect Youku did something to block downloading VIP videos.

**Comment by yan12125** [comment] 2017-04-09 13:53
Duplicate of #12694. VIP-only videos are not supported yet.

**Closed by yan12125** 2017-04-09 13:53 UTC
