### ISSUE TITLE
 An extractor error has occured. (caused by KeyError(u'id',));

### ISSUE THREAD

**Issue by alact** [rg3/youtube-dl#7184] opened 2015-10-15 13:12 UTC
youtube-dl -a list --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-a', u'list', u'--verbose']
[debug] Batch file urls: [u'http://8tracks.com/sxbvi/nowhere-in-particular#smart_id=tags:rock++alternative:safe', u'http://8tracks.com/corinneblu/here-s-to-the-rebels#smart_id=tags:rock++alternative:safe', u'http://8tracks.com/jeduardo-g/hauntingly-deep-beautiful-indie#smart_id=tags:rock++alternative:safe', u'http://8tracks.com/loisbang/i-m-cool#smart_id=tags:rock++alternative:safe', u'http://8tracks.com/stephmdlc/work-hard-do-your-own-thing-and-go-as-far-you-can', u'http://8tracks.com/shelbyhoff/get-pumped#smart_id=tags:work_out:safe', u'http://8tracks.com/alyssakschmidt/run-while-you-can', u'http://8tracks.com/poorcollegekid/get-it-together#smart_id=tags:work_out:safe', u'http://8tracks.com/emilybrock101/confidence-work-out-playlist#smart_id=tags:work_out:safe', u'http://8tracks.com/hoesaintloyal/work-out-jams#smart_id=tags:work_out:safe', u'http://8tracks.com/lettingthewaterfall/time-to-kick-ass#smart_id=tags:work_out:safe', u'http://8tracks.com/batansky/train-insane-or-remain-the-same-1#smart_id=tags:work_out:safe', u'http://8tracks.com/mayora_13/anime-is-epicness#smart_id=tags:work_out:safe']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.13
[debug] Python version 2.7.6 - Linux-3.19.0-30-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, rtmpdump 2.4
[debug] Proxy map: {}
[8tracks] nowhere-in-particular: Downloading webpage
[8tracks] nowhere-in-particular: Downloading song information 1/16
[8tracks] nowhere-in-particular: Downloading song information 2/16
[8tracks] nowhere-in-particular: Downloading song information 3/16
[8tracks] nowhere-in-particular: Downloading song information 4/16
[8tracks] nowhere-in-particular: Downloading song information 5/16
[8tracks] nowhere-in-particular: Waiting for 178.0 seconds
[8tracks] nowhere-in-particular: Downloading song information 5/16
[8tracks] nowhere-in-particular: Downloading song information 6/16
[8tracks] nowhere-in-particular: Waiting for 178.0 seconds
[8tracks] nowhere-in-particular: Downloading song information 6/16
[8tracks] nowhere-in-particular: Downloading song information 7/16
[8tracks] nowhere-in-particular: Waiting for 178.0 seconds
[8tracks] nowhere-in-particular: Downloading song information 7/16
[8tracks] nowhere-in-particular: Downloading song information 8/16
[8tracks] nowhere-in-particular: Waiting for 178.0 seconds
[8tracks] nowhere-in-particular: Downloading song information 8/16
[8tracks] nowhere-in-particular: Downloading song information 9/16
[8tracks] nowhere-in-particular: Waiting for 178.0 seconds
[8tracks] nowhere-in-particular: Downloading song information 9/16
[8tracks] nowhere-in-particular: Downloading song information 10/16
[8tracks] nowhere-in-particular: Waiting for 178.0 seconds
[8tracks] nowhere-in-particular: Downloading song information 10/16
[8tracks] nowhere-in-particular: Downloading song information 11/16
[8tracks] nowhere-in-particular: Waiting for 178.0 seconds
[8tracks] nowhere-in-particular: Downloading song information 11/16
[8tracks] nowhere-in-particular: Downloading song information 12/16
[8tracks] nowhere-in-particular: Waiting for 178.0 seconds
[8tracks] nowhere-in-particular: Downloading song information 12/16
[8tracks] nowhere-in-particular: Downloading song information 13/16
[8tracks] nowhere-in-particular: Waiting for 178.0 seconds
[8tracks] nowhere-in-particular: Downloading song information 13/16
[8tracks] nowhere-in-particular: Downloading song information 14/16
[8tracks] nowhere-in-particular: Waiting for 178.0 seconds
[8tracks] nowhere-in-particular: Downloading song information 14/16
[8tracks] nowhere-in-particular: Downloading song information 15/16
[8tracks] nowhere-in-particular: Waiting for 178.0 seconds
[8tracks] nowhere-in-particular: Downloading song information 15/16
ERROR: An extractor error has occured. (caused by KeyError(u'id',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/eighttracks.py", line 146, in _real_extract
    'id': compat_str(track_data['id']),
KeyError: u'id'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 296, in extract
    raise ExtractorError('An extractor error has occured.', cause=e)
ExtractorError: An extractor error has occured. (caused by KeyError(u'id',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by jaimeMF** [comment] 2015-10-15 13:42
Duplicate of #5900.

**Closed by jaimeMF** 2015-10-15 13:42 UTC
