### ISSUE TITLE
The soundcloud download doesn't work at all anymore

### ISSUE THREAD

**Issue by Alex1890** [rg3/youtube-dl#6999] opened 2015-09-27 13:47 UTC
[soundcloud] studio-jmpdnb/eazy-route-66: Resolving id
[soundcloud] studio-jmpdnb/eazy-route-66: Downloading info JSON
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Alex1890** [comment] 2015-09-27 13:49
./youtube-dl https://soundcloud.com/studio-jmpdnb/eazy-route-66

**Comment by epgfm** [comment] 2015-09-27 15:49
``` python
$ youtube-dl -v https://soundcloud.com/dashberlin/motorcycle-as-the-rush-comes
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://soundcloud.com/dashberlin/motorcycle-as-the-rush-comes']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.22
[debug] Python version 2.7.6 - Linux-3.13.0-63-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
[soundcloud] dashberlin/motorcycle-as-the-rush-comes: Resolving id
[soundcloud] dashberlin/motorcycle-as-the-rush-comes: Downloading info JSON
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 326, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1865, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

**Comment by NulByte** [comment] 2015-09-27 16:06
<code>
d:\workspace\youtube-dl -x --ignore-errors --audio-quality 0 --audio-format mp3 --add-metadata --metadata-from-title "%(artist)s - %(title)s" -o"D:\Downloaded-Music\%(title)s.%(ext)s" "https://soundcloud.com/qdance/crystal-nation-hosted-by-crystal-lake-episode-60" --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-x', u'--ignore-errors', u'--audio-quality', u'0', u'--audio-format', u'mp3', u'--add-metadata', u'--metadata-from-title', u'%(artist)s - %(title)s', u'-oD:\\Downloaded-Music\\%(title)s.%(ext)s', u'https://soundcloud.com/qdance/crystal-nation-hosted-by-crystal-lake-episode-60', u'--verbose']
[debug] Encodings: locale cp1255, fs mbcs, out cp862, pref cp1255
[debug] youtube-dl version 2015.09.22
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-75550-g23acb98, ffprobe N-75550-g23acb98
[debug] Proxy map: {}
[soundcloud] qdance/crystal-nation-hosted-by-crystal-lake-episode-60: Resolving id
[soundcloud] qdance/crystal-nation-hosted-by-crystal-lake-episode-60: Downloading info JSON
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "youtube_dl\extractor\common.pyo", line 326, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1865, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default
</code>

**Comment by Gwend4l** [comment] 2015-09-27 16:41
I confirm that it doesn't work anymore

**Comment by dstftw** [comment] 2015-09-27 17:41
Duplicate of #6930.
This is already fixed in master and will be incorporated in the next version of youtube-dl.

**Closed by dstftw** 2015-09-27 17:41 UTC
