### ISSUE TITLE
youtube-dl.2015.06.04.1: Youtube title with Cyrillic text does not work as expected

### ISSUE THREAD

**Issue by himadri0327** [rg3/youtube-dl#5982] opened 2015-06-14 17:46 UTC
Windows 7
Powershell 2.0

PS> youtube-dl --version
2015.06.04.1
PS> youtube-dl --get-title http://www.youtube.com/watch?v=bqLNdXS7YFU
TONI STORARO – Bravo / ТОНИ СТОРАРО – Браво
PS> $YTITLE=youtube-dl --get-title http://www.youtube.com/watch?v=bqLNdXS7YFU
PS> $YTITLE
TONI STORARO – Bravo /   –
PS U:\#MusicVidsYT-Euro\yt.FanTvBG,BG> youtube-dl -f22 -o "%(title)s.mp4" http://www.youtube.com/watch?v=bqLNdXS7YFU
[youtube] bqLNdXS7YFU: Downloading webpage
[youtube] bqLNdXS7YFU: Extracting video information
[youtube] bqLNdXS7YFU: Downloading DASH manifest
[download] Destination: TONI STORARO – Bravo _   – .mp4
[download] 100% of 78.89MiB in 00:23
PS U:\#MusicVidsYT-Euro\yt.FanTvBG,BG>
PS U:\#MusicVidsYT-Euro\yt.FanTvBG,BG> dir "TONI STORARO – Bravo*"
Mode                LastWriteTime     Length Name
-a---          06/14/15   1:38 PM   82717126 TONI STORARO – Bravo _   – .mp4

**Comment by dstftw** [comment] 2015-06-14 17:48
Duplicate of #5045.
This is intentional behavior for now. See #4787 for the rationale and #5527 for alternative solution discussions.

**Closed by dstftw** 2015-06-14 17:48 UTC
