### ISSUE TITLE
[Youku]ERROR: Youku server reported error -6004: 客户端无权播放,201;

### ISSUE THREAD

**Issue by sherkwast** [rg3/youtube-dl#14841] opened 2017-11-24 10:10 UTC
output
>youtube-dl http://v.youku.com/v_show/id_XODc4MjI0NzIw.html --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://v.youku.com/v_show/id_XODc4MjI0NzIw.html', '--verbose']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2017.11.15
[debug] Python version 3.4.4 - Windows-10-10.0.16299
[debug] exe versions: ffmpeg N-82597-gd316b21, ffprobe N-82597-gd316b21
[debug] Proxy map: {}
[youku] XODc4MjI0NzIw: Retrieving cna info
ERROR: Unable to download webpage: <urlopen error EOF occurred in violation of protocol (_ssl.c:600)> (caused by URLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:600)'),))
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\common.py", line 506, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\YoutubeDL.py", line 2196, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\utils.py", line 1086, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open

or 
>youtube-dl http://v.youku.com/v_show/id_XODc4MjI0NzIw.html --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://v.youku.com/v_show/id_XODc4MjI0NzIw.html', '--verbose']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2017.11.15
[debug] Python version 3.4.4 - Windows-10-10.0.16299
[debug] exe versions: ffmpeg N-82597-gd316b21, ffprobe N-82597-gd316b21
[debug] Proxy map: {}
[youku] XODc4MjI0NzIw: Retrieving cna info
ERROR: Unable to download webpage: '' (caused by BadStatusLine("''",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\common.py", line 506, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\YoutubeDL.py", line 2196, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\utils.py", line 1086, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1186, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1227, in getresponse
  File "C:\Python\Python34\lib\http\client.py", line 386, in begin
  File "C:\Python\Python34\lib\http\client.py", line 356, in _read_status

**Comment by yan12125** [comment] 2017-11-24 11:15
Duplicate of #14815. This will be fixed in the next version. Please wait patiently.

**Closed by yan12125** 2017-11-24 11:15 UTC
