### ISSUE TITLE
Unable to verify certificate

### ISSUE THREAD

**Issue by Probe1** [rg3/youtube-dl#7450] opened 2015-11-11 06:55 UTC
Nothing out of the ordinary, used yt-dl to grab https://www.youtube.com/watch?v=pWxJEIz7sSA and it kicked back that it could not verify the certificate.  Using latest build 11/10.

``` Downloading video...
ERROR: Unable to download webpage: (urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_sll.c:590 (caused by URLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),)) ```

**Comment by yan12125** [comment] 2015-11-11 07:14
Which operating system are you using? Windows XP, 7 or Linux, Mac OS X? Please post the full log from the following command:
```
youtube-dl --verbose "https://www.youtube.com/watch?v=pWxJEIz7sSA"
```

**Comment by Probe1** [comment] 2015-11-11 08:12
Windows 7 latest service pack.

```
Enter youtube url: youtube-dl --verbose https://www.youtube.com/watch?v=pWxJEIz7
sSA
Downloading video...
WARNING: The url doesn't specify the protocol, trying with http
WARNING: Could not send HEAD request to http://youtube-dl --verbose https://www.
youtube.com/watch?v=pWxJEIz7sSA: <urlopen error [Errno 11004] getaddrinfo failed
>
ERROR: Unable to download webpage: <urlopen error [Errno 11004] getaddrinfo fail
ed> (caused by URLError(gaierror(11004, 'getaddrinfo failed'),))

Couldn't download the youtube video. Did you copy the url correctly?
Press any key to continue . . .

```

**Comment by yan12125** [comment] 2015-11-11 11:50
Looks like you're using a wrapper but not youtube-dl itself. Could you run the command given above in Command Prompt (cmd.exe)?

**Comment by codaman** [comment] 2015-11-11 15:49
i'm using youtube-dl on .net web service it also get this error 

Traceback (most recent call last): File "__main__.py", line 19, in <module> File "youtube_dl\__init__.pyo", line 410, in main File "youtube_dl\__init__.pyo", line 377, in _real_main File "youtube_dl\YoutubeDL.pyo", line 338, in __init__ File "youtube_dl\YoutubeDL.pyo", line 1969, in _setup_opener File "youtube_dl\utils.pyo", line 492, in make_HTTPS_handler File "ssl.pyo", line 440, in create_default_context File "ssl.pyo", line 391, in load_default_certs File "ssl.pyo", line 378, in _load_windows_store_certs WindowsError: [Error 5] Access is denied

**Comment by bamcdougall** [comment] 2015-11-12 17:31
I have same issue.  Using latest build 11/10:
Downloading video... ERROR: Unable to download webpage: (urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_sll.c:590 (caused by URLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))

Using command line prompt, the following command is issued: 

youtube-dl -i --batch-file ./ImportChoons.txt --format "best" --extract-audio --audio-format "best" --audio-quality 0

where ImportChoons.txt is a file containing misc links to video clips on YouTube.
OS:  Windows 7 Professional, 64 bit, Service Pack 1

Only change from youtube-dl working and not working is upgrading youtube-dl to 11/10/2015 version

**Comment by dstftw** [comment] 2015-11-12 18:52
Duplicate of #7309.

**Closed by dstftw** 2015-11-12 18:52 UTC
