### ISSUE TITLE
Cannot download from redirector.googlevideo.com - FileNotFoundError

### ISSUE THREAD

**Issue by wanchihh** [rg3/youtube-dl#13450] opened 2017-06-21 08:55 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.18*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
> youtube-dl.exe -v "https://redirector.googlevideo.com/videoplayback?requiressl=yes&id=c1cc828315065c04&itag=5&source=blogger&app=blogger&cmo=secure_transport%3Dyes&cmo=sensitive_content%3Dyes&ip=0.0.0.0&ipbits=0&expire=1500166184&sparams=requiressl,id,itag,source,ip,ipbits,expire&signature=9536CF118D56B328CF347964541EF549132EB24A.35949507956A6C3E1EFC13C90311B14DCEE63C19&key=ck2"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://redirector.googlevideo.com/videoplayback?requiressl=yes&id=c1cc828315065c04&itag=5&source=blogger&app=blogger&cmo=secure_transport%3Dyes&cmo=sensitive_content%3Dyes&ip=0.0.0.0&ipbits=0&expire=1500166184&sparams=requiressl,id,itag,source,ip,ipbits,expire&signature=9536CF118D56B328CF347964541EF549132EB24A.35949507956A6C3E1EFC13C90311B14DCEE63C19&key=ck2']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.06.18
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-74113-gcdb0225, ffprobe N-74113-gcdb0225
[debug] Proxy map: {}
[generic] videoplayback?requiressl=yes&id=c1cc828315065c04&itag=5&source=blogger&app=blogger&cmo=secure_transport=yes&cmo=sensitive_content=yes&ip=0.0.0.0&ipbits=0&expire=1500166184&sparams=requiressl,id,itag,source,ip,ipbits,expire&signature=9536CF118D56B328CF347964541EF549132EB24A: Requesting header
[redirect] Following redirect to https://r2---sn-npoeen76.googlevideo.com/videoplayback?requiressl=yes&id=c1cc828315065c04&itag=5&source=blogger&app=blogger&ip=0.0.0.0&ipbits=0&expire=1500166184&sparams=expire,id,ip,ipbits,itag,mip,mm,mn,ms,mv,pl,requiressl,sc,source&signature=6AADCD47C491DFB982689B20B7510961BC6F3C0F.706F6135B8310714DEA0CB3DF6103D2838461345&key=cms1&cms_redirect=yes&mip=203.126.83.2&mm=30&mn=sn-npoeen76&ms=nxu&mt=1498034854&mv=m&pl=20&sc=yes
[generic] videoplayback?requiressl=yes&id=c1cc828315065c04&itag=5&source=blogger&app=blogger&ip=0.0.0.0&ipbits=0&expire=1500166184&sparams=expire,id,ip,ipbits,itag,mip,mm,mn,ms,mv,pl,requiressl,sc,source&signature=6AADCD47C491DFB982689B20B7510961BC6F3C0F.706F6135B8310714DEA0CB3DF6103D2838461345&key=cms1&cms_redirect=yes&mip=203.126.83: Requesting header
[debug] Invoking downloader on 'https://r2---sn-npoeen76.googlevideo.com/videoplayback?requiressl=yes&id=c1cc828315065c04&itag=5&source=blogger&app=blogger&ip=0.0.0.0&ipbits=0&expire=1500166184&sparams=expire,id,ip,ipbits,itag,mip,mm,mn,ms,mv,pl,requiressl,sc,source&signature=6AADCD47C491DFB982689B20B7510961BC6F3C0F.706F6135B8310714DEA0CB3DF6103D2838461345&key=cms1&cms_redirect=yes&mip=203.126.83.2&mm=30&mn=sn-npoeen76&ms=nxu&mt=1498034854&mv=m&pl=20&sc=yes'
ERROR: unable to open for writing: [Errno 2] No such file or directory: 'videoplayback-videoplaybackrequiressl=yes&id=c1cc828315065c04&itag=5&source=blogger&app=blogger&ip=0.0.0.0&ipbits=0&expire=1500166184&sparams=expire,id,ip,ipbits,itag,mip,mm,mn,ms,mv,pl,requiressl,sc,source&signature=6AADCD47C491DFB982689B20B7510961BC6F3C0F.706F6135B8310714DEA0CB3DF6103D2838461345&key=cms1&cms_redirect=yes&mip=203.126.83.unknown_video.part'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp_9wocfhk\build\youtube_dl\downloader\http.py", line 175, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp_9wocfhk\build\youtube_dl\utils.py", line 454, in sanitize_open
FileNotFoundError: [Errno 2] No such file or directory: 'videoplayback-videoplaybackrequiressl=yes&id=c1cc828315065c04&itag=5&source=blogger&app=blogger&ip=0.0.0.0&ipbits=0&expire=1500166184&sparams=expire,id,ip,ipbits,itag,mip,mm,mn,ms,mv,pl,requiressl,sc,source&signature=6AADCD47C491DFB982689B20B7510961BC6F3C0F.706F6135B8310714DEA0CB3DF6103D2838461345&key=cms1&cms_redirect=yes&mip=203.126.83.unknown_video.part'
```

---

### Description of your *issue*, suggested solution and other information

Hi, 

When I tried youtube-dl on the following url:
[https://redirector.googlevideo.com/videoplayback?requiressl=yes&id=c1cc828315065c04&itag=5&source=blogger&app=blogger&cmo=secure_transport%3Dyes&cmo=sensitive_content%3Dyes&ip=0.0.0.0&ipbits=0&expire=1500166184&sparams=requiressl,id,itag,source,ip,ipbits,expire&signature=9536CF118D56B328CF347964541EF549132EB24A.35949507956A6C3E1EFC13C90311B14DCEE63C19&key=ck2](https://redirector.googlevideo.com/videoplayback?requiressl=yes&id=c1cc828315065c04&itag=5&source=blogger&app=blogger&cmo=secure_transport%3Dyes&cmo=sensitive_content%3Dyes&ip=0.0.0.0&ipbits=0&expire=1500166184&sparams=requiressl,id,itag,source,ip,ipbits,expire&signature=9536CF118D56B328CF347964541EF549132EB24A.35949507956A6C3E1EFC13C90311B14DCEE63C19&key=ck2)
I get the error FileNotFoundError: [Errno 2] No such file or directory.

However if I go to the url from a web browser, the video will start downloading. 

Thanks.

**Comment by yan12125** [comment] 2017-06-21 13:17
Duplicate of #5921. Currently youtube-dl fails to handle very long file names.

**Closed by yan12125** 2017-06-21 13:17 UTC
