### ISSUE TITLE
HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by Misteralex007** [rg3/youtube-dl#9238] opened 2016-04-18 19:50 UTC
Hi !

So like you saw in title, i have a problem with youtube-dl i did the update and it's the same problem:
![concours](http://puu.sh/onc6q/7e7ef5b4ba.png)

And i used by VPS like a VPS, i have no problem to go on Youtube.
So why i get this error, i mean i'm the only one, i saw some issue about it, but no good answer.

Thanks,
Regards,
Misteralex007

**Comment by dstftw** [comment] 2016-04-18 19:52
Duplicate of #5138. You may want to read [FAQ entry on the issue](https://github.com/rg3/youtube-dl#http-error-429-too-many-requests-or-402-payment-required) and [this discussion](https://github.com/rg3/youtube-dl/issues/5138).

**Closed by dstftw** 2016-04-18 19:52 UTC
