### ISSUE TITLE
[Udemy] Not working on version 4 of udemy players

### ISSUE THREAD

**Issue by quanhua92** [rg3/youtube-dl#8866] opened 2016-03-15 15:07 UTC
youtube-dl stops working on the new version of udemy player. The course with the /v4/ causes this issue. For example:
https://www.udemy.com/web-hosting-101/learn/v4/

**Comment by dstftw** [comment] 2016-03-15 15:27
Duplicate of #8753.

**Closed by dstftw** 2016-03-15 15:27 UTC
