### ISSUE TITLE
vk.com

### ISSUE THREAD

**Issue by failuz** [rg3/youtube-dl#3298] opened 2014-07-20 00:03 UTC
youtube-dl --username 998909991736 --password ********************\* http://vk.com/video177220578_167400422  --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--username', '<PRIVATE>', '--password', '<PRIVATE>', 'http://vk.com/video177220578_167400422', '--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.07.15
[debug] Python version 2.6.6 - Linux-2.6.32-431.17.1.el6.x86_64-x86_64-with-centos-6.5-Final
[debug] Proxy map: {}
[vk.com] Logging in as 998909991736
[vk.com] 177220578_167400422: Downloading webpage
ERROR: Unable to extract vars; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 168, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vk.py", line 159, in _real_extract
    data_json = self._search_regex(r'var vars = ({.*?});', info_page, 'vars')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 384, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract vars; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by tpimh** [comment] 2015-06-12 19:12
I'm having this issue too. I use my email as username. Doesn't work with `.netrc` also.

**Comment by dstftw** [comment] 2015-06-12 19:14
Can you run it with `--write-pages` and post *.dump files?

**Comment by tpimh** [comment] 2015-06-12 19:24
None_https_-_login.vk.com_act=login.dump
```
<script type="text/javascript">
var _ua = navigator.userAgent;
var locDomain = 'vk.com'.match(/[a-zA-Z]+\.[a-zA-Z]+\.?$/)[0];
if (/opera/i.test(_ua) || !/msie 6/i.test(_ua) || document.domain != locDomain) {
  document.domain = locDomain;
}
parent.__qlClear();
parent.onLoginFailed(-1);
</script>
```

**Comment by dstftw** [comment] 2015-06-12 19:27
Looks like you specified wrong email/password.

**Comment by tpimh** [comment] 2015-06-12 19:28
I can login in a browser if I just copy and paste it from my `.netrc`, it is should be correct.

**Comment by dstftw** [comment] 2015-06-12 19:31
Pass it with `-u` and `-p` and post the [verbose log](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs) (credentials will be automatically removed).

**Comment by tpimh** [comment] 2015-06-12 19:34
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-v', u'-g', u'https://vk.com/video30144143_168209143']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.8
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: Unable to login, incorrect username and/or password
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 272, in extract
    self.initialize()
  File "./youtube-dl/youtube_dl/extractor/common.py", line 266, in initialize
    self._real_initialize()
  File "./youtube-dl/youtube_dl/extractor/vk.py", line 134, in _real_initialize
    self._login()
  File "./youtube-dl/youtube_dl/extractor/vk.py", line 131, in _login
    raise ExtractorError('Unable to login, incorrect username and/or password', expected=True)
ExtractorError: Unable to login, incorrect username and/or password

```

**Comment by dstftw** [comment] 2015-06-12 19:36
Have you enclosed both email and password in 'single quotes'?

**Comment by tpimh** [comment] 2015-06-12 19:39
Yes.

**Comment by tpimh** [comment] 2015-06-12 19:40
This is my command line: `./youtube-dl -u 'my@email' -p 'password' -v -g 'https://vk.com/video30144143_168209143'`

**Comment by dstftw** [comment] 2015-06-12 19:41
If you add `--write-pages` to your command line, does `None_https_-_login.vk.com_act=login.dump` is the same as before?

**Comment by tpimh** [comment] 2015-06-12 19:43
Yes, the file is created and it's contents are the same.

**Comment by dstftw** [comment] 2015-06-12 19:46
That's stange. Does it work if you use phone number instead email?

**Comment by tpimh** [comment] 2015-06-12 20:01
No, the error message is the same.

**Comment by dstftw** [comment] 2015-06-12 21:12
Does your password contain non-ASCII? I've managed to reproduce this with non-ASCII password and fixed in 4f3bf679f5a764f7a26d3c45c82be43e34a3cc4d.

**Comment by tpimh** [comment] 2015-06-12 22:02
No, my password only contains ASCII (latin lowercase, latin uppercase, numbers, punctuation). Maybe the problem is with characters like `*` and `&`? Maybe I should HTML-encode them?

**Comment by dstftw** [comment] 2015-06-12 22:03
Single quotes should be enough for that.

**Comment by dstftw** [comment] 2015-06-12 22:07
Are you sure you've pulled the latest repo version?

**Comment by tpimh** [comment] 2015-06-13 07:52
Yes, I just pulled it from github.

**Comment by mpenkov** [comment] 2018-08-02 04:35
@tpimh Just checking up on this issue. It's been a while. Are you still experiencing the problem?

**Comment by tpimh** [comment] 2018-08-05 19:46
I just tested version 2018.06.19 and it worked fine.

**Comment by mpenkov** [comment] 2018-08-05 23:02
Ok, we can close this, then.

**Closed** 2018-08-07 06:09 UTC
