### ISSUE TITLE
WARNING: [youtube] 7zbP-sRZZUQ: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)

### ISSUE THREAD

**Issue by Elite** [rg3/youtube-dl#6489] opened 2015-08-07 10:25 UTC
```
[debug] User config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.youtube.com/watch?v=7zbP-sRZZUQ']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.06.1
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.8
[debug] exe versions: ffmpeg N-72000-g876c89a, ffprobe N-72000-g876c89a
[debug] Proxy map: {}
[youtube] 7zbP-sRZZUQ: Downloading webpage
[youtube] 7zbP-sRZZUQ: Downloading video info webpage
[youtube] 7zbP-sRZZUQ: Extracting video information
[youtube] {43} signature length 40.43, html5 player new
[youtube] {18} signature length 40.43, html5 player new
[youtube] {5} signature length 40.43, html5 player new
[youtube] {36} signature length 40.43, html5 player new
[youtube] {17} signature length 40.43, html5 player new
[youtube] {135} signature length 40.43, html5 player new
[youtube] {244} signature length 40.43, html5 player new
[youtube] {134} signature length 40.43, html5 player new
[youtube] {243} signature length 40.43, html5 player new
[youtube] {133} signature length 40.43, html5 player new
[youtube] {242} signature length 40.43, html5 player new
[youtube] {160} signature length 40.43, html5 player new
[youtube] {140} signature length 40.43, html5 player new
[youtube] {171} signature length 40.43, html5 player new
[youtube] 7zbP-sRZZUQ: Downloading DASH manifest
WARNING: [youtube] 7zbP-sRZZUQ: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[info] Available formats for 7zbP-sRZZUQ:
format code  extension  resolution note
171          webm       audio only DASH audio , audio@128k
140          m4a        audio only DASH audio , m4a_dash container, aac  @128k
160          mp4        144p       DASH video , video only
242          webm       240p       DASH video , video only
133          mp4        240p       DASH video , video only
243          webm       360p       DASH video , video only
134          mp4        360p       DASH video , video only
244          webm       480p       DASH video , video only
135          mp4        480p       DASH video , video only
17           3gp        176x144
36           3gp        320x240
5            flv        400x240
43           webm       640x360
18           mp4        640x360    (best)
^C
[1]+  Done                    youtube-dl -v -F https://www.youtube.com/watch?v=7zbP-sRZZUQ

```

**Comment by dstftw** [comment] 2015-08-07 12:55
Duplicate of #6451. Remove cache with `--rm-cache-dir`.

**Closed by dstftw** 2015-08-07 12:55 UTC
