### ISSUE TITLE
Nicovideo - Unable to extract thumbPlayKey;

### ISSUE THREAD

**Issue by IrealiTY** [rg3/youtube-dl#11391] opened 2016-12-08 13:33 UTC
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
C:\Users\aleks\Downloads>youtube-dl.exe -v http://www.nicovideo.jp/watch/sm5473120
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.nicovideo.jp/watch/sm5473120']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.12.01
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[niconico] sm5473120: Downloading webpage
[niconico] sm5473120: Downloading video info page
[niconico] sm5473120: Downloading webpage
ERROR: Unable to extract thumbPlayKey; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6j6yd3lp\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6j6yd3lp\build\youtube_dl\extractor\common.py", line 357, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6j6yd3lp\build\youtube_dl\extractor\niconico.py", line 141, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6j6yd3lp\build\youtube_dl\extractor\common.py", line 660, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract thumbPlayKey; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

- Single video: http://www.nicovideo.jp/watch/sm5473120

---

### Description of your *issue*, suggested solution and other information

I'm not sure if the listed support on the website for:

- niconico: ニコニコ動画
- NiconicoPlaylist

is also accounting for NicoVideo as it seems they rebranded / changed how the service works.

**Comment by dstftw** [comment] 2016-12-08 17:22
Duplicate of #11170.

**Closed by dstftw** 2016-12-08 17:22 UTC
