### ISSUE TITLE
Can not use aria2c when download from Udemy

### ISSUE THREAD

**Issue by pseudor** [rg3/youtube-dl#11367] opened 2016-12-05 08:39 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -u username -p password --playlist-start 97 --playlist-end 193 -o "%(autonumber)s-%(id)s-%(title)s.%(ext)s" --external-downloader aria2c https://www.udemy.com/unrealcourse/learn/v4/content -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '--playlist-start', '97', '--playlist-end', '193', '-o', '%(autonumber)s-%(id)s-%(title)s.%(ext)s', '--external-downloader', 'aria2c.exe', 'https://www.udemy.com/unrealcourse/learn/v4/content', '-v']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2016.12.01
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] Logging in as username
[udemy:course] unrealcourse: Downloading webpage
[udemy:course] 657932: Downloading course curriculum
[download] Downloading playlist: The Unreal Engine Developer Course - Learn C++ & Make Games
[udemy:course] playlist The Unreal Engine Developer Course - Learn C++ & Make Games: Collected 260 video ids (downloading 97 of them)
[download] Downloading video 1 of 97
[udemy] Downloading login popup
[udemy] 4843694: Downloading webpage
[udemy] 4843694: Downloading lecture JSON
[udemy] 5646414: Downloading m3u8 information
[udemy] 5646414: Downloading m3u8 information
[debug] Invoking downloader on 'https://udemy-adaptive-streaming-prod.udemy.com/657932/5646414/2016-03-29_15-12-32-00773dc37737c52cf5dee18508719bcf/hls/hls_1080_4300/39f497c5cdce0b05291b66afcccb960a.m3u8?mign=EEsRFRMGbBcROQZJCUwANQk2ER0aAVUGGz1BRxEaByxJU01KRlgDT0oqDB5BHRYfAg1eRkJdBFpbe09JUh0AJR82FRhWUgZVXH9XWgdCUTUYDA4jHQwRWVp%2BU14EXkdyR0sbGRo3RwoFLEFRAlpLcFJbSklCW04%3D'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 107
[download] Destination: 00001-5646414-Setting Up a GitHub “Repo”.mp4
[download]   2.0% of ~299.83MiB at 36.51KiB/s ETA 14:37
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

I have add the path of youtube-dl and aria2c to the System Environment Variables. But when I download some video from Udemy, the aria2c does not work.

**Comment by yan12125** [comment] 2016-12-05 08:48
Duplicate of #6069. In youtube-dl, m3u8 and aria2c are not compatible yet.

**Closed by yan12125** 2016-12-05 08:48 UTC
