### ISSUE TITLE
Fix support for tape.tv

### ISSUE THREAD

**Issue by jakobjw** [rg3/youtube-dl#10074] opened 2016-07-12 21:21 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.07.11*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.11**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v  https://www.tape.tv/make-the-girl-dance/videos/baby-baby-baby
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.tape.tv/make-the-girl-dance/videos/baby-baby-baby']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.11
[debug] Python version 2.7.10 - Darwin-15.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.0.2, ffprobe 3.0.2
[debug] Proxy map: {}
[generic] baby-baby-baby: Requesting header
WARNING: Falling back on generic information extractor.
[generic] baby-baby-baby: Downloading webpage
[generic] baby-baby-baby: Extracting information
[generic] embed?referrer=twitter: Requesting header
WARNING: Falling back on generic information extractor.
[generic] embed?referrer=twitter: Downloading webpage
[generic] embed?referrer=twitter: Extracting information
[generic] embed?referrer=twitter: Requesting header
WARNING: Falling back on generic information extractor.
[generic] embed?referrer=twitter: Downloading webpage
[generic] embed?referrer=twitter: Extracting information
[generic] embed?referrer=twitter: Requesting header
WARNING: Falling back on generic information extractor.
[generic] embed?referrer=twitter: Downloading webpage
[generic] embed?referrer=twitter: Extracting information
[generic] embed?referrer=twitter: Requesting header
WARNING: Falling back on generic information extractor.
[generic] embed?referrer=twitter: Downloading webpage
[generic] embed?referrer=twitter: Extracting information
[generic] embed?referrer=twitter: Requesting header
WARNING: Falling back on generic information extractor.
[generic] embed?referrer=twitter: Downloading webpage
[generic] embed?referrer=twitter: Extracting information
[generic] embed?referrer=twitter: Requesting header
WARNING: Falling back on generic information extractor.
[generic] embed?referrer=twitter: Downloading webpage
[generic] embed?referrer=twitter: Extracting information
[generic] embed?referrer=twitter: Requesting header
WARNING: Falling back on generic information extractor.
[generic] embed?referrer=twitter: Downloading webpage
[generic] embed?referrer=twitter: Extracting information
[generic] embed?referrer=twitter: Requesting header
WARNING: Falling back on generic information extractor.
[generic] embed?referrer=twitter: Downloading webpage
^C
ERROR: Interrupted by user
<end of log>
```

---

This seems like a deadlock loop after following a wrong url (twitter).
By the way, tape.tv is missing in the list of the supported sites atm, but according to https://github.com/rg3/youtube-dl/issues/3964 it was supported in the past.

**Comment by dstftw** [comment] 2016-07-13 15:08
Duplicate of #3964.

**Closed by dstftw** 2016-07-13 15:08 UTC
