### ISSUE TITLE
Support for extractor "Channel 4"

### ISSUE THREAD

**Issue by Pat38** [rg3/youtube-dl#6355] opened 2015-07-25 07:39 UTC
Hi everybody,

When I try to download this show : 

youtube-dl --all-subs http://www.channel4.com/programmes/dispatches/on-demand/59665-005

the program returns this error : 
[generic] 59665-005: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 59665-005: Downloading webpage
[generic] 59665-005: Extracting information
ERROR: Unsupported URL: http://www.channel4.com/programmes/dispatches/on-demand/59665-005

Do you plan to add "Channel 4" support to the list of extractors ?

Thank you in advance for your answer,
Yours faithfully
Patrick.

**Comment by dstftw** [comment] 2015-07-25 09:32
Duplicate of #2050.

**Closed by dstftw** 2015-07-25 09:32 UTC
