### ISSUE TITLE
www.tf1.fr : FFmpeg conversion failed

### ISSUE THREAD

**Issue by ericzutter** [rg3/youtube-dl#11348] opened 2016-12-02 23:02 UTC
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.01**
- [X ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X ] Bug report (encountered problems with youtube-dl)

```
C:\>youtube-dl.exe -v http://www.tf1.fr/tf1/bienvenue-chez-nous/videos/bienvenue-chez-29-novembre-2016-marie-helene-rene.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.tf1.fr/tf1/bienvenue-chez-nous/videos/bienvenue-chez-29-novembre-2016-marie-helene-rene.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp65001, pref cp1252
[debug] youtube-dl version 2016.12.01
[debug] Python version 3.4.4 - Windows-7-6.1.7600-SP0
[debug] exe versions: ffmpeg N-81741-g1212e34
[debug] Proxy map: {}
[TF1] bienvenue-chez-29-novembre-2016-marie-helene-rene: Downloading webpage
[wat.tv] 13273518: Downloading JSON metadata
[wat.tv] 13273518: Downloading JSON metadata
[wat.tv] 13273518: Downloading m3u8 information
[wat.tv] 13273518: Downloading f4m manifest
[wat.tv] 13273518: Extracting http url
[wat.tv] 13273518: Checking http-280 URL
[wat.tv] 13273518: Checking http-492 URL
[wat.tv] 13273518: Checking http-704 URL
[wat.tv] 13273518: Checking http-1340 URL
[wat.tv] 13273518: Checking http-1976 URL
[wat.tv] 13273518: Checking http-2718 URL
[wat.tv] 13273518: Downloading MPD manifest
[debug] Invoking downloader on 'http://das.q1.tf1.fr/2/USP-0x0/35/18/13273518/ssm/13273518.ism/dash/'
[dashsegments] Total fragments: 1448
[download] Destination: Bienvenue chez nous du 29 novembre 2016 - Marie-Hélène et René (1_3)-13273518.fdash-video=2500071.mp4
[download] 100% of 865.53MiB in 09:29
[debug] Invoking downloader on 'http://ios.q1.tf1.fr/2/USP-0x0/35/18/13273518/ssm/13273518.ism/13273518-audio=64000.m3u8?vk=MTMyNzM1MTgubTN1OA==&st=sXD1vLSxJJo_CbvN_b3qiA&e=1480728469&t=1480717669&'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 362
[download] Destination: Bienvenue chez nous du 29 novembre 2016 - Marie-Hélène et René (1_3)-13273518.fhls-68.mp4
[download] 100% of 25.02MiB in 00:53
[ffmpeg] Merging formats into "Bienvenue chez nous du 29 novembre 2016 - Marie-Hélène et René (1_3)-13273518.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:Bienvenue chez nous du 29 novembre 2016 - Marie-Hélène et René (1_3)-13273518.fdash-video=2500071.mp4' -i 'file:Bienvenue chez nous du 29 novembre 2016 - Marie-Hélène et René (1_3)-13273518.fhls-68.mp4' -c copy -map 0:v:0 -map 1:a:0 'file:Bienvenue chez nous du 29 novembre 2016 - Marie-Hélène et René (1_3)-13273518.temp.mp4'
ERROR: Conversion failed!
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6j6yd3lp\build\youtube_dl\YoutubeDL.py", line 1837, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6j6yd3lp\build\youtube_dl\postprocessor\ffmpeg.py", line 444, in run
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6j6yd3lp\build\youtube_dl\postprocessor\ffmpeg.py", line 192, in run_ffmpeg_multiple_files
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!
```

---

### Description of your *issue*, suggested solution and other information
All videos downloaded from TF1 website give error "FFmpeg conversion failed". The video and audio is downloaded correctly but the FFMPEG command that merges video and audio together doesn't work.

Adding the parameter "-bsf:a aac_adtstoasc" to ffmpeg merge command solves the issue.

If after receiving "conversion error" I execute the follow command in Windows 7 then the merge happens correctly.
```
ffmpeg -y -i "file:Bienvenue chez nous du 29 novembre 2016 - Marie-Hélène et René (1_3)-13273518.fdash-video=2500071.mp4" -i "file:Bienvenue chez nous du 29 novembre 2016 - Marie-Hélène et René (1_3)-13273518.fhls-68.mp4" -c copy -map 0:v:0 -map 1:a:0  -bsf:a aac_adtstoasc "file:Bienvenue chez nous du 29 novembre 2016 - Marie-Hélène et René (1_3)-13273518.temp.mp4"
```

**Comment by yan12125** [comment] 2016-12-03 03:41
Duplicate of #9913

**Closed by yan12125** 2016-12-03 03:41 UTC

**Comment by ymollard** [comment] 2017-03-12 00:16
The quick fix for people looking for a workaround:
```
youtube-dl --postprocessor-args "-bsf:a aac_adtstoasc" <URL>
```

**Comment by jmpp** [comment] 2020-05-23 14:25
@ymollard That fixed the problem. Thank you very much!
Any explanation on what that preprocessor is doing under the hoods? I'm not very comfortable with media encoding, but I like to understand what's going on :)

**Comment by ymollard** [comment] 2020-05-24 23:09
Sorry @jmpp I must admit I forgot all about this issue.
I'd say executing the ffmpeg commands separately in verbose mode gives more information to identify the reason of failure.

**Comment by jmpp** [comment] 2020-05-25 11:19
@ymollard I meant about the signification of the `-bsf:a aac_adtstoasc` , but I've found some information about it here: https://ffmpeg.org/ffmpeg-bitstream-filters.html#aac_005fadtstoasc
`-bsf` means "bitstream filter" and the filter name `aac_adtstoasc` will convert an AAC MPEG-2 stream to a MPEG-4 stream (as I understood).
