### ISSUE TITLE
mp4 files double length or won't play in QuickTime Player/iTunes?

### ISSUE THREAD

**Issue by genericptr** [rg3/youtube-dl#5048] opened 2015-02-24 09:04 UTC
When I try to download audio using mp4 formats (mp3 is never presented in -F) the audio length is 2x what the original is resulting in no volume empty space at the end of the track or total failure to play. I'm using a Mac and usually opening the files in QuickTime Player or iTunes (where the file won't play at all) when I see the problem but in VLC this doesn't happen. Is this a bug that needs fixing or should I try another utility to convert it to mp3 perhaps? Thanks.

**Comment by phihag** [comment] 2015-02-24 09:42
Sorry, I don't understand what you are doing in the first place. Where are you downloading the videos from? How do you "download audio using mp4 formats"?

Note that mp3 can be present, it just depends on the service you're using. For instance:
```
$ youtube-dl -F http://www.audiomack.com/song/roosh-williams/extraordinary
[audiomack] roosh-williams/extraordinary: Downloading JSON metadata
[info] Available formats for 310086:
format code  extension  resolution note
0            mp3        unknown
```

So please elaborate on what you are doing. Don't forget to review or [issue reporting guidelines](https://github.com/rg3/youtube-dl/blob/master/CONTRIBUTING.md). In particular, the output when called with `-v` should answer many of the above questions.

**Comment by genericptr** [comment] 2015-02-24 09:49
Sorry I mistyped I meant m4a. I'm downloading from YouTube using -f 141 for example (141         m4a       audio only  DASH audio  256k , m4a_dash container, aac  @256k (44100Hz), 22.38MiB) and haven't seem mp3 yet. I'm curious if it's a bug on your end or Apple's software is not compliment with the standard and I should be converting it.

**Comment by phihag** [comment] 2015-02-24 09:58
YouTube does not natively serve mp3. You can simply pass in `-x --audio-format mp3` to let youtube-dl handle the conversion to mp3.

**Comment by genericptr** [comment] 2015-02-24 10:20
Ok, I'll just ignore the problem then and try mp3. I'm looking for ffprobe now and I think it changed it's name to ffmpeg. Is that correct? If so maybe I just need to change the name and install to /usr/bin? Thanks.

**Comment by phihag** [comment] 2015-02-24 10:33
I still don't understand your problem in the first place, and since you are refusing to post the requested output of youtube-dl when called with `-v` I'm afraid I cannot really help you.

Note that YouTube's m4as are not playable by a large number of players. youtube-dl should auto-correct this when ffmpeg is installed, and warn otherwise.

ffprobe is a binary in the ffmpeg package. You can download the ffmpeg package at https://www.ffmpeg.org/download.html#build-mac .

Without the requested information (the output when called with `-v`) about the problem, I'm afraid we cannot help you. I am therefore closing this issue. Feel free to provide the output and we will reopen it. Thanks!

**Comment by genericptr** [comment] 2015-02-24 10:46
Sorry I didn't post the output because it's a question about the specific format and how youtube-dl generated it internally, not that there was an error. You answered the question already though which is m4a is probably just a shaky format to use and I should convert it. Not sure where you want ffmpeg installed to but I do some research. Thanks.

**Comment by phihag** [comment] 2015-02-24 10:49
ffmpeg can go anywhere in your [PATH](https://en.wikipedia.org/wiki/PATH_(variable)). If you are installing it by hand instead of with a package manager or installer, `/usr/local/bin` is the preferred path to install to. If you want you can use an alternate location though, just specify [`--ffmpeg-location`](https://github.com/rg3/youtube-dl/blob/master/README.md#post-processing-options) either on the command line or [your configuration file](https://github.com/rg3/youtube-dl/blob/master/README.md#configuration).

**Comment by genericptr** [comment] 2015-02-24 11:48
Thanks for your support but I'm still having problems. Installed ffmpeg to correct location but I can't get youtube-dl to locate it using 2 methods (below). The option --ffmpeg-location is not appearing in youtube-dl -h either.

MacBooks-MacBook-2:~ ryanjoseph$ /usr/local/bin/ffmpeg
ffmpeg version 2.5.3-tessus Copyright (c) 2000-2015 the FFmpeg developers

MacBooks-MacBook-2:~ ryanjoseph$ youtube-dl -v -f 141 -x --audio-format mp3 --ffmpeg-location /usr/local/bin/ffmpeg https://www.youtube.com/watch?v=DShCO4lrnFU
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: no such option: --ffmpeg-location


MacBooks-MacBook-2:~ ryanjoseph$ youtube-dl -v -f 141 -x --audio-format mp3 https://www.youtube.com/watch?v=DShCO4lrnFU
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '-f', '141', '-x', '--audio-format', 'mp3', 'https://www.youtube.com/watch?v=DShCO4lrnFU']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.10.5
[debug] Python version 2.7.6 - Darwin-14.1.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.5.3-tessus
[debug] Proxy map: {}
[youtube] DShCO4lrnFU: Downloading webpage
[youtube] DShCO4lrnFU: Extracting video information
[youtube] DShCO4lrnFU: Downloading DASH manifest
[debug] Invoking downloader on 'https://r3---sn-w5nuxa-jomz.googlevideo.com/videoplayback?id=0d28423b896b9c55&itag=141&source=youtube&requiressl=yes&mm=31&mv=m&ms=au&pl=24&ratebypass=yes&mime=audio/mp4&gir=yes&clen=9651238&lmt=1424402263092566&dur=302.695&key=dg_yt0&fexp=905657,907263,916636,916930,927622,931359,934954,9405958,9406486,943917,945093,947225,947240,948124,952302,952605,952612,952901,953918,955301,957201,957906,959701&upn=i2kr-pXloug&mt=1424778054&sver=3&signature=02EDAE521F0308A5551F7C08917143A35EF1BD7A.786559B0380F55B201C760C5BEE1BC37ADF77812&ip=171.4.249.10&ipbits=0&expire=1424799704&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mv,ms,pl,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Q_bert's Qubes (Atari 2600) game review by Mike Matei-DShCO4lrnFU.m4a
[download] 100% of 9.20MiB in 00:41
[ffmpeg] Correcting container in "Q_bert's Qubes (Atari 2600) game review by Mike Matei-DShCO4lrnFU.m4a"
[debug] ffmpeg command line: ffmpeg -y -i 'Q_bert'"'"'s Qubes (Atari 2600) game review by Mike Matei-DShCO4lrnFU.m4a' -c copy -f mp4 'Q_bert'"'"'s Qubes (Atari 2600) game review by Mike Matei-DShCO4lrnFU.temp.m4a'
ERROR: ffprobe or avprobe not found. Please install one.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1425, in post_process
    keep_video_wish, info = pp.run(info)
  File "/usr/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 165, in run
    filecodec = self.get_audio_codec(path)
  File "/usr/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 131, in get_audio_codec
    raise PostProcessingError('ffprobe or avprobe not found. Please install one.')
PostProcessingError

**Comment by phihag** [comment] 2015-02-24 12:14
youtube-dl needs ffmpeg **and** ffprobe, both of which come in one package.

Additionally, your version of youtube-dl is out of date, and that's why `--ffmpeg-location` won't work (although it should not be necessary at all). See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Closed by phihag** 2015-02-24 12:14 UTC

**Comment by genericptr** [comment] 2015-02-26 01:20
Thanks for all your support, I got it working now by installing the package from brew. However, for the record I found out my iTunes can indeed play m4a files without errors so there must be an error in the way youtube-dl generated the file which results in the extra space I was talking about (this didn't affect the file in VLC though). Probably not worth digging into since it's a fringe format but I wanted to let you know anyways. Thanks again.

**Comment by phihag** [comment] 2015-02-26 01:52
youtube-dl just transmits the file as YouTube renders it - we can reproduce the behavior just fine when using an external downloader. iTunes supports normal m4a files, but not the specific format generated by YouTube.

**Comment by muchbetterbig** [comment] 2015-03-17 09:44
In order to solve MP4 won't play in QuickTime issue, we had better convert QuickTime unplayable MP4 to QuickTime supported format.

iDealshare VideoGo is just the ideal MP4 to QuickTime Converter which can convert all kinds of MP4 files encoded with whatever video or audio codecs to QuickTime more compatible MOV or MP4 on Mac or Windows.

This wonderful MP4 to QuickTime Converter also can convert other video formats to QuickTime format to successfully play AVI, WMV, MKV, VOB, FLV, MPG, RMVB, MOV, 3GP and etc in QuickTime. It even helps to convert audio to play FLAC, OGG, WMA, APE, DTS, AU, RA, 3GA and more in QuickTime.

Step by step guide at http://www.idealshare.net/mp4-quicktime-solution.html

**Comment by aimkeepachieve** [comment] 2015-05-29 08:27
According to Apple Support Website, QuickTime can only support MPEG-4 (.mp4, .m4v), but MP4 is a complex video container with various video and audio codecs. That's why sometimes QuickTime plays MP4 well, sometimes doesn't.

To solve QuickTime won't play MP4 issue, a strongly recommended solution is to convert all kinds of MP4 videos and movies to QuickTime more compatible formats.

Resources: http://www.idealshare.net/mp4-quicktime-solution.html
