### ISSUE TITLE
Bandcamp support artist download

### ISSUE THREAD

**Issue by lightonflux** [rg3/youtube-dl#6809] opened 2015-09-09 08:46 UTC
The extractor for Bandcamp works wonderful.  But only with with an album URL:

   https://thegrammarclub.bandcamp.com/album/bioavailable

Not with an artist URL:

    https://thegrammarclub.bandcamp.com/

Maybe yt-dl could look at the page and extract the album URLs and then proceed normally with track extraction.

**Comment by dstftw** [comment] 2015-09-09 23:04
Duplicate of #6231.

**Closed by dstftw** 2015-09-09 23:04 UTC
Labels: request

**Comment by djvs** [comment] 2016-09-10 21:15
@lightonflux  See script I gave on #6231
