### ISSUE TITLE
Ustream seems to be broken, no playlists are fetched

### ISSUE THREAD

**Issue by dilworks** [rg3/youtube-dl#5534] opened 2015-04-26 23:12 UTC
Just trying to watch some Ustream feeds, but I got this instead:

```
tomman@tomman-lp-c2:~/workbench/tsdx-mbench$ youtube-dl --list-formats --verbose http://www.ustream.tv/channel/rathmanmusic
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--list-formats', u'--verbose', u'http://www.ustream.tv/channel/rathmanmusic']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.17
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.0
[debug] exe versions: avconv 11.3-6, avprobe 11.3-6, ffmpeg 2.6.2-TSDX-WB7ex, ffprobe 2.6.2-TSDX-WB7ex, rtmpdump 2.4
[debug] Proxy map: {}
[ustream:channel] rathmanmusic: Downloading webpage
[ustream:channel] rathmanmusic: Downloading video information (next: 1)
[download] Downloading playlist: 16686678
[ustream:channel] playlist 16686678: Collected 0 video ids (downloading 0 of them)
```

The stream works fine with other tools, like Livestreamer.

**Comment by yan12125** [comment] 2015-04-27 05:37
Currently youtube-dl only supports Ustream archives (recordings). Live streams are not supported yet. It's a duplicate of #2226, thus closing.

**Closed by yan12125** 2015-04-27 05:37 UTC
