### ISSUE TITLE
Trying to download from Xfinity/Comcast for AETV

### ISSUE THREAD

**Issue by yuppicide** [rg3/youtube-dl#14796] opened 2017-11-19 07:20 UTC
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.15**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

I know some people have had this issue in the past? I'm not sure how to fix it. I am on Windows running the latest version. I downloaded the first 3 episodes fine.. because they didn't require a login/pass.

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '--ap-mso=Comcast_SSO', '--ap-username=PRIVATE', '--ap-password=PRIVATE', '-v', 'http://www.aetv.com/shows/shipping-wars/season-1/episode-4']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.11.15
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: rtmpdump 2.3
[debug] Proxy map: {}
[aenetworks] shipping-wars/season-1/episode-4: Downloading webpage
[aenetworks] 17165811: Downloading JSON metadata
[aenetworks] 17165811: Downloading Provider Redirect Page
ERROR: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\common.py", line 437, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\aenetworks.py", line 143, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\adobepass.py", line 1448, in _extract_mvpd_auth
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\adobepass.py", line 1360, in post_form
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\common.py", line 809, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\common.py", line 800, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yuppicide** [comment] 2017-11-19 23:55
I have sent you an email with a user/pass.

**Comment by remitamine** [comment] 2018-01-12 10:25
Duplicate of #11257.

**Closed by remitamine** 2018-01-12 10:25 UTC
Labels: tv-provider-account-needed
