### ISSUE TITLE
cannot download from vbox7.com error

### ISSUE THREAD

**Issue by waitforminute** [rg3/youtube-dl#9879] opened 2016-06-23 18:24 UTC
C:\Users\Admin>C:\Users\Admin\Desktop\youtube-dl.exe --verbose http://vbox7.com/
play:961eb2e2ce
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://vbox7.com/play:961eb2e2ce']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.06.23.1
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[Vbox7] 961eb2e2ce: Downloading webpage
[Vbox7] 961eb2e2ce: Getting session id
[Vbox7] 961eb2e2ce: Downloading webpage
[Vbox7] 961eb2e2ce: Getting session id
[Vbox7] 961eb2e2ce: Downloading redirect page
[Vbox7] 961eb2e2ce: Downloading info webpage
ERROR: Unable to download webpage: HTTP Error 500: Internal Server Error (caused
 by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure
you are using the latest version; type  youtube-dl -U  to update. Be sure to cal
l youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpylirceiz\bu
ild\youtube_dl\extractor\common.py", line 390, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpylirceiz\bu
ild\youtube_dl\YoutubeDL.py", line 1950, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_defau
lt

**Comment by dstftw** [comment] 2016-06-23 18:30
Duplicate of #9876.

**Closed by dstftw** 2016-06-23 18:30 UTC
