### ISSUE TITLE
[ZDF.de] Site support request

### ISSUE THREAD

**Issue by spookyahell** [rg3/youtube-dl#11179] opened 2016-11-13 02:01 UTC
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.08.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.08.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.11.08.1
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.zdf.de/comedy/heute-show/heute-show-vom-09-09-2016-102.html
- Single video: https://www.zdf.de/comedy/heute-show/heute-show-vom-23-09-2016-102.html

---

### Description of your *issue*, suggested solution and other information
So, the ZDF now has a new video deliviring platform. No more ZDFmediathek. 
Extractor must fetch info from `https://www.zdf.de/ZDFplayer/configs/zdf/zdf2016/configuration.json` and then pass them to `https://api.zdf.de/content/documents/%show_ID%.json?profile=player`
show_ID of >https://www.zdf.de/comedy/heute-show/heute-show-vom-09-09-2016-102.html< is `heute-show-vom-09-09-2016-102`
the api.zdf.de must be called with `Api-Auth`-Header `Bearer %apiToken-Value from configuration.json%`
Within the video json there is a mainVideoContent JSON child and it's value `http://zdf.de/rels/streams/ptmd` is relevant for all of the rest. In the there linkd JSON all links can be found (subtitle [VTT, TTML], mp4, hls [Here and often the best of all formats])

**Comment by yan12125** [comment] 2016-11-13 03:39
Duplicate of #11055 and there's a possible solution at #11063

**Closed by yan12125** 2016-11-13 03:39 UTC
