### ISSUE TITLE
How  get get full  output file name  after   downloading ?

### ISSUE THREAD

**Issue by moiseyo** [rg3/youtube-dl#8002] opened 2015-12-24 23:09 UTC
I'm trying to  get  file name  after downloading 
using version  youtube_dl-2014.06.26-py2.7.egg\youtube_dl i could  do it   using code 
  filename = self.prepare_filename(info_dict)
  self.filename=filename
and using version  youtube_dl-2015.12.21-py2.7.egg  the same code   return only  portion if   full  filename

Is any way  to use generic  code  to get get full  output file name  after   downloading 

Thank you

**Comment by mohamed-aziz** [comment] 2015-12-25 11:46
>>> a = youtube_dl.YoutubeDL()
>>> a.prepare_filename({'id': '1234', 'ext':'mp4', 'title':'test'})
u'test-1234.mp4'

**Comment by moiseyo** [comment] 2015-12-25 12:11
I tried 

The   results  
my code :
ydl_opts['formats']= ['mp4','avi']  #  does not filter extentions

file_name=ydl.prepare_filename({'id': out_dir, 'ext':'mp4', 'title':title})
result = ydl.extract_info(url                , download=True)
---------------------------------------------

Result :+1: 
filename :u'c:\\temp\\short\\2\\Louis CK - Restaurant Ordering Impression.mp4 #'
ydl.filename:u'c:\\temp\\short\\2\\Louis CK - Restaurant Ordering Impression.webm #'

Loaded file :+1: 
'c:\\temp\\short\\2\Louis CK - Restaurant Ordering Impression.webm #.mkv   # output File name does not match prepare name  
url: 'https://www.youtube.com/watch?v=OPkZ7TjLO9k'

**Comment by yan12125** [comment] 2017-11-28 05:25
Looks like a duplicate of #5710. Please move on there for further discussion.

**Closed by yan12125** 2017-11-28 05:25 UTC
