### ISSUE TITLE
Extractor Youku returned a compat_list result. It needs to be updated.

### ISSUE THREAD

**Issue by Popolon** [rg3/youtube-dl#5872] opened 2015-06-02 01:31 UTC
youtube-dl 'http://v.youku.com/v_show/id_XMTM5Mzk2NzYw.html'
[Youku] XMTM5Mzk2NzYw: Downloading JSON metadata
WARNING: Extractor Youku returned a compat_list result. It needs to be updated.
ERROR: unable to download video data: HTTP Error 404: Not Found

This is not a duplicate of #3038 (connexion refused and the ticket is closed).

**Comment by jaimeMF** [comment] 2015-06-02 07:09
Like #5114, it's probably a duplicate of #3038 (which is still open).

**Closed by jaimeMF** 2015-06-02 07:09 UTC
