### ISSUE TITLE
TBS and TNT does not work event though 13658 is closed

### ISSUE THREAD

**Issue by cas4** [rg3/youtube-dl#15056] opened 2017-12-22 22:12 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.14*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.14**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl.exe --verbose --hls-prefer-native --ap-mso Comcast_SSO --ap-username <omited> --ap-password <omited> http://www.tbs.com/movies/dr-seuss-how-the-grinch-stole-christmas
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--hls-prefer-native', '--ap-mso', 'Comcast_SSO', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '-v', 'http://www.tbs.com/movies/dr-seuss-how-the-grinch-stole-christmas']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.12.14
[debug] Python version 3.4.4 - Windows-10-10.0.16299
[debug] exe versions: none
[debug] Proxy map: {}
[TBS] dr-seuss-how-the-grinch-stole-christmas: Downloading webpage
[TBS] b18a6993a322c6f51fb02e93a97bf2a5b923303a: Downloading JSON metadata
[TBS] b18a6993a322c6f51fb02e93a97bf2a5b923303a: Downloading Provider Redirect Page
[TBS] b18a6993a322c6f51fb02e93a97bf2a5b923303a: Downloading Provider Login Page
[TBS] b18a6993a322c6f51fb02e93a97bf2a5b923303a: Logging in
[TBS] b18a6993a322c6f51fb02e93a97bf2a5b923303a: Retrieving Session
ERROR: Unable to download webpage: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpekokknty\build\youtube_dl\extractor\common.py", line 506, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpekokknty\build\youtube_dl\YoutubeDL.py", line 2196, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

### Description of your *issue*, suggested solution and other information

I've been following [#13658](https://github.com/rg3/youtube-dl/issues/13658) and the case claims to have TBS working.  I tried both TBS and TNT sites but they both give the following errors listed above.  I double and triple checked my username and password, so that shouldn't be the problem.  From my testing, it does not appear that support for TBS and TNT is fixed (unless I'm missing an argument from my command that I'm not aware of).

**Comment by remitamine** [comment] 2017-12-22 22:23
Duplicate of #11538.
```
youtube-dl http://www.tbs.com/movies/dr-seuss-how-the-grinch-stole-christmas
[TBS] dr-seuss-how-the-grinch-stole-christmas: Downloading webpage
[TBS] b18a6993a322c6f51fb02e93a97bf2a5b923303a: Downloading JSON metadata
[TBS] b18a6993a322c6f51fb02e93a97bf2a5b923303a: Retrieving Media Token
[TBS] b18a6993a322c6f51fb02e93a97bf2a5b923303a: Downloading XML
[TBS] b18a6993a322c6f51fb02e93a97bf2a5b923303a: Downloading m3u8 information
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 245
[download] Destination: Dr. Seuss' How the Grinch Stole Christmas!-b18a6993a322c6f51fb02e93a97bf2a5b923303a.mp4
[download]   0.1% of ~561.16MiB at 64.41KiB/s ETA 03:20:45
```

**Closed by remitamine** 2017-12-22 22:23 UTC
