### ISSUE TITLE
[site support request] Cybrary.it

### ISSUE THREAD

**Issue by iripu** [rg3/youtube-dl#18000] opened 2018-10-28 13:36 UTC
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
E:\Download>youtube-dl -v https://www.cybrary.it/video/investigative-process-md5calc-lab/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.cybrary.it/video/investigative-process-md5calc-lab/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.10.05
[debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg N-91317-gb41b6b3234, ffprobe N-91317-gb41b6b3234
[debug] Proxy map: {}
[generic] investigative-process-md5calc-lab: Requesting header
WARNING: Falling back on generic information extractor.
[generic] investigative-process-md5calc-lab: Downloading webpage
[generic] investigative-process-md5calc-lab: Extracting information
ERROR: Unsupported URL: https://www.cybrary.it/video/investigative-process-md5calc-lab/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\common.py", line 507, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\generic.py", line 3298, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.cybrary.it/video/investigative-process-md5calc-lab/

```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.cybrary.it/video/investigative-process-md5calc-lab/
- Playlist: https://www.cybrary.it/course/computer-hacking-forensics-analyst/

---

### Description of your *issue*, suggested solution and other information
- It needs a free account to view the videos
- Account creation is free and simple just like other sites. Here is one that can be used:
username: sarahmills
pw: sarah
- The videos are hosted on vimeo

**Comment by remitamine** [comment] 2018-10-28 13:49
Duplicate of #15620.

**Closed by remitamine** 2018-10-28 13:49 UTC
