### ISSUE TITLE
Russian letters are not used for filename of downloaded file

### ISSUE THREAD

**Issue by Klaus1189** [rg3/youtube-dl#9439] opened 2016-05-09 16:16 UTC
I use latest youtube-dl 2016.05.01 and this syntax
`youtube-dl -f 22 https://www.youtube.com/watch?v=hNqG7-dwmRo`

```
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. Alle Rechte vorbehalten.

C:\...>youtube-dl -v -f 22 https://www.youtube.com/watch?v=hNqG7-dwmRo
[debug] System config: []
[debug] User config: [u'-i', u'--proxy', u'']
[debug] Command-line args: [u'-v', u'-f', u'22', u'https://www.youtube.com/watch?v=hNqG7-dwmRo']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.05.01
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] hNqG7-dwmRo: Downloading webpage
[youtube] hNqG7-dwmRo: Downloading video info webpage
[youtube] hNqG7-dwmRo: Extracting video information
[youtube] {22} signature length 40.43, html5 player en_US-vflKklr93
[youtube] {43} signature length 40.43, html5 player en_US-vflKklr93
[youtube] {18} signature length 40.43, html5 player en_US-vflKklr93
[youtube] {5} signature length 40.43, html5 player en_US-vflKklr93
[youtube] {36} signature length 40.43, html5 player en_US-vflKklr93
[youtube] {17} signature length 40.43, html5 player en_US-vflKklr93
[youtube] {137} signature length 40.43, html5 player en_US-vflKklr93
[youtube] {248} signature length 40.43, html5 player en_US-vflKklr93
[youtube] {136} signature length 40.43, html5 player en_US-vflKklr93
[youtube] {247} signature length 40.43, html5 player en_US-vflKklr93
[youtube] {135} signature length 40.43, html5 player en_US-vflKklr93
[youtube] {244} signature length 40.43, html5 player en_US-vflKklr93
[youtube] {134} signature length 40.43, html5 player en_US-vflKklr93
[youtube] {243} signature length 40.43, html5 player en_US-vflKklr93
[youtube] {133} signature length 40.43, html5 player en_US-vflKklr93
[youtube] {242} signature length 40.43, html5 player en_US-vflKklr93
[youtube] {160} signature length 40.43, html5 player en_US-vflKklr93
[youtube] {278} signature length 40.43, html5 player en_US-vflKklr93
[youtube] {140} signature length 40.43, html5 player en_US-vflKklr93
[youtube] {171} signature length 40.43, html5 player en_US-vflKklr93
[youtube] {249} signature length 40.43, html5 player en_US-vflKklr93
[youtube] {250} signature length 40.43, html5 player en_US-vflKklr93
[youtube] {251} signature length 40.43, html5 player en_US-vflKklr93
[debug] Invoking downloader on u'https://r4---sn-uxax4vopj5qx-q0nl.googlevideo.com/videoplayback?key=yt6&initcwndbps=1162500&requiressl=yes&lmt=1458215101551084&expire=1462832011&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&mm=31&source=youtube&mn=sn-uxax4vopj5qx-q0nl&ip=88.133.1.193&ratebypass=yes&mt=1462810052&pl=17&mv=m&id=o-AASoTPGwZD2dtSpTvjWpqkZmzWsH7Fjq1jZmCtSuwfaJ&ms=au&dur=227.787&mime=video%2Fmp4&itag=22&upn=TOW_hfxmO_g&ipbits=0&sver=3&fexp=9407155%2C9413140%2C9416126%2C9416891%2C9417380%2C9422596%2C9427543%2C9428398%2C9431012%2C9433045%2C9433096%2C9433775%2C9433946%2C9435697%2C9435806%2C9436089&signature=5DFCC17EB54EEC285A30F3D6AE289F35195531D6.9B12626010D9267D633CD017C3F5B6C50DCB0D23'
[download] Destination:  - -hNqG7-dwmRo.mp4
[download] 100% of 55.53MiB in 00:20
```

**Comment by dstftw** [comment] 2016-05-09 16:18
Duplicate of #5045.
This is intentional behavior for now. See #4787 for the rationale and #5527 for alternative solution discussions.

**Closed by dstftw** 2016-05-09 16:18 UTC

**Comment by Klaus1189** [comment] 2016-05-09 17:02
I read the threads but I'm unsure what I have to do.

**Comment by dstftw** [comment] 2016-05-09 17:17
Build youtube-dl.exe with python 3 or run from sources with python 3 or use any supported OS apart from Windows.

**Comment by Klaus1189** [comment] 2016-05-09 17:24
OK, sadly I'm not a programmer but I know some things about it. Why isn't Python 3 not used as default? If youtube-dl.exe is built with Python 3, does it then work on Win 10?

**Comment by dstftw** [comment] 2016-05-09 17:26
Python 3 build has it's own problems.
