### ISSUE TITLE
music.yandex.ru bug

### ISSUE THREAD

**Issue by byjk** [rg3/youtube-dl#10205] opened 2016-08-01 06:51 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.07.30*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.30**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---
d:\1\3>youtube-dl -v https://music.yandex.ru/album/1980067
[debug] System config: []
[debug] User config: ['--no-mtime', '--no-check-certificate', '-o', '%(title)s.%
(ext)s']
[debug] Command-line args: ['-v', 'https://music.yandex.ru/album/1980067']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.07.30
[debug] Python version 3.4.4 - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg N-50515-g28adecf
[debug] Proxy map: {'http': 'http://someserver:80', 'no': 'localhost,12
7.0.0.1', 'https': 'http://someserver:80'}
[yandexmusic:album] 1980067: Downloading album JSON
[download] Downloading playlist: Nirvana - With The Lights Out - Box Set (2011)
[yandexmusic:album] playlist Nirvana - With The Lights Out - Box Set (2011): Col
lected 23 video ids (downloading 23 of them)
[download] Downloading video 1 of 23
[yandexmusic:track] 555386: Downloading track JSON
[yandexmusic:track] 555386: Downloading track location JSON
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpiptyv43b\bu
ild\youtube_dl\__init__.py", line 422, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpiptyv43b\bu
ild\youtube_dl\__init__.py", line 412, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpiptyv43b\bu
ild\youtube_dl\YoutubeDL.py", line 1775, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpiptyv43b\bu
ild\youtube_dl\YoutubeDL.py", line 693, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpiptyv43b\bu
ild\youtube_dl\YoutubeDL.py", line 854, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpiptyv43b\bu
ild\youtube_dl\YoutubeDL.py", line 746, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpiptyv43b\bu
ild\youtube_dl\YoutubeDL.py", line 682, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpiptyv43b\bu
ild\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpiptyv43b\bu
ild\youtube_dl\extractor\yandexmusic.py", line 138, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpiptyv43b\bu
ild\youtube_dl\extractor\yandexmusic.py", line 96, in _get_track_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpiptyv43b\bu
ild\youtube_dl\extractor\yandexmusic.py", line 78, in _get_track_url
TypeError: Can't convert 'list' object to str implicitly

---

**Comment by dstftw** [comment] 2016-08-01 14:38
Duplicate of #10193.

**Closed by dstftw** 2016-08-01 14:38 UTC
