### ISSUE TITLE
please please please

### ISSUE THREAD

**Issue by Ayman97** [rg3/youtube-dl#8885] opened 2016-03-17 15:01 UTC
please add tuts+ to supported sites, i know that my issue is repeated , but i need this tool soooo bad , my subscription in tuts+ is about to end , i need to batch download all of the courses videos i want, not just download one by one (the normal method in the site). 

and sorry if my English is bad ..
thanks

**Comment by dstftw** [comment] 2016-03-17 15:47
Duplicate of #3662.

**Closed by dstftw** 2016-03-17 15:47 UTC
