### ISSUE TITLE
"No video formats found" on vimeo channels

### ISSUE THREAD

**Issue by johnjam** [rg3/youtube-dl#7476] opened 2015-11-12 19:55 UTC
video to download: https://vimeo.com/channels/iphonehd/131037181
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.10
[debug] Git HEAD: cd49526
[debug] Python version 3.5.0 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {'http': 'http://127.0.0.1:8228', 'https': 'http://127.0.0.1:8228'}
[vimeo] 131037181: Downloading webpage
[vimeo] 131037181: Extracting information
[vimeo] 131037181: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/vimeo.py", line 427, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 766, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment] 2015-11-12 19:55
Duplicate of #7460.

**Closed by dstftw** 2015-11-12 19:55 UTC
