### ISSUE TITLE
Feature Request: Concatenate Post Processor

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#5956] opened 2015-06-12 00:54 UTC
I see there are already a few threads regarding this...but I was unable to see a conclusion (or I just missed it)
Currently I am using this sequence of commands and it seems to work:

youtube-dl http://thedailyshow.cc.com/full-episodes
youtube-dl http://thedailyshow.cc.com/full-episodes --get-filename  > filenames.txt

then a quick vbs parsing script to generate the following from the filenames.txt:

ffmpeg -i "thedailyshow june-10--2015---colin-quinn part 1-998f98c7-ead3-49a8-a411-d521dc0aaf1b.mp4" -c copy -bsf:v h264_mp4toannexb -f mpegts -y intermediate1.ts
ffmpeg -i "thedailyshow june-10--2015---colin-quinn part 2-11c46b77-b819-46d2-83d3-860e513bc82a.mp4" -c copy -bsf:v h264_mp4toannexb -f mpegts -y intermediate2.ts
ffmpeg -i "thedailyshow june-10--2015---colin-quinn part 3-2c62782c-320e-461b-ad99-8500ac4cfc67.mp4" -c copy -bsf:v h264_mp4toannexb -f mpegts -y intermediate3.ts
ffmpeg -i "thedailyshow june-10--2015---colin-quinn part 4-e92f9733-a359-4fbd-81a1-87b85cc7ce95.mp4" -c copy -bsf:v h264_mp4toannexb -f mpegts -y intermediate4.ts

ffmpeg -i "concat:intermediate1.ts|intermediate2.ts|intermediate3.ts|intermediate4.ts" -c copy -bsf:a aac_adtstoasc "thedailyshow.mp4"

Afraid I don't have the mad python skills to make a post processor, but just thought I'd offer it up....

Thanks
Ringo

**Comment by dstftw** [comment] 2016-01-24 11:42
Duplicate of #1325.

**Closed by dstftw** 2016-01-24 11:42 UTC
