### ISSUE TITLE
ozee download error 

### ISSUE THREAD

**Issue by drboy** [rg3/youtube-dl#15167] opened 2018-01-04 02:43 UTC
\youtube-dl-master>youtube-dl -f best --batch-file="ss.txt"
[generic] cheekhek-khauffnakk-sach-episode-21-june-19-2017-full-episode: Requesting header
WARNING: Falling back on generic information extractor.
[generic] cheekhek-khauffnakk-sach-episode-21-june-19-2017-full-episode: Downloading webpage
[generic] cheekhek-khauffnakk-sach-episode-21-june-19-2017-full-episode: Extracting information
[generic] cheekhek-khauffnakk-sach-episode-21-june-19-2017-full-episode: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 301: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Moved Permanently
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  
http://www.ozee.com/shows/cheekhek-khauffnakk-sach/video?page=2

**Comment by gurditsbedi** [comment] 2018-01-04 12:34
According to [this website](https://rg3.github.io/youtube-dl/supportedsites.html) ozee.com is not supported.

**Comment by remitamine** [comment] 2018-01-04 18:36
Duplicate of #11058

**Closed by remitamine** 2018-01-04 18:36 UTC
