### ISSUE TITLE
Request - Prevent Unnecessary Date Checks for Channels

### ISSUE THREAD

**Issue by jacksonedmonds** [rg3/youtube-dl#9095] opened 2016-04-06 14:40 UTC
Currently if you specify a date parameter when downloading from a YouTube channel, youtube-dl will check every single video on that channel to see if it matches the date requirement. While this makes sense for an unorder playlist, or for `--datebefore`, it is unnecessary for `--date` and `--dateafter` when applied to a YouTube channel (which by its nature is already chronologically ordered).

I propose that when using `--date` or `--dateafter` and specifying a URL which points to a YouTube channel, youtube-dl should stop downloading video info once a video with a date before the specified date is found.
For example,  if I run youtube-dl with `--date 20160407` and specify a channel URL, once a video from 20160406 is found, youtube-dl will not check any further videos.

Cheers.

**Comment by dstftw** [comment] 2016-04-06 14:44
Duplicate of #1502.

**Closed by dstftw** 2016-04-06 14:44 UTC
