### ISSUE TITLE
ERROR: [SSL: CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by xiaose** [rg3/youtube-dl#7475] opened 2015-11-12 18:49 UTC
C:\Program Files\YTDL>youtude-dl.exe https://www.youtube.com/watch?v=YsbTTY4nx0g -F --verbose
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=YsbTTY4nx0g', u'-F', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.11.10
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-60835-ga3a4d07, ffprobe N-60835-ga3a4d07
[debug] Proxy map: {}
[youtube] YsbTTY4nx0g: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)> (caused by URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))
  File "youtube_dl\extractor\common.pyo", line 329, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1873, in urlopen
  File "urllib2.pyo", line 431, in open
  File "urllib2.pyo", line 449, in _open
  File "urllib2.pyo", line 409, in _call_chain
  File "youtube_dl\utils.pyo", line 794, in https_open
  File "urllib2.pyo", line 1197, in do_open
```
...
...
...

C:\Program Files\YTDL>youtude-dl.exe --verbose -F https://www.youtube.com/watch?v=shQ3jdqrTg0
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-F', u'https://www.youtube.com/watch?v=shQ3jdqrTg0']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.11.10
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-60835-ga3a4d07, ffprobe N-60835-ga3a4d07
[debug] Proxy map: {}
[youtube] shQ3jdqrTg0: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)> (caused by URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))
  File "youtube_dl\extractor\common.pyo", line 329, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1873, in urlopen
  File "urllib2.pyo", line 431, in open
  File "urllib2.pyo", line 449, in _open
  File "urllib2.pyo", line 409, in _call_chain
  File "youtube_dl\utils.pyo", line 794, in https_open
  File "urllib2.pyo", line 1197, in do_open
```

**Comment by dstftw** [comment] 2015-11-12 18:52
Duplicate of #7309.

**Closed by dstftw** 2015-11-12 18:52 UTC

**Comment by a1iraxa** [comment] 2018-01-19 20:05
#11573 fixed.
