### ISSUE TITLE
ERROR: Unable to download webpage

### ISSUE THREAD

**Issue by mitguru007** [rg3/youtube-dl#7586] opened 2015-11-21 08:41 UTC
When is run "youtube-dl -J https://www.youtube.com/watch?v=fSr5YIfAWzw"
Get bellow error:
ERROR: Unable to download webpage: <urlopen error [Errno -3] Temporary failure in name resolution> (caused by URLError(gaierror(-3, 'Temporary failure in name resolution'),))

youtube-dl working fine. but, Some time continuously start this error. when i restart my Linux machine then error is solve and working fine again. 

Why this error start suddenly?

**Comment by yan12125** [comment] 2015-11-21 08:53
Such error messages indicates your DNS server is unstable. Closing as it's beyond the scope of youtube-dl.

**Closed by yan12125** 2015-11-21 08:53 UTC

**Comment by mitguru007** [comment] 2015-11-21 08:59
but, how to solve this? give me some step or some information. please

**Comment by mitguru007** [comment] 2015-11-21 09:11
yes i got. BIND DNS stop running..  
Thanks bro

**Comment by tristian2** [comment] 2015-11-27 00:01
@mitguru007 did you fix it?  i too get this issue 

ERROR: Unable to download webpage: <urlopen error [Errno -3] Try again> (caused by URLError(gaierror(-3, 'Try again'),))

if you fixed it, how?

thanks
