### ISSUE TITLE
Unable to download video from The Escapist

### ISSUE THREAD

**Issue by elevul** [rg3/youtube-dl#5531] opened 2015-04-26 11:07 UTC
As per title. Full report in the image.
![escapist](https://cloud.githubusercontent.com/assets/6944931/7336942/2c82a3c0-ec15-11e4-97b3-c166607b0cb8.JPG)
Youtube-dl is updated to the latest version.

**Comment by robin007bond** [comment] 2015-04-26 12:33
Same thing here, when trying to download the example URL.

For testing purposes, this is the URL:

http://www.escapistmagazine.com/videos/view/zero-punctuation/10104-Axiom-Verge-Stealth-Inc-2-Review

**Comment by dstftw** [comment] 2015-04-27 11:16
Duplicate of #5090.

**Closed by dstftw** 2015-04-27 11:16 UTC
