### ISSUE TITLE
(Bug report) WARNING: [youtube] RncVWdCURcc: Skipping DASH manifest: ExtractorError(u'Failed to download MPD manifest: HTTP Error 403: Forbidden (caused by HTTPError())

### ISSUE THREAD

**Issue by Serkan-devel** [rg3/youtube-dl#11119] opened 2016-11-04 16:32 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.04*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.04**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
<pre>
patently@Kachel:~$ sudo pip install --upgrade youtube-dlThe directory '/home/patently/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/patently/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already up-to-date: youtube-dl in /usr/local/lib/python2.7/dist-packages
patently@Kachel:~$ sudo pip install --upgrade pip
The directory '/home/patently/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/patently/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages
patently@Kachel:~$ sudo pip install --upgrade youtube-dl
The directory '/home/patently/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/patently/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already up-to-date: youtube-dl in /usr/local/lib/python2.7/dist-packages
patently@Kachel:~$ youtube-dl --verbose https://www.youtube.com/watch?v=RncVWdCURcc -f 'bestvideo+bestaudio/best'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=RncVWdCURcc', u'-f', u'bestvideo+bestaudio/best']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.04
[debug] Python version 2.7.12 - Linux-4.4.0-45-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.8-0ubuntu0.16.04.1, ffprobe 2.8.8-0ubuntu0.16.04.1
[debug] Proxy map: {}
[youtube] RncVWdCURcc: Downloading webpage
[youtube] RncVWdCURcc: Downloading video info webpage
[youtube] RncVWdCURcc: Extracting video information
[youtube] {22} signature length 40.40, html5 player en_US-vfl9TjB9H
[youtube] {43} signature length 40.40, html5 player en_US-vfl9TjB9H
[youtube] {18} signature length 40.40, html5 player en_US-vfl9TjB9H
[youtube] {36} signature length 40.40, html5 player en_US-vfl9TjB9H
[youtube] {17} signature length 40.40, html5 player en_US-vfl9TjB9H
[youtube] {137} signature length 40.40, html5 player en_US-vfl9TjB9H
[youtube] {248} signature length 40.40, html5 player en_US-vfl9TjB9H
[youtube] {136} signature length 40.40, html5 player en_US-vfl9TjB9H
[youtube] {247} signature length 40.40, html5 player en_US-vfl9TjB9H
[youtube] {135} signature length 40.40, html5 player en_US-vfl9TjB9H
[youtube] {244} signature length 40.40, html5 player en_US-vfl9TjB9H
[youtube] {134} signature length 40.40, html5 player en_US-vfl9TjB9H
[youtube] {243} signature length 40.40, html5 player en_US-vfl9TjB9H
[youtube] {133} signature length 40.38, html5 player en_US-vfl9TjB9H
[youtube] {242} signature length 40.40, html5 player en_US-vfl9TjB9H
[youtube] {160} signature length 40.40, html5 player en_US-vfl9TjB9H
[youtube] {278} signature length 40.40, html5 player en_US-vfl9TjB9H
[youtube] {140} signature length 40.40, html5 player en_US-vfl9TjB9H
[youtube] {171} signature length 40.40, html5 player en_US-vfl9TjB9H
[youtube] {249} signature length 40.40, html5 player en_US-vfl9TjB9H
[youtube] {250} signature length 40.40, html5 player en_US-vfl9TjB9H
[youtube] {251} signature length 40.40, html5 player en_US-vfl9TjB9H
[youtube] RncVWdCURcc: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vfl9TjB9H/base.js
[youtube] RncVWdCURcc: Downloading MPD manifest
WARNING: [youtube] RncVWdCURcc: Skipping DASH manifest: ExtractorError(u'Failed to download MPD manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[debug] Invoking downloader on u'https://r6---sn-i5h7ln7r.googlevideo.com/videoplayback?gcr=de&dur=1039.872&ipbits=0&expire=1478297973&lmt=1465110143326003&key=yt6&mime=video%2Fmp4&gir=yes&itag=137&clen=253177697&initcwndbps=507500&upn=ja0dHLn5SkQ&source=youtube&keepalive=yes&ei=FbUcWMbcKaOpiAbj3YT4BA&requiressl=yes&ip=188.96.209.185&sparams=clen%2Cdur%2Cei%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&mv=m&mt=1478276043&ms=au&mn=sn-i5h7ln7r&mm=31&pl=20&id=o-APYxmHlQJ_4wv4rzPxS0GlI4ydIHLE7s9Q8QdaaLjetl&signature=012FE1C0AF02BA46BE885C0EEB2CE8B3941E807B.4D13AB1176BFD614807D7B4555BD4B5FF647687B&ratebypass=yes'
[download] Resuming download at byte 15494963
[download] Destination: HALT DIE FRESSE YOUTUBE DEUTSCHLAND-RncVWdCURcc.f137.mp4
[download] 100% of 241.45MiB in 03:06
[debug] Invoking downloader on u'https://r6---sn-i5h7ln7r.googlevideo.com/videoplayback?gcr=de&dur=1039.928&ipbits=0&expire=1478297973&lmt=1465109931746503&key=yt6&mime=audio%2Fmp4&gir=yes&itag=140&clen=16517588&initcwndbps=507500&upn=ja0dHLn5SkQ&source=youtube&keepalive=yes&ei=FbUcWMbcKaOpiAbj3YT4BA&requiressl=yes&ip=188.96.209.185&sparams=clen%2Cdur%2Cei%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&mv=m&mt=1478276043&ms=au&mn=sn-i5h7ln7r&mm=31&pl=20&id=o-APYxmHlQJ_4wv4rzPxS0GlI4ydIHLE7s9Q8QdaaLjetl&signature=9D606F39905B381059F463C3677748A6784416FB.975C1448B457ACAA0BC53D7F7380A7C117AA1738&ratebypass=yes'
[download] Destination: HALT DIE FRESSE YOUTUBE DEUTSCHLAND-RncVWdCURcc.f140.m4a
[download] 100% of 15.75MiB in 00:13
[ffmpeg] Merging formats into "HALT DIE FRESSE YOUTUBE DEUTSCHLAND-RncVWdCURcc.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:HALT DIE FRESSE YOUTUBE DEUTSCHLAND-RncVWdCURcc.f137.mp4' -i 'file:HALT DIE FRESSE YOUTUBE DEUTSCHLAND-RncVWdCURcc.f140.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:HALT DIE FRESSE YOUTUBE DEUTSCHLAND-RncVWdCURcc.temp.mp4'
Deleting original file HALT DIE FRESSE YOUTUBE DEUTSCHLAND-RncVWdCURcc.f137.mp4 (pass -k to keep)
Deleting original file HALT DIE FRESSE YOUTUBE DEUTSCHLAND-RncVWdCURcc.f140.m4a (pass -k to keep)
patently@Kachel:~$
</pre>

---

### Description of your *issue*, suggested solution and other information

I only get an error when downloading this youtube video but playing back seems to be normal.

**Comment by dstftw** [comment] 2016-11-04 16:55
This is not an error.
Duplicate of #8944.

**Closed by dstftw** 2016-11-04 16:55 UTC
