### ISSUE TITLE
video.sibnet.ru not supported by generic extractor anymore due to site layout change

### ISSUE THREAD

**Issue by arisboch** [rg3/youtube-dl#14316] opened 2017-09-24 18:24 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.24*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.24**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
```
casval@casval-X6815 /tmp % youtube-dl -v  http://video.sibnet.ru/day/20170925/video3070570-Kogda_vsyu_svoyu_jizn_ne_sidel_sloja_lapki/\?utm_source\=main_page\&utm_medium\=video_block_day\&utm_campaign\=main_page_may
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://video.sibnet.ru/day/20170925/video3070570-Kogda_vsyu_svoyu_jizn_ne_sidel_sloja_lapki/?utm_source=main_page&utm_medium=video_block_day&utm_campaign=main_page_may']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.24
[debug] Python version 2.7.13 - Linux-4.10.0-35-generic-x86_64-with-Ubuntu-17.04-zesty
[debug] exe versions: avconv 3.2.4-1build2, avprobe 3.2.4-1build2, ffmpeg 3.2.4-1build2, ffprobe 3.2.4-1build2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] ?utm_source=main_page&utm_medium=video_block_day&utm_campaign=main_page_may: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?utm_source=main_page&utm_medium=video_block_day&utm_campaign=main_page_may: Downloading webpage
[generic] ?utm_source=main_page&utm_medium=video_block_day&utm_campaign=main_page_may: Extracting information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'http://video.sibnet.ru/shell.php?videoid=3070570'
[download] Destination: Когда всю свою жизнь не сидел сложа лапки-shell.php
[download] 100% of 9.41KiB in 00:00
```
Due to a layout change of the SibNet video site, the download fails (it just downloads a tiny .php file and no video whatsoever). It is however possible to download the video using an [Greasemonkey script](https://greasyfork.org/en/scripts/30954-download-sibnet-video-as-mp4), so they may be still hope.

**Comment by dstftw** [comment] 2017-09-24 18:26
Duplicate of #2879.

**Closed by dstftw** 2017-09-24 18:26 UTC

**Comment by arisboch** [comment] 2017-09-24 18:38
They is a new problem, please re-open the issue! Back then, the generic extractors were enough, now they aren't!

**Comment by dstftw** [comment] 2017-09-24 18:42
Stop posting duplicates. Site support request already exists.
