### ISSUE TITLE
Unable to download : Error http 429

### ISSUE THREAD

**Issue by GBenoitG** [rg3/youtube-dl#8630] opened 2016-02-22 00:24 UTC
I just want to test youtube-dl, but it's not possible.

`youtube-dl -v 'https://www.youtube.com/watch?t=4&v=BaW_jenozKc'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?t=4&v=BaW_jenozKc']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.13
[debug] Python version 2.7.3 - Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Debian-7
[debug] exe versions: avconv 0.8.17-6, avprobe 0.8.17-6, ffmpeg 0.8.17-6, ffprobe 0.8.17-6
[debug] Proxy map: {}
[youtube] BaW_jenozKc: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by
HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest
version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose
flag and include its complete output.
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 354, in
_request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1905, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 407, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 520, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 445, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 528, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
`

**Comment by yan12125** [comment] 2016-02-22 03:09
Duplicate of #5138. See discussion there and [this FAQ entry](https://github.com/rg3/youtube-dl/#http-error-429-too-many-requests-or-402-payment-required) for more information.

**Closed by yan12125** 2016-02-22 03:09 UTC
