### ISSUE TITLE
facebook video does not work - 500 server 

### ISSUE THREAD

**Issue by balyanrobin** [rg3/youtube-dl#8146] opened 2016-01-05 17:41 UTC
$ python -V
Python 2.7.9
$
$
$ /usr/local/scripts/youtube-dl https://www.facebook.com/myspass/videos/10153760344058119/ -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.facebook.com/myspass/videos/10153760344058119/', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.01
[debug] Python version 2.7.9 - Linux-3.10.53-56.140.amzn1.x86_64-x86_64-with-glibc2.3
[debug] exe versions: none
[debug] Proxy map: {}
[facebook] 10153760344058119: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 500: Internal Server Error (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/scripts/youtube-dl/youtube_dl/extractor/common.py", line 330, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/scripts/youtube-dl/youtube_dl/YoutubeDL.py", line 1886, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by dstftw** [comment] 2016-01-05 17:50
Duplicate of #8072.

**Closed by dstftw** 2016-01-05 17:50 UTC
