### ISSUE TITLE
Livestream download URL possibly broken

### ISSUE THREAD

**Issue by Ranutso** [rg3/youtube-dl#8797] opened 2016-03-08 20:07 UTC
Description:

I've noticed that since the last upgrade, Python will return a traceback error when downloading from Livestream (please see the debug messages below). I've noticed that this could be due a missing forward slash in the download URL.

```
$ youtube-dl -v "http://livestream.com/nrl/roostersrabbitohs2016"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://livestream.com/nrl/roostersrabbitohs2016']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.06
[debug] Python version 2.7.10 - Darwin-15.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.0, ffprobe 3.0
[debug] Proxy map: {}
[livestream] Downloading JSON metadata
[livestream] 4865369: Downloading page 1
[livestream] 4865369: Downloading page 2
[download] Downloading playlist: Roosters vs. Rabbitohs
[livestream] playlist Roosters vs. Rabbitohs: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[livestream] 114483875: Downloading JSON metadata
[livestream] 114483875: Downloading SMIL file
[debug] Invoking downloader on u'http://livestream-f.akamaihd.net3161248_4865369_a3721ed24b4a4f7fa6e960bba2bb2218_1_2320@103172?v=3.0.3&fp=WIN%2014,0,0,145&ssek=1598'
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 412, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 402, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1718, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 679, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 839, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 731, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 679, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 724, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1364, in process_video_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1626, in process_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1568, in dl
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 344, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 58, in real_download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1931, in url open
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 719, in http_open
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1194, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in end headers
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/idna.py", line 164, in encode
    result.append(ToASCII(label))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/idna.py", line 73, in ToASCII
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long
```
Notice that there is a forward slash missing after akamaihd.net on the "[debug] Invoking downloader on" URL.

Thank you!

**Comment by puncy** [comment] 2016-03-09 01:21
Hi ranutso

Looks like you are trying to do the same thing as me ;)

I put in an issue last night about it

**Comment by dstftw** [comment] 2016-03-09 17:08
Duplicate of #8794.

**Closed by dstftw** 2016-03-09 17:08 UTC

**Comment by gamersalpha** [comment] 2018-11-01 12:38
How to fixi this please ?
