### ISSUE TITLE
Could NOT download video from youtube

### ISSUE THREAD

**Issue by macfanr** [rg3/youtube-dl#6594] opened 2015-08-18 03:25 UTC
Could not download video with Vevo/W marked video(https://www.youtube.com/watch?v=ut9ThAbfde0).
it works well always, but today it always failed.

/////////////////////////////////////////////////////////////////////////////LOG///////////////////////////////////////////////////////////////////////////
[youtube] ut9ThAbfde0: Downloading webpage
[youtube] ut9ThAbfde0: Downloading video info webpage
[youtube] ut9ThAbfde0: Extracting video information
[youtube] ut9ThAbfde0: Downloading DASH manifest
WARNING: [youtube] ut9ThAbfde0: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
ERROR: unable to download video data: HTTP Error 403: Forbidden

**Comment by dstftw** [comment] 2015-08-18 03:29
Duplicate of #6451. Remove cache with `youtube-dl --rm-cache-dir`.

**Closed by dstftw** 2015-08-18 03:29 UTC
