### ISSUE TITLE
Unable to download webpage: HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by vippendu** [rg3/youtube-dl#5160] opened 2015-03-08 07:17 UTC
youtube-dl https://www.youtube.com/watch?v=hcfGm247m4Q
[youtube] hcfGm247m4Q: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by vippendu** [comment] 2015-03-08 07:25
File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 314, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1674, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib64/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.6/urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by jaimeMF** [comment] 2015-03-08 10:56
Duplicate of #5138.

**Closed by jaimeMF** 2015-03-08 10:56 UTC
