### ISSUE TITLE
[Support] Get Playlist Creator

### ISSUE THREAD

**Issue by Terax235** [rg3/youtube-dl#14427] opened 2017-10-06 13:39 UTC
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information
Is it possible to get a Playlist Creator with `YoutubeDL.getInfo()` ?
Like, I want to get a Playlist by URL, and then want to get who made the playlist, I have that:
```js
YoutubeDL.getInfo(PLAYLIST_URL, ['--no-warnings', '--force-ipv4'], async (err, info) => {
console.log(info[0].playlist_title)
});
```
But I didn't found a way on google and the Readme to get a Creator of a Youtube Playlist!

**Comment by dstftw** [comment] 2017-10-06 18:06
Not possible. Also no such method exist.
Duplicate of #11427.

**Closed by dstftw** 2017-10-06 18:06 UTC
