### ISSUE TITLE
Download best quality audio available

### ISSUE THREAD

**Issue by TriggerThumb** [rg3/youtube-dl#11657] opened 2017-01-09 22:43 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.08*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.08**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.01.08
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by TriggerThumb** [comment] 2017-01-09 22:54
Can someone please advise the best switch to use to capture the highest quality audio stream.

For example using the -f switch I'm looking to get the highest quality audio regardless if is available through audio only stream or a mixed audio/video stream.

Also, if this is not downloaded as an m4a file how would I remux (no conversion) the output to ensure I end up with just the m4a rather than a webm or something else?

I'm aware I can use the --extract-audio m4a switch but will this automatically look for the highest bitrate audio stream available including those in a mix of audio/video?

**Comment by dstftw** [comment] 2017-01-09 23:24
>get the highest quality audio regardless if is available through audio only stream or a mixed audio/video stream

Not possible, duplicate of #9302.

It's impossible to get m4a from webm without conversion.

` --extract-audio m4a` does not make any sense since ` --extract-audio` does not accept any arguments.

`-f bestaudio/best -x --audio-format m4a` is best you can do.

**Closed by dstftw** 2017-01-09 23:24 UTC

**Comment by jjgh** [comment] 2017-09-15 04:55
> `-f bestaudio/best -x --audio-format m4a` is best you can do.

@dstftw, but m4a is a container isn't it? So what will youtube-dl do in this case? Call ffmpeg to convert (re-encode) the extracted audio to aac and then put it in a m4a container?

**Comment by jjgh** [comment] 2017-09-16 19:02
sorry @dstftw but my question above arises from the fact that IMHO readme is not clear on what `--audio-format` actually does.

- Does it *always* re-encode to the given format? (and could you guys be a bit more consistent with the terminology: conversion vs re-encoding, choose one)
- What if bestaudio is already downloading the format given to `--audio-format`?
- What does `--audio-format best` do?
- Why is `--audio-format` accepting m4a and aac but not webm as a container for Opus/Vorbis?

Ty!
