### ISSUE TITLE
Crash on bandcamp album download on OS X

### ISSUE THREAD

**Issue by AAS** [rg3/youtube-dl#5333] opened 2015-03-31 13:45 UTC
My system info:
```
-> % uname -a
Darwin mbp13r.local 14.1.0 Darwin Kernel Version 14.1.0: Thu Feb 26 19:26:47 PST 2015; root:xnu-2782.10.73~1/RELEASE_X86_64 x86_64
aas@mbp13r [18:43:52] [~/Music/quake64] 
-> % brew --version
0.9.5
-> % youtube-dl --version
2015.03.28
```

Here is the crash output:
```
-> % youtube-dl -v http://aubreyhodges.bandcamp.com/album/quake-nintendo-64-official-soundtrack
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://aubreyhodges.bandcamp.com/album/quake-nintendo-64-official-soundtrack']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.28
[debug] Python version 2.7.9 - Darwin-14.1.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.6.1, ffprobe 2.6.1
[debug] Proxy map: {}
[Bandcamp:album] quake-nintendo-64-official-soundtrack: Downloading webpage
[download] Downloading playlist: Quake - Nintendo 64: Official Soundtrack
[Bandcamp:album] playlist Quake - Nintendo 64: Official Soundtrack: Collected 19 video ids (downloading 19 of them)
[download] Downloading video 1 of 19
[Bandcamp] quake-n64-theme: Downloading webpage
[debug] Invoking downloader on u'http://popplers5.bandcamp.com/download/track?enc=mp3-128&fsig=29202afb1f488bd498bfea77cc665b7e&id=1110736880&stream=1&ts=1427619504.0'
[download] Quake N64 Theme-1110736880.mp3 has already been downloaded
[download] 100% of 4.61MiB
[download] Downloading video 2 of 19
[Bandcamp] quake-n64-level-complete: Downloading webpage
[debug] Invoking downloader on u'http://popplers5.bandcamp.com/download/track?enc=mp3-128&fsig=208d814a18b3414fd4ec50b6d1382347&id=929181834&stream=1&ts=1427619505.0'
[download] Quake N64 Level Complete-929181834.mp3 has already been downloaded
[download] 100% of 3.63MiB
[download] Downloading video 3 of 19
[Bandcamp] quake-n64-rune-acquired: Downloading webpage
[debug] Invoking downloader on u'http://popplers5.bandcamp.com/download/track?enc=mp3-128&fsig=54997ccc8883a0966043d63edc164fea&id=943351211&stream=1&ts=1427619506.0'
[download] Quake N64 Rune Acquired-943351211.mp3 has already been downloaded
[download] 100% of 2.05MiB
[download] Downloading video 4 of 19
[Bandcamp] warbled-level-slipgate-complex: Downloading webpage
[debug] Invoking downloader on u'http://popplers5.bandcamp.com/download/track?enc=mp3-128&fsig=935a3ac17929fa3586296ebbfd1b5248&id=3645197842&stream=1&ts=1427619508.0'
[download] Warbled (Level - Slipgate Complex)-3645197842.mp3 has already been downloaded
[download] 100% of 10.98MiB
[download] Downloading video 5 of 19
[Bandcamp] growls-of-the-lost-level-castle-of-the-damned: Downloading webpage
[Bandcamp] 3157256848: Downloading free downloads page
[Bandcamp] 3157256848: Requesting download url
[debug] Invoking downloader on u''
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 408, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 398, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1446, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 662, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 821, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 715, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 662, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 708, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1150, in process_video_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1379, in process_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1354, in dl
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 341, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 64, in real_download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1673, in urlopen
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 423, in open
    protocol = req.get_type()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 285, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: 
```

**Comment by naglis** [comment] 2015-03-31 19:15
Duplicate of  #4861.

**Closed by naglis** 2015-03-31 19:15 UTC
