### ISSUE TITLE
latest git not working with some vids from le.com

### ISSUE THREAD

**Issue by jacwl** [rg3/youtube-dl#9757] opened 2016-06-11 16:28 UTC
the latest git is still not working with some vids from le.com

examples:
[http://sports.le.com/video/25418114.html](http://sports.le.com/video/25418114.html)
[http://sports.le.com/video/25741493.html](http://sports.le.com/video/25741493.html)
[http://www.le.com/ptv/vplay/25606975.html](http://www.le.com/ptv/vplay/25606975.html)
[http://www.le.com/ptv/vplay/25726861.html](http://www.le.com/ptv/vplay/25726861.html)

log from verbose is too long, I have attached the original log file below in case you need it

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://sports.le.com/video/25418114.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2016.06.11.3
[debug] Python version 2.7.6 - Linux-3.19.0-49-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg N-80271-g5fd7394-static
[debug] Proxy map: {}
[Le] 25418114: Downloading webpage
[Le] 25418114: Downloading playJson data
[Le] 25418114: Download JSON metadata for format 350
[Le] 25418114: Downloading m3u8 information for format 350
[Le] 25418114: Download JSON metadata for format 1000
[Le] 25418114: Downloading m3u8 information for format 1000
[Le] 25418114: Download JSON metadata for format 1300
[Le] 25418114: Downloading m3u8 information for format 1300
[Le] 25418114: Download JSON metadata for format 720p
[Le] 25418114: Downloading m3u8 information for format 720p
[Le] 25418114: Download JSON metadata for format 1080p
[Le] 25418114: Downloading m3u8 information for format 1080p
[debug] Invoking downloader on u'data:application/vnd.apple.mpegurl;base64,**EDITED**
[download] Destination: 2016环意自行车赛第十赛段全场录播（中文）-25418114.mp4
[debug] ffmpeg command line: ffmpeg -y -i 'data:application/vnd.apple.mpegurl;base64,**EDITED**
ERROR: unable to download video
Traceback (most recent call last):
  File "youtube_dl/YoutubeDL.py", line 1740, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "youtube_dl/YoutubeDL.py", line 687, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "youtube_dl/YoutubeDL.py", line 733, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "youtube_dl/YoutubeDL.py", line 1386, in process_video_result
    self.process_info(new_info)
  File "youtube_dl/YoutubeDL.py", line 1653, in process_info
    raise UnavailableVideoError(err)
UnavailableVideoError: [Errno 7] Argument list too long
```

[log1.txt](https://github.com/rg3/youtube-dl/files/310329/log1.txt)

**Comment by yan12125** [comment] 2016-06-11 16:31
Duplicate of #8588. Add ```--hls-prefer-native``` as a workaround.

**Closed by yan12125** 2016-06-11 16:31 UTC
