### ISSUE TITLE
openload.co cant download version 2017.1

### ISSUE THREAD

**Issue by mdoulabi** [rg3/youtube-dl#11652] opened 2017-01-09 13:57 UTC
youtube-dl -g https://openload.co/f/px-VMa2_q90/xcite-anal.dementia
ERROR: Unable to extract encrypted data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
why??

**Comment by yan12125** [comment] 2017-01-09 14:00
Duplicate of #10408. openload has changed their codes.

**Closed by yan12125** 2017-01-09 14:00 UTC
