### ISSUE TITLE
modification for bilibili extractor

### ISSUE THREAD

**Issue by njuFerret** [rg3/youtube-dl#17289] opened 2018-08-21 07:19 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale cp936, fs utf-8, out utf-8, pref cp936
[debug] youtube-dl version 2018.08.04
[debug] Python version 3.6.6 (CPython) - Windows-10-10.0.17134-SP0
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.bilibili.com/video/av28557586/?p=20
- Playlist: https://www.bilibili.com/video/av28557586/

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Bilibili extractor modification

I'm not sure if it's suitable to open an issue here. when downloading videos from bilibili.com, if the link contains a series of viedos, youtube-dl can only extract the first videos. 

for example, download the page on [https://www.bilibili.com/video/av28557586/?p=20]( https://www.bilibili.com/video/av28557586/?p=20 ), it contains a series of 38 videos distinguished by query parameter `?p=xx`,

here, I modify code of bilibili extrator, now it works with query string.

here's the patch [bilibili extrator]( https://gist.github.com/njuFerret/80fa1723f9571a799dbb534da6cd3172/raw/7c5ecbcb15df0c5029fcaa581fd142da6ebdec0a/bilibili.py )

this patch can work on links like `https://www.bilibili.com/video/av28557586/?p=20` only. 

to download one viedo use parameter `%(playlist_index)s` like: 
`youtube-dl -o "%(title)s_%(playlist_index)s.%(ext)s" -f "best" https://www.bilibili.com/video/av28557586/?p=20`

**Comment by remitamine** [comment] 2018-08-21 09:33
Duplicate of #16052.

**Closed by remitamine** 2018-08-21 09:33 UTC

**Comment by dragonken** [comment] 2018-12-13 19:09
How to use the [bilibili extrator](https://gist.githubusercontent.com/njuFerret/80fa1723f9571a799dbb534da6cd3172/raw/7c5ecbcb15df0c5029fcaa581fd142da6ebdec0a/bilibili.py) ?

```
$ git apply bilibili_extractor.diff
error: bilibili-61cb668-left.py: No such file or directory
```
