### ISSUE TITLE
Unable to download from SoundCloud

### ISSUE THREAD

**Issue by espectalll123** [rg3/youtube-dl#6958] opened 2015-09-24 22:14 UTC
After executing the following command:

    youtube-dl https://soundcloud.com/sushi_killer/sushi-killer-waifu-dream

I got this log in return:

    [soundcloud] sushi_killer/sushi-killer-waifu-dream: Resolving id
    [soundcloud] sushi_killer/sushi-killer-waifu-dream: Downloading info JSON
    ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Why was there a 401 Unauthorized error? Maybe SoundCloud "patched" the JSON request, or maybe it was a problem with my connection?

**Comment by dstftw** [comment] 2015-09-24 22:23
Duplicate of #6930.

**Closed by dstftw** 2015-09-24 22:23 UTC
