### ISSUE TITLE
auto-generated "Youtube mix" playlists are limited to 26 videos

### ISSUE THREAD

**Issue by remustata** [rg3/youtube-dl#6529] opened 2015-08-11 19:59 UTC
running command:
$ youtube-dl --verbose https://www.youtube.com/playlist?list=RDi7lv9oMjv_0
*******************************************************************************************
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/playlist?lis
t=RDi7lv9oMjv_0']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.08.09
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:playlist] RDi7lv9oMjv_0: Downloading Youtube mix
[download] Downloading playlist: Mix - Third Day - Soul On Fire (Official Lyric
Video)
[youtube:playlist] playlist Mix - Third Day - Soul On Fire (Official Lyric Video
): Collected 26 video ids (downloading 26 of them)
[download] Downloading video 1 of 26
******************************end of useful debug info******************************
The list is generated by youtube and has many videos, however the tool is only limited to downloading only the first 26.

the playlist is accessible through a browser only when a video url is included: https://www.youtube.com/watch?v=cka7fYhWj2E&index=1&list=RDi7lv9oMjv_0

Is there a way to get around the 26 videos limit?

I believe these lists are basically unlimited, however it would be nice to get let's say the first 1000 videos downloaded, or why not all of them until you fill your hdd

**Comment by dstftw** [comment] 2015-08-11 20:01
Duplicate of #3837.

**Closed by dstftw** 2015-08-11 20:01 UTC
