### ISSUE TITLE
Certificate verify failed (_ssl.c:590)

### ISSUE THREAD

**Issue by Rejerf** [rg3/youtube-dl#7379] opened 2015-11-05 21:20 UTC
Using every version of yt-dl released in the past 3 weeks, any link. What gives?

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=_64g0z-o5BI']
[debug] Encodings: locale cp1250, fs mbcs, out None, pref cp1250
[debug] youtube-dl version 2015.11.02
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-71839-g6197672
[debug] Proxy map: {}
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)> (caused by URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))
  File "youtube_dl\extractor\common.pyo", line 329, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1873, in urlopen
  File "urllib2.pyo", line 431, in open
  File "urllib2.pyo", line 449, in _open
  File "urllib2.pyo", line 409, in _call_chain
  File "youtube_dl\utils.pyo", line 794, in https_open
  File "urllib2.pyo", line 1197, in do_open

**Comment by jaimeMF** [comment] 2015-11-05 22:45
Duplicate of #7309

**Closed by jaimeMF** 2015-11-05 22:45 UTC
