### ISSUE TITLE
Mixcloud playlist download fails

### ISSUE THREAD

**Issue by adyton** [rg3/youtube-dl#7292] opened 2015-10-25 03:57 UTC
youtube-dl --verbose https://www.mixcloud.com/LiquidLounge/playlists/dubby-rhythms
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.mixcloud.com/LiquidLounge/playlists/dubby-rhythms']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.24
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8.1, ffprobe 2.8.1
[debug] Proxy map: {}
[mixcloud] LiquidLounge-playlists: Downloading webpage
[mixcloud] LiquidLounge-playlists: Trying mp3 URL
[mixcloud] LiquidLounge-playlists: Trying m4a URL
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 291, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/mixcloud.py", line 77, in _real_extract
    PREFIX + r'm-title="([^"]+)"', webpage, 'title')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 594, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 585, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment] 2015-10-25 13:59
Duplicate of #5272.

**Closed by dstftw** 2015-10-25 13:59 UTC
