### ISSUE TITLE
Unable to download from Viafree.no

### ISSUE THREAD

**Issue by MrDemocracy** [rg3/youtube-dl#14402] opened 2017-10-03 19:55 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl --all-subs --write-sub  --convert-subs srt  --embed-subs https://www.viafree.no/programmer/underholdning/aber-bergen -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--all-subs', '--write-sub', '--convert-subs', 'srt', '--embed-subs', 'https://www.viafree.no/programmer/underholdning/aber-bergen', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.08.27.1
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-87095-gef0c6d9, ffprobe N-87095-gef0c6d9
[debug] Proxy map: {}
[Viafree] aber-bergen: Downloading webpage
WARNING: [Viafree] aber-bergen: Failed to parse JSON Expecting ',' delimiter: line 1 column 15632 (char 15631)
[mtg] 875697: Downloading video JSON
[mtg] 875697: Downloading streams JSON
[mtg] 875697: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://mtgxno01-vh.akamaihd.net/i/201709/21/aa70ebc163820be7aab1feccc9a88777_73ad3d3a_,260,460,900,1800,2800,.mp4.csmil/index_4_av.m3u8?null=0&id=AgBYWXPSwdSqwoDo01k3QBd1otfC6hkkmxwGYPXH+KZjyPyAHMfobbR5dMCDeAPGv6g072GsVMrkcg%3d%3d&hdntl=exp=1507146240~acl=%2f*~data=hdntl~hmac=3d66af84f997b2a7ff9e6be1ecfb781872ea8a3eeaaaa979121534bfea06b70f'
[download] Melk - Ep. 16-875697.mp4 has already been downloaded
[download] 100% of 242.64MiB
[debug] ffmpeg command line: ffprobe -show_streams "file:Melk - Ep. 16-875697.mp4"
[ffmpeg] Fixing malformed AAC bitstream in "Melk - Ep. 16-875697.mp4"
[debug] ffmpeg command line: ffmpeg -y -i "file:Melk - Ep. 16-875697.mp4" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:Melk - Ep. 16-875697.temp.mp4"
[ffmpeg] There aren't any subtitles to convert
[ffmpeg] There aren't any subtitles to embed
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.viafree.no/programmer/underholdning/aber-bergen/sesong-2/episode-1
- Playlist: https://www.viafree.no/programmer/underholdning/aber-bergen/

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I'm trying to download all episodes of the norwegian series called Aber Bergen. When I try to do this, youtube-dl downloads episode 16 of another series called "Melk".

**Comment by dstftw** [comment] 2017-10-03 20:47
Duplicate of #12686.

**Closed** 2017-10-03 20:47 UTC

**Comment by MrDemocracy** [comment] 2017-10-03 21:49
Oops, sorry. I searched for "viafree.no" in the issues archive.
