### ISSUE TITLE
xhamster broken

### ISSUE THREAD

**Issue by maxya** [rg3/youtube-dl#6976] opened 2015-09-26 01:52 UTC
youtube-dl --verbose http://xhamster.com/movies/4310437/amateur_wife_deep_fisted_until_she_squirts.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://xhamster.com/movies/4310437/amateur_wife_deep_fisted_until_she_squirts.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.22
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.2
[debug] exe versions: ffmpeg 2.6.4, ffprobe 2.6.4, rtmpdump 2.4
[debug] Proxy map: {}
[XHamster] 4310437: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/bob/.bin/youtube-dl/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "/home/bob/.bin/youtube-dl/youtube_dl/extractor/common.py", line 287, in extract
    return self._real_extract(url)
  File "/home/bob/.bin/youtube-dl/youtube_dl/extractor/xhamster.py", line 66, in _real_extract
    title = self._html_search_regex(r'<title>(?P<title>.+?) - xHamster\.com</title>', webpage, 'title')
  File "/home/bob/.bin/youtube-dl/youtube_dl/extractor/common.py", line 590, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/home/bob/.bin/youtube-dl/youtube_dl/extractor/common.py", line 581, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

> curl -I http://xhamster.com/movies/4310437/amateur_wife_deep_fisted_until_she_squirts.html
HTTP/1.1 200 OK
Server: nginx/1.8.0
Date: Sat, 26 Sep 2015 01:52:17 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding
X-Powered-By: PHP/5.6.12

**Comment by dstftw** [comment] 2015-09-26 05:27
Duplicate of #6944.

**Closed by dstftw** 2015-09-26 05:27 UTC
