### ISSUE TITLE
Can't download video from ABC iview.

### ISSUE THREAD

**Issue by BlueHippo73** [rg3/youtube-dl#18257] opened 2018-11-20 09:26 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.18**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ x] Question
- [ ] Other

---

---

---

---

This is my first time using youtube-dl. I'm trying to download a video from ABC iview (using the steps shown in this tutorial video https://www.youtube.com/watch?v=fKe9rV-gl1c), but, I get the error message "ERROR: Unsupported URL".
The video I'm trying to download is https://iview.abc.net.au/show/christmas-with-poh
Am I doing something wrong? Any help would be appreciated.
Thank you.

**Comment by remitamine** [comment] 2018-11-20 09:42
Duplicate of #16868

**Closed by remitamine** 2018-11-20 09:42 UTC
