### ISSUE TITLE
Japanese and other languages Unicode under Windows 7

### ISSUE THREAD

**Issue by computerfreak105** [rg3/youtube-dl#5827] opened 2015-05-27 13:04 UTC
Hi! Is there a possibility that youtube-dl can write Japanese, Russian, Korean and other such languages in folder and file names? When ever I download a channel with such letters they aren't written. This also results in youtube-dl being unable to create a directory for a channel if it contains foreigen language charakters.
Here an example with log report, I can provide more if needed.
I use youtube-dl on a German Windows 7 Professional. I use it very often, so this feature request would mean a lot to me.
Thanks and kind regards
Ben

G:\>youtube-dl -f 140/m4a -o g:\yt/%(uploader)s/%(title)s_%(upload_date)s.%(ext)
s -a you.txt --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-f', u'140/m4a', u'-o', u'g:\\yt/%(uploader)s/%(ti
tle)s_%(upload_date)s.%(ext)s', u'-a', u'you.txt', u'--verbose']
[debug] Batch file urls: [u'https://www.youtube.com/channel/UC_cJTHZQCEYA4KNLrQ9
tM1w']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.05.20
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:channel] UC_cJTHZQCEYA4KNLrQ9tM1w: Downloading page #1
[download] Downloading playlist: UC_cJTHZQCEYA4KNLrQ9tM1w
[youtube:channel] playlist UC_cJTHZQCEYA4KNLrQ9tM1w: Downloading 9 videos
[download] Downloading video 1 of 9
[youtube] zmYJcf4AjZg: Downloading webpage
[youtube] zmYJcf4AjZg: Extracting video information
[youtube] zmYJcf4AjZg: Downloading DASH manifest
[debug] Invoking downloader on 'https://r8---sn-nfpnnjvh-1gis.googlevideo.com/vi
deoplayback?id=ce660971fe008d98&itag=140&source=youtube&requiressl=yes&pl=22&mv=
m&ms=au&mm=31&ratebypass=yes&mime=audio/mp4&gir=yes&clen=5092496&lmt=14283930008
72330&dur=422.417&upn=dOyqx42Su90&mt=1432731226&sver=3&fexp=936118,938690,940617
5,9406987,9408142,9408420,9408710,9413503,9415304,948124,952612&key=dg_yt0&signa
ture=7472C1521BE74A65DBBCBDC3AD141824F2FC0223.7D77AAF4D43628DF77255952A38933E2E8
F22CA2&ip=188.62.60.79&ipbits=0&expire=1432752960&sparams=ip,ipbits,expire,id,it
ag,source,requiressl,pl,mv,ms,mm,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: g:\yt\\_20150407.m4a
[download] 100% of 4.86MiB in 00:01
WARNING: zmYJcf4AjZg: writing DASH m4a. Only some players support this container
. Install ffmpeg or avconv to fix this automatically.
[download] Downloading video 2 of 9
[youtube] o2MKAF5z4y4: Downloading webpage
[youtube] o2MKAF5z4y4: Extracting video information
[youtube] o2MKAF5z4y4: Downloading DASH manifest
[debug] Invoking downloader on 'https://r4---sn-nfpnnjvh-1gis.googlevideo.com/vi
deoplayback?id=a3630a005e73e32e&itag=140&source=youtube&requiressl=yes&mm=31&ms=
au&pl=22&mv=m&ratebypass=yes&mime=audio/mp4&gir=yes&clen=8359895&lmt=14282949037
74486&dur=693.486&sver=3&key=dg_yt0&upn=mR2dnLJ136Q&fexp=936118,938690,9406175,9
406987,9408142,9408420,9408710,9413503,9415304,948124,952612&mt=1432731226&signa
ture=58BB3F050E3D8568354EBA9E15D4549229ECB544.21C1855FD901ACAAB1C36EAAC869907D4A
6F8884&ip=188.62.60.79&ipbits=0&expire=1432752962&sparams=ip,ipbits,expire,id,it
ag,source,requiressl,mm,ms,pl,mv,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: g:\yt\\_20150405.m4a
[download] 100% of 7.97MiB in 00:03
WARNING: o2MKAF5z4y4: writing DASH m4a. Only some players support this container
. Install ffmpeg or avconv to fix this automatically.
[download] Downloading video 3 of 9
[youtube] xpXTIoJdj5k: Downloading webpage
[youtube] xpXTIoJdj5k: Extracting video information
[youtube] xpXTIoJdj5k: Downloading DASH manifest
[debug] Invoking downloader on 'https://r6---sn-nfpnnjvh-1gis.googlevideo.com/vi
deoplayback?id=c695d322825d8f99&itag=140&source=youtube&requiressl=yes&ms=au&mv=
m&mm=31&pl=22&ratebypass=yes&mime=audio/mp4&gir=yes&clen=7400987&lmt=14279316291
70913&dur=613.935&fexp=936118,938690,9406175,9406987,9408142,9408420,9408710,941
3503,9415304,948124,952612&mt=1432731226&sver=3&signature=01C2F7F60657BF6D973D46
15A892FBC54238C007.36ECD5FBDA0E03E7CBB2B894E9A0D576A1812236&upn=3ZPCYKOWWu8&key=
dg_yt0&ip=188.62.60.79&ipbits=0&expire=1432752966&sparams=ip,ipbits,expire,id,it
ag,source,requiressl,ms,mv,mm,pl,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: g:\yt\\         _20150401.m4a
[download] 100% of 7.06MiB in 00:02
WARNING: xpXTIoJdj5k: writing DASH m4a. Only some players support this container
. Install ffmpeg or avconv to fix this automatically.
[download] Downloading video 4 of 9
[youtube] KZxpbIP2zVc: Downloading webpage
[youtube] KZxpbIP2zVc: Extracting video information
[youtube] KZxpbIP2zVc: Downloading DASH manifest
[debug] Invoking downloader on 'https://r5---sn-nfpnnjvh-1gis.googlevideo.com/vi
deoplayback?id=299c696c83f6cd57&itag=140&source=youtube&requiressl=yes&mm=31&pl=
22&ms=au&mv=m&ratebypass=yes&mime=audio/mp4&gir=yes&clen=10011001&lmt=1427763030
745495&dur=830.461&upn=38a_MgWUNtY&mt=1432731226&fexp=936118,938690,9406175,9406
987,9408142,9408420,9408710,9413503,9415304,948124,952612&key=dg_yt0&sver=3&sign
ature=84C6A8233CCF946F8A9A24B6C721CB3963CCD635.0A28716D2EE307F4C8A9CD05E7DBA199C
5CD87E2&ip=188.62.60.79&ipbits=0&expire=1432752970&sparams=ip,ipbits,expire,id,i
tag,source,requiressl,mm,pl,ms,mv,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: g:\yt\\_20150330.m4a
[download] 100% of 9.55MiB in 00:03
WARNING: KZxpbIP2zVc: writing DASH m4a. Only some players support this container
. Install ffmpeg or avconv to fix this automatically.
[download] Downloading video 5 of 9
[youtube] vwnZUZ1VaOw: Downloading webpage
[youtube] vwnZUZ1VaOw: Extracting video information
[youtube] vwnZUZ1VaOw: Downloading DASH manifest
[debug] Invoking downloader on 'https://r2---sn-nfpnnjvh-1gis.googlevideo.com/vi
deoplayback?id=bf09d9519d5568ec&itag=140&source=youtube&requiressl=yes&pl=22&mm=
31&ms=au&mv=m&ratebypass=yes&mime=audio/mp4&gir=yes&clen=9525115&lmt=14275865054
01775&dur=790.151&signature=5075BFFC54373D28C0426CF3AC25FD87111172EE.02A7C52A4E6
C946E2B2DDCF504FC6B6444567881&fexp=936118,938690,9406175,9406987,9408142,9408420
,9408710,9413503,9415304,948124,952612&sver=3&key=dg_yt0&mt=1432731344&upn=-VIlk
A99Bho&ip=188.62.60.79&ipbits=0&expire=1432752974&sparams=ip,ipbits,expire,id,it
ag,source,requiressl,pl,mm,ms,mv,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: g:\yt\\_20150328.m4a
[download] 100% of 9.08MiB in 00:03
WARNING: vwnZUZ1VaOw: writing DASH m4a. Only some players support this container
. Install ffmpeg or avconv to fix this automatically.
[download] Downloading video 6 of 9
[youtube] TTcq8xJBqhE: Downloading webpage
[youtube] TTcq8xJBqhE: Extracting video information
[youtube] TTcq8xJBqhE: Downloading DASH manifest
[debug] Invoking downloader on 'https://r2---sn-nfpnnjvh-1gis.googlevideo.com/vi
deoplayback?id=4d372af31241aa11&itag=140&source=youtube&requiressl=yes&mv=m&mm=3
1&ms=au&pl=22&ratebypass=yes&mime=audio/mp4&gir=yes&clen=6806032&lmt=14273370209
69584&dur=564.569&sver=3&signature=75CA0E066BC23E3C5A8294F06D9AA52ED3410D87.2A3B
2D907635032A782C28227820123C9DB5CEBE&fexp=936118,938690,9406175,9406987,9408142,
9408420,9408710,9413503,9415304,948124,952612&mt=1432731344&upn=AOpSiwpKl-Q&key=
dg_yt0&ip=188.62.60.79&ipbits=0&expire=1432752978&sparams=ip,ipbits,expire,id,it
ag,source,requiressl,mv,mm,ms,pl,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: g:\yt\\_20150325.m4a
[download] 100% of 6.49MiB in 00:02
WARNING: TTcq8xJBqhE: writing DASH m4a. Only some players support this container
. Install ffmpeg or avconv to fix this automatically.
[download] Downloading video 7 of 9
[youtube] jNOVM_7UKrY: Downloading webpage
[youtube] jNOVM_7UKrY: Extracting video information
[youtube] jNOVM_7UKrY: Downloading DASH manifest
[debug] Invoking downloader on 'https://r3---sn-nfpnnjvh-1gis.googlevideo.com/vi
deoplayback?id=8cd39533fed42ab6&itag=140&source=youtube&requiressl=yes&ms=au&mv=
m&pl=22&mm=31&ratebypass=yes&mime=audio/mp4&gir=yes&clen=8556353&lmt=14252793845
32804&dur=709.786&mt=1432731344&fexp=936118,938690,9406175,9406987,9408142,94084
20,9408710,9413503,9415304,948124,952612&upn=M4XQO40S0to&sver=3&signature=583A2C
4F8BA4A8148E13119EE03E8EF4B639C60E.1D7762F517F1812F22993A38F223CB622D3A52AE&key=
dg_yt0&ip=188.62.60.79&ipbits=0&expire=1432752981&sparams=ip,ipbits,expire,id,it
ag,source,requiressl,ms,mv,pl,mm,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: g:\yt\\_20150301.m4a
[download] 100% of 8.16MiB in 00:03
WARNING: jNOVM_7UKrY: writing DASH m4a. Only some players support this container
. Install ffmpeg or avconv to fix this automatically.
[download] Downloading video 8 of 9
[youtube] LkbiFGq8qcU: Downloading webpage
[youtube] LkbiFGq8qcU: Extracting video information
[youtube] LkbiFGq8qcU: Downloading DASH manifest
[debug] Invoking downloader on 'https://r1---sn-nfpnnjvh-1gis.googlevideo.com/vi
deoplayback?id=2e46e2146abca9c5&itag=140&source=youtube&requiressl=yes&pl=22&mm=
31&mv=m&ms=au&ratebypass=yes&mime=audio/mp4&gir=yes&clen=6859432&lmt=14243415669
62712&dur=569.004&sver=3&signature=48F80C8A9BDCFD434D53CED387F758D8BD064318.0A72
ADAB1FC11F3D8B52B236C05A855BA2AC6320&key=dg_yt0&mt=1432731344&upn=PZU3qxS64OE&fe
xp=936118,938690,9406175,9406987,9408142,9408420,9408710,9413503,9415304,948124,
952612&ip=188.62.60.79&ipbits=0&expire=1432752985&sparams=ip,ipbits,expire,id,it
ag,source,requiressl,pl,mm,mv,ms,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: g:\yt\\   _20150219.m4a
[download] 100% of 6.54MiB in 00:02
WARNING: LkbiFGq8qcU: writing DASH m4a. Only some players support this container
. Install ffmpeg or avconv to fix this automatically.
[download] Downloading video 9 of 9
[youtube] kTczwv4aQoo: Downloading webpage
[youtube] kTczwv4aQoo: Extracting video information
[youtube] kTczwv4aQoo: Downloading DASH manifest
[debug] Invoking downloader on 'https://r7---sn-nfpnnjvh-1gis.googlevideo.com/vi
deoplayback?id=913733c2fe1a428a&itag=140&source=youtube&requiressl=yes&mv=m&pl=2
2&mm=31&ms=au&ratebypass=yes&mime=audio/mp4&gir=yes&clen=5651082&lmt=14243412360
00218&dur=468.763&signature=4366D32FD3E80C17F25FAB342AC9DF59EE9260E5.9428970DC3E
75423299569DE5361EE9CFBB6383F&key=dg_yt0&mt=1432731344&sver=3&fexp=936118,938690
,9406175,9406987,9408142,9408420,9408710,9413503,9415304,948124,952612&upn=xJhRi
fLn0us&ip=188.62.60.79&ipbits=0&expire=1432752988&sparams=ip,ipbits,expire,id,it
ag,source,requiressl,mv,pl,mm,ms,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: g:\yt\\_20150219.m4a
[download] 100% of 5.39MiB in 00:02
WARNING: kTczwv4aQoo: writing DASH m4a. Only some players support this container
. Install ffmpeg or avconv to fix this automatically.

G:\>

**Comment by dstftw** [comment] 2015-05-27 14:47
Duplicate of #5045.
This is intentional behavior for now. See #4787 for the rationale and #5527 for alternative solution discussions.

**Closed by dstftw** 2015-05-27 14:47 UTC
