### ISSUE TITLE
Make --no-mtime default?

### ISSUE THREAD

**Issue by NickSto** [rg3/youtube-dl#14972] opened 2017-12-13 11:10 UTC
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

Do the developers have an opinion on turning on `--no-mtime` by default?

It's difficult to search for this, so I don't know if this debate has already occurred (I figure it has).

I went years without realizing youtube-dl was artificially setting the date modifieds on my videos to the upload date. It wasn't until I was trawling through the list of options and saw `--no-mtime` that I realized what happened.

I really like to have a record of when I first found and downloaded a video, and now there's years of videos I've saved where I have no idea what period of my life they're from. The worst part is, it poisoned the date modifieds on all the videos downloaded before that as well. If I see a video with a date from before that period, I don't know if it's actually from then, or if it's one downloaded with youtube-dl with a date that artificially put it back then.

I understand some people like to organize their videos with date modifieds set by the upload date, and that's fine. But I feel like that being the default violates the principle of least surprise, since the vast majority of tools don't operate that way. And it can cause a lot of damage, as I described.

I also understand that suddenly changing defaults can cause even more surprise, so I'm not sure if there's a solution at this point. But I'd love to hear thoughts on this.

**Comment by dstftw** [comment] 2017-12-13 15:34
Duplicate of #1709.

**Closed by dstftw** 2017-12-13 15:34 UTC

**Comment by NickSto** [comment] 2017-12-13 16:28
@dstftw Thanks! I figured this must've come up before, but I couldn't find it.

**Comment by NickSto** [comment] 2020-01-05 01:58
I saw #1709 was just locked down, but I couldn't tell if there was any response or position taken by the developers.

Just so we know what to expect, are they open to it, not decided, or a definite `WONTFIX`? Or should I just submit a pull request and see how it shakes out?
