### ISSUE TITLE
downloading from dailymotion is very slow ..

### ISSUE THREAD

**Issue by shahzadakram** [rg3/youtube-dl#3819] opened 2014-09-23 15:49 UTC
I tried many videos from dailymotion and feel its very slow for downloading videos from dailymotion .. but its works for all other website very good. ... can you please check it may be some thing can make it better .

Thanks

**Comment by pavs** [comment] 2015-02-11 09:41
Having the same issue with dailymotion download speed doesn't go over 150kbps. I am on a 500mbps connection.

**Comment by mbnoimi** [comment] 2015-06-08 14:58
+1

This issue occurs only on DailyMotion but in addition to slow downloading I experience false download done!

I'm using
Linux Mint 17.1 x64
youtube-dl 2015.05.20

PS. When I tried to upgrade to recant version (2015.06.04.1) I get the following output:
```
# pip install --upgrade youtube-dl
Requirement already up-to-date: youtube-dl in /usr/local/lib/python2.7/dist-packages
# youtube-dl --version
2015.05.20
```

**Comment by Artymort** [comment] 2015-06-29 20:51
A little update on this, I noticed that the first few seconds of download on [Dailymotion](http://www.dailymotion.com/video/xvel9v_episode-1-alone-on-the-wall_lifestyle) are quite satisfactory (around 6MiB/s here) and as soon as you get around 1.5% at max speed, the download speed slows down drastically.

As youtube-dl is able to resume, I used this to "hack" the download by cancelling/starting/cancelling/starting/... and it works but it takes a while and is quite annoying. I don't know how to patch it, but starting new downloads often seems to bypass what I think is a way for them to save bandwidth: *never give you more than you could watch*.

Two consecutive traces (~30 seconds interval, the first one was just after the download resumed):
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '-f', 'hd', 'http://www.dailymotion.com/video/xvel9v_episode-1-alone-on-the-wall_lifestyle']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 3.4.3 - Linux-4.0.5-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.7.1, ffprobe 2.7.1, rtmpdump 2.4
[debug] Proxy map: {'https': 'http://127.0.0.1:8118/', 'http': 'http://127.0.0.1:8118/'}
[dailymotion] xvel9v: Downloading webpage
[dailymotion] xvel9v: Extracting information
[dailymotion] xvel9v: Downloading embed page
[debug] Invoking downloader on 'https://www.dailymotion.com/cdn/H264-1280x720/video/xvel9v.mp4?auth=1435783659-2562-a66resg0-e6c24b7caf0043d2b7eb2c8fc1a9c5f8'
[download] Resuming download at byte 592649822
[download] Destination: Episode 1 - Alone On The Wall-xvel9v.mp4
[download]  61.3% of 928.88MiB at  5.50MiB/s ETA 01:05
```

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '-f', 'hd', 'http://www.dailymotion.com/video/xvel9v_episode-1-alone-on-the-wall_lifestyle']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 3.4.3 - Linux-4.0.5-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.7.1, ffprobe 2.7.1, rtmpdump 2.4
[debug] Proxy map: {'https': 'http://127.0.0.1:8118/', 'http': 'http://127.0.0.1:8118/'}
[dailymotion] xvel9v: Downloading webpage
[dailymotion] xvel9v: Extracting information
[dailymotion] xvel9v: Downloading embed page
[debug] Invoking downloader on 'https://www.dailymotion.com/cdn/H264-1280x720/video/xvel9v.mp4?auth=1435783659-2562-a66resg0-e6c24b7caf0043d2b7eb2c8fc1a9c5f8'
[download] Resuming download at byte 592649822
[download] Destination: Episode 1 - Alone On The Wall-xvel9v.mp4
[download]  62.5% of 928.88MiB at 446.82KiB/s ETA 13:17
```

Sorry for the local proxy thing, I'm using privoxy as an ad-free tool, I don't think it changes anything on the download speed.

**Comment by sebma** [comment] 2015-07-17 16:15
Hi, I have also the same pb. with dailymotion download speed.

What do you think that can be done to solve this issue ?

**Comment by Zopieux** [comment] 2015-11-18 18:02
Having the same issue. I guess Dailymotion uses some kind of token bucket to throttle their upload rate. A possible workaround would be to automatize the stop-and-restart approach explained by @Artymort.

**Comment by daga68** [comment] 2016-07-16 06:50
Hi, I am experiencing the same issue with dailymotion.

I am downloading tons of "Regular Show" cartoon for my kid and at the very begging is way fast,
but beyond 1.5% the speed drops down.

Any trick yet?

**Comment by PannenkoekenNL** [comment] 2016-09-05 12:11
I have exactly the same problem with the latest version.

**Comment by yan12125** [comment] 2016-09-05 14:48
@PannenkoekenNL Could you give your video URL?

**Comment by PannenkoekenNL** [comment] 2016-09-05 15:02
@yan12125 For example this ones:
http://www.dailymotion.com/video/x3m1qro_crayon-shin-chan-call-me-pencil-shinchan_fun
http://www.dailymotion.com/video/x3m9dw9_crayon-shin-chan-fighting-with-kazama_fun
http://www.dailymotion.com/video/x3m9eg3_crayon-shin-chan-a-present-for-miss-nanako_fun
http://www.dailymotion.com/video/x3m9eza_crayon-shin-chan-i-broke-the-glass_fun

**Comment by yan12125** [comment] 2016-09-05 15:57
Just tried http://www.dailymotion.com/video/x3m1qro_crayon-shin-chan-call-me-pencil-shinchan_fun. On the webpage HLS is used, while in youtube-dl the default format is HTTP. This command can be used to download the HLS format:
```
youtube-dl -v -f 'best[format_id^=hls]' "http://www.dailymotion.com/video/x3m1qro_crayon-shin-chan-call-me-pencil-shinchan_fun" --hls-prefer-native
```
Here ```--hls-prefer-native``` is necessary due to a ffmpeg bug.

Closing as download speed is beyond the scope of youtube-dl.

**Closed by yan12125** 2016-09-05 15:57 UTC

**Comment by sd65** [comment] 2018-07-10 15:30
Commenting here even if the issue is closed, I do understand that's it's not an youtube-dl bug but I want to help by providing a trick mentionned by @Artymort.

Dailymotion still trottle the download after 10 seconds, so you stop & relaunch youtube-dl... every 10 seconds. I had good results!

An easy way to it with a modern shell (zsh, bash, maybe others implementing `timeout`) is:
```
while :; do timeout 10 youtube-dl https://www.dailymotion.com/video/xxxxxxx; done
```
