### ISSUE TITLE
Can't download a video -> Got server HTTP error

### ISSUE THREAD

**Issue by gise88** [rg3/youtube-dl#11816] opened 2017-01-23 03:35 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.22*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.22**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v -x --audio-format 'mp3' https://www.youtube.com/watch?v=FfbZfBk-3rI
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-x', '--audio-format', 'mp3', 'https://www.youtube.com/watch?v=FfbZfBk-3rI']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.01.22
[debug] Python version 3.6.0 - Linux-4.8.13-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] FfbZfBk-3rI: Downloading webpage
[youtube] FfbZfBk-3rI: Downloading video info webpage
[youtube] FfbZfBk-3rI: Extracting video information
[youtube] FfbZfBk-3rI: Downloading MPD manifest
[debug] Invoking downloader on 'https://r4---sn-8vq54voxpu-ca9e.googlevideo.com/videoplayback?id=15f6d97c193edeb2&itag=251&source=youtube&requiressl=yes&usequic=no&initcwndbps=1705000&pcm2cms=yes&mn=sn-8vq54voxpu-ca9e&mm=31&ms=au&mv=m&pl=24&ratebypass=yes&mime=audio/webm&gir=yes&clen=16527868&lmt=1413354951380275&dur=655.621&mt=1485141339&upn=_-tAJUzMJU4&signature=1B480A803DB03ED8F1BFA89C23E6A32A8D770453.83F774C55FD98DE678D0ABD69EDF9EC536028A3C&key=dg_yt0&ip=188.218.87.187&ipbits=0&expire=1485163126&sparams=ip,ipbits,expire,id,itag,source,requiressl,usequic,initcwndbps,pcm2cms,mn,mm,ms,mv,pl,ratebypass,mime,gir,clen,lmt,dur'
[download] Got server HTTP error. Retrying (attempt 1 of 10)...
[download] Got server HTTP error. Retrying (attempt 2 of 10)...
[download] Got server HTTP error. Retrying (attempt 3 of 10)...
[download] Got server HTTP error. Retrying (attempt 4 of 10)...
[download] Got server HTTP error. Retrying (attempt 5 of 10)...
[download] Got server HTTP error. Retrying (attempt 6 of 10)...
[download] Got server HTTP error. Retrying (attempt 7 of 10)...
[download] Got server HTTP error. Retrying (attempt 8 of 10)...
[download] Got server HTTP error. Retrying (attempt 9 of 10)...
[download] Got server HTTP error. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries
  File "/usr/bin/youtube-dl", line 11, in <module>
    load_entry_point('youtube-dl==2017.1.22', 'console_scripts', 'youtube-dl')()
  File "/usr/lib/python3.6/site-packages/youtube_dl/__init__.py", line 444, in main
    _real_main(argv)
  File "/usr/lib/python3.6/site-packages/youtube_dl/__init__.py", line 434, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1791, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 705, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 751, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1435, in process_video_result
    self.process_info(new_info)
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1699, in process_info
    success = dl(filename, info_dict)
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1641, in dl
    return fd.download(name, info)
  File "/usr/lib/python3.6/site-packages/youtube_dl/downloader/common.py", line 353, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python3.6/site-packages/youtube_dl/downloader/http.py", line 131, in real_download
    self.report_error('giving up after %s retries' % retries)
  File "/usr/lib/python3.6/site-packages/youtube_dl/downloader/common.py", line 162, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 568, in report_error
    self.trouble(error_message, tb)
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 530, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

...
<end of log>
```

### Description of your *issue*, suggested solution and other information

Just trying to download and extract the audio from this youtube link (`https://www.youtube.com/watch?v=FfbZfBk-3rI`) but I got `Got server HTTP error`.
As you can see I'm using Arch Linux with the latest version of Youtube-dl.
I can see the video either with Firefox or with chrome..

**Comment by dstftw** [comment] 2017-01-23 15:30
Duplicate of #3721.

**Closed by dstftw** 2017-01-23 15:30 UTC
