### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by bismoy2013** [rg3/youtube-dl#6620] opened 2015-08-20 04:53 UTC
youtube-dl https://www.youtube.com/watch?v=X46t8ZFqUB4
[youtube] X46t8ZFqUB4: Downloading webpage
[youtube] X46t8ZFqUB4: Downloading video info webpage
[youtube] X46t8ZFqUB4: Extracting video information
[youtube] X46t8ZFqUB4: Downloading DASH manifest
WARNING: [youtube] X46t8ZFqUB4: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
ERROR: unable to download video data: HTTP Error 403: Forbidden

**Comment by yan12125** [comment] 2015-08-20 05:15
Duplicate of #6451. Remove the cache with ```youtube-dl --rm-cache-dir``` and try again.

**Closed by yan12125** 2015-08-20 05:15 UTC

**Comment by bismoy2013** [comment] 2015-08-20 05:19
Thanks
