### ISSUE TITLE
Site Support Request : VideoTanker

### ISSUE THREAD

**Issue by jayesh100** [rg3/youtube-dl#5044] opened 2015-02-24 00:36 UTC
Hi guys could you please support VideoTanker as well? The URL template is;
http://videotanker.co/player/embed_player.php?vid=#ID#
Where #ID# is a 5 digit video number (e.g. 91912). It can optionally be followed by parameters for height, width, etc : <code>&width=506&height=400&autoplay=no</code>, but youtube-dl already removes the parameters.
The above link's html source reveals the location of the Video, 
<code>var hq_video_file = 'http://server2.videotanker.co/files/videos/2015/02/19/14243813639bc64-hd.mp4';
var normal_video_file = 'http://server2.videotanker.co/files/videos/2015/02/19/14243813639bc64.flv';
</code>
But there is one catch; not every video has a HQ Video (e.g. the one above only has a "normal video", the hq video leads to a 404).

Thanks a lot and keep up the good work!!!

**Comment by phihag** [comment] 2015-02-24 10:24
Can you name an [example URL](https://yt-dl.org/example-url)? Please note that youtube-dl only supports sites that do not infringe copyright, so the the example URL must not infringe copyright.

**Comment by naglis** [comment] 2015-02-24 11:48
Duplicate of: #3871.

**Closed by naglis** 2015-02-24 11:48 UTC
