### ISSUE TITLE
Fails to download from CrunchyRoll [Ubuntu 14.04]

### ISSUE THREAD

**Issue by majorcyto** [rg3/youtube-dl#6080] opened 2015-06-25 05:10 UTC
I have been trying to get this to work with crunchyroll for a few hours, im not sure what else to do.

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-v', u'http://www.crunchyroll.com/akame-ga-kill/episode-1-kill-the-darkness-656895']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2015.06.15
[debug] Python version 2.7.6 - Linux-2.6.32-042stab094.7-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, rtmpdump 2.4
[debug] Proxy map: {}
[Crunchyroll] Logging in
[Crunchyroll] 656895: Downloading webpage
[Crunchyroll] 656895: Downloading media info
[Crunchyroll] 656895: Downloading media info for 360p
[Crunchyroll] 656895: Downloading media info for 480p
[Crunchyroll] 656895: Downloading media info for 720p
[Crunchyroll] 656895: Downloading media info for 1080p
[debug] Invoking downloader on 'rtmpe://c2fs.fplive.net/c2?nvb=20150625050746&nva=20150625090846&token=0e0b55c3813f534a3a635'
[download] Destination: Akame ga Kill! Episode 1  Kill the Darkness-656895.flv
[debug] rtmpdump command line: rtmpdump --verbose -r 'rtmpe://c2fs.fplive.net/c2?nvb=20150625050746&nva=20150625090846&token=0e0b55c3813f534a3a635' -o 'Akame ga Kill! Episode 1  Kill the Darkness-656895.flv.part' --playpath mp4:s/ve1440923/video.mp4 --resume --skip 1
[rtmpdump] RTMPDump v2.4 a107cef~git
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : c2fs.fplive.net
[rtmpdump] DEBUG: Parsed app     : c2?nvb=20150625050746&nva=20150625090846&token=0e0b55c3813f534a3a635
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : c2fs.fplive.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:s/ve1440923/video.mp4
[rtmpdump] DEBUG: tcUrl    : rtmpe://c2fs.fplive.net:1935/c2?nvb=20150625050746&nva=20150625090846&token=0e0b55c3813f534a3a635
[rtmpdump] DEBUG: app      : c2?nvb=20150625050746&nva=20150625090846&token=0e0b55c3813f534a3a635
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 0 bytes
[rtmpdump] RTMPDump v2.4 a107cef~git
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : c2fs.fplive.net
[rtmpdump] DEBUG: Parsed app     : c2?nvb=20150625050746&nva=20150625090846&token=0e0b55c3813f534a3a635
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : c2fs.fplive.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:s/ve1440923/video.mp4
[rtmpdump] DEBUG: tcUrl    : rtmpe://c2fs.fplive.net:1935/c2?nvb=20150625050746&nva=20150625090846&token=0e0b55c3813f534a3a635
[rtmpdump] DEBUG: app      : c2?nvb=20150625050746&nva=20150625090846&token=0e0b55c3813f534a3a635
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.


ERROR: rtmpdump exited with code 1
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 405, in main
    _real_main(argv)
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 395, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1502, in download
    res = self.extract_info(url)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 707, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1173, in process_video_result
    self.process_info(new_info)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1435, in process_info
    success = dl(filename, info_dict)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1377, in dl
    return fd.download(name, info)
  File "/usr/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/bin/youtube-dl/youtube_dl/downloader/rtmp.py", line 202, in real_download
    self.report_error('rtmpdump exited with code %d' % retval)
  File "/usr/bin/youtube-dl/youtube_dl/downloader/common.py", line 155, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 528, in report_error
    self.trouble(error_message, tb)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 490, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
```

**Comment by dstftw** [comment] 2015-06-25 14:10
Duplicate of #5881.

**Closed by dstftw** 2015-06-25 14:10 UTC
