### ISSUE TITLE
Skipping DASH manifest: ExtractorError

### ISSUE THREAD

**Issue by ccjunior9** [rg3/youtube-dl#6352] opened 2015-07-24 17:28 UTC
What I get:
"WARNING: [youtube] yOaoUx0Mc0Q: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)"
····
~$ youtube-dl -U
youtube-dl is up-to-date (2015.07.21)

**Comment by jaimeMF** [comment] 2015-07-24 17:41
Duplicate of #5118, it will be fixed in the next version.

For future reports, please post the full output a explained in the error message.

**Closed by jaimeMF** 2015-07-24 17:41 UTC
