### ISSUE TITLE
--ap-mso and --cookies no longer work with aenetworks (History Channel) or Discovery Networks [Comcast / DIRECTV]

### ISSUE THREAD

**Issue by Mr-Jake** [rg3/youtube-dl#15198] opened 2018-01-08 23:59 UTC
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.07*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

**--ap-mso Comcast_SSO**
```
C:\youtube-dl.exe "http://www.history.com/shows/pawn-stars/season-15/episode-1" --ap-mso Comcast_SSO --ap-username REMOVED --ap-password REMOVED -F -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://www.history.com/shows/pawn-stars/season-15/e
pisode-1', '--ap-mso', 'Comcast_SSO', '--ap-username', 'PRIVATE', '--ap-password
', 'PRIVATE', '-F', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.01.07
[debug] Python version 3.4.4 (CPython) - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg n3.3, ffprobe n3.3, rtmpdump 2.4
[debug] Proxy map: {}
[aenetworks] pawn-stars/season-15/episode-1: Downloading webpage
[aenetworks] 1072910403801: Downloading JSON metadata
[aenetworks] 1072910403801: Downloading Provider Redirect Page
ERROR: Unable to extract post url; please report this issue on https://yt-dl.org
/bug . Make sure you are using the latest version; type  youtube-dl -U  to updat
e. Be sure to call youtube-dl with the --verbose flag and include its complete o
utput.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4k56gdgt\bu
ild\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4k56gdgt\bu
ild\youtube_dl\extractor\common.py", line 438, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4k56gdgt\bu
ild\youtube_dl\extractor\aenetworks.py", line 143, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4k56gdgt\bu
ild\youtube_dl\extractor\adobepass.py", line 1448, in _extract_mvpd_auth
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4k56gdgt\bu
ild\youtube_dl\extractor\adobepass.py", line 1360, in post_form
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4k56gdgt\bu
ild\youtube_dl\extractor\common.py", line 803, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4k56gdgt\bu
ild\youtube_dl\extractor\common.py", line 794, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract post url; please report t
his issue on https://yt-dl.org/bug . Make sure you are using the latest version;
 type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose f
lag and include its complete output.
```

**--cookies**
```
C:\youtube-dl.exe "http://www.history.com/shows/pawn-stars/season-15/episode-1" --cookies "C:\youtube-dl\cookie.txt" -F -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://www.history.com/shows/pawn-stars/season-15/e
pisode-1', '--cookies', 'C:\\youtube-dl\\cookie.txt', '-F', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.01.07
[debug] Python version 3.4.4 (CPython) - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg n3.3, ffprobe n3.3, rtmpdump 2.4
[debug] Proxy map: {}
[aenetworks] pawn-stars/season-15/episode-1: Downloading webpage
[aenetworks] 1072910403801: Downloading JSON metadata
ERROR: This video is only available for users of participating TV providers. Use
 --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-use
rname and --ap-password or --netrc to provide account credentials.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4k56gdgt\bu
ild\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4k56gdgt\bu
ild\youtube_dl\extractor\common.py", line 438, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4k56gdgt\bu
ild\youtube_dl\extractor\aenetworks.py", line 143, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4k56gdgt\bu
ild\youtube_dl\extractor\adobepass.py", line 1409, in _extract_mvpd_auth
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4k56gdgt\bu
ild\youtube_dl\extractor\adobepass.py", line 1374, in raise_mvpd_required
youtube_dl.utils.ExtractorError: This video is only available for users of parti
cipating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operat
or Identifier and --ap-username and --ap-password or --netrc to provide account
credentials.
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):

History Channel:
http://www.history.com/shows/pawn-stars/season-15/episode-1

Discovery:
https://www.discovery.com/tv-shows/mythbusters/full-episodes/heads-will-roll

---

youtube-dl can no longer download videos from the History Channel (aenetworks) or the Discovery Channel that require a login. I tried both _--ap-mso Comcast_SSO --ap-username --ap-password_ and  _--cookies_ .  Both sites have worked in the past by using either --ap-mso Comcast_SSO or --cookies.

youtube-dl has no problem downloading free videos that do not require login. I can watch the login videos in my browser so I know my credentials and cookies are correct.

**Comment by HyperPlaneSubSpacePilot** [comment] 2018-01-09 21:01
Can confirm that is the case. Neither --AP-MSO or --cookies with directv login doesn't work. Free videos do.

**Comment by StevenDTX** [comment] 2018-01-11 15:57
Discovery hasn't worked since the *go sites were discontinued.

https://github.com/rg3/youtube-dl/issues/14954

**Comment by Mr-Jake** [comment] 2018-01-11 16:51
@HyperPlaneSubSpacePilot thanks for confirming. I thought the problem was limited to Comcast, but it is interesting that DirecTV does not work either. I saw in another issue that Charter was not working with  --ap-mso or --cookies.

If anyone else can test  --ap-mso or --cookies with their provider and post if it works, it might be helpful.

**Comment by remitamine** [comment] 2018-01-12 10:25
Duplicate of #11257.

**Closed by remitamine** 2018-01-12 10:25 UTC
