### ISSUE TITLE
Download playlist as one mp3 file?

### ISSUE THREAD

**Issue by orschiro** [rg3/youtube-dl#8310] opened 2016-01-24 08:45 UTC
Dear all,

youtube-dl's export and audio conversion feature for entire playlists is simply great!

One feature I am missing, however, is the option to automatically concatenate the individually downloaded and converted audio files into a single mp3 file that preserves the file position of the tracks according to the playlist. 

What is your opinion on such a feature?

Thankfully,

~Robert

**Comment by dstftw** [comment] 2016-01-24 08:49
Duplicate of #5956.

**Closed by dstftw** 2016-01-24 08:49 UTC

**Comment by orschiro** [comment] 2016-01-24 09:02
Dear @dstftw,

Thank you for referencing the already existing request!

~Robert
