### ISSUE TITLE
[Facebook] Fails to download

### ISSUE THREAD

**Issue by vxbinaca** [rg3/youtube-dl#8632] opened 2016-02-22 07:28 UTC
```
youtube-dl -v https://www.facebook.com/FetishDollEmily/videos/832207340241477
```
```
[debug] System config: []
[debug] User config: [u'--download-archive', u'~/.ytdlarchive', u'--retries', u'100', u'--no-overwrites', u'--call-home', u'--continue', u'--write-info-json', u'--write-description', u'--write-thumbnail', u'--write-annotations', u'--all-subs', u'--sub-format', u'srt', u'--convert-subs', u'srt', u'--write-sub', u'--add-metadata', u'-f', u'bestvideo+bestaudio/best', u'--merge-output-format', u'mkv', u'--embed-subs', u'--prefer-ffmpeg']
[debug] Command-line args: [u'-v', u'https://www.facebook.com/FetishDollEmily/videos/832207340241477']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.13
[debug] Python version 2.7.10 - Linux-4.2.0-27-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: ffmpeg 2.7.6-0ubuntu0.15.10.1, ffprobe 2.7.6-0ubuntu0.15.10.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Public IP address: 76.101.221.232
[facebook] 832207340241477: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError(u'instances',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 315, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/facebook.py", line 189, in _real_extract
    for item in server_js_data['instances']:
KeyError: u'instances'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 321, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'instances',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by vxbinaca** [comment] 2016-02-22 07:30
Yeah ```--ignore-config``` gives me the same result.

**Comment by yan12125** [comment] 2016-02-22 07:46
Duplicate of #8572. This is already fixed in but not included in the latest release yet.

**Closed by yan12125** 2016-02-22 07:46 UTC
