### ISSUE TITLE
unable to download youtube live stream

### ISSUE THREAD

**Issue by 2011** [rg3/youtube-dl#5754] opened 2015-05-19 22:10 UTC
This is probably a duplicate of some past bug, but I didn't see anything exactly like it.

This is a live stream (don't know if those eventually get converted to static videos).

$ youtube-dl -F 'https://www.youtube.com/watch?v=pyUCR-Sfenc'
[youtube] pyUCR-Sfenc: Downloading webpage
[youtube] pyUCR-Sfenc: Downloading video info webpage
[youtube] pyUCR-Sfenc: Extracting video information
[youtube] pyUCR-Sfenc: Downloading formats manifest
[youtube] pyUCR-Sfenc: Downloading DASH manifest
[info] Available formats for pyUCR-Sfenc:
format code  extension  resolution note
140          m4a        audio only DASH audio  144k , m4a_dash container, aac  @128k (48000Hz)
141          m4a        audio only DASH audio  272k , m4a_dash container, aac  @256k (48000Hz)
160          mp4        256x144    DASH video  124k , 15fps, video only
133          mp4        426x240    DASH video  258k , 30fps, video only
134          mp4        640x360    DASH video  616k , 30fps, video only
135          mp4        854x480    DASH video 1116k , 30fps, video only
136          mp4        1280x720   DASH video 2216k , 30fps, video only
151          mp4        72p        HLS 
132          mp4        240p       HLS 
92           mp4        240p       HLS 
93           mp4        360p       HLS 
94           mp4        480p       HLS 
95           mp4        720p       HLS  (best)

$ youtube-dl -v 'https://www.youtube.com/watch?v=pyUCR-Sfenc'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--restrict-filenames', '-o', '%(title)s-%(id)s-%(uploader)s.%(ext)s', '-w', '-v', 'https://www.youtube.com/watch?v=pyUCR-Sfenc']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.15
[debug] Python version 3.4.1 - Linux-3.18.7-x86_64-Intel-R-_Core-TM-_i5_CPU_750_@_2.67GHz
[debug] exe versions: ffmpeg 2.2.14, ffprobe 2.2.14, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] pyUCR-Sfenc: Downloading webpage
[youtube] pyUCR-Sfenc: Downloading video info webpage
[youtube] pyUCR-Sfenc: Extracting video information
[youtube] pyUCR-Sfenc: Downloading formats manifest
[youtube] pyUCR-Sfenc: Downloading DASH manifest
[debug] Invoking downloader on 'https://r6---sn-uo1-53as.googlevideo.com/videoplayback/id/pyUCR-Sfenc.2/itag/136/source/yt_live_broadcast/requiressl/yes/pmbypass/yes/playlist_type/DVR/gcr/us/ratebypass/yes/cmbypass/yes/mime/video%2Fmp4/live/1/gir/yes/fexp/920935,937412,9408142,9408583,9408707,9408710,9408768,9408787,9408855,9408941,9412773,9413053,9413138,945137,947602,948124,952612,952637,952642/key/cms1/upn/VDR1MV18GOQ/sver/3/signature/145057F75F773A31F2E23DF489D397B2E94AC592.3ABD3EB620D3DB985D5138C7466FBF9F5CCEA982/ip/123.123.123.123/ipbits/0/expire/1432094425/sparams/cmbypass,expire,gcr,gir,id,ip,ipbits,itag,live,mime,mm,mn,ms,mv,pl,playlist_type,pmbypass,ratebypass,requiressl,source/mm/32/mn/sn-uo1-53as/ms/lv/mt/1432072733/mv/u/pl/21'
ERROR: unable to download video data: HTTP Error 400: Bad Request
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1411, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1359, in dl
    return fd.download(name, info)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/downloader/http.py", line 59, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1710, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib64/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(_args)
  File "/usr/lib64/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(_args)
  File "/usr/lib64/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

**Comment by Vnr** [comment] 2015-05-20 02:52
Looks like it's a duplicate of  https://github.com/rg3/youtube-dl/issues/5703 and https://github.com/rg3/youtube-dl/issues/5545

**Comment by 2011** [comment] 2015-05-21 00:47
I have never seen the 92-95 formats (or the HSL identifier) before.

Unlike 5703, I was unable to get any of the formats while the stream was live.

**Closed** 2017-04-01 19:57 UTC
