### ISSUE TITLE
Comedy Central -> "ERROR: Unable to extract mgid"

### ISSUE THREAD

**Issue by artphotodude** [rg3/youtube-dl#7002] opened 2015-09-27 16:32 UTC
Here is the Verbose output:

------
LinuxMint:~ mintuser$ youtube-dl --verbose http://www.cc.com/full-episodes/7jsony/the-nightly-show-with-larry-wilmore-september-24--2015---pope-francis-in-nyc---deadly-selfies-season-1-ep-01112
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.cc.com/full-episodes/7jsony/the-nightly-show-with-larry-wilmore-september-24--2015---pope-francis-in-nyc---deadly-selfies-season-1-ep-01112']
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2015.09.22
[debug] Python version 2.7.8 - Darwin-8.11.0-Power_Macintosh-powerpc-32bit
[debug] exe versions: none
[debug] Proxy map: {}
[ComedyCentral] the-nightly-show-with-larry-wilmore-september-24--2015---pope-francis-in-nyc---deadly-selfies-season-1-ep-01112: Downloading webpage
ERROR: Unable to extract mgid; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/mtv.py", line 193, in _real_extract
    og_url = self._og_search_video_url(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 680, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 590, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 581, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 287, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/mtv.py", line 203, in _real_extract
    webpage, 'mgid')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 581, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract mgid; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. 
------

**Comment by dstftw** [comment] 2015-09-27 17:43
Duplicate of #6936.
This is already fixed in master and will be incorporated in the next version of youtube-dl.

**Closed by dstftw** 2015-09-27 17:43 UTC

**Comment by artphotodude** [comment] 2015-09-27 17:50
Many Thanks!  You all ROCK!
