### ISSUE TITLE
[bilibili] interface.bilibili.com_v_cdn_play -5003 checksum error

### ISSUE THREAD

**Issue by roytam1** [rg3/youtube-dl#10391] opened 2016-08-19 23:42 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.19*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.19**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -g --write-pages --proxy socks5://127.0.0.1:8124/ --verbose http://www.bilibili.com/video/av5904451/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-g', '--write-pages', '--proxy', 'socks5://127.0.0.1:8124/', '--verbose', 'http://www.bilibili.com/video/av5904451/']
[debug] Encodings: locale cp950, fs mbcs, out cp950, pref cp950
[debug] youtube-dl version 2016.08.19
[debug] Python version 3.4.4 - Windows-XP-5.1.2600-SP3
[debug] exe versions: avconv v12_dev0-3086-g0638b99, ffmpeg N-81311-g16ea0bc
[debug] Proxy map: {'http': 'socks5://127.0.0.1:8124/', 'https': 'socks5://127.0.0.1:8124/'}
ERROR: No videos found!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpppfzkhrf\build\youtube_dl\YoutubeDL.py", line 691, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpppfzkhrf\build\youtube_dl\extractor\common.py", line 347, inextract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpppfzkhrf\build\youtube_dl\extractor\bilibili.py", line 122, in _real_extract
youtube_dl.utils.ExtractorError: No videos found!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

in `9586632_http_-_interface.bilibili.com_v_cdn_play.dump`:
```
<?xml version="1.0" encoding="UTF-8"?>
<video>
	<code>-5003</code>
	<result>checksum error</result>
</video>
```
---

### Description of your *issue*, suggested solution and other information

Don't know if bilibili is updated their xml request format, and bilibili video ID `av5904451` requires Taiwan Proxy for getting URLs, but `--geo-verification-proxy` doesn't work.

**Comment by dstftw** [comment] 2016-08-19 23:51
Duplicate of #10375.

**Closed by dstftw** 2016-08-19 23:51 UTC
