### ISSUE TITLE
some youtube videos failing to download

### ISSUE THREAD

**Issue by mrbryce** [rg3/youtube-dl#14618] opened 2017-10-29 08:53 UTC
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones : 

[**_Closed xiaose opened this Issue on Oct 19, 2015 · 4 comments_**](https://github.com/rg3/youtube-dl/issues/7235)

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
PS ////////\captvty\tools> .\youtube-dl.exe -v https://www.youtube.com/watch?v=cZXWAl2epCs
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=cZXWAl2epCs']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.10.29
[debug] Python version 3.4.4 - Windows-10/////////
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[youtube] cZXWAl2epCs: Downloading webpage
[youtube] cZXWAl2epCs: Downloading video info webpage
[youtube] cZXWAl2epCs: Extracting video information
[youtube] cZXWAl2epCs: Downloading MPD manifest
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://r3---sn-25glenes.googlevideo.com/videoplayback?////////////////
[download] Resuming download at byte 29784161
[download] Destination: //////////////////////.webm
[download]  35.8% of 121.54MiB at  2.46MiB/s ETA 00:31 ERROR: unable to download video data: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1748)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\YoutubeDL.py", line 1892, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\YoutubeDL.py", line 1831, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\downloader\common.py", line 361, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\downloader\http.py", line 287, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\downloader\http.py", line 180, in download
  File "C:\Python\Python34\lib\http\client.py", line 537, in read
  File "C:\Python\Python34\lib\http\client.py", line 576, in readinto
  File "C:\Python\Python34\lib\socket.py", line 378, in readinto
  File "C:\Python\Python34\lib\ssl.py", line 748, in recv_into
  File "C:\Python\Python34\lib\ssl.py", line 620, in read
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1748)
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

https://www.youtube.com/watch?v=KciWtUav65M and https://www.youtube.com/watch?v=cZXWAl2epCs are failing during download using latest windows binary

**Comment by yan12125** [comment] 2017-10-29 13:09
Duplicate of #14139. Please move on there for further discussions.

**Closed by yan12125** 2017-10-29 13:09 UTC
