### ISSUE TITLE
Request - Multiple Config Files

### ISSUE THREAD

**Issue by jacksonedmonds** [rg3/youtube-dl#9093] opened 2016-04-06 14:27 UTC
Currently (AFAIK) you can only have a single, global config file.
I would like to be able to create a few different configs and call whichever one is relevant for the job.

For example, I would create one config for handling YouTube video downloads, one for YouTube audio downloads and one for Soundcloud downloads. I would then call the config with, for example:
`youtube-dl --config path-to-config/youtube-vid.txt URL`

Cheers.

**Comment by dstftw** [comment] 2016-05-03 12:14
Duplicate of #6745.

**Closed by dstftw** 2016-05-03 12:14 UTC
Labels: request
