### ISSUE TITLE
[NPO] NPO live doesn't download anymore since version 2015.03.09

### ISSUE THREAD

**Issue by robin007bond** [rg3/youtube-dl#5175] opened 2015-03-10 21:40 UTC
Test URL: http://www.npo.nl/live/npo-2

It doesn't work anymore unfortunately, while previous versions of youtube-dl worked fine.

Output:

```
youtube-dl http://www.npo.nl/live/npo-2 -v                                                 :(
[debug] System config: []                                           
[debug] User config: []
[debug] Command-line args: ['http://www.npo.nl/live/npo-2', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.09
[debug] Python version 3.4.3 - Linux-3.18.6-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.6, ffprobe 2.6, rtmpdump 2.4
[debug] Proxy map: {}
[npo.nl:live] npo-2: Downloading webpage
[npo.nl:live] npo-2: Downloading JSON metadata
[npo.nl:live] npo-2: Downloading token
[npo.nl:live] npo-2: Downloading hds JSON
[npo.nl:live] npo-2: Downloading hds URL
[npo.nl:live] npo-2: Downloading f4m manifest
[npo.nl:live] npo-2: Downloading hls JSON
[npo.nl:live] npo-2: Downloading hls URL
[npo.nl:live] npo-2: Downloading m3u8 information
[npo.nl:live] npo-2: Downloading ms JSON
[npo.nl:live] npo-2: Downloading ms URL
[debug] Invoking downloader on 'http://l2cm734a2d72300054ff64ae000000.9acb41193c47fab9.kpnsmoote2b.npostreaming.nl/d/live/npo/tvlive/ned2/ned2.isml/Manifest'
[download] Destination: Nederland 2 2015-03-10 22_39-LI_NEDERLAND2_136694.unknown_video
[download] 100% of 2.45KiB in 00:00

```
The video is saved in a very small unplayable file, as seen in the output

**Comment by corone17** [comment] 2015-03-10 23:29
It seems the 608x342 videostream is no longer the 'best' format:
```
youtube-dl.exe -F http://www.npo.nl/live/npo-2
[npo.nl:live] npo-2: Downloading webpage
[npo.nl:live] npo-2: Downloading JSON metadata
[npo.nl:live] npo-2: Downloading token
[npo.nl:live] npo-2: Downloading hds JSON
[npo.nl:live] npo-2: Downloading hds URL
[npo.nl:live] npo-2: Downloading f4m manifest
[npo.nl:live] npo-2: Downloading hls JSON
[npo.nl:live] npo-2: Downloading hls URL
[npo.nl:live] npo-2: Downloading m3u8 information
[npo.nl:live] npo-2: Downloading ms JSON
[npo.nl:live] npo-2: Downloading ms URL
[info] Available formats for LI_NEDERLAND2_136694:
format code  extension      resolution note
meta         mp4            multiple   Quality selection URL
f4m-128      flv            unknown     128k
f4m-264      flv            288x162     264k
f4m-564      flv            416x234     564k
f4m-764      flv            544x306     764k
f4m-964      flv            608x342     964k
279          mp4            288x162     279k , mp4a, avc1
665          mp4            416x234     665k , mp4a, avc1
877          mp4            544x306     877k , mp4a, avc1
1089         mp4            608x342    1089k , mp4a, avc1
10           unknown_video  unknown    (best)
```
Format "10" seems to be some (new?) sort of xml-file. I haven't seen it before. Why include it as a videostream?
By using `youtube-dl.exe -f 1089 http://www.npo.nl/live/npo-2` downloading still works though.

**Comment by dstftw** [comment] 2015-03-11 14:35
This will be fixed in the next version. Thanks for the report.

**Closed** 2015-03-11 14:34 UTC

**Comment by corone17** [comment] 2015-03-11 18:32
Confirmed. Thank you, dstftw.
