### ISSUE TITLE
Can't download video from youku.com

### ISSUE THREAD

**Issue by lgis80boy** [rg3/youtube-dl#7713] opened 2015-12-01 08:09 UTC
can't download video form youku.com 

my youtube-dl version is  2015.11.27.1

[youku] XMTM5NTE0ODU1Ng: Downloading JSON metadata 1
ERROR: Unable to download JSON metadata: [Errno 104] Connection reset by peer (caused by ConnectionResetError(104, 'Connection reset by peer')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment] 2015-12-01 11:32
Duplicate of #7627.

**Closed by dstftw** 2015-12-01 11:32 UTC
