### ISSUE TITLE
Download ends in 403 error on nVhNCTH8pDs

### ISSUE THREAD

**Issue by sirkkalap** [rg3/youtube-dl#6623] opened 2015-08-20 08:25 UTC
````bash
petes@gravelandsand /m/m/P/music ❯❯❯ youtube-dl --verbose https://www.youtube.com/watch\?v\=nVhNCTH8pDs   ⏎
[debug] System config: [u'--no-check-certificate']
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=nVhNCTH8pDs']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.16.1
[debug] Python version 2.7.10 - FreeBSD-9.2-RELEASE-p12-amd64-64bit-ELF
[debug] exe versions: ffmpeg N-69117-gd3d9a00
[debug] Proxy map: {}
[youtube] nVhNCTH8pDs: Downloading webpage
[youtube] nVhNCTH8pDs: Downloading video info webpage
[youtube] nVhNCTH8pDs: Extracting video information
[youtube] {43} signature length 40.42, html5 player new
[youtube] {18} signature length 40.42, html5 player new
[youtube] {5} signature length 40.42, html5 player new
[youtube] {36} signature length 40.42, html5 player new
[youtube] {17} signature length 40.42, html5 player new
[youtube] {135} signature length 40.42, html5 player new
[youtube] {244} signature length 40.42, html5 player new
[youtube] {134} signature length 40.42, html5 player new
[youtube] {243} signature length 40.42, html5 player new
[youtube] {133} signature length 40.40, html5 player new
[youtube] {242} signature length 40.42, html5 player new
[youtube] {160} signature length 40.42, html5 player new
[youtube] {278} signature length 40.42, html5 player new
[youtube] {140} signature length 40.42, html5 player new
[youtube] {171} signature length 40.42, html5 player new
[youtube] nVhNCTH8pDs: Downloading DASH manifest
WARNING: [youtube] nVhNCTH8pDs: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[debug] Invoking downloader on u'https://r5---sn-xap5-ixas.googlevideo.com/videoplayback?source=youtube&sver=3&clen=20469922&upn=d9yn1WmwSTU&lmt=1427898463869187&mv=m&pl=21&mt=1440058142&ms=au&id=o-AExNAt17lf4Qw72KJiXsA-qYAEX-E5iC40j8EyXDI51R&ip=88.113.157.131&key=yt5&keepalive=yes&mn=sn-xap5-ixas&mm=31&fexp=9407641%2C9408093%2C9408487%2C9408710%2C9409069%2C9414703%2C9415356%2C9415365%2C9415485%2C9415792%2C9415991%2C9416023%2C9416126%2C9416729%2C9417707%2C9418153%2C9418393%2C9418449%2C9418700%2C9419388&gir=yes&initcwndbps=2215000&dur=265.200&sparams=clen%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&requiressl=yes&ipbits=0&pcm2cms=yes&expire=1440079881&mime=video%2Fmp4&itag=135&signature=CE5517FF7124C54DC0354F37E9CD993942FF900F.EE8A2775472A19DFF4A129D9D57EC62508D7A149&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1579, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1527, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 60, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1860, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/local/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
````

**Comment by yan12125** [comment] 2015-08-20 10:26
Duplicate of #6451. Please remove cache via ```youtube-dl --rm-cache-dir``` and try again.

**Closed by yan12125** 2015-08-20 10:26 UTC
