### ISSUE TITLE
SBS Australia - Unable to download f4m manifest: HTTP Error 403: Forbidden / ExtractorError: No video formats found.    on some videos

### ISSUE THREAD

**Issue by XtremeBear** [rg3/youtube-dl#8853] opened 2016-03-14 00:58 UTC
This works fine:
http://www.sbs.com.au/ondemand/video/633090627727/the-story-of-egypt-the-road-to-the-pyramids

however, this fails!!!

http://www.sbs.com.au/ondemand/video/11888707849/egypt-what-lies-beneath
(unsetting useragent makes no difference)
```
[debug] System config: [u'--user-agent', u'Mozilla/5.0 (X11; Linux x86_64; rv:39.0) Gecko/20100101 Firefox/38.0', u'--restrict-filenames', u'--ffmpeg-location', u'/opt/ffmpeg/usr/bin/ffmpeg']
[debug] User config: []
[debug] Command-line args: [u'-f', u'flv', u'--verbose', u'http://www.sbs.com.au/ondemand/video/11888707849/egypt-what-lies-beneath']
[debug] Encodings: locale ISO-8859-1, fs ISO-8859-1, out ISO-8859-1, pref ISO-8859-1
[debug] youtube-dl version 2016.03.06
[debug] Python version 2.7.3 - Linux-3.10.17-x86_64-Intel-R-_Pentium-R-_Dual__CPU__E2160__@_1.80GHz-with-slackware-14.0
[debug] exe versions: ffmpeg 2.5.3, ffprobe 2.5.3, rtmpdump 2.4
[debug] Proxy map: {}
[SBS] 11888707849: Downloading webpage
[ThePlatform] Vi7X79M80Gr0: Downloading SMIL data
[ThePlatform] Vi7X79M80Gr0: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 403: Forbidden
[ThePlatform] Vi7X79M80Gr0: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 403: Forbidden
[ThePlatform] Vi7X79M80Gr0: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 403: Forbidden
[ThePlatform] Vi7X79M80Gr0: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 668, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 319, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/theplatform.py", line 234, in _real_extract
    formats, subtitles = self._extract_theplatform_smil(smil_url, video_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/theplatform.py", line 46, in _extract_theplatform_smil
    transform_rtmp_url=lambda streamer, src: (streamer, 'mp4:' + src))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1302, in _parse_smil_formats
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 832, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment] 2016-03-14 15:29
Duplicate of #3811.

**Closed by dstftw** 2016-03-14 15:29 UTC
