### ISSUE TITLE
Cookie file error

### ISSUE THREAD

**Issue by amkrankruleuen** [rg3/youtube-dl#5195] opened 2015-03-13 13:50 UTC
test@test:~# youtube-dl -e --cookies "cookie.txt" --print-traffic "https://www.youtube.com/watch?v=s898ws_7VMQ"
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 403, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 370, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 329, in __init__
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1755, in _setup_opener
  File "/usr/lib/python2.7/cookielib.py", line 1763, in load
    self._really_load(f, filename, ignore_discard, ignore_expires)
  File "/usr/lib/python2.7/_MozillaCookieJar.py", line 55, in _really_load
    filename)
cookielib.LoadError: 'cookie.txt' does not look like a Netscape format cookies file

Cookie file source:

.youtube.com    TRUE    /       FALSE   1428846439      VISITOR_INFO1_LIVE      s0IqaYrSgOg
.youtube.com    TRUE    /       FALSE   1428846439      YSC     ujJ3n8Oe-Vw
.youtube.com    TRUE    /       FALSE   1428846439      PREF    f1
.youtube.com    TRUE    /       FALSE   1428846439      goojf   0da5651fc58ad7dcba506892d2f4fdd6cwsAAABxSTNYbDBKSmJvQQ
.youtube.com    TRUE    /       FALSE   1428846439      ACTIVITY        1426254424997

And in cookie file use only tabs.

Maybe add support for example: --cookie "VISITOR_INFO1_LIVE=s0IqaYrSgOg; YSC=ujJ3n8Oe-Vw" ?

**Comment by jaimeMF** [comment] 2015-03-13 16:59
Apparently it only works if you also add `# Netscape HTTP Cookie File` at the start of the file, closing as a duplicate of #4539.

**Closed** 2016-01-31 17:56 UTC
