### ISSUE TITLE
ERROR: "rental" videos not supported;

### ISSUE THREAD

**Issue by simplelive** [rg3/youtube-dl#5688] opened 2015-05-13 06:00 UTC
[download] Downloading video 15 of 37
[youtube] loJGSgb9PUE: Downloading webpage
[youtube] loJGSgb9PUE: Downloading embed webpage
[youtube] loJGSgb9PUE: Refetching age-gated info webpage
ERROR: "rental" videos not supported; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by simplelive** [comment] 2015-05-13 06:08
[download] Downloading video 3 of 37
[youtube] PlSjPfpmhIU: Downloading webpage
[youtube] PlSjPfpmhIU: Downloading embed webpage
[youtube] PlSjPfpmhIU: Refetching age-gated info webpage
ERROR: "rental" videos not supported; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 914, in _real_extract
    raise ExtractorError('"rental" videos not supported')
ExtractorError: "rental" videos not supported; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by jaimeMF** [comment] 2015-05-13 09:52
Duplicate of #359.

**Closed by jaimeMF** 2015-05-13 09:52 UTC
