### ISSUE TITLE
Logging to a report file

### ISSUE THREAD

**Issue by orospakr** [rg3/youtube-dl#201] opened 2011-10-23 15:38 UTC
Right now, I just always pipe the output to tee.  However, because I like seeing the indicators, I leave the download progress spinner on, which produces lots of goop in the log file that I have to grep out afterwards.

It'd be great if youtube-dl did its own logging. :)

**Comment by dstftw** [comment] 2016-03-27 02:42
Duplicate of #6990.

**Closed by dstftw** 2016-03-27 02:42 UTC
