### ISSUE TITLE
Playback on other websites has been disabled by the video owner.

### ISSUE THREAD

**Issue by wdfsinap** [rg3/youtube-dl#8403] opened 2016-02-02 12:29 UTC
hi, I use youtube-dl latest version. and I get error when i try to download this video  http://www.youtube.com/watch?v=gUYU3FqMLT8

[root@nood]# youtube-dl -v http://www.youtube.com/watch?v=gUYU3FqMLT8
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=gUYU3FqMLT8']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.01
[debug] Python version 2.7.8 - Linux-2.6.32-573.8.1.el6.x86_64-x86_64-with-centos-6.7-Final
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] gUYU3FqMLT8: Downloading webpage
[youtube] gUYU3FqMLT8: Downloading embed webpage
[youtube] gUYU3FqMLT8: Refetching age-gated info webpage
ERROR: gUYU3FqMLT8: YouTube said: <a href="http://www.youtube.com/watch?v=gUYU3FqMLT8&feature=player_embedded" target="_blank">Watch this video on YouTube.</a><br/>Playback on other websites has been disabled by the video owner.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 313, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1160, in _real_extract
    expected=True, video_id=video_id)
ExtractorError: gUYU3FqMLT8: YouTube said: <a href="http://www.youtube.com/watch?v=gUYU3FqMLT8&feature=player_embedded" target="_blank">Watch this video on YouTube.</a><br/>Playback on other websites has been disabled by the video owner.

**Comment by yan12125** [comment] 2016-02-23 18:56
Duplicate of #4162. You need to provide credentials via ```--username``` and ```--password``` to download this video.

**Closed by yan12125** 2016-02-23 18:56 UTC
