### ISSUE TITLE
SSL certificate validation failure

### ISSUE THREAD

**Issue by 4chanmoot** [rg3/youtube-dl#5427] opened 2015-04-14 21:36 UTC
When trying to download a Youtube video, a certificate validation error occurs. This seems odd since my browsers are accepting the current Google certificate that Youtube uses.

FWIW this isn't a showstopper for me since passing --no-check-certificate works around the problem.

```
| => youtube-dl --verbose -x --audio-format mp3 --audio-quality 0 http://www.youtube.com/watch?v=-usL_kRXm6s
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-x', u'--audio-format', u'mp3', u'--audio-quality', u'0', u'http://www.youtube.com/watch?v=-usL_kRXm6s']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.09
[debug] Python version 2.7.9 - Darwin-14.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.6.1, ffprobe 2.6.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] -usL_kRXm6s: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)> (caused by URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 314, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1673, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 695, in https_open
    req, **kwargs)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
```

**Comment by dstftw** [comment] 2015-04-14 21:40
Duplicate of #5317.

**Closed by dstftw** 2015-04-14 21:40 UTC
