### ISSUE TITLE
ERROR: unable to download video data: HTTP Error 410: Gone

### ISSUE THREAD

**Issue by ekosan** [rg3/youtube-dl#9190] opened 2016-04-14 08:08 UTC
`xx@xx:~$ youtube-dl --verbose https://www.youtube.com/watch?v=ePN0HEvcHTY`
`[debug] System config: []`
`[debug] User config: []`
`[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=ePN0HEvcHTY']`
`[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8`
`[debug] youtube-dl version 2016.04.13`
`[debug] Python version 2.7.6 - Linux-4.2.0-35-generic-i686-with-Ubuntu-14.04-trusty`
`[debug] exe versions: avconv 11.6, avprobe 11.6`
`[debug] Proxy map: {}`
`[youtube] ePN0HEvcHTY: Downloading webpage`
`[youtube] ePN0HEvcHTY: Downloading video info webpage`
`[youtube] ePN0HEvcHTY: Extracting video information`
`[youtube] ePN0HEvcHTY: Downloading MPD manifest`
`WARNING: Requested formats are incompatible for merge and will be merged into mkv.`
`[debug] Invoking downloader on u'https://r1---sn-2uuxa3vh-ngbe.googlevideo.com/videoplayback?id=78f3741c4bdc1d36&itag=244&source=youtube&requiressl=yes&mm=31&mn=sn-2uuxa3vh-ngbe&pl=20&mv=m&ms=au&ratebypass=yes&mime=video/webm&gir=yes&clen=2886612&lmt=1411026302126825&dur=297.000&signature=0C27D4D9F5215BE6BA0A7D1FEE701FD0431D8537.3392EAE82C53E20090977A8CD160676E51ED6EE3&upn=8Yhv_4dshFs&fexp=9408504,9416126,9416891,9416984,9419451,9420452,9422596,9423328,9426269,9426687,9426926,9428012,9428335,9428398,9429051,9431104,9432564&key=dg_yt0&sver=3&mt=1460620204&ip=36.73.157.244&ipbits=0&expire=1460642036&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mn,pl,mv,ms,ratebypass,mime,gir,clen,lmt,dur'`
`ERROR: unable to download video data: HTTP Error 410: Gone`
`Traceback (most recent call last):`
`  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1632, in process_info`
`    partial_success = dl(fname, new_info)`
`  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1580, in dl`
`    return fd.download(name, info)`
`  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 350, in download`
`    return self.real_download(filename, info_dict)`
`  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 58, in real_download`
`    data = self.ydl.urlopen(request)`
`  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1940, in urlopen`
`    return self._opener.open(req, timeout=self._socket_timeout)`
`  File "/usr/lib/python2.7/urllib2.py", line 410, in open`
`    response = meth(req, response)`
`  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response`
`    'http', request, response, code, msg, hdrs)`
`  File "/usr/lib/python2.7/urllib2.py", line 448, in error`
`    return self._call_chain(*args)`
`  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain`
`    result = func(*args)`
`  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default`
`    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)`
`HTTPError: HTTP Error 410: Gone`

**Comment by yan12125** [comment] 2016-04-14 08:31
Duplicate of #4532.

**Closed by yan12125** 2016-04-14 08:31 UTC

**Comment by ekosan** [comment] 2016-04-14 08:39
@yan12125 Thank you..

**Comment by x011** [comment] 2022-03-10 11:45
`pip3 install --upgrade youtube-dl`
