### ISSUE TITLE
Bug On this Video youtube

### ISSUE THREAD

**Issue by praburamWAPKA** [rg3/youtube-dl#9346] opened 2016-04-29 06:55 UTC
youtube-dl --verbose https://youtube.com/watch?v=GECrBU_ 
2U48
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://youtube.com/watch?v=GECrBU_2U48']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2016.04.24
[debug] Python version 2.6.6 - Linux-2.6.32-042stab104.1-x86_64-with-centos-6.7-Final
[debug] exe versions: ffmpeg N-79595-g0499012-syslint
[debug] Proxy map: {}
[youtube] GECrBU_2U48: Downloading webpage
[youtube] GECrBU_2U48: Downloading video info webpage
WARNING: Unable to extract video title
ERROR: "rental" videos not supported; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 673, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1376, in _real_extract
    raise ExtractorError('"rental" videos not supported')
ExtractorError: "rental" videos not supported; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I have updated Version So thereis bug on this please check this

**Comment by yan12125** [comment] 2016-04-29 07:01
Duplicate of #359.

**Closed by yan12125** 2016-04-29 07:01 UTC
