### ISSUE TITLE
[archiveorg] Wayback Machine archives of YouTube videos

### ISSUE THREAD

**Issue by hololeap** [rg3/youtube-dl#18046] opened 2018-11-02 02:29 UTC
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```kinetik@triton ~ $ youtube-dl --verbose 'https://web.archive.org/web/20140915015235/http://www.youtube.com/watch?v=9bZkp7q19f0&feature=youtu.be'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://web.archive.org/web/20140915015235/http://www.youtube.com/watch?v=9bZkp7q19f0&feature=youtu.be']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.10.29
[debug] Git HEAD: 0753f1e
[debug] Python version 3.6.5 (CPython) - Linux-4.18.16-gentoo-x86_64-AMD_Athlon-tm-_II_X4_630_Processor-with-gentoo-2.4.1
[debug] exe versions: ffmpeg 3.3.6, ffprobe 3.3.6
[debug] Proxy map: {}
[generic] watch?v=9bZkp7q19f0&feature=youtu: Requesting header
WARNING: Falling back on generic information extractor.
[generic] watch?v=9bZkp7q19f0&feature=youtu: Downloading webpage
[generic] watch?v=9bZkp7q19f0&feature=youtu: Extracting information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://web.archive.org/web/20140915015235/http://www.youtube.com/annotations_invideo?cap_hist=1\\u0026cta=2\\u0026video_id=9bZkp7q19f0'
ERROR: unable to download video data: HTTP Error 404: NOT FOUND
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1908, in process_info
    success = dl(filename, info_dict)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1847, in dl
    return fd.download(name, info)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/downloader/common.py", line 364, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/lib64/python3.6/site-packages/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: NOT FOUND
```

---

These are all the same video (http://www.youtube.com/watch?v=9bZkp7q19f0):
- Single video (2013-02-15): https://web.archive.org/web/20130215123412/http://www.youtube.com/watch?v=9bZkp7q19f0&feature=youtu.be
- Single video (2014-09-15): https://web.archive.org/web/20140915015235/http://www.youtube.com/watch?v=9bZkp7q19f0&feature=youtu.be
- Single video (2016-05-19): https://web.archive.org/web/20160519124739/https://www.youtube.com/watch?v=9bZkp7q19f0&feature=youtu.be
- Single video (2018-05-08): https://web.archive.org/web/20180508055752/https://www.youtube.com/watch?v=9bZkp7q19f0&feature=youtu.be

---

YouTube videos archived within the Wayback Machine on `archive.org`, don't seem to be supported. I hazard a guess that supporting this may tricky because YouTube may change significantly depending on which date is chosen.

I don't see the point in playlists or related videos being supported, since there are low odds that any given video in a playlist is archived.

**Comment by dstftw** [comment] 2018-11-02 15:49
Duplicate of #13655.

**Closed by dstftw** 2018-11-02 15:49 UTC
