### ISSUE TITLE
youtube-dl --verbose -f 43 -l 'https://www.youtube.com/watch?v=jCiAd1KPSjY' gives an error.

### ISSUE THREAD

**Issue by shlomif** [rg3/youtube-dl#6672] opened 2015-08-25 20:00 UTC
Hi all! Thanks for youtube-dl.

Running the command line in the topic gives this error:

```
youtube-dl --verbose -f 43 -l 'https://www.youtube.com/watch?v=jCiAd1KPSjY' 2>&1 | tee ~/ydl.txt
```

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-f', u'43', u'-l', u'https://www.youtube.com/watch?v=jCiAd1KPSjY']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2015.08.23
[debug] Python version 2.7.10 - Linux-4.1.6-desktop-3.mga6-x86_64-with-mandrake-6-Cauldron
[debug] exe versions: ffmpeg 2.7.1, ffprobe 2.7.1
[debug] Proxy map: {}
[youtube] jCiAd1KPSjY: Downloading webpage
[youtube] jCiAd1KPSjY: Downloading video info webpage
[youtube] jCiAd1KPSjY: Extracting video information
[youtube] {22} signature length 40.43, html5 player new
[youtube] {43} signature length 40.43, html5 player new
[youtube] {18} signature length 40.43, html5 player new
[youtube] {5} signature length 40.43, html5 player new
[youtube] {36} signature length 40.43, html5 player new
[youtube] {17} signature length 40.43, html5 player new
[youtube] {13} signature length 40.43, html5 player new
[youtube] {137} signature length 40.43, html5 player new
[youtube] {248} signature length 40.43, html5 player new
[youtube] {136} signature length 40.43, html5 player new
[youtube] {247} signature length 40.43, html5 player new
[youtube] {135} signature length 40.43, html5 player new
[youtube] {244} signature length 40.43, html5 player new
[youtube] {134} signature length 40.43, html5 player new
[youtube] {243} signature length 40.43, html5 player new
[youtube] {133} signature length 40.43, html5 player new
[youtube] {242} signature length 40.43, html5 player new
[youtube] {160} signature length 40.43, html5 player new
[youtube] {278} signature length 40.43, html5 player new
[youtube] {140} signature length 40.43, html5 player new
[youtube] {171} signature length 40.43, html5 player new
[youtube] {249} signature length 40.43, html5 player new
[youtube] {250} signature length 40.43, html5 player new
[youtube] {251} signature length 40.43, html5 player new
[youtube] jCiAd1KPSjY: Downloading DASH manifest
WARNING: [youtube] jCiAd1KPSjY: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[debug] Invoking downloader on u'https://r4---sn-cx1x9-ua8s.googlevideo.com/videoplayback?source=youtube&ms=au&mv=m&mt=1440532626&mn=sn-cx1x9-ua8s&mm=31&requiressl=yes&mime=video%2Fwebm&itag=43&ipbits=0&key=yt5&expire=1440554286&sver=3&dur=0.000&pl=24&ratebypass=yes&pcm2cms=yes&lmt=1440260075630436&upn=sVRHcPo9njE&id=o-ADCr0aa8_vw8NUE1AF9EWqtibnbWqjm18HbVeKGLeF7H&initcwndbps=1217500&gcr=il&fexp=9408710%2C9409069%2C9415365%2C9415485%2C9416023%2C9416126%2C9417707%2C9418153%2C9418449%2C9418625&sparams=dur%2Cgcr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&ip=109.64.31.246&signature=C2ACE3382E36397DB801E730DF2082C5DAFF6852.2B84936920A34D8D0D85A4012C2D549310E9FCFC'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/shlomif/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1585, in process_info
    success = dl(filename, info_dict)
  File "/home/shlomif/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1527, in dl
    return fd.download(name, info)
  File "/home/shlomif/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/home/shlomif/bin/youtube-dl/youtube_dl/downloader/http.py", line 60, in real_download
    data = self.ydl.urlopen(request)
  File "/home/shlomif/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1860, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden

```

I'm getting a similar error without the "-f 43" flag. Please look into fixing it.

**Comment by dstftw** [comment] 2015-08-25 20:01
Duplicate of #6451. Remove cache with `youtube-dl --rm-cache-dir`.

**Closed by dstftw** 2015-08-25 20:01 UTC
