### ISSUE TITLE
ExtractorError

### ISSUE THREAD

**Issue by hansgerig** [rg3/youtube-dl#18015] opened 2018-10-30 03:04 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: [u'-o', u'%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.bbcamerica.com/?amcn_video_movie=adv-space-time']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.10.29
[debug] Python version 2.7.13 (CPython) - Linux-4.4.159-73-default-x86_64-with-SuSE-42.3-x86_64
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] ?amcn_video_movie=adv-space-time: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?amcn_video_movie=adv-space-time: Downloading webpage
[generic] ?amcn_video_movie=adv-space-time: Extracting information
[download] Downloading playlist: An Adventure in Space and Time | BBC America
[generic] playlist An Adventure in Space and Time | BBC America: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[ThePlatform] V1JQFmTdQkVn: Downloading SMIL data
ERROR: This content requires a valid, unexpired auth token.
Traceback (most recent call last):
  File "/home/user/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/home/user/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/home/user/bin/youtube-dl/youtube_dl/extractor/theplatform.py", line 297, in _real_extract
    formats, subtitles = self._extract_theplatform_smil(smil_url, video_id)
  File "/home/user/bin/youtube-dl/youtube_dl/extractor/theplatform.py", line 44, in _extract_theplatform_smil
    raise ExtractorError(error_element.attrib['abstract'], expected=True)
ExtractorError: This content requires a valid, unexpired auth token.
```

---

**Comment by remitamine** [comment] 2018-10-30 12:13
Duplicate of #17871.

**Closed by remitamine** 2018-10-30 12:13 UTC
