### ISSUE TITLE
get files/stream in multiple connections

### ISSUE THREAD

**Issue by nmr50** [rg3/youtube-dl#8451] opened 2016-02-07 09:12 UTC
Hello coders!
I watch how long time youtube-dl getting stream from some sites, especially from ntv.ru:
[ntv.ru] peredacha/chudo_tehniki/m24780/o378938/: Downloading webpage
[ntv.ru] 1256107: Downloading video XML
[ntv.ru] 1256107: Downloading access token
[download] Destination: <Чудо техники>. Выпуск от 31 января 2016 года-1256107.mp4
[download]  17.1% of 561.72MiB at 831.73KiB/s ETA 09:33
-- it starts with full speed of my 100mbit connection, 11mbytes/sec, but right after few seconds this speed drops to 800-700kbytes/sec. 
I want to ask you, ppl, is it possible to make some patch to youtube-dl that will perform multi connections to one URL, so transfer will take somewhat less time?

For example, the program names of those using this several connections feature are: aria2c, download master, lftp.

Thanks in advance!
-t

**Comment by dstftw** [comment] 2016-02-07 12:01
Use `--external-downloader`. Duplicate of #1498.

**Closed by dstftw** 2016-02-07 12:01 UTC

**Comment by nmr50** [comment] 2016-02-07 14:45
seems like this problem with slow connection happens because ntv.ru limits download speed no matter aria2 being used or not.
