### ISSUE TITLE
Working with unsupported sites (Codeschool)

### ISSUE THREAD

**Issue by picwellwisher12pk** [rg3/youtube-dl#10208] opened 2016-08-02 08:53 UTC
I guess my problem is all about unsupported extractor that you might include in package in future releases. Here is the output though
```
youtube-dl.exe -v https://www.codeschool.com/courses/surviving-apis-with-rails/videos
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://www.codeschool.com/courses/surviving-apis-with-rails/videos']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2016.08.01
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: none
[debug] Proxy map: {}
[generic] videos: Requesting header
[redirect] Following redirect to https://www.codeschool.com/users/sign_in
[generic] sign_in: Requesting header
WARNING: Falling back on generic information extractor.
[generic] sign_in: Downloading webpage
[generic] sign_in: Extracting information
ERROR: Unsupported URL: https://www.codeschool.com/users/sign_in
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpnq4x675r\build\youtube_dl\YoutubeDL.py", line 682, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpnq4x675r\build\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpnq4x675r\build\youtube_dl\extractor\generic.py", line 2336, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.codeschool.com/users/sign_in

```

**Comment by picwellwisher12pk** [comment] 2016-08-02 09:01
I wish I had enough knowledge to make the extractor myself, then I would not had bothered you and rather had helped you instead.

**Comment by yan12125** [comment] 2016-08-02 09:07
Duplicate of #4810. See https://github.com/rg3/youtube-dl/blob/master/README.md#developer-instructions if you're going to write your own extractor.

**Closed by yan12125** 2016-08-02 09:07 UTC
