### ISSUE TITLE
Add support for pivotshare.com websites

### ISSUE THREAD

**Issue by jgilf** [rg3/youtube-dl#12374] opened 2017-03-06 00:46 UTC
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.06**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Site support request (request for adding support for a new site)

### Description of your *issue*, suggested solution and other information

Please add support for pivotshare.com. 
#### Example URLs: 
https://www.cultorama.tv/media/brotherhood-of-justice/49480
https://www.adsrcourses.com/media/02-underestimating-acoustical-treatment/50481
https://rpwondemand.pivotshare.com/media/live-in-portsmouth-7/59694

#### There are a heap of other channels that can be found here:
https://www.pivotshare.com/discover/

#### Account can be provided if needed.

**Comment by yan12125** [comment] 2017-03-06 08:17
Duplicate of #11374

**Closed by yan12125** 2017-03-06 08:17 UTC
