### ISSUE TITLE
Won't work with https://www.youtube.com/watch?v=D8t8A8E_Tqc

### ISSUE THREAD

**Issue by Farfie** [rg3/youtube-dl#6686] opened 2015-08-26 19:57 UTC
Throws 403 forbidden error.
![yeoflh 1](https://cloud.githubusercontent.com/assets/2372953/9504535/1e1d9974-4c0b-11e5-9bf0-ed757b63fa1a.png)

**Comment by dstftw** [comment] 2015-08-26 19:58
Duplicate of #6451. Remove cache with `youtube-dl --rm-cache-dir`.

**Closed by dstftw** 2015-08-26 19:58 UTC
