### ISSUE TITLE
Output template playlist_index issue

### ISSUE THREAD

**Issue by zorrohere** [rg3/youtube-dl#6841] opened 2015-09-12 11:30 UTC
Lets say I am downloading playlist with 15 videos and after 6 videos it was interrupted. So when I restart with --playlist-start 7, the index doesn't add 0 by default to the playlist_index. It creates problem if I have created playlist or want to sort videos in playlist.

What I get is: 7. filename, 8. filename, 9. filename

I want it like: 07. filename, 08. filename, 09. filename

**Comment by dstftw** [comment] 2015-09-12 13:37
Duplicate of #5185.

**Closed by dstftw** 2015-09-12 13:37 UTC
