### ISSUE TITLE
HTTP Error 429

### ISSUE THREAD

**Issue by djr33333** [rg3/youtube-dl#9269] opened 2016-04-21 14:34 UTC
Here is the exact error I got today:

RROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I was trying to get this video 5 minutes ago:
https://www.youtube.com/watch?v=OyLWjDl7Thw&index=3&list=WL

I am running a Mac on the most up to date OS and Safari web Browser

I hope this helps

**Comment by yan12125** [comment] 2016-04-21 15:10
Duplicate of #5138. See also [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#http-error-429-too-many-requests-or-402-payment-required).

**Closed by yan12125** 2016-04-21 15:10 UTC
