### ISSUE TITLE
Bug when downloading a video from Facebook

### ISSUE THREAD

**Issue by Kasher** [rg3/youtube-dl#10027] opened 2016-07-07 09:26 UTC
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

❯ ./youtube-dl -v https://www.facebook.com/23tv.tv/videos/1234088389965246/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://www.facebook.com/23tv.tv/videos/1234088389965246/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.07
[debug] Python version 3.5.2 - Linux-4.6.3-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg N-76639-g58d32c0, ffprobe N-76639-g58d32c0, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] 1234088389965246: Downloading webpage
[debug] Invoking downloader on 'https://video.fsdv1-1.fna.fbcdn.net/v/t43.1792-2/13462948_114636645631815_388168315_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InN2ZV9oZCJ9&oh=1ae389bbb459acdea3b4d28242f8ae4d&oe=577E5E01'
[download] Facebook video #1234088389965246-1234088389965246.mp4 has already been downloaded
[download] 100% of 2.79MiB

---

### Description of your *issue*, suggested solution and other information

Hi,
I'm trying to download a video from Facebook, and when using Youtube-dl, another video is being downloaded, instead of the video that I was watching online.
The video's url is:
https://www.facebook.com/23tv.tv/videos/1234088389965246/

Here are some photos that demonstrate the result:
When I watch the video online, I get this video:
http://i.imgur.com/Tzy1kwY.png
And when downloading the video (using to most updated Youtube-dl version), I get this video:
http://i.imgur.com/qkSNpsV.png

I'll add that this is the first time I've encountered something like that. Usually Youtube-dl works perfectly, and I get the same video both when watching online and when downloading it using Youtube-dl.

Any help would be appreciated. Thanks!!

**Comment by yan12125** [comment] 2016-07-07 09:29
Duplicate of #9851.

**Closed by yan12125** 2016-07-07 09:29 UTC
