### ISSUE TITLE
[billbill]Unable to extract player parameters

### ISSUE THREAD

**Issue by penn1133** [rg3/youtube-dl#10381] opened 2016-08-19 09:28 UTC
The billbill has change it's web player,add a html5 player,then youtube-dl can't extract player parameters.

----------
mbp13:music sjzri$ youtube-dl -x --verbose "http://www.bilibili.com/video/av920756/"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-x', u'--verbose', u'http://www.bilibili.com/video/av920756/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.19
[debug] Python version 2.7.10 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.1.1, ffprobe 3.1.1
[debug] Proxy map: {}
[BiliBili] 920756: Downloading webpage
ERROR: Unable to extract player parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bilibili.py", line 97, in _real_extract
    webpage, 'player parameters'))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 650, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract player parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment] 2016-08-19 09:34
Duplicate of #10375.

> add a html5 player

For this video it says "视频不见了哟 你可以尝试登录" (the video is missing, try logging in) and another example from #10375: http://www.bilibili.com/video/av5782830/index_1.html still requires Flash. Do you have an HTML5-only example?

**Comment by vxbinaca** [comment] 2016-08-23 09:52
@yan12125 this one isn't working for me:

http://www.bilibili.com/video/av5522066/

**Comment by yan12125** [comment] 2016-08-23 11:08
Well, in Firefox's developer console I can see an URL http://103.5.35.15/... If I paste it to a new tab, Firefox says it's a "reported problematic website". Choosing to ignore the warning, I can watch the video now.

And yes, I can watch the video with Flash disabled. Closing this and leave further discussions to #10375

**Closed by yan12125** 2016-08-23 11:08 UTC
