### ISSUE TITLE
[WDR] Can't get video from WDR Mediathek

### ISSUE THREAD

**Issue by larsauswsw** [rg3/youtube-dl#9643] opened 2016-05-30 11:03 UTC
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.30.2**

- [x] Bug report (encountered problems with youtube-dl)

The support for the german WDR stopped working.

[larsis@sculptor ~]$ ./apps/youtube-dl -v  http://www1.wdr.de/mediathek/av/video-rainald-grebe-live-die-besten-songs-100.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www1.wdr.de/mediathek/av/video-rainald-grebe-live-die-besten-songs-100.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.30.2
[debug] Python version 2.6.6 - Linux-2.6.32-573.8.1.el6.x86_64-x86_64-with-centos-6.8-Final
[debug] exe versions: none
[debug] Proxy map: {}
[WDR] mediathek/av/video-rainald-grebe-live-die-besten-songs-100: Downloading webpage
[download] Downloading playlist: mediathek/av/video-rainald-grebe-live-die-besten-songs-100
[WDR] playlist mediathek/av/video-rainald-grebe-live-die-besten-songs-100: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: mediathek/av/video-rainald-grebe-live-die-besten-songs-100

**Comment by dstftw** [comment] 2016-05-30 15:13
Duplicate of #9517.

**Closed by dstftw** 2016-05-30 15:13 UTC
