### ISSUE TITLE
spiegel.de again: Unable to extract server URL

### ISSUE THREAD

**Issue by RokerHRO** [rg3/youtube-dl#16538] opened 2018-05-24 12:14 UTC
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.18**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
```
$ youtube-dl --verbose http://www.spiegel.de/video/geschichten-aus-dem-kalten-krieg-die-atombombe-im-vorgarten-video-99011625.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'http://www.spiegel.de/video/geschichten-aus-dem-kalten-krieg-die-atombombe-im-vorgarten-video-99011625.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.05.18
[debug] Python version 2.7.15 (CPython) - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg 4.0, ffprobe 4.0
[debug] Proxy map: {}
[Spiegel] 99011625: Downloading webpage
ERROR: Unable to extract server URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 503, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/spiegel.py", line 86, in _real_extract
    webpage, 'server URL', group='url')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 883, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract server URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by Mustolih0lih** [comment] 2018-05-24 13:48
saya kurang paham maksudnya apa?

**Comment by kennell** [comment] 2018-05-27 16:54
Similar problem, different URL, different Traceback:

```
youtube-dl http://www.spiegel.tv/videos/1156206-wo-ist-john-dyal -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://www.spiegel.tv/videos/1156206-wo-ist-john-dyal', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.05.26
[debug] Python version 3.6.4 (CPython) - Darwin-17.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1
[debug] Proxy map: {}
[Nexx] 1156206: Downloading JSON metadata
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/__init__.py", line 472, in main
    _real_main(argv)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/__init__.py", line 462, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2001, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 803, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 864, in process_ie_result
    extra_info=extra_info)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 500, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/nexx.py", line 229, in _real_extract
    assert cdn == 'azure'
AssertionError
```

**Comment by Karl-Malden** [comment] 2018-06-02 05:51
Hi Remitamine,

thanks for your efforts. Perhaps I'm making a mistake, but it doesn't seem to me, that the patch is solving the problem:

According to the ChangeLog the patch should be included since version 2018.05.30
I tested using 2018.05.30 and now 2018.06.02.

youtube-dl http://www.spiegel.de/video/eifel-zoo-aufregung-um-ausgebrochene-raubtiere-video-99018031.html

[Spiegel] 99018031: Downloading webpage
[Nexx] 1533779: Downloading JSON metadata
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./youtube-dl/__main__.py", line 19, in <module>
  File "./youtube-dl/youtube_dl/__init__.py", line 472, in main
  File "./youtube-dl/youtube_dl/__init__.py", line 462, in _real_main
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in download
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 803, in extract_info
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 869, in process_ie_result
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
  File "./youtube-dl/youtube_dl/extractor/common.py", line 500, in extract
  File "./youtube-dl/youtube_dl/extractor/nexx.py", line 229, in _real_extract
AssertionError

Are you able to reproduce the effect?

**Comment by Karl-Malden** [comment] 2018-06-02 05:55
again with debug infos

`[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'http://www.spiegel.de/video/eifel-zoo-aufregung-um-ausgebrochene-raubtiere-video-99018031.html', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.02
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-22-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.2-2, ffprobe 3.4.2-2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[Spiegel] 99018031: Downloading webpage
[Nexx] 1533779: Downloading JSON metadata
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./youtube-dl/__main__.py", line 19, in <module>
  File "./youtube-dl/youtube_dl/__init__.py", line 472, in main
  File "./youtube-dl/youtube_dl/__init__.py", line 462, in _real_main
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in download
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 803, in extract_info
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 869, in process_ie_result
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
  File "./youtube-dl/youtube_dl/extractor/common.py", line 500, in extract
  File "./youtube-dl/youtube_dl/extractor/nexx.py", line 229, in _real_extract
AssertionError
`

**Comment by remitamine** [comment] 2018-06-02 09:56
if I completely fixed this issue, I would've closed it, it only fixed the extraction for old videos hosted on `azure` CDN.
there is a need to handle `free` CDN type for `Nexx`, but I'm not working on it for now.

**Comment by testos77** [comment] 2018-06-04 18:14
I've been trying to code the new handle for the "free" cdn type. New or important compared to azure seems to be (full json below)
"hash":"8DZUCYZR1512345"
"cdnFolder":"292446133"
"cdnPathHTTP":"vcdn.vod.spiegel.de\/"
"cdnPathHLS":"vcdn.hls.spiegel.de\/"
"cdnPathDASH":"vcdn.hls.spiegel.de\/"


which results in the http call for dash:
http://vcdn.hls.spiegel.de/748/91/34/1534319/asset.ism/manifest.mpd?dcp_ver=aos4&videostream=8DZUCYZR1512345_320x180_400.mp4:400000,8DZUCYZR1512345_640x360_700.mp4:700000,8DZUCYZR1512345_720x404_900.mp4:900000,8DZUCYZR1512345_1024x576_1500.mp4:1500000&audiostream=8DZUCYZR1512345_1024x576_1500.mp4

At the moment I don't know how to get to the part of the http get from json cdn folder result:  
/748/ **91/34/** 1534319/

Json:
`{"metadata":{"status":200,"apiversion":"3.0.00","processingtime":0.07286620140075684,"calledwith":"\/videos\/byid\/1534319","forclient":748},"result":{"general":{"ID":1534319,"hash":"8DZUCYZR1534319","title":"Magazin vom 03.06.2018","subtitle":"Tod im toten Winkel \/ Militarisierung der US-Polizei \/ Rares gegen Bares","orderhint":"","uploaded":1528104251,"created":0,"videotype":"movie","runtime":"00:36:47","isPay":0,"payrefnr":"","isUGC":0,"isPicked":1,"isRacy":0,"language_raw":"de","language":"deutsch","channel":4776,"actors_raw":"","actors":"","studio_raw":2025,"studio_adref":"SPIEGEL-TV","studio":"SPIEGEL TV","licenseby":15696,"slug":"","fileversion":1,"teaser":"Themen: Tod im toten Winkel - Tragische Unf\u00e4lle durch Rechtsabbieger \/ Armeehubschrauber und Sturmgewehre - Die Militarisierung der Polizei in den USA \/ Rares gegen Bares - Unterwegs mit einem Antiquit\u00e4ten-Sch\u00e4tzer","description":"Moderation: Maria Gresz.","releasedate":1527976800},"channeldata":{"ID":4776,"title":"SPIEGEL TV","adref":"","parent":0,"ivwref":""},"imagedata":{"thumb":"https:\/\/nx-i.akamaized.net\/201806\/W1534319R6H68xL.jpg","thumb_hasX2":1,"thumb_hasX3":0,"thumb_action":"https:\/\/nx-i.akamaized.net\/201806\/C1534319GWNGCEUxL.jpg","thumb_quad":"https:\/\/nx-i.akamaized.net\/global\/nodata\/nodata_v2.jpg","thumb_alt":"https:\/\/nx-i.akamaized.net\/global\/nodata\/nodata_v2xL.jpg","animation":"https:\/\/nx-i.akamaized.net\/global\/nodata\/nodata_v2.jpg","preview":"https:\/\/nx-i.akamaized.net\/previews\/748\/1534319\/8DZUCYZR1534319.mp4?fv=1"},"interactiondata":{"rating":3,"ratingcount":0,"likecount":0,"commentcount":0,"favouritecount":0,"canBeRated":1,"inFavourites":0,"isLiked":0,"inWatchlist":0},"hotspotdata":[],"captiondata":[],"scenedata":[],"streamdata":{"originalDomain":748,"adMode":0,"logoMode":0,"originalAdChannel":"sptvatspon","payPreviewSeconds":-1,"bumperMode":0,"watermarkMode":1,"encodedTHUMBS":1,"encodedWEBM":1,"encodedVP9":0,"cdnType":"free","encodedHQ":1,"encodedLQ":1,"encodedHQLarge":1,"encodedLQLarge":1,"applyAzureStructure":1,"azureFileDistribution":"0400:320x180,0700:640x360,0900:720x404,1500:1024x576,2500:1280x720","applyFolderHierarchy":1,"thumbInterval":10,"cdnShieldHTTP":"","cdnShieldHTTPS":"","cdnShieldProgHTTP":"","cdnShieldProgHTTPS":"","cdnProvider":"ce","cdnFolder":"292446133","cdnPathHTTP":"vcdn.vod.spiegel.de\/","cdnPathHLS":"vcdn.hls.spiegel.de\/","cdnPathDASH":"vcdn.hls.spiegel.de\/"},"protectiondata":{"method":"","token":"","provider":"","server":"","key":""},"features":{"width":1920,"height":1080,"aspectRatio":"16:9","orientation":"landscape","isHD":0,"isFullHD":1,"is2K":0,"is4K":0,"isPanorama":0,"hasAudio":1,"hasStereo":1,"hasSurroundSound":0,"hasMultiAudio":0},"statusdata":{"ageok":1,"commok":1,"embedok":1,"devok":1,"geook":1,"canBeDownloaded":0,"shouldBeCached":0,"shouldAllowEmbed":1}}}`

**Closed** 2018-06-04 19:57 UTC

**Comment by Currrupted** [comment] 2018-06-06 17:01
I have the same issue with 2018.06.04, and none of the various options seemed to have resolved it.
This is my return:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.spiegel.tv/videos/1004747-planet-erde']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.06.04
[debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg 4.0, ffprobe 4.0
[debug] Proxy map: {}
[Nexx] 1004747: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('azureLocator',)); please report this issue on https://yt-dl
.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with t
he --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\extractor\common.py", lin
e 500, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\extractor\nexx.py", line
231, in _real_extract
KeyError: 'azureLocator'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\extractor\common.py", lin
e 500, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\extractor\nexx.py", line
231, in _real_extract
KeyError: 'azureLocator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\YoutubeDL.py", line 792,
in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\extractor\common.py", lin
e 513, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('azureLocator',)); please report t
his issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure
 to call youtube-dl with the --verbose flag and include its complete output.
```

Example URL: [http://www.spiegel.tv/videos/1004747-planet-erde](url)

**Comment by Hrxn** [comment] 2018-06-07 04:46
A release version with commit https://github.com/rg3/youtube-dl/commit/06ea7bdd99c16b718c977a652f0ef66341ac2b6c has not happened yet, it seems..

Try running git master

**Comment by Currrupted** [comment] 2018-06-07 20:28
@Hrxn At last I was able to compile master as an application.
**And it works perfectly!** Thank you very much!

**Comment by RokerHRO** [comment] 2018-06-11 11:22
Yep, works here too. Thanks a lot! :-)
