### ISSUE TITLE
Downloader errors

### ISSUE THREAD

**Issue by Rubueno** [rg3/youtube-dl#12269] opened 2017-02-25 23:24 UTC
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.24.1**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

```
B:\Temp>youtube-dl.exe --no-check-certificate https://www.youtube.com/watch?v=-wY53N1y6mU -o "%(title)s.%(ext)s" --audio-quality 0 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-check-certificate', 'https://www.youtube.com/watch?v=-wY53N1y6mU', '-o', '%(title)s.%(ext)s', '--audio-quality', '0', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.02.24.1
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82579-g28d8789, ffprobe N-82579-g28d8789
[debug] Proxy map: {}
[youtube] -wY53N1y6mU: Downloading webpage
[youtube] -wY53N1y6mU: Downloading video info webpage
ERROR: unable to download video info webpage: [WinError 10054] An existing connection was forcibly closed by the remote host (caused by ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl89hv5ts\build\youtube_dl\extractor\common.py", line 496, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl89hv5ts\build\youtube_dl\YoutubeDL.py", line 2093, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl89hv5ts\build\youtube_dl\utils.py", line 1082, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1186, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1227, in getresponse
  File "C:\Python\Python34\lib\http\client.py", line 386, in begin
  File "C:\Python\Python34\lib\http\client.py", line 348, in _read_status
  File "C:\Python\Python34\lib\socket.py", line 378, in readinto
  File "C:\Python\Python34\lib\ssl.py", line 748, in recv_into
  File "C:\Python\Python34\lib\ssl.py", line 620, in read

<end of log>
```

---

### Description of your *issue*, suggested solution and other information

When downloading a video, youtube-dl normally goes through the download process and does not prompt me with any errors. I had no issues running it exactly a week ago. The error requested me to report this, so I'm doing so.

**Comment by yan12125** [comment] 2017-02-26 06:15
In general that indicates unstable or censored networks. That's a duplicate of #8203. Please move there for further discussions.

**Closed by yan12125** 2017-02-26 06:15 UTC
