### ISSUE TITLE
Unable to download go90.com's videos.

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#10215] opened 2016-08-03 02:50 UTC
$ youtube-dl -v https://www.go90.com/profiles/va_0a41e9fb10434ab4a483fc2c60e07885
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://www.go90.com/profiles/va_0a41e9fb10434ab4a483fc2c60e07885']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.01
[debug] Python version 3.4.2 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.5
[debug] exe versions: ffmpeg 3.0.2-4, ffprobe 3.0.2-4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] va_0a41e9fb10434ab4a483fc2c60e07885: Requesting header
WARNING: Falling back on generic information extractor.
[generic] va_0a41e9fb10434ab4a483fc2c60e07885: Downloading webpage
[generic] va_0a41e9fb10434ab4a483fc2c60e07885: Extracting information
ERROR: Unsupported URL: https://www.go90.com/profiles/va_0a41e9fb10434ab4a483fc2c60e07885
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 682, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2336, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.go90.com/profiles/va_0a41e9fb10434ab4a483fc2c60e07885

**Comment by yan12125** [comment] 2016-08-03 03:22
Duplicate of #10127. Please move there for further discussion.

**Closed by yan12125** 2016-08-03 03:22 UTC
