### ISSUE TITLE
Can't grab filename when using youtube-dl as python module

### ISSUE THREAD

**Issue by kereilly** [rg3/youtube-dl#9550] opened 2016-05-20 16:45 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.05.16*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.16**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

I'm using youtube-dl as a python module in a script. i'm running youtube-dl 2016.05.16 and python 2.7.10 on mac os 10.11. The problem i'm having is getting youtube-dl to report the name of the file it downloads. i'm using the ydl.extract_info function but the file extension will be different from what is reported by youtube-dl and what is actually saved. here is the code

    destination = archival_location + ".%(ext)s"
    ydl_opts = {
        'logger' : MyLogger(),
        'progress_hooks': [my_hook],
        'outtmpl' : destination,
        'ignoreerrors' : True
    }
    try:
        with YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=False)
            download_target = ydl.prepare_filename(info)
            ydl.download([url])
       
so my download_target variable will have something like "downloaded_file.mp4" but the actually file is "downloaded_file.mkv". I'm guessing since it was a youtube download ffmpeg muxed the audio and video together making it an mkv file? But i need to preserve file extensions when i can so i know its type for further processing. thats why i'm using the ".%(ext)s" in the 'outtmpl' option. anything i'm doing wrong here or is this just what happens when ffmpeg gets used.

**Comment by dstftw** [comment] 2016-05-20 16:51
Duplicate of #5710.

**Closed by dstftw** 2016-05-20 16:51 UTC
