### ISSUE TITLE
Embedded videos from dailymotion

### ISSUE THREAD

**Issue by dkarnout** [rg3/youtube-dl#8199] opened 2016-01-10 11:41 UTC
Dailymotion allows in some videos public view for embedded ones, or else returns **HTTP error 404 Not Found**.

For example I am able to view the embedded video of the following link:
  http://greekdocumentaries1.blogspot.gr/2014/07/blog-post_26.html

I am also able to view the <iframe> of the embedded video:
  http://www.dailymotion.com/embed/video/k81FJOfJK4ijDQ8iMKL

But get 404 error on this:
  http://www.dailymotion.com/video/x211mo3

Is it possible for youtube-dl to capture the video from the link:
  http://www.dailymotion.com/embed/video/k81FJOfJK4ijDQ8iMKL
instead of:
  http://www.dailymotion.com/video/x211mo3

Thank you in advance.

The verbose result is:
youtube-dl -v http://www.dailymotion.com/embed/video/k81FJOfJK4ijDQ8iMKL
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.dailymotion.com/embed/video/k81FJOfJK4ijDQ8iMKL']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.09
[debug] Python version 2.7.9 - Linux-3.2.0-4-486-i686-with-debian-8.2
[debug] exe versions: avconv 11.4-6, avprobe 11.4-6
[debug] Proxy map: {}
[dailymotion] k81FJOfJK4ijDQ8iMKL: Downloading webpage
[dailymotion] k81FJOfJK4ijDQ8iMKL: Downloading m3u8 information
[debug] Invoking downloader on u'http://proxy-013.dc3.dailymotion.com/sec(9c53267b3d2ab15c818b99deda5ca81e)/video/300/886/122688003_mp4_h264_aac_hq.m3u8#cell=core'
[download] Destination: \u039dational.Geographic.H.Koilada.Twn.Lykwn.x264.DSR-GrLTv-k81FJOfJK4ijDQ8iMKL.mp4
[debug] avconv command line: avconv -y -headers 'Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Cookie: dmvk=569240d29eacf; ts=997088; v1st=7D86B1D3F3E7890BC1C45CBFF1540F9A
' -i 'http://proxy-013.dc3.dailymotion.com/sec(9c53267b3d2ab15c818b99deda5ca81e)/video/300/886/122688003_mp4_h264_aac_hq.m3u8#cell=core' -f mp4 -c copy -bsf:a aac_adtstoasc 'file:\u039dational.Geographic.H.Koilada.Twn.Lykwn.x264.DSR-GrLTv-k81FJOfJK4ijDQ8iMKL.mp4.part'
avconv version 11.4-6:11.4-1~deb8u1, Copyright (c) 2000-2014 the Libav developers
  built on Jun  4 2015 19:43:21 with gcc 4.9.2 (Debian 4.9.2-10)
[http @ 0xa07e900] HTTP error 404 Not Found
http://proxy-013.dc3.dailymotion.com/sec(9c53267b3d2ab15c818b99deda5ca81e)/video/300/886/122688003_mp4_h264_aac_hq.m3u8#cell=core: Input/output error

ERROR: avconv exited with code 1
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 410, in main
    _real_main(argv)
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 400, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1677, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 722, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1347, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1609, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1551, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/hls.py", line 63, in real_download
    self.report_error('%s exited with code %d' % (ffpp.basename, retval))
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 155, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 540, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 502, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

**Comment by jaimeMF** [comment] 2016-01-10 13:08
Duplicate of #8156.

**Closed by jaimeMF** 2016-01-10 13:08 UTC
