### ISSUE TITLE
bbc website: Unable to extract "OpenGraph title"

### ISSUE THREAD

**Issue by robinpaulson** [rg3/youtube-dl#8189] opened 2016-01-09 04:01 UTC
[$] youtube-dl -v http://www.bbc.co.uk/blogs/adamcurtis/entries/5a7b18b5-0ec3-3d3e-a307-54820a7c6a59                                     
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.bbc.co.uk/blogs/adamcurtis/entries/5a7b18b5-0ec3-3d3e-a307-54820a7c6a59']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.09
[debug] Python version 2.7.6 - Linux-4.4.0-0-generic-i686-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, ffmpeg 2.7.1, rtmpdump 2.4
[debug] Proxy map: {}
[bbc] 5a7b18b5-0ec3-3d3e-a307-54820a7c6a59: Downloading webpage
[download] Downloading playlist: BBC Blogs - Adam Curtis - HAPPIDROME - Part One
[bbc] playlist BBC Blogs - Adam Curtis - HAPPIDROME - Part One: Collected 7 video ids (downloading 7 of them)
[download] Downloading video 1 of 7
[bbc.co.uk] p0295xqc: Downloading video page
[bbc.co.uk] p0295xqg: Downloading media selection XML
[bbc.co.uk] p0295xqg: Downloading media selection XML
ERROR: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 663, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/bbc.py", line 474, in _real_extract
    title = self._og_search_title(webpage)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 678, in _og_search_title
    return self._og_search_property('title', html, **kargs)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 666, in _og_search_property
    escaped = self._search_regex(self._og_regexes(prop), html, name, flags=re.DOTALL, **kargs)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I tried the most recent, non-packaged, version also (2016-01-09), that produced the same problem.

**Comment by dstftw** [comment] 2016-01-09 14:21
Duplicate of #8147.

**Closed by dstftw** 2016-01-09 14:21 UTC
