### ISSUE TITLE
HTTP Error 403 Some Youtube Videos can not be Downloaded

### ISSUE THREAD

**Issue by moovinghead** [rg3/youtube-dl#6555] opened 2015-08-14 08:56 UTC
I can curently download all intendet Videos but the last 2 or 3 of one youtuber (xisumavoid).
If i type 
"C:\Users\Christian>\youtube-dl.exe http://www.youtube.com/watch?v=h1XjwYdY3hw"
i get this Error but only at Videos of xisumavoid:

[youtube] h1XjwYdY3hw: Downloading webpage
[youtube] h1XjwYdY3hw: Downloading video info webpage
[youtube] h1XjwYdY3hw: Extracting video information
[youtube] h1XjwYdY3hw: Downloading DASH manifest
WARNING: [youtube] h1XjwYdY3hw: Skipping DASH manifest: ExtractorError(u'Could n
ot download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); pl
ease report this issue on https://yt-dl.org/bug . Make sure you are using the la
test version; type  youtube-dl -U  to update. Be sure to call youtube-dl with th
e --verbose flag and include its complete output.',)
[youtube] h1XjwYdY3hw: Downloading js player new
[youtube] h1XjwYdY3hw: Downloading DASH manifest
WARNING: [youtube] h1XjwYdY3hw: Skipping DASH manifest: ExtractorError(u'Could n
ot download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); pl
ease report this issue on https://yt-dl.org/bug . Make sure you are using the la
test version; type  youtube-dl -U  to update. Be sure to call youtube-dl with th
e --verbose flag and include its complete output.',)
ERROR: unable to download video data: HTTP Error 403: Forbidden

**Comment by naxa** [comment] 2015-08-14 09:16
Got the same issue, here is the verbose output:

    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: [u'https://www.youtube.com/watch?v=vyBKvx38txk', u'--verbose']
    [debug] Encodings: locale cp1250, fs mbcs, out None, pref cp1250
    [debug] youtube-dl version 2015.08.09
    [debug] Git HEAD: e509df3
    [debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
    [debug] exe versions: ffmpeg N-67289-g7f24e1e, ffprobe N-67289-g7f24e1e
    [debug] Proxy map: {}
    [youtube] vyBKvx38txk: Downloading webpage
    [youtube] vyBKvx38txk: Downloading video info webpage
    [youtube] vyBKvx38txk: Extracting video information
    [youtube] {22} signature length 40.42, html5 player new
    [youtube] {43} signature length 40.42, html5 player new
    [youtube] {18} signature length 40.42, html5 player new
    [youtube] {5} signature length 40.42, html5 player new
    [youtube] {36} signature length 40.42, html5 player new
    [youtube] {17} signature length 40.42, html5 player new
    [youtube] {136} signature length 40.42, html5 player new
    [youtube] {247} signature length 40.42, html5 player new
    [youtube] {135} signature length 40.42, html5 player new
    [youtube] {244} signature length 40.42, html5 player new
    [youtube] {134} signature length 40.42, html5 player new
    [youtube] {243} signature length 40.42, html5 player new
    [youtube] {133} signature length 40.42, html5 player new
    [youtube] {242} signature length 40.42, html5 player new
    [youtube] {160} signature length 40.42, html5 player new
    [youtube] {278} signature length 40.42, html5 player new
    [youtube] {140} signature length 40.42, html5 player new
    [youtube] {171} signature length 40.42, html5 player new
    [youtube] vyBKvx38txk: Downloading DASH manifest
    WARNING: [youtube] vyBKvx38txk: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
    [debug] Invoking downloader on u'https://r2---sn-c0q7ln7d.googlevideo.com/videoplayback?lmt=1389224752070296&sver=3&upn=UOjYDLEnFcY&requiressl=yes&keepalive=yes&expire=1439565226&ms=au&mt=1439543565&dur=3493.280&mv=m&clen=330348314&ip=89.135.155.22&initcwndbps=7107500&gir=yes&mm=31&ipbits=0&mn=sn-c0q7ln7d&itag=136&sparams=clen%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&id=bf204abf1dfcb719&source=youtube&mime=video%2Fmp4&pl=15&key=yt5&fexp=9408710%2C9408858%2C9412539%2C9412773%2C9413123%2C9413315%2C9415365%2C9415485%2C9416023%2C9416126%2C9416729%2C9416984%2C9417118%2C9417707%2C9418026%2C9418153%2C9418410%2C9418561%2C9418903%2C9419342&signature=A1C8D077C2FF3A9C440630ED0C26E548DF1806D1.F183C6DA798A83E559E3FEB7739B8F5FAC2DEC6F&ratebypass=yes'
    ERROR: unable to download video data: HTTP Error 403: Forbidden
    Traceback (most recent call last):
      File "C:\_utils_\lang-python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 1579, in process_info
        partial_success = dl(fname, new_info)
      File "C:\_utils_\lang-python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 1527, in dl
        return fd.download(name, info)
      File "C:\_utils_\lang-python27\lib\site-packages\youtube_dl\downloader\common.py", line 342, in download
        return self.real_download(filename, info_dict)
      File "C:\_utils_\lang-python27\lib\site-packages\youtube_dl\downloader\http.py", line 60, in real_download
        data = self.ydl.urlopen(request)
      File "C:\_utils_\lang-python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 1860, in urlopen
        return self._opener.open(req, timeout=self._socket_timeout)
      File "C:\_utils_\lang-python27\lib\urllib2.py", line 437, in open
        response = meth(req, response)
      File "C:\_utils_\lang-python27\lib\urllib2.py", line 550, in http_response
        'http', request, response, code, msg, hdrs)
      File "C:\_utils_\lang-python27\lib\urllib2.py", line 475, in error
        return self._call_chain(*args)
      File "C:\_utils_\lang-python27\lib\urllib2.py", line 409, in _call_chain
        result = func(*args)
      File "C:\_utils_\lang-python27\lib\urllib2.py", line 558, in http_error_default
        raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
    HTTPError: HTTP Error 403: Forbidden

**Comment by yan12125** [comment] 2015-08-14 09:21
Possibly a duplicate of #6451. Can you try the suggestion in https://github.com/rg3/youtube-dl/issues/6451#issuecomment-128397059?

**Comment by dstftw** [comment] 2015-08-14 10:48
Duplicate of #6451. Remove cache with `--rm-cache-dir`.

**Closed by dstftw** 2015-08-14 10:48 UTC

**Comment by naxa** [comment] 2015-08-14 13:12
I confirm that with `youtube-dl --no-cache-dir` and/or with `youtube-dl --rm-cache-dir` it works. Thanks!
