### ISSUE TITLE
Is it possible to extract the audio from a video directly to stdout

### ISSUE THREAD

**Issue by ahmetalpbalkan** [rg3/youtube-dl#8838] opened 2016-03-12 03:13 UTC
I am looking for something that downloads the video to memory (or a temporary place) and streams the extracted audio directly to standard output as it is converted.

So something like:

    youtube-dl -x -o - http://url

however it gives me error:

    youtube-dl: error: Cannot download a video and extract audio into the same file! Use "-.%(ext)s" instead of "-" as the output template

If there are any workarounds to this, I'd appreciate. My use case is, I'm trying to extract audio of a video to stdout in a single command (say, docker container entrypoint) .

**Comment by dstftw** [comment] 2016-03-12 14:51
Not possible. Duplicate of #8269.

**Closed by dstftw** 2016-03-12 14:51 UTC

**Comment by bertho-zero** [comment] 2016-10-14 21:25
One day perhaps ..
