### ISSUE TITLE
[youtube] DO-5JVqx_MQ: Skipping DASH manifest

### ISSUE THREAD

**Issue by cdeex** [rg3/youtube-dl#10115] opened 2016-07-18 07:50 UTC
```
>youtube-dl.exe -u xxx@xxx.com --proxy 172.23.0.100:8080 https://www.youtube.com/watch?v=DO-5JVqx_MQ -F -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-u', 'PRIVATE', '--proxy', '172.23.0.100:8080', 'https://www.youtube.com/watch?v=DO-5JVqx_MQ', '-F', '-v']
Type account password and press [Return]:
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2016.07.17
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {'http': '172.23.0.100:8080', 'https': '172.23.0.100:8080'}
[youtube] Downloading login page
[youtube] Logging in
[youtube] DO-5JVqx_MQ: Downloading webpage
[youtube] DO-5JVqx_MQ: Downloading video info webpage
[youtube] DO-5JVqx_MQ: Extracting video information
[youtube] {60} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {52} signature length 40.39, html5 player en_US-vflWoKF7f
[youtube] DO-5JVqx_MQ: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vflWoKF7f/base.js
[youtube] {146} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {197} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {226} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {227} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {145} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {196} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {224} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {225} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {144} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {195} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {220} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {221} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {222} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {223} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {143} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {194} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {142} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {161} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {148} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {149} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {150} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {198} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {199} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {259} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {261} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] {329} signature length 40.41, html5 player en_US-vflWoKF7f
[youtube] DO-5JVqx_MQ: Downloading MPD manifest
[youtube] DO-5JVqx_MQ: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vflWoKF7f/base.js
[youtube] DO-5JVqx_MQ: Downloading MPD manifest
WARNING: [youtube] DO-5JVqx_MQ: Skipping DASH manifest: ExtractorError('Failed to download MPD manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the--verbose flag and include its complete output.',)
[info] Available formats for DO-5JVqx_MQ:
format code  extension  resolution note
148          m4a        audio only   57k , mp4a.40.5, 37.20MiB
149          m4a        audio only  136k , mp4a.40.2, 95.90MiB
198          webm       audio only  166k , vorbis, 85.50MiB
259          m4a        audio only  200k , mp4a.40.5, 141.80MiB
150          m4a        audio only  264k , mp4a.40.2, 188.84MiB
199          webm       audio only  273k , vorbis, 126.29MiB
329          m4a        audio only  391k , eac3 , 280.34MiB
261          m4a        audio only  392k , mp4a.40.2, 281.87MiB
161          mp4        256x144    144p  136k , avc1.4d400c, 24fps, video only,
82.88MiB
142          mp4        426x240    240p  279k , avc1.4d4015, 24fps, video only,
180.01MiB
143          mp4        640x360    360p  647k , avc1.4d401e, 24fps, video only,
355.41MiB
144          mp4        854x480    480p 1185k , avc1.4d401e, 24fps, video only,
676.20MiB
194          webm       640x360    360p 1392k , vp8, 25fps, video only, 441.51Mi
B
222          mp4        854x480    480p 1832k , avc1.4d401e, 24fps, video only,
1.02GiB
195          webm       854x480    480p 2304k , vp8, 25fps, video only, 739.53Mi
B
145          mp4        1280x720   720p 2377k , avc1.4d401f, 24fps, video only,
1.31GiB
220          webm       854x480    480p 2390k , vp8, 25fps, video only, 891.15Mi
B
223          mp4        854x480    480p 3562k , avc1.4d401e, 24fps, video only,
2.06GiB
224          mp4        1280x720   720p 3586k , avc1.4d401f, 24fps, video only,
2.04GiB
221          webm       854x480    480p 4466k , vp8, 25fps, video only, 1.13GiB
146          mp4        1920x1080  1080p 4666k , avc1.640028, 24fps, video only,
 2.52GiB
225          mp4        1280x720   720p 5917k , avc1.4d401f, 24fps, video only,
3.30GiB
226          mp4        1920x1080  1080p 6149k , avc1.640028, 24fps, video only,
 3.61GiB
196          webm       1280x720   720p 6331k , vp8, 25fps, video only, 1.54GiB
227          mp4        1920x1080  1080p 8424k , avc1.640028, 24fps, video only,
 4.91GiB
197          webm       1920x1080  1080p 12514k , vp8, 25fps, video only, 3.01Gi
B
52           mp4        640x360    medium
60           mp4        854x480    large  (best)

```

**Comment by yan12125** [comment] 2016-07-19 08:28
Could you try with ```--proxy http://172.23.0.100:8080``` or ```--proxy https://172.23.0.100:8080```?

**Comment by dstftw** [comment] 2016-09-03 21:08
Duplicate of #8944.

**Closed by dstftw** 2016-09-03 21:08 UTC
Labels: geo-restricted
