### ISSUE TITLE
Improvement Suggestion: faster dateafter (and datebefore) parameters

### ISSUE THREAD

**Issue by ben569** [rg3/youtube-dl#5922] opened 2015-06-07 22:11 UTC
I regularly download all the videos from youtube channels. But I only need the most recent videos, I keep the old ones on a server at home. For that, I use the following line in my bash script:
`youtube-dl -c --dateafter $date_after --yes-playlist -o '~/Youtube-DL/%(uploader)s/%(title)s.%(ext)s' -f 141/140 --external-downloader aria2c --external-downloader-args '-s 8' $chaine`
In `$chaine`, I usually put URLs along the lines of this: `https://youtube.com/user/SOME_YOUTUBER/videos`.
Of course, I specify the last time I downloaded the channel in `$date_after`. By the way, don't hesitate to suggest a cleaner way to eliminate the videos I have already downloaded.
However, since in these URLs the videos are classed by date by youtube, much time is wasted on checking wether or not a video has been posted recently enough, particularly when a channel has several thousands videos.
Maybe this time could be spared by assuming that as soon as a video is found to be out of date, all the remaining are, too.
On a side note, did I setup aria2c right for establishing 8 simultaneous connections? EDIT: I have CN:1 during the downloads.
If needed, I can provide you with my entire script - 23 lines.

**Comment by yan12125** [comment] 2015-06-08 05:52
If I'm correct, in case of youtube, user pages do not give accurate upload date. (Only inaccurate descriptions like "2 weeks ago"). As a result, it's necessary to extract all videos and compare one by one. Would you like to provide a concrete example URL?

**Comment by ben569** [comment] 2015-06-08 10:55
While the exact upload dates of the videos are not given, the videos on this page are *sorted by upload date*. As a consequence, youtube-dl could be optimized by checking the upload date of each video (and process it) *only until a single video is out of the date range* as all the other videos will be older than the tested one*. It's valid in two cases:
* Youtube-dl processes the playlist from the lastest to the oldest video *and* the --dateafter option is given
* Youtube-dl processes the playlist from the oldest to the lastest video *and* the --datebefore option is given
Did I make myself clear?

An example URL: https://www.youtube.com/user/MrSuicideSheep/videos

**Comment by dstftw** [comment] 2016-01-02 13:59
Duplicate of #1502.

**Closed by dstftw** 2016-01-02 13:59 UTC
Labels: request
