### ISSUE TITLE
Crunchyroll extractor not getting any video formats, even though they are displayed.

### ISSUE THREAD

**Issue by yirako** [rg3/youtube-dl#10306] opened 2016-08-12 07:42 UTC
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.12*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.12**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.crunchyroll.com/gintama/episode-69-please-help-by-separating-your-trash-510200', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-f', u'720p/480p/360p', u'--write-sub', u'--sub-lang', u'enUS', u'--no-part', u'-o', u'%(title)s %(resolution)s.%(ext)s', u'-v']
[debug] Encodings: locale cp1252, fs mbcs, out None, pref cp1252
[debug] youtube-dl version 2016.08.12
[debug] Python version 2.7.11 - Windows-8.1-6.3.9600
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[Crunchyroll] Logging in
[Crunchyroll] 510200: Downloading webpage
[Crunchyroll] 510200: Downloading media info for 360p
[Crunchyroll] 510200: Downloading media info for 480p
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "c:\Python27\lib\site-packages\youtube_dl\extractor\common.py", line 343, in extract
    return self._real_extract(url)
  File "c:\Python27\lib\site-packages\youtube_dl\extractor\crunchyroll.py", line 372, in _real_extract
    self._sort_formats(formats)
  File "c:\Python27\lib\site-packages\youtube_dl\extractor\common.py", line 866, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

Episode can't be dowloaded due to an error at the point of getting the formats supported for the specified episode. This error occurs even when trying to use -F to get the formats.

Deeper research got that crunchyroll extractor doesn't get a `video_url` and `formats` return no-formats to sort, so then causes the exception. Episode is confirmed to be playable at the site. Some other episodes ahead cause the same issue, too. But from certain point more ahead, it starts working again.

Seems to be a problem with old crunchyroll structure/formating, as any recent episode in the site is working fine with this same configuration/switches.
I couldn't debug further. Any help would be appreciated.

url of video used in this issue:
http://www.crunchyroll.com/gintama/episode-69-please-help-by-separating-your-trash-510200

**Comment by dstftw** [comment] 2016-08-12 16:10
Duplicate of #10301.

**Closed by dstftw** 2016-08-12 16:10 UTC
