### ISSUE TITLE
add support for businessinsider.com

### ISSUE THREAD

**Issue by Siddhant** [rg3/youtube-dl#5423] opened 2015-04-14 04:14 UTC
URL: http://www.businessinsider.com/excel-index-match-vlookup-video-how-to-2015-2?IR=T

**Comment by yan12125** [comment] 2015-04-14 04:48
Thanks for the report. The website will be supported in the next release of youtube-dl. (fixed in edfcf7abe2f31bb8309ca032e738c90dc3a5722e)

**Closed by yan12125** 2015-04-14 04:48 UTC

**Comment by sant527** [comment] 2017-01-03 12:40
youtube-dl "http://www.businessinsider.com/excel-index-match-vlookup-video-how-to-2015-2?IR=T" 
[generic] excel-index-match-vlookup-video-how-to-2015-2?IR=T: Requesting header
WARNING: Falling back on generic information extractor.
[generic] excel-index-match-vlookup-video-how-to-2015-2?IR=T: Downloading webpage
[generic] excel-index-match-vlookup-video-how-to-2015-2?IR=T: Extracting information
[Ooyala] 50YnY4czr4ms1vJ7yz3xzq0excz_pUMs: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment] 2017-01-03 12:49
Still working for me. Could you try with version 2017.01.02?
```
$ youtube-dl -v "http://www.businessinsider.com/tests-planes-undergo-before-ready-commercial-flight-chicken-guns-2016-12?IR=T" 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.businessinsider.com/tests-planes-undergo-before-ready-commercial-flight-chicken-guns-2016-12?IR=T']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.01.02
[debug] Git HEAD: 032478beb
[debug] Python version 3.6.0 - Linux-4.9.0-1-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] tests-planes-undergo-before-ready-commercial-flight-chicken-guns-2016-12?IR=T: Requesting header
WARNING: Falling back on generic information extractor.
[generic] tests-planes-undergo-before-ready-commercial-flight-chicken-guns-2016-12?IR=T: Downloading webpage
[generic] tests-planes-undergo-before-ready-commercial-flight-chicken-guns-2016-12?IR=T: Extracting information
[Ooyala] NsaDg0NjE6AtGeXKR_mf2fNZ0ySbiYok: Downloading JSON metadata
[Ooyala] NsaDg0NjE6AtGeXKR_mf2fNZ0ySbiYok: Downloading JSON metadata
[Ooyala] NsaDg0NjE6AtGeXKR_mf2fNZ0ySbiYok: Downloading f4m manifest
[Ooyala] NsaDg0NjE6AtGeXKR_mf2fNZ0ySbiYok: Downloading m3u8 information
[debug] Invoking downloader on 'http://player.ooyala.com/player/all/NsaDg0NjE6AtGeXKR_mf2fNZ0ySbiYok_2200.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 12
[download] Destination: HIGH-SPEED CHICKEN GUNS - The extreme tests planes undergo before they're ready for commercial flight-NsaDg0NjE6AtGeXKR_mf2fNZ0ySbiYok.mp4
[download] 100% of 31.88MiB in 00:04
[debug] ffmpeg command line: ffprobe -show_streams 'file:HIGH-SPEED CHICKEN GUNS - The extreme tests planes undergo before they'"'"'re ready for commercial flight-NsaDg0NjE6AtGeXKR_mf2fNZ0ySbiYok.mp4'
[ffmpeg] Fixing malformated aac bitstream in "HIGH-SPEED CHICKEN GUNS - The extreme tests planes undergo before they're ready for commercial flight-NsaDg0NjE6AtGeXKR_mf2fNZ0ySbiYok.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:HIGH-SPEED CHICKEN GUNS - The extreme tests planes undergo before they'"'"'re ready for commercial flight-NsaDg0NjE6AtGeXKR_mf2fNZ0ySbiYok.mp4' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:HIGH-SPEED CHICKEN GUNS - The extreme tests planes undergo before they'"'"'re ready for commercial flight-NsaDg0NjE6AtGeXKR_mf2fNZ0ySbiYok.temp.mp4'
```
