### ISSUE TITLE
insecure string pickle

### ISSUE THREAD

**Issue by ravarelab** [rg3/youtube-dl#8815] opened 2016-03-10 09:32 UTC
Hi,

I am a youtube-dl newbie. Trying to extract some math classes (i.e., https://youtu.be/bx-vGQFRXlo) I am getting an "insecure string pickle error. Using last version of youtube-dl. Can anyone help? An screen dump is below.

![screen shot 2016-03-10 at 10 30 04](https://cloud.githubusercontent.com/assets/17761058/13665154/3e8aaa36-e6ab-11e5-98bb-ed45476684d6.png)

**Comment by dstftw** [comment] 2016-03-10 09:38
Duplicate of #6840.

**Closed by dstftw** 2016-03-10 09:38 UTC
