### ISSUE TITLE
vip not support

### ISSUE THREAD

**Issue by yangfan3333** [rg3/youtube-dl#10588] opened 2016-09-07 18:26 UTC
version 2016.09.04.1

When I use youtube-dl  download iqiyi video VIP

ERROR：fixed output name but more than noe file to download

URL:http://www.iqiyi.com/v_19rrm38u7k.html

COULD YOU fix the iqiyi vip support? thanks . That  has been broken for a long time.

**Comment by yan12125** [comment] 2016-09-07 18:29
Duplicate of #9839.

> COULD YOU fix the iqiyi vip support?

Unless I or someone else can login to Iqiyi. Seems people outside Mainland China can't use VIP accounts, and no proxies are usable for login the last time I tried.

**Closed by yan12125** 2016-09-07 18:29 UTC
