### ISSUE TITLE
YouTube: Internal Server Error On Audio

### ISSUE THREAD

**Issue by ldo** [rg3/youtube-dl#12612] opened 2017-04-01 00:19 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.26*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Trouble downloading [this YouTube video](https://www.youtube.com/watch?v=A1qHYlPBSiI). Video came down fine, audio fails with “internal server error”. Also plays OK in Firefox. Verbose output:

ldo@theon:Radar Men From The Moon> youtube-dl -v https://www.youtube.com/watch?v=A1qHYlPBSiI
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=A1qHYlPBSiI']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.26
[debug] Git HEAD: 745399958
[debug] Python version 2.7.13 - Linux-4.9.0-2-amd64-x86_64-with-debian-9.0
[debug] exe versions: ffmpeg n3.3-dev-910-g1a79b8f8d2, ffprobe n3.3-dev-910-g1a79b8f8d2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] A1qHYlPBSiI: Downloading webpage
[youtube] A1qHYlPBSiI: Downloading video info webpage
[youtube] A1qHYlPBSiI: Extracting video information
[youtube] A1qHYlPBSiI: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on u'https://r6---sn-8vq54voxo1-53as.googlevideo.com/videoplayback?id=035a876253c14a22&itag=134&source=youtube&requiressl=yes&mm=31&mn=sn-8vq54voxo1-53as&ms=au&mv=m&initcwndbps=1802500&pl=22&ratebypass=yes&mime=video/mp4&gir=yes&clen=27056638&lmt=1411954879018797&dur=810.543&upn=NEUHvN-74vM&signature=8C21D35DEACC01AB8C38070E9E94F465DE4AC649.6514D072834D4DEAA857159798E1BEC20F10D200&key=dg_yt0&mt=1491005249&ip=121.75.148.251&ipbits=0&expire=1491026935&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mn,ms,mv,initcwndbps,pl,ratebypass,mime,gir,clen,lmt,dur'
[download] Radar Men from the Moon (Commando Cody) episode four-A1qHYlPBSiI.f134.mp4 has already been downloaded
[download] 100% of 25.80MiB
[debug] Invoking downloader on u'https://r6---sn-8vq54voxo1-53as.googlevideo.com/videoplayback?mn=sn-8vq54voxo1-53as&source=youtube&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&requiressl=yes&ipbits=0&mm=31&ip=121.75.148.251&itag=251&ms=au&mt=1491005249&mv=m&id=o-AOueoFnk7rOfZyFqEuaKTlo-GoY-kSp71KKXMZWgxCL5&pl=22&keepalive=yes&ei=lu_eWLTwE8qu4AKHr5ygDw&upn=6-3U5wi0x8I&expire=1491026934&mime=audio%2Fwebm&key=yt6&initcwndbps=1802500&signature=6A293C8E2CABC94103387665EA90B6B8CB97EE29.133BE4E8AA65E89DC9DEFAA8CC027035B77B8C6B&clen=12462807&gir=yes&dur=810.621&lmt=1422260006692908&ratebypass=yes'
[download] Got server HTTP error. Retrying (attempt 1 of 10)...
[download] Got server HTTP error. Retrying (attempt 2 of 10)...
[download] Got server HTTP error. Retrying (attempt 3 of 10)...
[download] Got server HTTP error. Retrying (attempt 4 of 10)...
[download] Got server HTTP error. Retrying (attempt 5 of 10)...
[download] Got server HTTP error. Retrying (attempt 6 of 10)...
[download] Got server HTTP error. Retrying (attempt 7 of 10)...
[download] Got server HTTP error. Retrying (attempt 8 of 10)...
[download] Got server HTTP error. Retrying (attempt 9 of 10)...
[download] Got server HTTP error. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries
Traceback (most recent call last):
  File "/home/ldo/new/source/youtube-dl/youtube_dl/downloader/http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "/home/ldo/new/source/youtube-dl/youtube_dl/YoutubeDL.py", line 2100, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: Internal Server Error

**Comment by dstftw** [comment] 2017-04-01 19:47
Duplicate of #3721.

**Closed by dstftw** 2017-04-01 19:47 UTC
