### ISSUE TITLE
Openload issue

### ISSUE THREAD

**Issue by edwardsdean** [rg3/youtube-dl#12560] opened 2017-03-26 12:14 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.24*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.24**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

The script is crashing while trying to download the following openload video https://openload.co/f/8uuyOoR0Cz8/Naruto_Shippuden_-_001_-_Homecoming-r197.1-r371-r277.mp4

```
C:\Users\edwar\Downloads>youtube-dl -v https://openload.co/f/8uuyOoR0Cz8/Naruto_Shippuden_-_001_-_Homecoming-r197.1-r371-r277.mp4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://openload.co/f/8uuyOoR0Cz8/Naruto_Shippuden_-_001_-_Homecoming-r197.1-r371-r277.mp4']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.03.24
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[Openload] 8uuyOoR0Cz8: Downloading webpage
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\build\youtube_dl\__init__.py", line 464, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\build\youtube_dl\__init__.py", line 454, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\build\youtube_dl\YoutubeDL.py", line 1884, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\build\youtube_dl\YoutubeDL.py", line 761, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\build\youtube_dl\extractor\common.py", line 428, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\build\youtube_dl\extractor\openload.py", line 92, in _real_extract
ValueError: invalid literal for int() with base 8: '7d9'
...
<end of log>
```

---

**Comment by yan12125** [comment] 2017-03-26 14:13
Duplicate of #10408

**Closed by yan12125** 2017-03-26 14:13 UTC
