### ISSUE TITLE
Problems with playlist download!

### ISSUE THREAD

**Issue by ronaldofas** [rg3/youtube-dl#8015] opened 2015-12-26 23:37 UTC
Please help-me with this problem:

[quote]
ronaldo@ronaldo-desktop-pessoal ~ $ youtube-dl -citk --verbose --max-quality mp4 https://www.youtube.com/playlist?list=PLcHPNq67CaVmiZ8An2oTSaqdnio2FmjnP
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-citk', '--verbose', '--max-quality', 'mp4', 'https://www.youtube.com/playlist?list=PLcHPNq67CaVmiZ8An2oTSaqdnio2FmjnP']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-3.16.0-38-generic-x86_64-with-LinuxMint-17.3-rosa
[debug] Proxy map: {}
[youtube:playlist] PLcHPNq67CaVmiZ8An2oTSaqdnio2FmjnP: Downloading page #1
WARNING: [youtube:playlist] PLcHPNq67CaVmiZ8An2oTSaqdnio2FmjnP: Playlist page is missing OpenGraph title, falling back ...
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1511, in _real_extract
    playlist_title = self._og_search_title(page)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 428, in _og_search_title
    return self._og_search_property('title', html, **kargs)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 416, in _og_search_property
    escaped = self._search_regex(self._og_regexes(prop), html, name, flags=re.DOTALL, **kargs)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 356, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 493, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 158, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1517, in _real_extract
    r'<h1 class="pl-header-title">(.*?)</h1>', page, u'title')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 366, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 356, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.[/quote]

Thanks.

**Comment by AGSPhoenix** [comment] 2015-12-27 01:27
Your version of youtube-dl is almost 2 years out of date. Update to the latest version and try running the command again.

Also, the `--max-quality` parameter is no longer necessary, as youtube-dl does this automatically.

**Comment by AGSPhoenix** [comment] 2015-12-27 01:30
Oh, almost forgot, `-t`/`--title` is also the default now, and is marked as deprecated.

**Comment by wilson18** [comment] 2015-12-27 02:39
I have just had the same error on mine which I believe is upto date. - I have reinstalled on a mac using brew and updated on CentOS via yum, problem persists on both 


[wilson18@Nightfury Banjo]$ youtube-dl https://www.youtube.com/playlist?list=PLsEmTFCr3fDOyxDR8gLC_ei2rhCqGuHOu --verbose
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: [u'https://www.youtube.com/playlist?list=PLsEmTFCr3fDOyxDR8gLC_ei2rhCqGuHOu', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.13
[debug] Python version 2.7.5 - Linux-3.10.0-229.14.1.el7.x86_64-x86_64-with-centos-7.1.1503-Core
[debug] exe versions: ffmpeg 2.6.3, ffprobe 2.6.3
[debug] Proxy map: {}
[youtube:playlist] PLsEmTFCr3fDOyxDR8gLC_ei2rhCqGuHOu: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1644, in _real_extract
    return self._extract_playlist(playlist_id)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1619, in _extract_playlist
    page, 'title')
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 593, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by AGSPhoenix** [comment] 2015-12-27 03:34
I've verified that the issue is resolved in the latest version, released three days ago:
```
PS C:\Users\Phoenix> youtube-dl.2015.11.13.exe --version
2015.11.13
PS C:\Users\Phoenix> youtube-dl.2015.11.13.exe https://www.youtube.com/playlist?list=PLsEmTFCr3fDOyxDR8gLC_ei2rhCqGuHOu --verbose --prefer-free-formats
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.youtube.com/playlist?list=PLsEmTFCr3fDOyxDR8gLC_ei2rhCqGuHOu', u'--verbose', u'--prefer-free-formats']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.11.13
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-76776-g3c110b0, ffprobe N-76776-g3c110b0
[debug] Proxy map: {}
[youtube:playlist] PLsEmTFCr3fDOyxDR8gLC_ei2rhCqGuHOu: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 661, in extract_info
  File "youtube_dl\extractor\common.pyo", line 290, in extract
  File "youtube_dl\extractor\youtube.pyo", line 1644, in _real_extract
  File "youtube_dl\extractor\youtube.pyo", line 1619, in _extract_playlist
  File "youtube_dl\extractor\common.pyo", line 593, in _html_search_regex
  File "youtube_dl\extractor\common.pyo", line 584, in _search_regex
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

PS C:\Users\Phoenix> youtube-dl.exe --version
2015.12.23
PS C:\Users\Phoenix> youtube-dl.exe https://www.youtube.com/playlist?list=PLsEmTFCr3fDOyxDR8gLC_ei2rhCqGuHOu --verbose --prefer-free-formats
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.youtube.com/playlist?list=PLsEmTFCr3fDOyxDR8gLC_ei2rhCqGuHOu', u'--verbose', u'--prefer-free-formats']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.12.23
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-76776-g3c110b0, ffprobe N-76776-g3c110b0
[debug] Proxy map: {}
[youtube:playlist] PLsEmTFCr3fDOyxDR8gLC_ei2rhCqGuHOu: Downloading webpage
[download] Downloading playlist: banjo
[youtube:playlist] playlist banjo: Downloading 36 videos
[download] Downloading video 1 of 36
[youtube] C2b_OsR1bHY: Downloading webpage
[youtube] C2b_OsR1bHY: Downloading video info webpage
[youtube] C2b_OsR1bHY: Extracting video information
[youtube] C2b_OsR1bHY: Downloading DASH manifest
[youtube] C2b_OsR1bHY: Downloading DASH manifest
[debug] Invoking downloader on u'https://r1---sn-fvf-jaxe.googlevideo.com/videoplayback?id=0b66ff3ac4756c76&itag=135&source=youtube&requiressl=yes&pcm2cms=yes&pl=20&mn=sn-fvf-jaxe&mm=31&ms=au&mv=m&ratebypass=yes&mime=video/mp4&gir=yes&clen=2972473&lmt=1441015415388234&dur=257.333&fexp=9416126,9420452,9422596,9423662&upn=DJOV_hBP1jo&signature=36820879166F0F94695BD3073B31747312AF0968.3CF17568AEED365BFA3A1C5913189C6C17FB0E72&sver=3&key=dg_yt0&mt=1451187011&ip=23.28.37.160&ipbits=0&expire=1451208669&sparams=ip,ipbits,expire,id,itag,source,requiressl,pcm2cms,pl,mn,mm,ms,mv,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Banjo-Kazooie Music - Mad Monster Mansion-C2b_OsR1bHY.f135.mp4
[download]   8.8% of 2.83MiB at 277.48KiB/s ETA 00:09
ERROR: Interrupted by user
```

It looks like the version in your repositories is outdated. You can either wait for the package maintainer for your distro to update, or switch to using the official builds from [this page](http://rg3.github.io/youtube-dl/download.html). There are instructions for how to install it from the command line there. Make sure you uninstall your distro's version first.

**Comment by dstftw** [comment] 2015-12-27 05:28
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Closed by dstftw** 2015-12-27 05:28 UTC
