### ISSUE TITLE
Error : YouTube said: This video is not available

### ISSUE THREAD

**Issue by tone87** [rg3/youtube-dl#7284] opened 2015-10-24 15:03 UTC
youtube link : https://www.youtube.com/watch?v=OFv2Y4MLpcg

this video work on youtube ..  

output error : 

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=OFv2Y4MLpcg', u'--extract-audio', u'--audio-format', u'mp3', u'--verbose']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out None, pref ANSI_X3.4-1968
[debug] youtube-dl version 2015.10.24
[debug] Python version 2.6.6 - Linux-2.6.32-573.3.1.el6.x86_64-x86_64-with-centos-6.7-Final
[debug] exe versions: ffmpeg n2.5.8-1-gaf098ad, ffprobe n2.5.8-1-gaf098ad
[debug] Proxy map: {}
[youtube] OFv2Y4MLpcg: Downloading webpage
[youtube] OFv2Y4MLpcg: Downloading video info webpage
ERROR: OFv2Y4MLpcg: YouTube said: This video is not available.
Traceback (most recent call last):
File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
ie_result = ie.extract(url)
File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 291, in extract
return self._real_extract(url)
File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1121, in _real_extract
expected=True, video_id=video_id)
ExtractorError: OFv2Y4MLpcg: YouTube said: This video is not available.

**Comment by tone87** [comment] 2015-10-24 15:05
the same output error for https://www.youtube.com/watch?v=G-2nd7pBZYo
why ?

**Comment by dstftw** [comment] 2015-10-24 15:06
Can you watch it in browser while not logged on?

**Comment by tone87** [comment] 2015-10-24 15:07
yes

**Comment by tone87** [comment] 2015-10-24 15:08
![image](https://cloud.githubusercontent.com/assets/8173557/10711101/d402b636-7a71-11e5-8db1-43af839fcbd5.png)

**Comment by dstftw** [comment] 2015-10-24 15:15
I can download it just fine via spanish proxy. Post the output of `youtube-dl -v --call-home https://www.youtube.com/watch?v=G-2nd7pBZYo`.

**Comment by tone87** [comment] 2015-10-24 15:25
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--call-home', u'https://www.youtube.com/watch?v=G-2nd7pBZYo']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out None, pref ANSI_X3.4-1968
[debug] youtube-dl version 2015.10.24
[debug] Python version 2.6.6 - Linux-2.6.32-573.3.1.el6.x86_64-x86_64-with-centos-6.7-Final
[debug] exe versions: ffmpeg n2.5.8-1-gaf098ad, ffprobe n2.5.8-1-gaf098ad
[debug] Proxy map: {}
[debug] Public IP address: 95.110.234.146
[youtube] G-2nd7pBZYo: Downloading webpage
[youtube] G-2nd7pBZYo: Downloading video info webpage
ERROR: G-2nd7pBZYo: YouTube said: This video is not available.
Traceback (most recent call last):
File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
ie_result = ie.extract(url)
File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 291, in extract
return self._real_extract(url)
File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1121, in _real_extract
expected=True, video_id=video_id)
ExtractorError: G-2nd7pBZYo: YouTube said: This video is not available.

**Comment by dstftw** [comment] 2015-10-24 19:28
Duplicate of #7249.

**Closed by dstftw** 2015-10-24 19:28 UTC

**Comment by dstftw** [comment] 2015-11-04 16:50
This issue is probably fixed in 44b2264feae331eeb34e83eed1387def3d61a437.
