### ISSUE TITLE
[PornHub] Title Cannot Be Extracted

### ISSUE THREAD

**Issue by MyPersonalKov** [rg3/youtube-dl#17197] opened 2018-08-09 23:26 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--download-archive', 'C:/Users/gpjaz/Documents/youtube-dl/p_downloads.txt', 'https://www.pornhub.com/users/tweetney/videos/public', '--verbose', '--dump-pages']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2018.08.04
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-91141-gc24d247e2c, ffprobe N-91141-gc24d247e2c
[debug] Proxy map: {}
[PornHubUserVideos] tweetney: Downloading page 2
[download] Downloading playlist: tweetney
[PornHubUserVideos] playlist tweetney: Collected 13 video ids (downloading 13 of them)
[download] Downloading video 1 of 13
[PornHub] ph5b5d6ea592d2a: Downloading pc webpage
[PornHub] Dumping request to http://www.pornhub.com/view_video.php?viewkey=ph5b5d6ea592d2a
PGh0bWw+PGhlYWQ+PHNjcmlwdCB0eXBlPSJ0ZXh0L2phdmFzY3JpcHQiPjwhLS0KZnVuY3Rpb24gbGVhc3RGYWN0b3IobikgewogaWYgKGlzTmFOKG4pIHx8ICFpc0Zpbml0ZShuKSkgcmV0dXJuIE5hTjsKIGlmICh0eXBlb2YgcGhhbnRvbSAhPT0gJ3VuZGVmaW5lZCcpIHJldHVybiAncGhhbnRvbSc7CiBpZiAodHlwZW9mIG1vZHVsZSAhPT0gJ3VuZGVmaW5lZCcgJiYgbW9kdWxlLmV4cG9ydHMpIHJldHVybiAnbm9kZSc7CiBpZiAobj09MCkgcmV0dXJuIDA7CiBpZiAobiUxIHx8IG4qbjwyKSByZXR1cm4gMTsKIGlmIChuJTI9PTApIHJldHVybiAyOwogaWYgKG4lMz09MCkgcmV0dXJuIDM7CiBpZiAobiU1PT0wKSByZXR1cm4gNTsKIHZhciBtPU1hdGguc3FydChuKTsKIGZvciAodmFyIGk9NztpPD1tO2krPTMwKSB7CiAgaWYgKG4laT09MCkgICAgICByZXR1cm4gaTsKICBpZiAobiUoaSs0KT09MCkgIHJldHVybiBpKzQ7CiAgaWYgKG4lKGkrNik9PTApICByZXR1cm4gaSs2OwogIGlmIChuJShpKzEwKT09MCkgcmV0dXJuIGkrMTA7CiAgaWYgKG4lKGkrMTIpPT0wKSByZXR1cm4gaSsxMjsKICBpZiAobiUoaSsxNik9PTApIHJldHVybiBpKzE2OwogIGlmIChuJShpKzIyKT09MCkgcmV0dXJuIGkrMjI7CiAgaWYgKG4lKGkrMjQpPT0wKSByZXR1cm4gaSsyNDsKIH0KIHJldHVybiBuOwp9CmZ1bmN0aW9uIGdvKCkgewogdmFyIHA9MTY3OTExNzAxMzkzNjsgdmFyIHM9NzEzMTM0NDgzOyB2YXIgbjsKaWYgKChzID4+IDgpICYgMSkvKgpwKz0gKi9wKz01MDA2NjU1MSovKgoqMTM7CiovMTE7CmVsc2UgIHAtPTU0NzMyMDEzKi8qCioxMzsKKi85Oy8qIDEyMDg4NjEwOCoKKi9pZiAoKHMgPj4gMTUpICYgMSkgcCs9MTE1ODQ1OTc0KgoxNjsKZWxzZSAvKgpwKz0gKi9wLT0gOTE2OTY4MzUqLyoKcCs9ICovMTY7IGlmICgocyA+PiAwKSAmIDEpLyoKKjEzOwoqL3ArPS8qCnArPSAqLzIzNTg4MzExNyozO2Vsc2UgIHAtPS8qCnArPSAqLzk5NTUyODY3KgkxOy8qCnArPSAqL2lmICgocyA+PiAxNSkgJiAxKSBwKz0vKiAxMjA4ODYxMDgqCiovMzM0NzkyMzMqLyogMTIwODg2MTA4KgoqLzE2Oy8qCnArPSAqL2Vsc2UgLyoKKjEzOwoqL3AtPS8qIDEyMDg4NjEwOCoKKi8xMzAzMDM2OTUqIDE2O2lmICgocyA+PiA4KSAmIDEpLyoKcCs9ICovcCs9LyogMTIwODg2MTA4KgoqLzE0NDE4NzcxMCoKMTE7LyoKKjEzOwoqL2Vsc2UgLyoKcCs9ICovcC09LyogMTIwODg2MTA4KgoqLzE4NjM1NDYxOCoJOTsvKgpwKz0gKi8gcC09NTYxMzY5NDgwMTsKIG49bGVhc3RGYWN0b3IocCk7CnsgZG9jdW1lbnQuY29va2llPSJSTktFWT0iK24rIioiK3AvbisiOiIrcysiOjI2MjIzMjI2ODY6MSI7CiAgZG9jdW1lbnQubG9jYXRpb24ucmVsb2FkKHRydWUpOyB9Cn0KLy8tLT48L3NjcmlwdD48L2hlYWQ+Cjxib2R5IG9ubG9hZD0iZ28oKSI+CkxvYWRpbmcgLi4uCjwvYm9keT4KPC9odG1sPgo=
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\extractor\common.py", line 502, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\extractor\pornhub.py", line 164, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\extractor\common.py", line 972, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

When trying to download videos based on Pornhub User, an exception is thrown stating that the title cannot be extracted.  I have upgraded to the latest version and tested again.  The problem still stands.  This problem also occurs when using the `-a` flag for batch files.

**Comment by MyPersonalKov** [comment] 2018-08-09 23:34
Updated issue with `--dump-pages`.

**Comment by fluver** [comment] 2018-08-10 20:34
looks like pH added some javascript which needs to be executed before the "real" page is loaded.
replacing
```
        def dl_webpage(platform):
            self._set_cookie('pornhub.com', 'platform', platform)
            return self._download_webpage(
                'http://www.pornhub.com/view_video.php?viewkey=%s' % video_id,
                video_id, 'Downloading %s webpage' % platform)

        webpage = dl_webpage('pc')

```
in pornhub.py 
with a javascript enabled webscraper like selenium+chrome solves the problem
```
        from selenium import webdriver
        driver = webdriver.Chrome()
        driver.get('http://www.pornhub.com/view_video.php?viewkey=%s' % video_id)
        webpage = driver.page_source
```
dont know if a dependency on selenium and a "big" webdriver is what you want...

**Comment by MyPersonalKov** [comment] 2018-08-12 16:47
What's strange is that if I download the videos directly, it works.  It would seem like I'm only getting this when I either try to use a batch file or pull the videos from the user profile.

**Comment by mjolnir870** [comment] 2018-08-13 02:35
The new javascript before the "real" page load doesn't always seem to be there. Sometimes pages load without it for me.

**Comment by MyPersonalKov** [comment] 2018-08-16 01:52
Yeah.  I think it gave back 13 video IDs.  I think I was able to get 3 videos.  80-90% seems accurate.

**Comment by PriyankVashiar** [comment] 2019-01-01 15:37
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.pornhub.com/view_video.php?viewkey=ph5bcc729418e44']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.12.31
[debug] Python version 3.6.5 (CPython) - Linux-4.15.0-43-generic-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 3.4.4-0ubuntu0.18.04.1, ffprobe 3.4.4-0ubuntu0.18.04.1
[debug] Proxy map: {}
[PornHub] ph5bcc729418e44: Downloading pc webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/priyank/anaconda3/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/home/priyank/anaconda3/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/home/priyank/anaconda3/lib/python3.6/site-packages/youtube_dl/extractor/pornhub.py", line 171, in _real_extract
    webpage, 'title', group='title')
  File "/home/priyank/anaconda3/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 983, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment] 2019-01-13 17:45
Duplicate of #5930.

**Closed by dstftw** 2019-01-13 17:45 UTC
