### ISSUE TITLE
I cant download from amc

### ISSUE THREAD

**Issue by elasca** [rg3/youtube-dl#13742] opened 2017-07-26 09:03 UTC
youtube-dl "http://www.amc.com/shows/the-walking-dead/video-extras/the-walking-dead-season--official-comic-con-trailer" --list-formats
[AMCNetworks] the-walking-dead-season-8-official-comic-con-trailer: Downloading webpage
[AMCNetworks] the-walking-dead-season-8-official-comic-con-trailer: Downloading JSON metadata
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu6zpd7mk\build\youtube_dl\__init__.py", line 465, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu6zpd7mk\build\youtube_dl\__init__.py", line 455, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu6zpd7mk\build\youtube_dl\YoutubeDL.py", line 1956, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu6zpd7mk\build\youtube_dl\YoutubeDL.py", line 776, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu6zpd7mk\build\youtube_dl\extractor\common.py", line 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu6zpd7mk\build\youtube_dl\extractor\amcnetworks.py", line 71, in _real_extract
IndexError: list index out of range

How can i fix this?

**Comment by remitamine** [comment] 2017-07-26 09:31
Duplicate of #12453

**Closed by remitamine** 2017-07-26 09:31 UTC
