### ISSUE TITLE
[Bug] douyu.com not working anymore

### ISSUE THREAD

**Issue by brlala** [rg3/youtube-dl#13479] opened 2017-06-23 13:22 UTC
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.23**
### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-o', '-', 'https://www.douyu.com/chenyifaer']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2017.06.05
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-86175-g64ea4d1, ffprobe N-86175-g64ea4d1
[debug] Proxy map: {}
[DouyuTV] chenyifaer: Downloading webpage
[DouyuTV] chenyifaer: Downloading room info
[DouyuTV] chenyifaer: Downloading video URL info
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\build\youtube_dl\__init__.py", line 465, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\build\youtube_dl\__init__.py", line 455, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\build\youtube_dl\YoutubeDL.py", line 1897, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\build\youtube_dl\YoutubeDL.py", line 761, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\build\youtube_dl\extractor\common.py", line 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\build\youtube_dl\extractor\douyutv.py", line 106, in _real_extract
TypeError: list indices must be integers, not str
-----------------
It shows this bug when i tried to stream it? can anyone help with this? thanks

**Comment by yan12125** [comment] 2017-06-23 14:13
This is a duplicate of #13419. Sorry I don't have much time on checking it - I'll be quite busy until mid- or late-July.

**Closed by yan12125** 2017-06-23 14:13 UTC
