### ISSUE TITLE
ABC iView Unsupported URL *UPDATE* (Can be deleted)

### ISSUE THREAD

**Issue by mattym444** [rg3/youtube-dl#18110] opened 2018-11-08 05:37 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.07*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -v "https://iview.abc.net.au/show/spicks-and-specks-reunion-special"
[debug] System config: []
[debug] User config: [u'-o', u'~/Desktop/%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://iview.abc.net.au/show/spicks-and-specks-reunion-special']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.11.07
[debug] Python version 2.7.10 (CPython) - Darwin-18.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg N-92374-gd96ae9d5ea-tessus, ffprobe N-92374-gd96ae9d5ea-tessus
[debug] Proxy map: {}
[generic] spicks-and-specks-reunion-special: Requesting header
WARNING: Falling back on generic information extractor.
[generic] spicks-and-specks-reunion-special: Downloading webpage
[generic] spicks-and-specks-reunion-special: Extracting information
ERROR: Unsupported URL: https://iview.abc.net.au/show/spicks-and-specks-reunion-special
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2324, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 6, column 634
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3298, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://iview.abc.net.au/show/spicks-and-specks-reunion-special
...
<end of log>
```
---

### Description of your *issue*, suggested solution and other information

The link "https://iview.abc.net.au/show/spicks-and-specks-reunion-special" doesn't work on Youtube-DL, i got the link from ABC iView > Share > Copy Link, and it still has an error?

How can i get the direct link?

### UPDATE

After looking at the page source and searching for "Video" it gave me the direct link "https://iview.abc.net.au/video/LE1802V001S00" this link doesn't work in a browser but downloads and works in youtube-dl.

**Comment by remitamine** [comment] 2018-11-08 07:01
Duplicate of #16868.

**Closed by remitamine** 2018-11-08 07:01 UTC
