### ISSUE TITLE
Unable to download Lynda.com videos with organization login

### ISSUE THREAD

**Issue by ankur56** [rg3/youtube-dl#9525] opened 2016-05-17 18:36 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.05.16*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.16**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v --cookies cookies.txt http://www.lynda.com/Bash-tutorials/Whats-Bash/142989/156632-4.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--cookies', u'cookies.txt', u'http://www.lynda.com/Bash-tutorials/Whats-Bash/142989/156632-4.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.05.16
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[lynda] 156632: Downloading video JSON
ERROR: lynda returned error: Session has expired
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 676, in extract_info
  File "youtube_dl\extractor\common.pyo", line 341, in extract
  File "youtube_dl\extractor\lynda.pyo", line 124, in _real_extract
ExtractorError: lynda returned error: Session has expired
...
<end of log>
```

---
---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.
It is a very common issue among youtube-dl users who want to download playlists/videos from lynda.com. I searched web to resolve this issue but none of the solutions worked. I have an organization login for lynda.com and I want to download whole playlists or member only videos from lynda.com. But when I try to do that, youtube-dl downloads only the free videos and not the whole playlist. And when I try to download individual member only videos, it gives the error "Session has expired". I have provided the full verbose output of this error. I used the method provided by DevKiddo in issue #5926 to download the videos. This issue is similar to issue #9118. I tried their solution which is nothing but trying to re-export the cookies. I tried this too but didn't work. I also tried to download the videos using a Linux (OpenSuse) machine but I got the same error. I would be grateful if someone could provide a working solution to this issue.

**Comment by dstftw** [comment] 2016-05-17 18:42
Duplicate of #7725.

**Closed by dstftw** 2016-05-17 18:42 UTC

**Comment by ankur56** [comment] 2016-05-17 18:50
issue #7725 doesn't use an organization login. #7725 has a private login.
