### ISSUE TITLE
`--convert-subs` WON'T work while `--skip-download` is provided.

### ISSUE THREAD

**Issue by flyisland** [rg3/youtube-dl#13573] opened 2017-07-05 08:54 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.02*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
D:\DevPorjects\youtube-dl>python -m youtube_dl -v --skip-download --write-auto-sub --ffmpeg-location D:\Tools\ffmpeg\bin\ --convert-subs srt https://www.youtube.com/watch?v=mcGTJWDJY9o
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--skip-download', '--write-auto-sub', '--ffmpeg-location', 'D:\\Tools\\ffmpeg\\bin\\', '--convert-subs', 'srt', 'https://www.youtube.com/watch?v=mcGTJWDJY9o']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2017.07.02
[debug] Python version 3.5.3 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-86691-gc885356, ffprobe N-86691-gc885356
[debug] Proxy map: {'https': 'http://c00414050:hUawei$2017@proxyus.huawei.com:8080', 'http': 'http://c00414050:hUawei$2017@proxyus.huawei.com:8080'}
[youtube] mcGTJWDJY9o: Downloading webpage
[youtube] mcGTJWDJY9o: Downloading video info webpage
[youtube] mcGTJWDJY9o: Extracting video information
[youtube] mcGTJWDJY9o: Looking for automatic captions
[youtube] mcGTJWDJY9o: Downloading MPD manifest
[info] Writing video subtitles to: Introduction to TCP_IP-mcGTJWDJY9o.en.vtt

...
D:\DevPorjects\youtube-dl>python -m youtube_dl -v --write-auto-sub --ffmpeg-location D:\Tools\ffmpeg\bin\ffmpeg.exe --convert-subs srt https://www.you
tube.com/watch?v=mcGTJWDJY9o
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--write-auto-sub', '--ffmpeg-location', 'D:\\Tools\\ffmpeg\\bin\\ffmpeg.exe', '--convert-subs', 'srt', 'https://www
.youtube.com/watch?v=mcGTJWDJY9o']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2017.07.02
[debug] Python version 3.5.3 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-86691-gc885356, ffprobe N-86691-gc885356
[debug] Proxy map: {'https': 'http://c00414050:hUawei$2017@proxyus.huawei.com:8080', 'http': 'http://c00414050:hUawei$2017@proxyus.huawei.com:8080'}
[youtube] mcGTJWDJY9o: Downloading webpage
[youtube] mcGTJWDJY9o: Downloading video info webpage
[youtube] mcGTJWDJY9o: Extracting video information
[youtube] mcGTJWDJY9o: Looking for automatic captions
[youtube] mcGTJWDJY9o: Downloading MPD manifest
[info] Writing video subtitles to: Introduction to TCP_IP-mcGTJWDJY9o.en.vtt
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r8---sn-q4f7snsr.googlevideo.com/videoplayback?id=99c1932560c963da&itag=135&source=youtube&requiressl=yes&mv=m
&initcwndbps=3782500&mn=sn-q4f7snsr&mm=31&ms=au&ei=w6RcWZnTGNqAugX8obXACQ&pl=20&ratebypass=yes&mime=video/mp4&gir=yes&clen=15456654&lmt=14290125387150
65&dur=1317.333&signature=100C33ADB70AE83A170725F65748E87CEDB6FE.1B4D4A2F4168E47F56D145B299CA657554FF8D8F&mt=1499243563&key=dg_yt0&ip=206.16.17.150&ip
bits=0&expire=1499265315&sparams=ip,ipbits,expire,id,itag,source,requiressl,mv,initcwndbps,mn,mm,ms,ei,pl,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Introduction to TCP_IP-mcGTJWDJY9o.f135.mp4
[download] 100% of 14.74MiB in 00:13
[debug] Invoking downloader on 'https://r4---sn-q4fl6n7y.googlevideo.com/videoplayback?sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%
2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&lmt=1421938120227753&gir=yes&ipbits=0&ei=uqRcWaOqIMTeW_LKhsAC&
signature=2BA866DE797613EA5FCD603FCEF209A7F6D6C100.52F8638F0CA512F631F3A1327B39B0634D52D41B&dur=1317.361&initcwndbps=2916250&keepalive=yes&key=yt6&ita
g=251&clen=21267221&source=youtube&mm=31&mn=sn-q4fl6n7y&pl=20&ip=206.16.17.150&mime=audio%2Fwebm&requiressl=yes&expire=1499265306&mt=1499243563&mv=m&i
d=o-AFlif0ioico9URRTGaC7Q2rZk-wPBZ-M9X46jzLmkN0G&ms=au&ratebypass=yes'
[download] Destination: Introduction to TCP_IP-mcGTJWDJY9o.f251.webm
[download] 100% of 20.28MiB in 00:17
[ffmpeg] Merging formats into "Introduction to TCP_IP-mcGTJWDJY9o.mkv"
[debug] ffmpeg command line: "D:\Tools\ffmpeg\bin\ffmpeg" -y -i "file:Introduction to TCP_IP-mcGTJWDJY9o.f135.mp4" -i "file:Introduction to TCP_IP-mcG
TJWDJY9o.f251.webm" -c copy -map "0:v:0" -map "1:a:0" "file:Introduction to TCP_IP-mcGTJWDJY9o.temp.mkv"
Deleting original file Introduction to TCP_IP-mcGTJWDJY9o.f135.mp4 (pass -k to keep)
Deleting original file Introduction to TCP_IP-mcGTJWDJY9o.f251.webm (pass -k to keep)
[ffmpeg] Converting subtitles
[debug] ffmpeg command line: "D:\Tools\ffmpeg\bin\ffmpeg" -y -i "file:Introduction to TCP_IP-mcGTJWDJY9o.en.vtt" -f srt "file:Introduction to TCP_IP-m
cGTJWDJY9o.en.srt"
Deleting original file Introduction to TCP_IP-mcGTJWDJY9o.en.vtt (pass -k to keep)
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information
As you can see from the output log, youtube-dl won't execute the `[ffmpeg] Converting subtitles` task while `--skip-download` is provided.

**Comment by dstftw** [comment] 2017-07-05 09:28
Duplicate of #9073.

**Closed by dstftw** 2017-07-05 09:28 UTC
