### ISSUE TITLE
[site-support-request] unable to download iqiyi.com video

### ISSUE THREAD

**Issue by shaanlan** [rg3/youtube-dl#6881] opened 2015-09-17 09:10 UTC
weeks ago, youtube-dl is able to download iqiyi.com video.
in my opion, iqiyi.com probably changed the data protocol between front-end and back-end.
so please check whether youtube-dl need to be updated
thanks a lot

youtube-dl http://www.iqiyi.com/v_19rrhal2u0.html --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.iqiyi.com/v_19rrhal2u0.html', u'--verbose']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2015.09.09
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[iqiyi] temp_id: download video page
[iqiyi] f290d60297d3dd2989642717fbb35cce: Downloading JSON metadata
ERROR: Unable to load data. Error code: A000001; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube-dl\youtube_dl\YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "youtube-dl\youtube_dl\extractor\common.py", line 287, in extract
    return self._real_extract(url)
  File "youtube-dl\youtube_dl\extractor\iqiyi.py", line 223, in _real_extract
    raise ExtractorError('Unable to load data. Error code: ' + raw_data['code'])

ExtractorError: Unable to load data. Error code: A000001; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by remitamine** [comment] 2015-09-17 10:38
the same error in this issue #6878

**Comment by dstftw** [comment] 2015-09-17 15:28
Duplicate of #6878.

**Closed by dstftw** 2015-09-17 15:28 UTC
