### ISSUE TITLE
udemy website not working

### ISSUE THREAD

**Issue by maheshvante2015** [rg3/youtube-dl#8949] opened 2016-03-23 19:06 UTC
C:\cource\test>youtube-dl -u XXX -p XXX "https://www.udemy.com/XXX/"
[udemy:course] Downloading login popup
[udemy:course] Logging in as XXX
[udemy:course] XXX: Downloading webpage
[udemy:course] XXX: Downloading course JSON
[udemy:course] 561828: Downloading course curriculum
[download] Downloading playlist: XXX
[udemy:course] playlist XXX : Collected 10 video ids (downloading 10 of them)
[download] Downloading video 1 of 10
[udemy] Downloading login popup
[udemy] 3314652: Downloading webpage
[udemy] 3314652: Downloading lecture JSON
[udemy] 3314652: Downloading lecture JSON
ERROR: Unable to download JSON metadata: HTTP Error 403: FORBIDDEN (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

C:\cource\test>youtube-dl -u XXX -p XXX "https://www.udemy.com/XXX/"
[udemy:course] Downloading login popup
[udemy:course] Logging in as XXX
[udemy:course] XXX: Downloading webpage
[udemy:course] XXX: Downloading course JSON
[udemy:course] 561828: Downloading course curriculum
[download] Downloading playlist: XXX
[udemy:course] playlist XXX : Collected 10 video ids (downloading 10 of them)
[download] Downloading video 1 of 10
[udemy] Downloading login popup
[udemy] 3314652: Downloading webpage
[udemy] 3314652: Downloading lecture JSON
[udemy] 3314652: Downloading lecture JSON
ERROR: Unable to download JSON metadata: HTTP Error 403: FORBIDDEN (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

C:\cource\test>youtube-dl -u XXX -p XXX "https://www.udemy.com/XXX/" --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://www.udemy.com/XXX/', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.03.18
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] Logging in as XXX
[udemy:course] XXX: Downloading webpage
[udemy:course] XXX: Downloading course JSON
[udemy:course] 561828: Downloading course curriculum
[download] Downloading playlist: XXX
[udemy:course] playlist XXX : Collected 10 video ids (downloading 10 of them)
[download] Downloading video 1 of 10
[udemy] Downloading login popup
[udemy] 3314652: Downloading webpage
[udemy] 3314652: Downloading lecture JSON
[udemy] 3314652: Downloading lecture JSON
ERROR: Unable to download JSON metadata: HTTP Error 403: FORBIDDEN (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 365, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 1929, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\python27\lib\urllib2.py", line 437, in open
    response = meth(req, response)
  File "c:\python27\lib\urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python27\lib\urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "c:\python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "c:\python27\lib\urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by jaimeMF** [comment] 2016-03-23 20:12
I assume it's a duplicate of #8948.

**Closed by jaimeMF** 2016-03-23 20:12 UTC
