### ISSUE TITLE
ERROR 503

### ISSUE THREAD

**Issue by kack-kun** [rg3/youtube-dl#11722] opened 2017-01-15 00:05 UTC
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'--list-subs', u'http://www.crunchyroll.com/tiger-mask-w/episode-11-the-tigers-killer-move-721157', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.01.14
[debug] Python version 2.7.9 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-82597-gd316b21, ffprobe N-82597-gd316b21
[debug] Proxy map: {}
[Crunchyroll] Downloading login page
ERROR: Unable to download webpage: HTTP Error 503: Service Temporarily Unavailable (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "c:\program files (x86)\python27\lib\site-packages\youtube_dl\extractor\common.py", line 406, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\program files (x86)\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\program files (x86)\python27\lib\urllib2.py", line 437, in open
    response = meth(req, response)
  File "c:\program files (x86)\python27\lib\urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\program files (x86)\python27\lib\urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "c:\program files (x86)\python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "c:\program files (x86)\python27\lib\urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by Starsam80** [comment] 2017-01-15 00:12
Duplicate of #11572. The TL;DR for the entire issue: Use cookies.

**Closed** 2017-01-15 00:19 UTC
