### ISSUE TITLE
Error Crunchyroll

### ISSUE THREAD

**Issue by L33TN3RD** [rg3/youtube-dl#6513] opened 2015-08-10 07:38 UTC
youtube-dl.exe --skip-download --write-sub --all-subs --verbose http://www.crunchyroll.com/gangsta/episode-1-naughty-boys-682683
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--skip-download', u'--write-sub', u'--all-subs', u'--verbose', u'http://www.crunchyroll.com/gangsta/episode-1-naughty-boys-682683']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.08.09
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-63833-gd4be3a8-Sherpya, ffprobe N-63833-gd4be3a8-Sherpya, rtmpdump 2.4
[debug] Proxy map: {}
[Crunchyroll] 682683: Downloading webpage
[Crunchyroll] 682683: Downloading media info
[Crunchyroll] 682683: Downloading media info for 360p
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 410, in main
  File "youtube_dl\__init__.pyo", line 400, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1653, in download
  File "youtube_dl\YoutubeDL.pyo", line 655, in extract_info
  File "youtube_dl\extractor\common.pyo", line 286, in extract
  File "youtube_dl\extractor\crunchyroll.pyo", line 280, in _real_extract
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by C-Bouthoorn** [comment] 2015-08-10 09:15
$ ./youtube-dl --verbose http://www.crunchyroll.com/gangsta/episode-1-naughty-boys-682683

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.crunchyroll.com/gangsta/episode-1-naughty-boys-682683']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.09
[debug] Python version 2.7.9 - Linux-3.19.0-22-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, rtmpdump 2.4
[debug] Proxy map: {}
[Crunchyroll] 682683: Downloading webpage
[Crunchyroll] 682683: Downloading media info
[Crunchyroll] 682683: Downloading media info for 360p
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./youtube-dl/__main__.py", line 19, in <module>
  File "./youtube-dl/youtube_dl/__init__.py", line 410, in main
  File "./youtube-dl/youtube_dl/__init__.py", line 400, in _real_main
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1653, in download
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 655, in extract_info
  File "./youtube-dl/youtube_dl/extractor/common.py", line 286, in extract
  File "./youtube-dl/youtube_dl/extractor/crunchyroll.py", line 280, in _real_extract
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by dstftw** [comment] 2015-08-10 15:08
Duplicate of #6314.

**Closed by dstftw** 2015-08-10 15:08 UTC
