### ISSUE TITLE
ERROR: unable to download video data: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by kieranoreilly** [rg3/youtube-dl#6452] opened 2015-08-03 23:15 UTC
Error:
Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[download] tmp2/KYPXej.mp4 has already been downloaded
[download] 100% of 0.00B

 Command: youtube-dl www.youtube.com/watch?v=rPYGG108E3I -f 18 -o tmp2/KYPXej.mp4 --verbose
Verbose:
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'www.youtube.com/watch?v=rPYGG108E3I', u'-f', u'18', u'-o', u'tmp2/KYPXej.mp4', u'--verbose']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2015.07.28
[debug] Python version 2.7.9 - Linux-3.16-0.bpo.2-amd64-x86_64-with-debian-8.0
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, ffmpeg 2.4.2-1, ffprobe 2.4.2-1, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: The url doesn't specify the protocol, trying with http
[youtube] rPYGG108E3I: Downloading webpage
[youtube] rPYGG108E3I: Downloading video info webpage
[youtube] rPYGG108E3I: Extracting video information
[youtube] {22} signature length 40.40, html5 player new
[youtube] {43} signature length 40.40, html5 player new
[youtube] {18} signature length 40.40, html5 player new
[youtube] {5} signature length 40.40, html5 player new
[youtube] {36} signature length 40.40, html5 player new
[youtube] {17} signature length 40.40, html5 player new
[youtube] {136} signature length 40.40, html5 player new
[youtube] {247} signature length 40.40, html5 player new
[youtube] {135} signature length 40.40, html5 player new
[youtube] {244} signature length 40.40, html5 player new
[youtube] {134} signature length 40.40, html5 player new
[youtube] {243} signature length 40.40, html5 player new
[youtube] {133} signature length 40.40, html5 player new
[youtube] {242} signature length 40.40, html5 player new
[youtube] {160} signature length 40.40, html5 player new
[youtube] {140} signature length 40.40, html5 player new
[youtube] {171} signature length 40.40, html5 player new
[youtube] rPYGG108E3I: Downloading DASH manifest
WARNING: [youtube] rPYGG108E3I: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[debug] Invoking downloader on u'https://r3---sn-tt17dn7y.googlevideo.com/videoplayback?mn=sn-tt17dn7y&mm=31&ratebypass=yes&key=yt5&requiressl=yes&pl=22&source=youtube&sver=3&expire=1438665245&dur=300.094&mv=m&mt=1438643540&ms=au&fexp=9405988%2C9407662%2C9407942%2C9408254%2C9408371%2C9408507%2C9408710%2C9412527%2C9412774%2C9414661%2C9414764%2C9415365%2C9415485%2C9416126%2C9416837%2C9417703%2C9418153%2C9418199%2C9418425&sparams=dur%2Cid%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&ipbits=0&ip=146.148.61.198&lmt=1391853561518767&itag=18&upn=5Vy9qK3d3Jo&mime=video%2Fmp4&id=o-AIE6OUjYSaqj5Lxwj9kckvqy6Pstjq-Y4HxHImI42zwV&signature=999C8EEF28C5F2F805C99F46D288270DBB14464.CA1EF66A236ADF0755206B8FD5C7B24F081B21'
[download] tmp2/KYPXej.mp4 has already been downloaded
[download] 100% of 0.00B

**Comment by kieranoreilly** [comment] 2015-08-03 23:18
I also get ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1436, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1378, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 59, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1732, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden

**Comment by dstftw** [comment] 2015-08-04 15:26
Duplicate of #6451.

**Closed by dstftw** 2015-08-04 15:26 UTC
