### ISSUE TITLE
YouTube - unable to download this video ....

### ISSUE THREAD

**Issue by kendalls63** [rg3/youtube-dl#6586] opened 2015-08-17 01:20 UTC
https://www.youtube.com/watch?v=D8xiaCGKrU0
Updated youtube-dl to version 2015.08.16.1.
youtube-dl https://www.youtube.com/watch?v=D8xiaCGKrU0
[youtube] D8xiaCGKrU0: Downloading webpage
[youtube] D8xiaCGKrU0: Downloading video info webpage
[youtube] D8xiaCGKrU0: Extracting video information
[youtube] D8xiaCGKrU0: Downloading DASH manifest
WARNING: [youtube] D8xiaCGKrU0: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
ERROR: unable to download video data: HTTP Error 403: Forbidden

**Comment by dstftw** [comment] 2015-08-17 03:26
Duplicate of #6451. Remove cache with `youtube-dl --rm-cache-dir`.

**Closed by dstftw** 2015-08-17 03:26 UTC
