### ISSUE TITLE
8tracks.com ERROR: An extractor error has occured. (caused by KeyError(u'id',))

### ISSUE THREAD

**Issue by protrolium** [rg3/youtube-dl#5900] opened 2015-06-05 15:27 UTC
$ youtube-dl -citw -f bestaudio --verbose http://8tracks.com/asaiber/classical-indian-pakistani-and-persian-music
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-citw', u'-f', u'bestaudio', u'--verbose', u'http://8tracks.com/asaiber/classical-indian-pakistani-and-persian-music']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 2.7.9 - Darwin-14.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.6.2, ffprobe 2.6.2
[debug] Proxy map: {}
[8tracks] classical-indian-pakistani-and-persian-music: Downloading webpage
[8tracks] classical-indian-pakistani-and-persian-music: Downloading song information 1/22
[8tracks] classical-indian-pakistani-and-persian-music: Downloading song information 2/22
[8tracks] classical-indian-pakistani-and-persian-music: Downloading song information 3/22
[8tracks] classical-indian-pakistani-and-persian-music: Downloading song information 4/22
[8tracks] classical-indian-pakistani-and-persian-music: Downloading song information 5/22
[8tracks] classical-indian-pakistani-and-persian-music: Waiting for 636.227272727 seconds
[8tracks] classical-indian-pakistani-and-persian-music: Downloading song information 5/22
[8tracks] classical-indian-pakistani-and-persian-music: Downloading song information 6/22
[8tracks] classical-indian-pakistani-and-persian-music: Waiting for 636.227272727 seconds
[8tracks] classical-indian-pakistani-and-persian-music: Downloading song information 6/22
[8tracks] classical-indian-pakistani-and-persian-music: Downloading song information 7/22
[8tracks] classical-indian-pakistani-and-persian-music: Waiting for 636.227272727 seconds
[8tracks] classical-indian-pakistani-and-persian-music: Downloading song information 7/22
[8tracks] classical-indian-pakistani-and-persian-music: Downloading song information 8/22
[8tracks] classical-indian-pakistani-and-persian-music: Waiting for 636.227272727 seconds
[8tracks] classical-indian-pakistani-and-persian-music: Downloading song information 8/22
[8tracks] classical-indian-pakistani-and-persian-music: Downloading song information 9/22
[8tracks] classical-indian-pakistani-and-persian-music: Waiting for 636.227272727 seconds
[8tracks] classical-indian-pakistani-and-persian-music: Downloading song information 9/22
[8tracks] classical-indian-pakistani-and-persian-music: Downloading song information 10/22
[8tracks] classical-indian-pakistani-and-persian-music: Waiting for 636.227272727 seconds
[8tracks] classical-indian-pakistani-and-persian-music: Downloading song information 10/22
[8tracks] classical-indian-pakistani-and-persian-music: Downloading song information 11/22
[8tracks] classical-indian-pakistani-and-persian-music: Downloading song information 12/22
[8tracks] classical-indian-pakistani-and-persian-music: Downloading song information 13/22
[8tracks] classical-indian-pakistani-and-persian-music: Downloading song information 14/22
[8tracks] classical-indian-pakistani-and-persian-music: Waiting for 636.227272727 seconds
[8tracks] classical-indian-pakistani-and-persian-music: Downloading song information 14/22
[8tracks] classical-indian-pakistani-and-persian-music: Downloading song information 15/22
[8tracks] classical-indian-pakistani-and-persian-music: Waiting for 636.227272727 seconds
[8tracks] classical-indian-pakistani-and-persian-music: Downloading song information 15/22
[8tracks] classical-indian-pakistani-and-persian-music: Downloading song information 16/22
[8tracks] classical-indian-pakistani-and-persian-music: Waiting for 636.227272727 seconds
[8tracks] classical-indian-pakistani-and-persian-music: Downloading song information 16/22
[8tracks] classical-indian-pakistani-and-persian-music: Downloading song information 17/22
[8tracks] classical-indian-pakistani-and-persian-music: Waiting for 636.227272727 seconds
[8tracks] classical-indian-pakistani-and-persian-music: Downloading song information 17/22
[8tracks] classical-indian-pakistani-and-persian-music: Downloading song information 18/22
[8tracks] classical-indian-pakistani-and-persian-music: Waiting for 636.227272727 seconds
[8tracks] classical-indian-pakistani-and-persian-music: Downloading song information 18/22
[8tracks] classical-indian-pakistani-and-persian-music: Downloading song information 19/22
[8tracks] classical-indian-pakistani-and-persian-music: Waiting for 636.227272727 seconds
[8tracks] classical-indian-pakistani-and-persian-music: Downloading song information 19/22
[8tracks] classical-indian-pakistani-and-persian-music: Downloading song information 20/22
ERROR: An extractor error has occured. (caused by KeyError(u'id',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/eighttracks.py", line 146, in _real_extract
    'id': compat_str(track_data['id']),
KeyError: u'id'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 279, in extract
    raise ExtractorError('An extractor error has occured.', cause=e)
ExtractorError: An extractor error has occured. (caused by KeyError(u'id',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by gilbertoca** [comment] 2015-06-11 20:07
Here as well:
```bash
[8tracks] best-music-to-have-while-studying-reading-or-chilling: Downloading song information 45/66
ERROR: An extractor error has occured. (caused by KeyError(u'id',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/eighttracks.py", line 146, in _real_extract
    'id': compat_str(track_data['id']),
KeyError: u'id'
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 279, in extract
    raise ExtractorError('An extractor error has occured.', cause=e)
ExtractorError: An extractor error has occured. (caused by KeyError(u'id',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
Version
```bash
$ youtube-dl --verbose "http://8tracks.com/joffidelity/best-music-to-have-while-studying-reading-or-chilling"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://8tracks.com/joffidelity/best-music-to-have-while-studying-reading-or-chilling']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 2.7.8 - Linux-3.16.7-21-desktop-x86_64-with-SuSE-13.2-x86_64
[debug] exe versions: ffmpeg 2.6.3, ffprobe 2.6.3
[debug] Proxy map: {}
[8tracks] best-music-to-have-while-studying-reading-or-chilling: Downloading webpage
```

**Comment by 04a391c1b7aa** [comment] 2015-07-09 16:58
I also get this error:

```
ERROR: An extractor error has occured. (caused by KeyError('id',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/eighttracks.py", line 146, in _real_extract
    'id': compat_str(track_data['id']),
KeyError: 'id'
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/eighttracks.py", line 146, in _real_extract
    'id': compat_str(track_data['id']),
KeyError: 'id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 279, in extract
    raise ExtractorError('An extractor error has occured.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occured. (caused by KeyError('id',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Haven't been able to figure out the problem yet, but I can for example download the first 2 songs if I change line 126 in https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/eighttracks.py to:
```
 for i in range(2):
```

**Comment by BerndGoldschmidt** [comment] 2015-07-24 14:08
Same issue here:

```
$ youtube-dl -i --verbose "https://8tracks.com/hellotuesday/go-down-in-flames"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-i', u'--verbose', u'https://8tracks.com/hellotuesday/go-down-in-flames']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.21
[debug] Python version 2.7.10 - Darwin-14.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2, rtmpdump 2.4
[debug] Proxy map: {}
[8tracks] go-down-in-flames: Downloading webpage
[8tracks] go-down-in-flames: Downloading song information 1/15
[8tracks] go-down-in-flames: Downloading song information 2/15
[8tracks] go-down-in-flames: Downloading song information 3/15
[8tracks] go-down-in-flames: Downloading song information 4/15
[8tracks] go-down-in-flames: Downloading song information 5/15
[8tracks] go-down-in-flames: Waiting for 113.6 seconds
[8tracks] go-down-in-flames: Downloading song information 5/15
[8tracks] go-down-in-flames: Downloading song information 6/15
[8tracks] go-down-in-flames: Waiting for 113.6 seconds
[8tracks] go-down-in-flames: Downloading song information 6/15
[8tracks] go-down-in-flames: Downloading song information 7/15
[8tracks] go-down-in-flames: Waiting for 113.6 seconds
[8tracks] go-down-in-flames: Downloading song information 7/15
[8tracks] go-down-in-flames: Waiting for 113.6 seconds
[8tracks] go-down-in-flames: Downloading song information 7/15
[8tracks] go-down-in-flames: Downloading song information 8/15
[8tracks] go-down-in-flames: Waiting for 113.6 seconds
[8tracks] go-down-in-flames: Downloading song information 8/15
[8tracks] go-down-in-flames: Waiting for 113.6 seconds
[8tracks] go-down-in-flames: Downloading song information 8/15
[8tracks] go-down-in-flames: Downloading song information 9/15
[8tracks] go-down-in-flames: Waiting for 113.6 seconds
[8tracks] go-down-in-flames: Downloading song information 9/15
[8tracks] go-down-in-flames: Downloading song information 10/15
[8tracks] go-down-in-flames: Waiting for 113.6 seconds
[8tracks] go-down-in-flames: Downloading song information 10/15
[8tracks] go-down-in-flames: Downloading song information 11/15
[8tracks] go-down-in-flames: Waiting for 113.6 seconds
[8tracks] go-down-in-flames: Downloading song information 11/15
[8tracks] go-down-in-flames: Waiting for 113.6 seconds
[8tracks] go-down-in-flames: Downloading song information 11/15
[8tracks] go-down-in-flames: Downloading song information 12/15
[8tracks] go-down-in-flames: Waiting for 113.6 seconds
[8tracks] go-down-in-flames: Downloading song information 12/15
ERROR: An extractor error has occured. (caused by KeyError(u'id',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/eighttracks.py", line 146, in _real_extract
    'id': compat_str(track_data['id']),
KeyError: u'id'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 656, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 281, in extract
    raise ExtractorError('An extractor error has occured.', cause=e)
ExtractorError: An extractor error has occured. (caused by KeyError(u'id',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by GijsTimmers** [comment] 2015-09-21 14:37
Duplicates:  #5278,  #5029. I'm having the same problem on Ubuntu 15.04, `youtube-dl` version 2015.09.09.

**Comment by dstftw** [comment] 2015-12-09 18:59
Duplicate of #5029.

**Closed by dstftw** 2015-12-09 18:59 UTC
