### ISSUE TITLE
Could not download DASH manifest: HTTP Error 403

### ISSUE THREAD

**Issue by Claperius** [rg3/youtube-dl#6680] opened 2015-08-26 13:51 UTC
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=haECT-SerHk']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.23
[debug] Python version 2.7.10 - Linux-3.9-1-amd64-x86_64-with-debian-stretch-sid
[debug] exe versions: avconv 11.4-6, avprobe 11.4-6, ffmpeg 1.0.6, ffprobe 1.0.6, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] haECT-SerHk: Downloading webpage
[youtube] haECT-SerHk: Downloading video info webpage
[youtube] haECT-SerHk: Extracting video information
[youtube] {22} signature length 40.43, html5 player new
[youtube] {43} signature length 40.43, html5 player new
[youtube] {18} signature length 40.43, html5 player new
[youtube] {5} signature length 40.43, html5 player new
[youtube] {36} signature length 40.43, html5 player new
[youtube] {17} signature length 40.43, html5 player new
[youtube] {13} signature length 40.43, html5 player new
[youtube] {137} signature length 40.43, html5 player new
[youtube] {248} signature length 40.43, html5 player new
[youtube] {136} signature length 40.43, html5 player new
[youtube] {247} signature length 40.43, html5 player new
[youtube] {135} signature length 40.43, html5 player new
[youtube] {244} signature length 40.43, html5 player new
[youtube] {134} signature length 40.43, html5 player new
[youtube] {243} signature length 40.43, html5 player new
[youtube] {133} signature length 40.43, html5 player new
[youtube] {242} signature length 40.43, html5 player new
[youtube] {160} signature length 40.43, html5 player new
[youtube] {140} signature length 40.43, html5 player new
[youtube] {171} signature length 40.43, html5 player new
[youtube] haECT-SerHk: Downloading DASH manifest
WARNING: [youtube] haECT-SerHk: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[debug] Invoking downloader on u'https://r6---sn-5uh5o-f5fz.googlevideo.com/videoplayback?upn=wX0FCHnEJuU&source=youtube&fexp=9407663%2C9408710%2C9408987%2C9409069%2C9412842%2C9415365%2C9415485%2C9415869%2C9416023%2C9416126%2C9416837%2C9417085%2C9417707%2C9418011%2C9418024%2C9418153%2C9418203%2C9418449%2C9419319%2C9419788%2C9420020&ms=au&mt=1440596917&mv=m&ip=195.150.66.140&id=o-AF4zVc9_Ft2iDpRJOpvJEOPfU8sHGejccNziXNwtyzsD&requiressl=yes&dur=218.400&mm=31&mn=sn-5uh5o-f5fz&pl=16&gcr=pl&ipbits=0&expire=1440618561&sparams=clen%2Cdur%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&initcwndbps=927500&lmt=1417061077708299&sver=3&pcm2cms=yes&mime=video%2Fmp4&itag=137&key=yt5&gir=yes&clen=94655723&keepalive=yes&signature=3983FDF48B389C92797E26D36A964EA5F914317B.0B543754EB7C40434F9D36A62658F193B6DCCDF2&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/opt/youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 1579, in process_info
    partial_success = dl(fname, new_info)
  File "/opt/youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 1527, in dl
    return fd.download(name, info)
  File "/opt/youtube-dl/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/opt/youtube-dl/youtube-dl/youtube_dl/downloader/http.py", line 60, in real_download
    data = self.ydl.urlopen(request)
  File "/opt/youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 1860, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden

**Comment by dstftw** [comment] 2015-08-26 14:18
Duplicate of #6451. Remove cache with `youtube-dl --rm-cache-dir`.

**Closed by dstftw** 2015-08-26 14:18 UTC
