### ISSUE TITLE
Site Request: v.qq.com

### ISSUE THREAD

**Issue by Loko0415** [rg3/youtube-dl#9210] opened 2016-04-16 09:38 UTC
Example video:http://v.qq.com/cover/t/t1rmktedqbey1g5/d0020cv1s3t.html

> [debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://v.qq.com/cover/t/t1rmktedqbey1g5/dcv1s3t.html']
[debug] Encodings: locale cp950, fs mbcs, out cp950, pref cp950
[debug] youtube-dl version 2016.04.13
[debug] Python version 3.5.1 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[generic] d0020cv1s3t: Requesting header
WARNING: Falling back on generic information extractor.
[generic] d0020cv1s3t: Downloading webpage
[generic] d0020cv1s3t: Extracting information
ERROR: Unsupported URL: http://v.qq.com/cover/t/t1rmktedqbey1g5/d0020cv1s3t.

Traceback (most recent call last):
  File "C:\youtube-dl.py\youtube_dl\YoutubeDL.py", line 67
n extract_info
    ie_result = ie.extract(url)
  File "C:\youtube-dl.py\youtube_dl\extractor\common.py",
 341, in extract
    return self._real_extract(url)
  File "C:\youtube-dl.py\youtube_dl\extractor\generic.py",
e 2024, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://v.qq.com/cover/t/
ktedqbey1g5/d0020cv1s3t.html

**Comment by yan12125** [comment] 2016-04-16 09:46
Duplicate of #6831.

**Closed by yan12125** 2016-04-16 09:46 UTC
