### ISSUE TITLE
Not-yet-started live streams fail with terrible error

### ISSUE THREAD

**Issue by nagisa** [rg3/youtube-dl#7018] opened 2015-09-29 15:58 UTC
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=Jc-LEG0T_4c']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.28
[debug] Python version 3.4.3 - Linux-4.1.6-1-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 2.8, ffprobe 2.8, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Jc-LEG0T_4c: Downloading webpage
[youtube] Jc-LEG0T_4c: Downloading video info webpage
[youtube] Jc-LEG0T_4c: Extracting video information
ERROR: no conn, hlsvp or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 655, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 287, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 1313, in _real_extract
    raise ExtractorError('no conn, hlsvp or url_encoded_fmt_stream_map information found in video info')
youtube_dl.utils.ExtractorError: no conn, hlsvp or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

This stream at attempt time was listed under “upcoming live streams”.

A better error message could be printed such as “this live stream is not up yet” instead.

**Comment by dstftw** [comment] 2015-09-29 16:04
Duplicate of #3320.

**Closed by dstftw** 2015-09-29 16:04 UTC
