### ISSUE TITLE
Unable to extract title

### ISSUE THREAD

**Issue by TheGr33k** [rg3/youtube-dl#4822] opened 2015-01-30 18:44 UTC
youtube-dl -g --verbose  http://www.pornhub.com/view_video.php?viewkey=107237
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-g', '--verbose', 'http://www.pornhub.com/view_video.php?viewkey=107237']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.30.2
[debug] Python version 3.4.2 - Linux-3.10.0-123.13.2.el7.x86_64-x86_64-with-centos-7.0.1406-Core
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 618, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 266, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pornhub.py", line 57, in _real_extract
    video_title = self._html_search_regex(r'<h1 [^>]+>([^<]+)', webpage, 'title')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 522, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment] 2015-01-30 18:49
>Error Page Not Found

**Comment by TheGr33k** [comment] 2015-01-30 18:52
@dstftw 
Here is another link http://www.pornhub.com/view_video.php?viewkey=2147327275

**Comment by dstftw** [comment] 2015-01-30 18:53
This one works for me. Could you upload `*.dump` files when running with `--write-pages`?

**Comment by TheGr33k** [comment] 2015-01-30 19:03
youtube-dl -g http://www.pornhub.com/view_video.php?viewkey=2147327275

`ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

Here is the dump 

https://www.sendspace.com/file/o0jno2

**Comment by phihag** [comment] 2015-01-30 20:54
This looks like a weird redirect, probably for caching purposes. I'll look into it; thanks for the report.

**Comment by fenglin1202** [comment] 2015-07-09 07:48
i meat the same problem too. seems all pornhub videos could not be downloaded.
youtube-dl version 2015.07.07
the dump file: https://goo.gl/TIklUA
and the verbose logs:

```
D:\Moo0\YouTube-DL 1.07\vdl>youtube-dl.exe --verbose --write-pages http://www.pornhub.com/view_video.php?viewkey=2062141185
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--write-pages', u'http://www.pornhub.com/view_video.php?viewkey=2062141185']
[debug] Encodings: locale cp950, fs mbcs, out cp950, pref cp950
[debug] youtube-dl version 2015.07.07
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[PornHub] 2062141185: Downloading webpage
[PornHub] Saving request to 2062141185_http_-_www.pornhub.com_view_video.phpviewkey=2062141185.dump
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update.
Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 654, in extract_info
  File "youtube_dl\extractor\common.pyo", line 273, in extract
  File "youtube_dl\extractor\pornhub.pyo", line 66, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 564, in _html_search_regex
  File "youtube_dl\extractor\common.pyo", line 555, in _search_regex
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its
complete output.
```

**Comment by k1-hedayati** [comment] 2015-08-06 18:11
Pornhub support seems to be broken

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-g', u'--verbose', u'http://www.pornhub.com/view_video.php?viewkey=2147327275']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.28
[debug] Python version 2.7.6 - Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 656, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 279, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/pornhub.py", line 113, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 735, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by gebn** [comment] 2015-08-06 20:15
@k1-hedayati I fixed this in 754e70cf3e74218ae5d840985fbf07bbe274332a; it'll be in the next release.

**Comment by k1-hedayati** [comment] 2015-08-09 17:56
@gebn That's great! Thanks for support.

**Comment by dstftw** [comment] 2016-07-27 19:12
Duplicate of #5930.

**Closed by dstftw** 2016-07-27 19:12 UTC
