### ISSUE TITLE
Requested Site : Voot.com

### ISSUE THREAD

**Issue by fuaxio** [rg3/youtube-dl#11644] opened 2017-01-08 15:59 UTC

**Comment by fuaxio** [comment] 2017-01-08 16:00
example site: http://www.voot.com/shows/bigg-boss-s10/10/450656/day-80-om-swami-strikes-again-/469329

**Comment by yan12125** [comment] 2017-01-08 16:02
Duplicate of #10255

**Closed by yan12125** 2017-01-08 16:02 UTC
