### ISSUE TITLE
youtube-dl no longer works with RTS (rts.ch)

### ISSUE THREAD

**Issue by lnef** [rg3/youtube-dl#6670] opened 2015-08-25 19:40 UTC
The site rts.ch is supported by youtube-dl (https://rg3.github.io/youtube-dl/supportedsites.html) but it does not work ...

$ youtube-dl --verbose -f best http://www.rts.ch/play/tv/doc-du-lundi/video/la-revolution-retro?id=7025793
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-f', u'best', u'http://www.rts.ch/play/tv/doc-du-lundi/video/la-revolution-retro?id=7025793']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.23
[debug] Python version 2.7.9 - Linux-3.19.0-25-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6
[debug] Proxy map: {}
[RTS] la-revolution-retro: Downloading JSON metadata
[RTS] 7025793: Downloading m3u8 information
[RTS] 7025793: Downloading hds token
[RTS] 7025793: Downloading f4m manifest
ERROR: Unable to download f4m manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 326, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1860, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

$

**Comment by dstftw** [comment] 2015-08-25 20:03
It's georestricted. Can you watch it in browser?

**Comment by lnef** [comment] 2015-08-25 20:10
Yes i can watch in a browser ...

I live in Geneva (Switzerland)

**Comment by dstftw** [comment] 2015-10-10 20:48
Duplicate of #4989.

**Closed by dstftw** 2015-10-10 20:48 UTC
Labels: geo-restricted
