### ISSUE TITLE
Flash 11.4 breaks youtube-dl - ERROR: RTMP download detected but "rtmpdump" could not be run

### ISSUE THREAD

**Issue by nawman** [rg3/youtube-dl#450] opened 2012-10-01 02:15 UTC
I am using window 7 and rg3-youtube-dl-2012.09.27 it was working fine utill I installed some other apps.

Now I get - ERROR: RTMP download detected but "rtmpdump" could not be run.

I think this has ned after installing the lastest Flash 11.4.

What can I do to get working again

**Comment by dstftw** [comment] 2016-06-12 17:04
Duplicate of #343.

**Closed** 2016-06-12 17:04 UTC
