### ISSUE TITLE
rtl-now.rtl.de: ERROR: rtmpdump exited with code 1

### ISSUE THREAD

**Issue by hstracker90** [rg3/youtube-dl#5726] opened 2015-05-16 15:03 UTC
Dear all, unfortunately I am having trouble downloading from RTLnow. It worked great until last week.
I would appreciate it very, very much if this could be fixed. Thank you!

PS C:\Users\hstracker> youtube-dl "http://rtl-now.rtl.de/lets-dance/folge-9-2015-05-15-20-15-00.php?container_id=206729&player=1&
season=8" --verbose
[debug] System config: []
[debug] User config: [u'-o', u'C:/Users/hstracker/Downloads/%(title)s.%(ext)s']
[debug] Command-line args: [u'http://rtl-now.rtl.de/lets-dance/folge-9-2015-05-15-20-15-00.php?container_id=206729&playe
r=1&season=8', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.05.15
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-68482-g92a596f, ffprobe N-68482-g92a596f, rtmpdump 2.4
[debug] Proxy map: {}
[RTLnow] 206729: Downloading webpage
[RTLnow] 206729: Downloading player data XML
[debug] Invoking downloader on u'rtmpe://fms.rtl.de/hds'
[download] Destination: C:\Users\hstracker\Downloads\Let's Dance - Folge 9.flv
[debug] rtmpdump command line: rtmpdump --verbose -r rtmpe://fms.rtl.de/hds -o 'C:\Users\hstracker\Downloads\Let'"'"'s Danc
e - Folge 9.flv.part' --swfVfy http://rtl-now.rtl.de/includes/vodplayer.swf --pageUrl 'http://rtl-now.rtl.de/lets-dance/
folge-9-2015-05-15-20-15-00.php?container_id=206729&player=1&season=8' --playpath mp4:202727/manifest-hds --resume --ski
p 1
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : fms.rtl.de
[rtmpdump] DEBUG: Parsed app     : hds
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : fms.rtl.de
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:202727/manifest-hds
[rtmpdump] DEBUG: tcUrl    : rtmpe://fms.rtl.de:1935/hds
[rtmpdump] DEBUG: swfUrl   : http://rtl-now.rtl.de/includes/vodplayer.swf
[rtmpdump] DEBUG: pageUrl  : http://rtl-now.rtl.de/lets-dance/folge-9-2015-05-15-20-15-00.php?container_id=206729&player
=1&season=8
[rtmpdump] DEBUG: app      : hds
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: SWFSHA256:
[rtmpdump] DEBUG: ce bb 86 a6 57 09 84 a6 96 0b 04 d1 7a 3b 9b 3c
[rtmpdump] DEBUG: 4b d9 68 c1 71 e8 13 70 62 28 2e d9 7e 70 5e 3a
[rtmpdump] DEBUG: SWFSize  : 1051380
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 0 bytes
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : fms.rtl.de
[rtmpdump] DEBUG: Parsed app     : hds
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : fms.rtl.de
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:202727/manifest-hds
[rtmpdump] DEBUG: tcUrl    : rtmpe://fms.rtl.de:1935/hds
[rtmpdump] DEBUG: swfUrl   : http://rtl-now.rtl.de/includes/vodplayer.swf
[rtmpdump] DEBUG: pageUrl  : http://rtl-now.rtl.de/lets-dance/folge-9-2015-05-15-20-15-00.php?container_id=206729&player
=1&season=8
[rtmpdump] DEBUG: app      : hds
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: SWFSHA256:
[rtmpdump] DEBUG: ce bb 86 a6 57 09 84 a6 96 0b 04 d1 7a 3b 9b 3c
[rtmpdump] DEBUG: 4b d9 68 c1 71 e8 13 70 62 28 2e d9 7e 70 5e 3a
[rtmpdump] DEBUG: SWFSize  : 1051380
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.

ERROR: rtmpdump exited with code 1
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 405, in main
  File "youtube_dl\__init__.pyo", line 395, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1484, in download
  File "youtube_dl\YoutubeDL.pyo", line 660, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 706, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 1155, in process_video_result
  File "youtube_dl\YoutubeDL.pyo", line 1417, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1359, in dl
  File "youtube_dl\downloader\common.pyo", line 342, in download
  File "youtube_dl\downloader\rtmp.pyo", line 202, in real_download
  File "youtube_dl\downloader\common.pyo", line 155, in report_error
  File "youtube_dl\YoutubeDL.pyo", line 527, in report_error
  File "youtube_dl\YoutubeDL.pyo", line 489, in trouble

**Comment by dstftw** [comment] 2015-05-16 16:44
Duplicate of #5681.

**Closed by dstftw** 2015-05-16 16:44 UTC

**Comment by JJ-Jana** [comment] 2015-05-16 17:18
Thank you that you post and I for one get this shit here on the cover! Because of you is my post I had posted as the first, has been closed! You should have time to look properly that there was already such a topic because RTLnow! Thank you dumbass!

Because such a punishing me here. SUCKS !!!!!!!!

**Comment by dstftw** [comment] 2015-05-16 17:22
@JJ-Jana calm down, no one touched you issue. I've just closed this one as duplicate of yours.

**Comment by hstracker90** [comment] 2015-05-17 07:33
Dear Jana, what kind of punishment do you expect? I am very sorry I didn't check the open topics.

**Comment by JJ-Jana** [comment] 2015-05-17 13:50
Hello, You are german right? 

Ich erwarte keine Strafe für dich, du hättest lediglich einmal richtig schauen können, denn mir wurde nun unterstellt das ich das Thema doppelt geöffnet habe und ich habe keine Lust darauf das man mir unterstellt das ich zwei User in einer person bin. Ich hatte dieses problem was du hier hast ein paar Tage zuvor geschildert und es konnte mir keiner wirklich helfen. 

Aber mir ist das egal, ihr könnt das ja hier weiter diskutieren. Ich bin raus hier.
