### ISSUE TITLE
Site Support Request: Channel4 "On Demand"

### ISSUE THREAD

**Issue by 0x27** [rg3/youtube-dl#5121] opened 2015-03-04 14:14 UTC
Unsure if it is possible (appears to be some Adobe Flash DRM in place, maybe RSTPdump or similar can help?), but it would be very nice to be able to download stuff from 4OD - www.channel4.com/on-demand.

Mainly because myself, amongst others, absolutely refuse to use Flash player for security reasons (and because its dead tech that needs to die) and it would be really awesome to be able to just download 4OD content from the commandline and watch it later without futzing about with Flash and all that nonsense.

If it would help I can try get a packet capture or something later today of the communication between browser and server to try figure out what is going on?

**Comment by jaimeMF** [comment] 2015-03-04 14:27
Duplicate of #2050. If it's using f4m drm (as you and https://github.com/rg3/youtube-dl/issues/2050#issuecomment-70367444 says), it will take some time.

**Closed by jaimeMF** 2015-03-04 14:27 UTC

**Comment by 0x27** [comment] 2015-03-04 15:12
Ah, didn't notice that issue :) 

Will have to look into this DRM thing, as breaking it is definately relavent to interests.
