### ISSUE TITLE
ERROR: Unable to download video webpage: <urlopen _FAILED] certificate verify failed (_ssl.c:547)>

### ISSUE THREAD

**Issue by mevsme** [rg3/youtube-dl#883] opened 2013-06-11 14:12 UTC
What it could be? Never met this before.
![picture](https://f.cloud.github.com/assets/1394030/637306/dcda262a-d2a0-11e2-8b42-fac03950bfa0.png)

**Comment by agrberg** [comment] 2015-05-08 14:30
I'm getting this same error on OS X 10.10.3

This is the output of `youtube-dl -v -i https://www.youtube.com/watch?v=6AMyFCO0K60`

```bash
[debug] System config: []
[debug] User config: [u'-o', u'/Users/aaron/Downloads/%(title)s.%(ext)s']
[debug] Command-line args: [u'-v', u'-i', u'https://www.youtube.com/watch?v=6AMyFCO0K60']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.04
[debug] Python version 2.7.9 - Darwin-14.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.6.2, ffprobe 2.6.2
[debug] Proxy map: {}
[youtube] 6AMyFCO0K60: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)> (caused by URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 312, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1708, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 720, in https_open
    req, **kwargs)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
```

**Comment by jaimeMF** [comment] 2015-05-08 16:42
@agrberg that's not an issue with youtube-dl, it's caused by the openssl installed with Homebrew. Try with the solutions listed in these comments: https://github.com/rg3/youtube-dl/issues/5317#issuecomment-94205465 and https://github.com/rg3/youtube-dl/issues/5317#issuecomment-94214004.

**Comment by agrberg** [comment] 2015-05-08 17:18
@jaimeMF thank you! That fixed it :+1:

**Comment by kud** [comment] 2016-07-08 11:17
I've got this problem too but on Windows. As we don't have homebrew, how to fix it? Is it a problem with cmder?

**Comment by kud** [comment] 2016-07-08 11:21
Okay, `--no-check-certificat` makes it work. Thanks for the workaround.

**Comment by yan12125** [comment] 2016-07-08 11:22
In general ```--no-check-certificate``` is not necessary. See #7309 for Windows users. A possible solution is at https://github.com/rg3/youtube-dl/issues/7309#issuecomment-172354527

Closing as others in this thread have solved the problem.

**Closed by yan12125** 2016-07-08 11:22 UTC
Labels: bug

**Comment by alma4rebi** [comment] 2017-03-25 07:04
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)> (caused by URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))

**Comment by Hrxn** [comment] 2017-03-25 08:08
https://github.com/rg3/youtube-dl/issues/7309#issuecomment-172354527

**Comment by alma4rebi** [comment] 2017-03-25 08:33
#LinuxMint + #Ubuntu

**Comment by yan12125** [comment] 2017-03-25 08:41
@alma4rebi First, please paste the full output of ```youtube-dl -v "your URL"```

**Comment by alma4rebi** [comment] 2017-03-25 08:54
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.24
[debug] Python version 2.7.12 - Linux-4.4.0-59-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 3.2.4-2, ffprobe 3.2.4-2
[debug] Proxy map: {}

**Comment by yan12125** [comment] 2017-03-25 08:58
This is incomplete. Need at least command line arguments, the URL and error messages.
