### ISSUE TITLE
403 Forbidden Issue

### ISSUE THREAD

**Issue by baruns** [rg3/youtube-dl#6152] opened 2015-07-04 19:11 UTC
[root@my ~]# youtube-dl -s -4 http://www.youtube.com/watch?v=5OAW3TKwfyk
[youtube] 5OAW3TKwfyk: Downloading webpage
[youtube] 5OAW3TKwfyk: Downloading video info webpage
[youtube] 5OAW3TKwfyk: Extracting video information
[youtube] 5OAW3TKwfyk: Downloading DASH manifest
[youtube] 5OAW3TKwfyk: Downloading js player en_US-vflzomeEU
[youtube] 5OAW3TKwfyk: Downloading DASH manifest
WARNING: [youtube] 5OAW3TKwfyk: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[root@my ~]# youtube-dl -U
youtube-dl is up-to-date (2015.07.04)
[root@my ~]#

**Comment by yan12125** [comment] 2015-07-05 10:00
It's a duplicate of #5118.
A side note: **DO NOT** run youtube-dl as root unless you're updating (```youtube-dl -U```)

**Closed by yan12125** 2015-07-05 10:00 UTC
