### ISSUE TITLE
Download specific parts of a video

### ISSUE THREAD

**Issue by Nevflinn** [rg3/youtube-dl#7165] opened 2015-10-13 21:48 UTC
Hi,

I'm trying to use youtube-dl to download up to a specific part of a video.

For instance, if I have a 5 minute video, and I want to download from 2:00 to 3:00, what command would I need in order to do this? I have reviewed the documentation but not seen any commands that relate to this.

Thank you for any advice you can offer.

**Comment by dstftw** [comment] 2015-10-14 03:05
Duplicate of #622.
That is not possible. You may try using [ffmpeg](https://github.com/rg3/youtube-dl/issues/4821#issuecomment-97564929).

**Closed by dstftw** 2015-10-14 03:05 UTC
