### ISSUE TITLE
Bug: Subtitles not converted when using `--skip-download`

### ISSUE THREAD

**Issue by TRox1972** [rg3/youtube-dl#9762] opened 2016-06-12 11:47 UTC
Without `--skip-download`
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--write-sub', u'--sub-format', u'dfxp', u'--convert-subtitles', u'srt', u'--verbose', u'http://www.c-span.org/video/?313572-1/attorney-general-eric-holder-voting-rights-act-decision']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2016.06.12
[debug] Python version 2.7.10 - Linux-2.6.32-042stab112.15-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, ffmpeg 11.2-6
[debug] Proxy map: {}
[CSpan] 313572: Downloading webpage
[CSpan] 315139: Downloading JSON metadata
[CSpan] 315139: Downloading XML
[download] Downloading playlist: Attorney General Eric Holder on Voting Rights Act Decision
[CSpan] playlist Attorney General Eric Holder on Voting Rights Act Decision: Collected 2 video ids (downloading 2 of them)
[download] Downloading video 1 of 2
[info] Writing video subtitles to: Attorney General Eric Holder on Voting Rights Act Decision part 1-315139_1.en.dfxp
[debug] Invoking downloader on u'http://media.c-spanvideo.org/trimmed/program/031/315139/program.315139.MP4-M20.mp4?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cDovL21lZGlhLmMtc3BhbnZpZGVvLm9yZy90cmltbWVkL3Byb2dyYW0vMDMxLzMxNTEzOS9wcm9ncmFtLjMxNTEzOS5NUDQtTTIwLm1wNCIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTQ2NTc0NjA3Mn0sIklwQWRkcmVzcyI6eyJBV1M6U291cmNlSXAiOiIxODUuMTcuMTg0Ljg3In19fV19&Key-Pair-Id=APKAIHKVWBEAXX562G7Q&Signature=BZPOn8ZfMTVzAaN-GbR4P~UJSqGxtzpEOxMMpZYadRXs8jIXZ3C9J-WzAr1yyHLuPb34V5IaG8yjre5YlZ8qjURN~eAjMPIDl6DU2EaAkhp9b3rmKNm2AdlfTtjy9-pxUJiufiSJUV9auaapltgmN51ArixRO-gKE9elBKeIz4Q_'
[download] Destination: Attorney General Eric Holder on Voting Rights Act Decision part 1-315139_1.mp4
[download] 100% of 60.55MiB in 00:00
[ffmpeg] Converting subtitles
WARNING: You have requested to convert dfxp (TTML) subtitles into another format, which results in style information loss
Deleting original file Attorney General Eric Holder on Voting Rights Act Decision part 1-315139_1.en.dfxp (pass -k to keep)
[download] Downloading video 2 of 2
[info] Writing video subtitles to: Attorney General Eric Holder on Voting Rights Act Decision part 2-315139_2.en.dfxp
[debug] Invoking downloader on u'http://media.c-spanvideo.org/dynamic/2013/06/25/20130625205918001_hd/20130625205918001_hd.MP4-M20.mp4?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cDovL21lZGlhLmMtc3BhbnZpZGVvLm9yZy9keW5hbWljLzIwMTMvMDYvMjUvMjAxMzA2MjUyMDU5MTgwMDFfaGQvMjAxMzA2MjUyMDU5MTgwMDFfaGQuTVA0LU0yMC5tcDQiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE0NjU3NDYwNzJ9LCJJcEFkZHJlc3MiOnsiQVdTOlNvdXJjZUlwIjoiMTg1LjE3LjE4NC44NyJ9fX1dfQ__&Key-Pair-Id=APKAIHKVWBEAXX562G7Q&Signature=QWh20WsuO9RmqTSFcvyg8G5GKJHDyEEEMcWMXTwPNLbMKBfdH2lIs4F3dvf1UMKIylkMC2VCRmYaDfP0f2g36X0cMHd1qPUCcg8yXQVqLNkh4WQmr1~kk0woqBGof-8ktuWmBxsgDZQE~Sly3MLl3tH5oqwlk6-UOprAeIyBOUw_'
[download] Destination: Attorney General Eric Holder on Voting Rights Act Decision part 2-315139_2.mp4
[download] 100% of 295.21MiB in 00:02
[ffmpeg] Converting subtitles
WARNING: You have requested to convert dfxp (TTML) subtitles into another format, which results in style information loss
Deleting original file Attorney General Eric Holder on Voting Rights Act Decision part 2-315139_2.en.dfxp (pass -k to keep)
[download] Finished downloading playlist: Attorney General Eric Holder on Voting Rights Act Decision
```

```
$ ls
Attorney General Eric Holder on Voting Rights Act Decision part 1-315139_1.en.srt
Attorney General Eric Holder on Voting Rights Act Decision part 1-315139_1.mp4
Attorney General Eric Holder on Voting Rights Act Decision part 2-315139_2.en.srt
Attorney General Eric Holder on Voting Rights Act Decision part 2-315139_2.mp4
```

With `--skip-download`
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--write-sub', u'--sub-format', u'dfxp', u'--convert-subtitles', u'srt', u'--verbose', u'http://www.c-span.org/video/?313572-1/attorney-general-eric-holder-voting-rights-act-decision', u'--skip-download']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2016.06.12
[debug] Python version 2.7.10 - Linux-2.6.32-042stab112.15-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, ffmpeg 11.2-6
[debug] Proxy map: {}
[CSpan] 313572: Downloading webpage
[CSpan] 315139: Downloading JSON metadata
[CSpan] 315139: Downloading XML
[download] Downloading playlist: Attorney General Eric Holder on Voting Rights Act Decision
[CSpan] playlist Attorney General Eric Holder on Voting Rights Act Decision: Collected 2 video ids (downloading 2 of them)
[download] Downloading video 1 of 2
[info] Writing video subtitles to: Attorney General Eric Holder on Voting Rights Act Decision part 1-315139_1.en.dfxp
[download] Downloading video 2 of 2
[info] Writing video subtitles to: Attorney General Eric Holder on Voting Rights Act Decision part 2-315139_2.en.dfxp
[download] Finished downloading playlist: Attorney General Eric Holder on Voting Rights Act Decision
```

```
$ ls
Attorney General Eric Holder on Voting Rights Act Decision part 1-315139_1.en.dfxp
Attorney General Eric Holder on Voting Rights Act Decision part 2-315139_2.en.dfxp
```

**Comment by yan12125** [comment] 2016-06-12 11:50
Duplicate of #9073 and a possible solution at #9738.

**Closed by yan12125** 2016-06-12 11:50 UTC
