### ISSUE TITLE
Output filename has non-ASCII, Unicode characters stripped 

### ISSUE THREAD

**Issue by AmperAndSand** [rg3/youtube-dl#5182] opened 2015-03-12 07:11 UTC
I downloaded this Youtube video, original title: "*[직캠]120505 레인보우(Rainbow) - A(エー) / 어린이날 축제(봉화)*" URL: https://www.youtube.com/watch?v=thNZgEwQ2uQ. 

I configured youtube-dl to copy the video title to the file name (`-o %(title)s`),  but the file name result I got was: "*[]120505 (Rainbow) - A() _  ()_thNZgEwQ2uQ_137 - 1920x1080 (DASH video)+141 - audio only (DASH audio)_Darksnipercam_20120505.mp4*". (All non-ASCII, Unicode characters were stripped.)  

How do I configure youtube-dl to copy the full title of the video on the filename without stripping non-ASCII, Unicode characters?

youtube-dl version: 2015.03.09
OS: Windows 7, 64-bit
Full `--verbose` output:

    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: ['--ffmpeg-location', 'C:\\Scripts\\Utilities\\ffmpeg\\bin', '--verbose', '--write-sub', '--sub-format', 'srt', '--retries', '20', '-f', 'bestvideo+bestaudio', '-o', 'C:\\Users\\username\\Files\\junkFolder\\%(title)s_%(id)s_%(format)s_%(uploader_id)s_%(upload_date)s.%(ext)s', 'https://www.youtube.com/watch?v=thNZgEwQ2uQ']
    [debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
    [debug] youtube-dl version 2015.03.09
    [debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
    [debug] exe versions: ffmpeg N-70606-g2e5605f, ffprobe N-70606-g2e5605f
    [debug] Proxy map: {}
    [youtube] thNZgEwQ2uQ: Downloading webpage
    [youtube] thNZgEwQ2uQ: Extracting video information
    WARNING: video doesn't have subtitles
    [youtube] thNZgEwQ2uQ: Downloading DASH manifest
    [debug] Invoking downloader on 'https://r1---sn-2aqu-hoay.googlevideo.com/videoplayback?id=b61359804c10dae4&itag=137&source=youtube&requiressl=yes&ms=au&mv=m&mm=31&pl=21&ratebypass=yes&mime=video/mp4&gir=yes&clen=132763606&lmt=1394836998673921&dur=282.459&mt=1426087215&key=dg_yt0&sver=3&fexp=900237,907263,923384,927622,929305,934954,936112,9407432,9407565,9407642,942659,943917,948124,951703,952302,952612,952901,955301,957201,959701&signature=58FE71EC1ABB1B23446B9D71DC3FEA8E458B3732.08F4310BD013ED6078BDE9CFFC6CDC45AB1E81C2&upn=fu82u9YHRz4&ip=121.54.32.148&ipbits=0&expire=1426108929&sparams=ip,ipbits,expire,id,itag,source,requiressl,ms,mv,mm,pl,ratebypass,mime,gir,clen,lmt,dur'
    [download] Destination: C:\Users\username\Files\junkFolder\[]120505 (Rainbow) - A() _  ()_thNZgEwQ2uQ_137 - 1920x1080 (DASH video)_Darksnipercam_20120505.f137.mp4
    [download] 100% of 126.61MiB in 18:38
    [debug] Invoking downloader on 'https://r1---sn-2aqu-hoay.googlevideo.com/videoplayback?id=b61359804c10dae4&itag=141&source=youtube&requiressl=yes&ms=au&mv=m&mm=31&pl=21&ratebypass=yes&mime=audio/mp4&gir=yes&clen=9009401&lmt=1394834181623246&dur=282.563&mt=1426087215&key=dg_yt0&sver=3&fexp=900237,907263,923384,927622,929305,934954,936112,9407432,9407565,9407642,942659,943917,948124,951703,952302,952612,952901,955301,957201,959701&signature=7DA16EB526B9A2B8C93785AF0F559BAF124FEDBB.1A4758EA1B4DD476142E13C1E460F8AC884FB888&upn=fu82u9YHRz4&ip=121.54.32.148&ipbits=0&expire=1426108929&sparams=ip,ipbits,expire,id,itag,source,requiressl,ms,mv,mm,pl,ratebypass,mime,gir,clen,lmt,dur'
    [download] Destination: C:\Users\username\Files\junkFolder\[]120505 (Rainbow) - A() _  ()_thNZgEwQ2uQ_141 - audio only (DASH audio)_Darksnipercam_20120505.f141.m4a
    [download] 100% of 8.59MiB in 01:53
    [ffmpeg] Merging formats into "C:\Users\username\Files\junkFolder\[]120505 (Rainbow) - A() _  ()_thNZgEwQ2uQ_137 - 1920x1080 (DASH video)+141 - audio only (DASH audio)_Darksnipercam_20120505.mp4"
    [debug] ffmpeg command line: 'C:\Scripts\Utilities\ffmpeg\bin\ffmpeg' -y -i 'C:\Users\username\Files\junkFolder\[]120505 (Rainbow) - A() _  ()_thNZgEwQ2uQ_137 - 1920x1080 (DASH video)_Darksnipercam_20120505.f137.mp4' -i 'C:\Users\username\Files\junkFolder\[]120505 (Rainbow) - A() _  ()_thNZgEwQ2uQ_141 - audio only (DASH audio)_Darksnipercam_20120505.f141.m4a' -c copy -map 0:v:0 -map 1:a:0 'C:\Users\username\Files\junkFolder\[]120505 (Rainbow) - A() _  ()_thNZgEwQ2uQ_137 - 1920x1080 (DASH video)+141 - audio only (DASH audio)_Darksnipercam_20120505.mp4'

**Comment by dstftw** [comment] 2015-03-12 14:43
Duplicate of #5045.

**Closed by dstftw** 2015-03-12 14:43 UTC
