### ISSUE TITLE
401 error when attempting to download from soundcloud.

### ISSUE THREAD

**Issue by mralext20** [rg3/youtube-dl#6961] opened 2015-09-25 02:05 UTC
error log obtained from youtube -v:

```
$ youtube-dl https://soundcloud.com/westonemusicgroup/juicy-fruit-eds9 -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://soundcloud.com/westonemusicgroup/juicy-fruit-eds9', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.22
[debug] Python version 2.7.9 - Linux-3.19.0-30-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: ffmpeg 2.5.8-0ubuntu0.15.04.1, ffprobe 2.5.8-0ubuntu0.15.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[soundcloud] westonemusicgroup/juicy-fruit-eds9: Resolving id
[soundcloud] westonemusicgroup/juicy-fruit-eds9: Downloading info JSON
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 326, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1865, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

$ 
```

... i think there's a change in the sound cloud api.

using version 2015.09.22, just installed from the install instructions on one of the pages on here.

**Comment by dstftw** [comment] 2015-09-25 03:12
Duplicate of #6930.

**Closed by dstftw** 2015-09-25 03:12 UTC
