### ISSUE TITLE
error downloading .flv from tvcast.naver.com.

### ISSUE THREAD

**Issue by 1tntla** [rg3/youtube-dl#6789] opened 2015-09-07 14:47 UTC
Hello,

Here is a video url

http://tvcast.naver.com/v/444529

When I try to download the vid, the format is in flv and it threw an error saying that 

ERROR: RTMP download detected but "rtmpdump" could not be run. Please install it.

So I simply tried installing rtmpdump with homebrew and now it threw another error...

ERROR: rtmpdump exited with code 1

I'm stuck here and if someone could help me, it would be great.

Thanks,

**Comment by dstftw** [comment] 2015-09-07 14:50
Duplicate of #6744.

**Closed by dstftw** 2015-09-07 14:50 UTC
