### ISSUE TITLE
[Openload.io] Generic extractor not working anymore

### ISSUE THREAD

**Issue by wu5oeDah** [rg3/youtube-dl#6469] opened 2015-08-05 15:28 UTC
youtube-dl --verbose https://openload.io/f/ZAn6oz-VZGE/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://openload.io/f/ZAn6oz-VZGE/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.28
[debug] Python version 3.4.3 - Linux-4.1.4-1-ARCH-i686-with-arch
[debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] ZAn6oz-VZGE: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ZAn6oz-VZGE: Downloading webpage
[generic] ZAn6oz-VZGE: Extracting information
[debug] Invoking downloader on 'https://openload.io/f/ZAn6oz-VZGE/'
[download] Destination: The.Last.Witch.Hunter.2015.HD.720p.By.Rj.Rabasha.mp4 _ openload-.unknown_video
[download] 100% of 36.39KiB in 00:00

Openload.io was never a supported website but the generic extractor worked until a couple of days ago.
The downloaded file is in fact the html file of the webpage that can be opened with a text editor.
The direct link to the video is usually of this form : https://1cv9bay.dl.openload.io/dl/l/CbXZdGTXiKA/The.Last.Witch.Hunter.2015.HD.720p.By.Rj.Rabasha.mp4
I was hoping that it would be a good addition to the supported websites.

Thanks for your awesome work.

**Comment by remitamine** [comment] 2015-08-05 19:05
the generic extractor doesn't work now because open load change the place of the video url.
before(this format is supported by this part of code https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/generic.py#L1684):
```html
<source type="video/mp4" src="https://openload.io/stream/ZAn6oz-VZGE~1438887310~105.97.0.0~HizgVA4U?mime=true">
```
now:
```html
<source type="video/mp4" src="">
...
<script>$("video source").attr("src", "https:\/\/openload.io\/stream\/ZAn6oz-VZGE~1438887310~105.97.0.0~HizgVA4U?mime=true");</script>
```

**Comment by wu5oeDah** [comment] 2015-08-08 06:54
Thanks for the prompt reply.
Could the generic extractor be fixed to make it work again ?

**Comment by dstftw** [comment] 2016-02-10 15:42
Duplicate of #8489.

**Closed by dstftw** 2016-02-10 15:42 UTC
Labels: site-support-request

**Comment by yan12125** [comment] 2016-03-20 09:09
openload.io/openload.co videos will be supported in the next version.

**Comment by mystica555** [comment] 2016-04-24 22:04
I'm very interested to know openload's motivation for what appears to be a stream unique id, a url unique id, a user unique id, and IP supernet / unix timestamp to tie a user down to their url...

While watching Bomfunk MC's Freestyler video, I was reminded of the movie Click... Let's just say that I don't have $2.99 in any electronic monetary account today but that I will spend such when available to purchase the video from Amazon...

https://openload.co/stream/OC_jThTA8C0~1461620648~2601:280::~FrWqIhf8?mime=true
302's to

https://1fgm8jm.oloadcdn.net/dl/l/-7u3zObcJ-c/OC_jThTA8C0/Click.2006.720p.BluRay.x264.YIFY.mp4?mime=true

So you have unique IDs:
FrWqIhf8
OC_jThTA8C0
-7u3zObcJ-c
1fgm8jm 

unix timestamp 1461620648 and Comcast residential ipv6 supernet of 2601:280::

OC_jThTA8C0 is the video UID
FrWqIhf8 appears to be a userhash?
-7u3zObcJ-c appears to be a video temporary dir but not within the format of one generated by mkstmp.
1fgm8jm may be a random id for a url for tracking purposes; may be a random server correlation; may be a hash depending on the other datapoints.. Its just makes me curious..

**Comment by Hrxn** [comment] 2016-04-25 16:30
I understand the curiosity, but all this is only speculation in the end, sadly..
