### ISSUE TITLE
is it possible to download only desired time interval?

### ISSUE THREAD

**Issue by lapaci** [rg3/youtube-dl#4821] opened 2015-01-30 14:41 UTC
I want to download small part of a video which is 2 hours long and 1080p. How can i do that with youtube-dl?

**Comment by phihag** [comment] 2015-01-30 15:00
At the moment, there is no such functionality. This is quite complicated internally, because we need to find a table of which times correspond to which time intervals, interpret that table, download the partial file (that's actually the easy part), and then reassemble the whole shebang so that the headers are valid.

**Comment by corone17** [comment] 2015-01-30 22:02
You could try to let youtube-dl only generate the url and then feed that url to ffmpeg.
Something like this:
```batch
SET /P url=
FOR /F %%A IN ('youtube-dl.exe -g %url%') DO (
ffmpeg.exe -ss 00:41:55 -i "%%A" -c copy -t 00:03:00 output.mp4
)
```

**Comment by mannemvamsi** [comment] 2015-02-10 20:39
Thank You.. !!

**Comment by nixxquality** [comment] 2015-02-16 21:40
+1

Long Twitch videos can sometimes be upwards of 5 GiB or more, and if you just want watch a small part of them, you have to wait a long time to be able to even watch that.

**Comment by alexmatveev** [comment] 2015-04-28 21:39
@corone17 This command downloads a full video to /tmp files or somewhere, loads it for cutting OR it naturally retrieves a part of remote file?

**Comment by alexmatveev** [comment] 2015-04-28 21:55
@corone17 This doesn't worked with long videos http://www.youtube.com/watch?v=eyU3bRy2x44 :-(

**Comment by corone17** [comment] 2015-04-29 20:00
@alexmatveev I didn't actually test it 3 months ago, so you could try and run the following as a batch-file:
```batch
@ECHO off

:Input
ECHO.
SET url=
ECHO Enter Youtube-url:
SET /P url=
IF "%url%" EQU "" GOTO End
IF "%url: =%" NEQ "%url%" GOTO Input
ECHO Enter start time (in seconds, or in hh:mm:ss[.xxx] form):
SET /P start=
ECHO Enter duration (in seconds, or in hh:mm:ss[.xxx] form):
SET /P dur=
ECHO.
FOR /F "delims==" %%A IN ('youtube-dl.exe --no-warnings --get-filename "%url%"') DO SET filename=%%A
FOR /F %%B IN ('youtube-dl.exe -g "%url%"') DO (
ffmpeg.exe -hide_banner -ss "%start%" -i "%%B" -c copy -t "%dur%" "%filename%"
)
GOTO Input

:End
```
If you make sure youtube-dl.exe and ffmpeg.exe are in the same directory, then this will work fine for your 3hour fireplace video :p.
Youtube-dl.exe will generate the direct videolink. This link will be the input for ffmpeg, which will then only download the section you specify.

**Comment by jaimeMF** [comment] 2015-09-02 12:17
Closing as a duplicate of #622.

**Closed by jaimeMF** 2015-09-02 12:17 UTC

**Comment by sergiy-talashko** [comment] 2017-04-06 15:24
@Reino17 Could you please write a shell script? (for linux users)

**Comment by Reino17** [comment] 2017-04-06 15:45
I'm sorry, but I'm not a Linux user. I have very little experience with Linux's shell script.

**Comment by sergiy-talashko** [comment] 2017-04-06 15:58
@Reino17 Ok, still thanks

**Comment by andreikobe** [comment] 2017-11-02 11:07
i finally made an account because I'm desperate for a clipconverter dot cc alternative because they've recently made impossible restrictions to what they could download. Really hope you find a way :(

**Comment by KeithCu** [comment] 2018-01-31 06:07
I know this is a somewhat difficult feature, but it is a great one to add. Right now, I want to grab a 2 minute clip from a 3 gig video file! I'd love to be able to give you the -ss and -t flags like ffmpeg.

**Comment by josephomorrow** [comment] 2018-05-01 19:43
youtube-dl does have a --postprocessor-args command-line parameter. Example:

youtube-dl --postprocessor-args "-ss 00:13:00.00 -t 00:04:00.00" https://youtu.be/...

where -ss indicates start position (13 minutes in) and -t indicates new length (4 minutes) of output video. Just tried it with a 47-minute video that had about 4 hours of nothing on the end of it. I used --postprocessor-args "-t 00:47:00.0" and it worked fine.

**Comment by teocci** [comment] 2018-05-03 06:59
I know that this question is long but you can do it using this command:

```
ffmpeg -ss 3:59:10 -i $(youtube-dl -f 22 -g 'https://www.youtube.com/watch?v=mMZriSvaVP8') \
-t 3:06:00
```
You need to have the `ffmpeg` installed.

**Comment by josephomorrow** [comment] 2018-05-03 16:43
I was primarily giving a command-line-friendly solution. If your download speed is too slow, then what alternative would you suggest for downloading a smaller chunk of the original?

**Comment by Reino17** [comment] 2018-05-04 11:41
Very nice.
Lately I've become more and more familiar with Bash (although I'm still a Windows user), but some things are still new to me.
Does `${4:-best}` mean: default to "-best" if the 4th parameter is empty?
What does `${@:5}` exactly do/mean (the `@` in particular)?
You know the `$url`-assignment can be simplified by doing `$(youtube-dl -gf $fmt ${@:5} "$1")`?
Also note `Usage: youtube-dl.exe [OPTIONS] URL [URL...]` that options (officially) need to go before the url.

**Comment by noureddin** [comment] 2018-05-04 22:41
Thanks, Reino17.

`${4:-best}` returns the value of `$4` if it has a value, otherwise (if it's unset or null) the value after the `:-` is used, ie, `best`.  
This is one of the Parameter Expansions listed in `man bash`. ;)

`$@` is an array holding all the parameters passed to the function; ie, it's equivalent to `$1 $2 $3 ...`.  
`${@:5}` returns `$@` without the first four elements.

I preferred `--get-url` over `-g` mainly to be consistent with `--get-filename`, and also to be more readable, because it's not an option I use every day. But I've already used the short option `-f`. So I guess you're right.

I also forgot to add the format option to the get-filename command, because it can change the extension.

As I can't find a documentation for the urls-options order except what you mentioned, I will change the code to put the urls at the end. Thanks.

I also added the `-stats` option to ffmpeg to show the progress bar of the encoding. (It shows after some time; I guess it downloads the relevant segment first.)

For quieter output, you can remove `-stats`, and change `-loglevel warning` to `-loglevel quiet`.

```bash
download-clip() {
    # $1: url or Youtube video id
    # $2: starting time, in seconds, or in hh:mm:ss[.xxx] form
    # $3: duration, in seconds, or in hh:mm:ss[.xxx] form
    # $4: format, as accepted by youtube-dl (default: best)
    # other args are passed directly to youtube-dl; eg, -r 40K
    local fmt=${4:-best}
    local url="$(youtube-dl -g -f $fmt ${@:5} "$1")"
    local filename="$(youtube-dl --get-filename -f $fmt ${@:5} "$1")"
    ffmpeg -loglevel warning -hide_banner -stats \
        -ss $2 -i "$url" -c copy -t $3 "$filename"
    printf "Saved to: %s\n" "$filename"
    # based on Reino17's and teocci's comments in https://github.com/rg3/youtube-dl/issues/4821
}
```

**Comment by KeithCu** [comment] 2018-05-10 23:37
That's a great step. Do you think you could convert it to Python and submit it as a patch?

**Comment by noureddin** [comment] 2018-05-11 01:30
I am not familiar enough with youtube-dl source code to be able to make a patch, but I will try.

In the mean time, there are some other discussions about this feature, mainly: #8851, and #622.  
And johnhawkinson suggested a good idea in #12347, but it doesn't seem to work in all cases.

**Comment by estathop** [comment] 2018-09-17 12:44
any progress ?

**Comment by Adityagurati** [comment] 2020-11-28 12:49
> At the moment, there is no such functionality. This is quite complicated internally, because we need to find a table of which times correspond to which byte intervals, interpret that table, download the partial file (that's actually the easy part), and then reassemble the whole shebang so that the headers are valid.

its 2020 now 5 year passed since that comment. Is that feature available now to trim the youtube video and dounload the specific parts.Please reply ASAP

**Comment by brake4bots** [comment] 2021-02-20 20:58
I made the following batch file to make it easier for me to download all or part of video, select desired streams, and extract/convert audio. Hopefully, others will find it helpful as well.

@Echo Off
REM Requires YouTube-DL.exe and FFMPEG.exe
REM This script provides an easy way to select specific video and/or audio streams,
REM download all or part of a video and/or audio, and extract audio only to desired format
REM For Stream, entering, for example, 137+140, will copy video from 137 and audio from 140
REM By default, it selects bestvideo+bestaudio instead of "best" which is often far from best

Set URL=
Set Stream=bestvideo+bestaudio
Set Start=
Set Stop=
Set AF=
Set AQ=
Set Audio=
Set fn=title
REM Set fn=id

Echo.
Set /P URL="Enter video URL: "
If "%URL%"=="" Goto End

YouTube-DL -F "%URL%"

Echo.
Set /P Stream="Enter stream number(s) (n or n+n or Enter for bestvideo+bestaudio): "
Set /P start="Enter start time (in seconds or hh:mm:ss or Enter for 0): "
If Not "%Start%"=="" Set Start=-ss %Start%
Set /P Stop="Enter stop time (in seconds hh:mm:ss or Enter for end): "
If Not "%Stop%"=="" Set Stop=-to %Stop%
Set /P AF="Enter format to extract audio only (e.g. aac, mp3, or Enter to skip): "
If "%AF%"=="" Goto Process
Set Audio=-x --audio-format %AF%
Set /P AQ="Enter audio convert quality (e.g. 192K or Enter for default): "
If Not "%AQ%"=="" Set Audio=%Audio% --audio-quality %AQ%

:Process
If Not "%Start%%Stop%"=="" Goto PartialDownload
YouTube-DL -f %stream% -o "%%(%fn%)s.%%(ext)s" %Audio% "%URL%"
Goto End

:PartialDownload
YouTube-DL -f %stream% --external-downloader ffmpeg --external-downloader-args "%Start% %Stop%" -o "%%(%fn%)s.%%(ext)s" %Audio% "%URL%"
:End

**Comment by AtomicNess123** [comment] 2021-09-22 15:06
Does this download only the part of the video?

**Comment by LesFerch** [comment] 2021-09-22 15:35
Yes, if you choose the ffmpeg option.

But, please note the comment:

REM Using ffmpeg to download part of a video will only save time when
downloading a very small chunk.

For example, that option saved me time when downloading the first five
minutes of a two hour video. But selecting something like 15 minutes
actually took longer than the youtube-dl method. YMMV. Do some trial and
error testing to figure out the threshold for the video chunks you're
downloading.

I'd be interested to hear your results.

Les

**Comment by rhysperry111** [comment] 2022-02-18 09:21
Just for anyone reading this issue who wants a quick way to do it on Linux, you can use
```
youtube-dl -g VIDEO_URL | xargs -I{} ffmpeg -ss START_TIME -i "{}" -c copy -t FINISH_TIME OUTPUT_NAME
```

**Comment by AlexanderMatveev** [comment] 2022-02-18 09:31
> Just for anyone reading this issue who wants a quick way to do it on Linux, you can use
> 
> ```
> 
> youtube-dl -g VIDEO_URL | xargs -I{} ffmpeg -ss START_TIME -i "{}" -c copy -t FINISH_TIME OUTPUT_NAME
> 
> ```

This downloads full video and then crops it. A little off topic.

**Comment by rhysperry111** [comment] 2022-02-18 10:02
> > Just for anyone reading this issue who wants a quick way to do it on Linux, you can use
> > ```
> > 
> > youtube-dl -g VIDEO_URL | xargs -I{} ffmpeg -ss START_TIME -i "{}" -c copy -t FINISH_TIME OUTPUT_NAME
> > ```
> 
> This downloads full video and then crops it. A little off topic.

No it doesn't...

**Comment by AtomicNess123** [comment] 2022-02-18 11:08
> Just for anyone reading this issue who wants a quick way to do it on Linux, you can use
> 
> ```
> youtube-dl -g VIDEO_URL | xargs -I{} ffmpeg -ss START_TIME -i "{}" -c copy -t FINISH_TIME OUTPUT_NAME
> ```

Thanks! What would be the format of time? START_TIME = 2:30 (for 2 minutes 30 seconds)?

**Comment by rhysperry111** [comment] 2022-02-18 11:14
> Thanks! What would be the format of time? START_TIME = 2:30 (for 2 minutes 30 seconds)?

You can read the ffmpeg docs to see other ways of specifying time, but hh:mm:as works (00:02:30)

**Comment by AlexanderMatveev** [comment] 2022-02-18 11:41
> > This downloads full video and then crops it. A little off topic.
> 
> No it doesn't... try it yourself if you don't believe me. It's the same solution that @Reino17 provided, but adapted for linux

My doubt is caused by the fact that youtube-dl doesn't get the start timestamp. This means that the video will download from the beginning. In any case, the above command does not work: 

```
youtube-dl -g https://www.youtube.com/watch?v=L_LUpnjgPso | xargs -I{} ffmpeg -ss 01:02:00 -c copy -t 01:01:00 t.mp4
Output file #0 does not contain any stream
```

**Comment by AtomicNess123** [comment] 2022-02-18 13:04
> youtube-dl -g https://www.youtube.com/watch?v=L_LUpnjgPso | xargs -I{} ffmpeg -ss 01:02:00 -i "{}" -c copy -t 01:01:00 1.mp4

When I run this I get

`{}: No such file or directory`

**Comment by josch** [comment] 2022-07-25 13:08
Don't forget to put quotes around your `{}` because otherwise your shell will interpret them as special characters.

Since there seems to be some confusion here about how this works and because some people assume that this will download the whole video first and only split afterwards, let me explain how this works.

The `-g` option is short for `--get-url`: https://manpages.debian.org/bullseye/youtube-dl/youtube-dl.1.en.html#g, Running youtube-dl with it lets youtube-dl output a list of URLs, one per line. Each url can either be the URL to a video or the URL to an m3u or similar. So in case of downloading from twitch, just running `youtube-dl -g` without the xargs part will output a list of (but usually one) links to m3u files. These files are then all fed into ffmpeg and ffmpeg is then the one that actually follows the url and does the actual downloading. In case of twitch an m3u looks like this:

```
0#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:12
#ID3-EQUIV-TDTG:2022-07-25T00:24:04
#EXT-X-PLAYLIST-TYPE:EVENT
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TWITCH-ELAPSED-SECS:0.000
#EXT-X-TWITCH-TOTAL-SECS:46439.425
#EXTINF:11.912,
0.ts
#EXTINF:11.912,
1.ts
#EXTINF:11.912,
2.ts
#EXTINF:11.912,
3.ts
#EXTINF:11.912,
4.ts
#EXTINF:11.912,
5.ts
#EXTINF:11.912,
```

The `EXTINF` entries tell ffmpeg how long each of the `*.ts` files is so if you also pass the `-ss` option to ffmpeg, then ffmpeg can pick out and download exactly those videos that it needs and ignore the rest. You will see this from the ffmpeg output which will *not* start downloading with `0.ts` but will only start after some offset.

**Comment by AtomicNess123** [comment] 2022-07-26 08:16
> Don't forget to put quotes around your `{}` because otherwise your shell will interpret them as special characters.


`youtube-dl -g https://www.youtube.com/watch?v=L_LUpnjgPso | xargs -I"{}" ffmpeg -ss 01:02:00 -i "{}" -c copy -t 01:01:00 1.mp4`

With quotes around {} does not work either, same message `{}: No such file or directory`

**Comment by josch** [comment] 2022-07-26 08:19
@AtomicNess123 what's your operating system and your version of xargs?

**Comment by AtomicNess123** [comment] 2022-07-26 08:22
MacOS Catalina 10.15.7 
$FreeBSD: src/usr.bin/xargs/strnsubst.c,v 1.7 2004/10/18 15:40:47 cperciva Exp $
$FreeBSD: src/usr.bin/xargs/xargs.c,v 1.57 2005/02/27 02:01:31 gad Exp $

**Comment by josch** [comment] 2022-07-26 08:33
@AtomicNess123 it seems that some versions of freebsd xargs do not have the `-I` option. Compare:

https://www.freebsd.org/cgi/man.cgi?query=xargs&manpath=FreeBSD+4.0-RELEASE
https://www.freebsd.org/cgi/man.cgi?query=xargs&manpath=FreeBSD+14.0-current

Maybe you can fix your problem by getting a more modern version of xargs.

**Comment by AtomicNess123** [comment] 2022-07-30 09:06
I have been trying to find how to update xargs on my MAC, unsucessfully.

**Comment by josch** [comment] 2022-07-30 18:43
@AtomicNess123 depending on what you want to download, maybe you don't need xargs at all. Try running the first part, the `youtube-dl -g` part and see what it outputs. If it's just a single line, then you can feed that directly into ffmpeg without xargs. For example if I want to download parts of https://www.twitch.tv/videos/1541264505 then I run:

     youtube-dl -g https://www.twitch.tv/videos/1541264505

Which (in my case) outputs:

    https://d1ymi26ma8va5x.cloudfront.net/a5a005f82fc0c7a2bda8_taketv_39656269816_1658662201/chunked/index-dvr.m3u8

I can then plug that into ffmpeg directly instead of the `{}` like this:

    ffmpeg -ss 08:47:06 -i "https://d1ymi26ma8va5x.cloudfront.net/a5a005f82fc0c7a2bda8_taketv_39656269816_1658662201/chunked/index-dvr.m3u8" -c copy out.mp4

**Comment by mestrini** [comment] 2023-06-18 15:54
> Just for anyone reading this issue who wants a quick way to do it on Linux, you can use
> 
> ```
> youtube-dl -g VIDEO_URL | xargs -I{} ffmpeg -ss START_TIME -i "{}" -c copy -t FINISH_TIME OUTPUT_NAME
> ```

This worked out almost perfectly, except for the "FINISH_TIME" that should be "DURATION" since the flag "-t" is being used. Maybe that's why @AlexanderMatveev  was assuming the video was being downloaded in full as he was telling the program to download more than one hour of video.

The other issue I have is not getting audio from the stream selected by youtube-dl. Investigating now either how to merge or how the select a stream with audio

Thanks @rhysperry111

**Comment by dirkf** [comment] 2023-06-19 09:26
A cross-platform yt-dl solution involving `--external-downloader ffmpeg --external-downloader-args ...`, with no _xargs_, was shown in https://github.com/ytdl-org/youtube-dl/issues/4821#issuecomment-782748524, but the placement of the _ffmpeg_ arguments supplied in `--external-downloader-args ...` may be incorrect (relative to the `-i ...` argument(s)). yt-dlp has additional syntax to control this which might eventually be back-ported.
