### ISSUE TITLE
Youtube ExtractorError Could not download DASH manifest

### ISSUE THREAD

**Issue by paleyellowmoon** [rg3/youtube-dl#6181] opened 2015-07-09 05:13 UTC
C:\>youtube-dl -v https://www.youtube.com/watch?v=9-j6Sv83oKo
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=9-j6Sv83oKo']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.07.07
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-65404-gd34ec64, ffprobe N-65404-gd34ec64, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 9-j6Sv83oKo: Downloading webpage
[youtube] 9-j6Sv83oKo: Downloading video info webpage
[youtube] 9-j6Sv83oKo: Extracting video information
[youtube] {22} signature length 41.42, html5 player en_US-vfld2QbH7
[youtube] {43} signature length 41.42, html5 player en_US-vfld2QbH7
[youtube] {18} signature length 41.42, html5 player en_US-vfld2QbH7
[youtube] {5} signature length 41.42, html5 player en_US-vfld2QbH7
[youtube] {36} signature length 41.42, html5 player en_US-vfld2QbH7
[youtube] {17} signature length 41.42, html5 player en_US-vfld2QbH7
[youtube] {136} signature length 41.42, html5 player en_US-vfld2QbH7
[youtube] {247} signature length 41.42, html5 player en_US-vfld2QbH7
[youtube] {135} signature length 41.42, html5 player en_US-vfld2QbH7
[youtube] {244} signature length 41.42, html5 player en_US-vfld2QbH7
[youtube] {134} signature length 41.42, html5 player en_US-vfld2QbH7
[youtube] {243} signature length 41.42, html5 player en_US-vfld2QbH7
[youtube] {133} signature length 41.42, html5 player en_US-vfld2QbH7
[youtube] {242} signature length 41.42, html5 player en_US-vfld2QbH7
[youtube] {160} signature length 41.42, html5 player en_US-vfld2QbH7
[youtube] {140} signature length 41.42, html5 player en_US-vfld2QbH7
[youtube] {171} signature length 41.42, html5 player en_US-vfld2QbH7
[youtube] 9-j6Sv83oKo: Downloading DASH manifest
[youtube] 9-j6Sv83oKo: Downloading player https://s.ytimg.com/yts/jsbin/html5player-en_US-vfld2QbH7/
html5player.js
[youtube] 9-j6Sv83oKo: Downloading DASH manifest
WARNING: [youtube] 9-j6Sv83oKo: Skipping DASH manifest: ExtractorError(u'Could not download DASH man
ifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.
org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to cal
l youtube-dl with the --verbose flag and include its complete output.',)
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r12---sn-nwj7knl7.googlevideo.com/videoplayback?id=f7e8fa4af
f37a0aa&itag=247&source=youtube&requiressl=yes&mv=m&gcr=us&pl=20&ms=au&mn=sn-nwj7knl7&mm=31&ratebypa
ss=yes&mime=video/webm&gir=yes&clen=5118056&lmt=1426148857807641&dur=175.175&upn=GMvaXbsb5A4&signatu
re=09680742ABE2C5E90BA9A928632023D97CC90B7D.14DB697528A2F818605EF59C250082D6E417B866&sver=3&fexp=901
816,9407118,9408142,9408420,9408710,9409171,9412478,9412754,9412857,9416126,9416495,9416652,9417205&
key=dg_yt0&mt=1436418465&ip=73.15.198.139&ipbits=0&expire=1436440179&sparams=ip,ipbits,expire,id,ita
g,source,requiressl,mv,gcr,pl,ms,mn,mm,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Roy Ayers - Aragon-9-j6Sv83oKo.f247.webm
[download] 100% of 4.88MiB in 00:17
[debug] Invoking downloader on 'https://r12---sn-nwj7knl7.googlevideo.com/videoplayback?id=f7e8fa4af
f37a0aa&itag=141&source=youtube&requiressl=yes&mv=m&gcr=us&pl=20&ms=au&mn=sn-nwj7knl7&mm=31&ratebypa
ss=yes&mime=audio/mp4&gir=yes&clen=5588450&lmt=1419492145170580&dur=175.264&upn=GMvaXbsb5A4&signatur
e=1C657F18518C33F88CE59DA87F75D863CE9A3586.5945E18DE79CC23DE2F089578C8CD188E27D61CD&sver=3&fexp=9018
16,9407118,9408142,9408420,9408710,9409171,9412478,9412754,9412857,9416126,9416495,9416652,9417205&k
ey=dg_yt0&mt=1436418465&ip=73.15.198.139&ipbits=0&expire=1436440179&sparams=ip,ipbits,expire,id,itag
,source,requiressl,mv,gcr,pl,ms,mn,mm,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Roy Ayers - Aragon-9-j6Sv83oKo.f141.m4a
[download] 100% of 5.33MiB in 00:07
[ffmpeg] Merging formats into "Roy Ayers - Aragon-9-j6Sv83oKo.mkv"
[debug] ffmpeg command line: ffmpeg -y -i 'Roy Ayers - Aragon-9-j6Sv83oKo.f247.webm' -i 'Roy Ayers -
 Aragon-9-j6Sv83oKo.f141.m4a' -c copy -map 0:v:0 -map 1:a:0 'Roy Ayers - Aragon-9-j6Sv83oKo.temp.mkv
'
Deleting original file Roy Ayers - Aragon-9-j6Sv83oKo.f247.webm (pass -k to keep)
Deleting original file Roy Ayers - Aragon-9-j6Sv83oKo.f141.m4a (pass -k to keep)

**Comment by TheGr33k** [comment] 2015-07-09 05:28
Duplicate of #5118

**Comment by yan12125** [comment] 2015-07-09 07:40
Thanks @TheGr33k  . Closing.

**Closed by yan12125** 2015-07-09 07:40 UTC
