### ISSUE TITLE
Facebook wrong video downloaded

### ISSUE THREAD

**Issue by bt** [rg3/youtube-dl#10040] opened 2016-07-08 13:40 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.07.07*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v https://www.facebook.com/GoAnimalsOfficial/videos/1074872945893629
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.facebook.com/GoAnimalsOfficial/videos/1074872945893629']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.07
[debug] Python version 2.7.10 - Darwin-15.5.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[facebook] 1074872945893629: Downloading webpage
[debug] Invoking downloader on u'https://video-lax3-1.xx.fbcdn.net/v/t43.1792-2/13577625_1772886362930367_1065720990_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InN2ZV9oZCJ9&oh=d5e7d3afd62654769711f67fb879cd3f&oe=577FD207'
[download] Destination: Facebook video #1074872945893629-1074872945893629.mp4
[download] 100% of 2.01MiB in 00:05
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.facebook.com/GoAnimalsOfficial/videos/1074872945893629

---

### Description of your *issue*, suggested solution and other information

When downloading some videos from Facebook, I get other videos, from the same page, but not the one I requested. I assume this is because the matching is not correctly?

**Comment by dstftw** [comment] 2016-07-08 16:32
Duplicate of #9851.

**Closed by dstftw** 2016-07-08 16:32 UTC
