### ISSUE TITLE
8tracks download bug

### ISSUE THREAD

**Issue by monodeep12** [rg3/youtube-dl#7907] opened 2015-12-19 06:31 UTC
**Version** : `youtube-dl is up-to-date (2015.12.18)`

**Command** : `youtube-dl -f bestaudio --verbose http://8tracks.com/maurya-bendukuri/bollywood-mix`

**Output** : 
```[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-f', u'bestaudio', u'--verbose', u'http://8tracks.com/maurya-bendukuri/bollywood-mix']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.18
[debug] Python version 2.7.10 - Linux-3.16.0-56-generic-x86_64-with-debian-jessie-sid
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6
[debug] Proxy map: {}
[8tracks] bollywood-mix: Downloading webpage
[8tracks] bollywood-mix: Downloading song information 1/10
[8tracks] bollywood-mix: Downloading song information 2/10
[8tracks] bollywood-mix: Downloading song information 3/10
[8tracks] bollywood-mix: Downloading song information 4/10
[8tracks] bollywood-mix: Downloading song information 5/10
[8tracks] bollywood-mix: Waiting for 300 seconds
[8tracks] bollywood-mix: Downloading song information 5/10
[8tracks] bollywood-mix: Downloading song information 6/10
[8tracks] bollywood-mix: Waiting for 300 seconds
[8tracks] bollywood-mix: Downloading song information 6/10
[8tracks] bollywood-mix: Downloading song information 7/10
[8tracks] bollywood-mix: Waiting for 300 seconds
[8tracks] bollywood-mix: Downloading song information 7/10
[8tracks] bollywood-mix: Downloading song information 8/10
[8tracks] bollywood-mix: Waiting for 300 seconds
[8tracks] bollywood-mix: Downloading song information 8/10
ERROR: An extractor error has occured. (caused by KeyError(u'id',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/eighttracks.py", line 146, in _real_extract
    'id': compat_str(track_data['id']),
KeyError: u'id'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 663, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 296, in extract
    raise ExtractorError('An extractor error has occured.', cause=e)
ExtractorError: An extractor error has occured. (caused by KeyError(u'id',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.```

**Comment by dstftw** [comment] 2015-12-19 06:33
Duplicate of #5029.

**Closed by dstftw** 2015-12-19 06:33 UTC

**Comment by monodeep12** [comment] 2015-12-19 06:37
@dstftw  Is there a fix already?

**Comment by dstftw** [comment] 2015-12-19 06:38
No idea.
