### ISSUE TITLE
Request for MSNBC extractor

### ISSUE THREAD

**Issue by bonacker** [rg3/youtube-dl#6544] opened 2015-08-12 21:42 UTC
NBCNews, NBCSports, and NBCSportsVPlayer are supported, but MSNBC.com is the domain that NBC News uses for most of its videos, and it isn't supported by Youtube-dl. Supporting it would make NBC a much more useful site.

Btw, how do you add that "Site Support Request?" I don't see where you can add it to a post.

**Comment by dstftw** [comment] 2015-08-12 22:06
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by bonacker** [comment] 2015-08-13 01:39
http://www.msnbc.com/morning-joe/watch/clinton-to-turn-in-server--heres-what-it-means-502792771618

**Comment by yan12125** [comment] 2015-08-13 05:11
Duplicate of #2371.

**Closed by yan12125** 2015-08-13 05:11 UTC
