### ISSUE TITLE
Update uploaded video

### ISSUE THREAD

**Issue by marabu88** [rg3/youtube-dl#8564] opened 2016-02-14 21:09 UTC
I once wrote a similar request, but did not realize that YouTube videos often compresses better after some time, without changing the resolution. Following features would be very useful (for me at least;))

If the video is already uploaded - reload occurs. Is it possible to upload video, if the source has a higher quality / resolution than the uploaded? Is it possible to do it now with the help of simple manipulation or need to write a special program in a language like Python? Currently, I'm using a bat-file for all manipulations

**Comment by dstftw** [comment] 2016-02-14 21:39
youtube-dl is a downloader not an uploader. If hosted video best format changes just redownload it with youtube-dl.

**Comment by dstftw** [comment] 2016-02-15 18:36
So, the original request was to be able to redownload videos if they appear in a better quality some time later. For example, just released video at the time of downloading had the best quality of 720p but later 1080p appeared as well, the aim is to be able to redownload this video as 1080p.

**Comment by dstftw** [comment] 2016-02-15 18:56
There is already an issue for that opened. Closing as duplicate of #6861.

**Closed by dstftw** 2016-02-15 18:56 UTC
