### ISSUE TITLE
iqiyi download error

### ISSUE THREAD

**Issue by nqzhang** [rg3/youtube-dl#13112] opened 2017-05-17 04:37 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.14*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.14**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
 youtube-dl -v http://www.iqiyi.com/v_19rrhnkilg.html#vfrm=2-4-0-1
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.iqiyi.com/v_19rrhnkilg.html#vfrm=2-4-0-1']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.14
[debug] Python version 2.7.5 - Linux-4.1.5-x86_64-linode61-x86_64-with-centos-7.3.1611-Core
[debug] exe versions: ffmpeg 2.6.8, ffprobe 2.6.8
[debug] Proxy map: {}
[iqiyi] temp_id: download video page
[iqiyi] b960407548cb9eb3550869c0f7c47310: Downloading JSON metadata
ERROR: Unable to load data. Error code: A00110; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/iqiyi.py", line 364, in _real_extract
    raise ExtractorError('Unable to load data. Error code: ' + raw_data['code'])
ExtractorError: Unable to load data. Error code: A00110; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by yan12125** [comment] 2017-05-17 06:36
Duplicate of #10088. Some specific Iqiyi videos are not supported yet.

**Closed by yan12125** 2017-05-17 06:36 UTC

**Comment by denobisipsis** [comment] 2017-05-17 11:40
You must use 

http://cache.video.qiyi.com/vms?key=fvip&src=1702633101b340d8917a69cf8a4b8c7c&tvId=508850700&vid=ba3f3aba19610a46d55734663b8cde23&vinfo=1&tm=506&qyid=&puid=1405568913&authKey=4685682ee0104ea4d43541225d0ac38e&um=1&pf=b6c13e26323c537d&thdk=&thdt=&rs=1&k_tag=1&qdv=3&vf=54fee0cdde944b3d2c0295e50ec8e511

vf=md5+salt

**Comment by yan12125** [comment] 2017-05-17 11:45
@denobisipsis do you know what the salt is?

**Comment by denobisipsis** [comment] 2017-05-17 12:07
u6fnp3eok0dpftcq9qbr4n9svk8tqh7u

**Comment by denobisipsis** [comment] 2017-05-17 12:08
for ibt

t6hrq6k0n6n6k6qdh6tje6wpb62v7654
