### ISSUE TITLE
Pluralsight

### ISSUE THREAD

**Issue by accorreia123** [rg3/youtube-dl#6576] opened 2015-08-16 13:30 UTC
Hi

Is it possible to extend the features for downloding my own registered courses from pluralsight.com?

Regards
ac

**Comment by dstftw** [comment] 2015-08-16 13:42
Duplicate of #6090.

**Closed by dstftw** 2015-08-16 13:42 UTC

**Comment by dstftw** [comment] 2015-08-23 04:43
Pluralsight will be supported in the next version.

**Comment by invaserver** [comment] 2018-08-20 21:43
Works great :-)
